### ISSUE TITLE
Go indentation changed from tabs to two spaces

### ISSUE THREAD

**Issue by ijt** [wsdjeg/SpaceVim#1322]
## Expected behavior, english is recommended
When editing Go files, indentation should be done with tabs. That is how Go programmers do it, with few exceptions.

## Environment Information
- OS: Debian
- vim version:  8.0 
- neovim version: None

## The reproduce ways from Vim starting (Required!)
vi main.go
apackage main

func main() {
// Put cursor here, hit tab. Instead of a tab you get two spaces.
}
<img width="718" alt="screen shot 2018-01-23 at 9 36 16 pm" src="https://user-images.githubusercontent.com/15530/35316255-81c5db86-0085-11e8-8785-00c04a65c6f7.png">

### SpaceVim Options :                                                                               
                                                                                                     
```viml                                                                                              
g:spacevim_statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor m
ode lighters', 'version control info', 'hunks']                                                      
g:spacevim_enable_statusline_display_mode = 0                                                        
g:spacevim_enable_os_fileformat_icon = 0                                                             
g:spacevim_leader_guide_position = 'botright'                                                        
g:spacevim_version = '0.7.0-dev'                                                                     
g:spacevim_force_global_config = 0                                                                   
g:spacevim_smartcloseignoreft = ['help', 'tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'Spa
ceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal']                                 
g:spacevim_default_indent = 2                                                                        
g:spacevim_enable_javacomplete2_py = 0                                                               
g:spacevim_enable_powerline_fonts = 1                                                                
g:spacevim_statusline_separator = 'arrow'                                                            
g:spacevim_enable_language_specific_leader = 1                                                       
g:spacevim_warning_symbol = '⚠'                                                                      
g:spacevim_simple_mode = 0                                                                           
g:spacevim_colorscheme = 'gruvbox'                                                                   
g:spacevim_enable_guicolors = 1                                                                      
g:spacevim_custom_plugins = []                                                                       
g:spacevim_leader_guide_submode_mappings = {'<C-C>': 'win_close'}                                    
g:spacevim_buffer_index_type = 0                                                                     
g:spacevim_hiddenfileinfo = 1                                                                        
g:spacevim_statusline_inactive_separator = 'arrow'                                                   
g:spacevim_gitcommit_pr_icon = ''                                                                   
g:spacevim_plugin_manager = 'dein'                                                                   
g:spacevim_error_symbol = '✖'                                                                        
g:spacevim_vim_plug_installed = 0                                                                    
g:spacevim_windows_smartclose = 'q'                                                                  
g:spacevim_windows_leader = 's'                                                                      
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.gi
t,.svn,.hg,.DS_Store,*.svg'                                                                          
g:spacevim_use_colorscheme = 1                                                                       
g:spacevim_enable_ale = 0                                                                            
g:spacevim_enable_insert_leader = 1                                                                  
g:spacevim_enable_cursorcolumn = 0                                                                   
g:spacevim_colorscheme_bg = 'dark'                                                                   
g:spacevim_enable_neocomplcache = 0                                                                  
g:spacevim_leader_guide_sort_horizontal = 0                                                          
g:spacevim_enable_vimfiler_welcome = 1                                                               
g:spacevim_max_column = 120                                                                          
g:spacevim_enable_debug = 0                                                                          
g:spacevim_enable_key_frequency = 0                                                                  
g:spacevim_auto_disable_touchpad = 1                                                                 
g:spacevim_vim_help_language = 'en'                                                                  
g:spacevim_gitcommit_issue_icon = ''                                                                
g:spacevim_lint_on_save = 1                                                                          
g:spacevim_search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']                                          
g:spacevim_dein_installed = 1                                                                        
g:spacevim_autocomplete_method = 'neocomplete'                                                       
g:spacevim_enable_vimfiler_filetypeicon = 0                                                          
g:spacevim_plugin_manager_max_processes = 8                                                          
g:spacevim_statusline_unicode_symbols = 1                                                            
g:spacevim_statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']                     
g:spacevim_unite_leader = 'f'                                                                        
g:spacevim_enable_ycm = 0  

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
SpaceVim support editorconfig, maybe create a config file for editorconfig in the root of your project will be better.

**Comment by wsdjeg** [comment]
Ok, It is bug of spacevim, I will improve tha indent config in spacevim.

**Comment by wsdjeg** [comment]
I just fix this issue, if you want to use 4 space as default indent, you can add this to your config:

```vim
" by default it is 2
let g:spacevim_default_indent = 4
```

**Comment by ijt** [comment]
I might be misreading your change, but it looks like you didn't change it so that Go is always indented with tabs. If so, that's not going to work very well. Nearly all Go developers use actual tabs, not an equivalent number of spaces, when writing Go code. It's just what the Go community has agreed to do so they never have to argue about it again.

**Comment by wsdjeg** [comment]
how about：

```vim
let g:spacevim_default_indent = 4
let g:spacevim_expand_tab =0
```

**Comment by ijt** [comment]
I'm not sure I understand what you're proposing, but it looks like you're saying Go users should put that snippet into their SpaceVim config. If so, I completely disagree. What I'd like to see is that whenever SpaceVim opens a Go file, it uses actual tabs because that is how everyone indents Go files. Users should not have to add any configuration for that to work the way it's supposed to.

**Comment by wsdjeg** [comment]
I agree！ I will try to implement this feature in a better way.

**Comment by ijt** [comment]
👍

**Comment by wsdjeg** [comment]
@ijt this issue has be fixed, when loaded `lang#go` layer. 

at the start of a empty line, if you hit tab, a tab will be inserted. and by default we use noexpandtab for go file, this options was setted in vim-go plugin.

This is my SpaceVim config, and I use toml as default configuration file.

```toml
#=============================================================================
# init.vim --- My SpaceVim config
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
#=============================================================================

# SpaceVim options {{{
[options]
    default_indent = 4
    enable_debug = 1
    enable_ale = 0
    # enable_ycm = 1
    # snippet_engine = "ultisnips"
    line_on_the_fly = 0
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = 1
    enable_os_fileformat_icon = 1
    buffer_index_type = 0
    statusline_separator = 'arrow'
    github_username = 'wsdjeg'
    auto_disable_touchpad = 0
    colorscheme = 'gruvbox'
    guifont = 'DejaVu Sans Mono for Powerline 9'
# }}}

# SpaceVim layer config {{{
[[layers]]
name = 'denite'
[[layers]]
name = 'github'
[[layers]]
name = 'git'
[[layers]]
name = 'VersionControl'
[[layers]]
name = 'lang#go'
[[layers]]
name = 'lang#json'
[[layers]]
name = 'lang#java'
[[layers]]
name = 'lang#c'
[[layers]]
name = 'chat'
[[layers]]
name = 'tags'
[[layers]]
name = 'lang#toml'
[[layers]]
name = 'lang#lua'
[[layers]]
name = 'lang#php'
[[layers]]
name = 'lang#python'
[[layers]]
name = 'lang#vim'
[[layers]]
name = 'colorscheme'
[[layers]]
name = 'debug'
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"
[[layers]]
name = 'lang#markdown'
enableWcwidth = 1
listItemIndent = 1
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
# }}}

# custom plugins {{{
[[custom_plugins]]
neme = 'lilydjwg/colorizer'
merged = 0
#
```
