### ISSUE TITLE
neomake  not use local eslint or other local node_module 

### ISSUE THREAD

**Issue by aizigao** [wsdjeg/SpaceVim#1770]
## Expected behavior, english is required
local eslint can be used defined in package.json
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

![image](https://user-images.githubusercontent.com/14126445/40755235-21ef23b8-64b0-11e8-9465-a4e42b54f7bb.png)

## I tried 
this issue is the same as https://github.com/neomake/neomake/issues/247
I has add   ![nrun](https://github.com/jaawerth/nrun.vim) in init.toml , it works well

init.toml
```toml
...
[options]
    bootstrap_after =  "myspacevim#after"
...

[[custom_plugins]]
  name = 'jaawerth/nrun.vim'
```
myspacevim.vim
```vim
function! myspacevim#after() abort
  let g:neomake_javascript_eslint_exe = nrun#Which('eslint')
endfunction
```
![image](https://user-images.githubusercontent.com/14126445/40755271-514bd426-64b0-11e8-8bf3-6965878b6d2f.png)
