### ISSUE TITLE
Missing some <leader> binding according to document

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#2007]
## Expected behavior, english is required

In the [document](https://spacevim.org/documentation/#editor-ui), there are some key bindings begin with \<leader\>.  But currently, these key bindings don't work:

Key | Mode | Action
-- | -- | --
\<leader\>+cd | Normal | Switch to the directory of the open buffer
\<leader\>+w | Normal/visual | Write (:w)
\<leader\>+ts | Normal | Toggle spell-checker (:setlocal spell!)
\<leader\>+tn | Normal | Toggle line numbers (:setlocal nonumber!)
\<leader\>+tl | Normal | Toggle hidden characters (:setlocal nolist!)
\<leader\>+th | Normal | Toggle highlighted search (:set hlsearch!)
\<leader\>+tw | Normal | Toggle wrap (:setlocal wrap! breakindent!)

## Environment Information

- OS: linux
- vim version: 8.0.1638
- neovim version: -
- SpaceVim version: 0.9.0-dev
- SpaceVim status:

```
On branch master
Your branch is up to date with 'remotes/origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 1
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['christoomey/vim-tmux-navigator', {'lazy': 1, 'on_cmd': ['TmuxNavigateLeft', 'TmuxNavigateDown', 'TmuxNavigateUp', 'TmuxNavigateRight', 'TmuxNavigatePrevious']}], ['thawk/vim-asciidoc-folding', {'lazy': 1, 'on_ft': 'asciidoc'}], ['ConradIrwin/vim-bracketed-paste'], ['derekwyatt/vim-fswitch', {'lazy': 1, 'on_func': ['FSwitch'], 'on_cmd': ['FSHere', 'FSRight', 'FSSplitRight', 'FSLeft', 'FSSplitLeft', 'FSAbove', 'FSSplitAbove', 'FSBelow', 'FSSplitBelow']}], ['junkblocker/patchreview-vim', {'lazy': 1, 'on_cmd': ['PatchReview', 'PatchReviewPersist', 'ReversePatchReview', 'ReversePatchReviewPersist', 'DiffReview', 'DiffReviewPersist']}], ['vim-scripts/CodeReviewer.vim', {'lazy': 1, 'on_map': {'n': '<Plug>AddComment'}, 'on_cmd': ['CheckReview', 'SortReviewFile']}], ['lilydjwg/colorizer']]
  debug_level = 1
  default_indent = 4
  disabled_plugins = ['vim-gutentags']
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 1
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tanht/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'unite-tag'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = '~/workspace/'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '0.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#tmux"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#xml"
[[layers]]
  name="tools"
[[layers]]
  name="denite"
[[layers]]
  name="leaderf"
[[layers]]
  name="unite"
[[layers]]
  name="tags"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(vim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.
