### ISSUE TITLE
lang#puppet is not documented

### ISSUE THREAD

**Issue by igalic** [wsdjeg/SpaceVim#2040]
The Puppet Language Layer still exists and can be enabled with:

```toml
[[layers]]
name = 'lang#puppet'
```

 but it is currently not documented on https://spacevim.org/layers/
