### ISSUE TITLE
Not able to set the mapleader key by :let g:mapleader=","

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2051]
Here is my init.toml file.

```toml
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    statusline_right_sections = ['fileformat', 'cursorpos', 'percentage', 'date', 'time']
    # 状态栏右侧部分的构成

    vimcompatible = true
    # Vim将运行在与SpaceVim兼容模式运行
    default_indent = 4
    # 默认缩进长度
    expand_tab = 4
    # insert模式下tab键被扩展的长度
    # enable_googlesuggest = 1
    # 是否打开Google建议，默认不启用
    bootstrap_before = "linkun_spacevim#before"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30`
```

 "linkun_spacevim#before"
in this file, I mapped some keys.

But I am not to set the mapleader by :let g:mapleader=",".

When I press <SPC> h I to get the debug info,  I get the error below.
![spc_h_i_error](https://user-images.githubusercontent.com/5350867/44252802-06bd4f80-a230-11e8-832e-96bf831f6c17.png)
