### ISSUE TITLE
Error detected while processing function <SNR>93_on_install_exit:

### ISSUE THREAD

**Issue by brakchen** [wsdjeg/SpaceVim#2057]
## Error detected while processing function <SNR>93_on_install_exit:
This is an error when first load vim.

## The reproduce ways
Following are my steps to reshow the error:
Before that this is my system info:
```
$uname -r
3.16.0-6-amd64
$ cat  /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
1. install spacevim follow the instructions from [Quick start guide](https://spacevim.org/quick-start-guide/#linux-%E6%88%96-macos)

2. run `vim` on system

3.error will show up about 5s

## Debug info
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  atusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  able_os_fileformat_icon = 0
  ader_guide_position = 'botright'
  rsion = '0.9.0-dev'
  rce_global_config = 0
  artcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  fault_indent = 2
  able_key_frequency = 0
  able_javacomplete2_py = 0
  able_powerline_fonts = 1
  atusline_separator = 'arrow'
  rning_symbol = '?'
  mple_mode = 0
  lorscheme = 'gruvbox'
  pand_tab = 1
  able_guicolors = 1
  stom_plugins = []
  ader_guide_submode_mappings = {'<C-C>': 'win_close'}
  ffer_index_type = 0
  ddenfileinfo = 1
  atusline_inactive_separator = 'arrow'
  tcommit_pr_icon = '?'
  ugin_manager = 'neobundle'
  ror_symbol = '?'
  ndows_smartclose = 'q'
  ndows_leader = 's'
  ldignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  able_ale = 0
  able_cursorcolumn = 0
  lorscheme_bg = 'dark'
  able_neocomplcache = 0
  ader_guide_sort_horizontal = 0
  able_vimfiler_welcome = 1
  x_column = 120
  able_debug = 0
  able_insert_leader = 1
  to_disable_touchpad = 1
  m_help_language = 'en'
  tcommit_issue_icon = '?'
  nt_on_save = 1
  arch_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  tocomplete_method = 'neocomplcache'
  able_vimfiler_filetypeicon = 0
  atusline_unicode_symbols = 1
  ugin_manager_processes = 16
  atusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  able_ycm = 0
  able_tabline_filetype_icon = 0
  lorscheme_default = 'desert'
  oject_rooter_automatically = 1
  sabled_plugins = []
  ader_guide_max_size = 0
  ifont = ''
  fo_symbol = '?'
  ader_guide_flatten = 1
  debar_width = 30
  able_googlesuggest = 0
  nguage = ''
  able_neomake = 1
  ugin_bundle_dir = '/home/vagrant/.cache/vimfiles/'
  able_language_specific_leader = 1
  ader_guide_run_map_on_popup = 1
  sts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  lativenumber = 1
  ader_guide_default_group_name = ''
  mcompatible = 0
  artcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  altime_leader_guide = 1
  rminal_cursor_shape = 2
  ep_server_alive = 1
  ippet_engine = 'neosnippet'
  oject_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  tocomplete_parens = 1
  thub_username = ''
  ader_guide_hspace = 5
  eckinstall = 1
  ndows_index_type = 0
  letype_icons = {}
  ugin_name = 'vim-grepper'
  able_cursorline = 1
  stom_color_palette = []
  nt_on_the_fly = 0
  bug_level = 1
  able_statusline_mode = 0
  lemanager = 'vimfiler'
  c_root = 'E:\sources\'
  ader_guide_vertical = 0
  able_vimfiler_gitstatus = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(vim)
version: 704
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gik, or build from sources.
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:35:36] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [18:35:36] [ Info ] smart tab in autocomplete layer n

eed patch 7.4.774
```
</details>
## Screenshots

![snip20180818_74](https://user-images.githubusercontent.com/17734336/44296381-4f910900-a301-11e8-88a5-fac842b4c51c.png)
![snip20180818_77](https://user-images.githubusercontent.com/17734336/44296384-5750ad80-a301-11e8-9e87-701f302e5a00.png)
