### ISSUE TITLE
How to add local custom plugin

### ISSUE THREAD

**Issue by binguea** [wsdjeg/SpaceVim#2090]
I understand that one can add any plugin available on github via:

```toml
[[custom_plugins]]
    name = "lilydjwg/colorizer"
    on_cmd = ["ColorHighlight", "ColorToggle"]
    merged = 0
```

My question is if I have a plugin in my development area, say: ~/coding/vim/greatPlugin/

How to set it up in init.toml?
