### ISSUE TITLE
Although I have set the option "vim_help_language = 'cn'" in init.toml, the help docs is still in English.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2121]
Although I have set the option "vim_help_language = 'cn'" in init.toml, the help docs is still in English.

**Comment by wsdjeg** [comment]
@ssfjhh do you load `chinese` layer?

**Comment by xylinkun** [comment]
``` toml
[[layers]]
    name = "chinese"
    vim_help_language = 'cn'
``` 

Yeah, I have loaded `chinese` layer with the codes above.

**Comment by wsdjeg** [comment]
@ssfjhh `vim_help_language` is not layer option for chinese layer, it is global option. in current version of SpaceVim, you can use : 

```toml
[options]
    vim_help_language = "cn"

[[layers]]
    name = "chinese"
```

why do you change `vim_help_language` to layer option? because the available values of `vim_help_language`  is not only `cn`, for example it maybe `jp` if we add japanese layer.
