### ISSUE TITLE
TypeScript Layer Crashing with Unknown Error

### ISSUE THREAD

**Issue by PeterDing** [wsdjeg/SpaceVim#2138]
## Expected behavior, english is required
Neovim crashed too many times when I wrote a middle size project with typescript.
Neovim given me no log and error infos, it just crashed without any message.
This unknown error almost occurs at one code error check point.

## The reproduce ways from Vim starting (Required!)
I can not explicitly give you a way to reproduce this error, because it activates randomly.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.1
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['airblade/vim-gitgutter', {'name': 'airblade/vim-gitgutter', 'merged': 0}], ['vim-python/python-syntax', {'name': 'vim-python/python-syntax', 'merged': 0}], ['luochen1990/rainbow', {'name': 'luochen1990/rainbow', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/peter/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'unite-tag'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 1
  version = '0.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='smart'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#javascript"
  enable_flow_syntax=1
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#cscope"
[[layers]]
  name="lang#unite"
[[layers]]
  name="tags"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [01:09:30] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [01:09:31] [ Info ] Find project root('.git/',''):/Users/peter/dev/chord/.git/
[ SpaceVim ] [01:09:31] [ Info ] Find project root('package.json',''):/Users/peter/dev/chord/package.json
[ SpaceVim ] [01:09:31] [ Info ] change to root:/Users/peter/dev/chord
[ SpaceVim ] [01:09:31] [ Info ] Find project root('.git/','/Users/peter/dev/chord/NERD_tree_1'):/Users/peter/dev/chord/.git/
[ SpaceVim ] [01:09:31] [ Info ] Find project root('package.json','/Users/peter/dev/chord/NERD_tree_1'):/Users/peter/dev/chord/package.json
[ SpaceVim ] [01:09:31] [ Info ] change to root:/Users/peter/dev/chord
[ SpaceVim ] [01:09:33] [ Info ] change to root:/Users/peter/dev/chord
[ SpaceVim ] [01:09:34] [ Info ] Find project root('.git/','/Users/peter/dev/chord/src/chord/workbench/parts/player/browser/component/processBar.tsx'):/Users/peter/dev/chord/.git/
[ SpaceVim ] [01:09:34] [ Info ] Find project root('package.json','/Users/peter/dev/chord/src/chord/workbench/parts/player/browser/component/processBar.tsx'):/Users/peter/dev/chord/package.json
[ SpaceVim ] [01:09:34] [ Info ] change to root:/Users/peter/dev/chord
[ SpaceVim ] [01:09:43] [ Info ] Find project root('.git/','/Users/peter/dev/chord/SpaceVimLayers'):/Users/peter/dev/chord/.git/
[ SpaceVim ] [01:09:43] [ Info ] Find project root('package.json','/Users/peter/dev/chord/SpaceVimLayers'):/Users/peter/dev/chord/package.json
[ SpaceVim ] [01:09:43] [ Info ] change to root:/Users/peter/dev/chord
[ SpaceVim ] [01:10:02] [ Info ] change to root:/Users/peter/dev/chord
```
</details>

## Screenshots
<img width="790" alt="screen shot 2018-09-05 at 00 52 04" src="https://user-images.githubusercontent.com/670690/45046498-ebb06380-b0a8-11e8-9a98-5d6130bf13ef.png">
