### ISSUE TITLE
Displaying window number in Statusline causes error when starting i-edit mode

### ISSUE THREAD

**Issue by thedelchop** [wsdjeg/SpaceVim#2147]
## Expected behavior, english is required
I should be able to use i-edit mode while displaying the window number in my statusline.
## The reproduce ways from Vim starting (Required!)
Setup your statusline with only the window number displayed.  Open up a file and attempt to enter i-edit mode.  Before entering i-edit mode the following error message is displayed:

```
Error detected while processing function SpaceVim#plugins#iedit#start[41]..SpaceVim#layers#core#statusline#mode:
line    8:
E684: list index out of range: 8
E15: Invalid expression: 'hi! SpaceVim_statusline_a gui=bold cterm=bold ctermbg=' . t[8][3] . ' ctermfg=' . t[8][2] . ' guibg=' . t[8][1] . ' guifg=' . t[8][0]
```
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.1
- SpaceVim version: 0.9.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 0
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['lilydjwg/colorizer'], ['mxw/vim-jsx'], ['moll/vim-node'], ['keith/rspec.vim'], ['jparise/vim-graphql'], ['slim-template/vim-slim'], ['briancollins/vim-jst'], ['nikvdp/ejs-syntax'], ['mtth/scratch.vim']]
  debug_level = 1
  default_indent = 2
  denite_leader = 'f'
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 1
  enable_googlesuggest = 0
  enable_guicolors = v:true
  enable_insert_leader = v:true
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = v:true
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'thedelchop'
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = '🛈'
  keep_server_alive = 1
  language = 'en_US.UTF-8'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 110
  plugin_bundle_dir = '~/.cache/SpaceVim/plugins/'
  plugin_manager = 'dein'
  plugin_manager_max_processes = 8
  plugin_manager_processes = 16
  plugin_name = 'helpful.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', 'package.json']
  realtime_leader_guide = 1
  relativenumber = v:true
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_width = 40
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'vcs', 'hunks']
  statusline_right_sections = []
  statusline_separator = 'curve'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 1
  unite_leader = ''
  version = '0.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
  show_cursor_error=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="shell"
  default_shell='terminal'
  default_position='bottom'
  default_size=40
[[layers]]
  name="sudo"
[[layers]]
  name="tmux"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#vim"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [01:27:22] [ Info ] SpaceVim startup status is: [1, '/Users/thedelchop/Workspace/autoraptor']
[ SpaceVim ] [01:27:22] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [01:27:22] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [01:27:22] [ Info ] Find project root('.git/',''):/Users/thedelchop/Workspace/autoraptor/.git/
[ SpaceVim ] [01:27:22] [ Info ] change to root:/Users/thedelchop/Workspace/autoraptor
[ SpaceVim ] [01:27:22] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [01:27:22] [ Info ] change to root:/Users/thedelchop/Workspace/autoraptor
[ SpaceVim ] [01:27:23] [ Info ] Find project root('.git/','/Users/thedelchop/Workspace/autoraptor/app/models/upsheet.rb'):/Users/thedelchop/Workspace/autoraptor/.git/
[ SpaceVim ] [01:27:23] [ Info ] change to root:/Users/thedelchop/Workspace/autoraptor
[ SpaceVim ] [01:28:02] [ Info ] Find project root('.git/','/Users/thedelchop/Workspace/autoraptor/[denite]'):/Users/thedelchop/Workspace/autoraptor/.git/
[ SpaceVim ] [01:28:02] [ Info ] change to root:/Users/thedelchop/Workspace/autoraptor
[ SpaceVim ] [01:28:14] [ Info ] change to root:/Users/thedelchop/Workspace/autoraptor
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<img width="1440" alt="screenshot 2018-09-08 01 36 49" src="https://user-images.githubusercontent.com/119857/45250736-adfd4600-b307-11e8-9275-9d1c5e6e7dbd.png">
