### ISSUE TITLE
How to modify tab indentation.

### ISSUE THREAD

**Issue by lliuaotian** [wsdjeg/SpaceVim#2237]
Hello, my English is not good, so the next question I use is Google Translate. The question I want to ask is that I am used to tab indentation of 4 spaces, and Spacevim defaults to 2 indents. It makes me very headache, and the vertical line mark tab of Spacevim is also based on 2 spaces. I don't know how to modify it.

**Comment by wsdjeg** [comment]
It should be:

```toml
[options]
    default_indent = 8
    expand_tab = false
```

but I recommand to use editorconfig, this plugin has been included in SpaceVim.
