### ISSUE TITLE
Android Termux:'match-up must be loaded before matchit'

### ISSUE THREAD

**Issue by King-1025** [wsdjeg/SpaceVim#2239]
I want to install SpaceVim on my Android Termux.Unfortunately,I get the error below:
``` 
Error detected while processing 
/data/data/com.termux/files/home/.cache/vimfiles/repos/github.com/andymass/vim-
matchup/plugin/matchup.vim:                   line   32:                                         
match-up must be loaded before matchit
Press ENTER or type command to continue
``` 
My installation steps:
1.type:`curl -sLf https://spacevim.org/cn/install.sh | bash -s -- -i vim & vim` and Enter.Waiting 
for some time , I get that error.

I checked the file named `matchup.vim` and attempted to change it by guess.
> before(line:32):
```
if has('nvim')
   if exists(':MatchDebug')
      runtime! autoload/matchup/unmatchit.vim
  endif
elseif exists('g:loaded_matchit')
    echoerr 'match-up must be loaded before matchit'
    finish
endif
```
> after(line:32)
```
if has('nvim')
   if exists(':MatchDebug')
      runtime! autoload/matchup/unmatchit.vim
  endif
elseif $HOME =~ "termux"
      runtime! autoload/matchup/unmatchit.vim
elseif exists('g:loaded_matchit')
     echoerr 'match-up must be loaded before matchit'
     finish
endif
```
The result is that the error has gone.However,I don't know whether it will cause other problems.If you have any ideas, please leave your answer.Thank you!

## Environment Information

- OS: linux
- vim version: 8.1.300
- neovim version: -
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/data/data/com.termux/files/home/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimcdoc'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#java"
[[layers]]
  name="chinese"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/data/data/com.termux/files/usr/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/data/data/com.termux/files/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gik, or build from sources.
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:26:09] [ Info ] Startup with argv: ['matchup.vim']
[ SpaceVim ] [19:26:09] [ Info ] Start to find root for: /data/data/com.termux/files/home/.cache/vimfiles/repos/github.com/andymass/vim-matchup/plugin/matchup.vim
[ SpaceVim ] [19:26:09] [ Info ]         (.git/):/data/data/com.termux/files/home/.cache/vimfiles/repos/github.com/andymass/vim-matchup/.git/
[ SpaceVim ] [19:26:09] [ Info ] change to root:/data/data/com.termux/files/home/.cache/vimfiles/repos/github.com/andymass/vim-matchup
[ SpaceVim ] [19:26:09] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [19:26:11] [ Info ] change to root:/data/data/com.termux/files/home/.cache/vimfiles/repos/github.com/andymass/vim-matchup
[ SpaceVim ] [19:26:11] [ Info ] change to root:/data/data/com.termux/files/home/.cache/vimfiles/repos/github.com/andymass/vim-matchup
[ SpaceVim ] [19:26:25] [ Info ] Start to find root for: /data/data/com.termux/files/usr/tmp/voR9FKE/2/issue_report.md
```
</details>
