### ISSUE TITLE
failed to call bootstrap_before function: bootstrap_before#init

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#2244]
## Expected behavior, english is required
failed to call bootstrap_before function: bootstrap_before#init

## Environment Information

- OS: linux
- vim version: 8.0.1766
- neovim version: -
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'bootstrap_after#init'
  bootstrap_before = 'bootstrap_before#init'
  buffer_index_type = 1
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['wsdjeg/Chineselinter.vim', {'name': 'wsdjeg/Chineselinter.vim', 'merged': 0}], ['luochen1990/rainbow', {'name': 'luochen1990/rainbow', 'merged': 0}], ['ssfjhh/SearchCriteria', {'name': 'ssfjhh/SearchCriteria', 'merged': 0}], ['junegunn/vim-easy-align', {'name': 'junegunn/vim-easy-align'}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_line = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 1
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 4
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'ssfjhh'
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/linkun/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimtex'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'fileformat', 'minor mode lighters', 'version control info']
  statusline_right_sections = ['cursorpos', 'percentage', 'date', 'time']
  statusline_separator = 'slant'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = ''
  windows_smartclose = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  show_cursor_error=0
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="chinese"
[[layers]]
  name="git"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#latex"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:53:29] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [10:53:29] [ Info ] find local conf: /home/linkun/.SpaceVim.d/init.toml
[ SpaceVim ] [10:53:29] [ Info ] generate local conf: /home/linkun/.cache/SpaceVim/conf/_home_linkun__SpaceVim_d_init_toml.json
[ SpaceVim ] [10:53:29] [ Error ] failed to call bootstrap_before function: bootstrap_before#init
[ SpaceVim ] [10:53:29] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [10:53:29] [ Info ] Start to find root for: 
[ SpaceVim ] [10:53:29] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [10:53:29] [ Info ] Start to find root for: 
[ SpaceVim ] [10:53:29] [ Error ] failed to call bootstrap_after function: bootstrap_after#init
[ SpaceVim ] [10:53:32] [ Info ] Start to find root for: /home/linkun/.SpaceVim.d/init.toml
[ SpaceVim ] [10:54:34] [ Info ] Start to find root for: /home/linkun/.SpaceVim.d/init.toml
[ SpaceVim ] [10:56:14] [ Info ] Start to find root for: /tmp/vKsbKN6/2/issue_report.md
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
