### ISSUE TITLE
golang complete is too slow.

### ISSUE THREAD

**Issue by hilaily** [wsdjeg/SpaceVim#2258]
## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.1
- SpaceVim version: 0.9.0
- SpaceVim status: 

```
HEAD detached at v0.9.0
nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/Laily/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimcdoc'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '0.9.0'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="fzf"
[[layers]]
  name="VersionControl"
[[layers]]
  name="chinese"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/Cellar/neovim/0.3.1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:02:08] [ Info ] SpaceVim startup status is: [1, '/Users/Laily/go/src/prome-demo']
[ SpaceVim ] [20:02:08] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [20:02:10] [ Info ] Find project root('.git/',''):/Users/Laily/go/src/prome-demo/.git/
[ SpaceVim ] [20:02:10] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:10] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [20:02:10] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:27] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:28] [ Info ] Find project root('.git/','/Users/Laily/go/src/prome-demo/vimfiler:default'):/Users/Laily/go/src/prome-demo/.git/
[ SpaceVim ] [20:02:28] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:29] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:29] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:29] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:02:29] [ Info ] Find project root('.git/','/Users/Laily/go/src/prome-demo/export.go'):/Users/Laily/go/src/prome-demo/.git/
[ SpaceVim ] [20:02:29] [ Info ] change to root:/Users/Laily/go/src/prome-demo
[ SpaceVim ] [20:11:52] [ Info ] change to root:/Users/Laily/go/src/prome-demo
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

It cost about 1 second when completing. I can't write anymore. 
I had tried to install python3 and neovim, but the deoplete is not as good as this one.
System is macOS 10.13.4
