### ISSUE TITLE
[typescript] `TSRefs` window position is unacceptable.

### ISSUE THREAD

**Issue by PeterDing** [wsdjeg/SpaceVim#2267]
@wsdjeg @mhartington

## Expected behavior, english is required
I write a testing demo code to show this problem.

- src/main.ts
```typescript
'use strict';
import { abc } from './lib';
```

- src/lib.ts
```typescript
'use strict';
export function abc() {
    console.log('--');
}
```

When I use `TSRefs` command at `abc` function, the result window appears at right bottom (the ❹) of main window (it should be at ❷ position). As following shows:

<img width="759" alt="screen shot 2018-10-19 at 11 07 55 am" src="https://user-images.githubusercontent.com/670690/47196016-2b00ee00-d391-11e8-9c28-06a7116cd71f.png">

<img width="758" alt="screen shot 2018-10-19 at 11 07 12 am" src="https://user-images.githubusercontent.com/670690/47196020-381ddd00-d391-11e8-8d1f-2bfe727800f4.png">

## The reproduce ways from Vim starting (Required!)
see above.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.2
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['airblade/vim-gitgutter', {'name': 'airblade/vim-gitgutter', 'merged': 0}], ['vim-python/python-syntax', {'name': 'vim-python/python-syntax', 'merged': 0}], ['luochen1990/rainbow', {'name': 'luochen1990/rainbow', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/peter/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'unite-tag'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = 'right'
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 1
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### autoload/myspacevim.vim

```vim
func! myspacevim#before() abort

    " deoplete
    " {{{
    let g:deoplete#ignore_sources = {}
    let g:deoplete#ignore_sources._ = ['buffer', 'around']
    " }}}


    set virtualedit=onemore             " Allow for cursor beyond last character
    set splitright

    " {{{
    " vimfiler indentation length of tree
    " let g:vimfiler_tree_indentation = 2

    " open a NERDTree automatically when vim starts up if no files were specified
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    " }}}


    " clang-format
    let g:neoformat_c_clangformat = {
        \ 'exe': 'clang-format',
        \ 'stdin': 1,
        \ }
    let g:neoformat_javascript_jsbeautify = {
        \ 'exe': 'js-beautify',
        \ 'stdin': 1,
        \ }


    " auto indent
    " {|} ->
    " {
    "     |
    " }
    " let g:delimitMate_expand_cr = 1


    " Use H and L to move to the previous/next tabpage.
    " only work at normal mode
    nmap H [b
    nmap L ]b


    " go to $
    nmap g9 g$


    " python
    " {{{
    let g:python3_host_prog = '/Users/peter/.pyenv/versions/3.6.6/bin/python3.6'
    " python highlight
    let g:python_highlight_all = 1

    " To disable Python 2 support
    " let g:loaded_python_provider = 1

    " Add spaces after comment delimiters by default
    let g:NERDAltDelims_python = 1

    " jedi
    let g:jedi#force_py_version = 3
    let g:deoplete#sources#jedi#python_path = '/Users/peter/.pyenv/versions/3.6.6/bin/python3.6'
    " The completion is too slow!
    " 1. Completion of complex libraries (like Numpy) should only be slow the first time you complete them.
    " After that the results should be cached and very fast.
    " 
    " 2. If it is still slow after the initial completion and you have installed the python-mode Vim plugin,
    " try disabling its rope mode:
    let g:pymode_rope = 0
    " 3. You can also use deoplete-jedi for completions, which uses Jedi,
    " but does completions asynchronously (requires Neovim).
    " It makes sense to use both jedi-vim and deoplete-jedi,
    " but you should disable jedi-vim's completions then:
    let g:jedi#completions_enabled = 0
    " Python has the following checkers, among others: flake8, pyflakes, pylint and a native python checker.
    " To tell syntastic to use pylint, you would use this setting:
    " let g:syntastic_python_checkers = ['pylint']
    " let g:syntastic_python_pylint_exec = '/usr/local/bin/pylint'
    "
    " if you cannot get completions for large package such as pandas<Paste>
    let g:deoplete#sources#jedi#server_timeout = 60

    " SpaceVim use neomake for syntax checking
    " https://vi.stackexchange.com/a/9136
    let g:neomake_python_flake8_maker = {
        \ 'args': [
            \ '--ignore=E221,E241,E272,E251,E203,E201,E202,E265,,E303,E402,E302,E128,E226,E231,E501,W702',
            \ '--format=default'
        \ ],
        \ 'errorformat':
            \ '%E%f:%l: could not compile,%-Z%p^,' .
            \ '%A%f:%l:%c: %t%n %m,' .
            \ '%A%f:%l: %t%n %m,' .
            \ '%-G%.%#',
        \ }
    let g:neomake_python_enabled_makers = ['flake8']
    " }}}


    " rust.vim
    " {{{
    let g:rustfmt_autosave = 1
    let g:rustfmt_options = '-f'
    " for CompleteParameter.vim
    " let g:racer_experimental_completer = 1

    au FileType rust nmap hd <Plug>(rust-def)
    au FileType rust nmap hs <Plug>(rust-def-split)
    au FileType rust nmap hv <Plug>(rust-def-vertical)
    au FileType rust nmap ho <Plug>(rust-doc)
    " }}}


    " show all uncompliable symbols
    set listchars=tab:>-,trail:~,extends:>,precedes:<
    set list


    " rainbow
    let g:rainbow_active = 1

    " javascript
    let g:tern#command = ["tern"]
    let g:tern#arguments = ["--persistent"]


    " typescript
    let g:tagbar_type_typescript = {
        \ 'ctagstype': 'typescript',
        \ 'kinds': [
          \ 'c:classes',
          \ 'n:modules',
          \ 'f:functions',
          \ 'v:variables',
          \ 'v:varlambdas',
          \ 'm:members',
          \ 'i:interfaces',
          \ 'e:enums',
          \ 's:statics',
        \ ]
    \ }


    " disable ctags
    let g:gutentags_ctags_exclude = [ "*.js", "*.jsx", "*.ts", "*.tsx", "*.css", "build", "vendor", ".git", "node_modules", "*.vim/bundle/*", "out" ]

endf


" func! myspacevim#after() abort
" endf
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='smart'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="denite"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#javascript"
  enable_flow_syntax=1
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#cscope"
[[layers]]
  name="lang#unite"
[[layers]]
  name="tags"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/Users/peter/.local/nvim-osx64/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:03:33] [ Info ] Startup with no argv, current dir is used: /private/tmp/t/test
[ SpaceVim ] [11:03:33] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [11:03:33] [ Info ] Start to find root for: 
[ SpaceVim ] [11:03:33] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [11:03:33] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:04:04] [ Info ] Start to find root for: /private/tmp/t/test/src/main.ts
[ SpaceVim ] [11:04:49] [ Info ] Start to find root for: /private/tmp/t/test/src/main.ts
[ SpaceVim ] [11:04:50] [ Info ] Start to find root for: 
[ SpaceVim ] [11:04:51] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:04:52] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:05:14] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:05:14] [ Info ] Start to find root for: 
[ SpaceVim ] [11:05:17] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:05:18] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:05:59] [ Info ] Start to find root for: /private/tmp/t/test/src/main.ts
[ SpaceVim ] [11:06:01] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:06:04] [ Info ] Start to find root for: /private/tmp/t/test/src/main.ts
[ SpaceVim ] [11:06:06] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:06:10] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:10] [ Info ] Start to find root for: 
[ SpaceVim ] [11:06:13] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:22] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:06:24] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:24] [ Info ] Start to find root for: 
[ SpaceVim ] [11:06:28] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:31] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:06:43] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:43] [ Info ] Start to find root for: 
[ SpaceVim ] [11:06:45] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:46] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:06:51] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:51] [ Info ] Start to find root for: 
[ SpaceVim ] [11:06:53] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:54] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:06:54] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:06:54] [ Info ] Start to find root for: 
[ SpaceVim ] [11:07:31] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:07:33] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:14:09] [ Info ] Start to find root for: /private/tmp/t/test/src/main.ts
[ SpaceVim ] [11:14:39] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:20:47] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:20:47] [ Info ] Start to find root for: 
[ SpaceVim ] [11:20:53] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:21:02] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:21:03] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:21:03] [ Info ] Start to find root for: 
[ SpaceVim ] [11:24:37] [ Info ] Start to find root for: /private/tmp/t/test/NERD_tree_1
[ SpaceVim ] [11:24:37] [ Info ] Start to find root for: /private/tmp/t/test/src/lib.ts
[ SpaceVim ] [11:24:46] [ Info ] Start to find root for: /var/folders/v5/jxt3nz9964j15xw3rxxc_3ph0000gn/T/nvim3vTbK7/7/issue_report.md
```
</details>
