### ISSUE TITLE
Jedi pydoc shift-k is intefered by SpaceVim. OK with vimr and minimized vimrc

### ISSUE THREAD

**Issue by monkeyxite** [wsdjeg/SpaceVim#2271]
## Expected behavior, english is required

When shift-k to get pydoc output, jedi report some kind of initial error (refer to **Output of “:verbose JediDebugInfo”**) due to environment not set .

Everything goes well with belowing vimrc (minimized version suggested by vim-jedi / within vimr with excatly SpaceVim config.
```
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
" let g:jedi#show_call_signatures=1

syntax on
filetype plugin indent on
```

##### jedi-vim version

 - jedi-vim git version: 0.9.0-60-gb6dfc5f-dirty
 - jedi git submodule status: +02f238ce08f2d7f9c4af9a17cbf5754836775e2f pythonx/jedi (v0.11.1)
 - parso git submodule status: +2ca629a2f6db2e905ddd5188113b1045f8a00fc2 pythonx/parso (v0.1.1)

##### Global Python

Using Python version 2 to access Jedi.
 - global sys.version: `2.7.14 (default, Jan  6 2018, 12:12:40), [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
 - global site module: `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc`

##### Jedi

 - path: `/Users/monkeyxite/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi/jedi/__init__.pyc`
 - version: 0.11.1
 - sys_path:
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python27.zip`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload`
    - `/Users/monkeyxite/Library/Python/2.7/lib/python/site-packages`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`
    - `/usr/local/Cellar/matplotlib/1.4.3/libexec/lib/python2.7/site-packages`
    - `/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0`
    - `/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa`
    - `_vim_path_`
                  Error detected while processing function <SNR>185_jedi_debug_info[12]..jedi#debug_info:
line   32:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/monkeyxite/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi_vim_debug.py", line 81, in display_debug_info
    if environment:
UnboundLocalError: local variable 'environment' referenced before assignment

## Environment Information

- OS: mac
- vim version: 8.1.280
- neovim version: -
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'completor'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['szymonmaszke/vimpyter', {'name': 'szymonmaszke/vimpyter'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Droid Sans Mono Nerd Font Complete:h12'
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/monkeyxite/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-fugitive'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="tools#dash"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#python"
[[layers]]
  name="git"
[[layers]]
  name="fzf"
[[layers]]
  name="github"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/HEAD-20d6ca2/MacVim.app/Contents/MacOS/Vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gik, or build from sources.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [22:28:43] [ Info ] Startup with argv: ['GetImgTool.py', 'GetQuestionTessAndroid.py', 'GetQuestionTessIos.py', '__init__.py']
[ SpaceVim ] [22:28:43] [ Info ] Start to find root for: /Volumes/MacMini/design/localAPP/TopSup/GetImgTool.py
[ SpaceVim ] [22:28:43] [ Info ]         (.git/):/Volumes/MacMini/design/localAPP/TopSup/.git/
[ SpaceVim ] [22:28:43] [ Info ] change to root:/Volumes/MacMini/design/localAPP/TopSup
[ SpaceVim ] [22:28:43] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [22:28:43] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [22:28:47] [ Info ] change to root:/Volumes/MacMini/design/localAPP/TopSup
[ SpaceVim ] [22:28:47] [ Info ] change to root:/Volumes/MacMini/design/localAPP/TopSup
[ SpaceVim ] [22:29:01] [ Info ] Start to find root for: /Volumes/MacMini/design/localAPP/TopSup/GetQuestionTessAndroid.py
[ SpaceVim ] [22:29:01] [ Info ]         (.git/):/Volumes/MacMini/design/localAPP/TopSup/.git/
[ SpaceVim ] [22:29:01] [ Info ] change to root:/Volumes/MacMini/design/localAPP/TopSup
[ SpaceVim ] [22:34:44] [ Info ] Start to find root for: /var/folders/nd/ysj85j0n6d5dxwz6611x50ph0000gn/T/vVn19ZC/10/issue_report.md
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
