### ISSUE TITLE
neomake errors when opening java project

### ISSUE THREAD

**Issue by LifelongNovember** [wsdjeg/SpaceVim#2280]
Writing any character in a java source file:
```
Error detected while processing function <SNR>99_neomake_automake[36]..<SNR>99_configure_buffer[31]..neomake#GetEnabledMakers[35]..neomake#map_makers[6]..neomake#GetMaker[9]..neomake#get_mak
er_by_name[13]..<SNR>242_GetMakerForFiletype[5]..neomake#makers#ft#java#javac[32]..<SNR>331_ReadClassPathFile:
line    6:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <SNR>99_neomake_automake[36]..<SNR>99_configure_buffer[31]..neomake#GetEnabledMakers[35]..neomake#map_makers[6]..neomake#GetMaker[9]..neomake#get_mak
er_by_name[13]..<SNR>242_GetMakerForFiletype[5]..neomake#makers#ft#java#javac[32]..<SNR>331_ReadClassPathFile:
line    6:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <SNR>99_neomake_automake[36]..<SNR>99_configure_buffer[31]..neomake#GetEnabledMakers[35]..neomake#map_makers[6]..neomake#GetMaker[9]..neomake#get_mak
er_by_name[13]..<SNR>242_GetMakerForFiletype[5]..neomake#makers#ft#java#javac[32]..<SNR>331_ReadClassPathFile:
line    6:
vim.error: Vim:E121: Undefined variable: a:classpathFile
Press ENTER or type command to continue
Error detected while processing function <SNR>99_neomake_automake[36]..<SNR>99_configure_buffer[31]..neomake#GetEnabledMakers:
line   35:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>99_neomake_automake[36]..<SNR>99_configure_buffer:
line   31:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>99_neomake_automake:
line   36:
E171: Missing :endif
Press ENTER or type command to continue	
```
## Expected behavior, english is required

Upon opening vim inside root of a java project, neomake should initialize classpath as explained here: https://spacevim.org/use-vim-as-a-java-ide/#syntax-lint

## Environment Information

- OS: linux
- vim version: 8.1.470
- neovim version: -
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

On a relatively fresh archlinux installation (a few days old), after reinstalling Spacevim completely with theses commands :

```
$ rm -rf ~/.vim* ~/.config/*vim* ~/.config/*Vim* ~/.SpaceVim* ~/.cache/*vim* ~/.cache/*Vim* ~/.cache/neosnippet ~/.local/share/*vim*
$ mkdir -p ~/.local/share/nvim/shada
$ curl -sLf https://spacevim.org/install.sh | bash
```

I launch vim for the first time, it asks me which mode should be used (I select dark mode). Then, it leaves me with an empty buffer and I have to restart vim in order to install packages. After enabling lang#java layer, I cd to the root of my java project, reopen vim, select my file in vimfiler and, whenever I save changes (or simply change the file with lint_on_the_fly enabled), these neomake errors appear.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/novambre/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-java'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:48:34] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [13:48:34] [ Info ] Startup with no argv, current dir is used: ~/Modèles/dijkstra
[ SpaceVim ] [13:48:34] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [13:48:34] [ Info ] Start to find root for: 
[ SpaceVim ] [13:48:34] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [13:48:34] [ Info ] Start to find root for: 
[ SpaceVim ] [13:48:41] [ Info ] Start to find root for: /tmp/vXDYORa/4/issue_report.md
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
