### ISSUE TITLE
Vim unite window, <c-s> can't split the file. But in nvim, it works.

### ISSUE THREAD

**Issue by 812lcl** [wsdjeg/SpaceVim#2283]
## Expected behavior, english is recommend
Vim unite window, <c-s> can't split the file. But in nvim, it works.
## Environment Information

- OS: mac
- vim version: 8.1.450
- neovim version: -
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#init'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'neosolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['skywind3000/vim-keysound', {'name': 'skywind3000/vim-keysound'}], ['wakatime/vim-wakatime', {'name': 'wakatime/vim-wakatime'}], ['gorodinskiy/vim-coloresque', {'name': 'gorodinskiy/vim-coloresque'}], ['812lcl/gutentags_plus', {'name': '812lcl/gutentags_plus'}], ['osyo-manga/vim-anzu', {'name': 'osyo-manga/vim-anzu'}], ['rdnetto/YCM-Generator', {'name': 'rdnetto/YCM-Generator'}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 1
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 0
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 1
  enable_statusline_mode = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = '812lcl'
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/812lcl/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'xmledit'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.gitignore', '.clang', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 2
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='smart'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="unite"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="chinese"
[[layers]]
  name="sudo"
[[layers]]
  name="tags"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
[[layers]]
  name="VersionControl"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#xml"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [21:41:18] [ Info ] Startup with argv: ['autoload/SpaceVim/default.vim']
[ SpaceVim ] [21:41:18] [ Info ] Start to find root for: /Users/812lcl/.SpaceVim/autoload/SpaceVim/default.vim
[ SpaceVim ] [21:41:18] [ Info ]         (.git/):/Users/812lcl/.SpaceVim/.git/
[ SpaceVim ] [21:41:18] [ Info ]         (.SpaceVim.d/):/Users/812lcl/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [21:41:18] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:18] [ Info ] find local conf: /Users/812lcl/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [21:41:18] [ Info ] force loadding global config >>>
[ SpaceVim ] [21:41:18] [ Info ] YCM only support ultisnips, change g:spacevim_snippet_engine to ultisnips
[ SpaceVim ] [21:41:18] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:18] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:19] [ Info ] Start to find root for: 
[ SpaceVim ] [21:41:19] [ Info ]         (.git/):/Users/812lcl/.SpaceVim/.git/
[ SpaceVim ] [21:41:19] [ Info ]         (.gitignore):/Users/812lcl/.SpaceVim/.gitignore
[ SpaceVim ] [21:41:19] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:20] [ Info ] Start to find root for: /Users/812lcl/.SpaceVim/[unite] - default
[ SpaceVim ] [21:41:20] [ Info ]         (.git/):/Users/812lcl/.SpaceVim/.git/
[ SpaceVim ] [21:41:20] [ Info ]         (.gitignore):/Users/812lcl/.SpaceVim/.gitignore
[ SpaceVim ] [21:41:20] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:25] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:27] [ Info ] Start to find root for: 
[ SpaceVim ] [21:41:27] [ Info ]         (.git/):/Users/812lcl/.SpaceVim/.git/
[ SpaceVim ] [21:41:27] [ Info ]         (.gitignore):/Users/812lcl/.SpaceVim/.gitignore
[ SpaceVim ] [21:41:27] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:40] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:41] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:43] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:44] [ Info ] Start to find root for: /Users/812lcl/.SpaceVim/.SpaceVim.d/autoload/SpaceVim/dev/z.vim
[ SpaceVim ] [21:41:44] [ Info ]         (.git/):/Users/812lcl/.SpaceVim/.git/
[ SpaceVim ] [21:41:44] [ Info ]         (.gitignore):/Users/812lcl/.SpaceVim/.gitignore
[ SpaceVim ] [21:41:44] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:45] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:48] [ Info ] Start to find root for: 
[ SpaceVim ] [21:41:48] [ Info ]         (.git/):/Users/812lcl/.SpaceVim/.git/
[ SpaceVim ] [21:41:48] [ Info ]         (.gitignore):/Users/812lcl/.SpaceVim/.gitignore
[ SpaceVim ] [21:41:48] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:51] [ Info ] change to root:/Users/812lcl/.SpaceVim
[ SpaceVim ] [21:41:54] [ Info ] Start to find root for: /var/folders/n5/pbszzkk572g_qtmg7sy_jfs40000gn/T/vjp7xed/9/issue_report.md
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
