### ISSUE TITLE
Disabling delimitMate causes VIM to freeze

### ISSUE THREAD

**Issue by mgoffin** [wsdjeg/SpaceVim#2290]
When you disable delimitMate, and attempt to type `(` while in Insert mode, VIM will freeze. This was noted in #1919 but still happens.

## Expected behavior, english is required

Disabling delimitMate results in VIM working and delimitMate being disabled.

## The reproduce ways from Vim starting (Required!)

Add the following to `[options]`:

```
 disabled_plugins = ["delimitMate"]
```

## Environment Information

- OS: mac
- vim version: 8.1.400
- neovim version: -
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   autoload/SpaceVim/mapping/guide/theme/one.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'one'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 1
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/mgoffin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-hybrid'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  spacevim_autocomplete_parens=0
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  show_cursor_error=0
  enable_ale=0
  lint_on_the_fly=1
  enable_neomake=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
[[layers]]
  name="denite"
[[layers]]
  name="colorscheme"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/bin/vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:52:53] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [10:52:53] [ Info ] find local conf: /Users/mgoffin/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [10:52:53] [ Info ] force loadding global config >>>
[ SpaceVim ] [10:52:53] [ Info ] Start to find root for: 
[ SpaceVim ] [10:52:53] [ Info ]         (.git/):/Users/mgoffin/.SpaceVim/.git/
[ SpaceVim ] [10:52:53] [ Info ]         (.SpaceVim.d/):/Users/mgoffin/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [10:52:53] [ Info ] change to root:/Users/mgoffin/.SpaceVim
[ SpaceVim ] [10:52:53] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [10:52:53] [ Info ] change to root:/Users/mgoffin/.SpaceVim
[ SpaceVim ] [10:52:55] [ Info ] Start to find root for: 
[ SpaceVim ] [10:52:55] [ Info ]         (.git/):/Users/mgoffin/.SpaceVim/.git/
[ SpaceVim ] [10:52:55] [ Info ]         (.SpaceVim.d/):/Users/mgoffin/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [10:52:55] [ Info ] change to root:/Users/mgoffin/.SpaceVim
[ SpaceVim ] [10:52:58] [ Info ] Start to find root for: /Users/mgoffin/.SpaceVim.d/init.toml
[ SpaceVim ] [10:54:30] [ Info ] Start to find root for: /Users/mgoffin/.SpaceVim/SpaceVimLayers
[ SpaceVim ] [10:54:30] [ Info ]         (.git/):/Users/mgoffin/.SpaceVim/.git/
[ SpaceVim ] [10:54:30] [ Info ]         (.SpaceVim.d/):/Users/mgoffin/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [10:54:30] [ Info ] change to root:/Users/mgoffin/.SpaceVim
[ SpaceVim ] [10:55:15] [ Info ] Start to find root for: /Users/mgoffin/.SpaceVim.d/init.toml
[ SpaceVim ] [10:55:24] [ Info ] Start to find root for: /Users/mgoffin/.SpaceVim/SpaceVimLayers
[ SpaceVim ] [10:55:24] [ Info ]         (.git/):/Users/mgoffin/.SpaceVim/.git/
[ SpaceVim ] [10:55:24] [ Info ]         (.SpaceVim.d/):/Users/mgoffin/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [10:55:24] [ Info ] change to root:/Users/mgoffin/.SpaceVim
[ SpaceVim ] [10:55:36] [ Info ] Start to find root for: /Users/mgoffin/.SpaceVim.d/init.toml
[ SpaceVim ] [10:55:47] [ Info ] Start to find root for: /var/folders/_9/n2ntj5396bbbcpll_yd20kk80000gp/T/v68mFA3/2/issue_report.md
```
