### ISSUE TITLE
I just lost part of the syntax highlighting when formatting a regular vue file.

### ISSUE THREAD

**Issue by kunish** [wsdjeg/SpaceVim#2305]
## Expected behavior, english is required
When I hit SPC b f, I want to format my code without losing syntax highlighting.
## The reproduce ways from Vim starting (Required!)
Open a *.vue file, go down half of the file to the part which next to the end of template and script tag.
Do some editing and exit to normal mode. Hit SPC b f (Format buffer text).
## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.2
- SpaceVim version: 1.0.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  background = 'dark'
  bootstrap_after = 'config#after'
  bootstrap_before = 'config#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = [['matze/vim-move', {'name': 'matze/vim-move'}], ['vim-scripts/ReplaceWithRegister', {'name': 'vim-scripts/ReplaceWithRegister'}], ['mhinz/vim-signify', {'name': 'mhinz/vim-signify'}], ['wellle/targets.vim', {'name': 'wellle/targets.vim'}], ['machakann/vim-highlightedyank', {'name': 'machakann/vim-highlightedyank'}], ['junegunn/vim-peekaboo', {'name': 'junegunn/vim-peekaboo'}], ['vim-scripts/YankRing.vim', {'name': 'vim-scripts/YankRing.vim'}], ['tpope/vim-abolish', {'name': 'tpope/vim-abolish'}], ['tommcdo/vim-exchange', {'name': 'tommcdo/vim-exchange'}], ['tomtom/tcomment_vim', {'name': 'tomtom/tcomment_vim'}], ['danro/rename.vim', {'name': 'danro/rename.vim'}], ['lfv89/vim-interestingwords', {'name': 'lfv89/vim-interestingwords'}], ['valloric/MatchTagAlways', {'name': 'valloric/MatchTagAlways'}], ['kien/rainbow_parentheses.vim', {'name': 'kien/rainbow_parentheses.vim'}], ['christoomey/vim-sort-motion', {'name': 'christoomey/vim-sort-motion'}], ['prettier/vim-prettier', {'name': 'prettier/vim-prettier'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = ['vim-multiple-cursors']
  enable_ale = 1
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_display_mode = 1
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 0
  lint_on_the_fly = 1
  max_column = 80
  plugin_bundle_dir = '/Users/shikun/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'neomru.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  defaushelllt_height=30
  default_position='top'
[[layers]]
  name="ctrlp"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lsp"
  filetypes=['javascript', 'vue']
[[layers]]
  name="git"
[[layers]]
  name="fzf"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="debug"
[[layers]]
  name="unite"
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/HEAD-25356f2/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:30:28] [ Info ] Startup with no argv, current dir is used: ~/workspace/web/wtx/mp-guard
[ SpaceVim ] [19:30:28] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [19:30:29] [ Info ] Start to find root for: 
[ SpaceVim ] [19:30:29] [ Info ]         (.git/):/Users/shikun/workspace/web/wtx/mp-guard/.git/
[ SpaceVim ] [19:30:29] [ Info ]         (package.json):/Users/shikun/workspace/web/wtx/mp-guard/package.json
[ SpaceVim ] [19:30:29] [ Info ] change to root:/Users/shikun/workspace/web/wtx/mp-guard
[ SpaceVim ] [19:30:29] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [19:30:30] [ Info ] change to root:/Users/shikun/workspace/web/wtx/mp-guard
[ SpaceVim ] [19:30:32] [ Info ] Start to find root for: /Users/shikun/workspace/web/wtx/mp-guard/src/App.vue
[ SpaceVim ] [19:30:32] [ Info ]         (.git/):/Users/shikun/workspace/web/wtx/mp-guard/.git/
[ SpaceVim ] [19:30:32] [ Info ]         (package.json):/Users/shikun/workspace/web/wtx/mp-guard/package.json
[ SpaceVim ] [19:30:32] [ Info ] change to root:/Users/shikun/workspace/web/wtx/mp-guard
[ SpaceVim ] [19:36:02] [ Info ] Start to find root for: /var/folders/4k/yjqk1q3j4k31sll5sj_x8z3h0000gn/T/nvimYJVlie/3/issue_report.md
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots
![image](https://user-images.githubusercontent.com/17328586/48771197-a2f96580-ecfb-11e8-9f44-21add412cc33.png)

![image](https://user-images.githubusercontent.com/17328586/48771187-9aa12a80-ecfb-11e8-9ed4-3c32b82c24ad.png)

<a href="https://asciinema.org/a/So5pceCCBPJwWKPeo6HCdFJps" target="_blank"><img src="https://asciinema.org/a/So5pceCCBPJwWKPeo6HCdFJps.svg" /></a>
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
