### ISSUE TITLE
Undefined variable: g:_spacevim_autocomplete_delay

### ISSUE THREAD

**Issue by rezende** [wsdjeg/SpaceVim#2362]
Error:

`[dein] Vim(call):E121: Undefined variable: g:_spacevim_autocomplete_delay`

## Expected behavior, english is required
Error message should not be shown

## The reproduce ways from Vim starting (Required!)
Enter insert mode

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 0
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/voxy/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'yajs.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lsp"
  filetypes=['python', 'javascript']
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.2.2_1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:58:09] [ Info ] Startup with no argv, current dir is used: ~/workspace/we-b-ackend
[ SpaceVim ] [14:58:09] [ Info ] find local conf: /Users/voxy/workspace/we-b-ackend/.SpaceVim.d/init.toml
[ SpaceVim ] [14:58:09] [ Info ] loadding cached local conf: /Users/voxy/.cache/SpaceVim/conf/_Users_voxy_workspace_we-b-ackend__SpaceVim_d_init_toml.json
[ SpaceVim ] [14:58:09] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [14:58:09] [ Info ] Start to find root for: 
[ SpaceVim ] [14:58:09] [ Info ]         (.git/):/Users/voxy/workspace/we-b-ackend/.git/
[ SpaceVim ] [14:58:09] [ Info ]         (package.json):/Users/voxy/workspace/we-b-ackend/package.json
[ SpaceVim ] [14:58:09] [ Info ]         (.SpaceVim.d/):/Users/voxy/workspace/we-b-ackend/.SpaceVim.d/
[ SpaceVim ] [14:58:09] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:09] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [14:58:09] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:10] [ Info ] Start to find root for: /Users/voxy/workspace/we-b-ackend/voxy/apps/legacy_mobile_api/views/goal.py
[ SpaceVim ] [14:58:10] [ Info ]         (.git/):/Users/voxy/workspace/we-b-ackend/.git/
[ SpaceVim ] [14:58:10] [ Info ]         (package.json):/Users/voxy/workspace/we-b-ackend/package.json
[ SpaceVim ] [14:58:10] [ Info ]         (.SpaceVim.d/):/Users/voxy/workspace/we-b-ackend/.SpaceVim.d/
[ SpaceVim ] [14:58:10] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:14] [ Info ] Start to find root for: /Users/voxy/workspace/we-b-ackend/voxy/apps/legacy_mobile_api/views/goal.py
[ SpaceVim ] [14:58:14] [ Info ]         (.git/):/Users/voxy/workspace/we-b-ackend/.git/
[ SpaceVim ] [14:58:14] [ Info ]         (package.json):/Users/voxy/workspace/we-b-ackend/package.json
[ SpaceVim ] [14:58:14] [ Info ]         (.SpaceVim.d/):/Users/voxy/workspace/we-b-ackend/.SpaceVim.d/
[ SpaceVim ] [14:58:14] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:18] [ Info ] Start to find root for: 
[ SpaceVim ] [14:58:18] [ Info ]         (.git/):/Users/voxy/workspace/we-b-ackend/.git/
[ SpaceVim ] [14:58:18] [ Info ]         (package.json):/Users/voxy/workspace/we-b-ackend/package.json
[ SpaceVim ] [14:58:18] [ Info ]         (.SpaceVim.d/):/Users/voxy/workspace/we-b-ackend/.SpaceVim.d/
[ SpaceVim ] [14:58:18] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:18] [ Info ] Start to find root for: /Users/voxy/workspace/we-b-ackend/vimfiler:default
[ SpaceVim ] [14:58:18] [ Info ]         (.git/):/Users/voxy/workspace/we-b-ackend/.git/
[ SpaceVim ] [14:58:18] [ Info ]         (package.json):/Users/voxy/workspace/we-b-ackend/package.json
[ SpaceVim ] [14:58:18] [ Info ]         (.SpaceVim.d/):/Users/voxy/workspace/we-b-ackend/.SpaceVim.d/
[ SpaceVim ] [14:58:18] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:18] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
[ SpaceVim ] [14:58:35] [ Info ] Start to find root for: /Users/voxy/workspace/we-b-ackend/SpaceVimLayers
[ SpaceVim ] [14:58:35] [ Info ]         (.git/):/Users/voxy/workspace/we-b-ackend/.git/
[ SpaceVim ] [14:58:35] [ Info ]         (package.json):/Users/voxy/workspace/we-b-ackend/package.json
[ SpaceVim ] [14:58:35] [ Info ]         (.SpaceVim.d/):/Users/voxy/workspace/we-b-ackend/.SpaceVim.d/
[ SpaceVim ] [14:58:35] [ Info ] change to root:/Users/voxy/workspace/we-b-ackend
```
</details>

## Screenshots
<img width="1186" alt="screen shot 2018-12-18 at 14 59 58" src="https://user-images.githubusercontent.com/1019224/50169940-d9fc7000-02d5-11e9-985c-acf0f461a3d2.png">
