### ISSUE TITLE
Python format-on-save not working

### ISSUE THREAD

**Issue by mr-ubik** [wsdjeg/SpaceVim#2399]
Python `format-on-save = 1` does not currently do anything.

## Expected behavior, english is required

Current buffer is formatted on save.

## The reproduce ways from Vim starting (Required!)

1. Set the following in the `init.toml`\
    ```toml
    [[layers]]
        name = "lang#python"
        format-on-save = 1
    ```
2. Open a dummy Python file and save it.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

#2105 Report a similar error.
