### ISSUE TITLE
misbehavior when open terminal multiple times

### ISSUE THREAD

**Issue by SteamedFish** [wsdjeg/SpaceVim#2408]
## Expected behavior, english is required

open terminal multiple times, and the terminal should still function correctly

## The reproduce ways from Vim starting (Required!)

* press <kbd>SPC '</kbd> to start a terminal
* press <kbd>ESC</kbd> to change the terminal window to normal mode instead of insert mode
* press <kbd>SPC '</kbd> again to start a new terminal

the terminal window is not working correctly.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: mac
- vim version: 8.1.650
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
HEAD detached at 8e82c338
nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 0
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 1
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 1
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfile_filetypeicon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'SteamedFish'
  guifont = 'SauceCodePro Nerd Font:h12'
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 80
  plugin_bundle_dir = '/Users/steamedfish/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'denite-gtags'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="VersionControl"
[[layers]]
  name="colorscheme"
[[layers]]
  name="cscope"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="floobits"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lisp"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#puppet"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
[[layers]]
  name="shell"
  default_position='bottom'
[[layers]]
  name="tags"
[[layers]]
  name="tests"
[[layers]]
  name="tumx"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
[[layers]]
  name="denite"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:18:07] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [15:18:07] [ Info ] find local conf: /Users/steamedfish/dotfiles/.SpaceVim.d/init.toml
[ SpaceVim ] [15:18:07] [ Info ] loadding cached local conf: /Users/steamedfish/.cache/SpaceVim/conf/_Users_steamedfish_dotfiles__SpaceVim_d_init_toml.json
[ SpaceVim ] [15:18:07] [ Info ] start to apply config [local]
[ SpaceVim ] [15:18:07] [ Info ] Start to find root for: 
[ SpaceVim ] [15:18:07] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:18:07] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:18:07] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [15:18:08] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:18:12] [ Info ] Start to find root for: 
[ SpaceVim ] [15:18:12] [ Info ]         (.git/):/Users/steamedfish/dotfiles/.git/
[ SpaceVim ] [15:18:12] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:18:12] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:18:16] [ Info ] Start to find root for: 
[ SpaceVim ] [15:18:16] [ Info ]         (.git/):/Users/steamedfish/dotfiles/.git/
[ SpaceVim ] [15:18:16] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:18:16] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:18:23] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:19:17] [ Info ] Start to find root for: 
[ SpaceVim ] [15:19:17] [ Info ]         (.git/):/Users/steamedfish/dotfiles/.git/
[ SpaceVim ] [15:19:17] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:19:17] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:19:22] [ Info ] Start to find root for: 
[ SpaceVim ] [15:19:22] [ Info ]         (.git/):/Users/steamedfish/dotfiles/.git/
[ SpaceVim ] [15:19:22] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:19:22] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:19:26] [ Info ] Start to find root for: 
[ SpaceVim ] [15:19:26] [ Info ]         (.git/):/Users/steamedfish/dotfiles/.git/
[ SpaceVim ] [15:19:26] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:19:26] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:19:30] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:23:40] [ Info ] Start to find root for: /Users/steamedfish/dotfiles/SpaceVimLayers
[ SpaceVim ] [15:23:40] [ Info ]         (.git/):/Users/steamedfish/dotfiles/.git/
[ SpaceVim ] [15:23:40] [ Info ]         (.SpaceVim.d/):/Users/steamedfish/dotfiles/.SpaceVim.d/
[ SpaceVim ] [15:23:40] [ Info ] change to root:/Users/steamedfish/dotfiles
[ SpaceVim ] [15:26:12] [ Info ] Start to find root for: /var/folders/7p/1crqbdl14mj9grpvt8bf8_j00000gn/T/vhFLalY/39/issue_report.md
[ SpaceVim ] [15:26:12] [ Info ] change to root:/Users/steamedfish/dotfiles
```
</details>
