### ISSUE TITLE
Failed to initialize LSP with error - 32603

### ISSUE THREAD

**Issue by zhuscat** [wsdjeg/SpaceVim#2410]
## Expected behavior, english is required

Start Vim and open an HTML file without error

## The reproduce ways from Vim starting (Required!)

I added flowing configuration in `init.toml`:

```toml
[[layers]]
name = 'ctrlp'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'lang#vue'

[[layers]]
name = 'lsp'
filetypes = [
  "html"
]

[[layers]]
name = 'lang#html'
```

Open Vim and plugins were installed successfully. Then open Vim again, and open an HTML file, with the following error:

```bash
Failed to initialize LSP with error - 32603: Request initialize failed with message: Cannot read property 'css' of undefined
```

## Environment Information

- OS: mac
- vim version: 8.1.577
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/zhuliangzhen/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-stylus'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="ctrlp"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lsp"
  filetypes=['html']
[[layers]]
  name="lang#html"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/8.1-153/MacVim.app/Contents/bin/../MacOS/Vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [21:54:51] [ Info ] Startup with no argv, current dir is used: ~/dev/learn/learn-vim
[ SpaceVim ] [21:54:51] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [21:54:51] [ Info ] start to apply config [glob]
[ SpaceVim ] [21:54:51] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [21:54:51] [ Info ] Start to find root for: 
[ SpaceVim ] [21:54:51] [ Info ] change to root:/Users/zhuliangzhen/dev/learn/learn-vim
[ SpaceVim ] [21:54:51] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [21:54:52] [ Info ] change to root:/Users/zhuliangzhen/dev/learn/learn-vim
[ SpaceVim ] [21:54:53] [ Info ] Start to find root for: /Users/zhuliangzhen/dev/learn/learn-vim/index.html
[ SpaceVim ] [21:54:53] [ Info ] change to root:/Users/zhuliangzhen/dev/learn/learn-vim
[ SpaceVim ] [21:54:56] [ Info ] Start to find root for: /var/folders/jj/zyhr08997fz5p6kx2pwt4pdr0000gn/T/vvH3wqs/1/issue_report.md
[ SpaceVim ] [21:54:56] [ Info ] change to root:/Users/zhuliangzhen/dev/learn/learn-vim
```
</details>

## Screenshots

<img width="1390" alt="2019-01-04 9 59 05" src="https://user-images.githubusercontent.com/14963619/50691544-005b3300-106c-11e9-8b2e-b4d651ae050d.png">
