### ISSUE TITLE
Asyncomplete at startup error message, mapping start by prefix error message on space.

### ISSUE THREAD

**Issue by kayfay** [wsdjeg/SpaceVim#2411]
## Expected behavior, english is required
Starting with vi with a file name doesn't open normally, displays this error message
Similar error reported #1234 closed ticket.

(Note* Denite also isn't working, but just disabled denite, remind me to re-test if this doesnl't solve that...)
(Note* I also haven't configured powerline-status properly, ignore or suggest a fix if you have time)

Error detected while processing function asyncomplete#register_source[5]..<SNR>201_next_tick_single_exec:       
line    5:                                                                                                      
E118: Too many arguments for function: function                                                                 
E116: Invalid arguments for function timer_start(0, function('s:next_tick_single_exec_callback', [a:func]))     
E15: Invalid expression: timer_start(0, function('s:next_tick_single_exec_callback', [a:func]))                 
E118: Too many arguments for function: function                                                                 
E116: Invalid arguments for function timer_start(0, function('s:next_tick_single_exec_callback', [a:func]))     
E15: Invalid expression: timer_start(0, function('s:next_tick_single_exec_callback', [a:func]))     

Another error, image included, occurs when pressing space bar.

## The reproduce ways from Vim starting (Required!)
vi ~/SpaceVim.d/init.toml

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.1.7
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  atusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  able_statusline_display_mode = 0
  able_os_fileformat_icon = 0
  ader_guide_position = 'botright'
  rsion = '1.1.0-dev'
  rce_global_config = 0
  artcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  fault_indent = 2
  able_key_frequency = 0
  able_javacomplete2_py = 0
  able_powerline_fonts = 1
  atusline_separator = 'arrow'
  rning_symbol = '⚠'
  able_statusline_bfpath = 0
  mple_mode = 0
  lorscheme = 'gruvbox'
  able_guicolors = 1
  stom_plugins = []
  ader_guide_submode_mappings = {'<C-C>': 'win_close'}
  mmandline_prompt = '➭'
  ffer_index_type = 4
  ddenfileinfo = 1
  atusline_inactive_separator = 'arrow'
  tcommit_pr_icon = ''
  ugin_manager = 'neobundle'
  ror_symbol = '✖'
  ndows_smartclose = 'q'
  ndows_leader = 's'
  ldignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  able_ale = 0
  able_insert_leader = 1
  able_cursorcolumn = 0
  lorscheme_bg = 'dark'
  able_statusline_tag = 1
  able_neocomplcache = 0
  ader_guide_sort_horizontal = 0
  able_vimfiler_welcome = 1
  x_column = 120
  able_debug = 0
  to_disable_touchpad = 1
  m_help_language = 'en'
  tcommit_issue_icon = ''
  nt_on_save = 1
  debar_direction = ''
  tocomplete_method = 'asyncomplete'
  able_vimfiler_filetypeicon = 0
  ep_server_alive = 1
  atusline_unicode_symbols = 1
  ugin_manager_processes = 16
  atusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  able_ycm = 0
  able_tabline_filetype_icon = 1
  lorscheme_default = 'desert'
  oject_rooter_automatically = 1
  sabled_plugins = []
  ader_guide_max_size = 0
  ifont = ''
  fo_symbol = 'ⓘ'
  ader_guide_flatten = 1
  debar_width = 30
  able_googlesuggest = 0
  able_neomake = 1
  tocomplete_parens = 1
  ugin_bundle_dir = '/home/atools/.cache/vimfiles/'
  able_language_specific_leader = 1
  ader_guide_run_map_on_popup = 1
  sts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  lativenumber = 1
  ader_guide_default_group_name = ''
  mcompatible = 0
  artcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  rminal_cursor_shape = 2
  ippet_engine = 'neosnippet'
  oject_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  arch_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  thub_username = ''
  ader_guide_hspace = 5
  altime_leader_guide = 1
  c_root = 'E:\sources\'
  pand_tab = 1
  eckinstall = 1
  ndows_index_type = 0
  letype_icons = {}
  ugin_name = 'cscope.vim'
  able_cursorline = 1
  stom_color_palette = []
  nt_on_the_fly = 0
  bug_level = 1
  able_statusline_mode = 0
  lemanager = 'vimfiler'
  ckground = 'dark'
  ader_guide_vertical = 0
  nguage = ''
  able_vimfiler_gitstatus = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#asciidoc"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#scala"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lsp"
[[layers]]
  name="lang#tags"
[[layers]]
  name="lang#tests"
[[layers]]
  name="tmux"
[[layers]]
  name="cscope"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(vi)
version: 704
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:33:15] [ Info ] Startup with argv: ['/home/atools/.SpaceVim.d/init.toml']
[ SpaceVim ] [19:33:15] [ Info ] find local conf: /home/atools/.SpaceVim.d/init.toml
[ SpaceVim ] [19:33:15] [ Info ] generate local conf: /home/atools/.cache/SpaceVim/conf/_home_atools__SpaceVim_d_init_toml.json
[ SpaceVim ] [19:33:15] [ Info ] start to apply config [local]
[ SpaceVim ] [19:33:15] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [19:33:15] [ Info ] Start to find root for: /home/atools/.SpaceVim.d/init.toml
[ SpaceVim ] [19:33:15] [ Info ] change to root:/home/atools
[ SpaceVim ] [19:33:15] [ Info ] change to root:/home/atools
[ SpaceVim ] [19:37:56] [ Info ] Start to find root for: /home/atools/SpaceVimLayers
[ SpaceVim ] [19:37:56] [ Info ] change to root:/home/atools
[ SpaceVim ] [19:38:01] [ Info ] change to root:/home/atools
[ SpaceVim ] [19:38:11] [ Info ] Start to find root for: /home/atools/SpaceVimLayers
[ SpaceVim ] [19:38:11] [ Info ] change to root:/home/atools
[ SpaceVim ] [19:38:14] [ Info ] change to root:/home/atools
[ SpaceVim ] [19:38:22] [ Info ] Start to find root for: /tmp/nvimTKNopw/2/issue_report.md
[ SpaceVim ] [19:38:22] [ Info ] change to root:/home/atools
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

https://asciinema.org/a/Pf4M8KoPUhb3Hoj3YJzQHI7XG

![screenshot from 2019-01-04 19-39-05](https://user-images.githubusercontent.com/8055951/50718064-1c55d900-105a-11e9-9d8c-61bad142613c.png)
![screenshot from 2019-01-04 19-39-17](https://user-images.githubusercontent.com/8055951/50718066-1c55d900-105a-11e9-81d7-56ff912038b2.png)
