### ISSUE TITLE
SpaceVim Autocomplete layer lag

### ISSUE THREAD

**Issue by michael-land** [wsdjeg/SpaceVim#2461]
## Expected behavior, english is recommend

The autocomplete layer delay should be reasonable.  I use neovim + deoplete for my auto-complete

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.3
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
1. nvim
2. open any .py file and start typing.
## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_before = 'myspacevim#after'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '‚û≠'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '‚úñ'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = 'ÔÅ™'
  gitcommit_pr_icon = 'Óú¶'
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = '‚ìò'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/michael/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '‚ö†'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#typescript"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:26:53] [ Info ] Startup with no argv, current dir is used: ~/Desktop/mystore
[ SpaceVim ] [09:26:54] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [09:26:54] [ Info ] start to apply config [glob]
[ SpaceVim ] [09:26:54] [ Info ] myspacevim#before called
[ SpaceVim ] [09:26:54] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [09:26:54] [ Info ] Start to find root for: 
[ SpaceVim ] [09:26:54] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:26:54] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:26:54] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [09:26:54] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:26:57] [ Info ] Start to find root for: /Users/michael/Desktop/mystore/vimfiler:default
[ SpaceVim ] [09:26:57] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:26:57] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:27:05] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:27:05] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:27:05] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:27:05] [ Info ] Start to find root for: /Users/michael/Desktop/mystore/templates/inventory/computer.html
[ SpaceVim ] [09:27:05] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:27:05] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:27:59] [ Info ] Start to find root for: /Users/michael/Desktop/mystore/templates/inventory/computer.html
[ SpaceVim ] [09:27:59] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:27:59] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:29:18] [ Info ] Start to find root for: /Users/michael/Desktop/mystore/templates/inventory/computer.html
[ SpaceVim ] [09:29:18] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:29:18] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:29:27] [ Info ] Start to find root for: /Users/michael/Desktop/mystore/templates/inventory/computer.html
[ SpaceVim ] [09:29:27] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:29:27] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:29:54] [ Info ] Start to find root for: /Users/michael/Desktop/mystore/templates/inventory/computer.html
[ SpaceVim ] [09:29:54] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:29:54] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:56:46] [ Info ] Start to find root for: /var/folders/51/wkv3zp3s7bb59t6l69_pv_q80000gn/T/nvimIV7kXV/2/issue_report.md
[ SpaceVim ] [09:56:46] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:56:47] [ Info ] Start to find root for: /var/folders/51/wkv3zp3s7bb59t6l69_pv_q80000gn/T/nvimIV7kXV/2/issue_report.md
[ SpaceVim ] [09:56:47] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:59:07] [ Info ] Start to find root for: 
[ SpaceVim ] [09:59:07] [ Info ]         (.git/):/Users/michael/Desktop/mystore/.git/
[ SpaceVim ] [09:59:07] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [09:59:45] [ Info ] Start to find root for: /Users/michael/.SpaceVim.d/init.toml
[ SpaceVim ] [09:59:45] [ Info ] change to root:/Users/michael/Desktop/mystore
[ SpaceVim ] [10:04:14] [ Info ] Start to find root for: /var/folders/51/wkv3zp3s7bb59t6l69_pv_q80000gn/T/nvimIV7kXV/4/issue_report.md
[ SpaceVim ] [10:04:14] [ Info ] change to root:/Users/michael/Desktop/mystore
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
