### ISSUE TITLE
Jedi-vim failed to initialize Python

### ISSUE THREAD

**Issue by tranhoangcore** [wsdjeg/SpaceVim#2462]
## Expected behavior, english is recommend
When opening file python.
## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.4
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is behind 'origin/master' by 52 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   autoload/SpaceVim.vim
	modified:   config/init.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

##### jedi-vim version

 - jedi-vim git version: 0.9.0-62-g7f4f2db-dirty
 - jedi git submodule status: +a79a1fbef57564d031c59f47def20a6d9adf3439 pythonx/jedi ()
 - parso git submodule status: +e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso ()

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.2 (default, Jan 10 2019, 23:51:51), [GCC 8.2.1 20181127]`
 - global site module: `/usr/lib/python3.7/site.py`
ERROR: could not import the "jedi" Python module: ImportError: bad magic number in 'parso.python': b'\x03\xf3\r\n'
  Traceback (most recent call last):
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 15, in <module>
      import parso
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/parso/parso/parser.py", line 27, in <module>
      from parso.pgen2.generator import ReservedString
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/parso/parso/pgen2/__init__.py", line 10, in <module>
      from parso.pgen2.generator import generate_grammar
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/parso/parso/pgen2/generator.py", line 31, in <module>
      from parso.pgen2.grammar_parser import GrammarParser, NFAState
    File "/home/core/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/parso/parso/pgen2/grammar_parser.py", line 8, in <module>
      from parso.python.tokenize import tokenize

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['lilydjwg/colorizer', {'name': 'lilydjwg/colorizer', 'on_cmd': ['ColorHighlight', 'ColorToggle'], 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/core/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'rust.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/', '.clang', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  auto-completion-tab-key-behavior='smart'
  auto-completion-delay=200
  auto-completion-complete-with-key-sequence-delay=0.1
  auto-completion-complete-with-key-sequence='nil'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="denite"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#javascript"
  auto_fix=1
  enable_flow_syntax=1
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="tmux"
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
[[layers]]
  name="cscope"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#vim"
[[layers]]
  name="tools"
[[layers]]
  name="debug"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
[[layers]]
  name="sudo"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#rust"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:49:36] [ Info ] Startup with argv: ['main.py']
[ SpaceVim ] [17:49:36] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [17:49:36] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:49:36] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [17:49:38] [ Info ] Start to find root for: /run/media/core/DATA/extract_vgg16_feature/main.py
[ SpaceVim ] [17:49:38] [ Info ] change to root:/run/media/core/DATA/extract_vgg16_feature
[ SpaceVim ] [17:49:38] [ Info ] change to root:/run/media/core/DATA/extract_vgg16_feature
[ SpaceVim ] [17:49:47] [ Info ] Start to find root for: /tmp/nvim9sSzzh/3/issue_report.md
[ SpaceVim ] [17:49:47] [ Info ] change to root:/run/media/core/DATA/extract_vgg16_feature
```
</details>

## Screenshots

![alt text](https://i.imgur.com/NvxJu2K.png)
