### ISSUE TITLE
nvim - outputs Invalid expression: type(a:name_or_dict) == v:t_dict

### ISSUE THREAD

**Issue by kayfay** [wsdjeg/SpaceVim#2466]
## Expected behavior, english is required

neovim doesn't work without bugs

## The reproduce ways from Vim starting (Required!)

check screenshots video from asciinema

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.0(1-197, 322, 377-378, 550, 703, 706-707)
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   init.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'morning'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['goerz/ipynb_notedown.vim', {'name': 'goerz/ipynb_notedown.vim'}], ['kshenoy/vim-signature', {'name': 'kshenoy/vim-signature'}], ['chrisbra/csv.vim', {'name': 'chrisbra/csv.vim'}], ['garbas/vim-snipmate', {'name': 'garbas/vim-snipmate'}], ['gaalcaras/ncm-R', {'name': 'gaalcaras/ncm-R'}], ['tomtom/tlib_vim', {'name': 'tomtom/tlib_vim'}], ['MarcWeber/vim-addon-mw-utils', {'name': 'MarcWeber/vim-addon-mw-utils'}], ['jalvesaq/colorout', {'name': 'jalvesaq/colorout'}], ['w0rp/ale', {'name': 'w0rp/ale'}], ['ervandew/screen', {'name': 'ervandew/screen'}], ['whatot/gtags-cscope.vim', {'name': 'whatot/gtags-cscope.vim'}], ['jalvesaq/southernlights', {'name': 'jalvesaq/southernlights'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/atools/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Unite-sources'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_shell='VimShell'
  default_position='right'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="csope"
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lsp"
[[layers]]
  name="ctrlp"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#scala"
[[layers]]
  name="leaderf"
[[layers]]
  name="tags"
[[layers]]
  name="lang#javascript"
  auto_fix=1
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#ocaml"
[[layers]]
  name="lang#python"
  format-on-save=1
[[layers]]
  name="lang#r"
[[layers]]
  name="lang#vim"
[[layers]]
  name="tools"
[[layers]]
  name="debug"
[[layers]]
  name="unite"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vi(vi)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:33:41] [ Info ] Startup with no argv, current dir is used: ~/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:41] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [20:33:41] [ Info ] start to apply config [glob]
[ SpaceVim ] [20:33:41] [ Error ] failed to call bootstrap_before function: myspacevim#before
[ SpaceVim ] [20:33:41] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#before
[ SpaceVim ] [20:33:41] [ Error ]        throwpoint: function SpaceVim#custom#load[34]..<SNR>23_load_glob_conf[9]..SpaceVim#custom#apply, line 28
[ SpaceVim ] [20:33:41] [ Info ] Start to find root for: 
[ SpaceVim ] [20:33:41] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:41] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [20:33:41] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:42] [ Error ] failed to call bootstrap_after function: myspacevim#after
[ SpaceVim ] [20:33:42] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#after
[ SpaceVim ] [20:33:42] [ Error ]        throwpoint: function SpaceVim#autocmds#VimEnter, line 34
[ SpaceVim ] [20:33:43] [ Info ] Start to find root for: /home/atools/edu/iswr/probability_distributions/SpaceVimLayers
[ SpaceVim ] [20:33:43] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:47] [ Info ] Start to find root for: 
[ SpaceVim ] [20:33:47] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:50] [ Info ] Start to find root for: 
[ SpaceVim ] [20:33:50] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:50] [ Info ] Start to find root for: /home/atools/edu/iswr/probability_distributions/[unite] - default
[ SpaceVim ] [20:33:50] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:33:54] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
[ SpaceVim ] [20:34:02] [ Info ] Start to find root for: /tmp/vwd6VRe/73/issue_report.md
[ SpaceVim ] [20:34:02] [ Info ] change to root:/home/atools/edu/iswr/probability_distributions
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots

    https://asciinema.org/a/1EQCI8iYn0jycqpLFlps57Qsq
