### ISSUE TITLE
cscope layer can't create cscope.out file

### ISSUE THREAD

**Issue by easytrys** [wsdjeg/SpaceVim#2508]
## Expected behavior, english is required
space m c i don't work, can't create cscope.out file without any hint.

## Environment Information

- OS: CentOS 7.6
- vim version: 8.1.822
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
# On branch master
nothing to commit, working directory clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/geenli/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'unite-tag'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'fire'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'fire'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
[[layers]]
  name="tags"
[[layers]]
  name="cscope"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/app/vim8.1/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:33:19] [ Info ] Startup with no argv, current dir is used: ~/jzsoft/report_server
[ SpaceVim ] [11:33:19] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [11:33:19] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:33:19] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [11:33:20] [ Info ] Start to find root for: 
[ SpaceVim ] [11:33:20] [ Info ]         (.git/):/home/geenli/jzsoft/report_server/.git/
[ SpaceVim ] [11:33:20] [ Info ] change to root:/home/geenli/jzsoft/report_server
[ SpaceVim ] [11:33:20] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [11:33:20] [ Info ] change to root:/home/geenli/jzsoft/report_server
[ SpaceVim ] [11:33:36] [ Info ] Start to find root for: 
[ SpaceVim ] [11:33:36] [ Info ]         (.git/):/home/geenli/jzsoft/report_server/.git/
[ SpaceVim ] [11:33:36] [ Info ] change to root:/home/geenli/jzsoft/report_server
[ SpaceVim ] [11:33:36] [ Info ] Start to find root for: /home/geenli/jzsoft/report_server/[unite] - default
[ SpaceVim ] [11:33:36] [ Info ]         (.git/):/home/geenli/jzsoft/report_server/.git/
[ SpaceVim ] [11:33:36] [ Info ] change to root:/home/geenli/jzsoft/report_server
[ SpaceVim ] [11:33:44] [ Info ] change to root:/home/geenli/jzsoft/report_server
[ SpaceVim ] [11:38:26] [ Info ] Start to find root for: /tmp/vf1uJtR/30/issue_report.md
[ SpaceVim ] [11:38:26] [ Info ] change to root:/home/geenli/jzsoft/report_server
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
