### ISSUE TITLE
How to use coc.nvim in SpaceVim

### ISSUE THREAD

**Issue by emrahc** [wsdjeg/SpaceVim#2564]
How can i add coc.nvim support for autocompletion/lsp to SpaceVim. Tried many times but failed each time. I use it mostluy React/ReactNative/Nodejs. Thanks for great project :)

**Comment by chenlijun99** [comment]
In `init.toml` put

```toml
[options]
  autocomplete_method = "coc"

# The lsp layer has to be enabled too. SpaceVim converts the configuration in the lsp layer and then passes it to coc.
# You can put your language servers here.
[[layers]] 
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'dart'
  ]
  [layers.override_cmd]
    c = ['ccls', '--log-file=/tmp/ccls.log']
    cpp = ['ccls', '--log-file=/tmp/ccls.log']
```

TIP: if you need to do some custom configuration with `coc.nvim`, instead of using `coc-settings.json` and putting it in `$XDG_CONFIG_HOME/nvim` or `$HOME/.config/nvim` by default（or `$HOME/.vim for vim`), which, since you're using SpaceVim, is occupied by the SpaceVim repository, a good alternative would be that of calling `coc#config` inside your `SpaceVim.d` directory (e.g. inside `SpaceVim.d/plugin/coc.vim`).
This way you don't pollute SpaceVim's repository and future SpaceVim updates won't have problems
(Certainly you can do some clever git stuff to workaround the presence of `coc-settings.json`, but IMHO it's not worth it)

Here is my configuration in `SpaceVim.d/plugin/coc.vim`

```vim
inoremap <silent><expr> <c-space> coc#refresh()

call coc#config('coc.preferences', {
			\ "autoTrigger": "always",
			\ "maxCompleteItemCount": 10,
			\ "codeLens.enable": 1,
			\ "diagnostic.virtualText": 1,
			\})

let s:coc_extensions = [
			\ 'coc-dictionary',
			\ 'coc-json',
			\ 'coc-ultisnips',
			\ 'coc-tag',
			\]

for extension in s:coc_extensions
	call coc#add_extension(extension)
endfor
```

Note that I don't configure any language server, because the lsp layer's configuration in `init.toml` already passes the correct language server configuration to `coc`.
