### ISSUE TITLE
denite layer broken after update

### ISSUE THREAD

**Issue by tofuhead** [wsdjeg/SpaceVim#2588]
## System info

- Linux (Ubuntu)
- Vim 8.0
- Python 3.6
- Spacevim version: latest (fresh install)

## Expected behavior, english is required

Pressing: **Leader f Space** should open up browser, but instead it throws python error.

## The reproduce ways from Vim starting (Required!)

Press: **Leader f Space**.   or any item in: **Leader f** 

This seems to work fine in Neovim, so problem with just with Vim. 
Before this was working fine, but after update I was required to install python3 neovim package, because that was missing.. (I haven't used Neovim ever).. it got rid of some errors, but main problem remains. 
and this affects ofcourse all parts here and there, that use denite... I just got best error text from fuzzy search..

## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['eshion/vim-sync', {'name': 'eshion/vim-sync', 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/basse/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-python-pep8-indent'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'Ve
buggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  vimfiler_tree_closed_icon = 'b'
  vimfiler_tree_opened_icon = 'a'
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'

  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="lang#python"

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.basic)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:10:05] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [17:10:05] [ Info ] find local conf: /home/basse/.SpaceVim.d/init.toml
[ SpaceVim ] [17:10:05] [ Info ] generate local conf: /home/basse/.cache/SpaceVim/conf/_home_basse__SpaceVim_d_init_tom
l.json
[ SpaceVim ] [17:10:05] [ Info ] start to apply config [local]
[ SpaceVim ] [17:10:05] [ Error ] failed to call bootstrap_before function: myspacevim#before
[ SpaceVim ] [17:10:05] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#before
[ SpaceVim ] [17:10:05] [ Error ]        throwpoint: function SpaceVim#custom#load[16]..SpaceVim#custom#apply, line 28
[ SpaceVim ] [17:10:05] [ Info ] Start to find root for:
[ SpaceVim ] [17:10:05] [ Info ] change to root:/home/basse
[ SpaceVim ] [17:10:05] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:10:06] [ Info ] change to root:/home/basse
[ SpaceVim ] [17:10:54] [ Info ] Start to find root for:
[ SpaceVim ] [17:10:54] [ Info ] change to root:/home/basse
[ SpaceVim ] [17:21:05] [ Info ] change to root:/home/basse
[ SpaceVim ] [17:21:15] [ Info ] Start to find root for:
[ SpaceVim ] [17:21:15] [ Info ] change to root:/home/basse
```
</details>

## Screenshots

![screenshot_20190215_170237](https://user-images.githubusercontent.com/8156935/52866109-ac516d00-3146-11e9-9277-ce019cbcea9d.png)

## Python Traceback
<details>

```
Error detected while processing function denite#helper#call_denite[15]..denite#start[4]..<SNR>243_start[1]..denite#i
nitialize[1]..denite#init#_initialize[10]..denite#vim#_initialize:
line   18:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/basse/.cache/vimfiles/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/__init__.py", line 10
, in <module>
    if find_spec('yarp'):
  File "/usr/lib/python3.6/importlib/util.py", line 91, in find_spec
    return _find_spec(fullname, None)
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1109, in _legacy_get_spec
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "/home/basse/.cache/vimfiles/repos/github.com/SpaceVim/nvim-yarp/pythonx/yarp.py", line 12, in <module>
    assert __name__ == "__main__"
AssertionError

```
</details>
