### ISSUE TITLE
open/change  file/buffer gvim will error: E892  

### ISSUE THREAD

**Issue by ws198601** [wsdjeg/SpaceVim#2618]
## The reproduce ways from Vim starting (Required!)
open any file ， change buffer，change tab    
the issue will reproduce

## Environment Information

- OS: windows
- vim version: 8.1.960
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['justinmk/vim-syntax-extra', {'name': 'justinmk/vim-syntax-extra', 'merged': 0}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\wangshuai\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tmuxline.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='smart'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="tools"
[[layers]]
  name="chinese"
[[layers]]
  name="colorscheme"
  random_theme=1
[[layers]]
  name="default"
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#perl"
[[layers]]
  name="lang#python"
  format-on-save=1
[[layers]]
  name="lang#scheme"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="tags"
[[layers]]
  name="tmux"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(D:\Program Files (x86)\Vim8\vim81\gvim.exe)
version: 801
OS: windows
[shell, shellcmdflag, shellslash]: ['C:\Windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:33:42] [ Info ] Startup with no argv, current dir is used: D:\Program Files (x86)\Vim8\vim81
[ SpaceVim ] [17:33:42] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [17:33:42] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:33:46] [ Info ] Start to find root for: 
[ SpaceVim ] [17:33:46] [ Info ] change to root:D:\Program Files (x86)\Vim8\vim81
[ SpaceVim ] [17:33:46] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:33:47] [ Info ] change to root:D:\Program Files (x86)\Vim8\vim81
[ SpaceVim ] [17:35:32] [ Info ] Start to find root for: E:\HUNDSUN_SVN\UPPS30\upps31pre\te\main\comp\UP_F_TASK.c
[ SpaceVim ] [17:35:32] [ Info ]         (.svn/):E:\HUNDSUN_SVN\UPPS30\upps31pre\.svn/
[ SpaceVim ] [17:35:32] [ Info ] change to root:E:\HUNDSUN_SVN\UPPS30\upps31pre
[ SpaceVim ] [17:35:40] [ Info ] Start to find root for: C:\Users\WANGSH~1\AppData\Local\Temp\VIC19B4.tmp\issue_report.md
[ SpaceVim ] [17:35:40] [ Info ]         (.SpaceVim.d/):C:\Users\wangshuai\.SpaceVim.d/
[ SpaceVim ] [17:35:40] [ Info ] change to root:C:\Users\wangshuai
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![image](https://user-images.githubusercontent.com/4425067/53159015-f089b500-35ff-11e9-82df-ebed22d78a8e.png)
