### ISSUE TITLE
editorconfig tab size issue with multiple rust files open.

### ISSUE THREAD

**Issue by Neopallium** [wsdjeg/SpaceVim#2672]
## Expected behavior, english is required
The tab size should be the same in all open Rust files.  I have tried setting `ident_size`/`tab_width` to 2 in `~/.editorconfig` and also `let g:spacevim_default_indent = 2`

Only the first Rust file (.rs) has tab size 2, the second file has tab size 8.

## The reproduce ways from Vim starting (Required!)
Make two Rust files with the same content:
```rust
fn main() {
	pritnln!("Hello"); // Use one real tab to indent.
}
```
create `~/.editorconfig`:
```
root = true
[*.rs]
indent_style=tab
indent_size=2
tab_width=2
```
Open both Rust files:
```
nvim test1.rs test2.rs
```
The first file should have the correct tab size.  Switch to the second file `:n` it will have tab size 8.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.4
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 0
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/robert/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-bookmarks'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="tmux"
[[layers]]
  name="lsp"
  override_cmd={'lua': ['lua-lsp']}
  filetypes=['go', 'javascript', 'html', 'css', 'rust', 'lua']
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#WebAssembly"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#extra"
[[layers]]
  name="git"
[[layers]]
  name="tools"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [21:51:45] [ Info ] Startup with argv: ['main.rs', 'pong.rs']
[ SpaceVim ] [21:51:45] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [21:51:45] [ Info ] start to apply config [glob]
[ SpaceVim ] [21:51:45] [ Info ] myspacevim#after called
[ SpaceVim ] [21:51:45] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [21:51:46] [ Info ] Start to find root for: /home/robert/projects/rust/pong/main.rs
[ SpaceVim ] [21:51:46] [ Info ] change to root:/home/robert/projects/rust/pong
[ SpaceVim ] [21:51:46] [ Info ] change to root:/home/robert/projects/rust/pong
[ SpaceVim ] [21:51:46] [ Error ] failed to call bootstrap_after function: myspacevim#after
[ SpaceVim ] [21:51:46] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#after
[ SpaceVim ] [21:51:46] [ Error ]        throwpoint: function SpaceVim#autocmds#VimEnter, line 34
[ SpaceVim ] [21:51:49] [ Info ] Start to find root for: /home/robert/projects/rust/pong/pong.rs
[ SpaceVim ] [21:51:49] [ Info ] change to root:/home/robert/projects/rust/pong
[ SpaceVim ] [21:51:51] [ Info ] Start to find root for: /home/robert/projects/rust/pong/SpaceVimLayers
[ SpaceVim ] [21:51:51] [ Info ] change to root:/home/robert/projects/rust/pong
[ SpaceVim ] [21:52:56] [ Info ] change to root:/home/robert/projects/rust/pong
[ SpaceVim ] [21:53:14] [ Info ] Start to find root for: /tmp/nvimjnRcrD/2/issue_report.md
[ SpaceVim ] [21:53:14] [ Info ] change to root:/home/robert/projects/rust/pong
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
