### ISSUE TITLE
Enable auto complete error message on CTRL N - n

### ISSUE THREAD

**Issue by kayfay** [wsdjeg/SpaceVim#2722]
## Expected behavior, english is required
CTRL N n
## The reproduce ways from Vim starting (Required!)
Open Nvim to edit .tex file
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.0
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'morning'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['jalvesaq/southernlights', {'name': 'jalvesaq/southernlights'}], ['ncm2/ncm2-bufword', {'name': 'ncm2/ncm2-bufword'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/atools/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Unite-sources'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_shell='VimShell'
  default_position='right'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="csope"
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lsp"
[[layers]]
  name="ctrlp"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#scala"
[[layers]]
  name="leaderf"
[[layers]]
  name="tags"
[[layers]]
  name="lang#javascript"
  auto_fix=1
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#ocaml"
[[layers]]
  name="lang#python"
  format-on-save=1
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#latex"
[[layers]]
  name="tools"
[[layers]]
  name="debug"
[[layers]]
  name="unite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvimRwLZcK/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:11:08] [ Info ] Startup with argv: ['kim-falk-prs.tex']
[ SpaceVim ] [08:11:08] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [08:11:08] [ Info ] start to apply config [glob]
[ SpaceVim ] [08:11:08] [ Error ] failed to call bootstrap_before function: myspacevim#before
[ SpaceVim ] [08:11:08] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#before
[ SpaceVim ] [08:11:08] [ Error ]        throwpoint: function SpaceVim#custom#load[34]..<SNR>24_load_glob_conf[9]..SpaceVim#custom#apply, line 28
[ SpaceVim ] [08:11:08] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [08:11:09] [ Info ] Start to find root for: /home/atools/edu/recommenders/kim-falk-prs/kim-falk-prs.tex
[ SpaceVim ] [08:11:09] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:11:09] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:11:09] [ Error ] failed to call bootstrap_after function: myspacevim#after
[ SpaceVim ] [08:11:09] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#after
[ SpaceVim ] [08:11:09] [ Error ]        throwpoint: function SpaceVim#autocmds#VimEnter, line 34
[ SpaceVim ] [08:30:53] [ Info ] FlyGrep startting ===========================
[ SpaceVim ] [08:30:53] [ Info ]    executable    : grep
[ SpaceVim ] [08:30:53] [ Info ]    option        : ['-inHr']
[ SpaceVim ] [08:30:53] [ Info ]    r_option      : ['.']
[ SpaceVim ] [08:30:53] [ Info ]    files         : ''
[ SpaceVim ] [08:30:53] [ Info ]    dir           : ''
[ SpaceVim ] [08:30:53] [ Info ]    ignore_case   : ['-i']
[ SpaceVim ] [08:30:53] [ Info ]    smart_case    : []
[ SpaceVim ] [08:30:53] [ Info ]    expr opt      : ['-e']
[ SpaceVim ] [08:30:54] [ Info ] FlyGrep ending    ===========================
[ SpaceVim ] [08:30:55] [ Info ] Start to find root for: /home/atools/edu/recommenders/kim-falk-prs/kim-falk-prs.tex
[ SpaceVim ] [08:30:55] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:30:58] [ Info ] Start to find root for: 
[ SpaceVim ] [08:30:58] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:33:29] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:33:29] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:35:36] [ Info ] Start to find root for: 
[ SpaceVim ] [08:35:36] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:35:36] [ Info ] Start to find root for: /home/atools/edu/recommenders/kim-falk-prs/[unite] - default
[ SpaceVim ] [08:35:36] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:35:41] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
[ SpaceVim ] [08:42:41] [ Info ] Start to find root for: /tmp/nvimjtm1fS/5/issue_report.md
[ SpaceVim ] [08:42:41] [ Info ] change to root:/home/atools/edu/recommenders/kim-falk-prs
```
</details>

## Screenshots
![Screenshot from 2019-04-09 20-39-17](https://user-images.githubusercontent.com/8055951/55843725-b5880600-5b07-11e9-952d-7b757c6e5ae5.png)

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
