### ISSUE TITLE
How to configure variables in spacevim?

### ISSUE THREAD

**Issue by maikol-solis** [wsdjeg/SpaceVim#2724]
I'm trying to learn vim and spacevim to type latex documents (I used emacs before). I want to set some configuration settings like this,  

```
let g:tex_flavor='latex'
let g:vimtex_view_general_viewer = 'evince'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg' 
```

I have read some disccusion about the init.toml vs init.vim files but I really don't get it. The documentation, IMHO,  is not clear enough for a newbie.  Also, I try to set a boostrap function but it seems that I did it wrong. 

I have a file called `latex.vim` in the `~/.SpaceVim.d/autoload/` which have 

```
function! latexconfig#after() abort
let g:tex_flavor='latex'
let g:vimtex_view_general_viewer = 'evince'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg' 
endfunction
```

I would like to make this work but I need some guidance to do it. 

Thanks for all you help. 

## Expected behavior, english is recommend

Know how to configure the plugins easily. 

## Environment Information

- OS: linux
- vim version: 8.1.1066
- neovim version: -
- SpaceVim version: 1.1.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  boostrap_after = 'latexconfig#after'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'one'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['KeitaNakamura/tex-conceal.vim', {'name': 'KeitaNakamura/tex-conceal.vim'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/maikol/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimtex'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#latex"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim(/usr/bin/gvim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:33:25] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [08:33:25] [ Info ] find local conf: /home/maikol/.SpaceVim.d/init.toml
[ SpaceVim ] [08:33:25] [ Info ] loadding cached local conf: /home/maikol/.cache/SpaceVim/conf/_home_maikol__SpaceVim_d_init_toml.json
[ SpaceVim ] [08:33:25] [ Info ] start to apply config [local]
[ SpaceVim ] [08:33:25] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [08:33:27] [ Info ] Start to find root for: 
[ SpaceVim ] [08:33:27] [ Info ] change to root:/home/maikol
[ SpaceVim ] [08:33:27] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [08:33:27] [ Info ] change to root:/home/maikol
[ SpaceVim ] [08:33:32] [ Info ] Start to find root for: /tmp/vSqhu6D/3/issue_report.md
[ SpaceVim ] [08:33:32] [ Info ] change to root:/home/maikol
[ SpaceVim ] [08:33:33] [ Info ] Start to find root for: /tmp/vSqhu6D/3/issue_report.md
[ SpaceVim ] [08:33:33] [ Info ] change to root:/home/maikol
[ SpaceVim ] [08:34:16] [ Info ] Start to find root for: /tmp/vSqhu6D/5/issue_report.md
[ SpaceVim ] [08:34:16] [ Info ] change to root:/home/maikol
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
