### ISSUE TITLE
vimfiler lags and shows keys on file tree when gitstatus enabled

### ISSUE THREAD

**Issue by mertyildiran** [wsdjeg/SpaceVim#2749]
## Expected behavior

[vimfiler](https://github.com/Shougo/vimfiler.vim) should run smoothly and not show the pressed keys on file tree.

## To reproduce

Either enable git status for vimfiler in `init.toml` with:

```plain
[options]
    enable_vimfiler_gitstatus = true
```

or enabled it inside [Bootstrap Functions](https://spacevim.org/documentation/#bootstrap-functions) with `let g:spacevim_enable_vimfiler_gitstatus = 1`

Then open SpaceVim and navigate through file tree using `h, j, k, l` keys by **quickly pressing** them.

You will experience a huge lag in vimfiler and it will show you the pressed keys for a brief moment.

## Debug info

I couldn't get the actual debug info by pressing <kbd>SPC h I</kbd> maybe I hit to some other issue:

```plain
Error detected while processing function SpaceVim#issue#report[1]..<SNR>295_open:
line    5:
E354: Invalid register name: '+'
Press ENTER or type command to continue
```

but I got it using `:SPDebugInfo!` command:

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['wakatime/vim-wakatime', {'name': 'wakatime/vim-wakatime', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0}], ['jwalton512/vim-blade', {'name': 'jwalton512/vim-blade', 'merged': 0}], ['lilydjwg/colorizer', {'name': 'lilydjwg/colorizer', 'merged': 0, 'on_cmd': ['ColorHighlight']}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'mertyildiran'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/mertyildiran/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tmuxline.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_highlight_persist = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  tagbar_show_linenumbers = 1
  tagbar_show_visibility = 1
  terminal_cursor_shape = 2
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  vimfiler_print_filename = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-delay=3
  auto-completion-tab-key-behavior='smart'
  auto-completion-return-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=12
[[layers]]
  name="colorscheme"
  enable=1
[[layers]]
  name="ctrlp"
[[layers]]
  name="lang#c"
  enable=1
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#elixir"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#javascript"
  enable=1
  enable_flow_syntax=1
[[layers]]
  name="lang#lisp"
[[layers]]
  name="lang#markdown"
  enable=1
[[layers]]
  name="lang#ocaml"
[[layers]]
  name="lang#php"
  enable=1
[[layers]]
  name="lang#python"
  enable=1
  format-on-save=1
[[layers]]
  name="lang#ruby"
  enable=1
[[layers]]
  name="lang#typescript"
  enable=1
[[layers]]
  name="lang#vim"
[[layers]]
  name="tags"
[[layers]]
  name="debug"
[[layers]]
  name="git"
  enable=1
[[layers]]
  name="github"
[[layers]]
  name="VersionControl"
  enable=1
[[layers]]
  name="unite"
[[layers]]
  name="tmux"
  enable=1
[[layers]]
  name="default"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [02:42:34] [ Info ] Startup with no argv, current dir is used: ~/Downloads/editor-test/Dragonfire
[ SpaceVim ] [02:42:34] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [02:42:34] [ Info ] start to apply config [glob]
[ SpaceVim ] [02:42:34] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [02:42:35] [ Info ] Start to find root for: 
[ SpaceVim ] [02:42:35] [ Info ]         (.git/):/home/mertyildiran/Downloads/editor-test/Dragonfire/.git/
[ SpaceVim ] [02:42:35] [ Info ] change to root:/home/mertyildiran/Downloads/editor-test/Dragonfire
[ SpaceVim ] [02:42:35] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [02:42:35] [ Info ] change to root:/home/mertyildiran/Downloads/editor-test/Dragonfire
[ SpaceVim ] [02:42:36] [ Info ] Start to find root for: /home/mertyildiran/Downloads/editor-test/Dragonfire/vimfiler:default
[ SpaceVim ] [02:42:36] [ Info ]         (.git/):/home/mertyildiran/Downloads/editor-test/Dragonfire/.git/
[ SpaceVim ] [02:42:36] [ Info ] change to root:/home/mertyildiran/Downloads/editor-test/Dragonfire
```
</details>

## Screenshots

I have recorded the issue:

https://asciinema.org/a/9BsrKkCvZYheyBj4Ru6ULpna2
