### ISSUE TITLE
Python repl does not work

### ISSUE THREAD

**Issue by hrishikeshvganu** [wsdjeg/SpaceVim#2754]
## Expected behavior, english is recommend
IN python repl when I send a line for execution and print the output should immediately appear in the repl window

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.2
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	autoload/myconfig.vim
#	session/
nothing added to commit but untracked files present (use "git add" to track)
```

## The reproduce ways from Vim starting (Required!)
type in a line like `print "hello"`
Type `[SPC]lsi` to start repl
Type `[SPC]lsl` to send the line 
## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myconfig#after'
  buffer_index_type = 0
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['tpope/vim-obsession', {'name': 'tpope/vim-obsession'}], ['dhruvasagar/vim-prosession', {'name': 'dhruvasagar/vim-prosession'}], ['devjoe/vim-codequery', {'name': 'devjoe/vim-codequery'}], ['mileszs/ack.vim', {'name': 'mileszs/ack.vim'}], ['vim-scripts/MPage', {'name': 'vim-scripts/MPage'}], ['mileszs/ack.vim', {'name': 'mileszs/ack.vim'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/spacevim/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'neomru.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#python"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="mhinz/neovim-remote"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/local/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:55:09] [ Info ] Startup with no argv, current dir is used: 
[ SpaceVim ] [14:55:09] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [14:55:09] [ Info ] start to apply config [glob]
[ SpaceVim ] [14:55:09] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [14:55:10] [ Info ] Start to find root for: 
[ SpaceVim ] [14:55:10] [ Info ]         (.git/):/developer/atke_nov_2018/10-march-clone/AutoTKE-master/.git/
[ SpaceVim ] [14:55:10] [ Info ]         (.SpaceVim.d/):/developer/.SpaceVim.d/
[ SpaceVim ] [14:55:10] [ Info ] change to root:/developer/atke_nov_2018/10-march-clone/AutoTKE-master
[ SpaceVim ] [14:55:10] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [14:55:11] [ Info ] change to root:/developer/atke_nov_2018/10-march-clone/AutoTKE-master
[ SpaceVim ] [14:55:11] [ Info ] Start to find root for: 
[ SpaceVim ] [14:55:11] [ Info ]         (.git/):/developer/atke_nov_2018/10-march-clone/AutoTKE-master/.git/
[ SpaceVim ] [14:55:11] [ Info ]         (.SpaceVim.d/):/developer/.SpaceVim.d/
[ SpaceVim ] [14:55:11] [ Info ] change to root:/developer/atke_nov_2018/10-march-clone/AutoTKE-master
[ SpaceVim ] [14:55:11] [ Info ] Start to find root for: /tmp/test.py
[ SpaceVim ] [14:55:11] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:55:20] [ Info ] Start to find root for: /home/spacevim/.SpaceVim/__REPL__
[ SpaceVim ] [14:55:20] [ Info ]         (.git/):/home/spacevim/.SpaceVim/.git/
[ SpaceVim ] [14:55:20] [ Info ]         (.SpaceVim.d/):/home/spacevim/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [14:55:20] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:55:21] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:56:40] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:56:50] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:56:54] [ Info ] Start to find root for: /home/spacevim/.SpaceVim/__REPL__
[ SpaceVim ] [14:56:54] [ Info ]         (.git/):/home/spacevim/.SpaceVim/.git/
[ SpaceVim ] [14:56:54] [ Info ]         (.SpaceVim.d/):/home/spacevim/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [14:56:54] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:56:54] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:57:20] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [14:57:23] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:15] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:26] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:34] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:43] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:49] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:52] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:04:59] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:05:19] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:06:28] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:06:44] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:06:47] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:06:48] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:06:56] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:07:06] [ Info ] Start to find root for: /home/spacevim/.SpaceVim/__REPL__
[ SpaceVim ] [15:07:06] [ Info ]         (.git/):/home/spacevim/.SpaceVim/.git/
[ SpaceVim ] [15:07:06] [ Info ]         (.SpaceVim.d/):/home/spacevim/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [15:07:06] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:07:06] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:07:22] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:07:31] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:07:50] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:07:54] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:08:03] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:36:23] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:37:25] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:37:29] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:37:37] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:37:47] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:37:54] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:37:59] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:38:13] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:38:49] [ Info ] Start to find root for: 
[ SpaceVim ] [15:38:49] [ Info ]         (.git/):/home/spacevim/.SpaceVim/.git/
[ SpaceVim ] [15:38:49] [ Info ]         (.SpaceVim.d/):/home/spacevim/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [15:38:49] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:38:57] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:39:11] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:42:01] [ Info ] Start to find root for: /home/spacevim/.SpaceVim/SpaceVimLayers
[ SpaceVim ] [15:42:01] [ Info ]         (.git/):/home/spacevim/.SpaceVim/.git/
[ SpaceVim ] [15:42:01] [ Info ]         (.SpaceVim.d/):/home/spacevim/.SpaceVim/.SpaceVim.d/
[ SpaceVim ] [15:42:01] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:42:33] [ Info ] change to root:/home/spacevim/.SpaceVim
[ SpaceVim ] [15:42:41] [ Info ] Start to find root for: /tmp/nvimV6BG4M/1/issue_report.md
[ SpaceVim ] [15:42:41] [ Info ] change to root:/home/spacevim/.SpaceVim
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
