### ISSUE TITLE
GTags invalid rows in quickfix window

### ISSUE THREAD

**Issue by gllera** [wsdjeg/SpaceVim#2760]
## Expected behavior, english is required
Be able to go to all references in the gtag's quickfix window.

## The reproduce ways from Vim starting (Required!)
Follow the [tags](https://spacevim.org/layers/gtags/) layer documentation to use GNU Global with exuberant-ctags and python-pygments in SpaceVim. Then create a GTags database (<kbd>SPC m g c</kbd>) and try to find references (<kbd>SPC m g r</kbd>) of some function.

## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/source/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-cpp-enhanced-highlight'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  auto-completion-tab-key-behavior='nil'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="git"
[[layers]]
  name="fzf"
[[layers]]
  name="VersionControl"
[[layers]]
  name="tags"
[[layers]]
  name="tmux"
[[layers]]
  name="lang#c"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
  ┊ ┊ SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvimyMh4nG/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
  ┊ ┊ Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
  ┊ ┊ Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
  ┊ ┊ Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:56:17] [ Info ] Startup with directory: /source/master2/DEV/tup.code
[ SpaceVim ] [16:56:17] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [16:56:17] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:56:17] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [16:56:18] [ Info ] Start to find root for: /source/master2/DEV/tup.code/
[ SpaceVim ] [16:56:18] [ Info ]         (.git/):/source/master2/DEV/tup.code/.git/
[ SpaceVim ] [16:56:18] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:18] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [16:56:18] [ Info ] Start to find root for:
[ SpaceVim ] [16:56:18] [ Info ]         (.git/):/source/master2/DEV/tup.code/.git/
[ SpaceVim ] [16:56:18] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:19] [ Info ] Start to find root for: /source/master2/DEV/tup.code/vimfiler:default
[ SpaceVim ] [16:56:19] [ Info ]         (.git/):/source/master2/DEV/tup.code/.git/
[ SpaceVim ] [16:56:19] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:25] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:25] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:25] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:25] [ Info ] Start to find root for: /source/master2/DEV/tup.code/src/tup/ccache.c
[ SpaceVim ] [16:56:25] [ Info ]         (.git/):/source/master2/DEV/tup.code/.git/
[ SpaceVim ] [16:56:25] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:29] [ Info ] Start to find root for:
[ SpaceVim ] [16:56:29] [ Info ]         (.git/):/source/master2/DEV/tup.code/.git/
[ SpaceVim ] [16:56:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:44] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:44] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:44] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:44] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [16:56:44] [ Info ] Start to find root for: /source/master2/DEV/tup.code/src/tup/path.c
[ SpaceVim ] [16:56:44] [ Info ]         (.git/):/source/master2/DEV/tup.code/.git/
[ SpaceVim ] [16:56:44] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:29] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:36] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:42] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:42] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:42] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:25:42] [ Info ] change to root:/source/master2/DEV/tup.code
[ SpaceVim ] [15:36:35] [ Info ] Start to find root for: /tmp/nvimclEbNH/3/issue_report.md
[ SpaceVim ] [15:36:35] [ Info ] change to root:/source/master2/DEV/tup.code
```
</details>

## Screenshots
Sometimes there are several rows invalid:
![image](https://user-images.githubusercontent.com/498397/56470986-48e90180-644d-11e9-810a-450e23240c08.png)

Sometimes all the rows are invalid:
![image](https://user-images.githubusercontent.com/498397/56471002-674efd00-644d-11e9-9830-1bedc1f99941.png)

(it depends on the function called)

btw, putting in the nvim initialization script the following:
`let g:Gtags_Use_Tags_Format = 1`
Solves this issue but there is a comment on 'gtags.vim' that says that this method is obsolete so I not sure about what's the 'correct' solution :/
