### ISSUE TITLE
golang environment doesn't load properly

### ISSUE THREAD

**Issue by firfly** [wsdjeg/SpaceVim#2764]
## Expected behavior, english is required
when I run a golang script with spacevim by <kbd>SPC l x</kbd>；I was told : 
`go: cannot find GOROOT directory: /usr/local/Cellar/go/1.9.2/libexec
`

and this is a obsolete GOROOT path after I upgrade my golang version to 1.12
then when I run the inside cmd with spacevim by  `!go env`, it confirm my assumer.
it's different from I run `go env` on my os prompt
it seems like there is a configration(or environment) used by spacevim that I can't see or modify.
and I try uninstall spacevim with delete all .Spacevim* staff and reinstall it, It didn't fix either.
what I miss? or any wrong posture?

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['kien/rainbow_parentheses.vim', {'name': 'kien/rainbow_parentheses.vim', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons'}], ['mhartington/oceanic-next', {'name': 'mhartington/oceanic-next',
 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/tony/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-go'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'curve'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#extra"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#vim"
[[layers]]
  name="shell"
  default_position='top'
[[layers]]
  name="lang#python"
  default_height=30
[[layers]]
  name="debug"
[[layers]]
  name="lang#go"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:10:24] [ Info ] Startup with argv: ['testlog.go']
[ SpaceVim ] [11:10:24] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [11:10:24] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:10:24] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [11:10:25] [ Info ] Start to find root for: /Users/tony/battleField/testlog.go
[ SpaceVim ] [11:10:25] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:10:25] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:10:29] [ Info ] Start to find root for: /Users/tony/battleField/__runner__
[ SpaceVim ] [11:10:29] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:10:29] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:10:29] [ Info ]    cmd:'go run testlog.go'
[ SpaceVim ] [11:10:46] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:12:33] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:14:41] [ Info ] Start to find root for: /Users/tony/battleField/SpaceVimLayers
[ SpaceVim ] [11:14:41] [ Info ] change to root:/Users/tony/battleField
[ SpaceVim ] [11:14:57] [ Info ] change to root:/Users/tony/battleField
```
</details>
