### ISSUE TITLE
Grep on the fly should ignore result from .gitignore

### ISSUE THREAD

**Issue by jefrydco** [wsdjeg/SpaceVim#2811]
## Expected behavior, english is recommend
Searching file in the current directory should ignore result from `.gitignore`. When you are JS developer with a lot of packages in node_modules, it really annoying to have the result from node_modules included.

## Environment Information

- OS: linux
- vim version: 8.1.1137
- neovim version: -
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Open grep on the fly using `SPC s p` or `SPC s /`

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jefrydco/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-stylus'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="git"
[[layers]]
  name="tmux"
[[layers]]
  name="lsp"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#elixir"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#html"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [04:14:53] [ Info ] Startup with directory: /mnt/Data/Projects/Github/jefrydco
[ SpaceVim ] [04:14:53] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [04:14:53] [ Info ] start to apply config [glob]
[ SpaceVim ] [04:14:53] [ Info ] Start to find root for: /mnt/Data/Projects/Github/jefrydco/
[ SpaceVim ] [04:14:53] [ Info ]         (.git/):/mnt/Data/Projects/Github/jefrydco/.git/
[ SpaceVim ] [04:14:53] [ Info ]         (package.json):/mnt/Data/Projects/Github/jefrydco/package.json
[ SpaceVim ] [04:14:53] [ Info ] change to root:/mnt/Data/Projects/Github/jefrydco
[ SpaceVim ] [04:14:53] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [04:14:53] [ Info ] Start to find root for: 
[ SpaceVim ] [04:14:53] [ Info ]         (.git/):/mnt/Data/Projects/Github/jefrydco/.git/
[ SpaceVim ] [04:14:53] [ Info ]         (package.json):/mnt/Data/Projects/Github/jefrydco/package.json
[ SpaceVim ] [04:14:53] [ Info ] change to root:/mnt/Data/Projects/Github/jefrydco
[ SpaceVim ] [04:15:51] [ Info ] FlyGrep startting ===========================
[ SpaceVim ] [04:15:51] [ Info ]    executable    : grep
[ SpaceVim ] [04:15:51] [ Info ]    option        : ['-inHr']
[ SpaceVim ] [04:15:51] [ Info ]    r_option      : ['.']
[ SpaceVim ] [04:15:51] [ Info ]    files         : ''
[ SpaceVim ] [04:15:51] [ Info ]    dir           : '/mnt/Data/Projects/Github/jefrydco'
[ SpaceVim ] [04:15:51] [ Info ]    ignore_case   : ['-i']
[ SpaceVim ] [04:15:51] [ Info ]    smart_case    : []
[ SpaceVim ] [04:15:51] [ Info ]    expr opt      : ['-e']
[ SpaceVim ] [04:15:51] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'test', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:51] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:15:54] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'tes', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:54] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:15:54] [ Info ] grep cmd: ['grep', '-inHr', '-e', 't', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:54] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:15:55] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'a', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:55] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:15:57] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'node', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:57] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:15:57] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'nod', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:57] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:15:58] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'n', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:15:58] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:01] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'inde', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:01] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:01] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:01] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:04] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'inde', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:04] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:05] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'ind', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:05] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:05] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'in', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:05] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:06] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'i', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:06] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:12] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'inde', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:12] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:13] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.v', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:13] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:13] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.ve', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:13] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:13] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.v', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:13] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:14] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.vue', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:14] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:18] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.vu', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:18] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:18] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.v', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:18] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:20] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'index.', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:20] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:21] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'a', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:21] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:26] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'no', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:26] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:27] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'n', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:27] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:16:28] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'a', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:16:28] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:18:17] [ Info ] grep cmd: ['grep', '-inHr', '-e', '', '/mnt/Data/Projects/Github/jefrydco']
[ SpaceVim ] [04:18:17] [ Info ] flygrep job id is: 1
[ SpaceVim ] [04:18:18] [ Info ] FlyGrep ending    ===========================
[ SpaceVim ] [04:18:25] [ Info ] Start to find root for: /tmp/v5XZlVG/4/issue_report.md
[ SpaceVim ] [04:18:25] [ Info ] change to root:/mnt/Data/Projects/Github/jefrydco
```
</details>

## Screenshots
![Screenshot from 2019-05-10 04-27-24](https://user-images.githubusercontent.com/20434351/57487933-01cb8f00-72dc-11e9-8a3f-e178f4d6a058.png)

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
