### ISSUE TITLE
Neomake virtualtext not disappearing 

### ISSUE THREAD

**Issue by patrickshobe** [wsdjeg/SpaceVim#2850]
## Expected behavior, english is required
Neomake errors should appear on the line the error is on. The error should also disappear when the cursor is moved off the line and it does not. 

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.4
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .SpaceVim.d/init.vim
	modified:   init.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## The reproduce ways from Vim starting (Required!)
1. Open a file with an error
2. Run neomake
3. Move cursor over the line with the error
4. Move cursor off the line with the error

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 2
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Hasklig:h15'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/pshobe/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tern_for_vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_left_sections = ['winnr', 'syntax checking', 'major mode']
  statusline_right_sections = ['time']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="denite"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="checker"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.4/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:12:23] [ Info ] Startup with no argv, current dir is used: /private/var/www/ltflask
[ SpaceVim ] [10:12:23] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [10:12:23] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:12:23] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [10:12:24] [ Info ] Start to find root for: 
[ SpaceVim ] [10:12:24] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:12:24] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:12:24] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:12:24] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [10:12:24] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:12:24] [ Info ] Start to find root for: /private/var/www/ltflask/psql/schema/apollo/__init__.py
[ SpaceVim ] [10:12:24] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:12:24] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:12:24] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:12:25] [ Info ] Start to find root for: 
[ SpaceVim ] [10:12:25] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:12:25] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:12:25] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:12:25] [ Info ] Start to find root for: /private/var/www/ltflask/vimfiler:default
[ SpaceVim ] [10:12:25] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:12:25] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:12:25] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:12:25] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:15:37] [ Info ] Start to find root for: /private/var/www/ltflask/SpaceVimLayers
[ SpaceVim ] [10:15:37] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:15:37] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:15:37] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:15:49] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:16:27] [ Info ] Start to find root for: /private/var/www/ltflask/SpaceVimLayers
[ SpaceVim ] [10:16:27] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:16:27] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:16:27] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:16:50] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:16:52] [ Info ] Start to find root for: /private/var/www/ltflask/[denite]
[ SpaceVim ] [10:16:52] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:16:52] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:16:52] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:16:56] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:16:56] [ Info ] Start to find root for: 
[ SpaceVim ] [10:16:56] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:16:56] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:16:56] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:16:56] [ Info ] Start to find root for: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/doc/pattern.txt
[ SpaceVim ] [10:16:56] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:17:08] [ Info ] Start to find root for: 
[ SpaceVim ] [10:17:08] [ Info ]         (.git/):/private/var/www/ltflask/.git/
[ SpaceVim ] [10:17:08] [ Info ]         (package.json):/private/var/www/ltflask/package.json
[ SpaceVim ] [10:17:08] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:18:07] [ Info ] change to root:/private/var/www/ltflask
[ SpaceVim ] [10:18:33] [ Info ] Start to find root for: /var/folders/8d/rpg7pry91l924_x1vcn8p2l51q2swy/T/nvim6cu41P/2/issue_report.md
[ SpaceVim ] [10:18:33] [ Info ] change to root:/private/var/www/ltflask
```
</details>

#### Error Appearing on wrong line

![Screen Shot 2019-05-28 at 10 14 37 AM](https://user-images.githubusercontent.com/32880860/58494349-26c05e80-8132-11e9-8e5f-abdf56db671c.png)

#### Error not disappearing
![Screen Shot 2019-05-28 at 10 20 37 AM](https://user-images.githubusercontent.com/32880860/58494425-4eafc200-8132-11e9-8055-9592946f8bac.png)

#### Many Errors at once
![many](https://user-images.githubusercontent.com/32880860/58500890-5d9d7100-8140-11e9-84c1-0eafe3acc213.png)
