### ISSUE TITLE
How can I change the linter?

### ISSUE THREAD

**Issue by jinyiliu** [wsdjeg/SpaceVim#2870]
I'd like to use a different linter in ale syntax checker plugin rather than the default linters.

More specifically, I want to use pycodestyle python linter. 
`ale`'s default linters contain pylint which is really too strict for python syntax check.

However if I try to add these codes in `init.toml` 
```toml
[options]
    # Syntax check, default checker: checkers
    enable_neomake = false
    enable_ale = true
    let g:ale_linters = {'python': ['pycodestyle']}
```
Apparently, the last line is not right.
So how can I do it?

Really thank you for the amazing vim editor!
