### ISSUE TITLE
Runner in Perl with "print color" not work

### ISSUE THREAD

**Issue by vincent-vivian-liu** [wsdjeg/SpaceVim#2884]
## Expected behavior, english is required
when running code `print color 'red'; print "This string is red in terminal\n" `, I expect the printed string should also be red in runner.

## The reproduce ways from Vim starting (Required!)
Run any perl code with above snippet will reproduce this phenomenon.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
SpaceVim layers:

## Environment Information

- OS: mac [**In fact is Msys2**]
- vim version: 8.1.1234
- neovim version: -
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   autoload/SpaceVim/plugins/runner.vim
    modified:   vimrc

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'SpaceVim'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/vivian/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'srcery-vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#perl"
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [07:33:32] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [07:33:32] [ Info ] find local conf: /home/vivian/.SpaceVim.d/init.toml
[ SpaceVim ] [07:33:32] [ Info ] loadding cached local conf: /home/vivian/.cache/SpaceVim/conf/_home_vivian__SpaceVim_d_init_toml.json
[ SpaceVim ] [07:33:32] [ Info ] start to apply config [local]
[ SpaceVim ] [07:33:34] [ Info ] Start to find root for: 
[ SpaceVim ] [07:33:34] [ Info ] change to root:/home/vivian
[ SpaceVim ] [07:33:34] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [07:33:34] [ Info ] change to root:/home/vivian
[ SpaceVim ] [07:38:08] [ Info ] Start to find root for: /home/vivian/test/color/color_test.pl
[ SpaceVim ] [07:38:08] [ Info ] change to root:/home/vivian
[ SpaceVim ] [07:38:15] [ Info ] Start to find root for: /home/vivian/test/color/__runner__
[ SpaceVim ] [07:38:15] [ Info ] change to root:/home/vivian/test/color
[ SpaceVim ] [07:38:15] [ Info ] change to root:/home/vivian
[ SpaceVim ] [07:38:15] [ Info ]    cmd:['perl', '-']
[ SpaceVim ] [07:38:34] [ Info ] Start to find root for: /tmp/vH6lzDu/8/issue_report.md
[ SpaceVim ] [07:38:34] [ Info ] change to root:/home/vivian/test/color
[ SpaceVim ] [07:38:40] [ Info ] Start to find root for: /tmp/vH6lzDu/8/issue_report.md
[ SpaceVim ] [07:38:40] [ Info ] change to root:/home/vivian/test/color
[ SpaceVim ] [07:42:37] [ Info ] change to root:/home/vivian
[ SpaceVim ] [07:42:57] [ Info ] Start to find root for: /tmp/vH6lzDu/10/issue_report.md
[ SpaceVim ] [07:42:57] [ Info ] change to root:/home/vivian/test/color
```
</details>

## plugins

<details><summary> SpaceVim plugin information </summary>

```log
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
+ format:                   loaded          https://spacevim.org/layers/format/
- fzf:                  not loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
+ lang#c:                   loaded          https://spacevim.org/layers/lang/c/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          no exists
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
- lang#html:            not loaded          https://spacevim.org/layers/lang/html/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
- lang#markdown:        not loaded          https://spacevim.org/layers/lang/markdown/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
+ lang#perl:                loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          no exists
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#ps1:             not loaded          no exists
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
- lang#python:          not loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          no exists
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#toml:            not loaded          no exists
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
- lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#xml:             not loaded          no exists
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          no exists
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
+ shell:                    loaded          https://spacevim.org/layers/shell/
- sudo:                 not loaded          https://spacevim.org/layers/sudo/
- tags:                 not loaded          no exists
- test:                 not loaded          https://spacevim.org/layers/test/
- tmux:                 not loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          no exists
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
- vim:                  not loaded          no exists
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![color_test](https://user-images.githubusercontent.com/14258188/59428491-fb1ac500-8e0f-11e9-9494-434c914817e0.png)
