### ISSUE TITLE
 Undefined variable: name when config custom_color_palette

### ISSUE THREAD

**Issue by vincent-vivian-liu** [wsdjeg/SpaceVim#2897]
## Expected behavior, english is required
Not this error
## The reproduce ways from Vim starting (Required!)
when set custom_color_palette in the custom configuration file `init.toml`.
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
## Environment Information

- OS: mac
- vim version: 8.1.1234
- neovim version: -
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   autoload/SpaceVim/api/vim/statusline.vim
	modified:   autoload/SpaceVim/layers/core/statusline.vim
	modified:   autoload/SpaceVim/plugins/runner.vim
	modified:   vimrc

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	autoload/SpaceVim/api/vim/statusline.vim.bak
	autoload/SpaceVim/api/vim/statusline.vim.vivi.bak
	autoload/SpaceVim/layers/core/statusline.vim.vivi.bak
	autoload/SpaceVim/layers/core/statusline.vim.vivi.bak.old

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'SpaceVim'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = [['#282828', '#FFA500', 250, 97], ['#d75fd7', '#4e4e4e', 170, 239], ['#c6c6c6', '#3a3a3a', 251, 237], ['#2c323c', 16], ['#282828', '#00BFFF', 114, 152], ['#2c323c', '#ff8787', 114, 210], ['#2c323c', '#d75f5f', 114, 167], ['#282828', '#689d6a', 235, 72], ['#282828', '#8f3f71', 235, 132]]
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = ['coc.nvim', 'markdown-preview.nvim', 'vim-node-rpc']
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/vivian/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tagbar-markdown'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
  statusline_separator = 'angry'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#perl"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#markdown"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:23:19] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [13:23:19] [ Info ] find local conf: /home/vivian/.SpaceVim.d/init.toml
[ SpaceVim ] [13:23:19] [ Info ] loadding cached local conf: /home/vivian/.cache/SpaceVim/conf/_home_vivian__SpaceVim_d_init_toml.json
[ SpaceVim ] [13:23:19] [ Info ] start to apply config [local]
[ SpaceVim ] [13:24:12] [ Info ] Start to find root for: 
[ SpaceVim ] [13:24:12] [ Info ] change to root:/home/vivian
[ SpaceVim ] [13:24:12] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [13:24:12] [ Info ] change to root:/home/vivian
[ SpaceVim ] [13:24:49] [ Info ] Start to find root for: /tmp/vrxlh6e/4/issue_report.md
[ SpaceVim ] [13:24:49] [ Info ] change to root:/home/vivian
```
</details>

## Screenshots
![bug_when_custom_color_palette](https://user-images.githubusercontent.com/14258188/59738993-d3a37c80-9295-11e9-9e7d-fb21f467172e.png)
![bug_when_custom_color_palette1](https://user-images.githubusercontent.com/14258188/59739029-f2097800-9295-11e9-8b1b-0b9431bb0438.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
