### ISSUE TITLE
The command is not available in this version

### ISSUE THREAD

**Issue by tranhoangcore** [wsdjeg/SpaceVim#2917]
## Expected behavior, english is recommend
Error detected while processing /home/core/.SpaceVim/init.vim:
line   11:
E319: The command is not available in this version: lua require('spacevim').bootstrap()
Completor requires vim compiled with python or python3 and has features `job`, `timers` and `lambda`
Press ENTER or type command to continue

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.1.7
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  atusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  able_os_fileformat_icon = 0
  ader_guide_position = 'botright'
  rsion = '1.2.0-dev'
  rce_global_config = 0
  artcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  fault_indent = 2
  able_key_frequency = 0
  able_javacomplete2_py = 0
  able_powerline_fonts = 1
  atusline_separator = 'nil'
  rning_symbol = '⚠'
  able_statusline_bfpath = 0
  mple_mode = 0
  lorscheme = 'gruvbox'
  able_guicolors = 0
  stom_plugins = []
  ader_guide_submode_mappings = {'<C-C>': 'win_close'}
  mmandline_prompt = '➭'
  ffer_index_type = 4
  ddenfileinfo = 1
  atusline_inactive_separator = 'bar'
  tcommit_pr_icon = ''
  ugin_manager = 'neobundle'
  ror_symbol = '✖'
  ndows_smartclose = 0
  ndows_leader = ''
  ldignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  able_ale = 0
  able_insert_leader = 1
  able_cursorcolumn = 0
  lorscheme_bg = 'dark'
  able_statusline_tag = 1
  able_neocomplcache = 0
  ader_guide_sort_horizontal = 0
  able_vimfiler_welcome = 1
  x_column = 120
  able_debug = 0
  to_disable_touchpad = 1
  m_help_language = 'en'
  tcommit_issue_icon = ''
  nt_on_save = 1
  debar_direction = ''
  tocomplete_method = 'completor'
  able_vimfiler_filetypeicon = 0
  ep_server_alive = 1
  atusline_unicode_symbols = 0
  ugin_manager_processes = 16
  atusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  able_ycm = 0
  able_tabline_filetype_icon = 0
  lorscheme_default = 'desert'
  letree_direction = 'right'
  oject_rooter_automatically = 1
  able_tabline_ft_icon = 0
  sabled_plugins = []
  ader_guide_max_size = 0
  ifont = ''
  atusline_iseparator = 'nil'
  fo_symbol = 'ⓘ'
  ader_guide_flatten = 1
  debar_width = 30
  able_googlesuggest = 0
  nguage = ''
  able_neomake = 1
  tocomplete_parens = 1
  ugin_bundle_dir = '/home/core/.cache/vimfiles/'
  able_language_specific_leader = 1
  ader_guide_run_map_on_popup = 1
  sts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  lativenumber = 1
  ader_guide_default_group_name = ''
  mcompatible = 1
  artcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  me_files_number = 6
  rminal_cursor_shape = 2
  ippet_engine = 'neosnippet'
  oject_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  arch_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  date_retry_cnt = 3
  thub_username = ''
  ader_guide_hspace = 5
  c_root = 'E:\sources\'
  pand_tab = 1
  eckinstall = 1
  ndows_index_type = 3
  letype_icons = {}
  ugin_name = 'suda.vim'
  able_cursorline = 1
  stom_color_palette = []
  nt_on_the_fly = 0
  bug_level = 1
  able_bepo_layout = 0
  altime_leader_guide = 1
  able_statusline_mode = 0
  lemanager = 'vimfiler'
  ader_guide_vertical = 0
  able_vimfiler_gitstatus = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="sudo"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(nvim)
version: 704
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:18:44] [ Info ] Startup with no argv, current dir is used: /boot/efi/EFI
[ SpaceVim ] [17:18:44] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [17:18:44] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:18:44] [ Info ] Start to find root for: 
[ SpaceVim ] [17:18:44] [ Info ] change to root:/boot/efi/EFI
[ SpaceVim ] [17:18:44] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:18:44] [ Info ] change to root:/boot/efi/EFI
[ SpaceVim ] [17:18:50] [ Info ] Start to find root for: /tmp/nvimMwkCVx/1/issue_report.md
[ SpaceVim ] [17:18:50] [ Info ] change to root:/boot/efi/EFI
```
</details>
