### ISSUE TITLE
easymotion should work in visual mode

### ISSUE THREAD

**Issue by ghost** [wsdjeg/SpaceVim#2936]
## Expected behavior, english is required

When in visual mode, the keyboard shotcuts to do easymotion movements should still work, and result in modifying the selection. For example, entering visual line mode while on line 10, and using easymotion to jump to line 25, should result in lines 10-25 being selected.

## The reproduce ways from Vim starting (Required!)

1. Press `v` to enter visual mode
2. Press `SPC j j` -- nothing happens, visual mode is exited

Or in visual line mode: 

1. Press `V` to enter visual line mode
2. Press `SPC j l` -- the selection jumps ahead several lines, but the easymotion overlays do not appear to choose a line to jump to.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.8
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	init.toml

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['rbgrouleff/bclose.vim', {'name': 'rbgrouleff/bclose.vim', 'merged': 0}], ['francoiscabrol/ranger.vim', {'name': 'francoiscabrol/ranger.vim', 'merged': 0}], ['christoomey/vim-tmux-navigator', {'name': 'christoomey/vim-tmux-navigator', 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/kahn/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'fzf-neoyank'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = 'left'
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  timeoutlen = 500
  update_retry_cnt = 3
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="git"
[[layers]]
  name="fzf"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.3.8/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:47:32] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [15:47:32] [ Info ] find local conf: /Users/kahn/src/local/dotfiles/conf/common/nvim/init.toml
[ SpaceVim ] [15:47:32] [ Info ] loadding cached local conf: /Users/kahn/.cache/SpaceVim/conf/_Users_kahn_src_local_dotfiles_conf_common_nvim_init_toml.json
[ SpaceVim ] [15:47:32] [ Info ] start to apply config [local]
[ SpaceVim ] [15:47:32] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [15:47:33] [ Info ] Start to find root for: 
[ SpaceVim ] [15:47:33] [ Info ] change to root:/Users/kahn
[ SpaceVim ] [15:47:33] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [15:47:33] [ Info ] change to root:/Users/kahn
[ SpaceVim ] [15:47:36] [ Info ] Start to find root for: /Users/kahn/src/checkout/src/app/components/AddressSelectionForm/AddressSelectionForm.js
[ SpaceVim ] [15:47:36] [ Info ]         (.git/):/Users/kahn/src/checkout/.git/
[ SpaceVim ] [15:47:36] [ Info ]         (package.json):/Users/kahn/src/checkout/package.json
[ SpaceVim ] [15:47:36] [ Info ] change to root:/Users/kahn/src/checkout
[ SpaceVim ] [16:47:30] [ Info ] Start to find root for: /var/folders/nf/5njg_hdx0cq8p0_968gw31wm0000gp/T/nvimjFJzUT/5/issue_report.md
[ SpaceVim ] [16:47:30] [ Info ] change to root:/Users/kahn/src/checkout
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
