### ISSUE TITLE
Invalid expression: deoplete#mappings#smart_close_popup()."\^H"

### ISSUE THREAD

**Issue by PeterDing** [wsdjeg/SpaceVim#2948]
## Expected behavior, english is required

This error is reported on one language rust file when I pass the 'delete' key to delete a word in insert mode. The word cann't be deleted but only the error is reported repeatedly. This error does not happen immediately after opening the rust file. It occurs after some minutes/seconds.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.3.8
- SpaceVim version: 1.2.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	coc-settings.json

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['airblade/vim-gitgutter', {'name': 'airblade/vim-gitgutter', 'merged': 0}], ['vim-python/python-syntax', {'name': 'vim-python/python-syntax', 'merged': 0}], ['luochen1990/rainbow', {'name': 'luochen1990/rainbow', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/peter/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'gtags.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = 'right'
  sidebar_width = 20
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 1
  update_retry_cnt = 3
  version = '1.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='smart'
  auto-completion-tab-key-behavior='smart'
  auto-completion-complete-with-key-sequence='nil'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="denite"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
  clang_executable='/usr/local/opt/llvm/bin/clang'
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#javascript"
  enable_flow_syntax=1
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#cscope"
[[layers]]
  name="lang#unite"
[[layers]]
  name="tags"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/Users/peter/.local/nvim-osx64/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:21:43] [ Info ] Startup with no argv, current dir is used: ~/dev/aget-rs
[ SpaceVim ] [18:21:43] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [18:21:43] [ Info ] start to apply config [glob]
[ SpaceVim ] [18:21:43] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [18:21:43] [ Info ] Start to find root for: 
[ SpaceVim ] [18:21:43] [ Info ]         (.git/):/Users/peter/dev/aget-rs/.git/
[ SpaceVim ] [18:21:43] [ Info ] change to root:/Users/peter/dev/aget-rs
[ SpaceVim ] [18:21:43] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [18:21:43] [ Info ] Start to find root for: /Users/peter/dev/aget-rs/NERD_tree_1
[ SpaceVim ] [18:21:43] [ Info ]         (.git/):/Users/peter/dev/aget-rs/.git/
[ SpaceVim ] [18:21:43] [ Info ] change to root:/Users/peter/dev/aget-rs
[ SpaceVim ] [18:21:47] [ Info ] Start to find root for: /Users/peter/dev/aget-rs/src/core.rs
[ SpaceVim ] [18:21:47] [ Info ]         (.git/):/Users/peter/dev/aget-rs/.git/
[ SpaceVim ] [18:21:47] [ Info ] change to root:/Users/peter/dev/aget-rs
[ SpaceVim ] [18:22:03] [ Info ] Start to find root for: /Users/peter/dev/aget-rs/src/core.rs
[ SpaceVim ] [18:22:03] [ Info ]         (.git/):/Users/peter/dev/aget-rs/.git/
[ SpaceVim ] [18:22:03] [ Info ] change to root:/Users/peter/dev/aget-rs
[ SpaceVim ] [18:22:43] [ Info ] Start to find root for: /var/folders/v5/jxt3nz9964j15xw3rxxc_3ph0000gn/T/nvimdY9WBg/6/issue_report.md
[ SpaceVim ] [18:22:43] [ Info ] change to root:/Users/peter/dev/aget-rs
```
</details>

## Screenshots

<img width="1280" alt="Screen Shot 2019-07-17 at 6 22 31 PM" src="https://user-images.githubusercontent.com/670690/61368255-102bbd80-a8c0-11e9-9139-f1b49be688ab.png">
