### ISSUE TITLE
Make spell check work for colorscheme - gruvbox

### ISSUE THREAD

**Issue by wasaCheney** [wsdjeg/SpaceVim#3024]
## Expected behavior, english is required
I like spacevim with gruvbox very much, but *spell check under gruvbox* does not work at all.
- Expect: hightlight typos, none-capitalize words when toggle spell check on under gruvbox
- But: nothing would happen
- Solution:
I find a simple way to make it! Reference website: [morhetz/gruvbox/issue#175](https://github.com/morhetz/gruvbox/issues/175)
  1. enable spacevim's colorscheme layer
  1. append the following content to file .SpaceVim/config/plugins/gruvbox.vim
  `let g:gruvbox_guisp_fallback = "bg"`

Then spell check works for gruvbox! The world becomes nice again!!! Hope it would be help.

## The reproduce ways from Vim starting (Required!)
1. enable spacevim's colorscheme layer
1. open any text file
1. toggle spell check on: SPC + t + S

But nothing would happen!

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.1.119
- neovim version: -
- SpaceVim version: 1.3.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   autoload/SpaceVim/layers/lang/latex.vim
	modified:   config/plugins/gruvbox.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/cheney/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'srcery-vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
  format-on-save=1
[[layers]]
  name="lang#sh"
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:02:20] [ Info ] Startup with argv: ['Methodology.tex']
[ SpaceVim ] [15:02:20] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [15:02:20] [ Info ] start to apply config [glob]
[ SpaceVim ] [15:02:23] [ Info ] Start to find root for: /mnt/article/towards_unsupervised_pansharpening/Methodology.tex
[ SpaceVim ] [15:02:23] [ Info ] change to root:/mnt/article/towards_unsupervised_pansharpening
[ SpaceVim ] [15:02:23] [ Info ] change to root:/mnt/article/towards_unsupervised_pansharpening
[ SpaceVim ] [15:03:14] [ Info ] Start to find root for: /mnt/article/towards_unsupervised_pansharpening/Methodology.tex
[ SpaceVim ] [15:03:14] [ Info ] change to root:/mnt/article/towards_unsupervised_pansharpening
[ SpaceVim ] [15:03:15] [ Info ] Start to find root for: 
[ SpaceVim ] [15:03:15] [ Info ] change to root:/mnt/article/towards_unsupervised_pansharpening
[ SpaceVim ] [15:03:15] [ Info ] change to root:/mnt/article/towards_unsupervised_pansharpening
[ SpaceVim ] [15:19:55] [ Info ] Start to find root for: /tmp/v2TMLos/90/issue_report.md
[ SpaceVim ] [15:19:55] [ Info ] change to root:/mnt/article/towards_unsupervised_pansharpening
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

Nothing happened before:
![Screenshot from 2019-08-26 15-33-32](https://user-images.githubusercontent.com/18375090/63673586-33c71980-c817-11e9-8e40-9b3db3d0f960.png)
Spell check works well now:
![Screenshot from 2019-08-26 15-33-00](https://user-images.githubusercontent.com/18375090/63673601-3aee2780-c817-11e9-9de7-81bf2a47fec1.png)
