### ISSUE TITLE
Set spelllang to different language than "en"

### ISSUE THREAD

**Issue by PandaLz** [wsdjeg/SpaceVim#3051]
## Expected behavior, english is required

Change default spell language with:

`:setlocal spell spelllang=es`

Throws:

`
spellfile#LoadFile(): No (writable) spell directory found.
Failed to create: /home/user/.local/share/nvim/site/spell
Warning: Cannot find word list "es.utf-8.spl" or "es.ascii.spl"
Press ENTER or type command to continue
`

Doing as pointed here:

https://github.com/neovim/neovim/issues/2102#issuecomment-269100273

Happen to prompt and download the required files but starting nvim normally would throw the same error.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.8
- SpaceVim version: 1.3.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['calincru/qml.vim', {'name': 'calincru/qml.vim', 'merged': 0}], ['pboettch/vim-cmake-syntax', {'name': 'pboettch/vim-cmake-syntax', 'merged': 0}], ['vim-scripts/ShaderHighLight', {'name': 'vim-scripts/ShaderHighLight', 'merged': 0}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = ['neco-look']
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/user/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'LanguageClient-neovim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="sudo"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#v"
[[layers]]
  name="lang#crystal"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#WebAssembly"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#dart"
[[layers]]
  name="lsp"
  filetypes=['rust', 'typescript', 'javascript', 'html', 'css', 'python', 'sh', 'go', 'cpp', 'c']
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:04:05] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [13:04:05] [ Info ] find local conf: /home/user/.SpaceVim.d/init.toml
[ SpaceVim ] [13:04:05] [ Info ] loadding cached local conf: /home/user/.cache/SpaceVim/conf/_home_user__SpaceVim_d_init_toml.json
[ SpaceVim ] [13:04:05] [ Info ] start to apply config [local]
[ SpaceVim ] [13:04:05] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [13:04:05] [ Info ] Start to find root for: 
[ SpaceVim ] [13:04:05] [ Info ] change to root:/home/user
[ SpaceVim ] [13:04:05] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [13:04:06] [ Info ] change to root:/home/user
[ SpaceVim ] [13:30:46] [ Info ] Start to find root for: /home/user/SpaceVimLayers
[ SpaceVim ] [13:30:46] [ Info ] change to root:/home/user
[ SpaceVim ] [13:31:21] [ Info ] Start to find root for: /tmp/nvim548KF4/1/issue_report.md
[ SpaceVim ] [13:31:21] [ Info ] change to root:/home/user
[ SpaceVim ] [13:31:22] [ Info ] Start to find root for: /tmp/nvim548KF4/1/issue_report.md
[ SpaceVim ] [13:31:22] [ Info ] change to root:/home/user
[ SpaceVim ] [13:33:57] [ Info ] Start to find root for: /tmp/nvim548KF4/2/issue_report.md
[ SpaceVim ] [13:33:57] [ Info ] change to root:/home/user
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
