### ISSUE TITLE
Scala lang: E716: Key not present in Dictionary: i

### ISSUE THREAD

**Issue by mrmodolo** [wsdjeg/SpaceVim#3143]
## Expected behavior, english is recommend

Use layer for scala development. 

## Environment Information

- OS: linux
- vim version: 8.1.320
- neovim version: -
- SpaceVim version: 1.3.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

Create a new scala project. Create a folder .SpaceVim.d, put a file init.tom whith the contents bellow and open a scala file.

cat .SpaceVim.d/init.toml
[options]
force_global_config = true

[[layers]]
name = "lang#scala"

When opening the file the error below is shown

Error detected while processing function SpaceVim#mapping#space#refrashLSPC[3]..30_language_specified_mappings[83]..SpaceVim#mapping#space#langSPC:
line 28:
E716: Key not present in Dictionary: i
E716: Key not present in Dictionary: i
Press ENTER or type command to continue

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/modolo/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'palenight.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'build.sbt', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#scala"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gik, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:06:53] [ Info ] Startup with argv: ['src/main/scala/Main.scala']
[ SpaceVim ] [19:06:53] [ Info ] find local conf: /home/modolo/Aprendendo/scala/workspace/hello-world-sbt/.SpaceVim.d/init.toml
[ SpaceVim ] [19:06:53] [ Info ] loadding cached local conf: /home/modolo/.cache/SpaceVim/conf/_home_modolo_Aprendendo_scala_workspace_hello-world-sbt__SpaceVim_d_init_toml.json
[ SpaceVim ] [19:06:53] [ Info ] start to apply config [local]
[ SpaceVim ] [19:06:53] [ Info ] force loadding global config >>>
[ SpaceVim ] [19:06:53] [ Info ] start to apply config [glob]
[ SpaceVim ] [19:06:53] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [19:06:53] [ Info ] Start to find root for: /home/modolo/Aprendendo/scala/workspace/hello-world-sbt/src/main/scala/Main.scala
[ SpaceVim ] [19:06:53] [ Info ]         (build.sbt):/home/modolo/Aprendendo/scala/workspace/hello-world-sbt/build.sbt
[ SpaceVim ] [19:06:53] [ Info ]         (.SpaceVim.d/):/home/modolo/Aprendendo/scala/workspace/hello-world-sbt/.SpaceVim.d/
[ SpaceVim ] [19:06:53] [ Info ] change to root:/home/modolo/Aprendendo/scala/workspace/hello-world-sbt
[ SpaceVim ] [19:06:53] [ Info ] change to root:/home/modolo/Aprendendo/scala/workspace/hello-world-sbt
[ SpaceVim ] [19:08:11] [ Info ] Start to find root for: /tmp/vMq3kAC/6/issue_report.md
[ SpaceVim ] [19:08:11] [ Info ] change to root:/home/modolo/Aprendendo/scala/workspace/hello-world-sbt
```
</details>

## Screenshots
![Captura de tela de 2019-10-12 19-05-40](https://user-images.githubusercontent.com/1923174/66708293-940d0e80-ed24-11e9-8222-9ef1c9e8d97b.png)

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
