### ISSUE TITLE
[SPC]iu not work without Unite

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#3150]
## Expected behavior, english is required

``SPC i u`` can be used to insert Unicode charater.

## The reproduce ways from Vim starting (Required!)

1. Enable ``denite``, disable ``unite``
2. Enable ``defx``, disable ``vimfiler`` (which will auto-enable ``unite``)
3. New a buffer, enter ``SPC i u``
4. Vim error: ``E492: Not an editor command: Unite unicode``

## Debug info

**The following information is for neovim, gvim has the same error too.**

## Environment Information

- OS: windows
- vim version: -
- neovim version: 0.3.5
- SpaceVim version: 1.3.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 0
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = ''
  colorscheme_bg = 'dark'
  colorscheme_default = 'gruvbox'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['lilydjwg/colorizer', {'name': 'lilydjwg/colorizer', 'merged': 0}], ['thawk/vim-asciidoc-folding', {'lazy': 1, 'name': 'thawk/vim-asciidoc-folding', 'on_ft': 'asciidoc'}], ['masukomi/vim-markdown-folding', {'lazy': 1, 'name': 'masukomi/vim-markdown-folding', 'on_ft': 'markdown'}], ['thawk/vim-b2', {'lazy': 0, 'name': 'thawk/vim-b2'}], ['ConradIrwin/vim-bracketed-paste', {'name': 'ConradIrwin/vim-bracketed-paste'}], ['derekwyatt/vim-fswitch', {'lazy': 1, 'on_func': ['FSwitch', 'FSReturnReadableCompanionFilename', 'FSReturnCompanionFilenameString'], 'name': 'derekwyatt/vim-fswitch', 'on_cmd': ['FSHere', 'FSRight', 'FSSplitRight', 'FSLeft', 'FSSplitLeft', 'FSAbove', 'FSSplitAbove', 'FSBelow', 'FSSplitBelow', 'FSTab']}], ['junkblocker/patchreview-vim', {'lazy': 1, 'name': 'junkblocker/patchreview-vim', 'on_cmd': ['PatchReview', 'PatchReviewPersist', 'ReversePatchReview', 'ReversePatchReviewPersist', 'DiffReview', 'DiffReviewPersist']}], ['vim-scripts/CodeReviewer.vim', {'lazy': 1, 'name': 'vim-scripts/CodeReviewer.vim', 'on_map': {'n': '<Plug>AddComment'}, 'on_cmd': ['CheckReview', 'SortReviewFile']}], ['haya14busa/dein-command.vim', {'lazy': 1, 'name': 'haya14busa/dein-command.vim', 'on_cmd': ['Dein']}], ['inkarkat/vim-ingo-library', {'lazy': 1, 'name': 'inkarkat/vim-ingo-library'}], ['inkarkat/vim-mark', {'lazy': 1, 'depends': ['inkarkat/vim-ingo-library'], 'name': 'inkarkat/vim-mark', 'on_map': ['<Plug>Mark'], 'on_cmd': ['Mark', 'MarkClear', 'Marks', 'MarkLoad', 'MarkSave', 'MarkYankDefinitions', 'MarkYankDefinitionsOneLiner', 'MarkPalette', 'MarkName']}], ['sickill/vim-monokai', {'name': 'sickill/vim-monokai'}], ['thawk/vim-pcet', {'lazy': 1, 'on_path': 'pcet_.*\.xml', 'name': 'thawk/vim-pcet'}], ['thawk/bbv2.vim', {'name': 'thawk/bbv2.vim'}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = ['vim-gutentags']
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'DejaVuSansMono NF:h13:cANSI:qDRAFT,DejaVuSansMono_Nerd_Font:h13:cANSI:qDRAFT,Consolas:h13:cANSI:qDRAFT'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\tanht\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-lilypond'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'stack.yaml', '.SpaceVim.d/', '.clang', 'pom.xml', 'package.json']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = '~/workspace/'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg,.*/,bin*/**/gcc-*/**,*.gcov,*.o'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  auto-completion-tab-key-behavior='smart'
  auto-completion-complete-with-key-sequence='nil'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="sudo"
[[layers]]
  name="VersionControl"
[[layers]]
  name="colorscheme"
[[layers]]
  name="denite"
[[layers]]
  name="incsearch"
[[layers]]
  name="tools"
[[layers]]
  name="lang#asciidoc"
[[layers]]
  name="lang#c"
  enable=1
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#javascript"
  enable=1
[[layers]]
  name="lang#markdown"
  enableWcwidth=1
  enable=1
  listItemIndent=1
  listItemChar='-'
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#python"
  enable=1
[[layers]]
  name="lang#sh"
  bash-file-head=['#!/usr/bin/env bash', '# Time: `strftime("%Y-%m-%d %T")`', '']
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lsp"
  enable=1
[[layers]]
  name="tags"
[[layers]]
  name="tmux"
  enable=1
[[layers]]
  name="lang#lilypond"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(D:\GreenSoft\Neovim\bin\nvim.exe)
version: 800
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:24:16] [ Info ] Startup with no argv, current dir is used: D:\GreenSoft\Neovim\bin
[ SpaceVim ] [11:24:16] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [11:24:17] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:24:18] [ Info ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [11:24:21] [ Info ] Start to find root for: 
[ SpaceVim ] [11:24:21] [ Info ] change to root:D:\GreenSoft\Neovim\bin
[ SpaceVim ] [11:24:21] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [11:24:21] [ Info ] change to root:D:\GreenSoft\Neovim\bin
[ SpaceVim ] [11:24:23] [ Info ] Start to find root for: 
[ SpaceVim ] [11:24:23] [ Info ] change to root:D:\GreenSoft\Neovim\bin
[ SpaceVim ] [11:24:30] [ Info ] Start to find root for: C:\Users\tanht\AppData\Local\Temp\nvimlwNCS1\1/issue_report.md
[ SpaceVim ] [11:24:30] [ Info ]         (.SpaceVim.d/):C:\Users\tanht\.SpaceVim.d/
[ SpaceVim ] [11:24:30] [ Info ] change to root:C:\Users\tanht
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
