### ISSUE TITLE
Sidebar is not works with another file tree except VimFiler

### ISSUE THREAD

**Issue by vkravets** [wsdjeg/SpaceVim#3200]
## Expected behavior, english is required
Sidebar should works in the same way which described here https://github.com/SpaceVim/SpaceVim/pull/2016 with `filemanager` != `vimfiler`

## The reproduce ways from Vim starting (Required!)
1. Change default file manager to `dfx`
```vim
[options]
filemanager = "defx"

[[layers]]
name = 'ui'
enable_sidebar = true
```
2. Enable sidebar

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.2
- SpaceVim version: 1.3.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'hybrid'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/vkravets/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'ctrlp-yank'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="git"
[[layers]]
  name="sudo"
[[layers]]
  name="ctrlp"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.2/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:58:11] [ Info ] Startup with no argv, current dir is used: ~/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:58:11] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [10:58:11] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:58:11] [ Info ] Start to find root for: 
[ SpaceVim ] [10:58:11] [ Info ]         (.git/):/Users/vkravets/work/opower-prometheus-metrics-bundle/.git/
[ SpaceVim ] [10:58:11] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:58:12] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [10:58:12] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:58:14] [ Info ] Start to find root for: /Users/vkravets/work/opower-prometheus-metrics-bundle/src/main/java/com/opower/dropwizard/metrics/MetricsRegistrar.java
[ SpaceVim ] [10:58:14] [ Info ]         (.git/):/Users/vkravets/work/opower-prometheus-metrics-bundle/.git/
[ SpaceVim ] [10:58:14] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:58:42] [ Info ] Start to find root for: /Users/vkravets/work/opower-prometheus-metrics-bundle/__Tagbar__.1
[ SpaceVim ] [10:58:42] [ Info ]         (.git/):/Users/vkravets/work/opower-prometheus-metrics-bundle/.git/
[ SpaceVim ] [10:58:42] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:58:42] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:59:06] [ Info ] Start to find root for: /Users/vkravets/work/opower-prometheus-metrics-bundle/SpaceVimLayers
[ SpaceVim ] [10:59:06] [ Info ]         (.git/):/Users/vkravets/work/opower-prometheus-metrics-bundle/.git/
[ SpaceVim ] [10:59:06] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:59:09] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
[ SpaceVim ] [10:59:32] [ Info ] Start to find root for: /var/folders/8h/l8f8xhy12298zbn222vshc_80000gn/T/nvimpcZva7/4/issue_report.md
[ SpaceVim ] [10:59:32] [ Info ] change to root:/Users/vkravets/work/opower-prometheus-metrics-bundle
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
