### ISSUE TITLE
Support formatting for *.tsx files 

### ISSUE THREAD

**Issue by kifirkin** [wsdjeg/SpaceVim#3221]
For now, `lang#typescript` layer and `neoformat` works only for pure `*.ts` files. When I'm trying to format `.tsx` file I've got an error:
```
Neoformat: formatter not defined for typescriptreact filetype
```

**Comment by PeterDing** [comment]
@alexmironof To format typescript files, you need to install following one:

https://github.com/sbdchd/neoformat/blob/33f7dfb231382998df77cf9fc8cef39778ec9449/autoload/neoformat/formatters/typescript.vim#L2

**Comment by kifirkin** [comment]
@PeterDing I've installed `prettier` and it works fine for pure `typescript (.ts)` files, but doesn't work for `typescriptreact (.tsx)`

**Comment by PeterDing** [comment]
@alexmironof I use `tsfmt`. It can format the `tsx` files.

**Comment by kifirkin** [comment]
@PeterDing  For me `neoformat` doesn't work with `tsfmt` for `.ts` due to https://github.com/SpaceVim/SpaceVim/issues/3008 and for `.tsx` I've got the same error

**Comment by PeterDing** [comment]
@alexmironof To format `ts` and `tsx`, `neoformat` and `prettier` both work for me without any exceptions.

I paste my config as following. Maybe it will help you.

- **~/.SpaceVim.d/init.toml**
```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "palenight"
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    default_indent = 4
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false

    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true

    # tagbar width
    sidebar_width = 20

    sidebar_direction = 'right'

    terminal_cursor_shape = 1

    bootstrap_before = "myspacevim#before"

    filemanager = "nerdtree"


# Enable autocomplete layer
[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
    auto-completion-complete-with-key-sequence = "nil"

[[layers]]
    name = 'checkers'

[[layers]]
    name = "denite"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'lang#javascript'
    enable_flow_syntax = true

[[layers]]
    name = 'lang#typescript'
```

- **~/.SpaceVim.d/autoload/myspacevim.vim**
```vim
func! myspacevim#before() abort

    " deoplete
    " {{{
    let g:deoplete#ignore_sources = {}
    let g:deoplete#ignore_sources._ = ['buffer', 'around']
    " }}}


    set virtualedit=onemore             " Allow for cursor beyond last character
    set splitright

    " open a NERDTree automatically when vim starts up if no files were specified
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    " }}}


    let g:neoformat_javascript_jsbeautify = {
        \ 'exe': 'js-beautify',
        \ 'stdin': 1,
        \ }
    let g:neoformat_typescript_prettier = {
        \ 'exe': 'prettier',
        \ 'args': ['--stdin', '--stdin-filepath', '"%:p"', '--parser', 'typescript'],
        \ 'stdin': 1
        \ }
    let g:neoformat_enabled_typescript = ['tsfmt', 'prettier']


    " show all uncompliable symbols
    set listchars=tab:>-,trail:~,extends:>,precedes:<
    set list


    " javascript
    let g:tern#command = ["tern"]
    let g:tern#arguments = ["--persistent"]


    " typescript
    let g:tagbar_type_typescript = {
        \ 'ctagstype': 'typescript',
        \ 'kinds': [
          \ 'c:classes',
          \ 'n:modules',
          \ 'f:functions',
          \ 'v:variables',
          \ 'v:varlambdas',
          \ 'm:members',
          \ 'i:interfaces',
          \ 'e:enums',
          \ 's:statics',
        \ ]
    \ }


    " disable ctags
    let g:gutentags_ctags_exclude = [ "*.js", "*.jsx", "*.ts", "*.tsx", "*.css", "build", "vendor", ".git", "node_modules", "*.vim/bundle/*", "out" ]

endf


" func! myspacevim#after() abort
" endf
```

----

### Environment

```
os mac
NVIM v0.3.8
SpaceVim 387288fc

$ which tsfmt                                                                                                                                        
/usr/local/bin/tsfmt

$ which prettier                                                                                                                                    
/usr/local/bin/prettier
```

**Comment by kifirkin** [comment]
@PeterDing Thanks a lot! finally I've found what exactly causes this issue.

```toml
[[custom_plugins]]
    name = "crusoexia/vim-monokai"
    merge = 0

[[custom_plugins]] # causes errors with neoformat
    name = "HerringtonDarkholme/yats.vim"
    merge = 0
```

I've used `yats.vim` for extended typescript syntax which causes formatting errors due to defining a new file type `typescriptreact` for `tsx` files
