### ISSUE TITLE
Deoplete with PHP autocomplete

### ISSUE THREAD

**Issue by mlapai** [wsdjeg/SpaceVim#3222]
@wsdjeg Hi, i cant make `deoplete` get `$this->` autocomplete on parent class (extended class) methods inside of child class, especially if there is more than one extended class, even tho i have generated ctags and gtags and i have installed `php-language-server`.

Im using following plugin for autocomplete (composer required for this):
```
[[custom_plugins]]
  name = 'lvht/phpcd.vim'
  build = 'composer install'
  merged = 0
  on_ft = 'php'
```
Am i doing something wrong in the following config ?

My SPDebugInfo:
### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['rafi/awesome-vim-colorschemes', {'name': 'rafi/awesome-vim-colorschemes', 'merged': 0}], ['arnaud-lb/vim-php-namespace', {'name': 'arnaud-lb/vim-php-namespace', 'merged': 0}], ['Rican7/php-doc-modded', {'name': 'Rican
7/php-doc-modded', 'merged': 0}], ['alvan/vim-php-manual', {'name': 'alvan/vim-php-manual', 'merged': 0}], ['stephpy/vim-php-cs-fixer', {'name': 'stephpy/vim-php-cs-fixer', 'merged': 0}], ['lvht/phpcd.vim', {'build': 'composer install', 'n
ame': 'lvht/phpcd.vim', 'merged': 0, 'on_ft': 'php'}], ['SirVer/ultisnips', {'name': 'SirVer/ultisnips', 'merged': 0}], ['sniphpets/sniphpets', {'name': 'sniphpets/sniphpets', 'merged': 0}], ['sniphpets/sniphpets-symfony', {'name': 'sniphp
ets/sniphpets-symfony', 'merged': 0}], ['algotech/ultisnips-php', {'name': 'algotech/ultisnips-php', 'merged': 0, 'on_ft': 'autocomplete'}], ['vim-vdebug/vdebug', {'name': 'vim-vdebug/vdebug', 'merged': 0}]]
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 0
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 100
  plugin_bundle_dir = '/home/unixporn/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Dockerfile.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 50
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```
### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
  auto-completion-delay=200
  auto-completion-complete-with-key-sequence='nil'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="gtags"
  gtagslabel='ctags'
[[layers]]
  name="tools"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="test"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#python"
  enable_typeinfo=1
[[layers]]
  name="lang#sh"

[[layers]]
  name="lang#javascript"
  auto_fix=0
  enable_flow_syntax=1
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lsp"
  filetypes=['php', 'python', 'sh', 'javascript', 'typescript', 'html', 'css', 'vue']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:

And then i have custom config `myspacevim.vim`:
```
function! myspacevim#after() abort

	" Only neccessary if using multiple tags
	" set path=.
  set tags+=.git/tags,tags

	"autoimport php namespace"
  function! IPhpInsertUse()
      call PhpInsertUse()
      call feedkeys('a',  'n')
  endfunction
  autocmd FileType php inoremap <Leader>u <Esc>:call IPhpInsertUse()<CR>
  autocmd FileType php noremap <Leader>u :call PhpInsertUse()<CR>

  function! IPhpExpandClass()
      call PhpExpandClass()
      call feedkeys('a', 'n')
  endfunction
  autocmd FileType php inoremap <Leader>e <Esc>:call IPhpExpandClass()<CR>
  autocmd FileType php noremap <Leader>e :call PhpExpandClass()<CR>
  let g:php_namespace_sort_after_insert = 1

	"autogenerate php docs"
	inoremap <C-P> <ESC>:call PhpDocSingle()<CR>i 
	nnoremap <C-P> :call PhpDocSingle()<CR> 
	vnoremap <C-P> :call PhpDocRange()<CR> 

	"update existing php docs"
	nnoremap <leader>h :call UpdatePhpDocIfExists()<CR>
	function! UpdatePhpDocIfExists()
			normal! k
			if getline('.') =~ '/'
					normal! V%d
			else
					normal! j
			endif
			call PhpDocSingle()
			normal! k^%k$
			if getline('.') =~ ';'
					exe "normal! $svoid"
			endif
	endfunction

	"remove function and class end comments"
	let g:pdv_cfg_autoEndFunction = 0
	let g:pdv_cfg_autoEndClass = 0

	"class doc configuration"
	let g:pdv_cfg_Author = ""
	let g:pdv_cfg_annotation_Author = 1
	let g:pdv_cfg_annotation_Package = 0
	let g:pdv_cfg_annotation_Version = 0
	let g:pdv_cfg_annotation_Copyright = 0
	let g:pdv_cfg_annotation_License = 0

	"PHP Manual for cursor word"
	let g:php_manual_online_search_shortcut = '<leader>k'



	"PHP REFORMAT CODE PHP-CS-FIXER"
	" If php-cs-fixer is in $PATH, you don't need to define line below
	let g:php_cs_fixer_path = "INSERT_YOUR_PATH_HERE"

	" If you use php-cs-fixer version 1.x
	let g:php_cs_fixer_level = "symfony"                   " options: --level (default:symfony)
	let g:php_cs_fixer_config = "default"                  " options: --config
	let g:php_cs_fixer_rules = "@PSR2"          " options: --rules (default:@PSR2)

	let g:php_cs_fixer_php_path = "php"               " Path to PHP
	let g:php_cs_fixer_enable_default_mapping = 1     " Enable the mapping by default (<leader>pcd)
	let g:php_cs_fixer_dry_run = 0                    " Call command with dry-run option
	let g:php_cs_fixer_verbose = 0                    " Return the output of command if 1, else an inline information.
	nnoremap <silent><leader>d :call PhpCsFixerFixDirectory()<CR>
	nnoremap <silent><leader>j :call PhpCsFixerFixFile()<CR>

	" update tags in background whenever you write a php file
	au BufWritePost *.php silent! !eval '[ -f ".git/hooks/ctags" ] && .git/hooks/ctags' &

	" Ultisnips
	let g:spacevim_snippet_engine = "ultisnips"
	let g:UltiSnipsExpandTrigger="<c-j>"
	let g:UltiSnipsJumpForwardTrigger="<c-j>"
	let g:UltiSnipsJumpBackwardTrigger="<c-b>"
	let g:ultisnips_php_scalar_types = 1

endfunction


function! myspacevim#before() abort
endfunction


```
