### ISSUE TITLE
Fuzzy finder doesn't work (denite)

### ISSUE THREAD

**Issue by blackxored** [wsdjeg/SpaceVim#3232]
## Expected behavior, english is required

Fuzzy finding to work 

## The reproduce ways from Vim starting (Required!)
Start NeoVim with denite layer.

```
[[layers]]
name="denite"
```

Open vim, press Leader f j (or any of the fuzzy finder bindings)
Vim just closes without any messages or errors.

## Debug info
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'bootstrap#after'
  bootstrap_before = 'bootstrap#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/blackxored/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-tmux'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="VersionControl"
[[layers]]
  name="shell"
[[layers]]
  name="colorscheme"
[[layers]]
  name="default"
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#purescript"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#vue"
[[layers]]
  name="tags"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:49:56] [ Info ] Startup with no argv, current dir is used: /private/tmp
[ SpaceVim ] [14:49:56] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [14:49:56] [ Info ] start to apply config [glob]
[ SpaceVim ] [14:49:56] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [14:49:57] [ Info ] Start to find root for: 
[ SpaceVim ] [14:49:57] [ Info ] change to root:/private/tmp
[ SpaceVim ] [14:49:57] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [14:49:57] [ Info ] change to root:/private/tmp
```
</details>

Config:
```
[options]
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filemanager = "nerdtree"
    bootstrap_before = "bootstrap#before"
    bootstrap_after = "bootstrap#after"
    
[[layers]]
  name = "VersionControl"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'checkers'
enable_neomake = true

[[layers]]
name = 'colorscheme'

[[layers]]
  name = "core#banner"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "core#tabline"

[[layers]]
  name = "core"

[[layers]]
  name = "default"

[[layers]]
  name = "fzf"

[[layers]]
  name = "format"

[[layers]]
  name = "git"

# [[layers]]
#  name = "github"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#extra"

#[[layers]]
#  name = "lang#haskell"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"

#[[layers]]
#  name = "lang#php"

#[[layers]]
#  name = "lang#purescript"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "gtags"
  # gtagslabel = "pygments"

[[layers]]
 name = "test"

#[[layers]]
#  name = "tmux"

# [[layers]]
#   name = "tools#dash"

# [[layers]]
#   name = "tools"

[[layers]]
  name = "ui"
  enable_sidebar = true
```
