### ISSUE TITLE
FlyGrep with NeoSolarized theme

### ISSUE THREAD

**Issue by blackxored** [wsdjeg/SpaceVim#3237]
## Expected behavior, english is required

When using the NeoSolarized theme, FlyGrep's buffer highlighted line is not highlighted at all.
As you can see in the screenshot below, pressing Tab or Shift-Tab to switch between results has no visible effect even while the functionality is there. 

## The reproduce ways from Vim starting (Required!)

Add this to config:
```toml
[[options]]
colorscheme = "NeoSolarized"
colorscheme_bg = "dark"

[[layers]]
name = "colorscheme"
```

## Debug info

This is outdated it seems, please update template?

## Screenshots

<img width="1791" alt="Screen Shot 2019-11-26 at 11 49 56 PM" src="https://user-images.githubusercontent.com/133308/69704016-824eb300-10a7-11ea-99b6-c8529ab9cfe3.png">

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
