### ISSUE TITLE
[Question] How to disable conceal within SpaceVim from config file

### ISSUE THREAD

**Issue by Gabirel** [wsdjeg/SpaceVim#3245]
## Expected behavior
Currently, I could disable vim `conceal` feature with latex via `let g:tex_conceal = ""` like below
![image](https://user-images.githubusercontent.com/12933851/70201909-e251f300-1752-11ea-9ce4-34e90ffa8077.png)

But how could I disable all conceal feature in all files within SpaceVim? Like no conceal in markdown.

How could I do this in `init.vim` and `init.toml` in both case?

#### In `tex`
Disable `conceal` feature with latex via `let g:tex_conceal = ""`

More details: https://github.com/Gabirel/Hack-SpaceVim/issues/44

#### In `markdown`
Disable `conceal` feature `let g:markdown_syntax_conceal = 0`
Ref: https://github.com/SpaceVim/SpaceVim/issues/3245#issuecomment-580730417

**Comment by wsdjeg** [comment]
Too many plugins use this feature, indentline vim-tex etc. spacevim do not change conceal option. you can config it in bootstrap function.

**Comment by wsdjeg** [comment]
in markdown layer, there is `let g:markdown_syntax_conceal = 0`, so it is disabled by default.

**Comment by strazto** [comment]
Loosely related, I want to change `R_assign`, or any of the similar settings for `Nvim-R`, but I'm finding the changes i make in bootstrap aren't working.

https://github.com/wsdjeg/Nvim-R/blob/42b8c8fce0d76c6538e519c80fd2142866372436/doc/Nvim-R.txt#L1172-L1215

my bootstrap:

```vim
function! rstudio#after() abort
  " set <M-->=^[-
  " let g:R_assign_map = '<M-->'
  let g:R_assign = 0
  " Build and install
  noremap <F5>b :call SpaceVim#plugins#runner#open('R CMD INSTALL --no-multiarch --with-keep.source .')<CR>
  " Run tests
  noremap <F5>t :call SpaceVim#plugins#runner#open('Rscript --no-save --no-restore -e devtools::test()')<CR>
endfunction
```

My init.toml:

```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    bootstrap_after = "rstudio#after"
    R_assign_map = '<M-->'
    R_assign = 0

[[layers]]
name = "lang#r"
repl_command = "R"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
```
