### ISSUE TITLE
SpaceVim not able to debug Java code by default

### ISSUE THREAD

**Issue by cthatcher-cb** [wsdjeg/SpaceVim#3254]
## Expected behavior, english is recommend
That when enabling the lang#java and debug layers that Java code would be debuggable without much additional setup. Currently struggling to figure out how to get java debugging to work as the VBGstartJDB command seems to be missing. Is there something that I missed or need to enable from a layer perspective?

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.4
- SpaceVim version: 1.4.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   config/plugins/gruvbox.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## The reproduce ways from Vim starting (Required!)
Attempting either of the following key strokes:

    SPC l d s => Not an editor command: VBGStartJDB
    SPC d l => read :h vebugger-launching
    Both of these keystrokes fail to initialize a JDB debugger for Java.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_updates = 1
  bootstrap_before = 'custom#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/colin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimproc.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  filetree_show_hidden=1
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="tmux"
[[layers]]
  name="colorscheme"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#java"
[[layers]]
  name="test"
[[layers]]
  name="debug"
[[layers]]
  name="gtags"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:12:59] [ Info ] Startup with no argv, current dir is used: ~/projects/project1
[ SpaceVim ] [13:12:59] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [13:12:59] [ Info ] start to apply config [glob]
[ SpaceVim ] [13:12:59] [ Info ] Start to find root for: 
[ SpaceVim ] [13:12:59] [ Info ]         (.git/):/home/colin/projects/project1/.git/
[ SpaceVim ] [13:12:59] [ Info ]         (pom.xml):/home/colin/projects/project1/pom.xml
[ SpaceVim ] [13:12:59] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:12:59] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [13:12:59] [ Info ] Start to find root for: /home/colin/projects/project1/NERD_tree_1
[ SpaceVim ] [13:12:59] [ Info ]         (.git/):/home/colin/projects/project1/.git/
[ SpaceVim ] [13:12:59] [ Info ]         (pom.xml):/home/colin/projects/project1/pom.xml
[ SpaceVim ] [13:12:59] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:13:01] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:13:03] [ Info ] Start to find root for: /home/colin/projects/project1/src/example.java
[ SpaceVim ] [13:13:03] [ Info ]         (.git/):/home/colin/projects/project1/.git/
[ SpaceVim ] [13:13:03] [ Info ]         (pom.xml):/home/colin/projects/project1/pom.xml
[ SpaceVim ] [13:13:03] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:14:24] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:14:24] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:14:24] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:14:25] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:14:25] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:14:25] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:20:57] [ Info ] Start to find root for: /home/colin/projects/project1/SpaceVimLayers
[ SpaceVim ] [13:20:57] [ Info ]         (.git/):/home/colin/projects/project1/.git/
[ SpaceVim ] [13:20:57] [ Info ]         (pom.xml):/home/colin/projects/project1/pom.xml
[ SpaceVim ] [13:20:57] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:21:13] [ Info ] Start to find root for: /tmp/nvimzuOYjn/4/issue_report.md
[ SpaceVim ] [13:21:13] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:21:13] [ Info ] Start to find root for: /tmp/nvimzuOYjn/4/issue_report.md
[ SpaceVim ] [13:21:13] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:21:13] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:32:04] [ Info ] change to root:/home/colin/projects/project1
[ SpaceVim ] [13:32:06] [ Info ] Start to find root for: /tmp/nvimzuOYjn/5/issue_report.md
[ SpaceVim ] [13:32:06] [ Info ] change to root:/home/colin/projects/project1
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
