### ISSUE TITLE
How to set colorscheme specific options? Especially italics in the gruvbox theme.

### ISSUE THREAD

**Issue by bric3** [wsdjeg/SpaceVim#3258]
**Is your feature request related to a problem? Please describe.**
Actually this is not a problem, but rather a documentation issue I think.

**Describe the solution you'd like**
Document how to set this kind of colorscheme settings using the toml file
https://github.com/SpaceVim/SpaceVim/blob/2e6aac03df0b426103a8a94c05371f8aca082f55/config/plugins/gruvbox.vim#L1

Currently I just don't understand how to do it with the TOML file.

**Describe alternatives you've considered**
* I tried the following changes in the toml file but this does not work :
```toml
[options]
  colorscheme = "gruvbox"
  ...
  gruvbox_italic = 1
```

```toml
gruvbox_italic = 1

[options]
  colorscheme = "gruvbox"
  ...
```

* I also tried adding a `~/.SpaceVim.d/init.vim` along with the existing `init.toml` file.

```vim
let g:gruvbox_italic = 1
```

But this doesn't work either, when the `init.toml` is there, this file is not even read (see [custom.vim L144](https://github.com/SpaceVim/SpaceVim/blob/40a43de7c079537c383a80bf60d466a8ade67454/autoload/SpaceVim/custom.vim#L144)).

**Additional context**
I've looked at other related issue, to find similar problems like :

* https://github.com/SpaceVim/SpaceVim/issues/3024
* https://github.com/SpaceVim/SpaceVim/issues/586
