### ISSUE TITLE
Python and R IDEs repl does not work as expected on Termux. 

### ISSUE THREAD

**Issue by linusjf** [wsdjeg/SpaceVim#3287]
https://github.com/SpaceVim/SpaceVim/issues/2754#issuecomment-573274002

SPC l r 
does not run the script within the REPL.

Another problem with lang#r:

Repl runs not in the same directory as file but its parent directory. This causes problem when a program expects input files in the same directory as R script.

```toml

#============================= == == == == == ============
#dark_powered.toml-- - dark powered configuration example for SpaceVim
#Copyright(c) 2016 - 2017 Wang Shidong &Contributors
#Author : Wang Shidong < wsdjeg at 163.com>
#URL : https: // spacevim.org
#License : GPLv3
#============================================================
#All SpaceVim option below[option] section
# This is a basic configuration example for SpaceVim

# All SpaceVim options are below [options] snippet
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_separator = "bar"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    # checkers options
    enable_statusline_mode = false
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
    name = "lilydjwg/colorizer"
    merged = false


[[layers]] 
    name = "lang#java"

[[layers]] 
    name = "lang#python"
    python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
    ]
    enable_typeinfo = true

[[layers]] 
    name = "lang#javascript"

[[layers]] 
    name = "lang#perl"

[[layers]] 
    name = "lang#ruby"

[[layers]] 
    name = "lang#c"

[[layers]] 
    name = "lang#r"
    repl_command = "R --vanilla"

[[layers]] 
    name = "format"

[[layers]]
    name = "checkers"

[[layers]] 
    name = 'shell' 
    default_position = 'top' 
    default_height = 30
```

The above is my init.toml configuration under directory .SpaceVim.d.

This isn't exactly per the issue template. Do let me know if you need any additional info.
