### ISSUE TITLE
Newly installed spacevim on Manajaro, can't run python program correctlly

### ISSUE THREAD

**Issue by superhxl** [wsdjeg/SpaceVim#3301]
## Debug info
SPDebugInfo
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/bruce/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDesc
ribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode light
ers']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.sv
g'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#latex"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [07:50:20] [ Info ] Startup with argv: ['bank.py']
[ SpaceVim ] [07:50:20] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [07:50:20] [ Info ] start to apply config [glob]
[ SpaceVim ] [07:50:20] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [07:50:20] [ Info ] Start to find root for: /home/bruce/Documents/coding/bank.py
[ SpaceVim ] [07:50:20] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:50:20] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:51:32] [ Info ] Start to find root for: /home/bruce/Documents/coding/__runner__
[ SpaceVim ] [07:51:32] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:51:32] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:51:32] [ Info ]    cmd:['', '/usr/bin/env', 'python', '-']
[ SpaceVim ] [07:54:18] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:55:26] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:55:31] [ Info ] Start to find root for: /home/bruce/Documents/coding/SpaceVimLayers
[ SpaceVim ] [07:55:31] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [07:56:39] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [08:13:18] [ Info ] Start to find root for: /home/bruce/Documents/coding/__runner__
[ SpaceVim ] [08:13:18] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [08:13:18] [ Info ] change to root:/home/bruce/Documents/coding
[ SpaceVim ] [08:13:18] [ Info ]    cmd:['', '/usr/bin/env', 'python', '-']
[ SpaceVim ] [08:13:30] [ Info ] Start to find root for: /home/bruce/Documents/coding/SpaceVimLayers
[ SpaceVim ] [08:13:30] [ Info ] change to root:/home/bruce/Documents/coding
```
</details>
## Screenshots

![](https://i.loli.net/2020/01/24/hXGsrA8iyetpDcF.png)
