### ISSUE TITLE
Installing DBExt Plugin fails. Where can I see the issue?

### ISSUE THREAD

**Issue by PeteW** [wsdjeg/SpaceVim#3349]
## Expected behavior
Adding the following to c:\users\ME\.SpaceVim.d\init.toml should install dbext plugin:
```
[[custom_plugins]]
name = 'vim-scripts/debext.vim'
```
I restart gvim, there is an attempt to install it. Eventually PlugManager reports fail.

I try to type `g` `f` with the cursor over the failed plugin display in PlugManager. I get the error: `error detected while processing function <SNR>206_open_plugin_dir: line 18: E475 invalid value for argument CWD`

I look in the log and I see 3 attempts to install the plugin, but no actual error:
```
[ SpaceVim ] [10:21:01] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 3
[ SpaceVim ] [10:21:03] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 2
[ SpaceVim ] [10:21:05] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 1
```
How do I figure out what the actual issue is with installing dbext?

## The reproduce ways from Vim starting (Required!)
Add the above to initi.toml and restart,

## Debug info
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 3
  checkinstall = 1
  colorscheme = 'base16-irblack'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['chrisbra/csv.vim', {'name': 'chrisbra/csv.vim'}], ['vim-scripts/ScrollColors', {'name': 'vim-scripts/ScrollColors'}], ['flazz/vim-colorschemes', {'name': 'flazz/vim-colorschemes'}], ['jceb/vim-orgmode', {'name': 'jceb/vim-orgmode'}], ['vim-scripts/DrawIt', {'name': 'vim-scripts/DrawIt'}], ['hashivim/vim-terraform', {'name': 'hashivim/vim-terraform'}], ['vim-scripts/debext.vim', {'name': 'vim-scripts/debext.vim'}]]
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\pweissbrod\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  tab_width = 4
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#clojure"
[[layers]]
  name="lang#python"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(C:\Program Files (x86)\Vim\vim80\gvim.exe)
version: 801
OS: windows
[shell, shellcmdflag, shellslash]: ['C:\windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:20:57] [ Info ] Startup with no argv, current dir is used: c:\Projects
[ SpaceVim ] [10:20:57] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [10:20:58] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:20:59] [ Info ] Start to find root for: c:/Projects/
[ SpaceVim ] [10:20:59] [ Info ] buffer name: 
[ SpaceVim ] [10:20:59] [ Info ] change to root: c:\Projects
[ SpaceVim ] [10:20:59] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [10:20:59] [ Info ] Start to find root for: c:/Projects/
[ SpaceVim ] [10:20:59] [ Info ] buffer name: 
[ SpaceVim ] [10:20:59] [ Info ] change to root: c:\Projects
[ SpaceVim ] [10:21:01] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 3
[ SpaceVim ] [10:21:03] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 2
[ SpaceVim ] [10:21:05] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 1
[ SpaceVim ] [10:21:33] [ Info ] buffer name: 
[ SpaceVim ] [10:21:33] [ Info ] change to root: c:\Projects
[ SpaceVim ] [10:21:33] [ Info ] buffer name: 
[ SpaceVim ] [10:21:33] [ Info ] change to root: c:\Projects
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
