### ISSUE TITLE
Dockerfile Language Server doesn't work

### ISSUE THREAD

**Issue by pbnj** [wsdjeg/SpaceVim#3350]
## Expected behavior, english is required

SpaceVim sets the filetype of Dockerfiles to `Dockerfile`, while LSP engines (`coc` in my case) expect `dockerfile` filetype.

This causes docker language server to not work in Dockerfiles.

### Prereqs

- Make sure language server is installed: `npm i -g dockerfile-language-server-nodejs`
- Enable LSP layer and register filetype: 
  ```toml
  [options]
  autocomplete_method = "coc"

  [[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
  
  [[layers]]
  name = 'lsp'
  filetypes = [ 'dockerfile' ]
  ```

### Steps

- Create `Dockerfile`: `touch Dockerfile && nvim Dockerfile`
- Unexpected Behavior: no LSP help, such as syntax errors, `K`, or <kbd>space</kbd> <kbd>l</kbd> <kbd>d</kbd>.
- Expected Behavior: LSP should be showing some errors, see screenshot below

### Workaround

Users must register `Dockerfile` filetype for LSP layer and provide an `override_cmd`:

```toml
[[layers]]
  name = 'lsp'
  filetypes = [
    'dockerfile',
    'Dockerfile',
  ]
  [layers.override_cmd]
  Dockerfile = ["docker-langserver", "--stdio"]
```

**Note**: WIthout the `override_cmd`, SpaceVim complains that there is no LSP for `Dockerfile`

## Debug info

N/A

### FileType: Dockerfile

![Screen Shot 2020-02-14 at 12 36 37 PM](https://user-images.githubusercontent.com/6811830/74565733-bb6c2600-4f26-11ea-86db-25f2a4fc87b5.png)

### FileType: dockerfile

![Screen Shot 2020-02-14 at 12 37 31 PM](https://user-images.githubusercontent.com/6811830/74565756-c757e800-4f26-11ea-9651-d9b5bb64ec7c.png)
