### ISSUE TITLE
Please add floating terminal window with session saving

### ISSUE THREAD

**Issue by rot88** [wsdjeg/SpaceVim#3376]
It would be very handy if there was a terminal that won't destroy my grid and I could open and close it wherever and whenever I want to, but the way it won't lose it's contents when I re-open it.

I'm a total newbie in `vim` so I can't help with examples.

It'd be great if the terminal appeared in the bottom of the screen and resized upwards as command output was produced just like it does the menu that is open when I press `Space`.

**Comment by wsdjeg** [comment]
This has been added in #3377, to use float terminal, just need to load the shell layer via:

```toml
[[layers]]
    name = 'shell'
    default_position = 'float'
    default_height = 30
```
