### ISSUE TITLE
Error while pressing SPC g s with git layer enabled

### ISSUE THREAD

**Issue by mkurop** [wsdjeg/SpaceVim#3433]
## Expected behavior, english is required
After pressing SPC g s in vim with spacevim git layer the status of the git repo should be displayed
## The reproduce ways from Vim starting (Required!)
After initializing repo from the CLI and loading a file in vim pressing SPC g s causes the following error:

Error detected while processing function dein#autoload#_on_cmd[13]..git#run[9]..git#status#run[1]..<SNR>230_openStatusBuffer:
line   10:
E119: Not enough arguments for function: bufnr
E15: Invalid expression: bufnr()
Press ENTER or type command to continue

after pressing ENTER the attached screen shows up, see the screenshot

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.0.1813
- neovim version: -
- SpaceVim version: 1.4.0
- SpaceVim status: 

```
# On branch master
nothing to commit, working directory clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/marcin/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/marcin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-gitgutter'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.4.0'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="git"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim(/usr/bin/gvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gtk, or build from sources.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:01:46] [ Info ] Startup with no argv, current dir is used: ~/ncbir
[ SpaceVim ] [16:01:46] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [16:01:46] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:01:46] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [16:01:46] [ Info ] Start to find root for: /home/marcin/ncbir/
[ SpaceVim ] [16:01:46] [ Info ]         (.git/):/home/marcin/ncbir
[ SpaceVim ] [16:01:46] [ Info ] buffer name: 
[ SpaceVim ] [16:01:46] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:01:46] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [16:01:47] [ Info ] buffer name: 
[ SpaceVim ] [16:01:47] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:01:49] [ Info ] Start to find root for: /home/marcin/ncbir/plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:01:49] [ Info ]         (.git/):/home/marcin/ncbir
[ SpaceVim ] [16:01:49] [ Info ] buffer name: /home/marcin/ncbir/plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:01:49] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:01:53] [ Info ] Start to find root for: git:/status
[ SpaceVim ] [16:01:53] [ Info ] buffer name: git://status
[ SpaceVim ] [16:01:53] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:23:31] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:23:31] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:24:51] [ Info ] Start to find root for: /home/marcin/ncbir/SpaceVimLayers
[ SpaceVim ] [16:24:51] [ Info ]         (.git/):/home/marcin/ncbir
[ SpaceVim ] [16:24:51] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [16:24:51] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:25:12] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:25:12] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:27:51] [ Info ] buffer name: git://status
[ SpaceVim ] [16:27:51] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:28:25] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:28:25] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:28:38] [ Info ] buffer name: git://status
[ SpaceVim ] [16:28:38] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:28:40] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:28:40] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:28:55] [ Info ] Start to find root for: git:/status
[ SpaceVim ] [16:28:55] [ Info ] buffer name: git://status
[ SpaceVim ] [16:28:55] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:29:07] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:29:07] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:32:53] [ Info ] buffer name: git://status
[ SpaceVim ] [16:32:53] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:32:55] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:32:55] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:33:09] [ Info ] Start to find root for: git:/status
[ SpaceVim ] [16:33:09] [ Info ] buffer name: git://status
[ SpaceVim ] [16:33:09] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:33:41] [ Info ] buffer name: plan_prac_badawczo_rozwojowych.txt
[ SpaceVim ] [16:33:41] [ Info ] change to root: /home/marcin/ncbir
[ SpaceVim ] [16:34:01] [ Info ] Start to find root for: /tmp/vxglLMo/9/issue_report.md
[ SpaceVim ] [16:34:01] [ Info ] buffer name: /tmp/vxglLMo/9/issue_report.md
[ SpaceVim ] [16:34:01] [ Info ] change to root: /home/marcin/ncbir
```
</details>

## Screenshots

![Screenshot from 2020-04-05 16-16-22](https://user-images.githubusercontent.com/34960598/78500832-110bc480-7759-11ea-8522-a73bfac208af.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
