### ISSUE TITLE
SpaceVim :: statusline :: vim-fugitive :: Branch depiction not properly spaced

### ISSUE THREAD

**Issue by lcrockett** [wsdjeg/SpaceVim#3447]
## Expected behavior, english is recommend
Proper spacing within status line right of Git branch depiction using vim-fugitive.

## Environment Information

- OS: mac
- vim version: 8.2.550
- neovim version: -
- SpaceVim version: 1.5.0-dev
- SpaceVim status:

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Opening any file that lives within a Git controlled repository folder.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_after = 'bootstrap#after'
  bootstrap_before = 'bootstrap#before'
  buffer_index_type = 3
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['pearofducks/ansible-vim', {'name': 'pearofducks/ansible-vim', 'merged': 0}], ['haya14busa/is.vim', {'name': 'haya14busa/is.vim', 'merged': 0}], ['tmsvg/pear-tree', {'name': 'tmsvg/pear-tree', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0}], ['blueyed/vim-diminactive', {'name': 'blueyed/vim-diminactive', 'merged': 0}], ['simnalamburt/vim-mundo', {'name': 'simnalamburt/vim-mundo', 'merged': 0}], ['tmux-plugins/vim-tmux-focus-events', {'name': 'tmux-plugins/vim-tmux-focus-events', 'merged': 0}], ['Shougo/vimproc.vim', {'name': 'Shougo/vimproc.vim', 'merged': 0}], ['sjl/vitality.vim', {'name': 'sjl/vitality.vim', 'merged': 0}]]
  data_dir = '/Users/lcrockett/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 'true'
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/lcrockett/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Unite-sources'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'nil'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'minor mode lighters', 'syntax checking', 'version control info', 'vcs', 'hunks']
  statusline_right_sections = ['search status', 'fileformat', 'cursorpos', 'percentage', 'input method', 'time']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 1
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=0
[[layers]]
  name="core"
  filetree_show_hidden=1
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="indentmove"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#xml"
[[layers]]
  name="operator"
[[layers]]
  name="shell"
  default_height=30
  default_position='bottom'
[[layers]]
  name="sudo"
[[layers]]
  name="tmux"
[[layers]]
  name="unite"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(vi)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:24:30] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [19:24:30] [ Info ] find local conf: /Users/lcrockett/.SpaceVim.d/init.toml
[ SpaceVim ] [19:24:30] [ Info ] loading cached local conf: /Users/lcrockett/.cache//SpaceVim/conf/_Users_lcrockett__SpaceVim_d_init_toml.json
[ SpaceVim ] [19:24:30] [ Info ] start to apply config [local]
[ SpaceVim ] [19:24:30] [ Info ] Initializing :: Function :: bootstrap#before
[ SpaceVim ] [19:24:30] [ Info ] Initialized :: Function :: bootstrap#before
[ SpaceVim ] [19:24:30] [ Info ] Start to find root for: /Users/lcrockett/
[ SpaceVim ] [19:24:30] [ Info ]         (.SpaceVim.d/):/Users/lcrockett
[ SpaceVim ] [19:24:30] [ Info ] buffer name:
[ SpaceVim ] [19:24:30] [ Info ] change to root: /Users/lcrockett
[ SpaceVim ] [19:24:30] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [19:24:30] [ Info ] buffer name:
[ SpaceVim ] [19:24:30] [ Info ] change to root: /Users/lcrockett
[ SpaceVim ] [19:24:30] [ Info ] Initializing :: Function :: bootstrap#after
[ SpaceVim ] [19:24:30] [ Info ] Initialized :: Function :: bootstrap#after
[ SpaceVim ] [19:24:32] [ Info ] Start to find root for: /private/var/folders/xl/510q8tfj5w717fthcyg5vvnr0009rh/T/vo8JrBd/2/issue_report.md
[ SpaceVim ] [19:24:32] [ Info ] buffer name: /var/folders/xl/510q8tfj5w717fthcyg5vvnr0009rh/T/vo8JrBd/2/issue_report.md
[ SpaceVim ] [19:24:32] [ Info ] change to root: /Users/lcrockett
```
</details>

## Screenshots

![spacevim-statusline-00](https://user-images.githubusercontent.com/58056722/79255110-0bfbf300-7e86-11ea-941a-e02afe8c594d.jpg)
