### ISSUE TITLE
Python - `not` keyword not syntax highlighted

### ISSUE THREAD

**Issue by cipherboy** [wsdjeg/SpaceVim#3462]
## Expected behavior, english is required

In Python, `not` is a keyword. The usually gets syntax highlighted.

I'm guessing this should probably be moved to a different project, but I need help identifying exactly which one. 

## The reproduce ways from Vim starting (Required!)

1. Create a new python file with following contents:
    ```python
    empty = False
    if not empty:
        print("Here!")
    ```
2. Open it in SpaceVim (e.g., `vim file.py`)

![Screenshot from 2020-04-19 09-03-27](https://user-images.githubusercontent.com/914030/79688498-b07e8c00-821c-11ea-93ad-0091589d2cda.png)

3. Open it with Fedora defualt config (e.g., `vim -u /etc/vimrc`).

![Screenshot from 2020-04-19 09-03-41](https://user-images.githubusercontent.com/914030/79688502-b4aaa980-821c-11ea-9c11-c347bd2d49c1.png)

## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'ron'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/cipherboy/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/cipherboy/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-fish'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lsp"
  filetypes=['javascript', 'html', 'css', 'python', 'sh', 'go']
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#python"
  enable_typeinfo=1
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#markdown"
  listItemIndent='tab'
[[layers]]
  name="lang#sh"
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:04:43] [ Info ] Startup with argv: ['sample.py']
[ SpaceVim ] [09:04:43] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [09:04:43] [ Info ] start to apply config [glob]
[ SpaceVim ] [09:04:44] [ Info ] Start to find root for: /home/cipherboy/GitHub/cipherboy/hist-ng/histng/sample.py
[ SpaceVim ] [09:04:44] [ Info ]         (.git/):/home/cipherboy/GitHub/cipherboy/hist-ng
[ SpaceVim ] [09:04:44] [ Info ] buffer name: sample.py
[ SpaceVim ] [09:04:44] [ Info ] change to root: /home/cipherboy/GitHub/cipherboy/hist-ng
[ SpaceVim ] [09:04:44] [ Info ] buffer name: histng/sample.py
[ SpaceVim ] [09:04:44] [ Info ] change to root: /home/cipherboy/GitHub/cipherboy/hist-ng
[ SpaceVim ] [09:04:46] [ Info ] Start to find root for: /home/cipherboy/GitHub/cipherboy/hist-ng/SpaceVimLayers
[ SpaceVim ] [09:04:46] [ Info ]         (.git/):/home/cipherboy/GitHub/cipherboy/hist-ng
[ SpaceVim ] [09:04:46] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [09:04:46] [ Info ] change to root: /home/cipherboy/GitHub/cipherboy/hist-ng
[ SpaceVim ] [09:05:13] [ Info ] buffer name: histng/sample.py
[ SpaceVim ] [09:05:13] [ Info ] change to root: /home/cipherboy/GitHub/cipherboy/hist-ng
[ SpaceVim ] [09:05:58] [ Info ] Start to find root for: /tmp/v1UixCw/6/issue_report.md
[ SpaceVim ] [09:05:58] [ Info ] buffer name: /tmp/v1UixCw/6/issue_report.md
[ SpaceVim ] [09:05:58] [ Info ] change to root: /home/cipherboy/GitHub/cipherboy/hist-ng
```
</details>

Note that I have `python-language-server` installed which uses `Jedi`; `vim-jedi` seems to work just fine highlighting `not` keyword. I'm running the latest `jedi`, `v0.17.0`.

## Screenshots

See above, inline.
