### ISSUE TITLE
Error while trying to get :help for anything, "Garbage after pattern... Invalid argument: helpHeadline"

### ISSUE THREAD

**Issue by Datamance** [wsdjeg/SpaceVim#3476]
## Expected behavior, english is recommend

Using `:help` shouldn't throw errors. Instead,I see this (also in first screenshot):

```
Error detected while processing /Users/ricorodriguez/.SpaceVim/after/syntax/help.vim:
line    3:
E402: Garbage after pattern: "^[-A-Z .][-A-Z0-9 .()_#]*\ze\(\s\+\*\|$\)"^M
E475: Invalid argument: helpHeadline "^[-A-Z .][-A-Z0-9 .()_#]*\ze\(\s\+\*\|$\)"^M
```

For the record, my `:checkhealth` output looks fine, as you can see in the second screenshot below.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

try to use `:help`

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/ricorodriguez/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/ricorodriguez/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:42:54] [ Info ] Startup with argv: ['main.py']
[ SpaceVim ] [00:42:54] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [00:42:54] [ Info ] start to apply config [glob]
[ SpaceVim ] [00:42:54] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:42:54] [ Info ] Start to find root for: /Users/ricorodriguez/Experiments/hq/hq/main.py
[ SpaceVim ] [00:42:54] [ Info ] buffer name: main.py
[ SpaceVim ] [00:42:54] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:42:54] [ Info ] buffer name: main.py
[ SpaceVim ] [00:42:54] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:42:58] [ Info ] Start to find root for: /Users/ricorodriguez/Experiments/hq/hq/
[ SpaceVim ] [00:42:58] [ Info ] buffer name: 
[ SpaceVim ] [00:42:58] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:42:58] [ Info ] Start to find root for: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/index.txt
[ SpaceVim ] [00:42:58] [ Info ] buffer name: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/index.txt
[ SpaceVim ] [00:42:58] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:43:15] [ Info ] Start to find root for: /Users/ricorodriguez/Experiments/hq/hq/SpaceVimLayers
[ SpaceVim ] [00:43:15] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [00:43:15] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:45:33] [ Info ] buffer name: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/index.txt
[ SpaceVim ] [00:45:33] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:45:35] [ Info ] buffer name: main.py
[ SpaceVim ] [00:45:35] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:45:40] [ Info ] Start to find root for: /Users/ricorodriguez/Experiments/hq/hq/
[ SpaceVim ] [00:45:40] [ Info ] buffer name: 
[ SpaceVim ] [00:45:40] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:45:40] [ Info ] Start to find root for: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/insert.txt
[ SpaceVim ] [00:45:40] [ Info ] buffer name: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/insert.txt
[ SpaceVim ] [00:45:40] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:45:49] [ Info ] buffer name: main.py
[ SpaceVim ] [00:45:49] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
[ SpaceVim ] [00:46:08] [ Info ] Start to find root for: /private/var/folders/wt/xh46t1fx79n2xhxlx74q0t680000gn/T/nvim04zaI5/2/issue_report.md
[ SpaceVim ] [00:46:08] [ Info ] buffer name: /var/folders/wt/xh46t1fx79n2xhxlx74q0t680000gn/T/nvim04zaI5/2/issue_report.md
[ SpaceVim ] [00:46:08] [ Info ] change to root: /Users/ricorodriguez/Experiments/hq/hq
```
</details>

## Screenshots
![image](https://user-images.githubusercontent.com/8699411/80176094-8125a180-85c5-11ea-9c7b-5cbf41306a24.png)

![image](https://user-images.githubusercontent.com/8699411/80176324-32c4d280-85c6-11ea-8771-e1fd921ccf1a.png)

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
