### ISSUE TITLE
SpaceVim always change root to my home diectory when i opened a file

### ISSUE THREAD

**Issue by jidibinlin** [wsdjeg/SpaceVim#3510]
## Expected behavior, english is recommend
Spacevim won`t change the working directory (or the project management not work?) to current project root
## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	coc-settings.json

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['Yggdroot/LeaderF', {'name': 'Yggdroot/LeaderF'}], ['dominikduda/vim_current_word', {'name': 'dominikduda/vim_current_word'}], ['jackguo380/vim-lsp-cxx-highlight', {'name': 'jackguo380/vim-lsp-cxx-highlight'}], ['luochen1990/rainbow', {'name': 'luochen1990/rainbow'}], ['puremourning/vimspector', {'name': 'puremourning/vimspector'}], ['jaxbot/semantic-highlight.vim', {'name': 'jaxbot/semantic-highlight.vim'}]]
  data_dir = '/home/qibin/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  layer_lang_java_formatter = '/opt/google-java-format/google-java-format.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/qibin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'emmet-vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
  enable=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#c"
  libclang_path='/usr/lib/x86_64-linux-gnu'
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="colorscheme"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#html"
[[layers]]
  name="sudo"
[[layers]]
  name="lsp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:07:24] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [17:07:24] [ Info ] find local conf: /home/qibin/.SpaceVim.d/init.toml
[ SpaceVim ] [17:07:24] [ Info ] loading cached local conf: /home/qibin/.cache//SpaceVim/conf/_home_qibin__SpaceVim_d_init_toml.json
[ SpaceVim ] [17:07:24] [ Info ] start to apply config [local]
[ SpaceVim ] [17:07:24] [ Info ] Start to find root for: /home/qibin/
[ SpaceVim ] [17:07:24] [ Info ]         (.SpaceVim.d/):/home/qibin
[ SpaceVim ] [17:07:24] [ Info ] buffer name: 
[ SpaceVim ] [17:07:24] [ Info ] change to root: /home/qibin
[ SpaceVim ] [17:07:24] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:07:25] [ Info ] buffer name: 
[ SpaceVim ] [17:07:25] [ Info ] change to root: /home/qibin
[ SpaceVim ] [17:07:28] [ Info ] Start to find root for: /home/qibin/[defx] -0
[ SpaceVim ] [17:07:28] [ Info ]         (.SpaceVim.d/):/home/qibin
[ SpaceVim ] [17:07:28] [ Info ] buffer name: [defx] -0
[ SpaceVim ] [17:07:28] [ Info ] change to root: /home/qibin
[ SpaceVim ] [17:07:36] [ Info ] buffer name: 
[ SpaceVim ] [17:07:36] [ Info ] change to root: /home/qibin
[ SpaceVim ] [17:07:37] [ Info ] Start to find root for: /home/qibin/code/PopMenu2/src/main/java/PopMenu2/App.java
[ SpaceVim ] [17:07:37] [ Info ]         (pom.xml):/home/qibin/code/PopMenu2
[ SpaceVim ] [17:07:37] [ Info ]         (.SpaceVim.d/):/home/qibin
[ SpaceVim ] [17:07:37] [ Info ] buffer name: /home/qibin/code/PopMenu2/src/main/java/PopMenu2/App.java
[ SpaceVim ] [17:07:37] [ Info ] change to root: /home/qibin
[ SpaceVim ] [17:11:41] [ Info ] Start to find root for: /tmp/nvimcwXkqa/3/issue_report.md
[ SpaceVim ] [17:11:41] [ Info ] buffer name: /tmp/nvimcwXkqa/3/issue_report.md
[ SpaceVim ] [17:11:41] [ Info ] change to root: /home/qibin
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
