### ISSUE TITLE
Bug : Colorscheme doesn't get installed correctly

### ISSUE THREAD

**Issue by SlyBouhafs** [wsdjeg/SpaceVim#3513]
## Expected behavior

Apply the Dracula Colorscheme installed in the custom_settings section.

[Dracula colorscheme](https://draculatheme.com/vim)

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

Add those those lines to init.toml :

```
[options]
colorscheme = "dracula"
```

```
[[custom_plugins]]
name = "dracula/vim"
merged = 0
```
Then run :SPupdate, everything installs correctly without any errors.

Restart Spacevim and the colorscheme doesn't get applied.

Try :colorscheme dracula, it only applies to the syntax.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'dracula'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['dracula/vim', {'name': 'dracula/vim', 'merged': 0}]]
  data_dir = '/Users/sly/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '*'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'FuraCode Nerd Font:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/sly/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Denite-sources'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 2
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
  enable=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#elm"
[[layers]]
  name="colorscheme"
  enable=1
[[layers]]
  name="ale"
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:15:26] [ Info ] Startup with argv: ['.SpaceVim.d/autoload/myspacevim.vim']
[ SpaceVim ] [19:15:26] [ Info ] find local conf: /Users/sly/.SpaceVim.d/init.toml
[ SpaceVim ] [19:15:26] [ Info ] loading cached local conf: /Users/sly/.cache//SpaceVim/conf/_Users_sly__SpaceVim_d_init_toml.json
[ SpaceVim ] [19:15:26] [ Info ] start to apply config [local]
[ SpaceVim ] [19:15:26] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [19:15:30] [ Info ] Start to find root for: /Users/sly/.SpaceVim.d/autoload/myspacevim.vim
[ SpaceVim ] [19:15:30] [ Info ]         (.SpaceVim.d/):/Users/sly
[ SpaceVim ] [19:15:30] [ Info ] buffer name: .SpaceVim.d/autoload/myspacevim.vim
[ SpaceVim ] [19:15:30] [ Info ] change to root: /Users/sly
[ SpaceVim ] [19:15:30] [ Info ] buffer name: .SpaceVim.d/autoload/myspacevim.vim
[ SpaceVim ] [19:15:30] [ Info ] change to root: /Users/sly
[ SpaceVim ] [19:15:39] [ Info ] Start to find root for: /private/var/folders/rf/m9w82tr10254xkv4yycgttjc0000gp/T/nvimCjJ9y9/3/issue_report.md
[ SpaceVim ] [19:15:39] [ Info ] buffer name: /var/folders/rf/m9w82tr10254xkv4yycgttjc0000gp/T/nvimCjJ9y9/3/issue_report.md
[ SpaceVim ] [19:15:39] [ Info ] change to root: /Users/sly
```
</details>

## Screenshots
![Capture d’écran 2020-05-06 à 7 24 58 PM](https://user-images.githubusercontent.com/1410462/81214165-56791700-8fcf-11ea-95c8-d3776f42f5c9.png)
