### ISSUE TITLE
Latex commands rendered as unicode

### ISSUE THREAD

**Issue by thilofischer** [wsdjeg/SpaceVim#3526]
## Expected behavior, english is required
When editing a LaTeX file, the written text should be shown.
Instead LaTeX commands (such as \subset) are displayed as unicode characters.
There should be a key-mapping to enable / disable this behavior.

## The reproduce ways from Vim starting (Required!)
Open Minimal Latex file:
```
\documentclass{article}
\begin{document}
  \begin{equation}
    V \subset S
  \end{equation}
\end{document}

```

The `\subset` will be rendered as `⊂`.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	autoload/SpaceVim/mapping/guide/theme/OceanicNext.vim

nothing added to commit but untracked files present (use "git add" to track)
```
/* The untracked file is just a colorscheme I am working on */

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['ap/vim-css-color', {'name': 'ap/vim-css-color', 'merged': 0}]]
  data_dir = '/home/thilo/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/thilo/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-debug'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_delay=100
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
  auto_completion_complete_with_key_sequence='jk'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="sudo"
[[layers]]
  name="fzf"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#latex"
[[layers]]
  name="debug"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvim3irpCW/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:18:37] [ Info ] Startup with argv: ['presentation.tex']
[ SpaceVim ] [12:18:37] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [12:18:37] [ Info ] start to apply config [glob]
[ SpaceVim ] [12:18:37] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [12:18:38] [ Info ] Start to find root for: /home/thilo/uni/dynamic_mis/latex/presentation.tex
[ SpaceVim ] [12:18:38] [ Info ]         (.git/):/home/thilo/uni/dynamic_mis
[ SpaceVim ] [12:18:38] [ Info ] buffer name: presentation.tex
[ SpaceVim ] [12:18:38] [ Info ] change to root: /home/thilo/uni/dynamic_mis
[ SpaceVim ] [12:18:38] [ Info ] buffer name: latex/presentation.tex
[ SpaceVim ] [12:18:38] [ Info ] change to root: /home/thilo/uni/dynamic_mis
[ SpaceVim ] [12:18:47] [ Info ] Start to find root for: /tmp/nvimJ23vHX/2/issue_report.md
[ SpaceVim ] [12:18:47] [ Info ] buffer name: /tmp/nvimJ23vHX/2/issue_report.md
[ SpaceVim ] [12:18:47] [ Info ] change to root: /home/thilo/uni/dynamic_mis
```
</details>

## Screenshots
![unicode](https://user-images.githubusercontent.com/24853577/81671801-a9c4ec80-9449-11ea-901f-ac70b542ca3b.png)
