### ISSUE TITLE
Error (typos) in gtags plugin.

### ISSUE THREAD

**Issue by mirsemen** [wsdjeg/SpaceVim#3538]
## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.5.0
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	fp.dir

nothing added to commit but untracked files present (use "git add" to track)
```

<details><summary> '$HOME/.SpaceVim.d/*' files</summary> 

### '$HOME/.SpaceVim.d/init.toml' file:
```toml

[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    enable_vimfiler_gitstatus = true
    filemanager = "defx"
    bootstrap_before = "config#before"
    bootstrap_after  = "config#after"
    default_indent   = 4
    max_column       = 80

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  clang_executable = "/home/sem/distrib/clang-git/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"
  merged = false

[[custom_plugins]]
name = 'Mizuchi/STL-Syntax'
merged = false

[[custom_plugins]]
name = 'matze/vim-meson'
merged = false
```

### '$HOME/.SpaceVim.d/autoload/config.vim' file:
```vim

function! config#before() abort
  " let g:cmake_ycm_symlinks = 1
  " let g:cmake_build_dir = 'build'
  " let g:cmake_export_compile_commands = 1
  " let g:cmake_ycm_symlinks = 1
endfunction

function! config#after() abort
    echom 'Set makeprg to Ninja'
    set makeprg=ninja\ -C\ build
    set cc=80
    set foldmethod=marker
    set foldlevel=99
    set foldcolumn=2
    map <silent> <F9> :make<CR>
    map <silent> <F10> :call SpaceVim#plugins#runner#run_task({'options': {'cwd': '/home/sem/projects/sas60/build/sas/'}, 'isBackground': 1, 'command':'./sas60','args':['-t2 -v -f2']})<CR>
    let g:neomake_c_enabled_makers = ['clangtidy']
    let g:neomake_cpp_enabled_makers = ['clangtidy']
    set cpoptions+=$

    nmap <leader>c :call OpenFileCppHpp(expand('%:p:r').".cpp")<CR>
    nmap <leader>h :call OpenFileCppHpp(expand('%:p:r').".hpp")<CR>
    nmap <leader>n :noh<CR>
endfunction

function OpenFileCppHpp(name)
    if filereadable(a:name)
        execute 'edit' a:name
    else
        echo "File '".a:name."' does not exist"
    endif
endfunction
```
</details>

## The reproduce ways from NeoVim starting
After pressing ```<Space>mgc```, the database of tag files is not created.
Tag's cache dir is empty:
```
# ls -l .cache/SpaceVim/tags/_home_sem_projects_sas60_
total 0
```
And then, after pressing ```<Space>mgd``` the plugin reports an error:
```
Error: global command failed. command line: global --resilt=ctags-x -qde 'set'
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'config#after'
  bootstrap_before = 'config#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['Mizuchi/STL-Syntax', {'name': 'Mizuchi/STL-Syntax', 'merged': 0}], ['matze/vim-meson', {'name': 'matze/vim-meson', 'merged': 0}]]
  data_dir = '/home/sem/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 80
  plugin_bundle_dir = '/home/sem/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'gtags.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
  clang_executable='/home/sem/distrib/clang-git/bin/clang'
[[layers]]
  name="gtags"
  gtagslabel='ctags'
  merged=0
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:18:24] [ Info ] Startup with no argv, current dir is used: ~/projects/sas60
[ SpaceVim ] [20:18:24] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [20:18:24] [ Info ] start to apply config [glob]
[ SpaceVim ] [20:18:24] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [20:18:24] [ Info ] Start to find root for: /home/sem/projects/sas60/
[ SpaceVim ] [20:18:24] [ Info ]         (.git/):/home/sem/projects/sas60
[ SpaceVim ] [20:18:24] [ Info ]         (.SpaceVim.d/):/home/sem/projects/sas60
[ SpaceVim ] [20:18:24] [ Info ] buffer name: 
[ SpaceVim ] [20:18:24] [ Info ] change to root: /home/sem/projects/sas60
[ SpaceVim ] [20:18:25] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [20:18:25] [ Info ] buffer name: 
[ SpaceVim ] [20:18:25] [ Info ] change to root: /home/sem/projects/sas60
[ SpaceVim ] [20:18:38] [ Info ] Start to find root for: /home/sem/projects/sas60/SpaceVimLayers
[ SpaceVim ] [20:18:38] [ Info ]         (.git/):/home/sem/projects/sas60
[ SpaceVim ] [20:18:38] [ Info ]         (.SpaceVim.d/):/home/sem/projects/sas60
[ SpaceVim ] [20:18:38] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [20:18:38] [ Info ] change to root: /home/sem/projects/sas60
[ SpaceVim ] [20:19:15] [ Info ] buffer name: 
[ SpaceVim ] [20:19:15] [ Info ] change to root: /home/sem/projects/sas60
[ SpaceVim ] [20:19:24] [ Info ] Start to find root for: /tmp/nvimTpMcgn/1/issue_report.md
[ SpaceVim ] [20:19:24] [ Info ] buffer name: /tmp/nvimTpMcgn/1/issue_report.md
[ SpaceVim ] [20:19:24] [ Info ] change to root: /home/sem/projects/sas60
```
</details>

## Solution

File ```/home/sem/.cache/vimfiles/repos/github.com/SpaceVim/gtags.vim/autoload/gtags.vim``` at function:
```vim
function! gtags#update(single_update) abort
```
1. Line: 461: Typo: ```-gtagslabel``` needs two '-' characters.
```vim
...
    if !empty(g:gtags_gtagslabel)
        let cmd += ['--gtagslabel=' . g:gtags_gtagslabel] " typo: option need two '--' characters
    endif
...
```

2. Line 466: GNU gtags doesn't have such an option ```--skip-unreadable```.
```vim
...
    if a:single_update && filereadable(dir . '/GTAGS')
        let cmd += ['--single-update', expand('%:p')]
    " else
        " let cmd += ['--skip-unreadable'] " The GNU 'gtags' doesn't have such an option
    endif
...
```
