### ISSUE TITLE
Make all trailing whitespace visible

### ISSUE THREAD

**Issue by ruzickap** [wsdjeg/SpaceVim#3548]
## Expected behavior, english is required

I'm trying to enable "trailing whitespace visible" feature. I was previously described here: https://github.com/SpaceVim/SpaceVim/issues/1266, but I'm not able to make it working according the steps described in the issue.

I would like to achive this beahvaior:

![https://camo.githubusercontent.com/cceb11abfea4eb4359a8147074b85219e5b4314f/687474703a2f2f692e696d6775722e636f6d2f537437794874682e706e67](https://camo.githubusercontent.com/cceb11abfea4eb4359a8147074b85219e5b4314f/687474703a2f2f692e696d6775722e636f6d2f537437794874682e706e67)

## Environment Information

- OS: linux
- vim version: 8.2.694
- neovim version: -
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting

I do have this configuration:

```bash
$ cat ~/.SpaceVim.d/init.toml
[options]
relativenumber = false
bootstrap_after = "myconfig#after"

# right sections of statusline
statusline_right_sections = [
   'cursorpos',
   'percentage',
   'input method',
   'whitespace'
]

$ cat ~/.SpaceVim.d/autoload/myconfig.vim
set mouse = ""
set nonumber
let g:spacevim_enable_vimfiler_welcome = 0
let g:better_whitespace_enabled = 1
let g:strip_whitespace_on_save = 1
```

Then I can try to test the "whitespace" feature by running:

```bash
echo 'test whitespace at the end:   ' > /tmp/test
vim /tmp/test
```

Unfortunately I can not see highlighted whitespaces at the end of the line like it is on the screenshot above.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myconfig#after'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/pruzicka/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/pruzicka/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'open-browser.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'whitespace']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:22:04] [ Info ] Startup with argv: ['/tmp/test']
[ SpaceVim ] [09:22:04] [ Info ] find local conf: /home/pruzicka/.SpaceVim.d/init.toml
[ SpaceVim ] [09:22:04] [ Info ] loading cached local conf: /home/pruzicka/.cache//SpaceVim/conf/_home_pruzicka__SpaceVim_d_init_toml.json
[ SpaceVim ] [09:22:04] [ Info ] start to apply config [local]
[ SpaceVim ] [09:22:04] [ Info ] Start to find root for: /tmp/test
[ SpaceVim ] [09:22:04] [ Info ] buffer name: /tmp/test
[ SpaceVim ] [09:22:04] [ Info ] change to root: /home/pruzicka
[ SpaceVim ] [09:22:04] [ Info ] buffer name: /tmp/test
[ SpaceVim ] [09:22:04] [ Info ] change to root: /home/pruzicka
[ SpaceVim ] [09:22:04] [ Error ] failed to call bootstrap_after function: myconfig#after
[ SpaceVim ] [09:22:04] [ Error ]        exception: Vim(call):E117: Unknown function: myconfig#after
[ SpaceVim ] [09:22:04] [ Error ]        throwpoint: function SpaceVim#autocmds#VimEnter, line 34
[ SpaceVim ] [09:22:09] [ Info ] Start to find root for: /tmp/vn0KrwE/3/issue_report.md
[ SpaceVim ] [09:22:09] [ Info ] buffer name: /tmp/vn0KrwE/3/issue_report.md
[ SpaceVim ] [09:22:09] [ Info ] change to root: /home/pruzicka
```
