### ISSUE TITLE
Emmet doesn't seem to work

### ISSUE THREAD

**Issue by wvffle** [wsdjeg/SpaceVim#3563]
## Expected behavior, english is recommend
According to [docs](https://github.com/SpaceVim/SpaceVim/blob/master/docs/layers/lang/html.md#key-bindings), emmet should expand expressions when `<C-e>` (or `<C-e>,`?) hit. That doesn't work. I've also tried to use emmets default keybind, change `g:user_emmet_leader_key` and invoking `:EmmetInstall` manually but none of those worked.

## Environment Information

- OS: archlinux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
```
nvim /tmp/test.html
i
div.test<C-e>
div.test<C-e>,
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'init#after'
  bootstrap_before = 'init#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'ayu'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['ayu-theme/ayu-vim', {'name': 'ayu-theme/ayu-vim', 'merged': 0}]]
  data_dir = '/root/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/root/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-ternjs'
  powerline_fonts = 1
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="tmux"
[[layers]]
  name="lsp"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#javascript"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:56:33] [ Info ] Startup with argv: ['/tmp/test.html']
[ SpaceVim ] [14:56:33] [ Info ] find local conf: /root/.SpaceVim.d/init.toml
[ SpaceVim ] [14:56:33] [ Info ] generate local conf: /root/.cache//SpaceVim/conf/_root__SpaceVim_d_init_toml.json
[ SpaceVim ] [14:56:33] [ Info ] start to apply config [local]
[ SpaceVim ] [14:56:33] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [14:56:33] [ Info ] Start to find root for: /tmp/test.html
[ SpaceVim ] [14:56:33] [ Info ] buffer name: /tmp/test.html
[ SpaceVim ] [14:56:33] [ Info ] change to root: /root
[ SpaceVim ] [14:56:33] [ Info ] buffer name: /tmp/test.html
[ SpaceVim ] [14:56:33] [ Info ] change to root: /root
[ SpaceVim ] [14:56:50] [ Info ] Start to find root for: /tmp/nvimkuWgOa/1/issue_report.md
[ SpaceVim ] [14:56:50] [ Info ] buffer name: /tmp/nvimkuWgOa/1/issue_report.md
[ SpaceVim ] [14:56:50] [ Info ] change to root: /root
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by wsdjeg** [comment]
You need to run `:SPInstall` to install all the plugins in `lang#html` layer.

**Comment by wsdjeg** [comment]
~~This seems an issue of emmet~~, I can reproduce it, `ctrl-e` do nothing in neovim/vim. I have check the `:imap <c-e>` when edit html file, it shows:

```
i  <C-E>m       @<Plug>(emmet-merge-lines)
i  <C-E>A       @<Plug>(emmet-anchorize-summary)
i  <C-E>a       @<Plug>(emmet-anchorize-url)
i  <C-E>k       @<Plug>(emmet-remove-tag)
i  <C-E>j       @<Plug>(emmet-split-join-tag)
i  <C-E>/       @<Plug>(emmet-toggle-comment)
i  <C-E>I       @<Plug>(emmet-image-encode)
i  <C-E>i       @<Plug>(emmet-image-size)
i  <C-E>N       @<Plug>(emmet-move-prev)
i  <C-E>n       @<Plug>(emmet-move-next)
i  <C-E>D       @<Plug>(emmet-balance-tag-outword)
i  <C-E>d       @<Plug>(emmet-balance-tag-inward)
i  <C-E>u       @<Plug>(emmet-update-tag)
i  <C-E>;       @<Plug>(emmet-expand-word)
i  <C-E>,       @<Plug>(emmet-expand-abbr)
```

so you should use **`Ctrl-e,`**

**Comment by wvffle** [comment]
As I said before, `ctrl-e,` doesn't work as well. SpaceVim is updated and SPInstall says that everything is installed.  

https://asciinema.org/a/VpYB2K9k1Vjoc85nnn3T5BfFV

**Comment by playmakermz** [comment]
excusme, i have a same issue. can't run emmet inside HTML file.

vim: VIM - Vi IMproved 8.2
OS : Manjaro
SpaceVim version : `1.8.0-dev`

after i check with `imap: <c-e>` the result is `No mapping found`

output of `:SPDebugInfo`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['joshdick/onedark.vim', {'repo': 'joshdick/onedark.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/lieat/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/lieat/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#python"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:20:58] [ Info ] Startup with argv: ['index.html']
[ SpaceVim ] [17:20:58] [ Info ] find local conf: /home/lieat/.SpaceVim.d/init.toml
[ SpaceVim ] [17:20:58] [ Info ] loading cached local conf: /home/lieat/.cache/SpaceVim/conf/_home_lieat__SpaceVim_d_init_toml.json
[ SpaceVim ] [17:20:58] [ Info ] start to apply config [local]
[ SpaceVim ] [17:20:58] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [17:20:58] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:20:58] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [17:20:58] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [17:20:58] [ Info ] Load projects cache from: /home/lieat/.cache/SpaceVim/projects.json
```
</details>
