### ISSUE TITLE
"Error detected while processing function" when opening some js files

### ISSUE THREAD

**Issue by usebaz** [wsdjeg/SpaceVim#3571]
Error when opening some js files:

```
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:                                                                              
line    3:                                                                                                                                                                                      
E684: list index out of range: 1                                                                                                                                                                
E15: Invalid expression: basic_info[1]
```

## Expected behavior, english is required

No error in console

## The reproduce ways from Vim starting (Required!)

Open some JS file in SpaceVim(`nvim`). An error appears in some files. I can not make a pattern for which. Also reappears when switching tabs.

## Debug info
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_before = 'local#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['mhartington/oceanic-next', {'name': 'mhartington/oceanic-next', 'merged': 0}], ['wakatime/vim-wakatime', {'name': 'wakatime/vim-wakatime', 'merged': 0}]]
  data_dir = '/home/user/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/user/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'palenight.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['package.json', 'package.json', 'Cargo.toml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 4
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#rust"
[[layers]]
  name="leaderf"
[[layers]]
  name="tmux"
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:49:34] [ Info ] Startup with argv: ['services/a.js']
[ SpaceVim ] [10:49:34] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [10:49:34] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:49:34] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [10:49:34] [ Info ] Start to find root for: /home/user/projects/p/services/a.js
[ SpaceVim ] [10:49:34] [ Info ]         (package.json):/home/user/projects/p
[ SpaceVim ] [10:49:34] [ Info ]         (package.json):/home/user/projects/p
[ SpaceVim ] [10:49:34] [ Info ] buffer name: services/a.js
[ SpaceVim ] [10:49:34] [ Info ] change to root: /home/user/projects/p
```
</details>

## Screenshots

![error](https://i.imgur.com/WzKJO0I.png)

## `:messages` output:

```
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E684: list index out of range: 1
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E15: Invalid expression: basic_info[1]
15 fewer lines
/\<extendParams\> [1/2]
15 fewer lines
/\<extendParams\> [1/1]
1 more line; before #809 1 second ago
57 fewer lines
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E684: list index out of range: 1
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E15: Invalid expression: basic_info[1]
36 fewer lines
E13: File exists (add ! to override)
E13: File exists (add ! to override)
"services/apple.js" 1138L, 43656C written
Error detected while processing function <SNR>220_do_delayed_update[11]..<SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E684: list index out of range: 1
Error detected while processing function <SNR>220_do_delayed_update[11]..<SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E15: Invalid expression: basic_info[1]
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E684: list index out of range: 1
Error detected while processing function <SNR>220_AutoUpdate[63]..<SNR>220_ProcessFile[84]..<SNR>220_ParseTagline:
line 3:
E15: Invalid expression: basic_info[1]

```

**Comment by usebaz** [comment]
For `vim` similar error:
```
Error detected while processing function <SNR>209_AutoUpdate[63]..<SNR>209_ProcessFile[84]..<SNR>209_ParseTagline:
line    3:
E684: list index out of range: 1
E684: list index out of range: 1
E684: list index out of range: 1
```

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_before = 'local#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['mhartington/oceanic-next', {'name': 'mhartington/oceanic-next', 'merged': 0}], ['wakatime/vim-wakatime', {'name': 'wakatime/vim-wakatime', 'merged': 0}]]
  data_dir = '/home/user/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/user/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'palenight.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['package.json', 'package.json', 'Cargo.toml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 4
  windows_leader = 's'
  windows_smartclose = 'q'
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#rust"
[[layers]]
  name="leaderf"
[[layers]]
  name="tmux"
[[layers]]
  name="colorscheme"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:40:31] [ Info ] Startup with argv: ['services/apple.js']
[ SpaceVim ] [10:40:31] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [10:40:31] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:40:31] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [10:40:31] [ Info ] Start to find root for: /home/user/projects/p/services/a.js
[ SpaceVim ] [10:40:31] [ Info ]         (package.json):/home/user/projects/p
[ SpaceVim ] [10:40:31] [ Info ]         (package.json):/home/user/projects/p
[ SpaceVim ] [10:40:31] [ Info ] buffer name: services/a.js
[ SpaceVim ] [10:40:31] [ Info ] change to root: /home/user/projects/p
[ SpaceVim ] [10:40:32] [ Info ] buffer name: services/a.js
[ SpaceVim ] [10:40:32] [ Info ] change to root: /home/user/projects/p
[ SpaceVim ] [10:40:32] [ Info ] buffer name: services/a.js
[ SpaceVim ] [10:40:32] [ Info ] change to root: /home/user/projects/p
```
</details>
