### ISSUE TITLE
Bootstrap_before doesn't load

### ISSUE THREAD

**Issue by TornaxO7** [wsdjeg/SpaceVim#3572]
## Expected behavior, english is recommend
I don't know why but spacevim doesn't load my keybindings and I think the reason is that it doesn't call the boostrap function. What am I doing wrong?

My init.toml:
```
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# -----<<<<<====== SPACEVIM =====>>>>>----- 
# All SpaceVim option below [option] 
[options]

    # load my settings
    bootstrap_before = "myspacevim#before"

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer colorscheme = "gruvbox9"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # ----- Statusline -----
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts statusline_separator = "arrow"
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    statusline_unicode_symbols = true
    statusline_left_sections = [
       'winnr',
       'filename',
       'percentage',
       'major mode',
       'minor mode lighters',
       'search status'
    ]
     # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'fileformat',
       'version control info',
       'input method',
       'date',
       'time'
    ]

    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true

    # filetree
    filetree_direction = "left"

    # enable VCS
    # enable_vimfiler_gitstatus = true

    # font
    # guifont = "hack Nerd Font:style=bold:pixelsize=12"
    # Use the standard vim "s" binding

    # Autoupdates
    automatic_update = true

    # the previous key to set the window manager
    windows_leader = 'w'

    # set spacevim to normal vim
    # vimcompatible = true
    
    # ----- Syntax -----
    # C
    enable_clang_syntax_highlighting = true
    clang_executable = "/usr/bin/gcc"


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "core#statusline"

[[layers]]
name = 'incsearch'

[[layers]]
name = "git"

[[layers]]
name = 'colorscheme'

# ----- Languages -----
[[layers]]
name = "lang#c"

[[layers]]
name = "lang#python"
format_on_save = 1
python_file_head = [
    '#!/usr/bin/env python',
    '#-------------------------------------',
    'Filename: ',
    'Author: TornaxO7',
    'Version: ',
    'Last edits: ',
    'Function: '
    '',
    ''
]

[[layers]]
name = "lang#latex"
# ----- Custom Plugins -----
# [[custom_plugins]]
# name = "<name>"
## on_cmd: This plugin will be loaded only if the following commands are called
# on_cmd = ["ColorHighlight", "..."]
# merged = false
[[custom_plugins]]
name = 'taigacute/gruvbox9'

[[custom_plugins]]
name = 'vim-airline/vim-airline-themes'
```

My bootstrap file is at: `~/.config/nvim/autoload/myspacevim.vim`<br>
Content of this file: <br>
```
function! myspacevim#before()
let g:gruvbox_transp_bg = 1

set clipboard=unnamedplus   # use global clipboard
set shiftwidth=4            # tabspace = 4
set tabstop=4
set scrolloff=7             # 7 lines before the border: Scrolling

" When After typing a bracket return, it will set place the cursor correctly
inoremap {<CR> {<CR>}<Esc>O
inoremap (<CR> (<CR>)<Esc>O
inoremap [<CR> [<CR>]<Esc>O

let g:airline_theme = 'badwolf'

noremap <S-h> 0
noremap <S-l> 5j
noremap <S-k> 5k
noremap ö i
noremap Ö I
endfunction
```

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   vimrc

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	autoload/myspacevim.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## The reproduce ways from Vim starting (Required!)
```
nvim <file>
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['ryanoasis/vim-devicons'], ['mboughaba/i3config.vim']]
  data_dir = '/home/tornax/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 1
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 4
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'TornaxO7'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = 'en_US.UTF8'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tornax/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'nerdtree-git-plugin'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'percentage', 'major mode', 'minor mode lighters']
  statusline_right_sections = ['cursorpos', 'fileformat', 'version control info', 'input method', 'date', 'time']
  statusline_separator = 'arrow'
  statusline_unciode_symbols = 1
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'de'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 'w'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="colorscheme"
[[layers]]
  name="incsearch"
[[layers]]
  name="shell"
[[layers]]
  name="git"
[[layers]]
  name="lsp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:55:07] [ Info ] Startup with argv: ['.SpaceVim.d/init.vim']
[ SpaceVim ] [14:55:07] [ Info ] find local conf: /home/tornax/.SpaceVim.d/init.vim
[ SpaceVim ] [14:55:07] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [14:55:08] [ Info ] Start to find root for: /home/tornax/.SpaceVim.d/init.vim
[ SpaceVim ] [14:55:08] [ Info ]         (.SpaceVim.d/):/home/tornax
[ SpaceVim ] [14:55:08] [ Info ] buffer name: .SpaceVim.d/init.vim
[ SpaceVim ] [14:55:08] [ Info ] change to root: /home/tornax
[ SpaceVim ] [14:55:08] [ Info ] buffer name: .SpaceVim.d/init.vim
[ SpaceVim ] [14:55:08] [ Info ] change to root: /home/tornax
[ SpaceVim ] [14:55:10] [ Info ] Start to find root for: /tmp/nvimivn4xb/2/issue_report.md
[ SpaceVim ] [14:55:10] [ Info ] buffer name: /tmp/nvimivn4xb/2/issue_report.md
[ SpaceVim ] [14:55:10] [ Info ] change to root: /home/tornax
[ SpaceVim ] [14:55:10] [ Info ] Start to find root for: /tmp/nvimivn4xb/2/issue_report.md
[ SpaceVim ] [14:55:10] [ Info ] buffer name: /tmp/nvimivn4xb/2/issue_report.md
[ SpaceVim ] [14:55:10] [ Info ] change to root: /home/tornax
[ SpaceVim ] [14:56:05] [ Info ] buffer name: .SpaceVim.d/init.vim
[ SpaceVim ] [14:56:05] [ Info ] change to root: /home/tornax
[ SpaceVim ] [14:56:08] [ Info ] Start to find root for: /tmp/nvimivn4xb/3/issue_report.md
[ SpaceVim ] [14:56:08] [ Info ] buffer name: /tmp/nvimivn4xb/3/issue_report.md
[ SpaceVim ] [14:56:08] [ Info ] change to root: /home/tornax
```
</details>
