### ISSUE TITLE
What options are available for `custom_plugins` sections in `init.toml`?

### ISSUE THREAD

**Issue by macintacos** [wsdjeg/SpaceVim#3576]
## Expected behavior, english is recommend

I'm trying to test out [firenvim](https://github.com/glacambre/firenvim) with my configuration, and for installation purposes it says to [add the following to your initconfig](https://github.com/glacambre/firenvim#pre-built) if you're using vim-plug (which I believe is what SpaceVim uses, but please feel free to correct me if I'm wrong?):

```
Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
```

I can't find a way to properly do this with SpaceVim, and while I was poking around, I realized that I genuinely can't find a list of all the option that are available when using `[[custom_plugins]]` in `init.toml`. Is there a list of option available documented anywhere? I couldn't find it.

Bonus points if you can tell me how I can accomplish this as well, since I don't know how to translate that post-hook installation in Spacevim properly.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootsrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'dracula'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = [['#282C34', '#bd93f9', 114, 235], ['#ABB2BF', '#45475b', 236, 144], ['#ABB2BF', '#282a36', 238, 144], ['#282a36', 59], ['#282c34', '#FF79C6', 235, 36], ['#282c34', '#ff5655', 235, 208], ['#282c34', '#af5f5f', 235, 131], ['#282828', '#689d6a', 235, 72], ['#282828', '#8f3f71', 235, 132]]
  custom_plugins = [['dracula/vim', {'name': 'dracula/vim', 'merged': 0}], ['machakann/vim-highlightedyank', {'name': 'machakann/vim-highlightedyank', 'merged': 0}], ['reedes/vim-lexical', {'name': 'reedes/vim-lexical', 'merged': 0}], ['tpope/vim-commentary', {'name': 'tpope/vim-commentary', 'merged': 0}], ['tpope/vim-surround', {'name': 'tpope/vim-surround', 'merged': 0}], ['vimwiki/vimwiki', {'name': 'vimwiki/vimwiki', 'merged': 0}], ['itchyny/vim-cursorword', {'name': 'itchyny/vim-cursorword', 'merged': 0}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0}], ['sheerun/vim-polyglot', {'name': 'sheerun/vim-polyglot', 'merged': 0}], ['airblade/vim-rooter', {'name': 'airblade/vim-rooter', 'merged': 0}]]
  data_dir = '/Users/juliant/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 1
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'macintacos'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/juliant/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'gtags.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json', 'pom.xml', 'Cargo.toml']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 1
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#python"
  format_on_save=1
  enable_typeinfo=1
[[layers]]
  name="denite"
[[layers]]
  name="debug"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#rust"
  format-autosave=1
  recommended-style=1
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#swift"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
[[layers]]
  name="sudo"
[[layers]]
  name="tools"
[[layers]]
  name="VersionControl"
[[layers]]
  name="gtags"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:48:28] [ Info ] Startup with no argv, current dir is used: ~/GitLocal/Website/site
[ SpaceVim ] [14:48:28] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [14:48:28] [ Info ] start to apply config [glob]
[ SpaceVim ] [14:48:28] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [14:48:29] [ Info ] Start to find root for: /Users/juliant/GitLocal/Website/site/
[ SpaceVim ] [14:48:29] [ Info ]         (.git/):/Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:29] [ Info ]         (package.json):/Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:29] [ Info ] buffer name: 
[ SpaceVim ] [14:48:29] [ Info ] change to root: /Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:29] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [14:48:29] [ Info ] buffer name: 
[ SpaceVim ] [14:48:29] [ Info ] change to root: /Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:40] [ Info ] Start to find root for: /Users/juliant/GitLocal/Website/site/
[ SpaceVim ] [14:48:40] [ Info ]         (.git/):/Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:40] [ Info ]         (package.json):/Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:40] [ Info ] buffer name: 
[ SpaceVim ] [14:48:40] [ Info ] change to root: /Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:40] [ Info ] Start to find root for: /Users/juliant/.SpaceVim/doc/SpaceVim.txt
[ SpaceVim ] [14:48:40] [ Info ]         (.git/):/Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:40] [ Info ]         (.SpaceVim.d/):/Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:40] [ Info ] buffer name: /Users/juliant/.SpaceVim/doc/SpaceVim.txt
[ SpaceVim ] [14:48:40] [ Info ] change to root: /Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:45] [ Info ] buffer name: 
[ SpaceVim ] [14:48:45] [ Info ] change to root: /Users/juliant/GitLocal/Website/site
[ SpaceVim ] [14:48:46] [ Info ] buffer name: /Users/juliant/.SpaceVim/doc/SpaceVim.txt
[ SpaceVim ] [14:48:46] [ Info ] change to root: /Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:48] [ Info ] Start to find root for: /Users/juliant/.SpaceVim/vimfiler:default
[ SpaceVim ] [14:48:48] [ Info ]         (.git/):/Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:48] [ Info ]         (.SpaceVim.d/):/Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:48] [ Info ] buffer name: vimfiler:default
[ SpaceVim ] [14:48:48] [ Info ] change to root: /Users/juliant/.SpaceVim
[ SpaceVim ] [14:48:48] [ Info ] buffer name: doc/SpaceVim.txt
[ SpaceVim ] [14:48:48] [ Info ] change to root: /Users/juliant/.SpaceVim
[ SpaceVim ] [14:49:04] [ Info ] Start to find root for: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/eval.txt
[ SpaceVim ] [14:49:04] [ Info ] buffer name: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/doc/eval.txt
[ SpaceVim ] [14:49:04] [ Info ] change to root: /Users/juliant/.SpaceVim
[ SpaceVim ] [14:49:08] [ Info ] buffer name: doc/SpaceVim.txt
[ SpaceVim ] [14:49:08] [ Info ] change to root: /Users/juliant/.SpaceVim
[ SpaceVim ] [15:20:40] [ Info ] Start to find root for: /private/var/folders/h_/3f3z91t936q41d46hflhqq640000gn/T/nvimXoJJev/2/issue_report.md
[ SpaceVim ] [15:20:40] [ Info ] buffer name: /var/folders/h_/3f3z91t936q41d46hflhqq640000gn/T/nvimXoJJev/2/issue_report.md
[ SpaceVim ] [15:20:40] [ Info ] change to root: /Users/juliant/.SpaceVim
```
</details>
