### ISSUE TITLE
Cache conf file is always used

### ISSUE THREAD

**Issue by fzakaria** [wsdjeg/SpaceVim#3581]
## Expected behavior, english is required

I expect when changes to _init.toml_ are made that they are applied
rather than the cached values in _init.json_

## The reproduce ways from Vim starting (Required!)

vim 
## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.4.0
- SpaceVim status: 

```
fatal: not a git repository (or any of the parent directories): .git
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['lilydjwg/colorizer', {'name': 'lilydjwg/colorizer', 'merged': 0}]]
  data_dir = '/home/fmzakari/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/fmzakari/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.4.0'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/nix/store/i9hbg4wmcbammvhdfishc3q3njrsfj6p-neovim-unwrapped-0.4.3/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [22:09:03] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [22:09:03] [ Info ] Startup with argv: ['/home/fmzakari/.config/nvim/init.vim']
[ SpaceVim ] [22:09:03] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [22:09:03] [ Info ] start to apply config [glob]
[ SpaceVim ] [22:09:03] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [22:09:03] [ Info ] Start to find root for: /nix/store/hqr4xky1b7cxzmqrhbypvmps8lixw8zl-source/init.vim
[ SpaceVim ] [22:09:03] [ Info ]         (.SpaceVim.d/):/home/fmzakari/.config/nvim
[ SpaceVim ] [22:09:03] [ Info ] buffer name: /home/fmzakari/.config/nvim/init.vim
[ SpaceVim ] [22:09:03] [ Info ] change to root: /home/fmzakari/.config/nvim
[ SpaceVim ] [22:09:03] [ Info ] buffer name: init.vim
[ SpaceVim ] [22:09:03] [ Info ] change to root: /home/fmzakari/.config/nvim
[ SpaceVim ] [22:09:10] [ Info ] Start to find root for: /tmp/nvimIzGdLx/2/issue_report.md
[ SpaceVim ] [22:09:10] [ Info ] buffer name: /tmp/nvimIzGdLx/2/issue_report.md
[ SpaceVim ] [22:09:10] [ Info ] change to root: /home/fmzakari/.config/nvim
```
</details>

Here are the **mtime** for the two files
```
❯ echo $(stat -c "%y" ~/.SpaceVim.d/init.toml)
2020-06-16 21:45:22.473700418 -0700
❯ echo $(stat -c "%y" ~/.cache/SpaceVim/conf/init.json)
2020-06-16 20:16:17.179431321 -0700
```

According to this [source](https://github.com/SpaceVim/SpaceVim/blame/46aaec70b244698bf912c2ecb02bfd93ec38a1dc/autoload/SpaceVim/custom.vim#L194) I expect the _init.toml_ to be used.
It's not clear why.

I stumbled on this due to others whom have had to resort manually clearing the cache file
https://github.com/jherland/home-manager/blob/0fd3177fd4e1769d338d2571edeaf4375614630a/home.nix#L20
