### ISSUE TITLE
How to debug python? help!

### ISSUE THREAD

**Issue by Aquaakuma** [wsdjeg/SpaceVim#3594]
## Expected behavior, english is required
Debug layers is not work.
OS :  Windows10
Vim verison: neovim 0.5.0
init.toml :
```
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = ""
    # colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    guifont = "Hack NF:h11"
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = false
    bootsrap_before = "scroll_map#before"
    bootsrap_after = "coc#before"
    vim_help_language = "cn"
    filemanager = "nerdtree"
    filetree_direction = "left"
    autocomplete_method = 'coc'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'
random_theme = true
frequency = "hourly"

[[layers]]
name = "chinese"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#python"
python_file_head = [
  '#!python',
  '# -*- coding: utf-8 -*-',
  '',
  '',
  ''
]

[[layers]]
name = "debug"

[[layers]]
name = "format"
[[layers]]
name = "tools"
[[custom_plugins]]
name = "yuttie/comfortable-motion.vim"
```
## The reproduce ways from Vim starting (Required!)
I enabled the debug layers,
When I used space+d+l to debug python is not response.
After I used space+d+b to enabled breakpoint and launching-debugger, I get some messages.
```
Error detected while processing function <SNR>241_readingTimerCallback[1]..474[13]..475[13]..476[7]..vebugger#pdb#_writeBreakpoints[3]..473[1]..<SNR>242_write_pipes[8]..<SNR>242_write[2]..<SNR>242_vp_pipe_write[5]..<SNR>242_libcall_raw_write[1]..<SNR>242_libcall:
line   11:
E605: Exception not caught: vimproc: vp_pipe_write: ['write() error: Invalid argument']
Error detected while processing function <SNR>241_readingTimerCallback[1]..474[13]..475[13]..476[7]..vebugger#pdb#_writeBreakpoints:
line    3:
E171: Missing :endif
Error detected while processing function <SNR>241_readingTimerCallback[1]..474[13]..475[13]..476:                                                                                               line    7:
E171: Missing :endif
Error detected while processing function <SNR>241_readingTimerCallback[1]..474:
line   13:
E170: Missing :endfor
Error detected while processing function <SNR>241_readingTimerCallback[1]..474[13]..475[13]..476[7]..vebugger#pdb#_writeBreakpoints[3]..473[1]..<SNR>242_write_pipes[8]..<SNR>242_write[2]..<SNR>242_vp_pipe_write[5]..<SNR>242_libcall_raw_write[1]..<SNR>242_libcall:
line   11:
E605: Exception not caught: vimproc: vp_pipe_write: ['write() error: Invalid argument']
Error detected while processing function <SNR>241_readingTimerCallback[1]..474[13]..475[13]..476[7]..vebugger#pdb#_writeBreakpoints:
line    3:
E171: Missing :endif
```
## Debug info
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootsrap_after = 'coc#before'
  bootsrap_before = 'scroll_map#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['yuttie/comfortable-motion.vim', {'name': 'yuttie/comfortable-motion.vim'}]]
  data_dir = 'C:\Users\75679\.cache\'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Hack NF:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\75679\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'VimCalc3'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
  frequency='hourly'
  random_theme=1
[[layers]]
  name="chinese"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
  python_file_head=['#!python', '# -*- coding: utf-8 -*-', '', '', '']
[[layers]]
  name="debug"
[[layers]]
  name="tools"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim.exe(C:\Program Files\Neovim\bin\nvim.exe)
version: 800
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:57:15] [ Info ] Startup with no argv, current dir is used: ~\Desktop
[ SpaceVim ] [11:57:15] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:57:16] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:57:16] [ Info ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [11:57:16] [ Info ] Start to find root for: C:/Users/75679/Desktop/
[ SpaceVim ] [11:57:16] [ Info ]         (.SpaceVim.d/):C:/Users/75679
[ SpaceVim ] [11:57:16] [ Info ] buffer name: 
[ SpaceVim ] [11:57:16] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [11:57:16] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [11:57:17] [ Info ] buffer name: 
[ SpaceVim ] [11:57:17] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [11:57:20] [ Info ] Start to find root for: C:/Users/75679/Desktop/test.py
[ SpaceVim ] [11:57:20] [ Info ]         (.SpaceVim.d/):C:/Users/75679
[ SpaceVim ] [11:57:20] [ Info ] buffer name: C:\Users\75679\Desktop\test.py
[ SpaceVim ] [11:57:20] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [11:57:22] [ Info ] buffer name: Desktop\test.py
[ SpaceVim ] [11:57:22] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:00:45] [ Info ] Start to find root for: C:/Users/75679/
[ SpaceVim ] [12:00:45] [ Info ]         (.SpaceVim.d/):C:/Users/75679
[ SpaceVim ] [12:00:45] [ Info ] buffer name: 
[ SpaceVim ] [12:00:45] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:00:45] [ Info ] Start to find root for: C:/Users/75679/.cache/vimfiles/.cache/init.vim/.dein/doc/vebugger.txt
[ SpaceVim ] [12:00:45] [ Info ]         (.SpaceVim.d/):C:/Users/75679
[ SpaceVim ] [12:00:45] [ Info ] buffer name: C:\Users\75679\.cache\vimfiles\.cache\init.vim\.dein\doc\vebugger.txt
[ SpaceVim ] [12:00:45] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:02:32] [ Info ] buffer name: Desktop\test.py
[ SpaceVim ] [12:02:32] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:02:36] [ Info ] Start to find root for: C:/Users/75679/
[ SpaceVim ] [12:02:36] [ Info ]         (.SpaceVim.d/):C:/Users/75679
[ SpaceVim ] [12:02:36] [ Info ] buffer name: 
[ SpaceVim ] [12:02:36] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:02:36] [ Info ] buffer name: .cache\vimfiles\.cache\init.vim\.dein\doc\vebugger.txt
[ SpaceVim ] [12:02:36] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:02:44] [ Info ] buffer name: Desktop\test.py
[ SpaceVim ] [12:02:44] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:06:24] [ Info ] Start to find root for: C:/Users/75679/
[ SpaceVim ] [12:06:24] [ Info ]         (.SpaceVim.d/):C:/Users/75679
[ SpaceVim ] [12:06:24] [ Info ] buffer name: 
[ SpaceVim ] [12:06:24] [ Info ] change to root: C:/Users/75679
[ SpaceVim ] [12:07:51] [ Info ] buffer name: Desktop\test.py
[ SpaceVim ] [12:07:51] [ Info ] change to root: C:/Users/75679
```
</details>

## Screenshots
![ 2020-06-29 123353](https://user-images.githubusercontent.com/31891793/85973280-d090af80-ba04-11ea-9492-6a749833fa6e.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
