### ISSUE TITLE
incorrect mode switch while typing text

### ISSUE THREAD

**Issue by raugustinus** [wsdjeg/SpaceVim#3598]
## Expected behavior, english is required
That I can keep typing my text. To stay in edit mode without switch.

## The reproduce ways from Vim starting (Required!)
Start typing some text like "Dit is een tijdelijke" and it will switch.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.3.4
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/[username]/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/[username]/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-jsdoc'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#typescript"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:33:54] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [10:33:54] [ Info ] find local conf: /home/[username]/.SpaceVim.d/init.toml
[ SpaceVim ] [10:33:54] [ Info ] loading cached local conf: /home/[username]/.cache//SpaceVim/conf/_home_[username]__SpaceVim_d_init_toml.json
[ SpaceVim ] [10:33:54] [ Info ] start to apply config [local]
[ SpaceVim ] [10:33:54] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [10:33:54] [ Info ] Start to find root for: /home/[username]/
[ SpaceVim ] [10:33:54] [ Info ]         (.SpaceVim.d/):/home/[username]
[ SpaceVim ] [10:33:54] [ Info ] buffer name: 
[ SpaceVim ] [10:33:54] [ Info ] change to root: /home/[username]
[ SpaceVim ] [10:33:54] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [10:33:54] [ Info ] buffer name: 
[ SpaceVim ] [10:33:54] [ Info ] change to root: /home/[username]
[ SpaceVim ] [10:33:58] [ Info ] Start to find root for: /home/[username]/
[ SpaceVim ] [10:33:58] [ Info ]         (.SpaceVim.d/):/home/[username]
[ SpaceVim ] [10:33:58] [ Info ] buffer name: 
[ SpaceVim ] [10:33:58] [ Info ] change to root: /home/[username]
[ SpaceVim ] [10:35:01] [ Info ] Start to find root for: /tmp/nvimbG9sQ0/1/issue_report.md
[ SpaceVim ] [10:35:01] [ Info ] buffer name: /tmp/nvimbG9sQ0/1/issue_report.md
[ SpaceVim ] [10:35:01] [ Info ] change to root: /home/[username]
[ SpaceVim ] [10:35:01] [ Info ] Start to find root for: /tmp/nvimbG9sQ0/1/issue_report.md
[ SpaceVim ] [10:35:01] [ Info ] buffer name: /tmp/nvimbG9sQ0/1/issue_report.md
[ SpaceVim ] [10:35:01] [ Info ] change to root: /home/[username]
[ SpaceVim ] [10:37:45] [ Info ] buffer name: 
[ SpaceVim ] [10:37:45] [ Info ] change to root: /home/[username]
[ SpaceVim ] [10:37:50] [ Info ] Start to find root for: /tmp/nvimbG9sQ0/3/issue_report.md
[ SpaceVim ] [10:37:50] [ Info ] buffer name: /tmp/nvimbG9sQ0/3/issue_report.md
[ SpaceVim ] [10:37:50] [ Info ] change to root: /home/[username]
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots
https://asciinema.org/a/GOiPIVDFw3X6GbpG69HF11ISL
