### ISSUE TITLE
Problems with lang#c

### ISSUE THREAD

**Issue by ssbanerje** [wsdjeg/SpaceVim#3613]
## Expected behavior

Configure SpaceVim with `lang#c` and `lsp`.

init.toml:
```toml
[[layers]]
  name = 'lang#c'
  [layer.clang_std]
    c = 'c11'
    cpp = 'c++17'

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'rust',
    'python',
    'sh',
    'html',
    'javascript'
  ]
  [layers.override_cmd]
    rust = ['rls']
```

Open file test.cpp in nvim:
```cpp
#include <iostream>
#include <string>

void print(const std::string &test_arg) {
  int i = 100;
  std::cout << test_arg << i << std::endl;
}

int main() {
  std::string test("Hello World");
  print(test);
  return 0;
}
```

Take cursor to any variable (say `test` in line 11) in file and execute:

- `[SPC]lD` -- `E117: Unknown function: SpaceVim#lsp#go_to_declaration`
- `[SPC]li` -- `E117: Unknown function: SpaceVim#lsp#go_to_impl`
- `[SPC]lt` -- `Vim(call):E117: Unknown function: SpaceVim#lsp#go_to_typedef`
- `[SPC]lR` -- `Vim(call):E117: Unknown function: SpaceVim#lsp#refactor`

Expected behavior is that these should work.

I have checed wtih `:SPInstall` and `:SPUpdate`. All plugins are installed there.

## The reproduce ways from Vim starting
Described above.

### Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

#### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'material'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/subho/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'ssbanerje'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/subho/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tmuxline.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'Cargo.toml', 'build.sbt']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'slant'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

#### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
  auto-completion-complete-with-key-sequence-delay=0.1
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="colorscheme"
[[layers]]
  name="incsearch"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
  git-plugin='gina'
[[layers]]
  name="sudo"
[[layers]]
  name="denite"
[[layers]]
  name="gtags"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="debug"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#python"
  format-on-save=1
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#tcl"
[[layers]]
  name="lang#scala"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['c', 'cpp', 'rust', 'python', 'sh', 'html', 'javascript']
[[layers]]
  name="tmux"
[[layers]]
  name="undotree"
```

#### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

#### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [04:06:00] [ Info ] Startup with argv: ['test.cpp']
[ SpaceVim ] [04:06:00] [ Info ] find local conf: /Users/subho/.SpaceVim.d/init.toml
[ SpaceVim ] [04:06:00] [ Info ] loading cached local conf: /Users/subho/.cache//SpaceVim/conf/_Users_subho__SpaceVim_d_init_toml.json
[ SpaceVim ] [04:06:00] [ Info ] start to apply config [local]
[ SpaceVim ] [04:06:00] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [04:06:01] [ Info ] Start to find root for: /Users/subho/test.cpp
[ SpaceVim ] [04:06:01] [ Info ]         (.SpaceVim.d/):/Users/subho
[ SpaceVim ] [04:06:01] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:01] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:01] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:01] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:06] [ Info ] Start to find root for: /Users/subho/__LanguageClient__
[ SpaceVim ] [04:06:06] [ Info ]         (.SpaceVim.d/):/Users/subho
[ SpaceVim ] [04:06:06] [ Info ] buffer name: __LanguageClient__
[ SpaceVim ] [04:06:06] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:06] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:06] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:09] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:09] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:09] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:09] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:45] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:45] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:06:56] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:06:56] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:07:31] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:07:31] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:07:47] [ Info ] buffer name: test.cpp
[ SpaceVim ] [04:07:47] [ Info ] change to root: /Users/subho
[ SpaceVim ] [04:09:03] [ Info ] Start to find root for: /private/var/folders/bx/1jkzsq_504xfy3h3_g6klmh40000gn/T/nvimicNnxR/3/issue_report.md
[ SpaceVim ] [04:09:03] [ Info ] buffer name: /var/folders/bx/1jkzsq_504xfy3h3_g6klmh40000gn/T/nvimicNnxR/3/issue_report.md
[ SpaceVim ] [04:09:03] [ Info ] change to root: /Users/subho
```
</details>
