### ISSUE TITLE
When running python commands from Spacevim's REPL some colors are not displayed correctly

### ISSUE THREAD

**Issue by siddhartha2202** [wsdjeg/SpaceVim#3623]
## Expected behavior, english is required
ipython sometimes outputs the output with color codes to show errors, however it does not display them properly by the REPL console

<img width="1115" alt="Captura de Pantalla 2020-07-11 a la(s) 22 39 51" src="https://user-images.githubusercontent.com/50558798/87238419-f3896f00-c3c7-11ea-935c-5ba6ef625ba3.png">

## Environment Information
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['kana/vim-textobj-user', {'name': 'kana/vim-textobj-user'}], ['kana/vim-textobj-entire', {'name': 'kana/vim-textobj-entire'}], ['machakann/vim-highlightedyank', {'name': 'machakann/vim-highlightedyank'}], ['vim-scripts/dbext.vim', {'name': 'vim-scripts/dbext.vim', 'merged': 0}], ['janko/vim-test', {'name': 'janko/vim-test'}], ['tpope/vim-projectionist', {'name': 'tpope/vim-projectionist'}], ['airblade/vim-rooter', {'name': 'airblade/vim-rooter'}]]
  data_dir = '/Users/emmanuel/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 0
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/emmanuel/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'git.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  auto-completion-tab-key-behavior='smart'
  auto-completion-delay=200
  auto-completion-complete-with-key-sequence-delay=0.1
  auto-completion-complete-with-key-sequence='nil'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
[[layers]]
  name="test"
[[layers]]
  name="gtags"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:42:35] [ Info ] Startup with argv: ['prueba.py']
[ SpaceVim ] [17:42:35] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [17:42:35] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:42:36] [ Info ] Start to find root for: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining/prueba.py
[ SpaceVim ] [17:42:36] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:36] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:36] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:36] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:48] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:48] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:50] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:50] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:51] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:51] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:51] [ Info ] Start to find root for: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining/__REPL__
[ SpaceVim ] [17:42:51] [ Info ] buffer name: __REPL__
[ SpaceVim ] [17:42:51] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:51] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:51] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:57] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:57] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:57] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:57] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:42:58] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:42:58] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:25] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:25] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:26] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:26] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:30] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:30] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:30] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:30] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:30] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:30] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:38] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:38] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:39] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:39] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:43:39] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:43:39] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:14] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:44:14] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:14] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:44:14] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:15] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:44:15] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:23] [ Info ] buffer name: __REPL__
[ SpaceVim ] [17:44:23] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:25] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:44:25] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:28] [ Info ] buffer name: __REPL__
[ SpaceVim ] [17:44:28] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
[ SpaceVim ] [17:44:29] [ Info ] buffer name: prueba.py
[ SpaceVim ] [17:44:29] [ Info ] change to root: /Users/emmanuel/workspace/ml_lab/Applied_Text_Mining
```
</details>

## Screenshots

https://asciinema.org/a/h5dFakUar7KiidClTL88dzTba
If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
