### ISSUE TITLE
Spacevim Rust layer does not allow searching for `racer` in $PATH

### ISSUE THREAD

**Issue by fzakaria** [wsdjeg/SpaceVim#3661]
#3021  Expected behavior, english is required

I expect for the **Rust** layer to find the _racer_ binary in $PATH

spacevim prints out the following error:
```
No racer executable found in $PATH (/nix/store/n7bmdn1x0mm8aqfmljxp547pwkrs2j6g-bash-interactive-4.4-p23/bin:/nix/store/nrhgrf4fcxh7r98gknj85hz5k
ap0wcs-patchelf-0.11/bin:/nix/store/za1rr3fxmgfbfl6nbigqi819m3m7nkgi-gcc-wrapper-9.3.0/bin:/nix/store/3krz9s8ni3bqy4hy35ycmq8assrrb4f6-gcc-9.3.0/
in:/nix/store/whqq1dwf73n27716v96va6y0pksgdsn0-glibc-2.31-bin/bin:/nix/store/xnks3zfwvvqgdb2lplg3s3v41k5nnwaz-coreutils-8.31/bin:/nix/store/6j585
9pab3lglrxqq1g9c2pa8qjgvj0-binutils-wrapper-2.31.1/bin:/nix/store/h4v5qdxlmnh7xfpl7pwzrs8js7220bz2-binutils-2.31.1/bin:/nix/store/whqq1dwf73n2771
v96va6y0pksgdsn0-glibc-2.31-bin/bin:/nix/store/xnks3zfwvvqgdb2lplg3s3v41k5nnwaz-coreutils-8.31/bin:/nix/store/7wg79xz8nrgfyj7cf2ycml774r3ylfzx-ru
t-1.45.0-2020-07-13-5c1f21c3b/bin:/nix/store/br667jnfmmx38az6rk8aib3jdbqbfr10-racer-2.1.33/bin:/nix/store/bgjmd1ji72zmfkwr7rqdfcayms5d509y-evcxr-
.5.1/bin:/nix/store/xnks3zfwvvqgdb2lplg3s3v41k5nnwaz-coreutils-8.31/bin:/nix/store/6sv4384l2w1ix6crz1q82454m1xqgz22-findutils-4.7.0/bin:/nix/stor
/0jc2k1i4dx98kl6518ijxlcqvcp455i5-diffutils-3.7/bin:/nix/store/5vxkyygp5ham0pf3iv419sgvgvh99jx5-gnused-4.8/bin:/nix/store/w8sssl6x80d9b1z928g97fv
25x7qka8-gnugrep-3.4/bin:/nix/store/p2imgcf73yah4mjqpj1ar3a9vckd1hfs-gawk-5.1.0/bin:/nix/store/g0j3pan49fp1nspif0zbcmr3zjzdbl8z-gnutar-1.32/bin:/
ix/store/9f68wvd0pr6i069cgv1jjb1fl8qpwfb4-gzip-1.10/bin:/nix/store/mxjj8is6d37va31yzznh44q7hxa38f5m-bzip2-1.0.6.0.1-bin/bin:/nix/store/4zwk4ix5p4
864xjhssslmpl2lk3lmjg-gnumake-4.3/bin:/nix/store/c4wxsn4jays9j31y5z9f83nr2cp7l4pa-bash-4.4-p23/bin:/nix/store/1ccxrdv5xy2fmylcy5v63qizx1sdq04g-pa
ch-2.7.6/bin:/nix/store/zz083gbssjski924rqa17pq6cdixyrv2-xz-5.2.5-bin/bin:/home/fmzakari/.nix-profile/bin:/home/fmzakari/.local/bin:/home/fmzakar
/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/fmzakari/.zsh/plugins/zsh-syntax-highlighting:/home/fmzakari/.zsh/plugins
powerlevel10k:/nix/store/gyqad4amzg59j5i1k2h557f4ayhym43g-neovim-ruby-env/bin)
```

My **PATH** variable though has **/nix/store/br667jnfmmx38az6rk8aib3jdbqbfr10-racer-2.1.33/bin** which contains **racer**
```
tree /nix/store/br667jnfmmx38az6rk8aib3jdbqbfr10-racer-2.1.33/bin

/nix/store/br667jnfmmx38az6rk8aib3jdbqbfr10-racer-2.1.33/bin
└── racer
```

Can the _racer_cmd_ be found on the actual $PATH rather than the TOML value?
https://github.com/SpaceVim/SpaceVim/blob/e2530924acb7eac46b956c2155356284a4a9392b/autoload/SpaceVim/layers/lang/rust.vim#L78

## The reproduce ways from Vim starting (Required!)

```
[[layers]]
    name = 'lang#rust'
    recommended-style = 1
    format-autosave = 1
```

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.4.0
- SpaceVim status: 

```
fatal: not a git repository (or any of the parent directories): .git
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['lilydjwg/colorizer', {'name': 'lilydjwg/colorizer', 'merged': 0}]]
  data_dir = '/home/fmzakari/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/fmzakari/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-racer'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'Cargo.toml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'fire'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  timeoutlen = 500
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.4.0'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
  autocomplete_method='coc'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="colorscheme"
  enable=1
[[layers]]
  name="fzf"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="lsp"
  override_cmd={'ruby': ['solargraph', 'stdio']}
  filetypes=['ruby']
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#nix"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#kotlin"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#rust"
  format-autosave=1
  recommended-style=1
[[layers]]
  name="-l"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/nix/store/193d09wqy4108z4k8r616bkwk3fnjzk5-neovim-unwrapped-0.4.3/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:29:11] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [16:29:11] [ Info ] Startup with argv: ['src/main.rs']
[ SpaceVim ] [16:29:11] [ Info ] Can not find project local config, start to loadding global config
[ SpaceVim ] [16:29:11] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:29:11] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [16:29:11] [ Info ] Start to find root for: /home/fmzakari/Development/scriptr/src/main.rs
[ SpaceVim ] [16:29:11] [ Info ]         (.git/):/home/fmzakari/Development/scriptr
[ SpaceVim ] [16:29:11] [ Info ]         (Cargo.toml):/home/fmzakari/Development/scriptr
[ SpaceVim ] [16:29:11] [ Info ] buffer name: src/main.rs
[ SpaceVim ] [16:29:11] [ Info ] change to root: /home/fmzakari/Development/scriptr
[ SpaceVim ] [16:29:11] [ Info ] buffer name: src/main.rs
[ SpaceVim ] [16:29:11] [ Info ] change to root: /home/fmzakari/Development/scriptr
[ SpaceVim ] [16:30:58] [ Info ] Start to find root for: /home/fmzakari/Development/scriptr/SpaceVimLayers
[ SpaceVim ] [16:30:58] [ Info ]         (.git/):/home/fmzakari/Development/scriptr
[ SpaceVim ] [16:30:58] [ Info ]         (Cargo.toml):/home/fmzakari/Development/scriptr
[ SpaceVim ] [16:30:58] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [16:30:58] [ Info ] change to root: /home/fmzakari/Development/scriptr
[ SpaceVim ] [16:31:11] [ Info ] buffer name: src/main.rs
[ SpaceVim ] [16:31:11] [ Info ] change to root: /home/fmzakari/Development/scriptr
[ SpaceVim ] [16:31:21] [ Info ] Start to find root for: /tmp/nvimbjSCvZ/22/issue_report.md
[ SpaceVim ] [16:31:21] [ Info ] buffer name: /tmp/nvimbjSCvZ/22/issue_report.md
[ SpaceVim ] [16:31:21] [ Info ] change to root: /home/fmzakari/Development/scriptr
```
</details>

## Screenshots
![image](https://user-images.githubusercontent.com/605070/88468189-b5468200-ce94-11ea-88c1-9ffa8fb9a082.png)
