### ISSUE TITLE
Error when press SPACE 

### ISSUE THREAD

**Issue by KelaKing** [wsdjeg/SpaceVim#3667]
## Environment Information

- OS: mac
- vim version: 8.2.539
- neovim version: -
- SpaceVim version: 1.5.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'completor'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/kela/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Hack Nerd Font:h14'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/kela/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/Applications/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gtk, or build from sources.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:41:03] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [18:41:03] [ Info ] find local conf: /Users/kela/.SpaceVim.d/init.toml
[ SpaceVim ] [18:41:03] [ Info ] loading cached local conf: /Users/kela/.cache//SpaceVim/conf/_Users_kela__SpaceVim_d_init_toml.json
[ SpaceVim ] [18:41:03] [ Info ] start to apply config [local]
[ SpaceVim ] [18:41:03] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [18:41:03] [ Info ] Start to find root for: /Users/kela/
[ SpaceVim ] [18:41:03] [ Info ]         (.SpaceVim.d/):/Users/kela
[ SpaceVim ] [18:41:03] [ Info ] buffer name: 
[ SpaceVim ] [18:41:03] [ Info ] change to root: /Users/kela
[ SpaceVim ] [18:41:03] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [18:41:03] [ Info ] buffer name: 
[ SpaceVim ] [18:41:03] [ Info ] change to root: /Users/kela
[ SpaceVim ] [18:41:05] [ Info ] Start to find root for: /Users/kela/
[ SpaceVim ] [18:41:05] [ Info ]         (.SpaceVim.d/):/Users/kela
[ SpaceVim ] [18:41:05] [ Info ] buffer name: 
[ SpaceVim ] [18:41:05] [ Info ] change to root: /Users/kela
[ SpaceVim ] [18:41:10] [ Info ] Start to find root for: /private/var/folders/f2/qfgp2bgn3078lvppd17sm2640000gn/T/vb0q8f0/1/issue_report.md
[ SpaceVim ] [18:41:10] [ Info ] buffer name: /var/folders/f2/qfgp2bgn3078lvppd17sm2640000gn/T/vb0q8f0/1/issue_report.md
[ SpaceVim ] [18:41:10] [ Info ] change to root: /Users/kela
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

<img width="1243" alt="截屏2020-07-29 18 40 30" src="https://user-images.githubusercontent.com/13584044/88790824-556d1580-d1cb-11ea-9a68-406402b264c2.png">
