### ISSUE TITLE
lang#rust + lsp: Go to definition broken

### ISSUE THREAD

**Issue by ssbanerje** [wsdjeg/SpaceVim#3669]
## Expected behavior

According to the documentation (https://spacevim.org/layers/lang/rust/), `[SPC] l s` and `[SPC] l x` should jump to definition after splitting the window. 

In the latest Spacevim, `[SPC] l s` is bound to send to REPL and `[SPC] l x` does not work.

This seems like a bug. 
 - From the code, it seems that `[SPC] l x` is bound to calls to the `vim-racer` plugin [(code)](https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/lang/rust.vim#L110-L113). Which is not loaded when the `lsp` (with rls) is used. 
- Then, later on, the `[SPC] l s` binding is overwritten with send [(code)](https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim/layers/lang/rust.vim#L154-L166).

However the `g d` shortcut seems to work with `lsp`/`rls`. So I would expect it should be possible for `[SPC] l s` and `[SPC] l x` to also work.

## How to reproduce
The setup follows instructions in https://spacevim.org/use-vim-as-a-rust-ide/. 

Here is the relevant init.toml:
```
[[layers]]
  name = 'lang#rust'
  format-autosave = 1

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'rust',
    'python',
    'sh',
    'html',
  ]
  [layers.override_cmd]
    rust = ['rls']
```

Open a rust file, go to a symbol, and press `[SPC] l s` or `[SPC] l x`

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.5.0-dev
- SpaceVim status:

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'material'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/subho/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'ssbanerje'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/subho/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'argtextobj.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'Cargo.toml', 'build.sbt']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'slant'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
  auto-completion-complete-with-key-sequence-delay=0.1
  autocomplete_method='coc'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="denite"
[[layers]]
  name="git"
  git-plugin='gina'
[[layers]]
  name="gtags"
[[layers]]
  name="incsearch"
[[layers]]
  name="shell"
  default_position='bottom'
[[layers]]
  name="sudo"
[[layers]]
  name="tools"
[[layers]]
  name="tmux"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
  format-on-save=1
[[layers]]
  name="lang#rust"
  format-autosave=1
[[layers]]
  name="lang#scala"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['c', 'cpp', 'rust', 'python', 'sh', 'html']
[[layers]]
  name="my_motions"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:39:49] [ Info ] Startup with no argv, current dir is used: ~/Workshop/IntelliKernel/hooks
[ SpaceVim ] [16:39:49] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [16:39:49] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:39:49] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [16:39:50] [ Info ] Start to find root for: /home/subho/Workshop/IntelliKernel/hooks/
[ SpaceVim ] [16:39:50] [ Info ]         (.git/):/home/subho/Workshop/IntelliKernel
[ SpaceVim ] [16:39:50] [ Info ]         (Cargo.toml):/home/subho/Workshop/IntelliKernel/hooks
[ SpaceVim ] [16:39:50] [ Info ] buffer name:
[ SpaceVim ] [16:39:50] [ Info ] change to root: /home/subho/Workshop/IntelliKernel/hooks
[ SpaceVim ] [16:39:50] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [16:39:50] [ Info ] buffer name:
[ SpaceVim ] [16:39:50] [ Info ] change to root: /home/subho/Workshop/IntelliKernel/hooks
[ SpaceVim ] [16:39:52] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [16:39:52] [ Info ] buffer name:
[ SpaceVim ] [16:39:52] [ Info ] change to root: /home/subho/Workshop/IntelliKernel/hooks
[ SpaceVim ] [16:39:52] [ Info ] close float statusline winid:1004
[ SpaceVim ] [16:39:52] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [16:39:57] [ Info ] buffer name:
[ SpaceVim ] [16:39:57] [ Info ] change to root: /home/subho/Workshop/IntelliKernel/hooks
[ SpaceVim ] [16:39:57] [ Info ] close float statusline winid:1006
[ SpaceVim ] [16:39:58] [ Info ] Start to find root for: /tmp/nvimt0f3TT/2/issue_report.md
[ SpaceVim ] [16:39:58] [ Info ] buffer name: /tmp/nvimt0f3TT/2/issue_report.md
[ SpaceVim ] [16:39:58] [ Info ] change to root: /home/subho/Workshop/IntelliKernel/hooks
```
</details>
