### ISSUE TITLE
Denite layer error

### ISSUE THREAD

**Issue by dimas-cyriaco** [wsdjeg/SpaceVim#3687]
Denite throws an error when trying to run any command.

## Expected behavior, english is recommend

Expect not to throw error.

## Environment Information

- OS: linux
- vim version: 8.0.1453
- neovim version: -
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

I just installed Vim 8 and SpaceVim, then added the denite layer. After that, I restarted Vim to install the plugins. Didn't change anithing else. It's a complete clean install.

Try to run a denite command. Via keybindings or via command line.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/work/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/work/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'neomru.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.basic)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:03:09] [ Info ] Startup with no argv, current dir is used: ~/Projetos/poc-leitor
[ SpaceVim ] [13:03:09] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [13:03:09] [ Info ] start to apply config [glob]
[ SpaceVim ] [13:03:09] [ Info ] Start to find root for: /home/work/Projetos/poc-leitor/
[ SpaceVim ] [13:03:09] [ Info ]         (.git/):/home/work/Projetos/poc-leitor
[ SpaceVim ] [13:03:09] [ Info ] buffer name: 
[ SpaceVim ] [13:03:09] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:03:09] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [13:03:09] [ Info ] buffer name: 
[ SpaceVim ] [13:03:09] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:03:12] [ Info ] Start to find root for: /home/work/Projetos/poc-leitor/poc-gio/src/Reader.js
[ SpaceVim ] [13:03:12] [ Info ]         (.git/):/home/work/Projetos/poc-leitor
[ SpaceVim ] [13:03:12] [ Info ] buffer name: /home/work/Projetos/poc-leitor/poc-gio/src/Reader.js
[ SpaceVim ] [13:03:12] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:14:44] [ Info ] Start to find root for: /home/work/Projetos/poc-leitor/SpaceVimLayers
[ SpaceVim ] [13:14:44] [ Info ]         (.git/):/home/work/Projetos/poc-leitor
[ SpaceVim ] [13:14:44] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [13:14:44] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:15:10] [ Info ] buffer name: poc-gio/src/Reader.js
[ SpaceVim ] [13:15:10] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:15:12] [ Info ] Start to find root for: /home/work/Projetos/poc-leitor/SpaceVimLayers
[ SpaceVim ] [13:15:12] [ Info ]         (.git/):/home/work/Projetos/poc-leitor
[ SpaceVim ] [13:15:12] [ Info ] buffer name: SpaceVimLayers
[ SpaceVim ] [13:15:12] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:15:54] [ Info ] buffer name: poc-gio/src/Reader.js
[ SpaceVim ] [13:15:54] [ Info ] change to root: /home/work/Projetos/poc-leitor
[ SpaceVim ] [13:16:26] [ Info ] Start to find root for: /tmp/vkGPpEq/6/issue_report.md
[ SpaceVim ] [13:16:26] [ Info ] buffer name: /tmp/vkGPpEq/6/issue_report.md
[ SpaceVim ] [13:16:26] [ Info ] change to root: /home/work/Projetos/poc-leitor
```
</details>

## Screenshots

![Screenshot from 2020-08-04 13-21-45](https://user-images.githubusercontent.com/65256/89318683-7ca56600-d655-11ea-939d-6f0b62d2f71d.png)

**Comment by dimas-cyriaco** [comment]
Fix the problem by adding this to the init.toml:

```toml
[[custom_plugins]]
    repo = "roxma/nvim-yarp"

[[custom_plugins]]
    repo = "roxma/vim-hug-neovim-rpc"
```
And installing msgpack with `pip install msgpack` and pynvim with `pip3 install --user pynvim`.

But I think this should be a internal dependency of the layer itself. Or, at least, be in the instalation docs.
