### ISSUE TITLE
Tabline does not show a new open file from ranger.vim

### ISSUE THREAD

**Issue by patzhang** [wsdjeg/SpaceVim#3690]
## Expected behavior, english is required

After opening a file from ranger.vim, the new buffer should be shown in focus in the current tab.

## The reproduce ways from Vim starting (Required!)

1. There are two existing tabs in the tabline. (1. init.toml  2. common.yml)
2. Open ranger with SPC a r (the keybinding was set up in myspacevim.vim as shown the screenshots)
3. ranger is open in a new tab3. Select a file (myspacevim.vim) and open it with Enter.
4. ranger is closed and myspacevim.vim is open. But it is not in focus. It is opened as tab2 and tab3 (common.yml) is shown in the front. I would expect myspacevim.vim is opened as tab3 and shown in focus.
5. I also tried other commands as listed at [here](https://github.com/francoiscabrol/ranger.vim#how-to-use-it), but it still does not show the opened file in focus.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['francoiscabrol/ranger.vim', {'repo': 'francoiscabrol/ranger.vim'}]]
  data_dir = '/Users/my.name/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/my.name/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.3/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [22:14:34] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [22:14:34] [ Info ] find local conf: /Users/my.name/dotfiles/roles/vim/files/.SpaceVim.d/init.toml
[ SpaceVim ] [22:14:34] [ Info ] loading cached local conf: /Users/my.name/.cache//SpaceVim/conf/_Users_my_name_dotfiles_roles_vim_files__SpaceVim_d_init_toml.json
[ SpaceVim ] [22:14:34] [ Info ] start to apply config [local]
[ SpaceVim ] [22:14:35] [ Info ] Start to find root for: /Users/my.name/
[ SpaceVim ] [22:14:35] [ Info ]         (.SpaceVim.d/):/Users/my.name/dotfiles/roles/vim/files
[ SpaceVim ] [22:14:35] [ Info ] buffer name: 
[ SpaceVim ] [22:14:35] [ Info ] change to root: /Users/my.name/dotfiles/roles/vim/files
[ SpaceVim ] [22:14:35] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [22:14:35] [ Info ] buffer name: 
[ SpaceVim ] [22:14:35] [ Info ] change to root: /Users/my.name/dotfiles/roles/vim/files
[ SpaceVim ] [22:14:39] [ Info ] Start to find root for: /Users/my.name/dotfiles/roles/vim/files/.SpaceVim.d/init.toml
[ SpaceVim ] [22:14:39] [ Info ]         (.git/):/Users/my.name/dotfiles
[ SpaceVim ] [22:14:39] [ Info ]         (.SpaceVim.d/):/Users/my.name/dotfiles/roles/vim/files
[ SpaceVim ] [22:14:39] [ Info ] buffer name: .SpaceVim.d/init.toml
[ SpaceVim ] [22:14:39] [ Info ] change to root: /Users/my.name/dotfiles/roles/vim/files
[ SpaceVim ] [22:17:07] [ Info ] Start to find root for: /private/var/folders/6p/1zr8245s5yj9654h33q3tt20tr7z10/T/nvimvtTiz3/1/issue_report.md
[ SpaceVim ] [22:17:07] [ Info ] buffer name: /var/folders/6p/1zr8245s5yj9654h33q3tt20tr7z10/T/nvimvtTiz3/1/issue_report.md
[ SpaceVim ] [22:17:07] [ Info ] change to root: /Users/my.name/dotfiles/roles/vim/files
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<img width="699" alt="Screenshot 2020-08-06 at 22 07 21" src="https://user-images.githubusercontent.com/1183059/89585639-1c214f00-d836-11ea-9dc4-c5296b03015d.png">

<img width="1151" alt="b_Screenshot 2020-08-06 at 22 07 46" src="https://user-images.githubusercontent.com/1183059/89586642-04e36100-d838-11ea-9322-ed95fabb42e6.png">

<img width="689" alt="Screenshot 2020-08-06 at 22 08 05" src="https://user-images.githubusercontent.com/1183059/89585665-28a5a780-d836-11ea-9369-714e431644b6.png">

<img width="882" alt="Screenshot 2020-08-06 at 22 08 26" src="https://user-images.githubusercontent.com/1183059/89585672-2e02f200-d836-11ea-8069-da944cd3bbea.png">

<img width="989" alt="Screenshot 2020-08-06 at 22 11 22" src="https://user-images.githubusercontent.com/1183059/89585687-35c29680-d836-11ea-8b4a-8f98f15dbd6f.png">
