### ISSUE TITLE
~/.SpaceVim.d/init.vim is ignored

### ISSUE THREAD

**Issue by danieru-desu** [wsdjeg/SpaceVim#3710]
## Expected behavior, english is recommend
$HOME/.SpaceVim.d/init.vim is considered.
## Environment Information

- OS: linux
- vim version: 8.1(1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401)
- neovim version: -
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   init.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## The reproduce ways from Vim starting (Required!)
Put anything into that file and see if it takes effect. 
What's in my file:
```
"highlight as foreground
let g:Hexokinase_highlighters = ['backgroundfull']

"update highlighting upon leaving insert mode
let g:Hexokinase_refreshEvents = ['InsertLeave', 'BufRead']

"langmap for russian layout
set langmap=йцукенгшщзхъ;qwertyuiop[]
set langmap+=фывапролджэё;asdfghjkl\\;'\\\
set langmap+=ячсмитьбю;zxcvbnm\\,.
set langmap+=ЙЦУКЕНГШЩЗХЪ;QWERTYUIOP{}
set langmap+=ФЫВАПРОЛДЖЭЁ;ASDFGHJKL\\:\\"\\~
set langmap+=ЯЧСМИТЬБЮ;ZXCVBNM<>
set langmap+=№#

"color stuff
let g:neosolarized_termtrans=1
let g:neosolarized_contrast = "high"

"set default filetype
setfiletype text 

"ignore case when searching

set ignorecase
```
`.SpaceVim.d` contents:
```
~ % ls .SpaceVim.d/
init.toml  vimrc
```
## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['rrethy/vim-hexokinase', {'build': 'make hexokinase', 'repo': 'rrethy/vim-hexokinase'}]]
  data_dir = '/home/daniel/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Hack Nerd Font Mono'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/daniel/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="tmux"
[[layers]]
  name="lang#c"
[[layers]]
  name="git"
[[layers]]
  name="lang#sh"
[[layers]]
  name="language-server-protocol"
[[layers]]
  name="sudo"
[[layers]]
  name="lang#python"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bedrock/cross/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:16:15] [ Info ] Startup with argv: ['/home/daniel/.SpaceVim.d/init.vim']
[ SpaceVim ] [16:16:15] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [16:16:15] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:16:15] [ Info ] YCM only support ultisnips, change g:spacevim_snippet_engine to ultisnips
[ SpaceVim ] [16:16:15] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [16:16:15] [ Info ] Start to find root for: /home/daniel/.SpaceVim.d/init.vim
[ SpaceVim ] [16:16:15] [ Info ] buffer name: /home/daniel/.SpaceVim.d/init.vim
[ SpaceVim ] [16:16:15] [ Info ] change to root: /home/daniel/.SpaceVim.d
[ SpaceVim ] [16:16:15] [ Info ] buffer name: init.vim
[ SpaceVim ] [16:16:15] [ Info ] change to root: /home/daniel/.SpaceVim.d
[ SpaceVim ] [16:16:23] [ Info ] Start to find root for: /tmp/vWw3Jfy/5/issue_report.md
[ SpaceVim ] [16:16:23] [ Info ] buffer name: /tmp/vWw3Jfy/5/issue_report.md
[ SpaceVim ] [16:16:23] [ Info ] change to root: /home/daniel/.SpaceVim.d
```
</details>
