### ISSUE TITLE
vimproc_mac.so not found after fresh install

### ISSUE THREAD

**Issue by odmir** [wsdjeg/SpaceVim#3720]
## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
## Expected behavior, english is required

I expect to start up a fresh install of neovim and SpaceVim without immediately getting errors.

## The reproduce ways from Vim starting (Required!)

Imediately after running 'nvim' without any arguments I get the following error:

> [vimproc] vimproc's DLL: "/Users/ricardonogueira/.SpaceVim/bundle/vimproc.vim/lib/vimproc_mac.so" is not found. Please read :help vimproc and make it.

I don't get it when running nvim with a filename as the argument. This is a pretty fresh install of vim as well as SpaceVim, it is barely configured.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/ricardonogueira/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/ricardonogueira/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'swift.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#swift"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.4/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:30:38] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [17:30:38] [ Info ] find local conf: /Users/ricardonogueira/.SpaceVim.d/init.toml
[ SpaceVim ] [17:30:38] [ Info ] loading cached local conf: /Users/ricardonogueira/.cache//SpaceVim/conf/_Users_ricardonogueira__SpaceVim_d_init_toml.json
[ SpaceVim ] [17:30:38] [ Info ] start to apply config [local]
[ SpaceVim ] [17:30:38] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [17:30:39] [ Info ] Start to find root for: /Users/ricardonogueira/
[ SpaceVim ] [17:30:39] [ Info ]         (.SpaceVim.d/):/Users/ricardonogueira
[ SpaceVim ] [17:30:39] [ Info ] buffer name: 
[ SpaceVim ] [17:30:39] [ Info ] change to root: /Users/ricardonogueira
[ SpaceVim ] [17:30:39] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:30:39] [ Info ] buffer name: 
[ SpaceVim ] [17:30:39] [ Info ] change to root: /Users/ricardonogueira
[ SpaceVim ] [17:30:42] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [17:30:42] [ Info ] buffer name: 
[ SpaceVim ] [17:30:42] [ Info ] change to root: /Users/ricardonogueira
[ SpaceVim ] [17:30:42] [ Info ] close float statusline winid:1004
[ SpaceVim ] [17:30:42] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [17:30:49] [ Info ] buffer name: 
[ SpaceVim ] [17:30:49] [ Info ] change to root: /Users/ricardonogueira
[ SpaceVim ] [17:30:49] [ Info ] close float statusline winid:1006
[ SpaceVim ] [17:30:49] [ Info ] Start to find root for: /private/var/folders/4t/752g5c957t77p0854n63bv1w0000gn/T/nvimqmVKZi/1/issue_report.md
[ SpaceVim ] [17:30:49] [ Info ] buffer name: /var/folders/4t/752g5c957t77p0854n63bv1w0000gn/T/nvimqmVKZi/1/issue_report.md
[ SpaceVim ] [17:30:49] [ Info ] change to root: /Users/ricardonogueira
```
</details>

## Screenshots

<img width="762" alt="Screenshot 2020-08-21 at 18 09 14" src="https://user-images.githubusercontent.com/278662/90916695-6deedb00-e3d9-11ea-8bcd-017c501e6ca7.png">
