### ISSUE TITLE
todo-manager does not work properly.

### ISSUE THREAD

**Issue by yabuki** [wsdjeg/SpaceVim#3735]
## Expected behavior, english is required

I wrote python code with todo,fixme etc... but todo-manager does not work properly, I'd like to use like this article. [Asynchronous todo manager | SpaceVim](https://spacevim.org/Asynchronous-todo-manager/)

please check screen cast.

## The reproduce ways from Vim starting (Required!)

open python file, then spc a o

sample code is here.
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# import doctest
import functools

#  class TestTarget(object):
#  """
#  doctestの例です。
#
#  >>> instace = TestTarget()
#
#  与えられた数に1を足して返します。
#
#  >>> instace.plusOne(5)
#  6
#
#  与えられた数に2を足して返します。
#
#  >>> instace.plusTwo(5)
#  7
#
#  """
#
#  def plusOne(self, arg1):
#      """@todo: Docstring for plusOne.
#
#      :arg1: @todo
#      :returns: @todo
#
#      """
#      return arg1 + 1
#
#  def plusTwo(self, arg1):
#      """@todo: Docstring for plusTwo.
#
#      :arg1: @todo
#      :returns: @todo
#
#      """
#      return arg1 + 2
#


def print_fin(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        output = func(*args, **kwargs)
        print(f"FIN {func.__name__}")
        return output

    return wrapper


@print_fin
def greet():
    """
    @todo: yabuki
    @fixme: tomorrow
    @question: qqqq
    @idea: アイディア
    >>> greet()
    Hello!
    FIN greet
    """
    print("Hello!")


if __name__ == "__main__":
    import doctest

    doctest.testmod()

    greet()

# doctest.testmod()
```

## Debug info

<details><summary> SpaceVim debug information </summary>                                                                                                                  
                                                                                                                                                                          
### SpaceVim options :                                                                                                                                                    
                                                                                                                                                                          
```toml                                                                                                                                                                   
  auto_disable_touchpad = 1                                                                                                                                               
  autocomplete_method = 'deoplete'                                                                                                                                        
  autocomplete_parens = 1                                                                                                                                                 
  automatic_update = 1                                                                                                                                                    
  bootstrap_after = 'my_config#after'                                                                                                                                     
  bootstrap_before = 'my_config#before'                                                                                                                                   
  buffer_index_type = 4                                                                                                                                                   
  checkinstall = 1                                                                                                                                                        
  colorscheme = 'jellybeans'                                                                                                                                              
  colorscheme_bg = 'dark'                                                                                                                                                 
  colorscheme_default = 'desert'                                                                                                                                          
  commandline_prompt = '➭'                                                                                                                                                
  custom_color_palette = []                                                                                                                                               
  custom_plugins = []                                                                                                                                                     
  data_dir = '/home/yabuki/.cache/'                                                                                                                                       
  debug_level = 1                                                                                                                                                         
  default_indent = 2                                                                                                                                                      
  disabled_plugins = ['gina', 'neosnippet']                                                                                                                               
  enable_ale = 0                                                                                                                                                          
  enable_bepo_layout = 0                                                                                                                                                  
  enable_cursorcolumn = 0                                                                                                                                                 
  enable_cursorline = 1                                                                                                                                                   
  enable_debug = 0                                                                                                                                                        
  enable_googlesuggest = 0                                                                                                                                                
  enable_guicolors = 1                                                                                                                                                    
  enable_insert_leader = 1                                                                                                                                                
  enable_javacomplete2_py = 0                                                                                                                                             
  enable_key_frequency = 0                                                                                                                                                
  enable_language_specific_leader = 1                                                                                                                                     
  enable_neocomplcache = 0                                                                                                                                                
  enable_neomake = 1                                                                                                                                                      
  enable_os_fileformat_icon = 0                                                                                                                                           
  enable_powerline_fonts = 1                                                                                                                                              
  enable_statusline_bfpath = 0                                                                                                                                            
  enable_statusline_mode = 1                                                                                                                                              
  enable_statusline_tag = 1                                                                                                                                               
  enable_tabline_filetype_icon = 1                                                                                                                                        
  enable_tabline_ft_icon = 0                                                                                                                                              
  enable_vimfiler_filetypeicon = 0                                                                                                                                        
  enable_vimfiler_gitstatus = 1                                                                                                                                           
  enable_vimfiler_welcome = 1                                                                                                                                             
  enable_ycm = 0                                                                                                                                                          
  error_symbol = '✖'                                                                                                                                                      
  escape_key_binding = 'jk'                                                                                                                                               
  expand_tab = 1                                                                                                                                                          
  filemanager = 'vimfiler'                                                                                                                                                
  filetree_direction = 'left'                                                                                                                                             
  filetype_icon = 1                                                                                                                                                       
  filetype_icons = {}                                                                                                                                                     
  force_global_config = 0                                                                                                                                                 
  gitcommit_issue_icon = ''                                                                                                                                              
  gitcommit_pr_icon = ''                                                                                                                                                 
  github_username = ''                                                                                                                                                    
  guifont = ''                                                                                                                                                            
  hiddenfileinfo = 1                                                                                                                                                      
  home_files_number = 6                                                                                                                                                   
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'                                                                                              
  info_symbol = 'ⓘ'                                                                                                                                                       
  keep_server_alive = 1                                                                                                                                                   
  language = ''                                                                                                                                                           
  leader_guide_default_group_name = ''                                                                                                                                    
  leader_guide_flatten = 1                                                                                                                                                
  leader_guide_hspace = 5                                                                                                                                                 
  leader_guide_max_size = 0                                                                                                                                               
  leader_guide_position = 'botright'                                                                                                                                      
  leader_guide_run_map_on_popup = 1                                                                                                                                       
  leader_guide_sort_horizontal = 0                                                                                                                                        
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}                                                                                                                  
  leader_guide_vertical = 0                                                                                                                                               
  lint_on_save = 1                                                                                                                                                        
  lint_on_the_fly = 0                                                                                                                                                     
  max_column = 120                                                                                                                                                        
  plugin_bundle_dir = '/home/yabuki/.cache/vimfiles/'                                                                                                                     
  plugin_manager = 'dein'                                                                                                                                                 
  plugin_manager_processes = 16                                                                                                                                           
  plugin_name = 'vim-pythonsense'                                                                                                                                         
  project_rooter_automatically = 1                                                                                                                                        
  project_rooter_outermost = 1                                                                                                                                            
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']                                                                                
  realtime_leader_guide = 1                                                                                                                                               
  relativenumber = 1                                                                                                                                                      
  search_tools = ['rg', 'git', 'grep']                                                                                                                                    
  sidebar_direction = ''                                                                                                                                                  
  sidebar_width = 30                                                                                                                                                      
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVim
TabsManager']                                                                                                                                                             
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']                                                                                                                
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'                                                                                                                                                
  statusline_inactive_separator = 'arrow'                                                                                                                                 
  statusline_iseparator = 'nil'                                                                                                                                           
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']                                                
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']                                                                                                   
  statusline_separator = 'arrow'                                                                                                                                          
  statusline_unicode_symbols = 0                                                                                                                                          
  terminal_cursor_shape = 2                                                                                                                                               
  todo_labels = ['@fixme', '@question', '@todo', '@idea']                                                                                                                 
  update_retry_cnt = 3                                                                                                                                                    
  version = '1.6.0-dev'                                                                                                                                                   
  vim_help_language = 'jp'                                                                                                                                                
  vimcompatible = 1                                                                                                                                                       
  warning_symbol = '⚠'                                                                                                                                                    
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'                                                   
  windows_index_type = 3                                                                                                                                                  
  windows_leader = ''                                                                                                                                                     
  windows_smartclose = ''                                                                                                                                                 
```                                                                                                                                                                       
                                                                                                                                                                          
                                                                                                                                                                          
### SpaceVim layers :                                                                                                                                                     
                                                                                                                                                                          
```toml                                                                                                                                                                   
[[layers]]                                                                                                                                                                
  name="autocomplete"                                                                                                                                                     
  auto_completion_return_key_behavior='complete'                                                                                                                          
  auto_completion_tab_key_behavior='cycle'                                                                                                                                
[[layers]]                                                                                                                                                                
  name="checkers"                                                                                                                                                         
[[layers]]                                                                                                                                                                
  name="format"                                                                                                                                                           
[[layers]]                                                                                                                                                                
  name="edit"                                                                                                                                                             
[[layers]]                                                                                                                                                                
  name="ui"                                                                                                                                                               
  enable_sidebar=1                                                                                                                                                        
  enable=1                                                                                                                                                                
[[layers]]                                                                                                                                                                
  name="core"                                                                                                                                                             
[[layers]]                                                                                                                                                                
  name="core#banner"                                                                                                                                                      
[[layers]]                                                                                                                                                                
  name="core#statusline"                                                                                                                                                  
[[layers]]                                                                                                                                                                
  name="core#tabline"                                                                                                                                                     
[[layers]]                                                                                                                                                                
  name="shell"                                                                                                                                                            
  default_position='bottom'                                                                                                                                               
  default_height=30                                                                                                                                                       
[[layers]]                                                                                                                                                                
  name="colorscheme"                                                                                                                                                      
[[layers]]                                                                                                                                                                
  name="default"                                                                                                                                                          
[[layers]]                                                                                                                                                                
  name="japanese"                                                                                                                                                         
[[layers]]                                                                                                                                                                
  name="git"                                                                                                                                                              
  git-plugin='fugitive'                                                                                                                                                   
[[layers]]                                                                                                                                                                
  name="github"                                                                                                                                                           
[[layers]]                                                                                                                                                                
  name="lang#markdown"                                                                                                                                                    
[[layers]]                                                                                                                                                                
  name="lang#asciidoc"                                                                                                                                                    
[[layers]]                                                                                                                                                                
  name="tools"                                                                                                                                                            
[[layers]]                                                                                                                                                                
  name="lang#python"                                                                                                                                                      
  python_file_head=['#!/usr/bin/env python3', '# -*- coding: utf-8 -*-', '', '']                                                                                          
  format_on_save=1                                                                                                                                                        
```                                                                                                                                                                       
                                                                                                                                                                          
                                                                                                                                                                          
### SpaceVim Health checking :
                                                                                                                                                                          
SpaceVim clipboard support check report:                                                                                                                                  
Checking +clipboard:                                                                                                                                                      
      SUCCEED!                                                                                                                                                            
SpaceVim environment check report:                                                                                                                                        
Current progpath: nvim(/usr/bin/nvim)                                                                                                                                     
version: 800                                                                                                                                                              
OS: linux                                                                                                                                                                 
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]                                                                                                                 
SpaceVim lua support check report:                                                                                                                                        
Checking +lua:                                                                                                                                                            
      Failed : Known issue, neovim do not support lua now.                                                                                                                
SpaceVim python support check report:                                                                                                                                     
Checking +python3:                                                                                                                                                        
      SUCCEED!                                                                                                                                                            
Checking +python:                                                                                                                                                         
      Failed : to support +python, you need run `pip2 install neovim`                                                                                                     
                                                                                                                                                                          
### SpaceVim runtime log :                                                                                                                                                
                                                                                                                                                                          
```log                                                                                                                                                                    
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!                                                                                  
[ SpaceVim ] [08:30:32] [ Info ] Startup with argv: ['decoDoctest.py']                                                                                                    
[ SpaceVim ] [08:30:32] [ Info ] Can not find project local config, start loading global config                                                                           
[ SpaceVim ] [08:30:32] [ Info ] start to apply config [glob]                                                                                                             
[ SpaceVim ] [08:30:32] [ Info ] bootstrap_before called                                                                                                                  
[ SpaceVim ] [08:30:33] [ Info ] Start to find root for: /home/yabuki/src/decoDoctest.py                                                                                  
[ SpaceVim ] [08:30:33] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:30:33] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:30:33] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:30:33] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:30:33] [ Info ] bootstrap_after called                                                                                                                   
[ SpaceVim ] [08:30:37] [ Info ] key binding guide float statusline winid:1003                                                                                            
[ SpaceVim ] [08:30:38] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:30:38] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:30:38] [ Info ] close float statusline winid:1003                                                                                                        
[ SpaceVim ] [08:30:38] [ Info ] key binding guide float statusline winid:1005                                                                                            
[ SpaceVim ] [08:30:38] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:30:38] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:30:38] [ Info ] close float statusline winid:1005                                                                                                        
[ SpaceVim ] [08:30:40] [ Info ] Start to find root for: /home/yabuki/src/SpaceVimLayers                                                                                  
[ SpaceVim ] [08:30:40] [ Info ] buffer name: SpaceVimLayers                                                                                                              
[ SpaceVim ] [08:30:40] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:31:14] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:31:14] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:31:25] [ Info ] key binding guide float statusline winid:1008                                                                                            
[ SpaceVim ] [08:31:25] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:31:25] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:31:25] [ Info ] close float statusline winid:1008                                                                                                        
[ SpaceVim ] [08:31:25] [ Info ] key binding guide float statusline winid:1010                                                                                            
[ SpaceVim ] [08:31:38] [ Info ] buffer name: decoDoctest.py                                                                                                              
[ SpaceVim ] [08:31:38] [ Info ] change to root: /home/yabuki/src                                                                                                         
[ SpaceVim ] [08:31:38] [ Info ] close float statusline winid:1010                                                                                                        
[ SpaceVim ] [08:31:38] [ Info ] Start to find root for: /home/yabuki/src/                                                                                                
[ SpaceVim ] [08:31:38] [ Info ] buffer name:                                                                                                                             
[ SpaceVim ] [08:31:38] [ Info ] change to root: /home/yabuki/src                                                                                                         
```                                                                                                                                                                       
</details>                                                                                                                                                                

 
## Screenshots

[![asciicast](https://asciinema.org/a/AxfUFYtEnzsKH8Mc6OtOSwQDw.svg)](https://asciinema.org/a/AxfUFYtEnzsKH8Mc6OtOSwQDw)
