### ISSUE TITLE
Inferior REPL ipython(python)of SpaceVim has some issues.

### ISSUE THREAD

**Issue by yabuki** [wsdjeg/SpaceVim#3754]
Hi, I am trying to use inferior REPL in my Environment.

## Expected behavior, english is required

I use Debian GNU/Linux sid(Development version). This environment is developing to next release. It means that it is going to be removing process with python2.

1. inferior REPL does not start.Because my environment does not exist python and ipython. My environment has python3 and ipython3. That is why I changed below code in ~/.SpaceVim/autoload/SpaceVim/layers/lang/python.vim. in line 72.

```python
  if executable('ipython')
    call SpaceVim#plugins#repl#reg('python', 'ipython --no-term-title')
  elseif executable('ipython3')
    call SpaceVim#plugins#repl#reg('python', 'ipython3 --no-term-title --colors=Linux')
  elseif executable('python')
    call SpaceVim#plugins#repl#reg('python', ['python', '-i'])
  elseif executable('python3')
    call SpaceVim#plugins#repl#reg('python', ['python3', '-i'])
  endif
```
 This modification can be started REPL process in my environment. ipython3 could be colored.

2. The result was different between 'copy and paste' and send buffer to ipython3.

- "copy and paste" to ipython3 is executed nomally.
- Using inferior REPL with send buffer raise a error.

```text
[REPL executable] 'ipython3 --no-term-title --colors=Linux'

--------------------
Python 3.8.5 (default, Aug  2 2020, 15:09:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: In [2]: In [3]: In [3]: In [4]: In [5]: In [5]: In [6]: In [7]: In [8]: In [9]: In [10]: In [11]: In [12]: In [13]: In [14]: In [15]: In [16]: In [17]: In [18]: In [19]: In [20]: In [21]: In [22]: In [23]: In [24]: In [25]: In [26]: In [27]: In [28]: In [29]: In [30]: In [31]: In [32]: In [33]: In [34]: In [35]: In [36]: In [37]: In [38]: In [39]: In [40]: In [41]: 
In [41]: In [41]:     ...:     ...:     ...:     ...:     ...:     ...: In [42]: [1;36m  File [1;32m"<ipython-input-42-8a02f2964b3a>"[1;36m, line [1;32m1[0m
[1;33m    return wrapper[0m
[1;37m    ^[0m
[1;31mSyntaxError[0m[1;31m:[0m 'return' outside function

In [43]: 
In [43]: In [43]:     ...:     ...:     ...:     ...:     ...:     ...:     ...:     ...:     ...:     ...:     ...:     ...: In [44]: In [44]:     ...:     ...: In [45]: 2 items had no tests:
    __main__
    __main__.print_fin
0 tests in 2 items.
0 passed and 0 failed.
Test passed.
Out[45]: TestResults(failed=0, attempted=0)
In [46]: In [46]: [1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-46-db845682bfe7>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mgreet[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mTypeError[0m: 'NoneType' object is not callable
```

## The reproduce ways from Vim starting (Required!)

when you use ipython3 or python3 eval below program.

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# import doctest
import functools

#  class TestTarget(object):
#  """
#  doctestの例です。
#
#  >>> instace = TestTarget()
#
#  与えられた数に1を足して返します。
#
#  >>> instace.plusOne(5)
#  6
#
#  与えられた数に2を足して返します。
#
#  >>> instace.plusTwo(5)
#  7
#
#  """
#
#  def plusOne(self, arg1):
#      """@todo: Docstring for plusOne.
#
#      :arg1: @todo
#      :returns: @todo
#
#      """
#      return arg1 + 1
#
#  def plusTwo(self, arg1):
#      """@todo: Docstring for plusTwo.
#
#      :arg1: @todo
#      :returns: @todo
#
#      """
#      return arg1 + 2
#


def print_fin(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        output = func(*args, **kwargs)
        print(f"FIN {func.__name__}")
        return output

    return wrapper



@print_fin
def greet():
    """
    @todo: yabuki
    @fixme: tomorrow
    @question: qqqq
    @idea: アイディア
    >>> greet()
    Hello!
    FIN greet
    """
    print("Hello!")


if __name__ == "__main__":
    import doctest

    doctest.testmod(verbose=True)

    greet()

# doctest.testmod()
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   autoload/SpaceVim/layers/lang/python.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'my_config#after'
  bootstrap_before = 'my_config#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'jellybeans'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/yabuki/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = ['gina', 'neosnippet']
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icon = 1
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Ubuntu Mono derivative Powerline:h15'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/yabuki/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-slumlord'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'git', 'grep']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'jp'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=1
  enable=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="default"
[[layers]]
  name="japanese"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="github"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#asciidoc"
[[layers]]
  name="tools"
[[layers]]
  name="lang#python"
  python_file_head=['#!/usr/bin/env python3', '# -*- coding: utf-8 -*-', '#', '# Author: YABUKI Yukiharu', '', '# Created Time: `strftime("%a %b %d")`', '']
  format_on_save=1
[[layers]]
  name="lang#plantuml"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [19:47:45] [ Info ] Startup with argv: ['Steps-day-by-day.adoc']
[ SpaceVim ] [19:47:45] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [19:47:45] [ Info ] global_dir is: /home/yabuki/.SpaceVim.d/
[ SpaceVim ] [19:47:45] [ Info ] start to apply config [glob]
[ SpaceVim ] [19:47:45] [ Error ] failed to call bootstrap_before function: my_config#before
[ SpaceVim ] [19:47:45] [ Error ]        exception: Vim:E492: Not an editor command: unction! my_config#before() abort
[ SpaceVim ] [19:47:45] [ Error ]        throwpoint: /home/yabuki/.SpaceVim.d/autoload/my_config.vim, line 1
[ SpaceVim ] [19:47:45] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [19:47:45] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:47:45] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:47:45] [ Info ] same as current directory, no need to change.
[   rooter ] [19:47:45] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:47:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:47:45] [ Error ] failed to call bootstrap_after function: my_config#after
[ SpaceVim ] [19:47:45] [ Error ]        exception: Vim:E492: Not an editor command: unction! my_config#before() abort
[ SpaceVim ] [19:47:45] [ Error ]        throwpoint: /home/yabuki/.SpaceVim.d/autoload/my_config.vim, line 1
[ SpaceVim ] [19:50:00] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [19:50:00] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:00] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:00] [ Info ] close float statusline winid:1003
[ SpaceVim ] [19:50:00] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [19:50:00] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:00] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:00] [ Info ] close float statusline winid:1005
[ SpaceVim ] [19:50:01] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [19:50:02] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:02] [ Info ] close float statusline winid:1007
[ SpaceVim ] [19:50:02] [ Info ] key binding guide float statusline winid:1009
[   rooter ] [19:50:04] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:04] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:04] [ Info ] close float statusline winid:1009
[ SpaceVim ] [19:50:13] [ Info ] key binding guide float statusline winid:1011
[   rooter ] [19:50:13] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:13] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:13] [ Info ] close float statusline winid:1011
[ SpaceVim ] [19:50:13] [ Info ] key binding guide float statusline winid:1013
[   rooter ] [19:50:33] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:33] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:33] [ Info ] close float statusline winid:1013
[ SpaceVim ] [19:50:41] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [19:50:41] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:50:41] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:41] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:41] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [19:50:41] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:50:41] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:41] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:52] [ Info ] key binding guide float statusline winid:1015
[   rooter ] [19:50:55] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:50:55] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:50:55] [ Info ] close float statusline winid:1015
[ SpaceVim ] [19:50:55] [ Info ] key binding guide float statusline winid:1017
[   rooter ] [19:51:00] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:51:00] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:51:00] [ Info ] close float statusline winid:1017
[ SpaceVim ] [19:51:00] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/.git/index
[ SpaceVim ] [19:51:00] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:51:00] [ Info ] buffer name: .git/index
[   rooter ] [19:51:00] [ Info ] same as current directory, no need to change.
[   rooter ] [19:51:04] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:51:04] [ Info ] same as current directory, no need to change.
[   rooter ] [19:51:04] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:51:04] [ Info ] same as current directory, no need to change.
[   rooter ] [19:51:11] [ Info ] buffer name: .git/index
[   rooter ] [19:51:11] [ Info ] same as current directory, no need to change.
[   rooter ] [19:52:52] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:52:52] [ Info ] same as current directory, no need to change.
[   rooter ] [19:52:52] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:52:52] [ Info ] same as current directory, no need to change.
[   rooter ] [19:52:58] [ Info ] buffer name: .git/index
[   rooter ] [19:52:58] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:53:08] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/.git/COMMIT_EDITMSG
[ SpaceVim ] [19:53:08] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:53:08] [ Info ] buffer name: .git/COMMIT_EDITMSG
[   rooter ] [19:53:08] [ Info ] same as current directory, no need to change.
[   rooter ] [19:53:08] [ Info ] buffer name: .git/index
[   rooter ] [19:53:08] [ Info ] same as current directory, no need to change.
[   rooter ] [19:53:08] [ Info ] buffer name: .git/COMMIT_EDITMSG
[   rooter ] [19:53:08] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:54:00] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/.git/COMMIT_EDITMSG
[ SpaceVim ] [19:54:00] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:54:00] [ Info ] buffer name: .git/COMMIT_EDITMSG
[   rooter ] [19:54:00] [ Info ] same as current directory, no need to change.
[   rooter ] [19:54:00] [ Info ] buffer name: .git/index
[   rooter ] [19:54:00] [ Info ] same as current directory, no need to change.
[   rooter ] [19:54:07] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:54:07] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:55:07] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [19:55:07] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:55:07] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:55:07] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:55:07] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [19:55:07] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:55:07] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:55:07] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:55:23] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/.git/COMMIT_EDITMSG
[ SpaceVim ] [19:55:23] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:55:23] [ Info ] buffer name: .git/COMMIT_EDITMSG
[   rooter ] [19:55:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [19:55:37] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/.git/COMMIT_EDITMSG
[ SpaceVim ] [19:55:37] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [19:55:37] [ Info ] buffer name: .git/COMMIT_EDITMSG
[   rooter ] [19:55:37] [ Info ] same as current directory, no need to change.
[   rooter ] [19:55:37] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [19:55:37] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:54:19] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [20:54:19] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [20:54:19] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [20:54:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:54:19] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/Steps-day-by-day.adoc
[ SpaceVim ] [20:54:19] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [20:54:19] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [20:54:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:54:26] [ Info ] key binding guide float statusline winid:1022
[   rooter ] [20:54:28] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [20:54:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:54:28] [ Info ] close float statusline winid:1022
[   rooter ] [20:54:28] [ Info ] buffer name is empty, skipped!
[   rooter ] [20:54:28] [ Info ] buffer name: No Name
[   rooter ] [20:54:28] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:56] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [20:59:56] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:04:05] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/[vimshell] - default
[ SpaceVim ] [15:04:05] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [15:04:05] [ Info ] buffer name: [vimshell] - default
[   rooter ] [15:04:05] [ Info ] same as current directory, no need to change.
[   rooter ] [15:04:13] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [15:04:13] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:04:41] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/iexe-bash@22
[ SpaceVim ] [15:04:41] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [15:04:41] [ Info ] buffer name: iexe-bash@22
[   rooter ] [15:04:41] [ Info ] same as current directory, no need to change.
[   rooter ] [15:04:59] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [15:04:59] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:05:14] [ Info ] Start to find root for: /home/yabuki/scm/git/learning-urwid/iexe-ipython3 --colors=linux@24
[ SpaceVim ] [15:05:14] [ Info ]         (.git/):/home/yabuki/scm/git/learning-urwid/
[   rooter ] [15:05:14] [ Info ] buffer name: iexe-ipython3 --colors=linux@24
[   rooter ] [15:05:14] [ Info ] same as current directory, no need to change.
[   rooter ] [15:05:45] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [15:05:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:28:51] [ Info ] key binding guide float statusline winid:1027
[   rooter ] [16:28:51] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [16:28:51] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:28:51] [ Info ] close float statusline winid:1027
[ SpaceVim ] [16:28:51] [ Info ] key binding guide float statusline winid:1029
[   rooter ] [16:28:51] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [16:28:51] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:28:51] [ Info ] close float statusline winid:1029
[ SpaceVim ] [16:28:58] [ Info ] key binding guide float statusline winid:1031
[   rooter ] [16:28:58] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [16:28:58] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:28:58] [ Info ] close float statusline winid:1031
[ SpaceVim ] [16:28:58] [ Info ] key binding guide float statusline winid:1033
[   rooter ] [16:28:59] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [16:28:59] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:28:59] [ Info ] close float statusline winid:1033
[ SpaceVim ] [16:29:01] [ Info ] key binding guide float statusline winid:1035
[   rooter ] [16:29:01] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [16:29:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:29:01] [ Info ] close float statusline winid:1035
[ SpaceVim ] [16:29:01] [ Info ] key binding guide float statusline winid:1037
[   rooter ] [16:29:02] [ Info ] buffer name: Steps-day-by-day.adoc
[   rooter ] [16:29:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:29:02] [ Info ] close float statusline winid:1037
[ SpaceVim ] [16:29:03] [ Info ] Start to find root for: /tmp/nvimdnGoRr/289/issue_report.md
[   rooter ] [16:29:03] [ Info ] buffer name: /tmp/nvimdnGoRr/289/issue_report.md
[   rooter ] [16:29:03] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

 https://asciinema.org/a/357322
