### ISSUE TITLE
E492: not an editor command: ClStart

### ISSUE THREAD

**Issue by Mick235711** [wsdjeg/SpaceVim#3766]
## Expected behavior, english is required
The spacevim should open properly when open .c or .cpp files

## The reproduce ways from Vim starting (Required!)
Simply open any .c or .cpp files, and the vim window shows the error message 'E492: not an editor command: ClStart'.
After searching for some time, it seems that this bug appears after commit `2f87f136` (Fix c cpp highlight (#3561)). ClStart is the command of Clighter8, but it is not automatically installed.
This error arise when enable_clang_syntax_highlight = true in `lang#c` layer.

## Debug info

Output of `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['wakatime/vim-wakatime']]
  data_dir = '/Users/mick/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'Mick235711'
  guifont = 'SauceCodePro Nerd Font:h14'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = 'en_US.UTF-8'
  layer_lang_java_formatter = '/Users/Mick/google-java-format.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/mick/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'devdocs.vim'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  enable=1
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="chinese"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#c"
  libclang_path='/usr/local/opt/llvm/lib'
  clang_executable='/usr/local/opt/llvm/bin/clang'
  enable_clang_syntax_highlight=1
  clang_flag=['-O2', '-std=c++17', '-Wall', '-Weverything']
[[layers]]
  name="lang#d"
[[layers]]
  name="lang#hack"
[[layers]]
  name="lang#matlab"
[[layers]]
  name="lang#pascal"
[[layers]]
  name="lang#prolog"
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#tcl"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'c': ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}'], 'cpp': ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}']}
  filetypes=['c', 'cpp', 'sh', 'python']
[[layers]]
  name="sudo"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/8.2-165_1/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:05:25] [ Info ] Startup with argv: ['/tmp/main.cpp']
[ SpaceVim ] [16:05:25] [ Info ] find local conf: /Users/mick/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [16:05:25] [ Info ] force loading global config >>>
[ SpaceVim ] [16:05:25] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:05:25] [ Info ] before
[ SpaceVim ] [16:05:25] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [16:05:25] [ Info ] Start to find root for: /private/tmp/main.cpp
[ SpaceVim ] [16:05:25] [ Info ] buffer name: /tmp/main.cpp
[ SpaceVim ] [16:05:25] [ Info ] change to root: /Users/mick/.SpaceVim
[ SpaceVim ] [16:05:25] [ Info ] buffer name: /private/tmp/main.cpp
[ SpaceVim ] [16:05:25] [ Info ] change to root: /Users/mick/.SpaceVim
[ SpaceVim ] [16:05:25] [ Info ] after
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
