### ISSUE TITLE
Add support for vim 7.4 caused weird problem on statusline

### ISSUE THREAD

**Issue by Mick235711** [wsdjeg/SpaceVim#3767]
## Expected behavior, english is required
The statusline separator should be arrow if correctly set (and default).

## The reproduce ways from Vim starting (Required!)
Simply start the vim. See screenshot below.
After some searching the issue appear after commit `c0a652c0` (Fix support for vim 7.4.1689 (#3663))

## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['wakatime/vim-wakatime']]
  data_dir = '/Users/mick/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'Mick235711'
  guifont = 'SauceCodePro Nerd Font:h14'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = 'en_US.UTF-8'
  layer_lang_java_formatter = '/Users/Mick/google-java-format.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/mick/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'devdocs.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  enable=1
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="chinese"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#c"
  libclang_path='/usr/local/opt/llvm/lib'
  clang_executable='/usr/local/opt/llvm/bin/clang'
  enable_clang_syntax_highlight=1
  clang_flag=['-O2', '-std=c++17', '-Wall', '-Weverything']
[[layers]]
  name="lang#d"
[[layers]]
  name="lang#hack"
[[layers]]
  name="lang#matlab"
[[layers]]
  name="lang#pascal"
[[layers]]
  name="lang#prolog"
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#tcl"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'c': ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}'], 'cpp': ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}']}
  filetypes=['c', 'cpp', 'sh', 'python']
[[layers]]
  name="sudo"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/8.2-165_1/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:15:03] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [16:15:03] [ Info ] find local conf: /Users/mick/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [16:15:03] [ Info ] force loading global config >>>
[ SpaceVim ] [16:15:03] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:15:03] [ Info ] before
[ SpaceVim ] [16:15:03] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [16:15:04] [ Info ] Start to find root for: /Users/mick/.SpaceVim/
[ SpaceVim ] [16:15:04] [ Info ]         (.git/):/Users/mick/.SpaceVim
[ SpaceVim ] [16:15:04] [ Info ]         (.SpaceVim.d/):/Users/mick/.SpaceVim
[ SpaceVim ] [16:15:04] [ Info ] buffer name: 
[ SpaceVim ] [16:15:04] [ Info ] change to root: /Users/mick/.SpaceVim
[ SpaceVim ] [16:15:04] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [16:15:04] [ Info ] buffer name: 
[ SpaceVim ] [16:15:04] [ Info ] change to root: /Users/mick/.SpaceVim
[ SpaceVim ] [16:15:04] [ Info ] after
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/22275534/92301080-0cab3800-ef93-11ea-85d6-beaea6581a8b.png)

As you can see, the upper statusline is ok, but not the down ones. statusline_separator is set to arrow.

**Comment by wsdjeg** [comment]
I think it is because you have set `statusline_iseparator = 'nil'`

**Comment by Mick235711** [comment]
Setting that to arrow changed nothing.
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['wakatime/vim-wakatime']]
  data_dir = '/Users/mick/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'Mick235711'
  guifont = 'SauceCodePro Nerd Font:h14'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = 'en_US.UTF-8'
  layer_lang_java_formatter = '/Users/Mick/google-java-format.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/Users/mick/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'devdocs.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml']
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.5.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='nil'
  enable=1
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="chinese"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#c"
  libclang_path='/usr/local/opt/llvm/lib'
  clang_executable='/usr/local/opt/llvm/bin/clang'
  enable_clang_syntax_highlight=1
  clang_flag=['-O2', '-std=c++17', '-Wall', '-Weverything']
[[layers]]
  name="lang#d"
[[layers]]
  name="lang#hack"
[[layers]]
  name="lang#matlab"
[[layers]]
  name="lang#pascal"
[[layers]]
  name="lang#prolog"
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#tcl"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'c': ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}'], 'cpp': ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}']}
  filetypes=['c', 'cpp', 'sh', 'python']
[[layers]]
  name="sudo"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/8.2-165_1/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:24:28] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [17:24:28] [ Info ] find local conf: /Users/mick/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [17:24:28] [ Info ] force loading global config >>>
[ SpaceVim ] [17:24:28] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:24:28] [ Info ] before
[ SpaceVim ] [17:24:28] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [17:24:29] [ Info ] Start to find root for: /Users/mick/.SpaceVim/
[ SpaceVim ] [17:24:29] [ Info ]         (.git/):/Users/mick/.SpaceVim
[ SpaceVim ] [17:24:29] [ Info ]         (.SpaceVim.d/):/Users/mick/.SpaceVim
[ SpaceVim ] [17:24:29] [ Info ] buffer name: 
[ SpaceVim ] [17:24:29] [ Info ] change to root: /Users/mick/.SpaceVim
[ SpaceVim ] [17:24:29] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [17:24:29] [ Info ] buffer name: 
[ SpaceVim ] [17:24:29] [ Info ] change to root: /Users/mick/.SpaceVim
[ SpaceVim ] [17:24:29] [ Info ] after
```
</details>

Screenshot are same.

**Comment by wsdjeg** [comment]
hmm, It is strange, I can not reproduce it, can you post your init.toml via gist? I will check it.

**Comment by Mick235711** [comment]
Sure.
<details><summary> .SpaceVim.d/init.toml </summary>

```toml

#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    guifont = "SauceCodePro Nerd Font:h14"
    default_indent = 4
    vim_help_language = "cn"
    autocomplete_method = "ycm"
    snippet_engine = "ultisnips"
    enable_ycm = 1
    layer_lang_java_formatter = "/Users/Mick/google-java-format.jar"
    relativenumber = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    lint_on_the_fly = true
    enable_statusline = true
    expand_tab = true
    enable_cursorline = true
    enable_cursorcolumn = true
    language = 'en_US.UTF-8'
    github_username = 'Mick235711'
    enable_powerline_fonts = true
    lint_on_save = true

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    enable = true
    auto-completion-return-key-behavior = "nil"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = 'checkers'
    lint_on_the_fly = true

[[layers]]
    name = 'chinese'

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'cscope'
    enable = false

[[layers]]
    name = 'debug'

[[layers]]
    name = 'default'

[[layers]]
    name = 'edit'

[[layers]]
    name = 'format'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'git'

[[layers]]
    name = 'github'

[[layers]]
    name = 'lang#c'
    clang_executable = '/usr/local/opt/llvm/bin/clang'
    libclang_path = '/usr/local/opt/llvm/lib'
    enable_clang_syntax_highlight = true
    clang_flag = ['-O2', '-std=c++17', '-Wall', '-Weverything']
    [layer.clang_std]
        c = 'c17'
        cpp = 'c++17'
        objc = 'c17'
        objcpp = 'c++17'

[[layers]]
    name = 'lang#d'

[[layers]]
    name = 'lang#hack'

[[layers]]
    name = 'lang#matlab'

[[layers]]
    name = 'lang#pascal'

[[layers]]
    name = 'lang#prolog'

[[layers]]
    name = 'lang#powershell'

[[layers]]
    name = 'lang#sql'

[[layers]]
    name = 'lang#tcl'

[[layers]]
    name = 'lang#haskell'

[[layers]]
    name = 'lang#java'

[[layers]]
    name = 'lang#latex'

[[layers]]
    name = 'lang#lua'

[[layers]]
    name = 'lang#markdown'

[[layers]]
    name = 'lang#python'

[[layers]]
    name = 'lang#ruby'

[[layers]]
    name = 'lang#sh'

[[layers]]
    name = 'lang#vim'

[[layers]]
    name = 'lsp'
    filetypes = ['c', 'cpp', 'sh', 'python']
    [layers.override_cmd]
        c = ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}']
        cpp = ['/usr/local/bin/cquery', '--log-file=/tmp/cquery.log', '--init={"cacheDirectory":"/tmp/cquery/"}']
#c = ['/usr/local/opt/llvm/bin/clangd']
#cpp = ['/usr/local/opt/llvm/bin/clangd']

[[layers]]
    name = 'sudo'

[[layers]]
    name = 'test'

[[layers]]
    name = 'tmux'

[[layers]]
    name = 'tools'

[[layers]]
    name = 'tools#dash'

#[[custom_plugins]]
#    repo = 'wakatime/vim-wakatime'
#    merged = false

```

</details>

<details><summary> .SpaceVim.d/autoload/myspacevim.vim </summary>

``` vim

function myspacevim#before() abort
    set nohlsearch
    set nowrap
    set expandtab
    set whichwrap=b,s,<,>,[,],
    set foldmethod=syntax
    set nofoldenable
    set rtp+=/usr/local/opt/fzf/
    let mapleader="\<Space>"
    let g:ycm_complete_in_comments=1
    let g:ycm_confirm_extra_conf=0
    let g:ycm_global_ycm_extra_conf="/Users/Mick/.ycm_extra_conf.py"
    let g:ycm_use_clangd=1
    "let g:ycm_clangd_binary_path="/usr/local/opt/llvm/bin/clangd"
    let g:ycm_collect_identifiers_from_tags_files=1
    let g:ycm_min_num_of_chars_for_completion=1
    let g:ycm_cache_omnifunc=0
    let g:ycm_seed_identifiers_with_syntax=1
    let g:spacevim_custom_plugins = [["wakatime/vim-wakatime"]]
    let g:wakatime_PythonBinary = "/usr/local/bin/python3"
    set tags+=/Users/Mick/stdcpp.tags
    call SpaceVim#logger#info("before")
endfunction

function myspacevim#after() abort
    call SpaceVim#logger#info("after")
endfunction

```
