### ISSUE TITLE
auto_completion_complete_with_key_sequence doesn't seem to work

### ISSUE THREAD

**Issue by psprint** [wsdjeg/SpaceVim#3783]
## Expected behavior, english is required
I assign `auto_completion_complete_with_key_sequence` to the recommended `jk`. When I press `jk` then "the complete-action should be called", which should be I *suspect* either:
- in insert — when completing → it should cause the current match to be accepted,
- in normal — when at a keyword to complete → it should go to insert and start completing.

However, none of those happen.

## The reproduce ways from Vim starting (Required!)

1. Load `lang#vim`
2. Open e.g.: `vimrc`
3. Type, e.g.: `call somefun` so that it starts completing.
4. Enter `jk` enough quickly.

OR:

1. Position at the word to complete.
2. In normal, press `jk` enough quickly.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.2.1065
- neovim version: -
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	[31mmodified:   autoload/SpaceVim/layers/chat.vim[m
	[31mmodified:   autoload/SpaceVim/layers/github.vim[m
	[31mmodified:   vimrc[m

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	[31mautoload/togglebg.vim[m
	[31mcolors/solarized.vim[m

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'solarized'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['mhartington/oceanic-next', {'repo': 'mhartington/oceanic-next', 'merged': 0}]]
  data_dir = '/home/sg/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/sg/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-chat'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
  auto_completion_complete_with_key_sequence='jk'
  auto_completion_complete_with_key_sequence_delay=10
  autocomplete_parens=0
  autocomplete_method='ycm'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#sh"
  enable=1
[[layers]]
  name="git"
  enable=1
  git-plugin='gina'
[[layers]]
  name="github"
[[layers]]
  name="ctrlspace"
  home-mapping-key='<Leader><Space>'
  enable-spacevim-styled-keys=1
[[layers]]
  name="colorscheme"
[[layers]]
  name="chat"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/home/sg/.zinit/polaris/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [07:09:05] [ Info ] Startup with argv: ['/home/sg/.vim/vimrc']
[ SpaceVim ] [07:09:05] [ Info ] find local conf: /home/sg/.SpaceVim.d/init.toml
[ SpaceVim ] [07:09:05] [ Info ] generate local conf: /home/sg/.cache//SpaceVim/conf/_home_sg__SpaceVim_d_init_toml.json
[ SpaceVim ] [07:09:05] [ Info ] start to apply config [local]
[ SpaceVim ] [07:09:05] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [07:09:05] [ Info ] CtrlSpace: no suitable grepping tool found
[ SpaceVim ] [07:09:05] [ Info ] CtrlSpace: using Vim's globpath() to collect files
[ SpaceVim ] [07:09:05] [ Info ] CtrlSpace: install rg or ag for faster file collection and .gitignore respect
[   rooter ] [07:09:05] [ Info ] Start to find root for: /home/sg/.SpaceVim/vimrc
[   rooter ] [07:09:05] [ Info ]         (.git/):/home/sg/.SpaceVim/
[   rooter ] [07:09:05] [ Info ]         (.SpaceVim.d/):/home/sg/
[   rooter ] [07:09:05] [ Info ] buffer name: /home/sg/.vim/vimrc
[   rooter ] [07:09:05] [ Info ] same as current directory, no need to change.
[   rooter ] [07:09:05] [ Info ] buffer name: .SpaceVim/vimrc
[   rooter ] [07:09:05] [ Info ] same as current directory, no need to change.
[   rooter ] [07:09:21] [ Info ] Start to find root for: /home/sg/.SpaceVim/vimrc
[   rooter ] [07:09:21] [ Info ]         (.git/):/home/sg/.SpaceVim/
[   rooter ] [07:09:21] [ Info ]         (.SpaceVim.d/):/home/sg/
[   rooter ] [07:09:21] [ Info ] buffer name: .SpaceVim/vimrc
[   rooter ] [07:09:21] [ Info ] same as current directory, no need to change.
[   rooter ] [07:11:48] [ Info ] Start to find root for: /home/sg/.SpaceVim/vimrc
[   rooter ] [07:11:48] [ Info ]         (.git/):/home/sg/.SpaceVim/
[   rooter ] [07:11:48] [ Info ]         (.SpaceVim.d/):/home/sg/
[   rooter ] [07:11:48] [ Info ] buffer name: .SpaceVim/vimrc
[   rooter ] [07:11:48] [ Info ] same as current directory, no need to change.
[   rooter ] [07:15:36] [ Info ] Start to find root for: /home/sg/.SpaceVim.d/init.toml
[   rooter ] [07:15:36] [ Info ]         (.SpaceVim.d/):/home/sg/
[   rooter ] [07:15:36] [ Info ] buffer name: /home/sg/.SpaceVim.d/init.toml
[   rooter ] [07:15:36] [ Info ] same as current directory, no need to change.
[   rooter ] [07:20:32] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:20:32] [ Info ] buffer name: No Name
[   rooter ] [07:20:32] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:20:32] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [07:20:32] [ Info ] close float statusline winid:1004
[   rooter ] [07:20:32] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:20:32] [ Info ] buffer name: No Name
[   rooter ] [07:20:32] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:20:32] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [07:20:33] [ Info ] close float statusline winid:1006
[   rooter ] [07:20:33] [ Info ] Start to find root for: /home/sg/SpaceVimLayers
[   rooter ] [07:20:33] [ Info ]         (.SpaceVim.d/):/home/sg/
[   rooter ] [07:20:33] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [07:20:33] [ Info ] same as current directory, no need to change.
[   rooter ] [07:21:00] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:21:00] [ Info ] buffer name: No Name
[   rooter ] [07:21:00] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:21:00] [ Info ] key binding guide float statusline winid:1009
[ SpaceVim ] [07:21:28] [ Info ] close float statusline winid:1009
[   rooter ] [07:21:28] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:21:28] [ Info ] buffer name: No Name
[   rooter ] [07:21:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:21:28] [ Info ] key binding guide float statusline winid:1011
[ SpaceVim ] [07:21:37] [ Info ] close float statusline winid:1011
[   rooter ] [07:22:51] [ Info ] buffer name: /home/sg/.SpaceVim.d/init.toml
[   rooter ] [07:22:51] [ Info ] same as current directory, no need to change.
[   rooter ] [07:29:38] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:29:38] [ Info ] buffer name: No Name
[   rooter ] [07:29:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:29:38] [ Info ] key binding guide float statusline winid:1013
[ SpaceVim ] [07:29:38] [ Info ] close float statusline winid:1013
[   rooter ] [07:29:38] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:29:38] [ Info ] buffer name: No Name
[   rooter ] [07:29:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:29:38] [ Info ] key binding guide float statusline winid:1015
[ SpaceVim ] [07:29:39] [ Info ] close float statusline winid:1015
[   rooter ] [07:29:43] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:29:43] [ Info ] buffer name: No Name
[   rooter ] [07:29:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:29:43] [ Info ] key binding guide float statusline winid:1017
[ SpaceVim ] [07:29:43] [ Info ] close float statusline winid:1017
[   rooter ] [07:29:43] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:29:43] [ Info ] buffer name: No Name
[   rooter ] [07:29:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:29:43] [ Info ] key binding guide float statusline winid:1019
[ SpaceVim ] [07:29:43] [ Info ] close float statusline winid:1019
[   rooter ] [07:29:51] [ Info ] buffer name: .SpaceVim/vimrc
[   rooter ] [07:29:51] [ Info ] same as current directory, no need to change.
[   rooter ] [07:29:53] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:29:53] [ Info ] buffer name: No Name
[   rooter ] [07:29:53] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:29:53] [ Info ] key binding guide float statusline winid:1021
[ SpaceVim ] [07:29:53] [ Info ] close float statusline winid:1021
[   rooter ] [07:29:53] [ Info ] buffer name is empty, skipped!
[   rooter ] [07:29:53] [ Info ] buffer name: No Name
[   rooter ] [07:29:53] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [07:29:53] [ Info ] key binding guide float statusline winid:1023
[ SpaceVim ] [07:29:54] [ Info ] close float statusline winid:1023
[   rooter ] [07:30:00] [ Info ] Start to find root for: /tmp/v7bxbwu/62/issue_report.md
[   rooter ] [07:30:00] [ Info ] buffer name: /tmp/v7bxbwu/62/issue_report.md
[   rooter ] [07:30:00] [ Info ] same as current directory, no need to change.
```
</details>

**Comment by Rom1deTroyes** [comment]
<kbd>j</kbd><kbd>k</kbd> is often used to remap <kbd>esc</kbd>ape : 

```
ESCAPE_KEY_BINDING                       *SpaceVim-options-escape_key_binding*
--
Set the key binding for switch to normal mode in insert mode. Default is `jk`,
to disable this key binding, set this option to empty string.
>
  escape_key_binding = 'jk'
```

Maybe this combination is overwrited by any prevalence in the loading ?  
While in `insert` mode, does pressing <kbd>j</kbd><kbd>k</kbd> exits you to `normal` mode ?

**Comment by Rom1deTroyes** [comment]
Reading your DebugInfo, it does :disappointed:
You can try to unset this by changing your escape key binding to an other combination, or disable it by adding `escape_key_binding = ''` in your init.toml

**Comment by psprint** [comment]
It's interesting that I hardly see any side-effects of the settings… Nor was `jk` working as an Escape (i.e.: it didn't exit into normal), nor is the completion-sequence now working after I've had (successfully — I've checked in debug-info) reset the `escape_key_binding`. I've did somewhat complete round-trip of trying a wide range of the `…delay = 10 …2400` and of trying to put the options into `[[options]]` rather than `[[layer]]`… And still no side-effects…

**Comment by wsdjeg** [comment]
Oh my god, I just found this layer option `auto_completion_complete_with_key_sequence` has not been implemented. sorry.

but `escape_key_binding` has been implemented. If you want to use `jk` to swich to normal mode instead of `Esc`. you can use:

```toml
[options]
  escape_key_binding = 'jk'
```

**Comment by wsdjeg** [comment]
I have fixed this issue, if you want to use `auto_completion_complete_with_key_sequence`, this layer option should has different value with `escape_key_binding`. for me it is:

```toml
[options]
    escape_key_binding = ''
[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
    auto_completion_complete_with_key_sequence = 'jk'
```
