### ISSUE TITLE
Powerline/Airline doesn't seem to change with themes

### ISSUE THREAD

**Issue by strazto** [wsdjeg/SpaceVim#3788]
## Expected behavior, english is recommend

The airline (or powerline) theme should change when I change colorschemes.

## Environment Information

- OS: linux
- vim version: 8.0.1453
- neovim version: -
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_after = 'rstudio#after'
  bootstrap_before = 'rstudio#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'jellybeans'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['christoomey/vim-tmux-navigator', {'name': 'christoomey/vim-tmux-navigator', 'on_cmd': ['TmuxNavigateLeft', 'TmuxNavigateDown', 'TmuxNavigateUp', 'TmuxNavigateRight'], 'merged': 0}], ['NLKNguyen/papercolor-theme', {'name': 'NLKNguyen/papercolor-theme', 'merged': 0}], ['vim-airline/vim-airline-themes', {'name': 'vim-airline/vim-airline-themes', 'merged': 0}], ['frazrepo/vim-rainbow', {'name': 'frazrepo/vim-rainbow', 'merged': 0}]]
  data_dir = '/home/matty/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/matty/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-signify'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.Rprofile', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#r"
  repl_command='R'
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="unite"
[[layers]]
  name="sudo"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:18:37] [ Info ] Startup with argv: ['init.toml']
[ SpaceVim ] [12:18:37] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [12:18:37] [ Info ] global_dir is: /home/matty/projects/bash_bindings/bootstrap/vim/config/SpaceVim.d/
[ SpaceVim ] [12:18:37] [ Info ] start to apply config [glob]
[ SpaceVim ] [12:18:37] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[   rooter ] [12:18:37] [ Info ] Start to find root for: /home/matty/projects/bash_bindings/bootstrap/vim/config/SpaceVim.d/init.toml
[   rooter ] [12:18:37] [ Info ]         (.git/):/home/matty/projects/bash_bindings/
[   rooter ] [12:18:37] [ Info ] buffer name: init.toml
[   rooter ] [12:18:37] [ Info ] change to root: /home/matty/projects/bash_bindings/
[   rooter ] [12:18:37] [ Info ] buffer name: bootstrap/vim/config/SpaceVim.d/init.toml
[   rooter ] [12:18:37] [ Info ] same as current directory, no need to change.
[   rooter ] [12:18:48] [ Info ] Start to find root for: /tmp/vKUR9Fp/4/issue_report.md
[   rooter ] [12:18:48] [ Info ] buffer name: /tmp/vKUR9Fp/4/issue_report.md
[   rooter ] [12:18:48] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

[![asciicast](https://asciinema.org/a/SPp7MOEHK32BWpFiwFk9Nu146.svg)](https://asciinema.org/a/SPp7MOEHK32BWpFiwFk9Nu146)
