### ISSUE TITLE
SpaceVim is no longer expanding tabs when multiple files are open. 

### ISSUE THREAD

**Issue by linusjf** [wsdjeg/SpaceVim#3815]
SpaceVim does not expand tabs for multiple files. User has to navigate using next and prev commands instead. 

## Expected behavior, english is required
Tabs must be visible at top of view for multiple open files.

## The reproduce ways from Vim starting (Required!)
$ vim file1 file2 ..... filen -p

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	autoload/JCommenter.vim

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['junegunn/vim-github-dashboard', {'name': 'junegunn/vim-github-dashboard', 'merged': 0}]]
  data_dir = '/data/data/com.termux/files/home/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/data/data/com.termux/files/home/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'helpful.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'package.json', '.SpaceVim.d/', '.clang', '.Rprofile']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_delay=200
  auto_completion_return_key_behavior='nil'
  auto_completion_tab_key_behavior='smart'
  auto_completion_complete_with_key_sequence='nil'
  auto_completion_complete_with_key_sequence_delay=0.1
[[layers]]
  name="checkers"
  enable_ale=1
  lint_on_the_fly=1
  enable_neomake=0
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#python"
  python_file_head=['#!/usr/bin/env python', '# -*- coding: utf-8 -*-', '', '']
  enable_typeinfo=1
[[layers]]
  name="lang#javascript"
  auto_fix=1
  enable_flow_syntax=1
[[layers]]
  name="lang#perl"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#r"
  repl_command='R --no-save'
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lisp"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="sudo"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#csharp"
  highlight_types=0
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/data/data/com.termux/files/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/data/data/com.termux/files/usr/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:48:09] [ Info ] Startup with argv: ['CentredDeque.java']
[ SpaceVim ] [11:48:09] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:48:09] [ Info ] global_dir is: /data/data/com.termux/files/home/.SpaceVim.d/
[ SpaceVim ] [11:48:09] [ Info ] start to apply config [glob]
[   rooter ] [11:48:11] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [11:48:11] [ Info ] Start to find root for: /data/data/com.termux/files/home/DSAlgos/src/main/java/ds/CentredDeque.java
[   rooter ] [11:48:11] [ Info ]         (.git/):/data/data/com.termux/files/home/DSAlgos/
[   rooter ] [11:48:11] [ Info ]         (pom.xml):/data/data/com.termux/files/home/DSAlgos/
[   rooter ] [11:48:11] [ Info ] buffer name: CentredDeque.java
[   rooter ] [11:48:11] [ Info ] change to root: /data/data/com.termux/files/home/DSAlgos/
[   rooter ] [11:48:11] [ Info ] buffer name: src/main/java/ds/CentredDeque.java
[   rooter ] [11:48:11] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:49:49] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [11:49:50] [ Info ] buffer name: src/main/java/ds/CentredDeque.java
[   rooter ] [11:49:50] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:49:50] [ Info ] close float statusline winid:1003
[ SpaceVim ] [11:49:50] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [11:49:50] [ Info ] buffer name: src/main/java/ds/CentredDeque.java
[   rooter ] [11:49:50] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:49:50] [ Info ] close float statusline winid:1005
[   rooter ] [11:49:54] [ Info ] Start to find root for: /data/data/com.termux/files/usr/tmp/nvimw70PXU/5/issue_report.md
[   rooter ] [11:49:54] [ Info ] buffer name: /data/data/com.termux/files/usr/tmp/nvimw70PXU/5/issue_report.md
[   rooter ] [11:49:54] [ Info ] same as current directory, no need to change.
```
</details>
