### ISSUE TITLE
tab key stopped moving between widnows in v1.6.0dev

### ISSUE THREAD

**Issue by elpdcore** [wsdjeg/SpaceVim#3823]
## Expected behavior, english is required
Pressing the `tab` key should jump the focus from window to window. From edit buffer to the file navigation for instance.

## The reproduce ways from Vim starting (Required!)
Starting vim. Focus is on the main bufffer. Pressing `tab`. Nothing happens

Moving back to v.1.5.0 (git checkout in ~/.Spacevim) fixes the problem.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['HerringtonDarkholme/yats.vim', {'name': 'HerringtonDarkholme/yats.vim', 'merge': 0}]]
  data_dir = '/home/eyal/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/eyal/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'LanguageClient-neovim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="git"
[[layers]]
  name="fzf"
[[layers]]
  name="lang#elixir"
[[layers]]
  name="lsp"
  filetypes=['typescript']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvim.aQ3qPmi/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:15:06] [ Info ] Startup with no argv, current dir is used: ~/projects/
[ SpaceVim ] [13:15:06] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [13:15:06] [ Info ] global_dir is: /home/eyal/.SpaceVim.d/
[ SpaceVim ] [13:15:06] [ Info ] start to apply config [glob]
[   rooter ] [13:15:07] [ Info ] buffer name is empty, skipped!
[   rooter ] [13:15:07] [ Info ] buffer name: No Name
[   rooter ] [13:15:07] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:07] [ Info ] try to open SpaceVim welcome page
[   rooter ] [13:15:07] [ Info ] buffer name: No Name
[   rooter ] [13:15:07] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:10] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [13:15:10] [ Info ] buffer name: No Name
[   rooter ] [13:15:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:10] [ Info ] close float statusline winid:1004
[ SpaceVim ] [13:15:10] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [13:15:11] [ Info ] buffer name: No Name
[   rooter ] [13:15:11] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:11] [ Info ] close float statusline winid:1006
[ SpaceVim ] [13:15:13] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [13:15:13] [ Info ] buffer name: No Name
[   rooter ] [13:15:13] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:13] [ Info ] close float statusline winid:1008
[ SpaceVim ] [13:15:13] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [13:15:15] [ Info ] buffer name: No Name
[   rooter ] [13:15:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:15] [ Info ] close float statusline winid:1010
[   rooter ] [13:15:15] [ Info ] Start to find root for: /home/eyal/projects/
[   rooter ] [13:15:15] [ Info ]         (.git/):/home/eyal/projects/
[   rooter ] [13:15:15] [ Info ]         (package.json):/home/eyal/projects
[   rooter ] [13:15:15] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [13:15:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:31] [ Info ] key binding guide float statusline winid:1013
[   rooter ] [13:15:31] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [13:15:31] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:31] [ Info ] close float statusline winid:1013
[ SpaceVim ] [13:15:31] [ Info ] key binding guide float statusline winid:1015
[   rooter ] [13:15:38] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [13:15:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:15:38] [ Info ] close float statusline winid:1015
[   rooter ] [13:15:38] [ Info ] Start to find root for: /tmp/nvimRfJz4g/1/issue_report.md
[   rooter ] [13:15:38] [ Info ] buffer name: /tmp/nvimRfJz4g/1/issue_report.md
[   rooter ] [13:15:38] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
