### ISSUE TITLE
Flake8 reports syntax error on f-string

### ISSUE THREAD

**Issue by willismonroe** [wsdjeg/SpaceVim#3825]
## Expected behavior, english is recommend

The syntax check on save should be fine with f-strings, but for some reason it's complaining about them.  Running the check on the command line reports no errors.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'markddown#after'
  bootstrap_before = 'custom_init#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['jceb/vim-orgmode', {'name': 'jceb/vim-orgmode'}], ['evanleck/vim-svelte', {'name': 'evanleck/vim-svelte'}]]
  data_dir = '/home/willis/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/willis/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'palenight.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', 'package.json', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="lang#python"
  python_file_head=['#!/usr/bin/env python3', '# -*- coding: utf-8 -*-', '', '']
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:05:24] [ Info ] Startup with no argv, current dir is used: ~/src/µgit/ugit
[ SpaceVim ] [10:05:24] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [10:05:24] [ Info ] global_dir is: /home/willis/.SpaceVim.d/
[ SpaceVim ] [10:05:24] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:05:24] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [10:05:25] [ Info ] buffer name is empty, skipped!
[   rooter ] [10:05:25] [ Info ] buffer name: No Name
[   rooter ] [10:05:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:05:25] [ Info ] try to open SpaceVim welcome page
[   rooter ] [10:05:25] [ Info ] buffer name: No Name
[   rooter ] [10:05:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:05:25] [ Error ] failed to call bootstrap_after function: markddown#after
[ SpaceVim ] [10:05:25] [ Error ]        exception: Vim(call):E117: Unknown function: markddown#after
[ SpaceVim ] [10:05:25] [ Error ]        throwpoint: function SpaceVim#autocmds#VimEnter, line 34
[   rooter ] [10:05:26] [ Info ] Start to find root for: /home/willis/src/µgit/ugit/data.py
[   rooter ] [10:05:26] [ Info ] buffer name: data.py
[   rooter ] [10:05:26] [ Info ] same as current directory, no need to change.
[   rooter ] [10:05:28] [ Info ] Start to find root for: /home/willis/src/µgit/ugit/data.py
[   rooter ] [10:05:28] [ Info ] buffer name: data.py
[   rooter ] [10:05:28] [ Info ] same as current directory, no need to change.
[   rooter ] [10:05:28] [ Info ] buffer name is empty, skipped!
[   rooter ] [10:05:28] [ Info ] buffer name: No Name
[   rooter ] [10:05:28] [ Info ] same as current directory, no need to change.
[   rooter ] [10:05:28] [ Info ] Start to find root for: /home/willis/src/µgit/ugit/vimfiler:default
[   rooter ] [10:05:28] [ Info ] buffer name: vimfiler:default
[   rooter ] [10:05:28] [ Info ] same as current directory, no need to change.
[   rooter ] [10:05:28] [ Info ] buffer name: data.py
[   rooter ] [10:05:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:05:52] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [10:05:52] [ Info ] buffer name: data.py
[   rooter ] [10:05:52] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:05:52] [ Info ] close float statusline winid:1005
[ SpaceVim ] [10:05:52] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [10:05:52] [ Info ] buffer name: data.py
[   rooter ] [10:05:52] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:05:52] [ Info ] close float statusline winid:1007
[ SpaceVim ] [10:05:53] [ Info ] key binding guide float statusline winid:1009
[   rooter ] [10:05:53] [ Info ] buffer name: data.py
[   rooter ] [10:05:53] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:05:53] [ Info ] close float statusline winid:1009
[   rooter ] [10:05:56] [ Info ] Start to find root for: /tmp/nvimCkyVS9/5/issue_report.md
[   rooter ] [10:05:56] [ Info ] buffer name: /tmp/nvimCkyVS9/5/issue_report.md
[   rooter ] [10:05:56] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![Syntax error in SpaceVim](https://user-images.githubusercontent.com/715210/93717200-0be4db00-fb29-11ea-9f63-c03ae1e73d3b.png)

![No error in console](https://user-images.githubusercontent.com/715210/93717273-9dece380-fb29-11ea-9111-15e42bc5b7ce.png)

No error running it manually on the terminal, and clearly there is no flake8 installed for python2, so I don't know where the error is coming from.
