### ISSUE TITLE
Rust evcxr repl not showing any output in buffer.

### ISSUE THREAD

**Issue by taranjlu** [wsdjeg/SpaceVim#3830]
## Expected behavior

I'm following this doc to try to setup IDE functionality for Rust: https://spacevim.org/use-vim-as-a-rust-ide/ After initially running into an issue where I did not have `evcxr` installed, I installed it via `cargo` but now when I try to start the repl, I get no output. I can see that the `evcxr` processes are running via `htop`, but the buffer does not have any output and simply looks like this:
![image](https://user-images.githubusercontent.com/6187278/93995876-660eb780-fd46-11ea-948d-8c3790f2b881.png)

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 

```
On branch master

Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
```

## Steps to Reproduce
1. `nvim hello.rs`
2. `SPC l s i`

```rust
// hello.rs
fn main() {
    println!("Hello, world!");
}
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'OceanicNext'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['mhartington/oceanic-next', {'repo': 'mhartington/oceanic-next', 'merged': 0}]]
  data_dir = '/home/----/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = ''
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/----/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-toml'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="incsearch"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#toml"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.4/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [02:47:17] [ Info ] Startup with no argv, current dir is used: ~/Documents
[ SpaceVim ] [02:47:17] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [02:47:17] [ Info ] global_dir is: /home/----/.SpaceVim.d/
[ SpaceVim ] [02:47:17] [ Info ] start to apply config [glob]
[ SpaceVim ] [02:47:17] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [02:47:17] [ Info ] buffer name is empty, skipped!
[   rooter ] [02:47:17] [ Info ] buffer name: No Name
[   rooter ] [02:47:17] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:47:17] [ Info ] try to open SpaceVim welcome page
[   rooter ] [02:47:18] [ Info ] buffer name: No Name
[   rooter ] [02:47:18] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:47:19] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [02:47:20] [ Info ] buffer name: No Name
[   rooter ] [02:47:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:47:20] [ Info ] close float statusline winid:1004
[ SpaceVim ] [02:47:20] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [02:47:22] [ Info ] buffer name: No Name
[   rooter ] [02:47:22] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:47:22] [ Info ] close float statusline winid:1006
[   rooter ] [02:47:22] [ Info ] Start to find root for: /tmp/nvimbMzT8L/1/issue_report.md
[   rooter ] [02:47:22] [ Info ] buffer name: /tmp/nvimbMzT8L/1/issue_report.md
[   rooter ] [02:47:22] [ Info ] same as current directory, no need to change.
```
</details>
