### ISSUE TITLE
checkhealth reports WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results. even though virtualenv is activated.

### ISSUE THREAD

**Issue by taranjlu** [wsdjeg/SpaceVim#3843]
## Expected behavior, english is required
I would expect the `checkhealth` to correctly identify that I am in a virtualenv, especially since other parts of SpaceVim (e.g. the neovim terminal or repl) all work correctly and are able to access the packages that are found in the virtualenv.

This is an overview of my Python setup:
- `pyenv` installed via Linuxbrew
- Python 2.7.18 installed and set globally via `pyenv`
- Python 3.7.8 installed and set globally via `pyenv`
- Virtualenvs created in `~/.virtualenvs`
- All virtualenvs created via `poetry` using the clean Python installations controlled by `pyenv`
- Using `fish` shell and `virtualfish` plugin to mimic `virtualenvwrapper`
  - I have also tested directly sourcing the activation script with the same result

```sh
❯ pyenv versions
  system
* 2.7.18 (set by /home/----/.pyenv/version)
* 3.7.8 (set by /home/----/.pyenv/version)
  3.8.5
```

## The reproduce ways from Vim starting (Required!)
1. Activate virtualenv (Python 3 dev tools virtualenv)
2. Open Python file with `nvim <python file>`
3. Run `:checkhealth`

## Debug info

<details><summary> SpaceVim checkhealth information </summary>

health#LanguageClient#check
========================================================================
  - OK: binary found: /home/----/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.158 
  - OK: Floating window is supported and will be used for hover

health#jedi#check
========================================================================
##### jedi-vim version

 - jedi-vim git version: a17b033
 - jedi git submodule status:  3b7106ae71cb7bd3431101d169a0110ee0c179aa pythonx/jedi (v0.17.2)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7/bin/python3`
 - global sys.version: `3.7.8 (default, Sep  9 2020, 23:38:40), [GCC 9.3.0]`
 - global site module: `/home/----/.pyenv/versions/3.7.8/lib/python3.7/site.py`

##### Jedi

 - path: `/home/----/.cache/vimfiles/repos/github.com/davidhalter/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.17.2

##### Jedi environment: <Environment: 3.7.8 in /home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7>

 - executable: /home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7/bin/python
 - sys_path:
    - `/home/----/.pyenv/versions/3.7.8/lib/python37.zip`
    - `/home/----/.pyenv/versions/3.7.8/lib/python3.7`
    - `/home/----/.pyenv/versions/3.7.8/lib/python3.7/lib-dynload`
    - `/home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.7.8 in /home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7> (/home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7/bin/python)

 - <Environment: 3.7.8 in /home/----/.pyenv/versions/3.7.8> (/home/----/.pyenv/versions/3.7.8/bin/python3.7)

 - <Environment: 2.7.18 in /home/----/.pyenv/versions/2.7.18> (/home/----/.pyenv/versions/2.7.18/bin/python2.7)

##### Settings

```
g:jedi#completions_enabled = 0 (default: 1)


  omnifunc=htmlcomplete#CompleteTags
	Last set from /home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.4/share/nvim/runtime/ftplugin/html.vim line 24
  completeopt=menu,menuone,longest
	Last set from ~/.SpaceVim/autoload/SpaceVim/default.vim line 116
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: xterm-256color
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.20/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/----/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /home/----/.pyenv/shims/python2 does not have the "neovim" module. :help |provider-python|
          /home/----/.pyenv/shims/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/----/.virtualenvs/python3.7-dev-tools-mUtRiraG-py3.7/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.20/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/----/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654
  - INFO: Executable: /home/----/.pyenv/versions/3.7.8/bin/python3
  - ERROR: Command error (job=10, exit code 1): `'/home/----/.pyenv/versions/3.7.8/bin/python3' -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` (in '/home/----/git/tl/tl.sandbox')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
    Stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
  - INFO: Python version: 3.7.8
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip3 install pynvim

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

</details>

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'tl_config#after'
  bootstrap_before = 'tl_config#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/----/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = ''
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/----/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-gitgutter'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="incsearch"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#python"
  format_on_save=1
[[layers]]
  name="VersionControl"
  enable_gtm_status=1
[[layers]]
  name="git"
```

### SpaceVim Health checking :

```
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.4/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
```

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:58:28] [ Info ] Startup with argv: ['python_test.py']
[ SpaceVim ] [13:58:28] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [13:58:28] [ Info ] global_dir is: /home/----/.SpaceVim.d/
[ SpaceVim ] [13:58:28] [ Info ] start to apply config [glob]
[ SpaceVim ] [13:58:28] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [13:58:29] [ Info ] Start to find root for: /home/----/git/tl/tl.sandbox/python_test.py
[   rooter ] [13:58:29] [ Info ]         (.git/):/home/----/git/tl/tl.sandbox/
[   rooter ] [13:58:29] [ Info ] buffer name: python_test.py
[   rooter ] [13:58:29] [ Info ] same as current directory, no need to change.
[   rooter ] [13:58:29] [ Info ] buffer name: python_test.py
[   rooter ] [13:58:29] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
