### ISSUE TITLE
syntax highlight about icase in flygrep window

### ISSUE THREAD

**Issue by mrbeardad** [wsdjeg/SpaceVim#3849]
## Expected behavior, english is required
Highlight  uppercase search result in flygrep window

## The reproduce ways from Vim starting (Required!)
1. `set ignorecase` and `set smartcase` in my neovim
2. open nvim and press `<space>sp` to open flygrep
3. type `todo`
4. fly grep print both `todo` and `TODO` in flygrep window, but `TODO` is not highlighted
## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 20bd6d61

```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   autoload/SpaceVim/layers/core.vim
	modified:   autoload/SpaceVim/mapping/g.vim
	modified:   config/plugins_before/YouCompleteMe.vim

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	README.md.orig
	autoload/SpaceVim/default.vim.orig
	autoload/SpaceVim/layers/ui.vim.orig
	autoload/SpaceVim/mapping/g.vim.orig
	config/plugins/open-browser.vim.orig
	init.vim.orig

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 0
  colorscheme = 'default-plus'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/beardad/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = ['neco-syntax', 'neoinclude.vim', 'neosnippet-snippets', 'neopairs.vim', 'deoplete-dictionary', 'CompleteParameter.vim']
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_quickrun = 1
  enable_statusline_bfpath = 1
  enable_statusline_mode = 1
  enable_statusline_tag = 0
  enable_tabline_ft_icon = 1
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 0
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/beardad/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-translator'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.root/', '.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.SpaceVim.d/', '.clang']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 25
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'version control info', 'vcs', 'hunks']
  statusline_right_sections = ['major mode', 'fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='nil'
  auto_completion_tab_key_behavior='nil'
  auto_completion_complete_with_key_sequence='nil'
  auto_completion_enable_snippets_in_popup=1
[[layers]]
  name="checkers"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="tools"
[[layers]]
  name="leaderf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="VersionControl"
[[layers]]
  name="checker"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#python"
[[layers]]
  name="chinese"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:21:32] [ Info ] Startup with argv: ['init.vim']
[ SpaceVim ] [00:21:32] [ Info ] find local conf: /home/beardad/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [00:21:32] [ Info ] force loading global config >>>
[ SpaceVim ] [00:21:32] [ Info ] global_dir is: /home/beardad/.SpaceVim.d/
[ SpaceVim ] [00:21:32] [ Info ] start to apply config [glob]
[   rooter ] [00:21:32] [ Info ] Start to find root for: /home/beardad/.SpaceVim/init.vim
[   rooter ] [00:21:32] [ Info ]         (.git/):/home/beardad/.SpaceVim/
[ SpaceVim ] [00:21:32] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [00:21:32] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [00:21:32] [ Info ] Start to find root for: /home/beardad/.SpaceVim/init.vim
[   rooter ] [00:21:32] [ Info ]         (.git/):/home/beardad/.SpaceVim/
[   rooter ] [00:21:34] [ Info ] Start to find root for: /home/beardad/.SpaceVim/SpaceVimLayers
[   rooter ] [00:21:34] [ Info ]         (.git/):/home/beardad/.SpaceVim/
[   rooter ] [00:21:47] [ Info ] buffer name is empty, skipped!
[ SpaceVim ] [00:21:47] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [00:21:47] [ Info ] close float statusline winid:1004
[   rooter ] [00:21:47] [ Info ] buffer name is empty, skipped!
[ SpaceVim ] [00:21:47] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [00:21:51] [ Info ] close float statusline winid:1006
[   rooter ] [00:21:51] [ Info ] Start to find root for: /tmp/nvimE04r3B/3/issue_report.md
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/54128430/94460177-ef146b80-01ea-11eb-95d5-a126b01cfa91.png)
