### ISSUE TITLE
runner.vim fails after first use

### ISSUE THREAD

**Issue by Zaechus** [wsdjeg/SpaceVim#3878]
## Expected behavior
Upon pressing `SPC l c b` or a similar Cargo command, the first execution works correctly. After trying to run it again, it fails. This occurs whether or not I close the runner window or don't close it. Also, if I already have more than one file open, the runner fails as well. The command should work both times without error. This is not a critical issue for me, for I usually just open a terminal and manually run commands.

## Environment Information

- OS: Artix Linux
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 8c9cda26

I'm using Alacritty on Sway WM with pure wayland.

All of my plugins are up to date, and `:checkhealth` reports no errors.

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Install SpaceVim with the instructions
Install vimproc
Add Rust layer (not really the issue as the runner doesn't work with Python either)
cd into project directory
Open any file
`SPC l c b` (should work)
`SPC l c b` (should fail)

Error output:
```
Error detected while processing function <SNR>80_stop_runner[2]..187:
line    3:
E900: Invalid channel id
Error detected while processing function <SNR>55_execCMD[1]..SpaceVim#plugins#runner#open[12]..<SNR>80_async_run[1]..<SNR>80_stop_runner[2]..187:
line    3:
E900: Invalid channel id
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/maxwell/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/maxwell/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'rust.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:56:18] [ Info ] Startup with argv: ['src/main.rs']
[ SpaceVim ] [11:56:18] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:56:18] [ Info ] global_dir is: /home/maxwell/.SpaceVim.d/
[ SpaceVim ] [11:56:18] [ Info ] start to apply config [glob]
[   rooter ] [11:56:18] [ Info ] Load projects cache from: /home/maxwell/.cache/SpaceVim/projects.json
[   rooter ] [11:56:18] [ Info ] Start to find root for: /home/maxwell/Code/mygithub/blademaster/src/main.rs
[   rooter ] [11:56:18] [ Info ]         (.git/):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:56:18] [ Info ]         (Cargo.toml):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:56:18] [ Info ] buffer name: src/main.rs
[   rooter ] [11:56:18] [ Info ] same as current directory, no need to change.
[   rooter ] [11:56:18] [ Info ] buffer name: src/main.rs
[   rooter ] [11:56:18] [ Info ] same as current directory, no need to change.
[   rooter ] [11:56:20] [ Info ] Start to find root for: /home/maxwell/Code/mygithub/blademaster/__runner__
[   rooter ] [11:56:20] [ Info ]         (.git/):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:56:20] [ Info ]         (Cargo.toml):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:56:20] [ Info ] buffer name: __runner__
[   rooter ] [11:56:20] [ Info ] same as current directory, no need to change.
[   rooter ] [11:56:20] [ Info ] buffer name: src/main.rs
[   rooter ] [11:56:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:56:20] [ Info ]    cmd:'cargo build'
[   rooter ] [11:56:23] [ Info ] Start to find root for: /home/maxwell/Code/mygithub/blademaster/__runner__
[   rooter ] [11:56:23] [ Info ]         (.git/):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:56:23] [ Info ]         (Cargo.toml):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:56:23] [ Info ] buffer name: __runner__
[   rooter ] [11:56:23] [ Info ] same as current directory, no need to change.
[   rooter ] [11:56:23] [ Info ] buffer name: src/main.rs
[   rooter ] [11:56:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:56:32] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [11:56:32] [ Info ] buffer name: src/main.rs
[   rooter ] [11:56:32] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:56:32] [ Info ] close float statusline winid:1005
[ SpaceVim ] [11:56:32] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [11:56:32] [ Info ] buffer name: src/main.rs
[   rooter ] [11:56:32] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:56:32] [ Info ] close float statusline winid:1007
[   rooter ] [11:57:08] [ Info ] Start to find root for: /home/maxwell/Code/mygithub/blademaster/SpaceVimLayers
[   rooter ] [11:57:08] [ Info ]         (.git/):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:57:08] [ Info ]         (Cargo.toml):/home/maxwell/Code/mygithub/blademaster/
[   rooter ] [11:57:08] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [11:57:08] [ Info ] same as current directory, no need to change.
[   rooter ] [11:57:36] [ Info ] buffer name: src/main.rs
[   rooter ] [11:57:36] [ Info ] same as current directory, no need to change.
[   rooter ] [11:57:39] [ Info ] Start to find root for: /tmp/nvimwjztbR/1/issue_report.md
[   rooter ] [11:57:39] [ Info ] buffer name: /tmp/nvimwjztbR/1/issue_report.md
[   rooter ] [11:57:39] [ Info ] same as current directory, no need to change.
```
</details>
