### ISSUE TITLE
No auto complete menu popup after a dot character .

### ISSUE THREAD

**Issue by eleven-monkey** [wsdjeg/SpaceVim#3879]
## Describe the behavior that you expect from SpaceVim

**[This is a mandatory section]**

I want auto complete menu popup after dot '.'.

## Describe the problem

When I types '.' there is no auto complete menu popup.I should type all characters myself .

## Describe steps to reproduce the problem

I recorded a gif，see screenshot section .

## Environment Information

- OS: windows
- vim version: 8.1.2197
- neovim version: -
- SpaceVim version: 1.3.0-dev
- SpaceVim status: 

```
On branch master
Your branch is behind 'origin/master' by 146 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .SpaceVim.d/init.vim
	modified:   vimrc

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'completor'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\Administrator\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-pythonsense'
  project_rooter_automatically = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr']
  sidebar_direction = ''
  sidebar_width = 30
  simple_mode = 0
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  update_retry_cnt = 3
  version = '1.3.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
  autocomplete_method='ycm'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(C:\Program Files\Vim\vim81\gvim.exe)
version: 801
OS: windows
[shell, shellcmdflag, shellslash]: ['C:\Windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:12:56] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [11:13:00] [ Info ] find local conf: C:\Users\Administrator\.SpaceVim.d\init.toml
[ SpaceVim ] [11:13:00] [ Info ] loadding cached local conf: C:\Users\Administrator\.cache\SpaceVim\conf\C__Users_Administrator__SpaceVim_d_init_toml.json
[ SpaceVim ] [11:13:00] [ Info ] start to apply config [local]
[ SpaceVim ] [11:13:01] [ Info ] Start to find root for: 
[ SpaceVim ] [11:13:01] [ Info ] change to root:C:\Users\Administrator
[ SpaceVim ] [11:13:01] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [11:13:01] [ Info ] change to root:C:\Users\Administrator
[ SpaceVim ] [11:13:14] [ Info ] Start to find root for: D:\个人文件夹\陈超\python_code\事故短信转换.py
[ SpaceVim ] [11:13:14] [ Info ] change to root:C:\Users\Administrator
[ SpaceVim ] [11:13:26] [ Info ] Start to find root for: C:\Users\ADMINI~1\AppData\Local\Temp\VIACBAB.tmp\issue_report.md
[ SpaceVim ] [11:13:26] [ Info ] change to root:C:\Users\Administrator
```
</details>

## Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/62041627/95542541-a77eb280-0a28-11eb-8511-07b24a30a4e7.gif)
