### ISSUE TITLE
Runner does not support input from stdin

### ISSUE THREAD

**Issue by LuxGiammi** [wsdjeg/SpaceVim#3904]
## Expected behavior, english is required

Upon pressing `SPC-l-r` while editing a python file, the runner comes up, but an `EOFError: EOF when reading a line` is issued 

## The reproduce ways from Vim starting (Required!)
1. Enable lang#python
2. Open SpaceVim
3. Open a new file called "test.py"
4. Write
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


a = input()
```
5. Press `SPC-l-r`

## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/luxgiammi/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/luxgiammi/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-pythonsense'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'fire'
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
  statusline_separator = 'bar'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  python_file_head=['#!/usr/bin/env python', '# -*- coding: utf-8 -*-', '', '']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:16:39] [ Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [20:16:39] [ Info ] find local conf: /home/luxgiammi/.SpaceVim.d/init.toml
[ SpaceVim ] [20:16:39] [ Info ] loading cached local conf: /home/luxgiammi/.cache//SpaceVim/conf/_home_luxgiammi__SpaceVim_d_init_toml.json
[ SpaceVim ] [20:16:39] [ Info ] start to apply config [local]
[ SpaceVim ] [20:16:39] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[   rooter ] [20:16:39] [ Info ] Load projects cache from: /home/luxgiammi/.cache/SpaceVim/projects.json
[   rooter ] [20:16:39] [ Info ] Start to find root for: /home/luxgiammi/
[   rooter ] [20:16:39] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:16:39] [ Info ] buffer name: No Name
[   rooter ] [20:16:39] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:16:39] [ Info ] try to open SpaceVim welcome page
[   rooter ] [20:16:40] [ Info ] buffer name: No Name
[   rooter ] [20:16:40] [ Info ] same as current directory, no need to change.
[   rooter ] [20:16:43] [ Info ] Start to find root for: /home/luxgiammi/test.py
[   rooter ] [20:16:43] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:16:43] [ Info ] buffer name: test.py
[   rooter ] [20:16:43] [ Info ] same as current directory, no need to change.
[   rooter ] [20:17:20] [ Info ] Start to find root for: /home/luxgiammi/__runner__
[   rooter ] [20:17:20] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:17:20] [ Info ] buffer name: __runner__
[   rooter ] [20:17:20] [ Info ] same as current directory, no need to change.
[   rooter ] [20:17:20] [ Info ] buffer name: test.py
[   rooter ] [20:17:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:17:20] [ Info ]    cmd:['/usr/bin/env', 'python3', '-']
[   rooter ] [20:17:27] [ Info ] Start to find root for: /home/luxgiammi/vimfiler:default
[   rooter ] [20:17:27] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:17:27] [ Info ] buffer name: vimfiler:default
[   rooter ] [20:17:27] [ Info ] same as current directory, no need to change.
[   rooter ] [20:17:29] [ Info ] buffer name: test.py
[   rooter ] [20:17:29] [ Info ] same as current directory, no need to change.
[   rooter ] [20:17:54] [ Info ] Start to find root for: /home/luxgiammi/SpaceVimLayers
[   rooter ] [20:17:54] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:17:54] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [20:17:54] [ Info ] same as current directory, no need to change.
[   rooter ] [20:18:01] [ Info ] Start to find root for: /home/luxgiammi/
[   rooter ] [20:18:01] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:18:01] [ Info ] buffer name: No Name
[   rooter ] [20:18:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:18:01] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [20:18:01] [ Info ] close float statusline winid:1006
[   rooter ] [20:18:01] [ Info ] Start to find root for: /home/luxgiammi/
[   rooter ] [20:18:01] [ Info ]         (.SpaceVim.d/):/home/luxgiammi/
[   rooter ] [20:18:01] [ Info ] buffer name: No Name
[   rooter ] [20:18:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:18:01] [ Info ] key binding guide float statusline winid:1008
[ SpaceVim ] [20:18:12] [ Info ] close float statusline winid:1008
[   rooter ] [20:18:12] [ Info ] Start to find root for: /tmp/vHopQ6K/2/issue_report.md
[   rooter ] [20:18:12] [ Info ] buffer name: /tmp/vHopQ6K/2/issue_report.md
[   rooter ] [20:18:12] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![1602785984](https://user-images.githubusercontent.com/17674050/96170365-c77c0d80-0f23-11eb-920e-1df6d85deb39.png)
