### ISSUE TITLE
Julia layer and coc autocomplete conflict

### ISSUE THREAD

**Issue by zmactep** [wsdjeg/SpaceVim#3906]
## Expected behavior, english is required

Use `coc` autocomplete with `lang#julia` language layer.

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 0004826e

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

Open any Julia file, go to insert mode, press Tab key. Everything freezes. On Command-C (MacOS) you can see some debug output (see screenshot below).

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_before = 'myspace#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['lyokha/vim-xkbswitch', {'name': 'lyokha/vim-xkbswitch'}], ['leanprover/lean.vim', {'name': 'leanprover/lean.vim', 'on_ft': 'lean'}]]
  data_dir = '/Users/pavel/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/pavel/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'markdown-preview.nvim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['cursorpos', 'battery status', 'time']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="tools"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="sudo"
[[layers]]
  name="unite"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#racket"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#julia"
[[layers]]
  name="lang#markdown"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.4/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:02:35] [ Info ] Startup with no argv, current dir is used: ~/Dropbox/DEV/yakovlev/julia/Abase
[ SpaceVim ] [11:02:35] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:02:35] [ Info ] global_dir is: /Users/pavel/.SpaceVim.d/
[ SpaceVim ] [11:02:35] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:02:35] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [11:02:35] [ Info ] Load projects cache from: /Users/pavel/.cache/SpaceVim/projects.json
[   rooter ] [11:02:36] [ Info ] Start to find root for: /Users/pavel/Dropbox/DEV/yakovlev/julia/Abase/
[   rooter ] [11:02:36] [ Info ] buffer name: No Name
[   rooter ] [11:02:36] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:02:37] [ Info ] try to open SpaceVim welcome page
[   rooter ] [11:02:37] [ Info ] buffer name: No Name
[   rooter ] [11:02:37] [ Info ] same as current directory, no need to change.
[   rooter ] [11:02:47] [ Info ] Start to find root for: /Users/pavel/Dropbox/DEV/yakovlev/julia/Abase/src/github.jl
[   rooter ] [11:02:47] [ Info ] buffer name: src/github.jl
[   rooter ] [11:02:47] [ Info ] same as current directory, no need to change.
[   rooter ] [11:03:42] [ Info ] Start to find root for: /Users/pavel/Dropbox/DEV/yakovlev/julia/Abase/SpaceVimLayers
[   rooter ] [11:03:42] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [11:03:42] [ Info ] same as current directory, no need to change.
[   rooter ] [11:05:25] [ Info ] buffer name: src/github.jl
[   rooter ] [11:05:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:06:18] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [11:06:18] [ Info ] buffer name: src/github.jl
[   rooter ] [11:06:18] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:06:18] [ Info ] close float statusline winid:1004
[ SpaceVim ] [11:06:18] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [11:06:19] [ Info ] buffer name: src/github.jl
[   rooter ] [11:06:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:06:19] [ Info ] close float statusline winid:1006
[   rooter ] [11:06:20] [ Info ] Start to find root for: /private/var/folders/pj/q3hm9_nn5jj5nvr82zkyhg3r0000gn/T/nvimITOorT/3/issue_report.md
[   rooter ] [11:06:20] [ Info ] buffer name: /var/folders/pj/q3hm9_nn5jj5nvr82zkyhg3r0000gn/T/nvimITOorT/3/issue_report.md
[   rooter ] [11:06:20] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/1034785/96229404-89243400-0f9f-11eb-822c-240080e9da84.png)
