### ISSUE TITLE
Error from Fuzzy finding mytagfunc

### ISSUE THREAD

**Issue by chrisRidgers** [wsdjeg/SpaceVim#3929]
## Expected behavior, english is required

Not sure, I'm still figuring that out

## The reproduce ways from Vim starting (Required!)

Open vim, using spacevim keymappings: `<Leader> ]` which should try to run myTagFunc() and fail.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: e934189f

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/chris/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/chris/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'phpcomplete.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="debug"
[[layers]]
  name="incsearch"
[[layers]]
  name="lang#php"
[[layers]]
  name="gtags"
  gtagslabel='pygments'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:25:08] [ Info ] Startup with no argv, current dir is used: ~/Development/Personal/sturents-slim-test-d026ee6a195f
[ SpaceVim ] [20:25:08] [ Info ] find local conf: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/.SpaceVim.d/init.toml
[ SpaceVim ] [20:25:08] [ Info ] generate local conf: /home/chris/.cache//SpaceVim/conf/_home_chris_Development_Personal_sturents-slim-test-d026ee6a195f__SpaceVim_d_init_toml.json
[ SpaceVim ] [20:25:08] [ Info ] start to apply config [local]
[ SpaceVim ] [20:25:08] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [20:25:08] [ Info ] Load projects cache from: /home/chris/.cache/SpaceVim/projects.json
[   rooter ] [20:25:08] [ Info ] Start to find root for: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/
[   rooter ] [20:25:08] [ Info ]         (.git/):/home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/
[   rooter ] [20:25:08] [ Info ] buffer name: No Name
[   rooter ] [20:25:08] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:25:08] [ Info ] try to open SpaceVim welcome page
[   rooter ] [20:25:09] [ Info ] buffer name: No Name
[   rooter ] [20:25:09] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:25:10] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [20:25:15] [ Info ] buffer name: No Name
[   rooter ] [20:25:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:25:15] [ Info ] close float statusline winid:1004
[   rooter ] [20:25:26] [ Info ] Start to find root for: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/.SpaceVim.d/init.toml
[   rooter ] [20:25:26] [ Info ]         (.git/):/home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/
[   rooter ] [20:25:26] [ Info ] buffer name: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/.SpaceVim.d/init.toml
[   rooter ] [20:25:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:29:21] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [20:29:21] [ Info ] buffer name: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/.SpaceVim.d/init.toml
[   rooter ] [20:29:21] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:29:21] [ Info ] close float statusline winid:1006
[ SpaceVim ] [20:29:21] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [20:29:26] [ Info ] buffer name: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/.SpaceVim.d/init.toml
[   rooter ] [20:29:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:29:26] [ Info ] close float statusline winid:1008
[   rooter ] [20:29:26] [ Info ] Start to find root for: /home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/SpaceVimLayers
[   rooter ] [20:29:26] [ Info ]         (.git/):/home/chris/Development/Personal/sturents-slim-test-d026ee6a195f/
[   rooter ] [20:29:26] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [20:29:26] [ Info ] same as current directory, no need to change.
[   rooter ] [20:29:35] [ Info ] Start to find root for: /tmp/nvimMqrypK/1/issue_report.md
[   rooter ] [20:29:35] [ Info ] buffer name: /tmp/nvimMqrypK/1/issue_report.md
[   rooter ] [20:29:35] [ Info ] same as current directory, no need to change.
[   rooter ] [20:29:36] [ Info ] Start to find root for: /tmp/nvimMqrypK/1/issue_report.md
[   rooter ] [20:29:36] [ Info ] buffer name: /tmp/nvimMqrypK/1/issue_report.md
[   rooter ] [20:29:36] [ Info ] same as current directory, no need to change.
[   rooter ] [20:29:36] [ Info ] buffer name: /tmp/nvimMqrypK/1/issue_report.md
[   rooter ] [20:29:36] [ Info ] same as current directory, no need to change.
[   rooter ] [20:32:10] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [20:32:10] [ Info ] same as current directory, no need to change.
[   rooter ] [20:32:12] [ Info ] buffer name: .SpaceVim.d/init.toml
[   rooter ] [20:32:12] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:32:15] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [20:32:15] [ Info ] buffer name: .SpaceVim.d/init.toml
[   rooter ] [20:32:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:32:15] [ Info ] close float statusline winid:1014
[ SpaceVim ] [20:32:15] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [20:32:20] [ Info ] buffer name: .SpaceVim.d/init.toml
[   rooter ] [20:32:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:32:20] [ Info ] close float statusline winid:1016
[   rooter ] [20:32:20] [ Info ] Start to find root for: /tmp/nvimMqrypK/2/issue_report.md
[   rooter ] [20:32:20] [ Info ] buffer name: /tmp/nvimMqrypK/2/issue_report.md
[   rooter ] [20:32:20] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/5954265/97754350-4ad65b00-1aef-11eb-832b-0a3df3fcc3bd.png)
