### ISSUE TITLE
[Clojure] cmd-clj command not found when starting Clojure REPL

### ISSUE THREAD

**Issue by practicalli-johnny** [wsdjeg/SpaceVim#3931]
## Expected behavior
`SPC l s i` should open a Clojure REPL when run with a Clojure file open.

## Actual behavior
Instead, a new REPL window appears showing the following error:
```
[REPL executable] 'cmd-clj'

--------------------
/bin/bash: cmd-clj: command not found

[Done] exited with code=127 in 0.049968 seconds
```
**From the [hack in the comment below](#issuecomment-720140933) it seems the correct binary name is not found or incorrectly set as `cmd-clj` on Linux system**

The `clojure` binary is installed in /usr/local/bin and runs in the terminal used to run neovim.

```
clojure -Sdescribe
{:version "1.10.1.727"
 :config-files ["/usr/local/lib/clojure/deps.edn" "/home/spacevim/.clojure/deps.edn" ]
 :config-user "/home/spacevim/.clojure/deps.edn"
 :config-project "deps.edn"
 :install-dir "/usr/local/lib/clojure"
 :config-dir "/home/spacevim/.clojure"
 :cache-dir "/home/spacevim/.clojure/.cpcache"
 :force false
 :repro false
 :main-aliases ""
 :repl-aliases ""}
```

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.3
- SpaceVim version: 1.6.0-dev
- SpaceVim status: af773b6b

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Add the Clojure layer, `lang#clojure` and restart SpaceVim

Open a Clojure source code file from a project with a deps.edn configuration file.

`SPC l s i` or `, s i` to start a repl

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/spacevim/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'fd'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/spacevim/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-fireplace'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'project.clj', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#clojure"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:20:56] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [18:20:56] [ Info ] find local conf: /home/spacevim/.SpaceVim.d/init.toml
[ SpaceVim ] [18:20:56] [ Info ] generate local conf: /home/spacevim/.cache//SpaceVim/conf/_home_spacevim__SpaceVim_d_init_toml.json
[ SpaceVim ] [18:20:56] [ Info ] start to apply config [local]
[ SpaceVim ] [18:20:56] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [18:20:57] [ Info ] Load projects cache from: /home/spacevim/.cache/SpaceVim/projects.json
[   rooter ] [18:20:57] [ Info ] Start to find root for: /home/spacevim/
[   rooter ] [18:20:57] [ Info ] buffer name: No Name
[   rooter ] [18:20:57] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:20:57] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:20:57] [ Info ] buffer name: No Name
[   rooter ] [18:20:57] [ Info ] same as current directory, no need to change.
[   rooter ] [18:21:19] [ Info ] Start to find root for: /home/spacevim/projects/playground/src/practicalli/playground.clj
[   rooter ] [18:21:19] [ Info ] buffer name: projects/playground/src/practicalli/playground.clj
[   rooter ] [18:21:19] [ Info ] same as current directory, no need to change.
[   rooter ] [18:21:23] [ Info ] Start to find root for: /home/spacevim/__REPL__
[   rooter ] [18:21:23] [ Info ] buffer name: __REPL__
[   rooter ] [18:21:23] [ Info ] same as current directory, no need to change.
[   rooter ] [18:21:23] [ Info ] buffer name: projects/playground/src/practicalli/playground.clj
[   rooter ] [18:21:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:23:36] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [18:23:37] [ Info ] buffer name: projects/playground/src/practicalli/playground.clj
[   rooter ] [18:23:37] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:23:37] [ Info ] close float statusline winid:1005
[ SpaceVim ] [18:23:37] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [18:23:40] [ Info ] buffer name: projects/playground/src/practicalli/playground.clj
[   rooter ] [18:23:40] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:23:40] [ Info ] close float statusline winid:1007
[   rooter ] [18:23:40] [ Info ] Start to find root for: /tmp/nvimyPrn4K/3/issue_report.md
[   rooter ] [18:23:40] [ Info ] buffer name: /tmp/nvimyPrn4K/3/issue_report.md
[   rooter ] [18:23:40] [ Info ] same as current directory, no need to change.
```
</details>
