### ISSUE TITLE
Invalid expression project_paths

### ISSUE THREAD

**Issue by mrmodolo** [wsdjeg/SpaceVim#3944]
## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/modolo/.cache/'
  debug_level = 1
  default_indent = 2
  default_shell = 'terminal'
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
    enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  layer_lang_java_formatter = '/home/modolo/.config/neoformat/google-java-format-1.9-all-deps.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
    lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/modolo/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-javacomplete2'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json', 'pom.xml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerT
erminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
  format_on_save=0
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="git"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#groovy"
[[layers]]
  name="lang#nim"
[[layers]]
  name="lang#clj"
[[layers]]
  name="lang#java"
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.ecli
pse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.level=NONE', '-noverify', '-Xmx1G', '-jar', '~/opt/lsp/jdt-language-server/plugins/org.eclipse.
equinox.launcher_1.5.800.v20200727-1323.jar', '-configuration', '~/opt/lsp/jdt-language-server/config_linux', '-data', '~/.cache/javalsp']}
  filetypes=['java', 'ada']
[[layers]]
  name="core#projectmanager"
### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:37:05] [ Info ] Startup with no argv, current dir is used: ~/hsc-integrações/openshift-grupos
[ SpaceVim ] [18:37:05] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:37:05] [ Info ] global_dir is: /home/modolo/.SpaceVim.d/
[ SpaceVim ] [18:37:05] [ Info ] start to apply config [glob]
[   rooter ] [18:37:05] [ Info ] Load projects cache from: /home/modolo/.cache/SpaceVim/projects.json
[   rooter ] [18:37:05] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [18:37:05] [ Info ] Start to find root for: /home/modolo/hsc-integrações/openshift-grupos/
[   rooter ] [18:37:05] [ Info ]         (.git/):/home/modolo/hsc-integrações/openshift-grupos/
[   rooter ] [18:37:05] [ Info ] buffer name: No Name
[   rooter ] [18:37:05] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:37:05] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:37:05] [ Info ] buffer name: No Name
[   rooter ] [18:37:05] [ Info ] same as current directory, no need to change.
[   rooter ] [18:38:37] [ Info ] Start to find root for: /home/modolo/hsc-integrações/openshift-grupos/
[   rooter ] [18:38:37] [ Info ]         (.git/):/home/modolo/hsc-integrações/openshift-grupos/
[   rooter ] [18:38:37] [ Info ]         (.git/):/home/modolo/hsc-integrações/openshift-grupos/
[   rooter ] [18:38:37] [ Info ] buffer name: No Name
[   rooter ] [18:38:37] [ Info ] same as current directory, no need to change.
```
</details>
      `
`

## Screenshots
![image](https://user-images.githubusercontent.com/1923174/98417808-5fbb6d00-2060-11eb-8f27-32f04b26f52d.png)
