### ISSUE TITLE
"Generate key bindings" conflicting with "Gradle key bindings"

### ISSUE THREAD

**Issue by TheWall89** [wsdjeg/SpaceVim#3953]
## Expected behavior, english is required

If you have a look at the SpaceVim.txt help file on Github master branch, you can see that both [Generate key bindings](https://github.com/SpaceVim/SpaceVim/blob/ae6052b9e082b7a2b13e6661c3164c9bbfe75d46/doc/SpaceVim.txt#L2426) and [Gradle key bindings](https://github.com/SpaceVim/SpaceVim/blob/ae6052b9e082b7a2b13e6661c3164c9bbfe75d46/doc/SpaceVim.txt#L2426) start with the sequence `SPC l g`. If I press that sequence in my SpaceVim, I get Gradle operations. The generate stuff is accecssible via `<Leader> j` but this is not documented anywhere.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: ae6052b9

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

Open a Java project or file.
Press `SPC l g` and you get the Gradle keybindings.
Press `<Leader> j` and you get Java autogenerate keybindings.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'one'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['masukomi/vim-markdown-folding', {'name': 'masukomi/vim-markdown-folding', 'merged': 0}], ['glacambre/firenvim', {'repo': 'glacambre/firenvim', 'merged': 0}], ['machakann/vim-highlightedyank', {'name': 'machakann/vim-highlightedyank', 'merged': 0}], ['Konfekt/FastFold', {'repo': 'Konfekt/FastFold', 'merged': 0}], ['pseewald/vim-anyfold', {'repo': 'pseewald/vim-anyfold', 'merged': 0}]]
  data_dir = '/home/thewall/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  layer_lang_java_formatter = '/home/thewall/Programmi/google-java-format-1.9-all-deps.jar'
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/thewall/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'LanguageClient-neovim'
  project_rooter_automatically = 1
  project_rooter_outermost = 0
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 1
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="incsearch"
[[layers]]
  name="gtags"
  gtagslabel='pygments'
[[layers]]
  name="denite"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="sudo"
[[layers]]
  name="tools"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lang#markdown"
  enabled_formater=['prettier']
  listItemIndent='tab'
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.level=ALL', '-noverify', '-Xmx1G', '-jar', '~/Programmi/lsp/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar', '-configuration', '~/Programmi/lsp/eclipse.jdt.ls/config_linux', '-data', '~/.cache/lsp']}
  filetypes=['java']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:02:50] [ Info ] Startup with argv: ['src/main/java/it/cnit/blueprint/composer/App.java']
[ SpaceVim ] [13:02:50] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [13:02:50] [ Info ] global_dir is: /home/thewall/Coding/thewall-home-config/SpaceVim.d/
[ SpaceVim ] [13:02:50] [ Info ] start to apply config [glob]
[ SpaceVim ] [13:02:50] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [13:02:51] [ Info ] Load projects cache from: /home/thewall/.cache/SpaceVim/projects.json
[   rooter ] [13:02:51] [ Info ] Start to find root for: /home/thewall/Coding/5G-EVE/exp-nsd-composer/src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:02:51] [ Info ]         (.git/):/home/thewall/Coding/5G-EVE/exp-nsd-composer/
[   rooter ] [13:02:51] [ Info ]         (pom.xml):/home/thewall/Coding/5G-EVE/exp-nsd-composer/
[   rooter ] [13:02:51] [ Info ]         (.SpaceVim.d/):/home/thewall/Coding/thewall-home-config/
[   rooter ] [13:02:51] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:02:51] [ Info ] same as current directory, no need to change.
[   rooter ] [13:02:51] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:02:51] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:02:56] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [13:02:56] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:02:56] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:02:56] [ Info ] close float statusline winid:1003
[ SpaceVim ] [13:02:56] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [13:02:59] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:02:59] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:02:59] [ Info ] close float statusline winid:1005
[ SpaceVim ] [13:03:02] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [13:03:02] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:03:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:03:02] [ Info ] close float statusline winid:1007
[ SpaceVim ] [13:03:02] [ Info ] key binding guide float statusline winid:1009
[   rooter ] [13:03:04] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:03:04] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:03:04] [ Info ] close float statusline winid:1009
[   rooter ] [13:03:04] [ Info ] Start to find root for: /home/thewall/Coding/5G-EVE/exp-nsd-composer/__LanguageClient__
[   rooter ] [13:03:04] [ Info ]         (.git/):/home/thewall/Coding/5G-EVE/exp-nsd-composer/
[   rooter ] [13:03:04] [ Info ]         (pom.xml):/home/thewall/Coding/5G-EVE/exp-nsd-composer/
[   rooter ] [13:03:04] [ Info ]         (.SpaceVim.d/):/home/thewall/Coding/thewall-home-config/
[   rooter ] [13:03:04] [ Info ] buffer name: __LanguageClient__
[   rooter ] [13:03:04] [ Info ] same as current directory, no need to change.
[   rooter ] [13:03:05] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [13:03:05] [ Info ] same as current directory, no need to change.
[   rooter ] [14:35:00] [ Info ] buffer name: __LanguageClient__
[   rooter ] [14:35:00] [ Info ] same as current directory, no need to change.
[   rooter ] [14:35:20] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:35:31] [ Info ] key binding guide float statusline winid:1012
[   rooter ] [14:35:33] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:33] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:35:33] [ Info ] close float statusline winid:1012
[ SpaceVim ] [14:35:33] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [14:35:34] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:34] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:35:34] [ Info ] close float statusline winid:1014
[ SpaceVim ] [14:35:39] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [14:35:39] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:39] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:35:39] [ Info ] close float statusline winid:1016
[ SpaceVim ] [14:35:39] [ Info ] key binding guide float statusline winid:1018
[   rooter ] [14:35:44] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:44] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:35:44] [ Info ] close float statusline winid:1018
[   rooter ] [14:35:57] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:57] [ Info ] same as current directory, no need to change.
[   rooter ] [14:35:57] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:35:57] [ Info ] same as current directory, no need to change.
[   rooter ] [14:35:57] [ Info ] Start to find root for: /home/thewall/Coding/thewall-home-config/SpaceVim.d/init.toml
[   rooter ] [14:35:57] [ Info ]         (.git/):/home/thewall/Coding/thewall-home-config/
[   rooter ] [14:35:57] [ Info ]         (.SpaceVim.d/):/home/thewall/Coding/thewall-home-config/
[   rooter ] [14:35:57] [ Info ] buffer name: /home/thewall/Coding/thewall-home-config/SpaceVim.d/init.toml
[   rooter ] [14:35:57] [ Info ] change to root: /home/thewall/Coding/thewall-home-config/
[   rooter ] [14:41:30] [ Info ] buffer name: /home/thewall/Coding/5G-EVE/exp-nsd-composer/src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:41:30] [ Info ] change to root: /home/thewall/Coding/5G-EVE/exp-nsd-composer/
[ SpaceVim ] [14:41:36] [ Info ] key binding guide float statusline winid:1023
[   rooter ] [14:41:36] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:41:36] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:41:36] [ Info ] close float statusline winid:1023
[ SpaceVim ] [14:41:36] [ Info ] key binding guide float statusline winid:1025
[   rooter ] [14:41:36] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:41:36] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:41:36] [ Info ] close float statusline winid:1025
[ SpaceVim ] [14:41:42] [ Info ] key binding guide float statusline winid:1027
[   rooter ] [14:41:42] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:41:42] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:41:42] [ Info ] close float statusline winid:1027
[ SpaceVim ] [14:41:42] [ Info ] key binding guide float statusline winid:1029
[   rooter ] [14:41:44] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:41:44] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:41:44] [ Info ] close float statusline winid:1029
[ SpaceVim ] [14:41:44] [ Info ] key binding guide float statusline winid:1031
[   rooter ] [14:42:46] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:42:46] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:42:46] [ Info ] close float statusline winid:1031
[ SpaceVim ] [14:42:51] [ Info ] key binding guide float statusline winid:1033
[   rooter ] [14:42:55] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:42:55] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:42:55] [ Info ] close float statusline winid:1033
[ SpaceVim ] [14:42:55] [ Info ] key binding guide float statusline winid:1035
[   rooter ] [14:43:43] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:43:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:43:43] [ Info ] close float statusline winid:1035
[ SpaceVim ] [14:43:47] [ Info ] key binding guide float statusline winid:1037
[   rooter ] [14:43:47] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:43:47] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:43:47] [ Info ] close float statusline winid:1037
[ SpaceVim ] [14:43:47] [ Info ] key binding guide float statusline winid:1039
[   rooter ] [14:43:49] [ Info ] buffer name: src/main/java/it/cnit/blueprint/composer/App.java
[   rooter ] [14:43:49] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:43:49] [ Info ] close float statusline winid:1039
[   rooter ] [14:43:51] [ Info ] Start to find root for: /tmp/nvimxz1UBp/28/issue_report.md
[   rooter ] [14:43:51] [ Info ] buffer name: /tmp/nvimxz1UBp/28/issue_report.md
[   rooter ] [14:43:51] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

Another weird thing. Pressing `<Leader>` and waiting for the guide to show:
![image](https://user-images.githubusercontent.com/2626117/98819404-1aff4f80-242d-11eb-8855-6e5a1cb83559.png)
The `[j]` has no description.

EDIT: I submitted by error an empty issue at the beginning. Sorry.
