### ISSUE TITLE
Opening & closing files containing {} causes error with SpaceVim#layers#core#statusline#get

### ISSUE THREAD

**Issue by ReedyBear** [wsdjeg/SpaceVim#3976]
## Expected behavior, english is required
Open the file with no errors

## The reproduce ways from Vim starting (Required!)
I'm using neovim & nerdtree. 
1. Open neovim (spacevim is open w/ nerdtree on the right)
2. [space] -> 2 (focus nerdtree)
3. go to a file containing `{` and `}` in the name
4. press [o] to open it
5. Below error displays
6. Save the file `:w`, I think. It's bound to ctrl+s on mine
7. Same error as below, PLUS `Neomake: Error during User autocmd for NeomakeFinished: Vim(return):E488: Trailing characters`

### The error I'm getting:
<pre><span style="background-color:#FB4934"><font color="#282828"><b>Error detected while processing function SpaceVim#layers#core#statusline#get[180]..&lt;SNR&gt;37_active[15]..112[6]..109[1]..110:</b></font></span>
<span style="background-color:#282828"><font color="#7C6F64">line    3:</font></span>
<span style="background-color:#FB4934"><font color="#282828"><b>E488: Trailing characters</b></font></span>
<span style="background-color:#FB4934"><font color="#282828"><b>E488: Trailing characters</b></font></span></pre>

Also, SOMETIMES, it'll open a new window as well... on save

### SPC h I
See next comment

## Screenshots
No screenshots

**Comment by ReedyBear** [comment]
## Expected behavior, english is recommend

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 3d525cb8


```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   init.vim

no changes added to commit (use "git add" and/or "git commit -a")
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/reed/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/reed/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'neomru.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=35
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#css"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#python"
[[layers]]
  name="fzf"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:46:21] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [14:46:21] [ Info ] find local conf: /home/reed/.SpaceVim.d/init.toml
[ SpaceVim ] [14:46:21] [ Info ] loading cached local conf: /home/reed/.cache//SpaceVim/conf/_home_reed__SpaceVim_d_init_toml.json
[ SpaceVim ] [14:46:21] [ Info ] start to apply config [local]
[ SpaceVim ] [14:46:21] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [14:46:21] [ Info ] Load projects cache from: /home/reed/.cache/SpaceVim/projects.json
[   rooter ] [14:46:22] [ Info ] Start to find root for: /home/reed/
[   rooter ] [14:46:22] [ Info ] buffer name: No Name
[   rooter ] [14:46:22] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:46:22] [ Info ] try to open SpaceVim welcome page
[   rooter ] [14:46:22] [ Info ] buffer name: No Name
[   rooter ] [14:46:22] [ Info ] same as current directory, no need to change.
[   rooter ] [14:46:24] [ Info ] Start to find root for: /home/reed/NERD_tree_1
[   rooter ] [14:46:24] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:46:24] [ Info ] same as current directory, no need to change.
[   rooter ] [14:46:33] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/join.{gameId}.php
[   rooter ] [14:46:33] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:33] [ Info ] buffer name: data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/join.{gameId}.php
[   rooter ] [14:46:33] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:36] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:46:36] [ Info ] change to root: /home/reed/
[   rooter ] [14:46:38] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:46:38] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:38] [ Info ] buffer name: data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:46:38] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:42] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:46:42] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:42] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:46:42] [ Info ] same as current directory, no need to change.
[   rooter ] [14:46:46] [ Info ] buffer name: code/Game/public/join.{gameId}.php
[   rooter ] [14:46:46] [ Info ] same as current directory, no need to change.
[   rooter ] [14:46:48] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:48] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:46:48] [ Info ] buffer name: No Name
[   rooter ] [14:46:48] [ Info ] same as current directory, no need to change.
[   rooter ] [14:46:50] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:46:50] [ Info ] change to root: /home/reed/
[   rooter ] [14:47:31] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:47:31] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:47:31] [ Info ] buffer name: data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:47:31] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:50:34] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:50:34] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:50:34] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:50:34] [ Info ] same as current directory, no need to change.
[   rooter ] [14:50:58] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:50:58] [ Info ] change to root: /home/reed/
[   rooter ] [14:51:00] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new.php
[   rooter ] [14:51:00] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:51:00] [ Info ] buffer name: data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new.php
[   rooter ] [14:51:00] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:51:02] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:02] [ Info ] same as current directory, no need to change.
[   rooter ] [14:51:05] [ Info ] buffer name: code/Game/public/new.php
[   rooter ] [14:51:05] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:51:10] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [14:51:10] [ Info ] buffer name: code/Game/public/new.php
[   rooter ] [14:51:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:51:10] [ Info ] close float statusline winid:1005
[ SpaceVim ] [14:51:10] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [14:51:11] [ Info ] buffer name: code/Game/public/new.php
[   rooter ] [14:51:11] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:51:11] [ Info ] close float statusline winid:1007
[   rooter ] [14:51:11] [ Info ] buffer name: No Name
[   rooter ] [14:51:11] [ Info ] same as current directory, no need to change.
[   rooter ] [14:51:13] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:13] [ Info ] same as current directory, no need to change.
[   rooter ] [14:51:22] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:22] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:51:22] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:22] [ Info ] same as current directory, no need to change.
[   rooter ] [14:51:30] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:51:30] [ Info ] change to root: /home/reed/
[   rooter ] [14:51:41] [ Info ] buffer name: data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:41] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:51:47] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:47] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:51:47] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:51:47] [ Info ] same as current directory, no need to change.
[   rooter ] [14:53:28] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/new-join.{gameId}.php
[   rooter ] [14:53:28] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:53:28] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:53:28] [ Info ] same as current directory, no need to change.
[   rooter ] [14:54:33] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/SpaceVimLayers
[   rooter ] [14:54:33] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:54:33] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [14:54:33] [ Info ] same as current directory, no need to change.
[   rooter ] [14:56:11] [ Info ] buffer name: code/Game/public/new-join.{gameId}.php
[   rooter ] [14:56:11] [ Info ] same as current directory, no need to change.
[   rooter ] [14:56:15] [ Info ] buffer name: No Name
[   rooter ] [14:56:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:56:19] [ Info ] key binding guide float statusline winid:1011
[   rooter ] [14:56:20] [ Info ] buffer name: No Name
[   rooter ] [14:56:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:56:20] [ Info ] close float statusline winid:1011
[ SpaceVim ] [14:56:20] [ Info ] key binding guide float statusline winid:1013
[   rooter ] [14:56:26] [ Info ] buffer name: No Name
[   rooter ] [14:56:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:56:26] [ Info ] close float statusline winid:1013
[ SpaceVim ] [14:56:26] [ Info ] key binding guide float statusline winid:1015
[   rooter ] [14:56:28] [ Info ] buffer name: No Name
[   rooter ] [14:56:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:56:28] [ Info ] close float statusline winid:1015
[ SpaceVim ] [14:56:30] [ Info ] key binding guide float statusline winid:1017
[   rooter ] [14:56:30] [ Info ] buffer name: No Name
[   rooter ] [14:56:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:56:30] [ Info ] close float statusline winid:1017
[ SpaceVim ] [14:56:30] [ Info ] key binding guide float statusline winid:1019
[   rooter ] [14:56:34] [ Info ] buffer name: No Name
[   rooter ] [14:56:34] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:56:34] [ Info ] close float statusline winid:1019
[   rooter ] [14:56:36] [ Info ] Start to find root for: /tmp/nvimK4xGIQ/11/issue_report.md
[   rooter ] [14:56:36] [ Info ] buffer name: /tmp/nvimK4xGIQ/11/issue_report.md
[   rooter ] [14:56:36] [ Info ] same as current directory, no need to change.
[   rooter ] [14:56:36] [ Info ] Start to find root for: /tmp/nvimK4xGIQ/11/issue_report.md
[   rooter ] [14:56:36] [ Info ] buffer name: /tmp/nvimK4xGIQ/11/issue_report.md
[   rooter ] [14:56:36] [ Info ] same as current directory, no need to change.
[   rooter ] [14:58:19] [ Info ] buffer name: No Name
[   rooter ] [14:58:19] [ Info ] same as current directory, no need to change.
[   rooter ] [14:58:21] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:58:21] [ Info ] change to root: /home/reed/
[   rooter ] [14:58:26] [ Info ] buffer name: No Name
[   rooter ] [14:58:26] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:58:26] [ Info ] buffer name: /tmp/nvimK4xGIQ/11/issue_report.md
[   rooter ] [14:58:26] [ Info ] same as current directory, no need to change.
[   rooter ] [14:58:27] [ Info ] buffer name: No Name
[   rooter ] [14:58:27] [ Info ] same as current directory, no need to change.
[   rooter ] [14:58:29] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:58:29] [ Info ] change to root: /home/reed/
[   rooter ] [14:58:32] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/join.{gameId}.php
[   rooter ] [14:58:32] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:58:32] [ Info ] buffer name: data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/join.{gameId}.php
[   rooter ] [14:58:32] [ Info ] change to root: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:58:37] [ Info ] Start to find root for: /home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/code/Game/public/join.{gameId}.php
[   rooter ] [14:58:37] [ Info ]         (.git/):/home/reed/data/Taeluf/Dev/Project-Main/mtgpaper.me/
[   rooter ] [14:58:37] [ Info ] buffer name: code/Game/public/join.{gameId}.php
[   rooter ] [14:58:37] [ Info ] same as current directory, no need to change.
[   rooter ] [14:58:58] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:58:58] [ Info ] change to root: /home/reed/
[ SpaceVim ] [14:59:02] [ Info ] key binding guide float statusline winid:1025
[   rooter ] [14:59:03] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:59:03] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:59:03] [ Info ] close float statusline winid:1025
[ SpaceVim ] [14:59:03] [ Info ] key binding guide float statusline winid:1027
[   rooter ] [14:59:05] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:59:05] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:59:05] [ Info ] close float statusline winid:1027
[   rooter ] [14:59:06] [ Info ] Start to find root for: /tmp/nvimK4xGIQ/15/issue_report.md
[   rooter ] [14:59:06] [ Info ] buffer name: /tmp/nvimK4xGIQ/15/issue_report.md
[   rooter ] [14:59:06] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
