### ISSUE TITLE
Encounter errors when I start Neovim.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#4006]
## Expected behavior, english is required

No error is shown when I start Neovim.

## The reproduce ways from Vim starting (Required!)

Just start Neovim.

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: windows
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: a2ef673a

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  background = 'dark'
  bootstrap_after = 'bootstrap_after#init'
  bootstrap_before = 'bootstrap_before#init'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['junegunn/vim-easy-align', {'name': 'junegunn/vim-easy-align', 'merged': 0}]]
  data_dir = 'C:\Users\linkun\.cache\'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 1
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_line = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 1
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 4
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'ssfjhh'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\linkun\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'PatentHubSearchCriteria'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'major mode', 'minor mode lighters', 'filename', 'fileformat', 'version control info', 'whitespace']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='smart'
  auto-completion-tab-key-behavior='smart'
  auto-completion-delay=200
  auto-completion-complete-with-key-sequence-delay=0.1
  auto-completion-quotes-key-behavior='smart'
  auto-completion-complete-with-key-sequence='nil'
[[layers]]
  name="checkers"
  show_cursor_error=1
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_scrollbar=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="chinese"
[[layers]]
  name="git"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
[[layers]]
  name="lang#python"
  python-file-head=['#!/usr/bin/env python', '# -*- coding: utf-8 -*-', '# Author: Kun Lin', '# Time: `strftime("%Y-%m-%d %T")`', '', '']
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#markdown"
  enableWcwidth=1
  listItemIndent='1'
  listItemChar='-'
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#julia"
[[layers]]
  name="lang#autohotkey"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#incoPatSearchCriteria"
[[layers]]
  name="lang#PatentHubSearchCriteria"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\Users\linkun\scoop\apps\neovim\current\bin\nvim.exe)
version: 800
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:51:39] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [20:51:39] [ Info ] find local conf: C:\Users\linkun\.SpaceVim.d\init.toml
[ SpaceVim ] [20:51:39] [ Info ] loading cached local conf: C:\Users\linkun\.cache\\SpaceVim\conf\C__Users_linkun__SpaceVim_d_init_toml.json
[ SpaceVim ] [20:51:39] [ Info ] start to apply config [local]
[ SpaceVim ] [20:51:39] [ Info ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [20:51:40] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [20:53:54] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [20:53:55] [ Info ] close float statusline winid:1004
[ SpaceVim ] [20:53:55] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [20:53:57] [ Info ] close float statusline winid:1006
[ SpaceVim ] [20:55:06] [ Info ] key binding guide float statusline winid:1009
[ SpaceVim ] [20:55:07] [ Info ] close float statusline winid:1009
[ SpaceVim ] [20:55:07] [ Info ] key binding guide float statusline winid:1011
[ SpaceVim ] [20:55:13] [ Info ] close float statusline winid:1011
[ SpaceVim ] [20:55:41] [ Info ] key binding guide float statusline winid:1013
[ SpaceVim ] [20:55:41] [ Info ] close float statusline winid:1013
[ SpaceVim ] [20:55:41] [ Info ] key binding guide float statusline winid:1015
[ SpaceVim ] [20:55:45] [ Info ] close float statusline winid:1015
[ SpaceVim ] [20:59:18] [ Info ] key binding guide float statusline winid:1018
[ SpaceVim ] [20:59:19] [ Info ] close float statusline winid:1018
[ SpaceVim ] [20:59:19] [ Info ] key binding guide float statusline winid:1020
[ SpaceVim ] [20:59:20] [ Info ] close float statusline winid:1020
```

</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Environment Information

- OS: windows
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: a2ef673a

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

When I start vim, I encounter the follow 2 errors every time this month.
![image](https://user-images.githubusercontent.com/5350867/102217457-8e5a1c80-3f17-11eb-94fa-469217f74564.png)
![image](https://user-images.githubusercontent.com/5350867/102217497-9e71fc00-3f17-11eb-8aae-2808d7bab9ce.png)
