### ISSUE TITLE
Undefined variable: g:gtags_cache_dir

### ISSUE THREAD

**Issue by programmador** [wsdjeg/SpaceVim#4007]
Hello! I do not update SpaceVim very often and thereby cannot tell when the issue has appeared. Probably few months ago.
I'm using SpaceVim with PHP + LSP (intelephense) + gtags (ctags)
SpaceVim blaims that a variable needed for ctags is not set while I'm trying to find a type definition with <KBD> SPC m g d </KBD>:
```
Error detected while processing function gtags#global[24]..<SNR>304_ExecLoad:
line   35:
E121: Undefined variable: g:gtags_cache_dir
E116: Invalid arguments for function <SNR>7_unify_path
E15: Invalid expression: s:FILE.unify_path(g:gtags_cache_dir) . s:FILE.path_to_fname($GTAGSROOT)
Press ENTER or type command to continue
```
Imperatively setting tags_cache_dir for gtags layer config does not help.
Though setting the variable in an autoload file helps:
```
func! myspacevim#before() abort
    let g:gtags_cache_dir="~/.cache/SpaceVim/tags/"
endfunction
```

## Expected behavior, english is required

<KBD>SPC m g d</KBD> should perform a jump to antother file/class

## The reproduce ways from Vim starting (Required!)

- Start SpaceVim
- Open a file. Encounters with PHP files at least.
- Put cursor at any type. For example a function return type hint.
- Press <KBD>SPC m g d</KBD>

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: a2ef673a

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/alexander/.cache/'
  debug_level = 1
  default_indent = 4
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/alexander/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'phpactor'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', 'pubspec.yaml', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 60
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lsp"
  override_cmd={'php': ['intelephense', '--stdio'], 'rust': ['rust-analyzer'], 'dart': ['dart', '/opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot', '--lsp']}
  filetypes=['dart', 'php', 'rust']
[[layers]]
  name="colorscheme"
[[layers]]
  name="ctrlspace"
  enable-spacevim-styled-keys=1
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="gtags"
  tags_cache_dir='~/.cache/SpaceVim/tags/'
[[layers]]
  name="sudo"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#dart"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#rust"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:16:10] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim.d/autoload
[ SpaceVim ] [14:16:10] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [14:16:10] [ Info ] global_dir is: /home/alexander/.SpaceVim.d/
[ SpaceVim ] [14:16:10] [ Info ] start to apply config [glob]
[ SpaceVim ] [14:16:10] [ Info ] myspacevim#before called
[ SpaceVim ] [14:16:10] [ Error ] failed to call bootstrap_before function: myspacevim#before
[ SpaceVim ] [14:16:10] [ Error ]        exception: Vim(let):E35: No previous regular expression
[ SpaceVim ] [14:16:10] [ Error ]        throwpoint: function SpaceVim#custom#load[34]..<SNR>48_load_glob_conf[10]..SpaceVim#custom#apply[54]..myspacevim#before, line 4
[ SpaceVim ] [14:16:10] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[   rooter ] [14:16:10] [ Info ] Load projects cache from: /home/alexander/.cache/SpaceVim/projects.json
[   rooter ] [14:16:10] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [14:16:10] [ Info ] Start to find root for: /home/alexander/.SpaceVim.d/autoload/
[   rooter ] [14:16:10] [ Info ]         (.git/):/home/alexander/.SpaceVim.d/
[   rooter ] [14:16:10] [ Info ] buffer name: No Name
[   rooter ] [14:16:10] [ Info ] change to root: /home/alexander/.SpaceVim.d/
[ SpaceVim ] [14:16:10] [ Info ] try to open SpaceVim welcome page
[   rooter ] [14:16:10] [ Info ] buffer name: No Name
[   rooter ] [14:16:10] [ Info ] change to root: /home/alexander/.SpaceVim.d/
[   rooter ] [14:16:11] [ Info ] Start to find root for: /home/alexander/.SpaceVim.d/
[   rooter ] [14:16:11] [ Info ]         (.git/):/home/alexander/.SpaceVim.d/
[   rooter ] [14:16:11] [ Info ] buffer name: No Name
[   rooter ] [14:16:11] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:11] [ Info ] Start to find root for: /home/alexander/.SpaceVim.d/
[   rooter ] [14:16:11] [ Info ]         (.git/):/home/alexander/.SpaceVim.d/
[   rooter ] [14:16:11] [ Info ] buffer name: No Name
[   rooter ] [14:16:11] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:11] [ Info ] buffer name: No Name
[   rooter ] [14:16:11] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:14] [ Info ] Start to find root for: /home/alexander/code/antifraud/NERD_tree_1
[   rooter ] [14:16:14] [ Info ]         (.git/):/home/alexander/code/antifraud/
[   rooter ] [14:16:14] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:16:14] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:14] [ Info ] Start to find root for: /home/alexander/code/antifraud/
[   rooter ] [14:16:14] [ Info ]         (.git/):/home/alexander/code/antifraud/
[   rooter ] [14:16:14] [ Info ] buffer name: No Name
[   rooter ] [14:16:14] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:15] [ Info ] buffer name: NERD_tree_1
[   rooter ] [14:16:15] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:24] [ Info ] Start to find root for: /home/alexander/code/antifraud/src/Context/AntiFraud/CustomerCache/Model/CachedCustomer.php
[   rooter ] [14:16:24] [ Info ]         (.git/):/home/alexander/code/antifraud/
[   rooter ] [14:16:24] [ Info ] buffer name: src/Context/AntiFraud/CustomerCache/Model/CachedCustomer.php
[   rooter ] [14:16:24] [ Info ] same as current directory, no need to change.
[   rooter ] [14:16:26] [ Info ] buffer name: src/Context/AntiFraud/CustomerCache/Model/CachedCustomer.php
[   rooter ] [14:16:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:16:30] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [14:16:30] [ Info ] buffer name: src/Context/AntiFraud/CustomerCache/Model/CachedCustomer.php
[   rooter ] [14:16:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:16:30] [ Info ] close float statusline winid:1008
[ SpaceVim ] [14:16:30] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [14:16:30] [ Info ] buffer name: src/Context/AntiFraud/CustomerCache/Model/CachedCustomer.php
[   rooter ] [14:16:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:16:30] [ Info ] close float statusline winid:1010
[   rooter ] [14:16:33] [ Info ] Start to find root for: /tmp/nvimvvTR0J/5/issue_report.md
[   rooter ] [14:16:33] [ Info ] buffer name: /tmp/nvimvvTR0J/5/issue_report.md
[   rooter ] [14:16:33] [ Info ] same as current directory, no need to change.
```
</details>
