### ISSUE TITLE
SPACEVIMDIR set wrong path

### ISSUE THREAD

**Issue by yihuajack** [wsdjeg/SpaceVim#4021]
Set environment variable SPACEVIMDIR as a path such as "D:\Documents\Programming\vim"
Actual behavior: automatically create a file named "viminit.toml" after choosing basic mode or dark powered mode at startup
## Expected behavior, english is required

Expected behavior: Use `init.toml` in this path.

## Environment Information
- OS: windows
- vim version: 8.2.2224
- neovim version: -
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 6ec44b5f

## The reproduce ways from Vim starting (Required!)
Set environment variable SPACEVIMDIR as a path such as "D:\Documents\Programming\vim"
Then open Vim
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'completor'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'E:\Cadence\SPB_Data\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'E:\Cadence\SPB_Data\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(E:\Program_Files\Vim\vim82\gvim.exe)
version: 802
OS: windows
[shell, shellcmdflag, shellslash]: ['C:\WINDOWS\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:41:41] [ Info ] Startup with no argv, current dir is used: C:\Users\Yihua
[ SpaceVim ] [18:41:41] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:41:41] [ Info ] global_dir is: D:\Documents\Programming\vimhome
[ SpaceVim ] [18:41:41] [ Info ] start to apply config [glob]
[ SpaceVim ] [18:41:41] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:41:41] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:41:43] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:41:44] [ Info ] Load projects cache from: E:/Cadence/SPB_Data/.cache/SpaceVim/projects.json
[   rooter ] [18:42:43] [ Info ] Start to find root for: C:/Users/Yihua/
[   rooter ] [18:42:43] [ Info ] buffer name: No Name
[   rooter ] [18:42:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:42:43] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [18:42:45] [ Info ] close float statusline winid:1004
[   rooter ] [18:42:45] [ Info ] Start to find root for: C:/Users/Yihua/
[   rooter ] [18:42:45] [ Info ] buffer name: No Name
[   rooter ] [18:42:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:42:45] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [18:42:51] [ Info ] close float statusline winid:1006
[   rooter ] [18:42:51] [ Info ] Start to find root for: C:/Users/Yihua/AppData/Local/Temp/V1T5205.tmp/issue_report.md
[   rooter ] [18:42:51] [ Info ] buffer name: C:\Users\Yihua\AppData\Local\Temp\V1T5205.tmp\issue_report.md
[   rooter ] [18:42:51] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
