### ISSUE TITLE
Trouble installing lang#markdown -- instead get: markdown-preview.nvim: Building failed.

### ISSUE THREAD

**Issue by JBlaschke** [wsdjeg/SpaceVim#4025]
## Expected behavior, english is required
Installing `lang#markdown` results in `markdown-preview.nvim: Building failed.` I tried debugging, but I can't find any more information. The documentation also doesn't tell me where logs are saved, so that I can view a more detailed error message.

I followed all the `npm` installs here: https://spacevim.org/layers/lang/markdown/ 

## The reproduce ways from Vim starting (Required!)
`:SPReinstall markdown-preview.nvim` produces the following message:
```
[dein] /Users/johannesblaschke/.cache/vimfiles/repos/github.com/iamcco/markdown-preview.nvim
[dein] Error installing plugins:
[dein]   markdown-preview.nvim
[dein] Please read the error message log with the :message command.
[dein] Done: (2020/12/29 11:42:31)
```

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 6ec44b5f

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/johannesblaschke/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/johannesblaschke/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-bookmarks'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="github"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#julia"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#matlab"
[[layers]]
  name="tags"
[[layers]]
  name="gtags"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="tools"
[[layers]]
  name="colors"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.4/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:41:16] [ Info ] Startup with no argv, current dir is used: ~/.cache/vimfiles/repos/github.com
[ SpaceVim ] [11:41:16] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:41:16] [ Info ] global_dir is: /Users/johannesblaschke/local/my-config/spacevim/SpaceVim.d/
[ SpaceVim ] [11:41:16] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:41:17] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:41:17] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:41:17] [ Info ] try to call func of mode:whitespace
[ SpaceVim ] [11:41:17] [ Info ] no func found for mode:whitespace
[   rooter ] [11:41:17] [ Info ] Load projects cache from: /Users/johannesblaschke/.cache/SpaceVim/projects.json
[   rooter ] [11:41:17] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [11:41:17] [ Info ] Start to find root for: /Users/johannesblaschke/.cache/vimfiles/repos/github.com/
[   rooter ] [11:41:17] [ Info ]         (.SpaceVim.d/):/Users/johannesblaschke/local/my-config/spacevim/
[   rooter ] [11:41:17] [ Info ] buffer name: No Name
[   rooter ] [11:41:17] [ Info ] change to root: /Users/johannesblaschke/local/my-config/spacevim/
[ SpaceVim ] [11:41:17] [ Info ] try to open SpaceVim welcome page
[   rooter ] [11:41:17] [ Info ] buffer name: No Name
[   rooter ] [11:41:17] [ Info ] change to root: /Users/johannesblaschke/local/my-config/spacevim/
[   rooter ] [11:42:16] [ Info ] Start to find root for: /Users/johannesblaschke/local/my-config/spacevim/
[   rooter ] [11:42:16] [ Info ]         (.git/):/Users/johannesblaschke/local/my-config/
[   rooter ] [11:42:16] [ Info ]         (.SpaceVim.d/):/Users/johannesblaschke/local/my-config/spacevim/
[   rooter ] [11:42:16] [ Info ] buffer name: No Name
[   rooter ] [11:42:16] [ Info ] change to root: /Users/johannesblaschke/local/my-config/
[   rooter ] [11:53:56] [ Info ] buffer name: No Name
[   rooter ] [11:53:56] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:57] [ Info ] buffer name: No Name
[   rooter ] [11:53:57] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:53:58] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [11:54:01] [ Info ] buffer name: No Name
[   rooter ] [11:54:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:54:01] [ Info ] close float statusline winid:1006
[ SpaceVim ] [11:54:01] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [11:54:05] [ Info ] buffer name: No Name
[   rooter ] [11:54:05] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:54:05] [ Info ] close float statusline winid:1008
[   rooter ] [11:54:07] [ Info ] Start to find root for: /private/var/folders/4q/mwr1jypj1kbcb83ygyw0qwgh0000gn/T/nvimf3JJxB/2/issue_report.md
[   rooter ] [11:54:07] [ Info ] buffer name: /var/folders/4q/mwr1jypj1kbcb83ygyw0qwgh0000gn/T/nvimf3JJxB/2/issue_report.md
[   rooter ] [11:54:07] [ Info ] same as current directory, no need to change.
```
</details>
