### ISSUE TITLE
autocomplete_method = "deoplete" in SpaceVim.d/init.toml do not work

### ISSUE THREAD

**Issue by wqingzex** [wsdjeg/SpaceVim#4027]
## Expected behavior, english is required
when I set 
```
autocomplete_method = "deoplete"
```
in ~/.SpaceVim.d/init.toml and *SPUpdate*, I find that nothing happen

debug info show that:
  autocomplete_method = 'neocomplete'

## Debug info

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  automatic_update = 0
  background = 'dark'
  bootstrap_before = 'spacevim_fork#before'
  buffer_index_type = 1
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  cursorcolumn = 1
  custom_color_palette = []
  custom_plugins = [['aperezdc/vim-template', {'name': 'aperezdc/vim-template', 'merged': 0}]]
  data_dir = '/Users/wang/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['indentLine']
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = 'X>'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'I>'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 100
  plugin_bundle_dir = '/Users/wang/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-zsh'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'version control info', 'vcs', 'hunks']
  statusline_right_sections = ['major mode', 'minor mode lighters', 'fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = 'W>'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
  show_cursor_error=1
  enable=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="unite"
[[layers]]
  name="exprfold"
[[layers]]
  name="git"
  enable=1
[[layers]]
  name="github"
[[layers]]
  name="indentmove"
[[layers]]
  name="VersionControl"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
  enable=1
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#python"
  enable=1
[[layers]]
  name="lang#sh"
  enable=1
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:01:18] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [13:01:18] [ Info ] find local conf: /Users/wang/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [13:01:18] [ Info ] force loading global config >>>
[ SpaceVim ] [13:01:18] [ Info ] global_dir is: /Users/wang/.SpaceVim.d/
[ SpaceVim ] [13:01:18] [ Info ] start to apply config [glob]
[ SpaceVim ] [13:01:18] [ Error ] failed to call bootstrap_before function: spacevim_fork#before
[ SpaceVim ] [13:01:18] [ Error ]        exception: Vim(autocmd):E216: No such group or event: TermOpen * setlocal nonu
[ SpaceVim ] [13:01:18] [ Error ]        throwpoint: function SpaceVim#custom#load[30]..<SNR>44_load_glob_conf[10]..SpaceVim#custom#apply[54]..spacevim_fork#before, line 58
[ SpaceVim ] [13:01:18] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [13:01:18] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [13:01:18] [ Info ] Load projects cache from: /Users/wang/.cache/SpaceVim/projects.json
[   rooter ] [13:01:18] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [13:01:18] [ Info ] Start to find root for: /Users/wang/.SpaceVim/
[   rooter ] [13:01:18] [ Info ]         (.git/):/Users/wang/.SpaceVim/
[   rooter ] [13:01:18] [ Info ] buffer name: No Name
[   rooter ] [13:01:18] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:01:18] [ Info ] try to open SpaceVim welcome page
[   rooter ] [13:01:18] [ Info ] buffer name: No Name
[   rooter ] [13:01:18] [ Info ] same as current directory, no need to change.
```
</details>

## config
```
#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # set intent to 2
    default_indent = 2
    # disable relative line number
    relativenumber = false
    # statusline setting
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    statusline_left_sections = [
        'winnr',
        'filename',
        'version control info'
    ]
    statusline_right_sections = [
        'major mode',
        'minor mode lighters'
        'fileformat',
        'cursorpos',
        'percentage'
    ]
    enable_statusline_display_mode = false
    # buffer line, tab line
    buffer_index_type = 1
    enable_os_fileformat_icon = 1
    enable_tabline_filetype_icon = true
    # plugin manager
    #plugin_manager = 'vim-plug'
    # linter setting
    enable_neomake = false
    enable_ale = true 
    lint_on_the_fly = true
    error_symbol = 'X>'
    warning_symbol = 'W>'
    info_symbol = 'I>'
    # autocomplete method
    # autocomplete_method = "coc"
    # autocomplete_method = "ycm"
    # autocomplete_method = "neocomplcache"
    # autocomplete_method = "completor"
    # autocomplete_method = "asyncomplete"
    autocomplete_method = "deoplete"
    # snippet setting
    snippet_engine = 'ultisnips'
    # other SpaveVim setting
    automatic_update = 0
    max_column = 100
    cursorcolumn = true
    disabled_plugins = [
        'indentLine'
    ]
    # Enable vim compatible mode, avoid changing origin vim key bindings
    #vimcompatible = true
    # custom setting
    bootstrap_before = "spacevim_fork#before"

# Layers listed in SpaceVim with command: [SPC] h l
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "checkers"
  enable = true
  show_cursor_error = true

[[layers]]
  name = "debug"
  enable = false

# Enable yank/paste function
# <Leader> y  => yank to system clipboard
# <Leader> p  => paste from system clipboard
[[layers]]
  name = "default"

[[layers]]
  #name = "leaderf"
  name = "unite"
  enable = true

[[layers]]
  name = "exprfold"
  enable = true

[[layers]]
  name = "git"
  enable = true

[[layers]]
  name = "github"
  enable = true

[[layers]]
  name = "incsearch"
  enable = false

[[layers]]
  name = "indentmove"
  enable = true 

# Enable VersionControl layer
[[layers]]
  name = "VersionControl"

[[layers]]
  name = 'shell'
  # Optional Value: {"top", "bottom", "left", "right", "full"}
  default_position = 'bottom'
  default_height = 30

# Layer: tags
# Requirements:
#   - ctags
#   - python-pygments
# More details: https://spacevim.org/layers/tags/
[[layers]]
  name = "tags"
  enable = false

[[layers]]
  name = "tmux"
  enable = false

[[layers]]
  name = "tools"
  enable = false

[[layers]]
  name = "ui"
  enable = true 

#
######## Function Layers End   ########


######## Language Layers Start ########
#

[[layers]]
  name = "lang#c"
  enable = true
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "lang#dockerfile"
  enable = true 

# Layer: lang#go
# Warning: You probably need to install `go-fmt` to enable support for neoformat.
[[layers]]
  name = "lang#go"
  enable = true 

# Layer: lang#markdown
# Formatting:
# SpaceVim use remark to formatting markdown file, so you need to install this program. you can install it via npm:
#
#   `npm -g install remark`
#   `npm -g install remark-cli`
#   `npm -g install remark-stringify`
[[layers]]
  name = "lang#markdown"
  enable = false

# Layer: lang#python
# Opthons:
#   Syntax Checking: `pip install --user flake8`
#   Buffer formatting: `pip install --user yapf`
#   Format imports: `pip install --user autoflake`
#   Sort imports: `pip install --user isort`
[[layers]]
  name = "lang#python"
  enable = true

[[layers]]
  name = "lang#sh"
  enable = true

#
######## Language Layers End   ########


[[custom_plugins]]
name = 'aperezdc/vim-template'
merged = 0
```

## vim info
![image](https://user-images.githubusercontent.com/3603171/103395539-8af6a000-4b69-11eb-8149-a2de84b22076.png)

**Comment by wsdjeg** [comment]
what do you mean `do  not work`? what is the reproduce step?

**Comment by wqingzex** [comment]
it means that no matter whatever you set autocomplete_method in init.toml, it show autocomplete_method= neocomplete in SPDebugInfo. 

It's always on my mac, not the linux os, I have no sure steps to reproduce it

**Comment by axqd** [comment]
+1 same here

**Comment by glyh** [comment]
Autocomplete is deoplete by default, try remove the autocomplete_method?

Also, the deoplete used by SpaceVim is deprecated, see #4067

**Comment by wsdjeg** [comment]
`autocomplete_method = "neocomplete"` works well for me:

```toml
[options]
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
    statusline_separator='arrow'
    statusline_iseparator='arrow'
    buffer_index_type = 0
    default_indent = 4
    enable_debug = 1
    autocomplete_method = "neocomplete"
# SpaceVim layer config {{{
[[layers]]
    name = 'core'

[[layers]]
    name = 'ui'
    enable_scrollbar = true
    enable_indentline = false
    # filetree_show_hidden = true
# python 
[[layers]]
  name = 'lang#python'
  python_file_head = [      
      '# -*- coding: utf-8 -*-',
      '# Author: xxx',
      '# Mail: xxx@xx'
      '# Created Time: `strftime("%a %b %d")`'
      ''
  ]
```

with this config, restart vim, and run `:SPSet autocomplete_method`, you will see: `"neocomplete"`
