### ISSUE TITLE
rust layer lsp support not working (neovim)

### ISSUE THREAD

**Issue by pythoneer** [wsdjeg/SpaceVim#4036]
## Expected behavior, english is required
after `rustup component add rls rust-analysis rust-src` adding the following
```toml
[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]
```
would result in autocompletion. As suggested in the gitter chat, from a user with the same problem, removing lsp and install racer did however worked. 

Regardless to this are there plans to transition to rust-analyzer?

## The reproduce ways from Vim starting (Required!)
install rust
`rustup component add rls rust-analysis rust-src`
adding the lines from above. 

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 3b7c300a

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/naikon/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/naikon/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'Cargo.toml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#rust"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:40:11] [ Info ] Startup with directory: ~/Documents/dev/test/rust/spacevim_rust
[ SpaceVim ] [17:40:11] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [17:40:11] [ Info ] global_dir is: /home/naikon/.SpaceVim.d/
[ SpaceVim ] [17:40:11] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:40:11] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [17:40:11] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:40:11] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [17:40:11] [ Info ] try to open SpaceVim welcome page
[   rooter ] [17:40:11] [ Info ] Load projects cache from: /home/naikon/.cache/SpaceVim/projects.json
[   rooter ] [17:40:12] [ Info ] Start to find root for: /home/naikon/Documents/dev/test/rust/spacevim_rust/vimfiler:default
[   rooter ] [17:40:12] [ Info ]         (.git/):/home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:12] [ Info ]         (Cargo.toml):/home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:12] [ Info ] buffer name: vimfiler:default
[   rooter ] [17:40:12] [ Info ] same as current directory, no need to change.
[   rooter ] [17:40:13] [ Info ] Start to find root for: /home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:13] [ Info ]         (.git/):/home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:13] [ Info ]         (Cargo.toml):/home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:13] [ Info ] buffer name: No Name
[   rooter ] [17:40:13] [ Info ] same as current directory, no need to change.
[   rooter ] [17:40:13] [ Info ] buffer name: vimfiler:default
[   rooter ] [17:40:13] [ Info ] same as current directory, no need to change.
[   rooter ] [17:40:13] [ Info ] buffer name: No Name
[   rooter ] [17:40:13] [ Info ] same as current directory, no need to change.
[   rooter ] [17:40:13] [ Info ] Start to find root for: /home/naikon/Documents/dev/test/rust/spacevim_rust/src/main.rs
[   rooter ] [17:40:13] [ Info ]         (.git/):/home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:13] [ Info ]         (Cargo.toml):/home/naikon/Documents/dev/test/rust/spacevim_rust/
[   rooter ] [17:40:13] [ Info ] buffer name: src/main.rs
[   rooter ] [17:40:13] [ Info ] same as current directory, no need to change.
[   rooter ] [17:40:41] [ Info ] Start to find root for: /tmp/nvimVZqfJJ/2/issue_report.md
[   rooter ] [17:40:41] [ Info ] buffer name: /tmp/nvimVZqfJJ/2/issue_report.md
[   rooter ] [17:40:41] [ Info ] same as current directory, no need to change.
```
</details>
