### ISSUE TITLE
No proper typescript support for *.tsx files

### ISSUE THREAD

**Issue by 0ctothorp** [wsdjeg/SpaceVim#4037]
## Expected behavior, english is recommend

I expect linting, formatting, language specific options under <kbd>SPC l</kbd> and lsp autocomplete to work the same way as it works with the *.ts files. The only thing that works for *.tsx is the syntax highlighting. Everything else is broken. *.ts files work just fine.

## Environment Information

- OS: linux
- vim version: 8.2.1149
- neovim version: -
- SpaceVim version: 1.6.0
- SpaceVim status: d870c6a1

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

Enable the typescript layer and try to save a tsx file with some code.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/octothorp/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 80
  plugin_bundle_dir = '/home/octothorp/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'asyncomplete-necovim.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#vim"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gtk, or build from sources.
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:31:28] [ Info ] Startup with no argv, current dir is used: ~/code/my-internet-property
[ SpaceVim ] [18:31:28] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:31:28] [ Info ] global_dir is: /home/octothorp/.SpaceVim.d/
[ SpaceVim ] [18:31:28] [ Info ] start to apply config [glob]
[ SpaceVim ] [18:31:28] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [18:31:28] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:31:28] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:31:28] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [18:31:28] [ Info ] no func found for mode:syntax-checking
[ SpaceVim ] [18:31:28] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [18:31:28] [ Info ] no func found for mode:fill-column-indicator
[ SpaceVim ] [18:31:28] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:31:28] [ Info ] Load projects cache from: /home/octothorp/.cache/SpaceVim/projects.json
[   rooter ] [18:31:30] [ Info ] Start to find root for: /home/octothorp/code/my-internet-property/src/pages/index.tsx
[   rooter ] [18:31:30] [ Info ]         (.git/):/home/octothorp/code/my-internet-property/
[   rooter ] [18:31:30] [ Info ]         (package.json):/home/octothorp/code/my-internet-property/
[   rooter ] [18:31:30] [ Info ] buffer name: src/pages/index.tsx
[   rooter ] [18:31:30] [ Info ] same as current directory, no need to change.
[   rooter ] [18:31:34] [ Info ] Start to find root for: /home/octothorp/code/my-internet-property/src/pages/index.tsx
[   rooter ] [18:31:34] [ Info ]         (.git/):/home/octothorp/code/my-internet-property/
[   rooter ] [18:31:34] [ Info ]         (package.json):/home/octothorp/code/my-internet-property/
[   rooter ] [18:31:34] [ Info ] buffer name: src/pages/index.tsx
[   rooter ] [18:31:34] [ Info ] same as current directory, no need to change.
[   rooter ] [18:32:15] [ Info ] Start to find root for: /home/octothorp/code/my-internet-property/
[   rooter ] [18:32:15] [ Info ]         (.git/):/home/octothorp/code/my-internet-property/
[   rooter ] [18:32:15] [ Info ]         (package.json):/home/octothorp/code/my-internet-property/
[   rooter ] [18:32:15] [ Info ] buffer name: No Name
[   rooter ] [18:32:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:32:15] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [18:32:15] [ Info ] close float statusline winid:1004
[   rooter ] [18:32:15] [ Info ] Start to find root for: /home/octothorp/code/my-internet-property/
[   rooter ] [18:32:15] [ Info ]         (.git/):/home/octothorp/code/my-internet-property/
[   rooter ] [18:32:15] [ Info ]         (package.json):/home/octothorp/code/my-internet-property/
[   rooter ] [18:32:15] [ Info ] buffer name: No Name
[   rooter ] [18:32:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:32:15] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [18:32:44] [ Info ] close float statusline winid:1006
[   rooter ] [18:33:35] [ Info ] Start to find root for: /home/octothorp/code/my-internet-property/
[   rooter ] [18:33:35] [ Info ]         (.git/):/home/octothorp/code/my-internet-property/
[   rooter ] [18:33:35] [ Info ]         (package.json):/home/octothorp/code/my-internet-property/
[   rooter ] [18:33:35] [ Info ] buffer name: No Name
[   rooter ] [18:33:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:33:35] [ Info ] key binding guide float statusline winid:1008
[ SpaceVim ] [18:33:35] [ Info ] close float statusline winid:1008
[   rooter ] [18:33:35] [ Info ] Start to find root for: /home/octothorp/code/my-internet-property/
[   rooter ] [18:33:35] [ Info ]         (.git/):/home/octothorp/code/my-internet-property/
[   rooter ] [18:33:35] [ Info ]         (package.json):/home/octothorp/code/my-internet-property/
[   rooter ] [18:33:35] [ Info ] buffer name: No Name
[   rooter ] [18:33:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:33:35] [ Info ] key binding guide float statusline winid:1010
[ SpaceVim ] [18:33:35] [ Info ] close float statusline winid:1010
[   rooter ] [18:33:38] [ Info ] Start to find root for: /tmp/vnZRTrR/2/issue_report.md
[   rooter ] [18:33:38] [ Info ] buffer name: /tmp/vnZRTrR/2/issue_report.md
[   rooter ] [18:33:38] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

Linting and formatting not working on save:
![spacevim3](https://user-images.githubusercontent.com/5238816/103443511-4ef23680-4c60-11eb-971c-0bc46dded649.png)
I managed to make formatting work with prettier by using some duct tape in the autoload vim script:
```vim
  let g:neoformat_typescriptreact_prettier = {
    \ 'exe': 'prettier',
    \ 'args': ['--stdin', '--stdin-filepath', '"%:p"', '--parser', 'typescript'],
    \ 'stdin': 1
    \ }
  let g:neoformat_enabled_typescriptreact = ['prettier']
```
No luck with eslint though.

No language options when hitting <kbd>SPC l</kbd>:
![spacevim2](https://user-images.githubusercontent.com/5238816/103443499-24a07900-4c60-11eb-9120-031c325753d7.png)
