### ISSUE TITLE
<leader> y not defined despite layer = 'default' enabled in init.toml

### ISSUE THREAD

**Issue by mkurop** [wsdjeg/SpaceVim#4049]
## Describe the behavior that you expect from SpaceVim
After pressing <kbd>leader y</kbd> in normal mode I would expect yanking the text under cursor into system clipboard, but I get a message ```key binding is not defined```

If possible, in addition to the description, please also provide a link to the relevant SpaceVim documentation that describes the expected behaviour/feature.
Here is place in the spacevim docu which mentions the expected behaviour: https://spacevim.org/layers/default/
## Describe the problem
The problem is I can't yank the text into system clipboard.

Please describe the observed problem in simple and clear terms.

## Describe steps to reproduce the problem
After pressing <kbd>\ y</kbd> in normal mode I get info that the key binding is not defined.

Please list all the steps from the point the Vim session was started until the problem was observed, in simple and clear terms.
* start vim
* press <kbd>\ y</kbd>
* observe message
## Environment Information

- OS: linux
- vim version: 8.1.2269
- neovim version: -
- SpaceVim version: 1.6.0-dev
- SpaceVim status: 3d525cb8

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['lilydjwg/colorizer', {'repo': 'lilydjwg/colorizer', 'merged': 0}], ['roxma/nvim-yarp', {'repo': 'roxma/nvim-yarp', 'merged': 0}], ['roxma/vim-hug-neovim-rpc', {'repo': 'roxma/vim-hug-neovim-rpc', 'merged': 0}]]
  data_dir = '/home/marcin/.cache/'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SourceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/home/marcin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dispatch'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'test', 'vcs', 'hunks']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time', 'test']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highliht=1
[[layers]]
  name="gtags"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="debug"
[[layers]]
  name="tmux"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/bin/vim)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:09:58] [ Info ] Startup with no argv, current dir is used: ~/src/pybind11-cuda
[ SpaceVim ] [13:09:58] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [13:09:58] [ Info ] global_dir is: /home/marcin/.SpaceVim.d/
[ SpaceVim ] [13:09:58] [ Info ] start to apply config [glob]
[   rooter ] [13:09:58] [ Info ] Load projects cache from: /home/marcin/.cache/SpaceVim/projects.json
[   rooter ] [13:09:58] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [13:09:58] [ Info ] Start to find root for: /home/marcin/src/pybind11-cuda/
[   rooter ] [13:09:58] [ Info ]         (.git/):/home/marcin/src/pybind11-cuda/
[   rooter ] [13:09:58] [ Info ] buffer name: No Name
[   rooter ] [13:09:58] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:09:58] [ Info ] try to open SpaceVim welcome page
[   rooter ] [13:09:58] [ Info ] buffer name: No Name
[   rooter ] [13:09:58] [ Info ] same as current directory, no need to change.
[   rooter ] [13:10:00] [ Info ] Start to find root for: /home/marcin/src/pybind11-cuda/CMakeLists.txt
[   rooter ] [13:10:00] [ Info ]         (.git/):/home/marcin/src/pybind11-cuda/
[   rooter ] [13:10:00] [ Info ] buffer name: /home/marcin/src/pybind11-cuda/CMakeLists.txt
[   rooter ] [13:10:00] [ Info ] same as current directory, no need to change.
[   rooter ] [13:10:02] [ Info ] Start to find root for: /home/marcin/src/pybind11-cuda/
[   rooter ] [13:10:02] [ Info ]         (.git/):/home/marcin/src/pybind11-cuda/
[   rooter ] [13:10:02] [ Info ] buffer name: No Name
[   rooter ] [13:10:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:10:02] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [13:10:02] [ Info ] close float statusline winid:1004
[   rooter ] [13:17:25] [ Info ] Start to find root for: /tmp/vIhzia6/7/issue_report.md
[   rooter ] [13:17:25] [ Info ] buffer name: /tmp/vIhzia6/7/issue_report.md
[   rooter ] [13:17:25] [ Info ] same as current directory, no need to change.
[   rooter ] [13:17:32] [ Info ] Start to find root for: /tmp/vIhzia6/7/issue_report.md
[   rooter ] [13:17:32] [ Info ] buffer name: /tmp/vIhzia6/7/issue_report.md
[   rooter ] [13:17:32] [ Info ] same as current directory, no need to change.
[   rooter ] [13:17:33] [ Info ] buffer name: /tmp/vIhzia6/7/issue_report.md
[   rooter ] [13:17:33] [ Info ] same as current directory, no need to change.
[   rooter ] [13:17:33] [ Info ] Start to find root for: /tmp/vIhzia6/12/issue_report.md
[   rooter ] [13:17:33] [ Info ] buffer name: /tmp/vIhzia6/12/issue_report.md
[   rooter ] [13:17:33] [ Info ] same as current directory, no need to change.
```
</details>

## If needed, provide Screenshots and/or Video captures

Ideally, please use asciinema for video captures. See https://asciinema.org/.
