### ISSUE TITLE
NeoSolarized palette not working in leaderGuide in MacVim

### ISSUE THREAD

**Issue by Gigitsu** [wsdjeg/SpaceVim#4053]
## Expected behavior, english is recommend
The colors for the leaderGuide should be displayed correctly

## Environment Information

- OS: mac
- vim version: 8.2.2164
- neovim version: -
- SpaceVim version: 1.6.0
- SpaceVim status: d870c6a1

```
HEAD detached at d870c6a1
nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Just open the leaderGuide

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'NeoSolarized'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['roxma/nvim-yarp', {'name': 'roxma/nvim-yarp', 'merged': 0}], ['roxma/vim-hug-neovim-rpc', {'name': 'roxma/vim-hug-neovim-rpc', 'merged': 0}], ['tpope/vim-dadbod', {'name': 'tpope/vim-dadbod', 'merged': 0}]]
  data_dir = '~/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '~/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dispatch'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'slant'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'version control info', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'major mode', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#elixir"
[[layers]]
  name="fuzzy"
[[layers]]
  name="ctrlp"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
  git-plugin='fugitive'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/usr/local/Cellar/macvim/8.2-169_2/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:06:39] [ Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [10:06:39] [ Info ] find local conf: ~/Developer/src/github.com/gigitsu/dotfiles/SpaceVim.d/init.toml
[ SpaceVim ] [10:06:39] [ Info ] loading cached local conf: ~/.cache//SpaceVim/conf/_Users_gigitsu_Developer_src_github_com_gigitsu_dotfiles_SpaceVim_d_init_toml.json
[ SpaceVim ] [10:06:39] [ Info ] start to apply config [local]
[ SpaceVim ] [10:06:39] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [10:06:39] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [10:06:39] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [10:06:39] [ Info ] try to open SpaceVim welcome page
[   rooter ] [10:06:40] [ Info ] Load projects cache from: ~/.cache/SpaceVim/projects.json
[   rooter ] [10:06:43] [ Info ] Start to find root for: ~/
[   rooter ] [10:06:43] [ Info ]         (.SpaceVim.d/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:43] [ Info ] buffer name: No Name
[   rooter ] [10:06:43] [ Info ] change to root: ~/Developer/src/github.com/gigitsu/dotfiles/
[ SpaceVim ] [10:06:43] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [10:06:43] [ Info ] close float statusline winid:1004
[   rooter ] [10:06:43] [ Info ] Start to find root for: ~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:43] [ Info ]         (.git/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:43] [ Info ]         (.SpaceVim.d/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:43] [ Info ] buffer name: No Name
[   rooter ] [10:06:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:06:43] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [10:06:43] [ Info ] close float statusline winid:1006
[   rooter ] [10:06:43] [ Info ] Start to find root for: ~/Developer/src/github.com/gigitsu/dotfiles/SpaceVimLayers
[   rooter ] [10:06:43] [ Info ]         (.git/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:43] [ Info ]         (.SpaceVim.d/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:43] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [10:06:43] [ Info ] same as current directory, no need to change.
[   rooter ] [10:06:48] [ Info ] Start to find root for: ~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:48] [ Info ]         (.git/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:48] [ Info ]         (.SpaceVim.d/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:06:48] [ Info ] buffer name: No Name
[   rooter ] [10:06:48] [ Info ] same as current directory, no need to change.
[   rooter ] [10:07:02] [ Info ] Start to find root for: ~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:07:02] [ Info ]         (.git/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:07:02] [ Info ]         (.SpaceVim.d/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:07:02] [ Info ] buffer name: No Name
[   rooter ] [10:07:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:07:02] [ Info ] key binding guide float statusline winid:1010
[ SpaceVim ] [10:07:02] [ Info ] close float statusline winid:1010
[   rooter ] [10:07:02] [ Info ] Start to find root for: ~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:07:02] [ Info ]         (.git/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:07:02] [ Info ]         (.SpaceVim.d/):~/Developer/src/github.com/gigitsu/dotfiles/
[   rooter ] [10:07:02] [ Info ] buffer name: No Name
[   rooter ] [10:07:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:07:02] [ Info ] key binding guide float statusline winid:1012
[ SpaceVim ] [10:07:08] [ Info ] close float statusline winid:1012
[   rooter ] [10:07:08] [ Info ] Start to find root for: /private/var/folders/0g/6xx12fwj0rq95psvlvrb2k7w0000gn/T/v8E8dNG/2/issue_report.md
[   rooter ] [10:07:08] [ Info ] buffer name: /var/folders/0g/6xx12fwj0rq95psvlvrb2k7w0000gn/T/v8E8dNG/2/issue_report.md
[   rooter ] [10:07:08] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![Screenshot 2021-01-14 at 10 06 01](https://user-images.githubusercontent.com/3147882/104568272-2d298400-5650-11eb-97c8-566b2b107eea.png)
