### ISSUE TITLE
ERROR [coc.nvim]: Some plugin change completeopt on insert mode

### ISSUE THREAD

**Issue by ogfunkycold** [wsdjeg/SpaceVim#4056]
## Expected behavior, english is required
After a fresh new install, at the first try in insert mode after typing any letter I've got :

[coc.nvim]: Some plugin change completeopt on insert mode: Last set from ~/.SpaceVim/bundle/deoplete.nvim/autoload/deoplete/mapping.vim line 77!

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.5.0
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 5b7607a1

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	pack/

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/orly/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/orly/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [21:12:34] [ Info ] Startup with argv: ['a.txt']
[ SpaceVim ] [21:12:34] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [21:12:34] [ Info ] global_dir is: /home/orly/.SpaceVim.d/
[ SpaceVim ] [21:12:34] [ Info ] start to apply config [glob]
[ SpaceVim ] [21:12:34] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [21:12:34] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [21:12:34] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [21:12:34] [ Info ] Load projects cache from: /home/orly/.cache/SpaceVim/projects.json
[   rooter ] [21:13:00] [ Info ] Start to find root for: /home/orly/tmp/vimfiler:default@2
[   rooter ] [21:13:00] [ Info ] buffer name: vimfiler:default@2
[   rooter ] [21:13:00] [ Info ] same as current directory, no need to change.
[   rooter ] [21:13:17] [ Info ] Start to find root for: /home/orly/tmp/a.txt
[   rooter ] [21:13:17] [ Info ] buffer name: a.txt
[   rooter ] [21:13:17] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:19] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [21:20:19] [ Info ] buffer name: a.txt
[   rooter ] [21:20:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:19] [ Info ] close float statusline winid:1004
[ SpaceVim ] [21:20:19] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [21:20:19] [ Info ] buffer name: a.txt
[   rooter ] [21:20:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:19] [ Info ] close float statusline winid:1006
[ SpaceVim ] [21:20:25] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [21:20:25] [ Info ] buffer name: a.txt
[   rooter ] [21:20:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:25] [ Info ] close float statusline winid:1008
[ SpaceVim ] [21:20:25] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [21:20:35] [ Info ] buffer name: a.txt
[   rooter ] [21:20:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:35] [ Info ] close float statusline winid:1010
[   rooter ] [21:20:35] [ Info ] Start to find root for: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] same as current directory, no need to change.
[   rooter ] [21:20:35] [ Info ] Start to find root for: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] same as current directory, no need to change.
[   rooter ] [21:20:37] [ Info ] Start to find root for: /home/orly/tmp/
[   rooter ] [21:20:37] [ Info ] buffer name: No Name
[   rooter ] [21:20:37] [ Info ] same as current directory, no need to change.
[   rooter ] [21:20:37] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:37] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:21:43] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [21:21:54] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:21:54] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:21:54] [ Info ] close float statusline winid:1014
[ SpaceVim ] [21:21:54] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [21:22:01] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:22:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:22:01] [ Info ] close float statusline winid:1016
[   rooter ] [21:22:01] [ Info ] Start to find root for: /tmp/nvimjlJUVS/4/issue_report.md
[   rooter ] [21:22:01] [ Info ] buffer name: /tmp/nvimjlJUVS/4/issue_report.md
[   rooter ] [21:22:01] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
asciinema recording

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.5.0
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 5b7607a1

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	pack/

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/orly/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/orly/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [21:12:34] [ Info ] Startup with argv: ['a.txt']
[ SpaceVim ] [21:12:34] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [21:12:34] [ Info ] global_dir is: /home/orly/.SpaceVim.d/
[ SpaceVim ] [21:12:34] [ Info ] start to apply config [glob]
[ SpaceVim ] [21:12:34] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [21:12:34] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [21:12:34] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [21:12:34] [ Info ] Load projects cache from: /home/orly/.cache/SpaceVim/projects.json
[   rooter ] [21:13:00] [ Info ] Start to find root for: /home/orly/tmp/vimfiler:default@2
[   rooter ] [21:13:00] [ Info ] buffer name: vimfiler:default@2
[   rooter ] [21:13:00] [ Info ] same as current directory, no need to change.
[   rooter ] [21:13:17] [ Info ] Start to find root for: /home/orly/tmp/a.txt
[   rooter ] [21:13:17] [ Info ] buffer name: a.txt
[   rooter ] [21:13:17] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:19] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [21:20:19] [ Info ] buffer name: a.txt
[   rooter ] [21:20:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:19] [ Info ] close float statusline winid:1004
[ SpaceVim ] [21:20:19] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [21:20:19] [ Info ] buffer name: a.txt
[   rooter ] [21:20:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:19] [ Info ] close float statusline winid:1006
[ SpaceVim ] [21:20:25] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [21:20:25] [ Info ] buffer name: a.txt
[   rooter ] [21:20:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:25] [ Info ] close float statusline winid:1008
[ SpaceVim ] [21:20:25] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [21:20:35] [ Info ] buffer name: a.txt
[   rooter ] [21:20:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:20:35] [ Info ] close float statusline winid:1010
[   rooter ] [21:20:35] [ Info ] Start to find root for: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] same as current directory, no need to change.
[   rooter ] [21:20:35] [ Info ] Start to find root for: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:35] [ Info ] same as current directory, no need to change.
[   rooter ] [21:20:37] [ Info ] Start to find root for: /home/orly/tmp/
[   rooter ] [21:20:37] [ Info ] buffer name: No Name
[   rooter ] [21:20:37] [ Info ] same as current directory, no need to change.
[   rooter ] [21:20:37] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:20:37] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:21:43] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [21:21:54] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:21:54] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:21:54] [ Info ] close float statusline winid:1014
[ SpaceVim ] [21:21:54] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [21:22:01] [ Info ] buffer name: /tmp/nvimjlJUVS/2/issue_report.md
[   rooter ] [21:22:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [21:22:01] [ Info ] close float statusline winid:1016
[   rooter ] [21:22:01] [ Info ] Start to find root for: /tmp/nvimjlJUVS/4/issue_report.md
[   rooter ] [21:22:01] [ Info ] buffer name: /tmp/nvimjlJUVS/4/issue_report.md
[   rooter ] [21:22:01] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
