### ISSUE TITLE
KeyError: 'time' with completion plugin deoplete on neovim

### ISSUE THREAD

**Issue by glyh** [wsdjeg/SpaceVim#4067]
## Expected behavior, english is required
   Completion plugin works fine. 
## The reproduce ways from Vim starting (Required!)
  Just run `nvim`, turn to input mode, the bug occurs itself
## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/anonymous/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/anonymous/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
  enable=1
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:48:20] [ Info ] Startup with no argv, current dir is used: ~/CS/projects/experiments/sicp-solutions-clojure
[ SpaceVim ] [14:48:20] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [14:48:20] [ Info ] global_dir is: /home/anonymous/.SpaceVim.d/
[ SpaceVim ] [14:48:20] [ Info ] start to apply config [glob]
[ SpaceVim ] [14:48:20] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [14:48:20] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [14:48:20] [ Info ] try to open SpaceVim welcome page
[   rooter ] [14:48:20] [ Info ] Load projects cache from: /home/anonymous/.cache/SpaceVim/projects.json
[   rooter ] [14:48:55] [ Info ] Start to find root for: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [14:48:55] [ Info ]         (.git/):/home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [14:48:55] [ Info ] buffer name: No Name
[   rooter ] [14:48:55] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:37] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [14:53:37] [ Info ] buffer name: No Name
[   rooter ] [14:53:37] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:37] [ Info ] close float statusline winid:1004
[ SpaceVim ] [14:53:37] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [14:53:37] [ Info ] buffer name: No Name
[   rooter ] [14:53:37] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:37] [ Info ] close float statusline winid:1006
[ SpaceVim ] [14:53:38] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [14:53:38] [ Info ] buffer name: No Name
[   rooter ] [14:53:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:38] [ Info ] close float statusline winid:1008
[ SpaceVim ] [14:53:38] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [14:53:38] [ Info ] buffer name: No Name
[   rooter ] [14:53:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:38] [ Info ] close float statusline winid:1010
[ SpaceVim ] [14:53:39] [ Info ] key binding guide float statusline winid:1012
[   rooter ] [14:53:39] [ Info ] buffer name: No Name
[   rooter ] [14:53:39] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:39] [ Info ] close float statusline winid:1012
[ SpaceVim ] [14:53:39] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [14:53:39] [ Info ] buffer name: No Name
[   rooter ] [14:53:39] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:39] [ Info ] close float statusline winid:1014
[ SpaceVim ] [14:53:41] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [14:53:41] [ Info ] buffer name: No Name
[   rooter ] [14:53:41] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:41] [ Info ] close float statusline winid:1016
[ SpaceVim ] [14:53:41] [ Info ] key binding guide float statusline winid:1018
[   rooter ] [14:53:41] [ Info ] buffer name: No Name
[   rooter ] [14:53:41] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:41] [ Info ] close float statusline winid:1018
[ SpaceVim ] [14:53:43] [ Info ] key binding guide float statusline winid:1020
[   rooter ] [14:53:43] [ Info ] buffer name: No Name
[   rooter ] [14:53:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:43] [ Info ] close float statusline winid:1020
[ SpaceVim ] [14:53:43] [ Info ] key binding guide float statusline winid:1022
[   rooter ] [14:53:43] [ Info ] buffer name: No Name
[   rooter ] [14:53:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:43] [ Info ] close float statusline winid:1022
[ SpaceVim ] [14:53:48] [ Info ] key binding guide float statusline winid:1024
[   rooter ] [14:53:48] [ Info ] buffer name: No Name
[   rooter ] [14:53:48] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:48] [ Info ] close float statusline winid:1024
[ SpaceVim ] [14:53:54] [ Info ] key binding guide float statusline winid:1026
[   rooter ] [14:53:54] [ Info ] buffer name: No Name
[   rooter ] [14:53:54] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:54] [ Info ] close float statusline winid:1026
[ SpaceVim ] [14:53:56] [ Info ] key binding guide float statusline winid:1028
[   rooter ] [14:53:56] [ Info ] buffer name: No Name
[   rooter ] [14:53:56] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:56] [ Info ] close float statusline winid:1028
[ SpaceVim ] [14:53:58] [ Info ] key binding guide float statusline winid:1030
[   rooter ] [14:53:58] [ Info ] buffer name: No Name
[   rooter ] [14:53:58] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:53:58] [ Info ] close float statusline winid:1030
[   rooter ] [14:54:05] [ Info ] Start to find root for: /tmp/nvimQgt4EH/1/issue_report.md
[   rooter ] [14:54:05] [ Info ] buffer name: /tmp/nvimQgt4EH/1/issue_report.md
[   rooter ] [14:54:05] [ Info ] same as current directory, no need to change.
[   rooter ] [14:54:05] [ Info ] Start to find root for: /tmp/nvimQgt4EH/1/issue_report.md
[   rooter ] [14:54:05] [ Info ] buffer name: /tmp/nvimQgt4EH/1/issue_report.md
[   rooter ] [14:54:05] [ Info ] same as current directory, no need to change.
[   rooter ] [14:55:04] [ Info ] Start to find root for: /tmp/nvimQgt4EH/3/issue_report.md
[   rooter ] [14:55:04] [ Info ] buffer name: /tmp/nvimQgt4EH/3/issue_report.md
[   rooter ] [14:55:04] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![Screenshot_20210202_145830](https://user-images.githubusercontent.com/12870742/106563818-4fcffe00-6567-11eb-850a-56d0865375b7.png)

## Further information

I've been using neovim, and I'm starting up SpaceVim with `nvim`.

This bug doesn't occur when I try it with `vim`. 

In my previous nvim configuration file, there is the pulgin deoplete.nvim installed on my nvim and works fine.
