### ISSUE TITLE
Escape key in leaderf not working

### ISSUE THREAD

**Issue by glyh** [wsdjeg/SpaceVim#4071]
## Expected behavior, english is recommend

Leaderf can be closed using Esc or Ctrl+g.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 6ce4e0e6�

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    bundle/deoplete.nvim/.travis.yml
	modified:   bundle/deoplete.nvim/README.md
	modified:   bundle/deoplete.nvim/autoload/deoplete.vim
	modified:   bundle/deoplete.nvim/autoload/deoplete/custom.vim
	modified:   bundle/deoplete.nvim/autoload/deoplete/handler.vim
	modified:   bundle/deoplete.nvim/autoload/deoplete/init.vim
	modified:   bundle/deoplete.nvim/autoload/deoplete/mapping.vim
	modified:   bundle/deoplete.nvim/autoload/deoplete/util.vim
	modified:   bundle/deoplete.nvim/autoload/health/deoplete.vim
	modified:   bundle/deoplete.nvim/doc/deoplete.txt
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/base/filter.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/base/source.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/child.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/context.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/base.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_auto_delimiter.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_auto_paren.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_case.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_remove_overlap.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_remove_paren.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_reorder_attr.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_abbr.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_info.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_kind.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_menu.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_cpsm.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_full_fuzzy.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_fuzzy.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_head.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_length.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/sorter_rank.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/filter/sorter_word.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/logger.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/parent.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/source/around.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/source/base.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/source/file.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/source/member.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/source/omni.py
	modified:   bundle/deoplete.nvim/rplugin/python3/deoplete/util.py
	modified:   bundle/deoplete.nvim/test/conftest.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	bundle/deoplete.nvim/.github/workflows/
	bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_word_abbr.py
	bundle/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_matchfuzzy.py

no changes added to commit (use "git add" and/or "git commit -a")
```

## The reproduce ways from Vim starting (Required!)

Open some code, open Leaderf, let's say search function definitons using Space+i+j.

Then press Esc (or Ctrl+g).

Nothing happens, but `:q` works.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'boot#after'
  bootstrap_before = 'boot#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/anonymous/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/anonymous/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-fireplace'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', 'project.clj']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  enable=1
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="git"
[[layers]]
  name="leaderf"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#clojure"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:06:00] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim.d
[ SpaceVim ] [10:06:00] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [10:06:00] [ Info ] global_dir is: /home/anonymous/.SpaceVim.d/
[ SpaceVim ] [10:06:00] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:06:00] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [10:06:00] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [10:06:00] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [10:06:00] [ Info ] no func found for mode:fill-column-indicator
[   rooter ] [10:06:00] [ Info ] Load projects cache from: /home/anonymous/.cache/SpaceVim/projects.json
[   rooter ] [10:06:00] [ Info ] Start to find root for: /home/anonymous/.SpaceVim.d/
[   rooter ] [10:06:00] [ Info ]         (.git/):/home/anonymous/.SpaceVim.d/
[   rooter ] [10:06:00] [ Info ] buffer name: No Name
[   rooter ] [10:06:00] [ Info ] same as current directory, no need to change.
[   rooter ] [10:06:01] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [10:06:01] [ Info ] Start to find root for: /home/anonymous/.SpaceVim.d/
[   rooter ] [10:06:01] [ Info ]         (.git/):/home/anonymous/.SpaceVim.d/
[   rooter ] [10:06:01] [ Info ] buffer name: No Name
[   rooter ] [10:06:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:06:01] [ Info ] try to open SpaceVim welcome page
[   rooter ] [10:06:01] [ Info ] buffer name: No Name
[   rooter ] [10:06:01] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:06:03] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [10:06:03] [ Info ] buffer name: No Name
[   rooter ] [10:06:03] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:06:03] [ Info ] close float statusline winid:1004
[   rooter ] [10:06:07] [ Info ] Start to find root for: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/src/sicp_solutions_clojure/core.clj
[   rooter ] [10:06:07] [ Info ]         (.git/):/home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [10:06:07] [ Info ]         (project.clj):/home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [10:06:07] [ Info ] buffer name: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/src/sicp_solutions_clojure/core.clj
[   rooter ] [10:06:07] [ Info ] change to root: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [10:06:14] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:06:14] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:11] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [10:15:11] [ Info ] buffer name: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:11] [ Info ] change to root: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[ SpaceVim ] [10:15:11] [ Info ] close float statusline winid:1007
[ SpaceVim ] [10:15:11] [ Info ] key binding guide float statusline winid:1009
[   rooter ] [10:15:13] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:13] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:13] [ Info ] close float statusline winid:1009
[ SpaceVim ] [10:15:20] [ Info ] key binding guide float statusline winid:1012
[   rooter ] [10:15:20] [ Info ] Start to find root for: /usr/share/nvim/runtime/Function/LeaderF
[   rooter ] [10:15:20] [ Info ] buffer name: /usr/share/nvim/runtime/Function/LeaderF
[   rooter ] [10:15:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:20] [ Info ] close float statusline winid:1012
[   rooter ] [10:15:22] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:22] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:24] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [10:15:25] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:25] [ Info ] close float statusline winid:1014
[ SpaceVim ] [10:15:28] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [10:15:28] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:28] [ Info ] close float statusline winid:1016
[ SpaceVim ] [10:15:31] [ Info ] key binding guide float statusline winid:1018
[   rooter ] [10:15:31] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:31] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:31] [ Info ] close float statusline winid:1018
[ SpaceVim ] [10:15:38] [ Info ] key binding guide float statusline winid:1020
[   rooter ] [10:15:38] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:15:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [10:15:38] [ Info ] close float statusline winid:1020
[   rooter ] [10:19:16] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:19:16] [ Info ] same as current directory, no need to change.
[   rooter ] [10:19:31] [ Info ] buffer name: src/sicp_solutions_clojure/core.clj
[   rooter ] [10:19:31] [ Info ] same as current directory, no need to change.
[   rooter ] [10:19:35] [ Info ] Start to find root for: /home/anonymous/CS/projects/experiments/sicp-solutions-clojure/SpaceVimLayers
[   rooter ] [10:19:35] [ Info ]         (.git/):/home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [10:19:35] [ Info ]         (project.clj):/home/anonymous/CS/projects/experiments/sicp-solutions-clojure/
[   rooter ] [10:19:35] [ Info ] buffer name: SpaceVimLayers
[   rooter ] [10:19:35] [ Info ] same as current directory, no need to change.
[   rooter ] [10:20:01] [ Info ] Start to find root for: /tmp/nvimDv8FNS/5/issue_report.md
[   rooter ] [10:20:01] [ Info ] buffer name: /tmp/nvimDv8FNS/5/issue_report.md
[   rooter ] [10:20:01] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![Screenshot_20210204_102315](https://user-images.githubusercontent.com/12870742/106835927-29c76c80-66d3-11eb-9a09-633938c3a20a.png)
