### ISSUE TITLE
Go auto-completion is configured

### ISSUE THREAD

**Issue by 0x1306a94** [wsdjeg/SpaceVim#4072]
## The reproduce ways from Vim starting (Required!)

Go auto-completion is configured
After pressing the tab key to complete, `<0>` will be inserted at the end

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: mac
- vim version: 8.2.850
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 6ce4e0e6

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'completor'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/king/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'FiraCode-Retina:h14'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/king/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-go'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  snippet_engine='ultisnips'
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
  autocomplete_method='deoplete'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#go"
[[layers]]
  name="shell"
  default_height=30
  default_position='top'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(vi)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gtk, or build from sources.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:40:36] [ Info ] Startup with directory: ~/WorkSpace/go/src/
[ SpaceVim ] [15:40:36] [ Info ] find local conf: /Users/king/.SpaceVim.d/init.toml
[ SpaceVim ] [15:40:36] [ Info ] loading cached local conf: /Users/king/.cache//SpaceVim/conf/_Users_king__SpaceVim_d_init_toml.json
[ SpaceVim ] [15:40:36] [ Info ] start to apply config [local]
[ SpaceVim ] [15:40:36] [ Warn ] defx requires +python3!
[ SpaceVim ] [15:40:36] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:40:36] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:40:36] [ Info ] try to open SpaceVim welcome page
[   rooter ] [15:40:37] [ Info ] Load projects cache from: /Users/king/.cache/SpaceVim/projects.json
[   rooter ] [15:41:26] [ Info ] Start to find root for: /Users/king/WorkSpace/go/src/
[   rooter ] [15:41:26] [ Info ] buffer name: No Name
[   rooter ] [15:41:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:41:26] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [15:41:26] [ Info ] close float statusline winid:1004
[   rooter ] [15:41:26] [ Info ] Start to find root for: /Users/king/WorkSpace/go/src/
[   rooter ] [15:41:26] [ Info ] buffer name: No Name
[   rooter ] [15:41:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:41:26] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [15:41:27] [ Info ] close float statusline winid:1006
[   rooter ] [15:41:27] [ Info ] Start to find root for: /private/var/folders/9k/dncvmxxj4qv7q1hyjrx47xtm0000gp/T/visNf4i/2/issue_report.md
[   rooter ] [15:41:27] [ Info ] buffer name: /var/folders/9k/dncvmxxj4qv7q1hyjrx47xtm0000gp/T/visNf4i/2/issue_report.md
[   rooter ] [15:41:27] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gnbghcv6rdj314t0u0mzt.jpg)
