### ISSUE TITLE
Bootstrap functions silently ignore errors

### ISSUE THREAD

**Issue by MrQubo** [wsdjeg/SpaceVim#4079]
## Expected behavior, english is recommend

- SpaceVim informs about the error in bootstrap function. E.g. by displaying "E492: Not an editor command: foobar".

## Environment Information

- OS: linux
- vim version: 8.2.2380
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: cbb5610a

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting

- Add `foobar` to bootstrap_after or bootstrap_before function.
- Open vim.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'none'
  autocomplete_parens = 0
  automatic_update = 1
  background = 'dark'
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 1
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['let-def/vimbufsync', {'name': 'let-def/vimbufsync'}], ['whonore/Coqtail', {'depends': ['let-def/vimbufsync'], 'name': 'whonore/Coqtail'}], ['junegunn/vim-easy-align', {'name': 'junegunn/vim-easy-align'}], ['blindFS/vim-taskwarrior', {'name': 'blindFS/vim-taskwarrior'}], ['vim-latex/vim-latex', {'name': 'vim-latex/vim-latex'}], ['ryanoasis/vim-devicons', {'lazy': 1, 'depends': ['Shougo/vimfiler.vim', 'Shougo/unite.vim', 'Shougo/denite.nvim', 'powerline/powerline', 'vim-airline/vim-airline', 'scrooloose/nerdtree'], 'name': 'ryanoasis/vim-devicons'}], ['tweekmonster/exception.vim', {'name': 'tweekmonster/exception.vim'}]]
  data_dir = '/home/arch/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['java_getset.vim', 'javacomplete', 'vim-javacomplete', 'vim-javacomplete2']
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_display_mode = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 0
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/arch/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-zsh'
  project_rooter_automatically = 0
  project_rooter_outermost = 1
  project_rooter_patterns = []
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 45
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 0
  windows_leader = 's'
  windows_smartclose = 'sx'
```

### SpaceVim layers :

```toml
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="gtags"
[[layers]]
  name="sudo"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="lsp"
  filetypes=['c', 'cpp', 'css', 'dockerfile', 'html', 'javascript', 'python', 'rust', 'sh', 'typescript', 'vue']
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:00:17] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [09:00:17] [ Info ] find local conf: /home/arch/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [09:00:17] [ Info ] force loading global config >>>
[ SpaceVim ] [09:00:17] [ Info ] global_dir is: /home/arch/.SpaceVim/SpaceVim.d/
[ SpaceVim ] [09:00:17] [ Info ] start to apply config [glob]
[ SpaceVim ] [09:00:17] [ Warn ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [09:00:17] [ Warn ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [09:00:17] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:00:17] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [09:00:17] [ Info ] Load projects cache from: /home/arch/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:00:18] [ Info ] try to open SpaceVim welcome page
[ SpaceVim ] [09:00:19] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [09:00:19] [ Info ] close float statusline winid:1004
[ SpaceVim ] [09:00:19] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [09:00:21] [ Info ] close float statusline winid:1006
[ SpaceVim ] [09:00:24] [ Info ] key binding guide float statusline winid:1008
[ SpaceVim ] [09:00:25] [ Info ] close float statusline winid:1008
[ SpaceVim ] [09:00:25] [ Info ] key binding guide float statusline winid:1010
[ SpaceVim ] [09:00:26] [ Info ] close float statusline winid:1010
[ SpaceVim ] [09:00:27] [ Info ] key binding guide float statusline winid:1012
[ SpaceVim ] [09:00:27] [ Info ] close float statusline winid:1012
[ SpaceVim ] [09:00:27] [ Info ] key binding guide float statusline winid:1014
[ SpaceVim ] [09:00:28] [ Info ] close float statusline winid:1014
```
</details>
