### ISSUE TITLE
The `<SPC> h <SPC>` command fails to find SpaceVim documentation for me.

### ISSUE THREAD

**Issue by ilyagr** [wsdjeg/SpaceVim#4081]
The `<SPC> h <SPC>` command fails to find SpaceVim documentation for me.

1. It always opens with a useless screen that has `SpaceVim` in the search bar and no results. It looks like this:

```
> SpaceVim
  0/12750
```

2. If I delete the "SpaceVim" from the prompt, I can search through Vim's built-in help and the help for the plugins SpaceVim installed. The SpaceVim documentation itself isn't there, however. (So, no documentation for various layers, for instance)

3. This is a bit unrelated and minor, but trying to get documentation on this command via  `<SPC> h d k` followed by `<SPC> h <SPC>` tells me that `SPC - h - SPC is undefined`.

## Expected behavior, english is recommend
I should be able to search SpaceVim documentation after pressing the key combination.

## Environment Information

- OS: linux
- vim version: 8.1(1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401)
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 14392bd9

```
On branch master
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

1. Start Vim in a terminal (not sure if it matters; I don't have gvim installed).
2. Press `<SPC> h <SPC>`.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/ilyagr/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/ilyagr/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-gitgutter'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="git"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:37:08] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [13:37:08] [ Info ] find local conf: /home/ilyagr/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [13:37:08] [ Info ] force loading global config >>>
[ SpaceVim ] [13:37:08] [ Info ] global_dir is: /home/ilyagr/.SpaceVim.d/
[ SpaceVim ] [13:37:08] [ Info ] start to apply config [glob]
[ SpaceVim ] [13:37:08] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [13:37:08] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [13:37:08] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [13:37:08] [ Info ] try to open SpaceVim welcome page
[   rooter ] [13:37:08] [ Info ] Load projects cache from: /home/ilyagr/.cache/SpaceVim/projects.json
[   rooter ] [13:38:13] [ Info ] Start to find root for: /tmp/vGrShfM/5/issue_report.md
[   rooter ] [13:38:13] [ Info ] buffer name: /tmp/vGrShfM/5/issue_report.md
[   rooter ] [13:38:13] [ Info ] same as current directory, no need to change.
```
</details>
