### ISSUE TITLE
Problems with `unite` layer, including `<SPC> h <SPC>`  problem again

### ISSUE THREAD

**Issue by ilyagr** [wsdjeg/SpaceVim#4084]
I tried using the 'unite' layer instead of the 'fzf' layer, since docs suggest it's more fully featured. This caused two problems and one improvement:

- The issue from https://github.com/SpaceVim/SpaceVim/issues/4081 reappears: `<SPC> h <SPC>` doesn't find any information. This time, there is no help available at all (even for vim and plugins).

- Every startup, I get the following message in the terminal. After pressing ENTER, vim starts normally.

  ```
   $ vim
   [dein] Plugin name "unite.vim" is already defined.
   Press ENTER or type command to continue
  ```

- On the bright side, `<SPC> ?` now works as I requested in https://github.com/SpaceVim/SpaceVim/issues/3347#issuecomment-777049806.

For completeness, I also tried 'denite' and 'leaderf' instead of 'unite'. **'leaderf' works perfectly (!)**. 'denite' does not work, probably because I'm not using neovim.

## Environment Information (debug info is for the 'unite' layer config)

- OS: linux
- vim version: 8.1(1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401)
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: bf748e1e

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
Same as https://github.com/SpaceVim/SpaceVim/issues/4081

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/ilyagr/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/ilyagr/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'git.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="unite"
[[layers]]
  name="git"
[[layers]]
  name="debug"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:07:37] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [16:07:37] [ Info ] find local conf: /home/ilyagr/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [16:07:37] [ Info ] force loading global config >>>
[ SpaceVim ] [16:07:37] [ Info ] global_dir is: /home/ilyagr/.SpaceVim.d/
[ SpaceVim ] [16:07:37] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:07:37] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [16:07:37] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:07:37] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:07:38] [ Info ] try to open SpaceVim welcome page
[   rooter ] [16:07:39] [ Info ] Load projects cache from: /home/ilyagr/.cache/SpaceVim/projects.json
[   rooter ] [16:07:41] [ Info ] Start to find root for: /home/ilyagr/.SpaceVim/
[   rooter ] [16:07:41] [ Info ]         (.git/):/home/ilyagr/.SpaceVim/
[   rooter ] [16:07:41] [ Info ] buffer name: No Name
[   rooter ] [16:07:41] [ Info ] same as current directory, no need to change.
[   rooter ] [16:07:41] [ Info ] Start to find root for: /home/ilyagr/.SpaceVim/[unite] - default
[   rooter ] [16:07:41] [ Info ]         (.git/):/home/ilyagr/.SpaceVim/
[   rooter ] [16:07:41] [ Info ] buffer name: [unite] - default
[   rooter ] [16:07:41] [ Info ] same as current directory, no need to change.
[   rooter ] [16:07:44] [ Info ] Start to find root for: /home/ilyagr/.SpaceVim/
[   rooter ] [16:07:44] [ Info ]         (.git/):/home/ilyagr/.SpaceVim/
[   rooter ] [16:07:44] [ Info ] buffer name: No Name
[   rooter ] [16:07:44] [ Info ] same as current directory, no need to change.
[   rooter ] [16:09:14] [ Info ] Start to find root for: /home/ilyagr/.SpaceVim/doc/SpaceVim.txt
[   rooter ] [16:09:14] [ Info ]         (.git/):/home/ilyagr/.SpaceVim/
[   rooter ] [16:09:14] [ Info ] buffer name: /home/ilyagr/.SpaceVim/doc/SpaceVim.txt
[   rooter ] [16:09:14] [ Info ] same as current directory, no need to change.
[   rooter ] [16:09:17] [ Info ] buffer name: [unite] - default
[   rooter ] [16:09:17] [ Info ] same as current directory, no need to change.
[   rooter ] [16:09:22] [ Info ] buffer name: /home/ilyagr/.SpaceVim/doc/SpaceVim.txt
[   rooter ] [16:09:22] [ Info ] same as current directory, no need to change.
[   rooter ] [16:09:31] [ Info ] Start to find root for: /tmp/vn79TNr/130/issue_report.md
[   rooter ] [16:09:31] [ Info ] buffer name: /tmp/vn79TNr/130/issue_report.md
[   rooter ] [16:09:31] [ Info ] same as current directory, no need to change.
```
</details>

**Comment by wsdjeg** [comment]
this has been fixed now.

**Comment by ilyagr** [comment]
First, to make sure we are on the same page: this is a different issue to #4081 (even though the symptoms are similar). That other issue was triggered by the `SpaceVim.txt` file being empty. This issue is specific to the `unite` layer, and happens even with the correct `SpaceVim.txt`. 

Thanks for looking but no, this doesn't seem fixed to me. In fact, **there is a regression**. After updating SpaceVim, I am now getting slightly different symptoms, and **neither `unite` nor `leaderf` work**. (On commit bf748e1, `leaderf` works.)

## For `leaderf`

On pressing `<SPC> h <SPC>`, I get a Vim error message:

```
Vim:E492: Not an editor command: Leaderf help -input=SpaceVim
```

## For `unite`

On pressing `<SPC> h <SPC>`, I get a Vim error message:

```
Vim:E492: Not an editor command: Unite help -input=SpaceVim
```

I tried removing `~/.cache/vimfiles` to get dein to reinstall all plugins. Now, on every startup, I get a window named `PlugManager` that says:

```
Installing plugins (0/1)
[                                                  ]
 
  - unite.vim: Skip local
```

Here is the debug info with the latest `master` version, with `unite`, after reinstalling all the plugins.

## Environment Information

- OS: linux
- vim version: 8.1(1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401)
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 1b57c561


```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/ilyagr/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/ilyagr/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'git.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="unite"
[[layers]]
  name="git"
[[layers]]
  name="debug"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:08:08] [ Info ] Startup with argv: ['/home/ilyagr/.SpaceVim.d/init.toml']
[ SpaceVim ] [17:08:09] [ Info ] find local conf: /home/ilyagr/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [17:08:09] [ Info ] force loading global config >>>
[ SpaceVim ] [17:08:09] [ Info ] global_dir is: /home/ilyagr/.SpaceVim.d/
[ SpaceVim ] [17:08:09] [ Info ] start to apply config [glob]
[ SpaceVim ] [17:08:09] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [17:08:09] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:08:09] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [17:08:09] [ Info ] Load projects cache from: /home/ilyagr/.cache/SpaceVim/projects.json
[   rooter ] [17:12:06] [ Info ] Start to find root for: /tmp/vNkhHwM/2/issue_report.md
[   rooter ] [17:12:06] [ Info ] buffer name: /tmp/vNkhHwM/2/issue_report.md
[   rooter ] [17:12:06] [ Info ] same as current directory, no need to change.
```
</details>
