### ISSUE TITLE
At startup, error message: [dein] Plugin name "vim-jsdoc" is already defined, when having both typescript and javascript layers activated

### ISSUE THREAD

**Issue by autra** [wsdjeg/SpaceVim#4085]
## Expected behavior, english is required

When having both typescript and javascript layer, no error at startup.

## Actual behaviour

At startup, I have this error:

```
[dein] Plugin name "vim-jsdoc" is already defined.
```

## The reproduce ways from Vim starting (Required!)

- have javascript and typescript layers activated
- start vim

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: bf748e1e

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'molokai'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/augustin/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/augustin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'riv.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="ctrlp"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#python"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#rst"
[[layers]]
  name="debug"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:28:07] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [08:28:07] [ Info ] find local conf: /home/augustin/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [08:28:07] [ Info ] force loading global config >>>
[ SpaceVim ] [08:28:07] [ Info ] global_dir is: /home/augustin/.SpaceVim.d/
[ SpaceVim ] [08:28:07] [ Info ] start to apply config [glob]
[ SpaceVim ] [08:28:07] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [08:28:07] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [08:28:08] [ Info ] try to open SpaceVim welcome page
[   rooter ] [08:28:08] [ Info ] Load projects cache from: /home/augustin/.cache/SpaceVim/projects.json
[   rooter ] [08:28:15] [ Info ] Start to find root for: /home/augustin/.SpaceVim/autoload/SpaceVim/layers/lang/javascript.vim
[   rooter ] [08:28:15] [ Info ]         (.git/):/home/augustin/.SpaceVim/
[   rooter ] [08:28:15] [ Info ] buffer name: javascript.vim
[   rooter ] [08:28:15] [ Info ] change to root: /home/augustin/.SpaceVim/
[   rooter ] [08:31:56] [ Info ] Start to find root for: /tmp/nvimgIVZmA/7/issue_report.md
[   rooter ] [08:31:56] [ Info ] buffer name: /tmp/nvimgIVZmA/7/issue_report.md
[   rooter ] [08:31:56] [ Info ] same as current directory, no need to change.
[   rooter ] [08:31:57] [ Info ] Start to find root for: /tmp/nvimgIVZmA/7/issue_report.md
[   rooter ] [08:31:57] [ Info ] buffer name: /tmp/nvimgIVZmA/7/issue_report.md
[   rooter ] [08:31:57] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [08:32:15] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [08:32:16] [ Info ] buffer name: issue_report.md
[   rooter ] [08:32:16] [ Info ] change to root: /home/augustin/.SpaceVim/autoload/SpaceVim/layers/lang/
[ SpaceVim ] [08:32:16] [ Info ] close float statusline winid:1006
[ SpaceVim ] [08:32:18] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [08:32:18] [ Info ] buffer name: issue_report.md
[   rooter ] [08:32:18] [ Info ] change to root: /home/augustin/.SpaceVim/autoload/SpaceVim/layers/lang/
[ SpaceVim ] [08:32:18] [ Info ] close float statusline winid:1008
[ SpaceVim ] [08:32:18] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [08:32:22] [ Info ] buffer name: issue_report.md
[   rooter ] [08:32:22] [ Info ] change to root: /home/augustin/.SpaceVim/autoload/SpaceVim/layers/lang/
[ SpaceVim ] [08:32:22] [ Info ] close float statusline winid:1010
[   rooter ] [08:32:23] [ Info ] Start to find root for: /tmp/nvimgIVZmA/9/issue_report.md
[   rooter ] [08:32:23] [ Info ] buffer name: /tmp/nvimgIVZmA/9/issue_report.md
[   rooter ] [08:32:23] [ Info ] same as current directory, no need to change.
```
</details>

I can probably make a PR, but I'm not sure how to do it properly. Do I check for javascript layer in typescript layer ? Do I check for already loaded jsdoc in both (how to do this)?
