### ISSUE TITLE
neovim没有状态栏，只有几个黑白图标，neovimqt就没事

### ISSUE THREAD

**Issue by tiankongsnow** [wsdjeg/SpaceVim#4086]
## 问题描述
我在windows安装了vim和neovim，然后安装spacevim，在我另一台机器上，这俩都没出事，但是这台机器上，vim没问题，但是neovim没有状态栏，只有几个黑白图标，neovimqt就不是这样，而且安装sp后，打开neovim并没有安装插件这一过程，vim就有。
## Environment Information

- OS: windows
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.6.0-dev
- SpaceVim status: d626ce2d 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\Administrator\.cache\'
  debug_level = 1
  default_indent = 2
  disabled_plugins = []
  enable_ale = 0
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_insert_leader = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = '等距更纱黑体 T SC:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\Administrator\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'srcery-vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.6.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim.exe(D:\Program Files\nvim-win64\Neovim\bin\nvim.exe)
version: 800
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [01:13:15] [ Info ] Startup with no argv, current dir is used: D:\Program Files\nvim-win64\Neovim\bin
[ SpaceVim ] [01:13:15] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [01:13:15] [ Info ] global_dir is: C:/Users/Administrator/.SpaceVim.d/
[ SpaceVim ] [01:13:15] [ Info ] start to apply config [glob]
[ SpaceVim ] [01:13:16] [ Info ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [01:13:17] [ Info ] try to open SpaceVim welcome page
[   rooter ] [01:13:17] [ Info ] Load projects cache from: C:/Users/Administrator/.cache/SpaceVim/projects.json
[   rooter ] [01:13:21] [ Info ] Start to find root for: D:/Program Files/nvim-win64/Neovim/bin/
[   rooter ] [01:13:21] [ Info ] buffer name: No Name
[   rooter ] [01:13:21] [ Info ] same as current directory, no need to change.
[   rooter ] [01:13:43] [ Info ] Start to find root for: C:/Users/ADMINI~1/AppData/Local/Temp/nvimzG1rJq/0/issue_report.md
[   rooter ] [01:13:44] [ Info ]         (.SpaceVim.d/):C:/Users/ADMINI~1/
[   rooter ] [01:13:44] [ Info ] buffer name: C:\Users\ADMINI~1\AppData\Local\Temp\nvimzG1rJq\0\issue_report.md
[   rooter ] [01:13:44] [ Info ] change to root: C:/Users/ADMINI~1/
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## 截图

![vim](https://images.gitee.com/uploads/images/2021/0201/012519_f9839553_7350572.png "vim.PNG")
![gvim](https://images.gitee.com/uploads/images/2021/0201/012541_23fe32ac_7350572.png "gvim.PNG")
![nvimqt](https://images.gitee.com/uploads/images/2021/0201/012555_9784674e_7350572.png "neovimqt.PNG")
![nvim](https://images.gitee.com/uploads/images/2021/0201/012612_76202c63_7350572.png "neovim.PNG")
