### ISSUE TITLE
[dein] Plugin name vim-snippets is already defined.

### ISSUE THREAD

**Issue by hexh250786313** [wsdjeg/SpaceVim#4102]
## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.5.0
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 1b57c561

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	coc-settings.json
	files/
	sessions/

nothing added to commit but untracked files present (use "git add" to track)
```

## The reproduce ways from Vim starting (Required!)

- Warning "[dein] Plugin name vim-snippets is already defined." when starting Neovim
- Vim-snippets plugin dosen't work (with coc-snippets which is a coc plugin)
- The warning disappeared after I removed the custom_plugins vim-snippents in `init.toml`, but vim-snippets still didn't work

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 0
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'codedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = [['#ffffff', '#0a7aca', 246, 235], ['#ffffff', '#373737', 239, 246], ['#ffffff', '#373737', 237, 246], ['#373737', 241], ['#1e1e1e', '#ffaf00', 235, 109], ['#5cb6f8', '#3c3c3c', 235, 208], ['#ffffff', '#8ec07c', 235, 108], ['#ffffff', '#689d6a', 235, 72], ['#ffffff', '#8f3f71', 235, 132]]
  custom_plugins = [['tpope/vim-fugitive', {'repo': 'tpope/vim-fugitive', 'merged': 0}], ['rhysd/conflict-marker.vim', {'repo': 'rhysd/conflict-marker.vim', 'merged': 0}], ['sodapopcan/vim-twiggy', {'repo': 'sodapopcan/vim-twiggy', 'merged': 0}], ['rbong/vim-flog', {'repo': 'rbong/vim-flog', 'merged': 0}], ['junkblocker/git-time-lapse', {'repo': 'junkblocker/git-time-lapse', 'merged': 0}], ['maxmellon/vim-jsx-pretty', {'repo': 'maxmellon/vim-jsx-pretty', 'merged': 0}], ['tomasiser/vim-code-dark', {'repo': 'tomasiser/vim-code-dark', 'merged': 0}], ['yuezk/vim-js', {'repo': 'yuezk/vim-js', 'merged': 0}], ['honza/vim-snippets', {'repo': 'honza/vim-snippets', 'merged': 0}], ['psliwka/vim-smoothie', {'repo': 'psliwka/vim-smoothie', 'merged': 0}]]
  data_dir = '/home/hexh/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['vim-startify', 'CompleteParameter.vim', 'neopairs.vim', 'vim-matchup', 'neosnippet-snippets', 'neosnippet.vim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/hexh/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'palenight.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'snippets'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="lsp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:41:58] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [15:41:58] [ Info ] find local conf: /home/hexh/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [15:41:58] [ Info ] force loading global config >>>
[ SpaceVim ] [15:41:58] [ Info ] global_dir is: /home/hexh/workspace/notes/Something/bak/linux/home/.SpaceVim.d/
[ SpaceVim ] [15:41:58] [ Info ] start to apply config [glob]
[ SpaceVim ] [15:41:59] [ Warn ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [15:41:59] [ Warn ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [15:41:59] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:41:59] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:41:59] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [15:41:59] [ Info ] no func found for mode:syntax-checking
[ SpaceVim ] [15:41:59] [ Info ] try to call func of mode:whitespace
[ SpaceVim ] [15:41:59] [ Info ] no func found for mode:whitespace
[ SpaceVim ] [15:41:59] [ Info ] try to open SpaceVim welcome page
[   rooter ] [15:41:59] [ Info ] Load projects cache from: /home/hexh/.cache/SpaceVim/projects.json
[   rooter ] [15:42:00] [ Info ] Start to find root for: /home/hexh/workspace/notes/Something/bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:42:00] [ Info ]         (.git/):/home/hexh/workspace/notes/Something/
[   rooter ] [15:42:00] [ Info ]         (.SpaceVim.d/):/home/hexh/workspace/notes/Something/bak/linux/home/
[   rooter ] [15:42:00] [ Info ] buffer name: /home/hexh/workspace/notes/Something/bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:42:00] [ Info ] change to root: /home/hexh/workspace/notes/Something/
[   rooter ] [15:42:07] [ Info ] Start to find root for: /home/hexh/workspace/notes/Something/bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:42:07] [ Info ]         (.git/):/home/hexh/workspace/notes/Something/
[   rooter ] [15:42:07] [ Info ]         (.SpaceVim.d/):/home/hexh/workspace/notes/Something/bak/linux/home/
[   rooter ] [15:42:07] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:42:07] [ Info ] same as current directory, no need to change.
[   rooter ] [15:42:55] [ Info ] Start to find root for: /home/hexh/workspace/notes/Something/[defx] -0
[   rooter ] [15:42:55] [ Info ]         (.git/):/home/hexh/workspace/notes/Something/
[   rooter ] [15:42:55] [ Info ]         (.SpaceVim.d/):/home/hexh/workspace/notes/Something/bak/linux/home/
[   rooter ] [15:42:55] [ Info ] buffer name: [defx] -0
[   rooter ] [15:42:55] [ Info ] same as current directory, no need to change.
[   rooter ] [15:42:57] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:42:57] [ Info ] same as current directory, no need to change.
[   rooter ] [15:42:57] [ Info ] Start to find root for: /home/hexh/workspace/notes/Something/bak/linux/home/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [15:42:57] [ Info ]         (.git/):/home/hexh/workspace/notes/Something/
[   rooter ] [15:42:57] [ Info ]         (.SpaceVim.d/):/home/hexh/workspace/notes/Something/bak/linux/home/
[   rooter ] [15:42:57] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [15:42:57] [ Info ] same as current directory, no need to change.
[   rooter ] [15:42:58] [ Info ] buffer name: [defx] -0
[   rooter ] [15:42:58] [ Info ] same as current directory, no need to change.
[   rooter ] [15:42:58] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [15:42:58] [ Info ] same as current directory, no need to change.
[   rooter ] [15:43:00] [ Info ] Start to find root for: /home/hexh/workspace/notes/Something/bak/linux/home/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [15:43:00] [ Info ]         (.git/):/home/hexh/workspace/notes/Something/
[   rooter ] [15:43:00] [ Info ]         (.SpaceVim.d/):/home/hexh/workspace/notes/Something/bak/linux/home/
[   rooter ] [15:43:00] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [15:43:00] [ Info ] same as current directory, no need to change.
[   rooter ] [15:43:09] [ Info ] buffer name: [defx] -0
[   rooter ] [15:43:09] [ Info ] same as current directory, no need to change.
[   rooter ] [15:43:10] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [15:43:10] [ Info ] same as current directory, no need to change.
[   rooter ] [15:43:10] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:43:10] [ Info ] same as current directory, no need to change.
[   rooter ] [15:43:12] [ Info ] buffer name: [defx] -0
[   rooter ] [15:43:12] [ Info ] same as current directory, no need to change.
[   rooter ] [15:43:12] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:43:12] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:43:24] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [15:43:25] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:43:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:43:25] [ Info ] close float statusline winid:1006
[ SpaceVim ] [15:43:25] [ Info ] key binding guide float statusline winid:1008
[   rooter ] [15:43:31] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:43:31] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:43:31] [ Info ] close float statusline winid:1008
[ SpaceVim ] [15:44:11] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [15:44:11] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:44:11] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:44:11] [ Info ] close float statusline winid:1010
[ SpaceVim ] [15:44:11] [ Info ] key binding guide float statusline winid:1012
[   rooter ] [15:44:12] [ Info ] buffer name: bak/linux/home/.SpaceVim.d/init.toml
[   rooter ] [15:44:12] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:44:12] [ Info ] close float statusline winid:1012
[   rooter ] [15:44:12] [ Info ] Start to find root for: /tmp/nvimr4pMIW/3/issue_report.md
[   rooter ] [15:44:12] [ Info ] buffer name: /tmp/nvimr4pMIW/3/issue_report.md
[   rooter ] [15:44:12] [ Info ] same as current directory, no need to change.
```
</details>

**Comment by hexh250786313** [comment]
Vim-snippets works fine after I removed the line 33 in `~/.SpaceVim/bundle/dein.vim/autoload/dein/parse.vim`:

```vim
@@ -33 +32,0 @@ function! dein#parse#_add(repo, options, overwrite) abort
-      return {}
```

But it won't be the solution of course.

**Comment by Shougo** [comment]
Your SpaceVim is the latest version?

**Comment by Shougo** [comment]
SpaceVim's dein may be old though.

**Comment by hexh250786313** [comment]
> SpaceVim's dein may be old though.

I have no idea about this. I just call `SPUpdate` to update all plugins.

**Comment by Shougo** [comment]
Hm.  SpaceVim's dein supports overwrite flag.
https://github.com/SpaceVim/SpaceVim/commit/211fcf679336bf212aa61621fc8c29b1071aec25

It seems old though.
@wsdjeg Please update the dein to the latest.

**Comment by Shougo** [comment]
@wsdjeg custom_plugins layer uses overwrite flag?

**Comment by wsdjeg** [comment]
Yeah, plugin in SpaceVim is added with overwrite flag by default, because a plugin maybe existe in more than one layer.

and currently the version of dein is https://github.com/Shougo/dein.vim/commit/7e39f0cb65cc971fff4bdbbd85cb23e404b9c86a

**Comment by hexh250786313** [comment]
So, any solution? I have updated my SpaceVim to [SpaceVim/SpaceVim@`c06bce14`](https://github.com/SpaceVim/SpaceVim/commit/c06bce147c51ee8846a6de8f74f7526b660a2c1b), but I don't think it make a difference to the issue.

**Comment by Shougo** [comment]
@hexh250786313 You should upload the minimal config.  We have no ESP skills.

**Comment by Shougo** [comment]
You should add overwrite flag manually.

```toml
[[custom_plugins]]
    repo = "honza/vim-snippets"
    overwrite = true
```

**Comment by Shougo** [comment]
OK.  I get the reason.
@wsdjeg Please compare the implementation.

The load layers feature uses overwrite flag.
https://github.com/SpaceVim/SpaceVim/blob/211fcf679336bf212aa61621fc8c29b1071aec25/autoload/SpaceVim/plugins.vim#L25

But for custom plugins, overwrite flag is not added automatically.
https://github.com/SpaceVim/SpaceVim/blob/211fcf679336bf212aa61621fc8c29b1071aec25/autoload/SpaceVim/plugins.vim#L39

>@wsdjeg custom_plugins layer uses overwrite flag?

I have asked it before...

**Comment by wsdjeg** [comment]
OK, thanks

**Comment by hexh250786313** [comment]
## `init.toml`

```toml
[options]
    enable_guicolors = false
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    vimcompatible = true
    enable_neomake = false
    autocomplete_method = "coc"
    autocomplete_parens = false
    filemanager = "defx"

[[layers]]
  name = "checkers"
  enable = false

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]] 
  name = 'lsp'

[[custom_plugins]]
  repo = "honza/vim-snippets"
  merged = false
  overwrite = true

```

## Coc

My coc is installed with coc-tsserver, coc-lists and coc-snippets.

And there is no custom coc config.

**Comment by Shougo** [comment]
```toml
[[custom_plugins]]
  repo = "honza/vim-snippets"
  merged = false
  overwrite = true
```

It should work.  Have you tested the config?

**Comment by hexh250786313** [comment]
@Shougo Yep, no warning but vim-snippets doesn't work.

**Comment by Shougo** [comment]
What means `vim-snippets` does not work?
I don't understand.

**Comment by hexh250786313** [comment]
## An old version SpaceVim

I reset my SpaceVim to a279122e0c323fe3cdc2525eb4855baeb78db66. Then I input `cl` in a js file, the coc give the tips `console.log` like this:

![image](https://user-images.githubusercontent.com/26080416/108451252-74cfab00-72a1-11eb-80bd-65b4d0fc7fcb.png)

## Latest SpaceVim

I do the same with the latest SpaceVim, but there's no snippets tips (`[S]` means snippets):

![image](https://user-images.githubusercontent.com/26080416/108451506-e7408b00-72a1-11eb-9b43-40055a95a8bf.png)

Both of them use above `init.toml` and the same coc plugins.

**Comment by Shougo** [comment]
https://github.com/SpaceVim/SpaceVim/blob/c06bce147c51ee8846a6de8f74f7526b660a2c1b/autoload/SpaceVim/layers/autocomplete.vim#L43

vim-snippets is already bundled in SpaceVim.
So you don't need to configure it.

**Comment by Shougo** [comment]
vim-snippets seems lazy loaded on `InsertEnter` but coc does not support lazy loaded source.

**Comment by Shougo** [comment]
You should disable lazy load in vim-snippets.

```toml
[[custom_plugins]]
  repo = "honza/vim-snippets"
  merged = false
  overwrite = true
  lazy = false
```
