### ISSUE TITLE
cmp#check_revert_select('()', '') error 

### ISSUE THREAD

**Issue by code5717** [wsdjeg/SpaceVim#4106]
i am using Linux Popos (based on ubuntu)
i downloaded a bbunch of plugins
i get 
```
cmp#check_revert_select('()', '')
```
when i code in c i get ^^ in the command bar

my log 
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/airbus5717/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 8
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/airbus5717/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-gitgutter'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
  enable_clang_syntax_highlight=0
  clang_flag=['-I/user/include']
[[layers]]
  name="neomake"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
  java_formatter_jar='/home/airbus5717/code/java/res/google-java-format-1.9-all-deps.jar'
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.level=NONE', '-noverify', '-Xmx1G', '-jar', '/home/airbus5717/code/java/res/jdt-language-server-0.9.0-201711302113/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-configuration', '/home/airbus5717/code/java/res/jdt-language-server-0.9.0-201711302113/config_linux', '-data', '/home/airbus5717/.cache/javalsp']}
  filetypes=['python', 'java']
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [23:06:18] [ Info ] Startup with argv: ['main.c']
[ SpaceVim ] [23:06:18] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [23:06:18] [ Info ] global_dir is: /home/airbus5717/.SpaceVim.d/
[ SpaceVim ] [23:06:18] [ Info ] start to apply config [glob]
[ SpaceVim ] [23:06:18] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [23:06:18] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [23:06:18] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [23:06:18] [ Info ] Load projects cache from: /home/airbus5717/.cache/SpaceVim/projects.json
[   rooter ] [23:06:18] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [23:06:18] [ Info ] Start to find root for: /home/airbus5717/code/c/raylib/helloWorld/main.c
[   rooter ] [23:06:18] [ Info ]         (.clang):/home/airbus5717/code/c/raylib/helloWorld/
[   rooter ] [23:06:18] [ Info ] buffer name: main.c
[   rooter ] [23:06:18] [ Info ] same as current directory, no need to change.
[   rooter ] [23:06:18] [ Info ] buffer name: main.c
[   rooter ] [23:06:18] [ Info ] same as current directory, no need to change.
```
</details>
