### ISSUE TITLE
[Bug] Lang: Go - Error `E225: global mapping already exists for (`

### ISSUE THREAD

**Issue by JustinTimperio** [wsdjeg/SpaceVim#4109]
## System
OS: Arch Linux x86_64
Kernel: 5.10.16-arch1-1
Neovim: neovim@0.4.4-1
Spacevim: 1.7.0-dev
GoTags: gotags@v1.4.1

## The reproduce ways from Vim starting (Required!)
1. Install Spacevim - `curl -sLf https://spacevim.org/install.sh | bash`
2. Install Golang layer with gotags and binaries installed: (https://spacevim.org/layers/lang/go/)
2. Open any existing or new go file - `nvim file.go`
4. Save file with <kbd>SPC f s</kbd>

## Screenshots

![image](https://user-images.githubusercontent.com/9936997/108773930-09017280-752d-11eb-8e95-f397542aef69.png)

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: a9a79af4

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/justin/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/justin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#go"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:46:04] [ Info ] Startup with argv: ['/home/justin/Repos/GoLang/dapmi/dampi.go']
[ SpaceVim ] [16:46:04] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [16:46:04] [ Info ] global_dir is: /home/justin/.SpaceVim.d/
[ SpaceVim ] [16:46:04] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:46:04] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [16:46:04] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:46:04] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [16:46:04] [ Info ] Load projects cache from: /home/justin/.cache/SpaceVim/projects.json
[   rooter ] [16:46:18] [ Info ] Start to find root for: /home/justin/Repos/GoLang/dapmi/dampi.go
[   rooter ] [16:46:18] [ Info ]         (.git/):/home/justin/Repos/GoLang/dapmi/
[   rooter ] [16:46:18] [ Info ] buffer name: dampi.go
[   rooter ] [16:46:18] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:46:20] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [16:46:20] [ Info ] buffer name: dampi.go
[   rooter ] [16:46:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:46:20] [ Info ] close float statusline winid:1003
[ SpaceVim ] [16:46:20] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [16:46:20] [ Info ] buffer name: dampi.go
[   rooter ] [16:46:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:46:20] [ Info ] close float statusline winid:1005
[   rooter ] [16:46:22] [ Info ] Start to find root for: /tmp/nvimO05Scx/2/issue_report.md
[   rooter ] [16:46:22] [ Info ] buffer name: /tmp/nvimO05Scx/2/issue_report.md
[   rooter ] [16:46:22] [ Info ] same as current directory, no need to change.
```
</details>
