### ISSUE TITLE
Copy/paste fails silently on wayland if wl-clipboard package is not installed

### ISSUE THREAD

**Issue by taranjlu** [wsdjeg/SpaceVim#4112]
## Expected behavior, english is recommend
This isn't exactly a bug, more of a config/documentation issue. I would expect to get a warning message in `:checkhealth` and maybe have a mention in the documentation.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: a9a79af4

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
On Fedora 33, using Sway as window manager, it seems that `wl-clipboard` package is not installed by default (which seems like an oversight...).

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'tl_config#after'
  bootstrap_before = 'tl_config#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['tmhedberg/SimpylFold', {'repo': 'tmhedberg/SimpylFold', 'merged': 0, 'on_ft': ['python'], 'overwrite': 1}], ['Konfekt/FastFold', {'repo': 'Konfekt/FastFold', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/----/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = ''
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/----/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="incsearch"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="sudo"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#python"
  format_on_save=1
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/home/linuxbrew/.linuxbrew/Cellar/neovim/0.4.4_1/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [02:15:14] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [02:15:14] [ Info ] find local conf: /home/----/.SpaceVim.d/init.toml
[ SpaceVim ] [02:15:14] [ Info ] loading cached local conf: /home/----/.cache//SpaceVim/conf/_home_----__SpaceVim_d_init_toml.json
[ SpaceVim ] [02:15:14] [ Info ] start to apply config [local]
[ SpaceVim ] [02:15:14] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [02:15:14] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [02:15:14] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [02:15:14] [ Info ] Load projects cache from: /home/----/.cache/SpaceVim/projects.json
[   rooter ] [02:15:14] [ Info ] Start to find root for: /home/----/
[   rooter ] [02:15:14] [ Info ] buffer name: No Name
[   rooter ] [02:15:14] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:15:14] [ Info ] try to open SpaceVim welcome page
[   rooter ] [02:15:14] [ Info ] buffer name: No Name
[   rooter ] [02:15:14] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:15:23] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [02:15:23] [ Info ] buffer name: No Name
[   rooter ] [02:15:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:15:23] [ Info ] close float statusline winid:1004
[ SpaceVim ] [02:15:23] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [02:15:27] [ Info ] buffer name: No Name
[   rooter ] [02:15:27] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [02:15:27] [ Info ] close float statusline winid:1006
[   rooter ] [02:15:27] [ Info ] Start to find root for: /tmp/nvimvrHKjP/1/issue_report.md
[   rooter ] [02:15:27] [ Info ] buffer name: /tmp/nvimvrHKjP/1/issue_report.md
[   rooter ] [02:15:27] [ Info ] same as current directory, no need to change.
```
</details>
