### ISSUE TITLE
Jump to error line in tasks manager

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4126]
**Is your feature request related to a problem? Please describe.**
tasks manager can be used instead of ``:make``  to compile project, but when there're some compile error, we can't jump to error line like in quickfix window.

**Describe the solution you'd like**
In VSCode, tasks has a property named [``problemMatcher``](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher), which can be used to match the problem to jump to error line.  I suggest tasks manager in SpaceVim support the jumping too.

**Describe alternatives you've considered**
 1. load the final output into quickfix window, it automatically support error jumping.  But it can only work after the task is completely finished, which may need minutes for large C++ project.
 2. support ``errorformat`` natively in tasks manager, so the jumping is possible while the task is running, no need to wait it finish.

**Additional context**

**Comment by wsdjeg** [comment]
good idea. we can add problemmatcher, for example:

```
[my-task]
    command = 'echo'
    args = ['hello world']
    isBackground = true
    problemMatcher = [
           regexp = ''
           filelocation = ['relative', '${workspaceFolder}']
    ]
```

**Comment by wsdjeg** [comment]
errorformat or regexp? I think in one task only one of these can be used.

**Comment by thawk** [comment]
I perfer using errorformat, so we don't need to write another match expression.  But maybe using regexp is easier to implement.

**Comment by wsdjeg** [comment]
@thawk in #4127 the `errorformat` option has been added, and you can definded task `test_problemMatcher` like this:

```
[test_problemMatcher]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:6:1 test error message']
    isBackground = true
[test_problemMatcher.problemMatcher]
    errorformat = '%f:%l:%c\ %m'
```

after running this task, you will see:

![image](https://user-images.githubusercontent.com/13142418/110803412-20c15080-82ba-11eb-8d49-d22d4e88e148.png)

But that PR has not been finished.

**Comment by thawk** [comment]
I would perfer taking **current** ``&errorformat`` instead of repeat it again. I think ``&errorformat`` is already set in most situation.
If need to write in ``tasks.toml``, maybe regexp is much easier for most people.
Is it possible to make problemMatcher default to ``&errorformat``, and let user set ``regexp`` instead?

```toml
[test_noProblemMatcher]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:3:1 test error message']
    isBackground = true
[test_defaultErrorFormat]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:7:1 test error message']
    isBackground = true
    problemMatcher = {}  # use a empty table to distinguish from no problemMatcher at all
[test_regexp]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:12:1 test error message']
    isBackground = true
    [[test_regexp.problemMatcher.pattern]]
          regexp = "^(.*):(\\d+):(\\d+)\\s+(\\S.*)$"
          file = 1
          line = 2
          column = 3
          #severity = 4
          message = 4
```

It seems to be a little complicated to use regexp :-(
