### ISSUE TITLE
how to configure mccabe with spacevim lsp?

### ISSUE THREAD

**Issue by rachmadaniHaryono** [wsdjeg/SpaceVim#4145]
## Expected behavior, english is recommend
1. create following file "main.py" on empty folder
```python
def main():
    v1 = 1
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
    if v1 == 2:
        print(v1)
```
2. when opened there should be error on error list (`space-e-l`) `main.py|1 col 1 warning| Cyclomatic complexity too high: 16 (threshold 15)`
3. create setup.cfg with following content

```ini
[flake8]
max_complexity = 17
```
4. close spacevim
5. open main.py once again
6. no more error on main.py

what happen is on step 6, the same error still exist.

i take step 3, and 4 assuming the error is coming from flake8's mccabe.

there is also option to change the limit on `~/.config/flake8` but i want to keep it on project folder.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 48a6e4b9

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	config/commands.vim

nothing added to commit but untracked files present (use "git add" to track)
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['masukomi/vim-markdown-folding', {'repo': 'masukomi/vim-markdown-folding', 'overwrite': 1}], ['tmhedberg/SimpylFold', {'repo': 'tmhedberg/SimpylFold', 'overwrite': 1}]]
  data_dir = '/home/r3r/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['fcitx.vim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'rachmadaniHaryono'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/r3r/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'zeavim.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="foldsearch"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="github"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
  python_interpreter='/home/r3r/envs/neovim3/bin/python'
  enable_typeinfo=1
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'python': ['/home/r3r/envs/neovim3/bin/pyls']}
  filetypes=['python']
[[layers]]
  name="shell"
  default_shell='terminal'
[[layers]]
  name="tags"
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#mpv"
  musics_directory='/home/r3r/Music_Unsorted'
  mpv_interpreter='/usr/bin/mpv'
[[layers]]
  name="tools#zeal"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:36:43] [ Info ] Startup with argv: ['main.py']
[ SpaceVim ] [09:36:43] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [09:36:43] [ Info ] global_dir is: /home/r3r/.SpaceVim.d/
[ SpaceVim ] [09:36:43] [ Info ] start to apply config [glob]
[ SpaceVim ] [09:36:43] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [09:36:43] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:36:44] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [09:36:44] [ Info ] Load projects cache from: /home/r3r/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:36:56] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [09:36:58] [ Info ] Start to find root for: /home/r3r/git/temp/main.py
[   rooter ] [09:36:58] [ Info ] buffer name: main.py
[   rooter ] [09:36:58] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:36:58] [ Info ] close float statusline winid:1003
[ SpaceVim ] [09:36:58] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [09:36:59] [ Info ] buffer name: main.py
[   rooter ] [09:36:59] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:36:59] [ Info ] close float statusline winid:1005
[   rooter ] [09:37:00] [ Info ] Start to find root for: /tmp/nvimvq0lyS/3/issue_report.md
[   rooter ] [09:37:00] [ Info ] buffer name: /tmp/nvimvq0lyS/3/issue_report.md
[   rooter ] [09:37:00] [ Info ] same as current directory, no need to change.
```
</details>

**Comment by rachmadaniHaryono** [comment]
i just found about this issue https://github.com/palantir/python-language-server/issues/190 which linked me to another project https://github.com/emanspeaks/pyls-flake8

installing pyls-flake8 have better outcome but there is difference in behaviour

1. create main.py similar to above
2. no error when opening main.py
3. create virtualenv on the folder
4. no error when opening main.py
5. pip install flake8
6. no error when opening main.py
7. create setup.cfg with following content:
```ini
[flake8]
max-complexity = 15
```
8 when main.py opened there is entry on error list (space-e-l) `main.py|1 col 1 warning| 'main' is too complex (16)`
9. change setup.cfg with following content:
```ini
[flake8]
max-complexity = 16
```
10 no error when opening main.py

**Comment by wsdjeg** [comment]
```
[   rooter ] [09:36:58] [ Info ] Start to find root for: /home/r3r/git/temp/main.py
[   rooter ] [09:36:58] [ Info ] buffer name: main.py
[   rooter ] [09:36:58] [ Info ] same as current directory, no need to change.
```

the main.py is not in a project, you should run `git init` in `/home/r3r/git/temp/`, then create `setup.cfg` in it.

**Comment by rachmadaniHaryono** [comment]
<details>
<summary>SpaceVim runtime log </summary>

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:11:48] [ Info ] Startup with argv: ['main.py']
[ SpaceVim ] [16:11:48] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [16:11:48] [ Info ] global_dir is: /home/r3r/.SpaceVim.d/
[ SpaceVim ] [16:11:48] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:11:48] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:11:48] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [16:11:49] [ Info ] Load projects cache from: /home/r3r/.cache/SpaceVim/projects.json
[ SpaceVim ] [16:12:20] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [16:12:21] [ Info ] Start to find root for: /home/r3r/git/temp/main.py
[   rooter ] [16:12:21] [ Info ]         (.git/):/home/r3r/git/temp/
[   rooter ] [16:12:21] [ Info ] buffer name: main.py
[   rooter ] [16:12:21] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:12:21] [ Info ] close float statusline winid:1003
[ SpaceVim ] [16:12:21] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [16:12:25] [ Info ] buffer name: main.py
[   rooter ] [16:12:25] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:12:25] [ Info ] close float statusline winid:1005
[ SpaceVim ] [16:12:27] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [16:12:27] [ Info ] buffer name: main.py
[   rooter ] [16:12:27] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:12:27] [ Info ] close float statusline winid:1007
[ SpaceVim ] [16:12:27] [ Info ] key binding guide float statusline winid:1009
[   rooter ] [16:12:28] [ Info ] buffer name: main.py
[   rooter ] [16:12:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:12:28] [ Info ] close float statusline winid:1009
[ SpaceVim ] [16:12:28] [ Info ] key binding guide float statusline winid:1011
[   rooter ] [16:12:29] [ Info ] buffer name: main.py
[   rooter ] [16:12:29] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [16:12:29] [ Info ] close float statusline winid:1011
```
</details>

removed pyls-flake8 and run `git init` on the folder, the first error is still exist 

> main.py|1 col 1 warning| Cyclomatic complexity too high: 16 (threshold 15)

**Comment by wsdjeg** [comment]
What is your crrent directory? you can check it via `:pwd`, is it `/home/r3r/git/temp/`?

**Comment by rachmadaniHaryono** [comment]
yes `/home/r3r/git/temp`

**Comment by rachmadaniHaryono** [comment]
i can't reproduce this issue with my new config

and also i have changed my lsp layer config and don't use pyls anymore

my current config with lsp layer

```toml
[[layers]]
name = 'lsp'
filetypes = ["python"]
enabled_clients = ["pyright"]
```
pyright can be installed through snap https://snapcraft.io/pyright

for more info https://github.com/microsoft/pyright
