### ISSUE TITLE
Lang#latex characters missing

### ISSUE THREAD

**Issue by vuvgaG** [wsdjeg/SpaceVim#4167]
## Expected behavior, english is recommend

I expected characters to show like $ and commands line \textbf

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 55a7b777

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/vuv/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/vuv/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-clangx'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#extra"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="lang#plantuml"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#python"
  format_on_save=1
  enable_typeinfo=1
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.4_1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [04:04:44] [ Info ] Startup with argv: ['main.tex']
[ SpaceVim ] [04:04:44] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [04:04:44] [ Info ] global_dir is: /Users/vuv/source/bash-profile/SpaceVim.d/
[ SpaceVim ] [04:04:44] [ Info ] start to apply config [glob]
[ SpaceVim ] [04:04:44] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [04:04:45] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [04:04:45] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [04:04:45] [ Info ] Load projects cache from: /Users/vuv/.cache/SpaceVim/projects.json
[   rooter ] [04:04:46] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [04:04:46] [ Info ] Start to find root for: /Users/vuv/source/learning/math-textbook/math-algebra-textbook/main.tex
[   rooter ] [04:04:46] [ Info ]         (.git/):/Users/vuv/source/learning/math-textbook/
[   rooter ] [04:04:46] [ Info ] buffer name: main.tex
[   rooter ] [04:04:46] [ Info ] change to root: /Users/vuv/source/learning/math-textbook/
[   rooter ] [04:04:46] [ Info ] buffer name: math-algebra-textbook/main.tex
[   rooter ] [04:04:46] [ Info ] same as current directory, no need to change.
[   rooter ] [04:04:48] [ Info ] Start to find root for: /private/var/folders/r6/32ldt9xn4z34wngtzn_0_b1r0000gn/T/nvimQg87oc/2/issue_report.md
[   rooter ] [04:04:48] [ Info ] buffer name: /var/folders/r6/32ldt9xn4z34wngtzn_0_b1r0000gn/T/nvimQg87oc/2/issue_report.md
[   rooter ] [04:04:48] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/75189112/113495845-2b06f100-94ec-11eb-99f8-588256702ca8.png)
