### ISSUE TITLE
The layer "incsearch" doesn't work well.

### ISSUE THREAD

**Issue by xylinkun** [wsdjeg/SpaceVim#4180]
## Expected behavior, english is required

I have tried to enable the layer `incsearch` according to the documentation. but I encounter some errors when I restart SpaceVim.

> Search index is provided by incsearch layer, to enable this layer:
> 
> [layers]
>    name = "incsearch"

## The reproduce ways from Vim starting (Required!)

Just enable the layer "incsearch" via the following configure and then restart SpaceVim.

```toml
[layers]
    name = "incsearch"
```

The bug disappeared after I disabled the layer "incsearch".

## Debug info

SpaceVim layers:

- lang#PatentHubSearchCriteria:not loaded          no exists
- lang#incoPatSearchCriteria:not loaded          no exists
- VersionControl:       not loaded          https://spacevim.org/layers/VersionControl/
+ autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
- chat:                 not loaded          https://spacevim.org/layers/chat/
+ checkers:                 loaded          https://spacevim.org/layers/checkers/
- chinese:              not loaded          https://spacevim.org/layers/chinese/
- colorscheme:          not loaded          https://spacevim.org/layers/colorscheme/
+ core#banner:              loaded          https://spacevim.org/layers/core/banner/
+ core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
+ core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
+ core:                     loaded          https://spacevim.org/layers/core/
- cscope:               not loaded          https://spacevim.org/layers/cscope/
- ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
- ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
- debug:                not loaded          https://spacevim.org/layers/debug/
- denite:               not loaded          https://spacevim.org/layers/denite/
+ edit:                     loaded          https://spacevim.org/layers/edit/
- exprfold:             not loaded          no exists
- floobits:             not loaded          https://spacevim.org/layers/floobits/
- foldsearch:           not loaded          https://spacevim.org/layers/foldsearch/
+ format:                   loaded          https://spacevim.org/layers/format/
- fuzzy:                not loaded          no exists
- fzf:                  not loaded          https://spacevim.org/layers/fzf/
- games:                not loaded          no exists
- git:                  not loaded          https://spacevim.org/layers/git/
- github:               not loaded          https://spacevim.org/layers/github/
- gtags:                not loaded          https://spacevim.org/layers/gtags/
- incsearch:            not loaded          no exists
- indentmove:           not loaded          no exists
- japanese:             not loaded          https://spacevim.org/layers/japanese/
- lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
- lang#actionscript:    not loaded          https://spacevim.org/layers/lang/actionscript/
- lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
- lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
- lang#aspectj:         not loaded          https://spacevim.org/layers/lang/aspectj/
- lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
- lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
- lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
- lang#c:               not loaded          https://spacevim.org/layers/lang/c/
- lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
- lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
- lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
- lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
- lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
- lang#d:               not loaded          https://spacevim.org/layers/lang/d/
- lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
- lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
- lang#eiffel:          not loaded          https://spacevim.org/layers/lang/eiffel/
- lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
- lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
- lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
- lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
- lang#factor:          not loaded          no exists
- lang#forth:           not loaded          no exists
- lang#fortran:         not loaded          https://spacevim.org/layers/lang/fortran/
- lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
- lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
- lang#go:              not loaded          https://spacevim.org/layers/lang/go/
- lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
- lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
- lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
- lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
- lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
- lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
- lang#html:            not loaded          https://spacevim.org/layers/lang/html/
- lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
- lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
- lang#io:              not loaded          https://spacevim.org/layers/lang/io/
- lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
- lang#j:               not loaded          https://spacevim.org/layers/lang/j/
- lang#janet:           not loaded          https://spacevim.org/layers/lang/janet/
- lang#java:            not loaded          https://spacevim.org/layers/lang/java/
- lang#javascript:      not loaded          https://spacevim.org/layers/lang/javascript/
- lang#json:            not loaded          no exists
- lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
- lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
- lang#lasso:           not loaded          https://spacevim.org/layers/lang/lasso/
- lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
- lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
- lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
- lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
- lang#markdown:        not loaded          https://spacevim.org/layers/lang/markdown/
- lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
- lang#moonscript:      not loaded          https://spacevim.org/layers/lang/moonscript/
- lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
- lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
- lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
- lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
- lang#pascal:          not loaded          https://spacevim.org/layers/lang/pascal/
- lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
- lang#php:             not loaded          https://spacevim.org/layers/lang/php/
- lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
- lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
- lang#povray:          not loaded          https://spacevim.org/layers/lang/povray/
- lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
- lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
- lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
- lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
- lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
- lang#python:          not loaded          https://spacevim.org/layers/lang/python/
- lang#r:               not loaded          https://spacevim.org/layers/lang/r/
- lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
- lang#reason:          not loaded          https://spacevim.org/layers/lang/reason/
- lang#red:             not loaded          https://spacevim.org/layers/lang/red/
- lang#rescript:        not loaded          https://spacevim.org/layers/lang/rescript/
- lang#ring:            not loaded          https://spacevim.org/layers/lang/ring/
- lang#rst:             not loaded          https://spacevim.org/layers/lang/rst/
- lang#ruby:            not loaded          https://spacevim.org/layers/lang/ruby/
- lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
- lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
- lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
- lang#sh:              not loaded          https://spacevim.org/layers/lang/sh/
- lang#slim:            not loaded          https://spacevim.org/layers/lang/slim/
- lang#sml:             not loaded          https://spacevim.org/layers/lang/sml/
- lang#solidity:        not loaded          no exists
- lang#sql:             not loaded          no exists
- lang#supercollider:   not loaded          no exists
- lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
- lang#swig:            not loaded          no exists
- lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
- lang#toml:            not loaded          https://spacevim.org/layers/lang/toml/
- lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
- lang#v:               not loaded          https://spacevim.org/layers/lang/v/
- lang#vbnet:           not loaded          https://spacevim.org/layers/lang/vbnet/
- lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
- lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
- lang#wdl:             not loaded          no exists
- lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
- lang#xml:             not loaded          https://spacevim.org/layers/lang/xml/
- lang#xquery:          not loaded          no exists
- lang#zig:             not loaded          https://spacevim.org/layers/lang/zig/
- leaderf:              not loaded          https://spacevim.org/layers/leaderf/
- lsp:                  not loaded          https://spacevim.org/layers/language-server-protocol/
- mail:                 not loaded          no exists
- operator:             not loaded          no exists
- org:                  not loaded          no exists
- shell:                not loaded          https://spacevim.org/layers/shell/
- sudo:                 not loaded          https://spacevim.org/layers/sudo/
- test:                 not loaded          https://spacevim.org/layers/test/
- tmux:                 not loaded          https://spacevim.org/layers/tmux/
- tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
- tools#mpv:            not loaded          https://spacevim.org/layers/tools/mpv/
- tools#screensaver:    not loaded          no exists
- tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
- tools:                not loaded          https://spacevim.org/layers/tools/
+ ui:                       loaded          https://spacevim.org/layers/ui/
- unite:                not loaded          https://spacevim.org/layers/unite/
- vim:                  not loaded          no exists

## Screenshots

![image](https://user-images.githubusercontent.com/5350867/113815591-0178ee80-97a6-11eb-944b-1cd17aed44b5.png)

**Comment by wsdjeg** [comment]
Please post the debug info via `SPC h I` not layer list `SPC h l`

**Comment by xylinkun** [comment]
> Please post the debug info via `SPC h I` not layer list `SPC h l`


## Expected behavior, english is recommend

## Environment Information

- OS: windows
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 7577abce

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\clinku\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\clinku\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'open-browser.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\Users\clinku\scoop\apps\neovim\current\bin\nvim.exe)
version: 800
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:47:36] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [13:47:36] [ Info ] find local conf: C:/Users/clinku/.SpaceVim.d/init.toml
[ SpaceVim ] [13:47:36] [ Info ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [13:47:36] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [13:47:36] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [13:47:37] [ Info ] try to open SpaceVim welcome page
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

**Comment by xylinkun** [comment]
![image](https://user-images.githubusercontent.com/5350867/114293969-60ec3c80-9acd-11eb-8c28-1d0aa8e96272.png)
What's the character here? I cannot copy the string after it to the clipboard unless it's removed.

**Comment by wsdjeg** [comment]
> I cannot copy the string after it to the clipboard unless it's removed.

this is a bug of default clipboard command in neovim-qt.

**Comment by wsdjeg** [comment]
```
- OS: windows
- vim version: -
- neovim version: 0.5.0
- SpaceVim version: 1.7.0-dev
- SpaceVim status: fd334cf6
```

it works for me.

**Comment by cmdrrobin** [comment]
Similar issues, different error:

```
Error detected while processing function <SNR>60_update_search_index[16]..SpaceVim#layers#core#statusline#toggle_section[22]..SpaceVim#layers#core#statusline#get[203]..<SNR>35_active:
line   15:
E121: Undefined variable: s:lsep
E116: Invalid arguments for function 113
E15: Invalid expression: s:STATUSLINE.build(lsec, rsec, s:lsep, s:rsep, fname, tag, 'SpaceVim_statusline_a', 'SpaceVim_statusline_b', 'SpaceVim_statusline_c', 'SpaceVim_statusline_z', winwidth(winnr()))
Press ENTER or type command to continue
```

```
<!-- please remove the issue template when request for a feature -->
## Expected behavior, english is recommend

## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: c5e691c3


```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'bootstrap#after'
  bootstrap_before = 'bootstrap#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['pearofducks/ansible-vim', {'name': 'pearofducks/ansible-vim', 'merged': 0, 'overwrite': 1}], ['ryanoasis/vim-devicons', {'name': 'ryanoasis/vim-devicons', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/Users/robin/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 1
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/robin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'slant'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'search status', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=0
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#puppet"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="incsearch"
[[layers]]
  name="shell"
  default_height=30
  default_position='bottom'
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.4.4_2/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:13:25] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [12:13:25] [ Info ] find local conf: /Users/robin/.SpaceVim.d/init.toml
[ SpaceVim ] [12:13:25] [ Info ] generate local conf: /Users/robin/.cache//SpaceVim/conf/_Users_robin__SpaceVim_d_init_toml.json
[ SpaceVim ] [12:13:25] [ Info ] start to apply config [local]
[ SpaceVim ] [12:13:25] [ Info ] Initializing bootstrap#before
[ SpaceVim ] [12:13:25] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [12:13:25] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:13:25] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:13:26] [ Info ] try to open SpaceVim welcome page
[   rooter ] [12:13:26] [ Info ] Load projects cache from: /Users/robin/.cache/SpaceVim/projects.json
[ SpaceVim ] [12:13:26] [ Info ] Initializing bootstrap#after
[   rooter ] [12:13:28] [ Info ] Start to find root for: /Users/robin/.SpaceVim.d/init.toml
[   rooter ] [12:13:28] [ Info ] buffer name: /Users/robin/.SpaceVim.d/init.toml
[   rooter ] [12:13:28] [ Info ] same as current directory, no need to change.
[   rooter ] [12:13:59] [ Info ] Start to find root for: /private/var/folders/5z/yx_09z6s4wg5v3ckyyqwvntw0000gn/T/nvimiv9uwl/4/issue_report.md
[   rooter ] [12:13:59] [ Info ] buffer name: /var/folders/5z/yx_09z6s4wg5v3ckyyqwvntw0000gn/T/nvimiv9uwl/4/issue_report.md
[   rooter ] [12:13:59] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
```
