### ISSUE TITLE
Defx: failed to paste or move file

### ISSUE THREAD

**Issue by mistical2008** [wsdjeg/SpaceVim#4205]
## Expected behavior, english is required
When I yank file by `c` or `yY` and paste with `P` than it must be pasted to destination under the cursor.

## The reproduce ways from Vim starting (Required!)
**Case 1**
1. Open the `Defx` file tree by `[SPC]fot`
2. Copy a file by `c`
3. Move a cursor to destination
4. Press `P`
5. Shows err message: `Failed to paste`

**Case 2**
1. Open the `Defx` file tree by `[SPC]fot`
2. Copy a file by `yY`
3. Move a cursor to destination
4. Press `P`
5. Shows python err message output: https://pastebin.com/HgFTskZs
6. Press `P` second time
7. File pasted with an error message: `Failed to paste`

**Case 3**
1. Open the `Defx` file tree by `[SPC]fot`
2. Start moving a file by `m`
3. Move a cursor to destination
4. Press `P`
5. Shows err message: `Failed to paste`

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: d2039580

```
On branch master
Your branch is ahead of 'origin/master' by 14 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   bundle/vim-snippets/UltiSnips/javascript.snippets

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	bundle/vim-snippets/UltiSnips/javascript_snippets.py
	bundle/vim-snippets/UltiSnips/vimsnippets.py
	coc-settings.json
	spell/

no changes added to commit (use "git add" and/or "git commit -a")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['https://gitlab.com/dbeniamine/todo.txt-vim', {'repo': 'https://gitlab.com/dbeniamine/todo.txt-vim', 'merged': 0, 'overwrite': 1}], ['kovetskiy/sxhkd-vim', {'repo': 'kovetskiy/sxhkd-vim', 'merged': 0, 'overwrite': 1}], ['liuchengxu/vista.vim', {'repo': 'liuchengxu/vista.vim', 'merged': 0, 'overwrite': 1}], ['michal-h21/vim-zettel', {'repo': 'michal-h21/vim-zettel', 'merged': 0, 'overwrite': 1}], ['vimwiki/vimwiki', {'repo': 'vimwiki/vimwiki', 'merged': 0, 'overwrite': 1}], ['junegunn/fzf.vim', {'repo': 'junegunn/fzf.vim', 'merged': 0, 'overwrite': 1}], ['dbeniamine/cheat.sh-vim', {'repo': 'dbeniamine/cheat.sh-vim', 'merged': 0, 'overwrite': 1}], ['wlemuel/vim-tldr', {'repo': 'wlemuel/vim-tldr', 'merged': 0, 'overwrite': 1}], ['sheerun/vim-polyglot', {'repo': 'sheerun/vim-polyglot', 'merged': 0, 'overwrite': 1}], ['styled-components/vim-styled-components', {'repo': 'styled-components/vim-styled-components', 'merged': 0, 'overwrite': 1}], ['kristijanhusak/vim-js-file-import', {'repo': 'kristijanhusak/vim-js-file-import', 'merged': 0, 'overwrite': 1}], ['kristijanhusak/defx-git', {'loadconf': 1, 'repo': 'kristijanhusak/defx-git', 'merged': 0, 'hook_source': 'call SpaceVim#util#loadConfig(''plugins/defx-git.vim'')', 'overwrite': 1}], ['dense-analysis/ale', {'repo': 'dense-analysis/ale', 'merged': 0, 'overwrite': 1}], ['nicwest/vim-camelsnek', {'repo': 'nicwest/vim-camelsnek', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/evgeniy/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['vnote']
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/evgeniy/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'emmet-vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', 'Cargo.toml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
  lint_engine='ale'
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=21
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="ctrlp"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="VersionControl"
  enable-gtm-status=1
[[layers]]
  name="github"
[[layers]]
  name="tools"
[[layers]]
  name="tmux"
[[layers]]
  name="test"
[[layers]]
  name="sudo"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#python"
[[layers]]
  name="unite"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#html"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:48:07] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [11:48:07] [ Info ] find local conf: /home/evgeniy/.SpaceVim.d/init.toml
[ SpaceVim ] [11:48:07] [ Info ] loading cached local conf: /home/evgeniy/.cache//SpaceVim/conf/_home_evgeniy__SpaceVim_d_init_toml.json
[ SpaceVim ] [11:48:07] [ Info ] start to apply config [local]
[ SpaceVim ] [11:48:07] [ Warn ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [11:48:07] [ Warn ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [11:48:07] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:48:07] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:48:08] [ Info ] try to open SpaceVim welcome page
[   rooter ] [11:48:08] [ Info ] Load projects cache from: /home/evgeniy/.cache/SpaceVim/projects.json
[   rooter ] [11:48:08] [ Info ] Start to find root for: /home/evgeniy/[defx] -0
[   rooter ] [11:48:08] [ Info ] buffer name: [defx] -0
[   rooter ] [11:48:08] [ Info ] same as current directory, no need to change.
[   rooter ] [11:48:08] [ Info ] Start to find root for: /home/evgeniy/
[   rooter ] [11:48:08] [ Info ] buffer name: No Name
[   rooter ] [11:48:08] [ Info ] same as current directory, no need to change.
[   rooter ] [11:48:09] [ Info ] buffer name: [defx] -0
[   rooter ] [11:48:09] [ Info ] same as current directory, no need to change.
[   rooter ] [11:52:50] [ Info ] buffer name: No Name
[   rooter ] [11:52:50] [ Info ] same as current directory, no need to change.
[   rooter ] [11:52:50] [ Info ] Start to find root for: /home/evgeniy/tmp/new-app/src/App.js
[   rooter ] [11:52:50] [ Info ] buffer name: tmp/new-app/src/App.js
[   rooter ] [11:52:50] [ Info ] same as current directory, no need to change.
[   rooter ] [11:52:54] [ Info ] buffer name: [defx] -0
[   rooter ] [11:52:54] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:26] [ Info ] buffer name: tmp/new-app/src/App.js
[   rooter ] [11:53:26] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:36] [ Info ] Start to find root for: /tmp/nvimjb49zk/15/issue_report.md
[   rooter ] [11:53:36] [ Info ] buffer name: /tmp/nvimjb49zk/15/issue_report.md
[   rooter ] [11:53:36] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots
https://asciinema.org/a/rk2hWq9bWyYtsuD2i9YzvJGY4
