### ISSUE TITLE
ma is not work when use tools layers

### ISSUE THREAD

**Issue by nicklogshow** [wsdjeg/SpaceVim#4216]
## Environment Information

- OS: mac
- vim version: 8.2.2681
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 172579a2

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'completor'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/q/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 1
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h18'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/q/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-bookmarks'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="fzf"
[[layers]]
  name="incsearch"
[[layers]]
  name="tools"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: Vim(/Applications/MacVim.app/Contents/MacOS/Vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gtk, or build from sources.
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [20:52:17] [ Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [20:52:17] [ Info ] find local conf: /Users/q/.SpaceVim.d/init.toml
[ SpaceVim ] [20:52:17] [ Info ] loading cached local conf: /Users/q/.cache//SpaceVim/conf/_Users_q__SpaceVim_d_init_toml.json
[ SpaceVim ] [20:52:17] [ Info ] start to apply config [local]
[ SpaceVim ] [20:52:17] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [20:52:17] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [20:52:17] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [20:52:18] [ Info ] try to open SpaceVim welcome page
[   rooter ] [20:52:18] [ Info ] Load projects cache from: /Users/q/.cache/SpaceVim/projects.json
[   rooter ] [20:52:20] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:20] [ Info ] buffer name: No Name
[   rooter ] [20:52:20] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:52:20] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [20:52:21] [ Info ] close float statusline winid:1004
[   rooter ] [20:52:21] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:21] [ Info ] buffer name: No Name
[   rooter ] [20:52:21] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:52:21] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [20:52:28] [ Info ] close float statusline winid:1006
[   rooter ] [20:52:28] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:28] [ Info ] buffer name: No Name
[   rooter ] [20:52:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:52:28] [ Info ] key binding guide float statusline winid:1008
[ SpaceVim ] [20:52:30] [ Info ] close float statusline winid:1008
[   rooter ] [20:52:38] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:38] [ Info ] buffer name: No Name
[   rooter ] [20:52:38] [ Info ] same as current directory, no need to change.
[   rooter ] [20:52:38] [ Info ] Start to find root for: /Users/q/[unite] - default
[   rooter ] [20:52:38] [ Info ] buffer name: [unite] - default
[   rooter ] [20:52:38] [ Info ] same as current directory, no need to change.
[   rooter ] [20:52:42] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:42] [ Info ] buffer name: No Name
[   rooter ] [20:52:42] [ Info ] same as current directory, no need to change.
[   rooter ] [20:52:45] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:45] [ Info ] buffer name: No Name
[   rooter ] [20:52:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:52:45] [ Info ] key binding guide float statusline winid:1011
[ SpaceVim ] [20:52:47] [ Info ] close float statusline winid:1011
[   rooter ] [20:52:47] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:47] [ Info ] buffer name: No Name
[   rooter ] [20:52:47] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:52:47] [ Info ] key binding guide float statusline winid:1013
[ SpaceVim ] [20:52:53] [ Info ] close float statusline winid:1013
[   rooter ] [20:52:53] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:52:53] [ Info ] buffer name: No Name
[   rooter ] [20:52:53] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:52:53] [ Info ] key binding guide float statusline winid:1015
[ SpaceVim ] [20:52:54] [ Info ] close float statusline winid:1015
[   rooter ] [20:53:09] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:53:09] [ Info ] buffer name: No Name
[   rooter ] [20:53:09] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:53:09] [ Info ] key binding guide float statusline winid:1017
[ SpaceVim ] [20:53:09] [ Info ] close float statusline winid:1017
[   rooter ] [20:53:20] [ Info ] buffer name: [unite] - default
[   rooter ] [20:53:20] [ Info ] same as current directory, no need to change.
[   rooter ] [20:53:25] [ Info ] buffer name: No Name
[   rooter ] [20:53:25] [ Info ] same as current directory, no need to change.
[   rooter ] [20:53:35] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:53:35] [ Info ] buffer name: No Name
[   rooter ] [20:53:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:53:35] [ Info ] key binding guide float statusline winid:1020
[ SpaceVim ] [20:53:40] [ Info ] close float statusline winid:1020
[   rooter ] [20:53:45] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:53:45] [ Info ] buffer name: No Name
[   rooter ] [20:53:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:53:45] [ Info ] key binding guide float statusline winid:1022
[ SpaceVim ] [20:53:48] [ Info ] close float statusline winid:1022
[   rooter ] [20:53:48] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:53:48] [ Info ] buffer name: No Name
[   rooter ] [20:53:48] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:53:48] [ Info ] key binding guide float statusline winid:1024
[ SpaceVim ] [20:53:54] [ Info ] close float statusline winid:1024
[   rooter ] [20:53:54] [ Info ] Start to find root for: /Users/q/vimfiler:default
[   rooter ] [20:53:54] [ Info ] buffer name: vimfiler:default
[   rooter ] [20:53:54] [ Info ] same as current directory, no need to change.
[   rooter ] [20:53:54] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:53:54] [ Info ] buffer name: No Name
[   rooter ] [20:53:54] [ Info ] same as current directory, no need to change.
[   rooter ] [20:53:58] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:53:58] [ Info ] buffer name: No Name
[   rooter ] [20:53:58] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:53:59] [ Info ] key binding guide float statusline winid:1027
[ SpaceVim ] [20:54:07] [ Info ] close float statusline winid:1027
[   rooter ] [20:54:07] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:54:07] [ Info ] buffer name: No Name
[   rooter ] [20:54:07] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [20:54:07] [ Info ] key binding guide float statusline winid:1029
[ SpaceVim ] [20:54:11] [ Info ] close float statusline winid:1029
[   rooter ] [20:54:11] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:54:11] [ Info ] buffer name: No Name
[   rooter ] [20:54:11] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:11] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:54:11] [ Info ] buffer name: No Name
[   rooter ] [20:54:11] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:27] [ Info ] buffer name: No Name
[   rooter ] [20:54:27] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:27] [ Info ] buffer name: No Name
[   rooter ] [20:54:27] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:28] [ Info ] buffer name: vimfiler:default
[   rooter ] [20:54:28] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:29] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:54:29] [ Info ] buffer name: No Name
[   rooter ] [20:54:29] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:29] [ Info ] Start to find root for: /Users/q/[unite] - action
[   rooter ] [20:54:29] [ Info ] buffer name: [unite] - action
[   rooter ] [20:54:29] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:31] [ Info ] buffer name: vimfiler:default
[   rooter ] [20:54:31] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:34] [ Info ] buffer name: No Name
[   rooter ] [20:54:34] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:35] [ Info ] buffer name: [unite] - default
[   rooter ] [20:54:35] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:36] [ Info ] buffer name: No Name
[   rooter ] [20:54:36] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:37] [ Info ] buffer name: [unite] - default
[   rooter ] [20:54:37] [ Info ] same as current directory, no need to change.
[   rooter ] [20:54:52] [ Info ] buffer name: No Name
[   rooter ] [20:54:52] [ Info ] same as current directory, no need to change.
[   rooter ] [20:56:07] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:56:07] [ Info ] buffer name: No Name
[   rooter ] [20:56:07] [ Info ] same as current directory, no need to change.
[   rooter ] [20:56:32] [ Info ] buffer name: [unite] - default
[   rooter ] [20:56:32] [ Info ] same as current directory, no need to change.
[   rooter ] [20:56:38] [ Info ] buffer name: No Name
[   rooter ] [20:56:38] [ Info ] same as current directory, no need to change.
[   rooter ] [20:56:45] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:56:45] [ Info ] buffer name: No Name
[   rooter ] [20:56:45] [ Info ] same as current directory, no need to change.
[   rooter ] [20:57:36] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:57:36] [ Info ] buffer name: No Name
[   rooter ] [20:57:36] [ Info ] same as current directory, no need to change.
[   rooter ] [20:58:04] [ Info ] buffer name: No Name
[   rooter ] [20:58:04] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:05] [ Info ] buffer name: [unite] - default
[   rooter ] [20:59:05] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:07] [ Info ] buffer name: No Name
[   rooter ] [20:59:07] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:08] [ Info ] buffer name: No Name
[   rooter ] [20:59:08] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:10] [ Info ] buffer name: vimfiler:default
[   rooter ] [20:59:10] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:10] [ Info ] buffer name: No Name
[   rooter ] [20:59:10] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:11] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:59:11] [ Info ] buffer name: No Name
[   rooter ] [20:59:11] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:12] [ Info ] Start to find root for: /Users/q/
[   rooter ] [20:59:12] [ Info ] buffer name: No Name
[   rooter ] [20:59:12] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:13] [ Info ] buffer name: No Name
[   rooter ] [20:59:13] [ Info ] same as current directory, no need to change.
[  FlyGrep ] [20:59:16] [ Info ] FlyGrep startting ===========================
[  FlyGrep ] [20:59:16] [ Info ]    executable    : grep
[  FlyGrep ] [20:59:16] [ Info ]    option        : ['-inHr']
[  FlyGrep ] [20:59:16] [ Info ]    r_option      : ['.']
[  FlyGrep ] [20:59:16] [ Info ]    files         : ''
[  FlyGrep ] [20:59:16] [ Info ]    dir           : ''
[  FlyGrep ] [20:59:16] [ Info ]    ignore_case   : ['-i']
[  FlyGrep ] [20:59:16] [ Info ]    smart_case    : []
[  FlyGrep ] [20:59:16] [ Info ]    expr opt      : ['-e']
[  FlyGrep ] [20:59:16] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\v:q
[  FlyGrep ] [20:59:16] [ Info ] grep cmd: ['grep', '-inHr', '-e', ':q', '.']
[  FlyGrep ] [20:59:16] [ Info ] flygrep job id is: 1
[  FlyGrep ] [20:59:17] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\v:qq
[  FlyGrep ] [20:59:17] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\v:qqq
[  FlyGrep ] [20:59:18] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\v:qqqq
[  FlyGrep ] [20:59:18] [ Info ] grep cmd: ['grep', '-inHr', '-e', ':qqqq', '.']
[  FlyGrep ] [20:59:18] [ Info ] flygrep job id is: 1
[  FlyGrep ] [20:59:18] [ Info ] FlyGrep ending    ===========================
[   rooter ] [20:59:19] [ Info ] buffer name: No Name
[   rooter ] [20:59:19] [ Info ] same as current directory, no need to change.
[   rooter ] [20:59:43] [ Info ] buffer name: [unite] - default
[   rooter ] [20:59:43] [ Info ] same as current directory, no need to change.
[   rooter ] [21:00:41] [ Info ] buffer name: No Name
[   rooter ] [21:00:41] [ Info ] same as current directory, no need to change.
[   rooter ] [21:00:45] [ Info ] Start to find root for: /private/var/folders/6j/74b1ng8n7f7gkp4cq1bhqfxh0000gn/T/vZ9Fsb2/9/issue_report.md
[   rooter ] [21:00:45] [ Info ] buffer name: /var/folders/6j/74b1ng8n7f7gkp4cq1bhqfxh0000gn/T/vZ9Fsb2/9/issue_report.md
[   rooter ] [21:00:45] [ Info ] same as current directory, no need to change.
```
</details>

when i type ma, it show me a unite window. what i need is tools feature that show me all mark list
m a	Show list of all bookmarks

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
