### ISSUE TITLE
Error when toggle of syntax and spell checking

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4224]
## Expected behavior, english is required

Toggle of syntax checker and spelling checker should work.

## The reproduce ways from Vim starting (Required!)

Hit `SPC t s` or `SPC t S` and get an error message:

```
Error detected while processing function SpaceVim#layers#core#statusline#toggle_mode:
line    9:
E117: Unknown function: function('<SNR>27_toggle_syntax_checker') 
```
```
Error detected while processing function SpaceVim#layers#core#statusline#toggle_mode:
line    9:
E117: Unknown function: function('<SNR>35_toggle_spell_check')
```

## Debug info

Please press <kbd>SPC h I</kbd>, debug info will be put into clipboard, then paste all content below.

## Environment Information

- OS: linux
- vim version: 8.2.716
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 3a327235

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 0
  checkinstall = 1
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/mgedmin/python-imports.vim.git', {'repo': 'https://github.com/mgedmin/python-imports.vim.git', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'JetBrainsMono Nerd Font Mono, Thin 11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-debug'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#python"
  python_file_head=[]
  enabled_linters=['pylint']
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="debug"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim(/usr/bin/vim.gtk3)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:04:15] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [17:04:15] [ Info ] find local conf: /home/jacky/.SpaceVim.d/init.toml
[ SpaceVim ] [17:04:15] [ Info ] loading cached local conf: /home/jacky/.cache//SpaceVim/conf/_home_jacky__SpaceVim_d_init_toml.json
[ SpaceVim ] [17:04:15] [ Info ] start to apply config [local]
[ SpaceVim ] [17:04:15] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [17:04:15] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:04:15] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [17:04:15] [ Info ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[   rooter ] [17:04:16] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:04:16] [ Info ] buffer name: No Name
[   rooter ] [17:04:16] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:04:16] [ Info ] try to open SpaceVim welcome page
[   rooter ] [17:04:16] [ Info ] buffer name: No Name
[   rooter ] [17:04:16] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:27] [ Info ] Start to find root for: /home/jacky/vimfiler:default
[   rooter ] [17:04:27] [ Info ] buffer name: vimfiler:default
[   rooter ] [17:04:27] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:38] [ Info ] buffer name: No Name
[   rooter ] [17:04:38] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:38] [ Info ] buffer name: vimfiler:default
[   rooter ] [17:04:38] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:38] [ Info ] buffer name: No Name
[   rooter ] [17:04:38] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:38] [ Info ] Start to find root for: /home/jacky/.vimspector.json
[   rooter ] [17:04:38] [ Info ] buffer name: /home/jacky/.vimspector.json
[   rooter ] [17:04:38] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:39] [ Info ] buffer name: vimfiler:default
[   rooter ] [17:04:39] [ Info ] same as current directory, no need to change.
[   rooter ] [17:04:39] [ Info ] buffer name: /home/jacky/.vimspector.json
[   rooter ] [17:04:39] [ Info ] same as current directory, no need to change.
[   rooter ] [17:06:02] [ Info ] Start to find root for: /home/jacky/.vimspector.json
[   rooter ] [17:06:02] [ Info ] buffer name: .vimspector.json
[   rooter ] [17:06:02] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:10:40] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [17:10:48] [ Info ] try to call func of mode:syntax-checking
[   rooter ] [17:10:53] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:10:53] [ Info ] buffer name: No Name
[   rooter ] [17:10:53] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:10:53] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [17:10:54] [ Info ] close float statusline winid:1004
[   rooter ] [17:10:54] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:10:54] [ Info ] buffer name: No Name
[   rooter ] [17:10:54] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:10:54] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [17:10:55] [ Info ] close float statusline winid:1006
[ SpaceVim ] [17:10:55] [ Info ] try to call func of mode:syntax-checking
[   rooter ] [17:12:28] [ Info ] Start to find root for: /home/jacky/Documents/proj/2104_Eurowatts/launcher.py
[   rooter ] [17:12:28] [ Info ] buffer name: Documents/proj/2104_Eurowatts/launcher.py
[   rooter ] [17:12:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:12:29] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [17:12:31] [ Info ] try to call func of mode:syntax-checking
[   rooter ] [17:12:34] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:12:34] [ Info ] buffer name: No Name
[   rooter ] [17:12:34] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:12:34] [ Info ] key binding guide float statusline winid:1008
[ SpaceVim ] [17:12:35] [ Info ] close float statusline winid:1008
[   rooter ] [17:12:44] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:12:44] [ Info ] buffer name: No Name
[   rooter ] [17:12:44] [ Info ] same as current directory, no need to change.
[   rooter ] [17:12:44] [ Info ] buffer name: Documents/proj/2104_Eurowatts/launcher.py
[   rooter ] [17:12:44] [ Info ] same as current directory, no need to change.
[   rooter ] [17:12:55] [ Info ] Start to find root for: /home/jacky/Documents/proj/2104_Eurowatts/launcher.py
[   rooter ] [17:12:55] [ Info ] buffer name: Documents/proj/2104_Eurowatts/launcher.py
[   rooter ] [17:12:55] [ Info ] same as current directory, no need to change.
[   rooter ] [17:12:55] [ Info ] buffer name: .vimspector.json
[   rooter ] [17:12:55] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:13:06] [ Info ] try to call func of mode:spell-checking
[   rooter ] [17:13:15] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:13:15] [ Info ] buffer name: No Name
[   rooter ] [17:13:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:13:15] [ Info ] key binding guide float statusline winid:1011
[ SpaceVim ] [17:13:15] [ Info ] close float statusline winid:1011
[   rooter ] [17:13:17] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:13:17] [ Info ] buffer name: No Name
[   rooter ] [17:13:17] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:13:17] [ Info ] key binding guide float statusline winid:1013
[ SpaceVim ] [17:13:17] [ Info ] close float statusline winid:1013
[ SpaceVim ] [17:13:21] [ Info ] try to call func of mode:spell-checking
[   rooter ] [17:13:23] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:13:23] [ Info ] buffer name: No Name
[   rooter ] [17:13:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:13:23] [ Info ] key binding guide float statusline winid:1015
[ SpaceVim ] [17:13:23] [ Info ] close float statusline winid:1015
[ SpaceVim ] [17:13:45] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [17:13:45] [ Info ] no func found for mode:fill-column-indicator
[   rooter ] [17:14:10] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:14:10] [ Info ] buffer name: No Name
[   rooter ] [17:14:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:14:10] [ Info ] key binding guide float statusline winid:1017
[ SpaceVim ] [17:14:10] [ Info ] close float statusline winid:1017
[   rooter ] [17:14:10] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:14:10] [ Info ] buffer name: No Name
[   rooter ] [17:14:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:14:10] [ Info ] key binding guide float statusline winid:1019
[ SpaceVim ] [17:14:10] [ Info ] close float statusline winid:1019
[ SpaceVim ] [17:14:10] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [17:14:10] [ Info ] no func found for mode:fill-column-indicator
[   rooter ] [17:14:12] [ Info ] Start to find root for: /home/jacky/.vimspector.json
[   rooter ] [17:14:12] [ Info ] buffer name: .vimspector.json
[   rooter ] [17:14:12] [ Info ] same as current directory, no need to change.
[   rooter ] [17:14:52] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:14:52] [ Info ] buffer name: No Name
[   rooter ] [17:14:52] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:14:52] [ Info ] key binding guide float statusline winid:1021
[ SpaceVim ] [17:14:52] [ Info ] close float statusline winid:1021
[   rooter ] [17:15:22] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:15:22] [ Info ] buffer name: No Name
[   rooter ] [17:15:22] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:15:23] [ Info ] key binding guide float statusline winid:1023
[ SpaceVim ] [17:15:23] [ Info ] close float statusline winid:1023
[   rooter ] [17:15:23] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [17:15:23] [ Info ] buffer name: No Name
[   rooter ] [17:15:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [17:15:23] [ Info ] key binding guide float statusline winid:1025
[ SpaceVim ] [17:15:23] [ Info ] close float statusline winid:1025
[ SpaceVim ] [17:15:24] [ Info ] try to call func of mode:spell-checking
[   rooter ] [17:17:18] [ Info ] Start to find root for: /tmp/vhvy7hf/13/issue_report.md
[   rooter ] [17:17:18] [ Info ] buffer name: /tmp/vhvy7hf/13/issue_report.md
[   rooter ] [17:17:18] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
