### ISSUE TITLE
markdown-preview.nvim: Building failed.

### ISSUE THREAD

**Issue by pipiTan** [wsdjeg/SpaceVim#4234]
## Environment Information

- OS: mac
- vim version: -
- neovim version: 0.5.0
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 1fe6a3da

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['psliwka/vim-smoothie', {'repo': 'psliwka/vim-smoothie', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/Users/zaintan/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/zaintan/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'markdown-preview.nvim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#scheme"
[[layers]]
  name="lang#markdown"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/Users/zaintan/nvim/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:24:10] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [00:24:10] [ Info ] find local conf: /Users/zaintan/.SpaceVim.d/init.toml
[ SpaceVim ] [00:24:10] [ Info ] loading cached local conf: /Users/zaintan/.cache//SpaceVim/conf/_Users_zaintan__SpaceVim_d_init_toml.json
[ SpaceVim ] [00:24:10] [ Info ] start to apply config [local]
[ SpaceVim ] [00:24:10] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:24:11] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:24:11] [ Info ] try to open SpaceVim welcome page
[   rooter ] [00:24:11] [ Info ] Load projects cache from: /Users/zaintan/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:24:14] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [00:24:14] [ Info ] Start to find root for: /Users/zaintan/
[   rooter ] [00:24:14] [ Info ] buffer name: No Name
[   rooter ] [00:24:14] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [00:24:14] [ Info ] close float statusline winid:1004
[ SpaceVim ] [00:24:14] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [00:24:19] [ Info ] buffer name: No Name
[   rooter ] [00:24:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [00:24:19] [ Info ] close float statusline winid:1006
[   rooter ] [00:24:20] [ Info ] Start to find root for: /private/var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/2/issue_report.md
[   rooter ] [00:24:20] [ Info ] buffer name: /var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/2/issue_report.md
[   rooter ] [00:24:20] [ Info ] same as current directory, no need to change.
[   rooter ] [00:24:20] [ Info ] Start to find root for: /private/var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/2/issue_report.md
[   rooter ] [00:24:20] [ Info ] buffer name: /var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/2/issue_report.md
[   rooter ] [00:24:20] [ Info ] same as current directory, no need to change.
[   rooter ] [00:25:27] [ Info ] Start to find root for: /Users/zaintan/
[   rooter ] [00:25:27] [ Info ] buffer name: No Name
[   rooter ] [00:25:27] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [00:25:35] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 3
[   rooter ] [00:25:42] [ Info ] buffer name: /var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/2/issue_report.md
[   rooter ] [00:25:42] [ Info ] same as current directory, no need to change.
[   rooter ] [00:25:43] [ Info ] buffer name: No Name
[   rooter ] [00:25:43] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [00:25:43] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 2
[ SpaceVim ] [00:25:47] [ Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 1
[   rooter ] [00:26:09] [ Info ] Start to find root for: /private/var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/4/issue_report.md
[   rooter ] [00:26:09] [ Info ] buffer name: /var/folders/fs/6wsxvdfd7_d8zpjjq6q_hc900000gn/T/nvimymg8X9/4/issue_report.md
[   rooter ] [00:26:09] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots
![image](https://user-images.githubusercontent.com/18749923/116001438-043d6580-a627-11eb-8a08-fb1dbd07d004.png)

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
