### ISSUE TITLE
Toggle of statusline symbol of spell checking is inverted

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4252]
## Expected behavior, english is required

When activating spell checking with `[SPC]tS` the statusline symbol should appear.
When de-activating spell checking with `[SPC]tS` the statusline symbol should disappear.

## The reproduce ways from Vim starting (Required!)

Press `[SPC]tS` : when spell checking is enabled the statusline symbol is not present, when spell checking is disabled the statusline symbol is present.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.7.0-dev
- SpaceVim status: c5e691c3

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 0
  checkinstall = 1
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/mgedmin/python-imports.vim.git', {'repo': 'https://github.com/mgedmin/python-imports.vim.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/puremourning/vimspector.git', {'repo': 'https://github.com/puremourning/vimspector.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/ludovicchabant/vim-gutentags.git', {'repo': 'https://github.com/ludovicchabant/vim-gutentags.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/vim-scripts/argtextobj.vim', {'repo': 'https://github.com/vim-scripts/argtextobj.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'FiraCode Nerd Font Mono:h11:l'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Denite-sources'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left_sections = ['vcs', 'hunks']
  statusline_right_sections = ['cursorpos', 'input method', 'date', 'time']
  statusline_separator = 'slant'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:14:16] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [13:14:16] [ Info ] find local conf: /home/jacky/.SpaceVim.d/init.toml
[ SpaceVim ] [13:14:16] [ Info ] generate local conf: /home/jacky/.cache//SpaceVim/conf/_home_jacky__SpaceVim_d_init_toml.json
[ SpaceVim ] [13:14:16] [ Info ] start to apply config [local]
[ SpaceVim ] [13:14:16] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [13:14:16] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [13:14:16] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [13:14:16] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [13:14:16] [ Info ] try to call func of mode:spell-checking
[   rooter ] [13:14:16] [ Info ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[   rooter ] [13:14:16] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [13:14:16] [ Info ] Start to find root for: /home/jacky/
[   rooter ] [13:14:16] [ Info ] buffer name: No Name
[   rooter ] [13:14:16] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:14:16] [ Info ] try to open SpaceVim welcome page
[   rooter ] [13:14:16] [ Info ] buffer name: No Name
[   rooter ] [13:14:16] [ Info ] same as current directory, no need to change.
[   rooter ] [13:14:18] [ Info ] Start to find root for: /home/jacky/.SpaceVim.d/init.toml
[   rooter ] [13:14:18] [ Info ] buffer name: .SpaceVim.d/init.toml
[   rooter ] [13:14:18] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [13:14:26] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [13:14:28] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [13:14:29] [ Info ] try to call func of mode:spell-checking
[ SpaceVim ] [13:14:30] [ Info ] try to call func of mode:spell-checking
[ SpaceVim ] [13:17:16] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [13:17:17] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [13:17:19] [ Info ] try to call func of mode:spell-checking
[   rooter ] [13:19:48] [ Info ] Start to find root for: /tmp/nvimHa5YqO/1/issue_report.md
[   rooter ] [13:19:48] [ Info ] buffer name: /tmp/nvimHa5YqO/1/issue_report.md
[   rooter ] [13:19:48] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

Spell checking enabled: no statusline symbol

![image](https://user-images.githubusercontent.com/34267385/116996460-bd610700-acdb-11eb-933b-36ec5b614632.png)

Spell checking disabled: statusline symbol

![image](https://user-images.githubusercontent.com/34267385/116996505-cf42aa00-acdb-11eb-87cf-1aa2c2179d6f.png)
