### ISSUE TITLE
Error when using "SPC b b" get buffer

### ISSUE THREAD

**Issue by freephys** [wsdjeg/SpaceVim#4261]
## Expected behavior, english is required
Sth like shown in the link:
https://everettjf.gitbooks.io/spacevimtutorial/content/basic/4.html
## Debug inf
![Capture-SPC b b-buffer](https://user-images.githubusercontent.com/128408/117499642-1ed5df80-af41-11eb-92ac-79b3bc6ebdfe.JPG)

## Environment Information

- OS: linux
- vim version: 8.1.2269
- neovim version: -
- SpaceVim version: 1.7.0-dev
- SpaceVim status: 9a568151 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'neocomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/nshen/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/nshen/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-gitgutter'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.7.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  python_interpreter='/home/nshen/anaconda3/bin/python'
  format_on_save=1
  enabled_linters=['python', 'pylint']
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.nox)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:34:44] [ Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [14:34:44] [ Info ] find local conf: /home/nshen/.SpaceVim.d/init.toml
[ SpaceVim ] [14:34:44] [ Info ] loading cached local conf: /home/nshen/.cache//SpaceVim/conf/_home_nshen__SpaceVim_d_init_toml.json
[ SpaceVim ] [14:34:44] [ Info ] start to apply config [local]
[ SpaceVim ] [14:34:45] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [14:34:45] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [14:34:45] [ Info ] Load projects cache from: /home/nshen/.cache/SpaceVim/projects.json
[   rooter ] [14:34:45] [ Info ] Start to find root for: /home/nshen/
[   rooter ] [14:34:45] [ Info ] buffer name: No Name
[   rooter ] [14:34:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:34:45] [ Info ] try to open SpaceVim welcome page
[   rooter ] [14:34:45] [ Info ] buffer name: No Name
[   rooter ] [14:34:45] [ Info ] same as current directory, no need to change.
[   rooter ] [14:34:47] [ Info ] Start to find root for: /home/nshen/
[   rooter ] [14:34:47] [ Info ] buffer name: No Name
[   rooter ] [14:34:47] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:34:48] [ Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [14:34:48] [ Info ] close float statusline winid:1004
[   rooter ] [14:34:48] [ Info ] Start to find root for: /home/nshen/
[   rooter ] [14:34:48] [ Info ] buffer name: No Name
[   rooter ] [14:34:48] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [14:34:48] [ Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [14:34:48] [ Info ] close float statusline winid:1006
[   rooter ] [14:34:48] [ Info ] Start to find root for: /tmp/vb1gLPs/4/issue_report.md
[   rooter ] [14:34:48] [ Info ] buffer name: /tmp/vb1gLPs/4/issue_report.md
[   rooter ] [14:34:48] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
