### ISSUE TITLE
Use only 1 neomake window

### ISSUE THREAD

**Issue by bestouff** [wsdjeg/SpaceVim#4276]
When editing rust files, each file open its own neomake window, and saving a file only update its own neomake window.  
Would it be possible to only have one neomake window for all rust files of a project ?

**Comment by wsdjeg** [comment]
moved to google mail list.

**Comment by wsdjeg** [comment]
@bestouff I can not reprodce it, do you have reproduce step and screenshorts?

**Comment by bestouff** [comment]
Ok, with this config:
```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#rust"
  recommended-style = true
  format-autosave = true
```
and this in autoload:
```vim
function! myspacevim#after() abort
highlight Comment cterm=italic
endfunction
set wrap
```
Every file has its own neomake window when I save it:
![Capture d’écran de 2021-06-21 16-55-27](https://user-images.githubusercontent.com/1163188/122783243-adb07880-d2b1-11eb-9211-64d353f88ff5.png)
