### ISSUE TITLE
Find and Replace deletes text lines of words that expected to be replaced

### ISSUE THREAD

**Issue by forgoty** [wsdjeg/SpaceVim#4295]
## Expected behavior, english is recommend
While I do Find and Replace all the lines that have been found at flygrep are replaced to replace value.
## Actual behavior, english is recommend
While I do Find and Replace (SPC-s-/, {enter replace pattern}, Alt-r to enter replace mode, ESC to end editing, ESC to confirm) the editor removes everything that matches the search. Tested only on python layer
### Environment Information
OS: linux
vim version: -
neovim version: 0.4.4
SpaceVim version: 1.7.0
SpaceVim status: c7eb99d6bb405a81f4eeba835b2b653010a2dcec
### Config
```toml
# This is a basic configuration example for SpaceVim

# All SpaceVim options are below [options] snippet
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "doom-gruvbox-theme"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    guifont = "Hack:h10"
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    enable_statusline_mode = false
    filetree_direction = "left"

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

[[layers]]
  name = "lang#python"
  enabled_linters = ['flake8']
  python_file_head = []

[[layers]]
  name = "colorscheme"

[[layers]]
    name = "denite"

[[layers]]
  name = "checkers"
  show_cursor_error = true
  lint_on_the_fly = true
  lint_on_save = true
```

### Screenshots
Asciinema:
https://asciinema.org/a/KRhZ2nV2xi6NDbaes1CcJjPCP

**Comment by wsdjeg** [comment]
what is the debug info? you can get it by key binding `SPC h I`

**Comment by forgoty** [comment]
## Expected behavior, english is recommend

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.4.4
- SpaceVim version: 1.8.0-dev
- SpaceVim status: c7eb99d6


```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	colors/doom-gruvbox-theme.vim

nothing added to commit but untracked files present (use "git add" to track)
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'doom-gruvbox-theme'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['https://github.com/sheerun/vim-polyglot.git', {'repo': 'https://github.com/sheerun/vim-polyglot.git', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/nikita/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Hack:h10'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/nikita/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'fzf-neoyank'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
[[layers]]
  name="checkers"
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  python_file_head=['']
  enabled_linters=['flake8']
[[layers]]
  name="lang#go"
[[layers]]
  name="colorscheme"
[[layers]]
  name="fzf"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:40:50] [ Info ] Startup with argv: ['find_one.py']
[ SpaceVim ] [09:40:50] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [09:40:50] [ Info ] a:path is :~/.SpaceVim.d/
[ SpaceVim ] [09:40:50] [ Info ] a:path is :~/.SpaceVim.d/
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.SpaceVim.d/
[ SpaceVim ] [09:40:50] [ Info ] case three
[ SpaceVim ] [09:40:50] [ Info ] a:path is :~/.SpaceVim.d/
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.SpaceVim.d/
[ SpaceVim ] [09:40:50] [ Info ] global_dir is: /home/nikita/.SpaceVim.d/
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache//SpaceVim/conf/init.json
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache//SpaceVim/conf/init.json
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.cache//SpaceVim/conf/init.json
[ SpaceVim ] [09:40:50] [ Info ] case three
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache//SpaceVim/conf/init.json
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.cache//SpaceVim/conf/init.json
[ SpaceVim ] [09:40:50] [ Info ] start to apply config [glob]
[ SpaceVim ] [09:40:50] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [09:40:50] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:40:50] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:40:50] [ Info ] try to call func of mode:hi-characters-for-long-lines
[ SpaceVim ] [09:40:50] [ Info ] no func found for mode:hi-characters-for-long-lines
[ SpaceVim ] [09:40:50] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [09:40:50] [ Info ] no func found for mode:fill-column-indicator
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache/
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache/
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.cache/
[ SpaceVim ] [09:40:50] [ Info ] case three
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache/
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.cache/
[   rooter ] [09:40:50] [ Info ] Load projects cache from: /home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:40:50] [ Info ] case three
[ SpaceVim ] [09:40:50] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:40:50] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[  FlyGrep ] [09:40:53] [ Info ] FlyGrep startting ===========================
[  FlyGrep ] [09:40:53] [ Info ]    executable    : grep
[  FlyGrep ] [09:40:53] [ Info ]    option        : ['-inHr']
[  FlyGrep ] [09:40:53] [ Info ]    r_option      : ['.']
[  FlyGrep ] [09:40:53] [ Info ]    files         : ''
[  FlyGrep ] [09:40:53] [ Info ]    dir           : ''
[  FlyGrep ] [09:40:53] [ Info ]    ignore_case   : ['-i']
[  FlyGrep ] [09:40:53] [ Info ]    smart_case    : []
[  FlyGrep ] [09:40:53] [ Info ]    expr opt      : ['-e']
[  FlyGrep ] [09:40:54] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vf
[  FlyGrep ] [09:40:54] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfi
[  FlyGrep ] [09:40:54] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfin
[  FlyGrep ] [09:40:55] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind
[  FlyGrep ] [09:40:55] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find', '.']
[  FlyGrep ] [09:40:55] [ Info ] flygrep job id is: 4
[  FlyGrep ] [09:40:55] [ Error ]  flygerp stderr: ['/usr/bin/grep: ./.git/index: binary file matches']
[  FlyGrep ] [09:40:55] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_
[  FlyGrep ] [09:40:55] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_', '.']
[  FlyGrep ] [09:40:55] [ Info ] flygrep job id is: 5
[  FlyGrep ] [09:40:55] [ Error ]  flygerp stderr: ['/usr/bin/grep: ./.git/index: binary file matches']
[  FlyGrep ] [09:40:55] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_a
[  FlyGrep ] [09:40:55] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_an
[  FlyGrep ] [09:40:55] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and
[  FlyGrep ] [09:40:56] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and', '.']
[  FlyGrep ] [09:40:56] [ Info ] flygrep job id is: 6
[  FlyGrep ] [09:40:56] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_
[  FlyGrep ] [09:40:56] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and_', '.']
[  FlyGrep ] [09:40:56] [ Info ] flygrep job id is: 7
[  FlyGrep ] [09:40:56] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_r
[  FlyGrep ] [09:40:56] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_re
[  FlyGrep ] [09:40:57] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and_re', '.']
[  FlyGrep ] [09:40:57] [ Info ] flygrep job id is: 8
[  FlyGrep ] [09:40:57] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_rep
[  FlyGrep ] [09:40:57] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and_rep', '.']
[  FlyGrep ] [09:40:57] [ Info ] flygrep job id is: 9
[  FlyGrep ] [09:40:57] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_repl
[  FlyGrep ] [09:40:57] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_repla
[  FlyGrep ] [09:40:57] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and_repla', '.']
[  FlyGrep ] [09:40:57] [ Info ] flygrep job id is: 10
[  FlyGrep ] [09:40:57] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_replac
[  FlyGrep ] [09:40:57] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and_replac', '.']
[  FlyGrep ] [09:40:57] [ Info ] flygrep job id is: 11
[  FlyGrep ] [09:40:57] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vfind_and_replace
[  FlyGrep ] [09:40:58] [ Info ] grep cmd: ['grep', '-inHr', '-e', 'find_and_replace', '.']
[  FlyGrep ] [09:40:58] [ Info ] flygrep job id is: 12
[  FlyGrep ] [09:41:10] [ Info ] matchadd pattern: [^:]*:\d\+:\d\+:.*\zs\C\vhello
[  FlyGrep ] [09:41:15] [ Info ] FlyGrep ending    ===========================
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test/vimfiler:default@5
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test/vimfiler:default@5
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test/vimfiler:default@5
[ SpaceVim ] [09:41:19] [ Info ] case three
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test/vimfiler:default@5
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test/vimfiler:default@5
[   rooter ] [09:41:19] [ Info ] Start to find root for: /tmp/test/vimfiler:default@5
[ SpaceVim ] [09:41:19] [ Info ] a:path is :.git/
[ SpaceVim ] [09:41:19] [ Info ] a:path is :.git/
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test/.git/
[ SpaceVim ] [09:41:19] [ Info ] case three
[ SpaceVim ] [09:41:19] [ Info ] a:path is :.git/
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test/.git/
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test/.git/
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test/.git/
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test
[ SpaceVim ] [09:41:19] [ Info ] case one
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test/.git/
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/home/nikita
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/home/nikita
[ SpaceVim ] [09:41:19] [ Info ] path is :/home/nikita/
[ SpaceVim ] [09:41:19] [ Info ] case three
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/home/nikita
[ SpaceVim ] [09:41:19] [ Info ] path is :/home/nikita/
[   rooter ] [09:41:19] [ Info ]         (.git/):/tmp/test/
[   rooter ] [09:41:19] [ Info ] buffer name: vimfiler:default@5
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:19] [ Info ] case three
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:19] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:19] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:19] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:19] [ Info ] case three
[ SpaceVim ] [09:41:19] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:19] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:21] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [09:41:21] [ Info ] buffer name: vimfiler:default@5
[ SpaceVim ] [09:41:21] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:21] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:21] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:21] [ Info ] case three
[ SpaceVim ] [09:41:21] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:21] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:21] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:21] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:21] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:21] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:21] [ Info ] case three
[ SpaceVim ] [09:41:21] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:21] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:21] [ Info ] close float statusline winid:1006
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test/find_one.py
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test/find_one.py
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/find_one.py
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test/find_one.py
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/find_one.py
[   rooter ] [09:41:27] [ Info ] Start to find root for: /tmp/test/find_one.py
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:27] [ Info ] buffer name: find_one.py
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:27] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test/find_two.py
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test/find_two.py
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/find_two.py
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test/find_two.py
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/find_two.py
[   rooter ] [09:41:27] [ Info ] Start to find root for: /tmp/test/find_two.py
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:27] [ Info ] buffer name: find_two.py
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:27] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:27] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] case three
[ SpaceVim ] [09:41:27] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:27] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[   rooter ] [09:41:30] [ Info ] buffer name: vimfiler:default@5
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:30] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:30] [ Info ] case three
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:30] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] case three
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[   rooter ] [09:41:30] [ Info ] buffer name: find_two.py
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:30] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:30] [ Info ] case three
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:30] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] case three
[ SpaceVim ] [09:41:30] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:30] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/nvimMhfOzW/1/issue_report.md
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/nvimMhfOzW/1/issue_report.md
[ SpaceVim ] [09:41:34] [ Info ] path is :/tmp/nvimMhfOzW/1/issue_report.md
[ SpaceVim ] [09:41:34] [ Info ] case three
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/nvimMhfOzW/1/issue_report.md
[ SpaceVim ] [09:41:34] [ Info ] path is :/tmp/nvimMhfOzW/1/issue_report.md
[   rooter ] [09:41:34] [ Info ] Start to find root for: /tmp/nvimMhfOzW/1/issue_report.md
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:34] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:34] [ Info ] case three
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:34] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:34] [ Info ] buffer name: /tmp/nvimMhfOzW/1/issue_report.md
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:34] [ Info ] path is :/tmp/test/
[ SpaceVim ] [09:41:34] [ Info ] case three
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/tmp/test
[ SpaceVim ] [09:41:34] [ Info ] path is :/tmp/test/
[   rooter ] [09:41:34] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:34] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:34] [ Info ] case three
[ SpaceVim ] [09:41:34] [ Info ] a:path is :/home/nikita/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:41:34] [ Info ] path is :/home/nikita/.cache/SpaceVim/projects.json
```
</details>


Sorry for not attaching it later. Hope it helps
