### ISSUE TITLE
`+` not recognized

### ISSUE THREAD

**Issue by Marin-Kitagawa** [wsdjeg/SpaceVim#4302]
When I press `SPC n +` it says
```
key bindings is not defined: [SPC]-n-<80>
```
This is a fresh installation and the older `init.vim` file is replaced by the one by `SpaceVim`
I have just added the following lines
```vim
set guifont=FiraCode\ Nerd\ Font:h12
set number
set relativenumber
```
The following was already present
```vim
execute 'source' fnamemodify(expand('<sfile>'), ':h').'/main.vim'
```

The following is my `init.toml` file
```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    windows_leader = ''
    enable_language_specific_leader = false
    vimcompatible = true
    windows_smartclose = ''
    automatic_update = true
    filemanager = "nerdtree"
    enable_vimfiler_gitstatus = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
name = "colorscheme"
random_theme = true

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
```

But I can't use `+` either for going to `count` lines after the current line or for the above purpose.
