### ISSUE TITLE
Add support for rust-analyzer

### ISSUE THREAD

**Issue by AMythicDev** [wsdjeg/SpaceVim#4303]
Although `lang#rust` supports rls and racer, they are being phased out slowly by rust-analyzer. Could we have support for rust-analyzer too.

**Comment by wsdjeg** [comment]
The `lsp` layer supports custom language server command, so you can override the language server command of rust.

```toml
[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rust-analyzer"]
```
