### ISSUE TITLE
VimIRC plugin installation

### ISSUE THREAD

**Issue by duytrung** [wsdjeg/SpaceVim#4345]
Hello,

I want to install the plugin VimIRC, as it said just to copy the file to vim plugin folder and run from the vim command. But seems doesn't work

I'm new to the spaceVim, please instruct how to do with custom (not github repos).

Such as:
1. VimIRC
2. GoldenVim plugin:

I did as the following but not work as well. The program just stalled.

[[custom_plugins]]
    repo = "https://github.com/zhaocai/GoldenView.Vim/zipball/master"
    merged = false

I assume the plugin folder in this case is the bundle folder.

Thank you very much

**Comment by wsdjeg** [comment]
It should be:

```toml
[[custom_plugins]]
    repo = "zhaocai/GoldenView.Vim"
    merged = false
```
