### ISSUE TITLE
plugin update execute function    error: E475: Invalid value for argument cwd

### ISSUE THREAD

**Issue by oeyoews** [wsdjeg/SpaceVim#4375]
## The reproduce ways from Vim starting (Required!)
1. :SPUdate
2. error info
```sh
处理 function 356[2]..<SNR>273_on_pull_exit[43]..<SNR>273_pull[45]..<SNR>273_pull[6]..177 时发生错误: 
第40 行: E475: Invalid value for argument cwd
```

**Comment by wsdjeg** [comment]
Why do not following the issue template, where is the debug info?
--------------
wsdjeg

**Comment by oeyoews** [comment]
[spavim.md](https://github.com/SpaceVim/SpaceVim/files/6953616/spavim.md)
![2021-08-09 18-14-07 的屏幕截图](https://user-images.githubusercontent.com/72405338/128691495-e9bd2985-0eb4-4092-9305-ed16f91a07c1.png)

**Comment by oeyoews** [comment]
## Expected behavior, english is recommend

## Environment Information

- OS: linux
- vim version: 8.2()
- neovim version: -
- SpaceVim version: 1.8.0-dev
- SpaceVim status: c151563\0

```
位于分支 master
您的分支与上游分支 'origin/master' 一致。

无文件要提交，干净的工作区
```

## The reproduce ways from Vim starting (Required!)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['machakann/vim-highlightedyank', {'repo': 'machakann/vim-highlightedyank', 'overwrite': 1}], ['jceb/vim-orgmode', {'repo': 'jceb/vim-orgmode', 'overwrite': 1}]]
  data_dir = '/home/oeyoews/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 1
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Droid Sans Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/oeyoews/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-debug'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  enable=1
  default_position='top'
  default_height=50
[[layers]]
  name="colorscheme"
[[layers]]
  name="incsearch"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lsp"
  override_cmd={'c': ['clangd']}
  filetypes=['c', 'cpp']
[[layers]]
  name="debug"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:06:26] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [18:06:26] [ Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [18:06:26] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d
[ SpaceVim ] [18:06:26] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d
[ SpaceVim ] [18:06:26] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:26] [ Info ] case three
[ SpaceVim ] [18:06:26] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d
[ SpaceVim ] [18:06:26] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:26] [ Info ] find local conf: /home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/init.toml
[ SpaceVim ] [18:06:26] [ Info ] loading cached local conf: /home/oeyoews/.cache//SpaceVim/conf/_home_oeyoews_dotfiles_spacevim_d__SpaceVim_d_init_toml.json
[ SpaceVim ] [18:06:26] [ Info ] start to apply config [local]
[ SpaceVim ] [18:06:26] [ Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [18:06:26] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:06:27] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:06:27] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [18:06:27] [ Info ] no func found for mode:fill-column-indicator
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/
[   rooter ] [18:06:27] [ Info ] Load projects cache from: /home/oeyoews/.cache/SpaceVim/projects.json
[   rooter ] [18:06:27] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:06:27] [ Info ] Start to find root for: /home/oeyoews/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:06:27] [ Info ] case one
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:06:27] [ Info ]         (.SpaceVim.d/):/home/oeyoews/dotfiles/spacevim.d/
[   rooter ] [18:06:27] [ Info ] buffer name: No Name
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:06:27] [ Info ] change to root: /home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:06:27] [ Info ] buffer name: No Name
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:06:27] [ Info ] change to root: /home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] case three
[ SpaceVim ] [18:06:27] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:06:27] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/
[   rooter ] [18:07:24] [ Info ] Start to find root for: /home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:24] [ Info ] case one
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:07:24] [ Info ]         (.git/):/home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] case one
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d/.SpaceVim.d/
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:07:24] [ Info ]         (.SpaceVim.d/):/home/oeyoews/dotfiles/spacevim.d/
[   rooter ] [18:07:24] [ Info ] buffer name: No Name
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/
[   rooter ] [18:07:24] [ Info ] change to root: /home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:24] [ Info ] case three
[ SpaceVim ] [18:07:24] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:24] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/
[   rooter ] [18:07:30] [ Info ] Start to find root for: /home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :.git/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :.git/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :.git/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] case one
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles/.git/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:07:30] [ Info ]         (.git/):/home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] case one
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.SpaceVim.d/
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/
[   rooter ] [18:07:30] [ Info ] buffer name: No Name
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/
[   rooter ] [18:07:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[   rooter ] [18:07:30] [ Info ] buffer name: No Name
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/dotfiles/
[   rooter ] [18:07:30] [ Info ] change to root: /home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] case three
[ SpaceVim ] [18:07:30] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:07:30] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[   rooter ] [18:08:34] [ Info ] buffer name: No Name
[ SpaceVim ] [18:08:34] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:08:34] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:08:34] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/
[ SpaceVim ] [18:08:34] [ Info ] case three
[ SpaceVim ] [18:08:34] [ Info ] a:path is :/home/oeyoews/dotfiles/spacevim.d
[ SpaceVim ] [18:08:34] [ Info ] path is :/home/oeyoews/dotfiles/spacevim.d/
[   rooter ] [18:08:34] [ Info ] change to root: /home/oeyoews/dotfiles/
[ SpaceVim ] [18:08:34] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:34] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:34] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:34] [ Info ] case three
[ SpaceVim ] [18:08:34] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:34] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/tmp/vRIcB5j/7/issue_report.md
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/tmp/vRIcB5j/7/issue_report.md
[ SpaceVim ] [18:08:38] [ Info ] path is :/tmp/vRIcB5j/7/issue_report.md
[ SpaceVim ] [18:08:38] [ Info ] case three
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/tmp/vRIcB5j/7/issue_report.md
[ SpaceVim ] [18:08:38] [ Info ] path is :/tmp/vRIcB5j/7/issue_report.md
[   rooter ] [18:08:38] [ Info ] Start to find root for: /tmp/vRIcB5j/7/issue_report.md
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:08:38] [ Info ] path is :/home/oeyoews/dotfiles/
[ SpaceVim ] [18:08:38] [ Info ] case three
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:08:38] [ Info ] path is :/home/oeyoews/dotfiles/
[   rooter ] [18:08:38] [ Info ] buffer name: /tmp/vRIcB5j/7/issue_report.md
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:08:38] [ Info ] path is :/home/oeyoews/dotfiles/
[ SpaceVim ] [18:08:38] [ Info ] case three
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/dotfiles
[ SpaceVim ] [18:08:38] [ Info ] path is :/home/oeyoews/dotfiles/
[   rooter ] [18:08:38] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:38] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:38] [ Info ] case three
[ SpaceVim ] [18:08:38] [ Info ] a:path is :/home/oeyoews/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:08:38] [ Info ] path is :/home/oeyoews/.cache/SpaceVim/projects.json
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.

![2021-08-09 18-14-07 的屏幕截图](https://user-images.githubusercontent.com/72405338/128692091-0c22cba4-606c-4eb3-83e3-c13997866b14.png)
