### ISSUE TITLE
Lines become highlighted up to indentation depth when cursor passes over in normal mode

### ISSUE THREAD

**Issue by taranlu-houzz** [wsdjeg/SpaceVim#4424]
## Expected behavior, english is required
This issue started happening recently (maybe about two weeks ago?). When moving around in normal mode, passing over a  blank line causes it to be highlighted up to indentation level of the previous line (and the highlight does not go away until I use `:noh`). I mainly work in Python, which is indentation based, so this happens all over the place and makes the interface extremely cluttered.

## The reproduce ways from Vim starting (Required!)
- Open `spacevim` and start working on any Python file with indentation.

## Debug info
<details>

  ```
  SpaceVim layers:
  
  + autocomplete:             loaded          https://spacevim.org/layers/autocomplete/
  - chat:                 not loaded          https://spacevim.org/layers/chat/
  + checkers:                 loaded          https://spacevim.org/layers/checkers/
  - chinese:              not loaded          https://spacevim.org/layers/chinese/
  + colorscheme:              loaded          https://spacevim.org/layers/colorscheme/
  + core#banner:              loaded          https://spacevim.org/layers/core/banner/
  + core#statusline:          loaded          https://spacevim.org/layers/core/statusline/
  + core#tabline:             loaded          https://spacevim.org/layers/core/tabline/
  + core:                     loaded          https://spacevim.org/layers/core/
  - cscope:               not loaded          https://spacevim.org/layers/cscope/
  - ctrlp:                not loaded          https://spacevim.org/layers/ctrlp/
  - ctrlspace:            not loaded          https://spacevim.org/layers/ctrlspace/
  - debug:                not loaded          https://spacevim.org/layers/debug/
  - denite:               not loaded          https://spacevim.org/layers/denite/
  + edit:                     loaded          https://spacevim.org/layers/edit/
  - exprfold:             not loaded          no exists
  - floobits:             not loaded          https://spacevim.org/layers/floobits/
  - foldsearch:           not loaded          https://spacevim.org/layers/foldsearch/
  + format:                   loaded          https://spacevim.org/layers/format/
  - fuzzy:                not loaded          no exists
  - fzf:                  not loaded          https://spacevim.org/layers/fzf/
  - games:                not loaded          no exists
  + git:                      loaded          https://spacevim.org/layers/git/
  - github:               not loaded          https://spacevim.org/layers/github/
  - gtags:                not loaded          https://spacevim.org/layers/gtags/
  + incsearch:                loaded          no exists
  - indentmove:           not loaded          no exists
  - japanese:             not loaded          https://spacevim.org/layers/japanese/
  - lang#actionscript:    not loaded          https://spacevim.org/layers/lang/actionscript/
  - lang#agda:            not loaded          https://spacevim.org/layers/lang/agda/
  - lang#asciidoc:        not loaded          https://spacevim.org/layers/lang/asciidoc/
  - lang#aspectj:         not loaded          https://spacevim.org/layers/lang/aspectj/
  - lang#assembly:        not loaded          https://spacevim.org/layers/lang/assembly/
  - lang#autohotkey:      not loaded          https://spacevim.org/layers/lang/autohotkey/
  - lang#autoit:          not loaded          no exists
  - lang#batch:           not loaded          https://spacevim.org/layers/lang/batch/
  - lang#c:               not loaded          https://spacevim.org/layers/lang/c/
  - lang#chapel:          not loaded          https://spacevim.org/layers/lang/chapel/
  - lang#clojure:         not loaded          https://spacevim.org/layers/lang/clojure/
  - lang#coffeescript:    not loaded          https://spacevim.org/layers/lang/coffeescript/
  - lang#crystal:         not loaded          https://spacevim.org/layers/lang/crystal/
  - lang#csharp:          not loaded          https://spacevim.org/layers/lang/csharp/
  - lang#d:               not loaded          https://spacevim.org/layers/lang/d/
  - lang#dart:            not loaded          https://spacevim.org/layers/lang/dart/
  - lang#dockerfile:      not loaded          https://spacevim.org/layers/lang/dockerfile/
  - lang#e:               not loaded          https://spacevim.org/layers/lang/e/
  - lang#eiffel:          not loaded          https://spacevim.org/layers/lang/eiffel/
  - lang#elixir:          not loaded          https://spacevim.org/layers/lang/elixir/
  - lang#elm:             not loaded          https://spacevim.org/layers/lang/elm/
  - lang#erlang:          not loaded          https://spacevim.org/layers/lang/erlang/
  - lang#extra:           not loaded          https://spacevim.org/layers/lang/extra/
  - lang#factor:          not loaded          https://spacevim.org/layers/lang/factor/
  - lang#fennel:          not loaded          https://spacevim.org/layers/lang/fennel/
  - lang#forth:           not loaded          no exists
  - lang#fortran:         not loaded          https://spacevim.org/layers/lang/fortran/
  - lang#foxpro:          not loaded          https://spacevim.org/layers/lang/foxpro/
  - lang#fsharp:          not loaded          https://spacevim.org/layers/lang/fsharp/
  - lang#go:              not loaded          https://spacevim.org/layers/lang/go/
  - lang#goby:            not loaded          https://spacevim.org/layers/lang/goby/
  - lang#gosu:            not loaded          https://spacevim.org/layers/lang/gosu/
  - lang#graphql:         not loaded          https://spacevim.org/layers/lang/graphql/
  - lang#groovy:          not loaded          https://spacevim.org/layers/lang/groovy/
  - lang#hack:            not loaded          https://spacevim.org/layers/lang/hack/
  - lang#haskell:         not loaded          https://spacevim.org/layers/lang/haskell/
  - lang#html:            not loaded          https://spacevim.org/layers/lang/html/
  - lang#hy:              not loaded          https://spacevim.org/layers/lang/hy/
  - lang#idris:           not loaded          https://spacevim.org/layers/lang/idris/
  - lang#io:              not loaded          https://spacevim.org/layers/lang/io/
  - lang#ipynb:           not loaded          https://spacevim.org/layers/lang/ipynb/
  - lang#j:               not loaded          https://spacevim.org/layers/lang/j/
  - lang#janet:           not loaded          https://spacevim.org/layers/lang/janet/
  - lang#java:            not loaded          https://spacevim.org/layers/lang/java/
  + lang#javascript:          loaded          https://spacevim.org/layers/lang/javascript/
  - lang#json:            not loaded          no exists
  - lang#julia:           not loaded          https://spacevim.org/layers/lang/julia/
  - lang#kotlin:          not loaded          https://spacevim.org/layers/lang/kotlin/
  - lang#lasso:           not loaded          https://spacevim.org/layers/lang/lasso/
  - lang#latex:           not loaded          https://spacevim.org/layers/lang/latex/
  - lang#lisp:            not loaded          https://spacevim.org/layers/lang/lisp/
  - lang#livescript:      not loaded          https://spacevim.org/layers/lang/livescript/
  - lang#lua:             not loaded          https://spacevim.org/layers/lang/lua/
  + lang#markdown:            loaded          https://spacevim.org/layers/lang/markdown/
  - lang#matlab:          not loaded          https://spacevim.org/layers/lang/matlab/
  - lang#moonscript:      not loaded          https://spacevim.org/layers/lang/moonscript/
  - lang#nim:             not loaded          https://spacevim.org/layers/lang/nim/
  - lang#nix:             not loaded          https://spacevim.org/layers/lang/nix/
  - lang#ocaml:           not loaded          https://spacevim.org/layers/lang/ocaml/
  - lang#pact:            not loaded          https://spacevim.org/layers/lang/pact/
  - lang#pascal:          not loaded          https://spacevim.org/layers/lang/pascal/
  - lang#perl:            not loaded          https://spacevim.org/layers/lang/perl/
  - lang#php:             not loaded          https://spacevim.org/layers/lang/php/
  - lang#plantuml:        not loaded          https://spacevim.org/layers/lang/plantuml/
  - lang#pony:            not loaded          https://spacevim.org/layers/lang/pony/
  - lang#povray:          not loaded          https://spacevim.org/layers/lang/povray/
  - lang#powershell:      not loaded          https://spacevim.org/layers/lang/powershell/
  - lang#processing:      not loaded          https://spacevim.org/layers/lang/processing/
  - lang#prolog:          not loaded          https://spacevim.org/layers/lang/prolog/
  - lang#puppet:          not loaded          https://spacevim.org/layers/lang/puppet/
  - lang#purescript:      not loaded          https://spacevim.org/layers/lang/purescript/
  + lang#python:              loaded          https://spacevim.org/layers/lang/python/
  - lang#r:               not loaded          https://spacevim.org/layers/lang/r/
  - lang#racket:          not loaded          https://spacevim.org/layers/lang/racket/
  - lang#reason:          not loaded          https://spacevim.org/layers/lang/reason/
  - lang#red:             not loaded          https://spacevim.org/layers/lang/red/
  - lang#rescript:        not loaded          https://spacevim.org/layers/lang/rescript/
  - lang#ring:            not loaded          https://spacevim.org/layers/lang/ring/
  - lang#rst:             not loaded          https://spacevim.org/layers/lang/rst/
  + lang#ruby:                loaded          https://spacevim.org/layers/lang/ruby/
  - lang#rust:            not loaded          https://spacevim.org/layers/lang/rust/
  - lang#s:               not loaded          no exists
  - lang#scala:           not loaded          https://spacevim.org/layers/lang/scala/
  - lang#scheme:          not loaded          https://spacevim.org/layers/lang/scheme/
  + lang#sh:                  loaded          https://spacevim.org/layers/lang/sh/
  - lang#slim:            not loaded          https://spacevim.org/layers/lang/slim/
  - lang#smalltalk:       not loaded          https://spacevim.org/layers/lang/smalltalk/
  - lang#sml:             not loaded          https://spacevim.org/layers/lang/sml/
  - lang#solidity:        not loaded          no exists
  - lang#splus:           not loaded          no exists
  - lang#sql:             not loaded          no exists
  - lang#supercollider:   not loaded          no exists
  - lang#swift:           not loaded          https://spacevim.org/layers/lang/swift/
  - lang#swig:            not loaded          no exists
  - lang#tcl:             not loaded          https://spacevim.org/layers/lang/tcl/
  + lang#toml:                loaded          https://spacevim.org/layers/lang/toml/
  - lang#typescript:      not loaded          https://spacevim.org/layers/lang/typescript/
  - lang#v:               not loaded          https://spacevim.org/layers/lang/v/
  - lang#vbnet:           not loaded          https://spacevim.org/layers/lang/vbnet/
  - lang#vim:             not loaded          https://spacevim.org/layers/lang/vim/
  - lang#vue:             not loaded          https://spacevim.org/layers/lang/vue/
  - lang#wdl:             not loaded          no exists
  - lang#WebAssembly:     not loaded          https://spacevim.org/layers/lang/WebAssembly/
  - lang#wolfram:         not loaded          https://spacevim.org/layers/lang/wolfram/
  - lang#xml:             not loaded          https://spacevim.org/layers/lang/xml/
  - lang#xquery:          not loaded          no exists
  - lang#zig:             not loaded          https://spacevim.org/layers/lang/zig/
  - leaderf:              not loaded          https://spacevim.org/layers/leaderf/
  + lsp:                      loaded          https://spacevim.org/layers/language-server-protocol/
  - mail:                 not loaded          no exists
  - operator:             not loaded          no exists
  - org:                  not loaded          no exists
  + shell:                    loaded          https://spacevim.org/layers/shell/
  + sudo:                     loaded          https://spacevim.org/layers/sudo/
  - test:                 not loaded          https://spacevim.org/layers/test/
  - tmux:                 not loaded          https://spacevim.org/layers/tmux/
  - tools#dash:           not loaded          https://spacevim.org/layers/tools/dash/
  - tools#mpv:            not loaded          https://spacevim.org/layers/tools/mpv/
  - tools#screensaver:    not loaded          no exists
  - tools#zeal:           not loaded          https://spacevim.org/layers/tools/zeal/
  - tools:                not loaded          https://spacevim.org/layers/tools/
  + ui:                       loaded          https://spacevim.org/layers/ui/
  - unite:                not loaded          https://spacevim.org/layers/unite/
  + VersionControl:           loaded          https://spacevim.org/layers/VersionControl/
  - vim:                  not loaded          no exists
  ```

</details>

## Screenshots

![image](https://user-images.githubusercontent.com/52425255/130501543-af241a39-159c-4133-b47c-e1448338fba1.png)

**Comment by TidalPaladin** [comment]
Experiencing the same issue. It looks like disabling indentation guides with `SPC t h i` fixes the highlighting issue at the cost of no longer having indentation guides.

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/tidal/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/tidal/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-tmux'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lsp"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#python"
  format_on_save=0
  enable_typeinfo=1
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#latex"
[[layers]]
  name="git"
  git_pugin='fugitive'
[[layers]]
  name="VersionControl"
[[layers]]
  name="dockerfile"
[[layers]]
  name="tmux"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:24:44] [ Info ] Startup with argv: ['default.py']
[ SpaceVim ] [08:24:44] [ Info ] find local conf: /home/tidal/voidrice/.SpaceVim.d/init.toml
[ SpaceVim ] [08:24:44] [ Info ] loading cached local conf: /home/tidal/.cache/SpaceVim/conf/_home_tidal_voidrice__SpaceVim_d_init_toml.json
[ SpaceVim ] [08:24:44] [ Info ] start to apply config [local]
[ SpaceVim ] [08:24:45] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [08:24:45] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [08:24:45] [ Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [08:24:45] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [08:24:45] [ Info ] try to call func of mode:whitespace
[ SpaceVim ] [08:24:45] [ Info ] no func found for mode:whitespace
[   rooter ] [08:24:45] [ Info ] Load projects cache from: /home/tidal/.cache/SpaceVim/projects.json
[   rooter ] [08:24:45] [ Info ] Start to find root for: /home/tidal/default.py
[   rooter ] [08:24:45] [ Info ]         (.SpaceVim.d/):/home/tidal/voidrice/
[   rooter ] [08:24:45] [ Info ] buffer name: default.py
[   rooter ] [08:24:45] [ Info ] change to root: /home/tidal/voidrice/
[   rooter ] [08:24:45] [ Info ] buffer name: /home/tidal/default.py
[   rooter ] [08:24:45] [ Info ] same as current directory, no need to change.
```
</details>
