### ISSUE TITLE
Go To Definition displays error - Typescript

### ISSUE THREAD

**Issue by Doomwhite** [wsdjeg/SpaceVim#4445]
## Expected behavior, english is required
When I use the GoTo Definition on a type it was supposed to preview the type from where it's imported.

## The reproduce ways from Vim starting (Required!)
Windows 10, on Gvim.
Any type/function that you would normally use the goto definition, inside a .ts file and using the typescript layer.

## Debug info
<kbd>
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\Cliente\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SourceCodePro Nerd Font Mono:h9'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\Cliente\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-bookmarks'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
  enable=1
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#typescript"
  enable=1
[[layers]]
  name="shell"
  enable=1
[[layers]]
  name="fzf"
[[layers]]
  name="sudo"
[[layers]]
  name="lc"
[[layers]]
  name="tools"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(C:\Program Files\Vim\vim82\gvim.exe)
version: 802
OS: windows
[shell, shellcmdflag, shellslash]: ['C:\Windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:43:07] [ Info ] Startup with no argv, current dir is used: F:\Projetos\bsc-project\bsc-app
[ SpaceVim ] [10:43:07] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [10:43:07] [ Info ] global_dir is: C:/Users/Cliente/.SpaceVim.d/
[ SpaceVim ] [10:43:07] [ Info ] start to apply config [glob]
[ SpaceVim ] [10:43:07] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [10:43:07] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [10:43:08] [ Info ] try to open SpaceVim welcome page
[   rooter ] [10:43:08] [ Info ] Load projects cache from: C:/Users/Cliente/.cache/SpaceVim/projects.json
[   rooter ] [10:43:11] [ Info ] Start to find root for: F:/Projetos/bsc-project/bsc-app/projects/module/pages/indicator-registration/src/indicator.component.ts
[   rooter ] [10:43:11] [ Info ] buffer name: F:\Projetos\bsc-project\bsc-app\projects\module\pages\indicator-registration\src\indicator.component.ts
[   rooter ] [10:43:11] [ Info ] same as current directory, no need to change.
```
</details>

</kbd>

## Screenshots
![image](https://user-images.githubusercontent.com/40442835/131236896-877849e9-be92-4950-88e6-2d6e2711f01a.png)
