### ISSUE TITLE
Custom plugins are not loading

### ISSUE THREAD

**Issue by linusjf** [wsdjeg/SpaceVim#4470]
Custom plugins are not loading as expected despite specifying them in init.toml.

## Expected behavior

Plugins must be loaded and expected behaviour must happen. E.g., templates must be loaded and initialized for template plugins.

## The reproduce ways from Vim starting (Required!)

File init.toml:

```toml
#============================= == == == == == ============
#dark_powered.toml-- - dark powered configuration example for SpaceVim
#Copyright(c) 2016 - 2017 Wang Shidong &Contributors
#Author : Wang Shidong < wsdjeg at 163.com>
#URL : https: // spacevim.org
#License : GPLv3
#============================================================
#All SpaceVim option below[option] section
# This is a basic configuration example for SpaceVim

# All SpaceVim options are below [options] snippet
[options]
    default_indent = 2
    expand_tab = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_separator = "bar"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = false
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    # checkers options
    enable_statusline_mode = true
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
    name = "core#banner" 

[[layers]]
    name = "core#statusline" 

[[layers]]
    name = "core#tabline" 

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
# auto_completion_return_key_behavior = "nil"
auto_completion_tab_key_behavior = "smart"
    auto_completion_delay = 200
    auto_completion_complete_with_key_sequence = "nil"
    auto_completion_complete_with_key_sequence_delay = 0.1
    # name = "autocomplete"
      auto-completion-return-key-behavior = "complete"
#    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = "shell"
    default_position = "top"
    default_height = 30

# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
    name = "vim-scripts/dbext.vim"
    merged = true
    
    name = "lilydjwg/colorizer"
    merged = true

    name = "junegunn/vim-github-dashboard"
    merged = true
    
    name = "kdheepak/JuliaFormatter.vim"
    merged = true

    name = "nono/jquery.vim"
    merged = true

    name = 'tibabit/vim-templates'
    merged = false
    
    name = 'aperezdc/vim-template'
    merged = true

    name = 'editorconfig/editorconfig-vim'
    merged = true

    name = 'tpope/vim-surround'
    merged = true

    name = 'scrooloose/nerdtree'
    merged = true

    name = 'scrooloose/syntastic'
    merged = true

    name = 'pangloss/vim-javascript'
    merged = true

    name = 'luchermitte/vimfold4c'
    merged = true

    name = 'shougo/neocomplete.vim'
    merged = true

[[layers]] 
    name = "lang#java"

[[layers]]
  name = "lang#php"

[[layers]] 
    name = "lang#html"

[[layers]]
    name = "lang#sh"

[[layers]] 
    name = "lang#python"
    python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
    ]
    enable_typeinfo = true

[[layers]] 
    name = "lang#javascript"
    auto_fix = true
    enable_flow_syntax = true

[[layers]] 
    name = "lang#perl"

[[layers]] 
    name = "lang#ruby"

[[layers]] 
    name = "lang#c"
    clang_executable = "/data/data/com.termux/files/usr/bin/clang"
    enable_clang_syntax_highlight = true
    [layer.clang_std]
    c = "c17"
    cpp = "c++20"

[[layers]] 
    name = "lang#r"
    repl_command = "R --no-save"

[[layers]] 
    name = "format"

[[layers]]
    name = "checkers"
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true

[[layers]] 
    name = 'shell' 
    default_position = 'top' 
    default_height = 30

[[layers]]
    name = "git"

[[layers]]
    name = "github"

[[layers]]
    name = "lang#latex"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "ui"
    enable_sidebar = true

[[layers]]
    name = "sudo"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#rust"
  recommended_style = true
  format_on_save = true

[[layers]]
  name = "lang#julia"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "lang#sql"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#xquery"

[[layers]]
  name = "lang#groovy"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#d"
```

File autoload/myspacevim.vim

```vim
function! myspacevim#before() abort
  au BufRead,BufNewFile *.R setlocal textwidth=80
  au BufRead,BufNewFile *.r setlocal textwidth=80
  au BufRead,BufNewFile *.jl setlocal textwidth=80
  au BufRead,BufNewFile jquery.*.js set ft=javascript syntax=jquery
let g:neomake_enabled_c_makers = ['clang']
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['prettier', 'eslint'],
\   'r': ['styler']
\}
" Set this variable to 1 to fix files when you save them.
let g:ale_fix_on_save = 0
" Enable completion where available.
" This setting must be set before ALE is loaded.
" You should not turn this setting on if you wish to use ALE as a completion
" source for other completion plugins, like Deoplete.
let g:ale_completion_enabled = 1
nnoremap jk <Esc>
" normal mode mapping
nnoremap <localleader>jf :JuliaFormatterFormat<CR>
" visual mode mapping
vnoremap <localleader>jf :JuliaFormatterFormat<CR>
let g:JuliaFormatter_options = {
      \ 'indent'                    : 2,
      \ 'margin'                    : 80,
      \ 'always_for_in'             : v:true,
      \ 'whitespace_typedefs'       : v:false,
      \ 'whitespace_ops_in_indices' : v:true,
      \ 'remove_extra_newlines'     : v:true,
      \ 'always_use_return'         : v:true,
      \ 'whitespace_in_kwargs'      : v:true,
      \ 'annotate_untyped_fields_with_any' : v:true,
      \ 'format_docstrings'         : v:true
      \ }
"other configs
let g:github_dashboard = { 'username': 'fernal73', 'password': $GITHUB_TOKEN }
let g:gista#client#default_username = 'monkeyxite'
let g:tmpl_auto_initialize = 1 
let g:tmpl_search_paths = ['~/templates']
let g:tmpl_author_email = 'linusfernandes at gmail dot com'
let g:tmpl_author_name = 'Linus Fernandes'
let g:tmpl_project = 'Github Learning Repos'
let g:tmpl_company = 'Linus Fernandes'
let g:tmpl_copyright = 'Copyright (c) g:tmpl_company'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_auto_jump = 1
endfunction

function! myspacevim#after() abort
iunmap jk
endfunction

```

## Output of the `:SPDebugInfo!`
```
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['shougo/neocomplete.vim', {'name': 'shougo/neocomplete.vim', 'merged': 1, 'overwrite': 1}]]
  data_dir = '/data/data/com.termux/files/home/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_filetree_gitstatus = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/data/data/com.termux/files/home/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dlang'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'package.json', '.SpaceVim.d/', '.clang', '.Rprofile', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_delay=200
  auto-completion-return-key-behavior='complete'
  auto_completion_tab_key_behavior='smart'
  auto_completion_complete_with_key_sequence='nil'
  auto_completion_complete_with_key_sequence_delay=0.1
[[layers]]
  name="checkers"
  enable_ale=1
  lint_on_the_fly=1
  enable_neomake=0
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#python"
  python_file_head=['#!/usr/bin/env python', '# -*- coding: utf-8 -*-', '', '']
  enable_typeinfo=1
[[layers]]
  name="lang#javascript"
  auto_fix=1
  enable_flow_syntax=1
[[layers]]
  name="lang#perl"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#c"
  clang_executable='/data/data/com.termux/files/usr/bin/clang'
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#r"
  repl_command='R --no-save'
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="sudo"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#csharp"
  highlight_types=0
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#rust"
  format_on_save=1
  recommended_style=1
[[layers]]
  name="lang#julia"
[[layers]]
  name="lang#lisp"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lang#xquery"
[[layers]]
  name="lang#groovy"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#d"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/data/data/com.termux/files/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/data/data/com.termux/files/usr/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:33:16] [ Info ] Startup with argv: ['debuginfo']
[ SpaceVim ] [11:33:16] [ Info ] find local conf: /data/data/com.termux/files/home/.SpaceVim.d/init.toml
[ SpaceVim ] [11:33:16] [ Info ] loading cached local conf: /data/data/com.termux/files/home/.cache/SpaceVim/conf/_data_data_com_termux_files_home__SpaceVim_d_init_toml.json
[ SpaceVim ] [11:33:16] [ Info ] start to apply config [local]
[ SpaceVim ] [11:33:16] [ Warn ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [11:33:16] [ Warn ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [11:33:16] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:33:16] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:33:16] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [11:33:17] [ Info ] Load projects cache from: /data/data/com.termux/files/home/.cache/SpaceVim/projects.json
[ SpaceVim ] [11:33:17] [ Error ] npm or yarn is required to build iamcco/markdown-preview and neoclide/vim-node-rpc
[   rooter ] [11:33:18] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [11:33:18] [ Info ] Start to find root for: /data/data/com.termux/files/home/debuginfo
[   rooter ] [11:33:18] [ Info ] buffer name: debuginfo
[   rooter ] [11:33:18] [ Info ] same as current directory, no need to change.
[   rooter ] [11:33:18] [ Info ] buffer name: debuginfo
[   rooter ] [11:33:18] [ Info ] same as current directory, no need to change.
```
</details>

```
