### ISSUE TITLE
with `lang#lisp` layer only suggestions and autocomplete functions working. No other vim-lisp/vlime functions with `[SPC] l` are working! :disappointed: 

### ISSUE THREAD

**Issue by bauripalash** [wsdjeg/SpaceVim#4485]
## Expected behavior, english is recommend

while editing a lisp source code, `[SPC] l I  ` should evaluate the s-expr instead I get `Vim(call):E117: Unknown function: VlimeInspect`
This is not just while editing a lisp file , no `[SPC] l` does not work , I alaway get error something like `Unknown function Vlime<PUT ANY SHOULD BE PRESENT FUNCTION>`

So in sort:
any lisp functions not working except autocomplete.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.6.0
- SpaceVim version: 1.8.0-dev
- SpaceVim status: f48b6a9a

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
* `$ nvim foo.lisp`
* `press [i]`
* `type any random lisp expr`
* '[ESC]:w'
* `While in this mode , do [SPC] l s s`
* `We got and error which says Vim(call):E117: Unknown function VlimeSendToREPL`
[PS. You can use any `[SPC] l` combinations, but you'll alaway get `....Unknown function: Vlime<ANY VLIME FUNCTION>` ]

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/palash/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/palash/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-lisp'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#lisp"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:25:36] [ Info ] Startup with argv: ['a.lisp']
[ SpaceVim ] [11:25:36] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:25:36] [ Info ] global_dir is: /home/palash/.SpaceVim.d/
[ SpaceVim ] [11:25:36] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:25:36] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [11:25:36] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:25:36] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:25:36] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [11:25:37] [ Info ] Load projects cache from: /home/palash/.cache/SpaceVim/projects.json
[   rooter ] [11:25:44] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:25:44] [ Info ] buffer name: No Name
[   rooter ] [11:25:44] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:25:44] [ Info ] key binding guide float statusline winid:1003
[   rooter ] [11:25:45] [ Info ] Start to find root for: /home/palash/Desktop/ll/a.lisp
[   rooter ] [11:25:45] [ Info ] buffer name: a.lisp
[   rooter ] [11:25:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:25:45] [ Info ] close float statusline winid:1003
[   rooter ] [11:25:45] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:25:45] [ Info ] buffer name: No Name
[   rooter ] [11:25:45] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:25:45] [ Info ] key binding guide float statusline winid:1005
[   rooter ] [11:25:49] [ Info ] buffer name: a.lisp
[   rooter ] [11:25:49] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:25:49] [ Info ] close float statusline winid:1005
[   rooter ] [11:25:49] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:25:49] [ Info ] buffer name: No Name
[   rooter ] [11:25:49] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:25:49] [ Info ] key binding guide float statusline winid:1007
[   rooter ] [11:25:54] [ Info ] buffer name: a.lisp
[   rooter ] [11:25:54] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:25:54] [ Info ] close float statusline winid:1007
[   rooter ] [11:26:26] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:26:26] [ Info ] buffer name: No Name
[   rooter ] [11:26:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:27] [ Info ] key binding guide float statusline winid:1009
[   rooter ] [11:26:28] [ Info ] buffer name: a.lisp
[   rooter ] [11:26:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:28] [ Info ] close float statusline winid:1009
[   rooter ] [11:26:28] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:26:28] [ Info ] buffer name: No Name
[   rooter ] [11:26:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:28] [ Info ] key binding guide float statusline winid:1011
[   rooter ] [11:26:32] [ Info ] buffer name: a.lisp
[   rooter ] [11:26:32] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:32] [ Info ] close float statusline winid:1011
[   rooter ] [11:26:35] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:26:35] [ Info ] buffer name: No Name
[   rooter ] [11:26:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:35] [ Info ] key binding guide float statusline winid:1013
[   rooter ] [11:26:35] [ Info ] buffer name: a.lisp
[   rooter ] [11:26:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:35] [ Info ] close float statusline winid:1013
[   rooter ] [11:26:35] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:26:35] [ Info ] buffer name: No Name
[   rooter ] [11:26:35] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:35] [ Info ] key binding guide float statusline winid:1015
[   rooter ] [11:26:47] [ Info ] buffer name: a.lisp
[   rooter ] [11:26:47] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:47] [ Info ] close float statusline winid:1015
[   rooter ] [11:26:47] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:26:47] [ Info ] buffer name: No Name
[   rooter ] [11:26:47] [ Info ] same as current directory, no need to change.
[   rooter ] [11:27:08] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:08] [ Info ] same as current directory, no need to change.
[   rooter ] [11:27:15] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:15] [ Info ] buffer name: No Name
[   rooter ] [11:27:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:15] [ Info ] key binding guide float statusline winid:1018
[   rooter ] [11:27:15] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:15] [ Info ] close float statusline winid:1018
[   rooter ] [11:27:15] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:15] [ Info ] buffer name: No Name
[   rooter ] [11:27:15] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:15] [ Info ] key binding guide float statusline winid:1020
[   rooter ] [11:27:18] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:18] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:18] [ Info ] close float statusline winid:1020
[   rooter ] [11:27:22] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:22] [ Info ] buffer name: No Name
[   rooter ] [11:27:22] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:22] [ Info ] key binding guide float statusline winid:1022
[   rooter ] [11:27:22] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:22] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:22] [ Info ] close float statusline winid:1022
[   rooter ] [11:27:23] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:23] [ Info ] buffer name: No Name
[   rooter ] [11:27:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:23] [ Info ] key binding guide float statusline winid:1024
[   rooter ] [11:27:26] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:26] [ Info ] close float statusline winid:1024
[   rooter ] [11:27:26] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:26] [ Info ] buffer name: No Name
[   rooter ] [11:27:26] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:26] [ Info ] key binding guide float statusline winid:1026
[   rooter ] [11:27:30] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:30] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:30] [ Info ] close float statusline winid:1026
[   rooter ] [11:27:33] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:33] [ Info ] buffer name: No Name
[   rooter ] [11:27:33] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:33] [ Info ] key binding guide float statusline winid:1028
[   rooter ] [11:27:33] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:33] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:33] [ Info ] close float statusline winid:1028
[   rooter ] [11:27:33] [ Info ] Start to find root for: /home/palash/Desktop/ll/
[   rooter ] [11:27:33] [ Info ] buffer name: No Name
[   rooter ] [11:27:33] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:33] [ Info ] key binding guide float statusline winid:1030
[   rooter ] [11:27:41] [ Info ] buffer name: a.lisp
[   rooter ] [11:27:41] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:41] [ Info ] close float statusline winid:1030
[   rooter ] [11:27:41] [ Info ] Start to find root for: /tmp/nvimGJHn1U/1/issue_report.md
[   rooter ] [11:27:41] [ Info ] buffer name: /tmp/nvimGJHn1U/1/issue_report.md
[   rooter ] [11:27:41] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

[![asciicast](https://asciinema.org/a/rLv5rsCJoiGwMQMBH2IvH68kI.svg)](https://asciinema.org/a/rLv5rsCJoiGwMQMBH2IvH68kI)
