### ISSUE TITLE
Spacevim does not start

### ISSUE THREAD

**Issue by ssbanerje** [wsdjeg/SpaceVim#4495]
## Expected behavior
My latest call to `SPUpdate`, seems to have broken my Spacevim installation.

Spacevim now prints an error on executing `nvim` or `vim`. Further, some plugins like `dein` don't work.

Here is the startup error:
```
Error detected while processing function SpaceVim#custom#load[40]..<SNR>50_load_glob_conf[10]..SpaceVim#custom#apply[31]..SpaceVim#layers#load[22]..SpaceVim#layers#lang#lua#set_variable:
line    3:
E121: Undefined variable: a:var
E116: Invalid arguments for function get
E15: Invalid expression: get(a:var, 'format_on_save', s:format_on_save)
Error detected while processing function SpaceVim#custom#load[40]..<SNR>50_load_glob_conf[10]..SpaceVim#custom#apply:
line   31:
E171: Missing :endif
Error detected while processing function SpaceVim#custom#load[40]..<SNR>50_load_glob_conf:
line   10:
E171: Missing :endif
Error detected while processing function SpaceVim#custom#load:
line   40:
E171: Missing :endifError detected while processing command line:
E117: Unknown function: dein#install
remote/host: generated rplugin manifest: /home/subho/.local/share/nvim/rplugin.vimnvim: ../src/nvim/message.c:2291: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
```

## The reproduce ways from Vim starting

Execute the `vim` or `nvim` command.

The log in the previous section is from the `nvim --headless +'call dein#install()' +UpdateRemotePlugins +qall` command.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'material'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/subho/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 1
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 1
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetree_show_hidden = 1
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'ssbanerje'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 100
  plugin_bundle_dir = '/home/subho/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'slant'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
  enable=1
  format_on_save=0
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="autmcomplete"
[[layers]]
  name="colorscheme"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="denite"
[[layers]]
  name="git"
  git-plugin='gina'
[[layers]]
  name="gtags"
[[layers]]
  name="incsearch"
[[layers]]
  name="shell"
  default_position='bottom'
[[layers]]
  name="sudo"
[[layers]]
  name="tools"
[[layers]]
  name="tmux"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvimdyloLc/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:26:00] [ Info ] Startup with no argv, current dir is used: ~/Workshop/dotfiles
[ SpaceVim ] [11:26:00] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:26:00] [ Info ] global_dir is: /home/subho/.SpaceVim.d/
[ SpaceVim ] [11:26:00] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:26:00] [ Info ] try to open SpaceVim welcome page
```
</details>
