### ISSUE TITLE
commit 'd807b9bf' breaks markdown-preview.nvim plugin

### ISSUE THREAD

**Issue by YueHonghui** [wsdjeg/SpaceVim#4500]
## Expected behavior, english is required
When I use the latest SpaceVim and enable the markdown layer, I will get a error `Error: nvim_call_function: Vim:E117 : Unknown function: openbrowser#open` after attempt to preview a markdown file. It should open a preview browser windows successfully. 

## The reproduce ways from Vim starting (Required!)
1. use the latest SpaceVim
2. enable the markdown layer
3. open a markdown file
4. use `SPACE+l+p` to preview the markdown file

I have already found the commit `d807b9bf` breaks this. The commit before it works fine. But I don't know how to fix it.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['YueHonghui/markdown-preview.nvim', {'depends': 'open-browser.vim', 'build': 'cd app & yarn install', 'repo': 'YueHonghui/markdown-preview.nvim', 'on_cmd': 'MarkdownPreview', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/xxx/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['vim-startify', 'markdown-preview.nvim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 1
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/xxx/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'helpful.vim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 50
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_delay=200
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='cycle'
  auto_completion_complete_with_key_sequence='nil'
  auto_completion_complete_with_key_sequence_delay=0.1
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lsp"
  override_cmd={'go': ['gopls', '-remote=127.0.0.1:19191'], 'c': ['ccls', '--log-file=/tmp/ccls.log'], 'plzconfig': ['plz', 'tool', 'lsp'], 'cpp': ['ccls', '--log-file=/tmp/ccls.log']}
  filetypes=['c', 'cpp', 'go', 'plzconfig']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [22:33:23] [ Info ] Startup with no argv, current dir is used: ~/code/src/github.com/perflabs/api
[ SpaceVim ] [22:33:23] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [22:33:23] [ Info ] global_dir is: /home/xxx/.SpaceVim.d/
[ SpaceVim ] [22:33:23] [ Info ] start to apply config [glob]
[ SpaceVim ] [22:33:23] [ Warn ] Failed to enable lsp for plzconfig, plz is not executable!
[ SpaceVim ] [22:33:23] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [22:33:23] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [22:33:23] [ Info ] the func has been added to mode:spell-checking
[   rooter ] [22:33:23] [ Info ] Load projects cache from: /home/xxx/.cache/SpaceVim/projects.json
[   rooter ] [22:33:23] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [22:33:23] [ Info ] Start to find root for: /home/xxx/code/src/github.com/perflabs/api/
[   rooter ] [22:33:23] [ Info ]         (.git/):/home/xxx/code/src/github.com/perflabs/api/
[   rooter ] [22:33:23] [ Info ] buffer name: No Name
[   rooter ] [22:33:23] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [22:33:23] [ Info ] try to open SpaceVim welcome page
[   rooter ] [22:33:23] [ Info ] buffer name: No Name
[   rooter ] [22:33:23] [ Info ] same as current directory, no need to change.
[   rooter ] [22:33:24] [ Info ] Start to find root for: /home/xxx/code/src/github.com/perflabs/api/vimfiler:default
[   rooter ] [22:33:24] [ Info ]         (.git/):/home/xxx/code/src/github.com/perflabs/api/
[   rooter ] [22:33:24] [ Info ] buffer name: vimfiler:default
[   rooter ] [22:33:24] [ Info ] same as current directory, no need to change.
[   rooter ] [22:33:26] [ Info ] buffer name: No Name
[   rooter ] [22:33:26] [ Info ] same as current directory, no need to change.
[   rooter ] [22:33:26] [ Info ] buffer name: vimfiler:default
[   rooter ] [22:33:26] [ Info ] same as current directory, no need to change.
[   rooter ] [22:33:26] [ Info ] buffer name: No Name
[   rooter ] [22:33:26] [ Info ] same as current directory, no need to change.
[   rooter ] [22:33:26] [ Info ] Start to find root for: /home/xxx/code/src/github.com/perflabs/api/README.md
[   rooter ] [22:33:26] [ Info ]         (.git/):/home/xxx/code/src/github.com/perflabs/api/
[   rooter ] [22:33:26] [ Info ] buffer name: README.md
[   rooter ] [22:33:26] [ Info ] same as current directory, no need to change.
```
</details>
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
