### ISSUE TITLE
Denite: <C-j> and <C-k> don't select the next/previous lines

### ISSUE THREAD

**Issue by goetzc** [wsdjeg/SpaceVim#4507]
Hi. Looks like any Denite buffer is not moving the selection to the next/previous lines when using `<C-j>` or `<C-k>`. I think this should already be working, based on this:
https://github.com/SpaceVim/SpaceVim/blob/a74237108a78106757e445d335760cd8165bcef4/config/plugins/denite.vim#L111-L113

## Expected behavior
In a Denite buffer, `<C-j>` or `<C-k>` should select the next/previous lines.

## The reproduce ways from Vim starting
`<Space>ff` or any other Denite buffer show this behavior.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options:

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'custom#after'
  bootstrap_before = 'custom#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'OceanicNext'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['jamessan/vim-gnupg', {'repo': 'jamessan/vim-gnupg', 'overwrite': 1}], ['pearofducks/ansible-vim', {'repo': 'pearofducks/ansible-vim', 'overwrite': 1}], ['Glench/Vim-Jinja2-Syntax', {'repo': 'Glench/Vim-Jinja2-Syntax', 'overwrite': 1}], ['hashivim/vim-terraform', {'repo': 'hashivim/vim-terraform', 'overwrite': 1}], ['tpope/vim-eunuch', {'repo': 'tpope/vim-eunuch', 'overwrite': 1}]]
  data_dir = '/home/goetz/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/goetz/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'org-mode'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers:

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_indentline=0
  indentline_char=''
[[layers]]
  name="core"
  filetree_show_hidden=1
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="tools"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="incsearch"
[[layers]]
  name="sudo"
[[layers]]
  name="tmux"
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lsp"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#ruby"
  enabled_linters=['rubocop']
[[layers]]
  name="lang#sh"
[[layers]]
  name="org"
[[layers]]
  name="tools#mpv"
```

### SpaceVim Health checking:

```log
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
```

### SpaceVim runtime log:

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:11:58] [ Info ] Startup with no argv, current dir is used: ~/.dotfiles
[ SpaceVim ] [18:11:59] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:11:59] [ Info ] global_dir is: /home/goetz/.SpaceVim.d/
[ SpaceVim ] [18:11:59] [ Info ] start to apply config [glob]
[ SpaceVim ] [18:11:59] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:11:59] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:11:59] [ Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [18:11:59] [ Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [18:11:59] [ Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [18:11:59] [ Info ] no func found for mode:fill-column-indicator
[   rooter ] [18:11:59] [ Info ] Load projects cache from: /home/goetz/.cache/SpaceVim/projects.json
[   rooter ] [18:11:59] [ Info ] Start to find root for: /home/goetz/.dotfiles/
[   rooter ] [18:11:59] [ Info ]         (.git/):/home/goetz/.dotfiles/
[   rooter ] [18:11:59] [ Info ] buffer name: No Name
[   rooter ] [18:11:59] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [18:11:59] [ Info ] try to open SpaceVim welcome page
[   rooter ] [18:11:59] [ Info ] buffer name: No Name
[   rooter ] [18:11:59] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots
![image](https://user-images.githubusercontent.com/2220440/139510682-228d27e6-c411-4e44-aa44-db87b51416f1.png)
