### ISSUE TITLE
after update spacevim，the ctrl+d  and ctrl+u move cursor line by line to the target

### ISSUE THREAD

**Issue by sydnash** [wsdjeg/SpaceVim#4514]
## Expected behavior, english is required

after update spacevim，the ctrl+d  and ctrl+u move cursor line by line to the target line.

## The reproduce ways from Vim starting (Required!)

i want the cursor move to the target line immediately, not line by line.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/sydnash/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/sydnash/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-stylus'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'package.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
[[layers]]
  name="gtags"
[[layers]]
  name="lsp"
  filetypes=['c', 'cpp']
[[layers]]
  name="git"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#html"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:35:28] [ Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [15:35:28] [ Info ] find local conf: /Users/sydnash/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [15:35:28] [ Info ] force loading global config >>>
[ SpaceVim ] [15:35:28] [ Info ] global_dir is: /Users/sydnash/.SpaceVim.d/
[ SpaceVim ] [15:35:28] [ Info ] start to apply config [glob]
[ SpaceVim ] [15:35:28] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:35:28] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:35:28] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [15:35:28] [ Info ] Load projects cache from: /Users/sydnash/.cache/SpaceVim/projects.json
[   rooter ] [15:35:28] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [15:35:28] [ Info ] Start to find root for: /Users/sydnash/.SpaceVim/
[   rooter ] [15:35:28] [ Info ]         (.git/):/Users/sydnash/.SpaceVim/
[   rooter ] [15:35:28] [ Info ] buffer name: No Name
[   rooter ] [15:35:28] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [15:35:28] [ Info ] try to open SpaceVim welcome page
[   rooter ] [15:35:28] [ Info ] buffer name: No Name
[   rooter ] [15:35:28] [ Info ] same as current directory, no need to change.
```
</details>
