### ISSUE TITLE
cannot show unicode icon in windows terminal

### ISSUE THREAD

**Issue by johnsonkee** [wsdjeg/SpaceVim#4517]
## Expected behavior, english is recommend
I want to show unicode icon in filetree and status line. For example, the `git status`; and lots of filetype icone including markdown and shell and so on.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.6.0
- SpaceVim version: 1.8.0-dev
- SpaceVim status: 05e45fc0

```
HEAD detached from v1.7.0
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   bundle/neoformat/autoload/neoformat/formatters/python.vim

```

## The reproduce ways from Vim starting (Required!)

I have already installed Dejavu fonts, and other presquistics. I edit my file in remote server through ssh. 

I am using **windows terminal**, whatever I try, it is hard to show any unicode icon.

But strangely, when I switch to MobaXterm, through the same ssh link, the Spacevim can show unicode icon.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['ferrine/md-img-paste.vim', {'repo': 'ferrine/md-img-paste.vim', 'overwrite': 1}]]
  data_dir = '/root/work/spacevim_data/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_gitstatus = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/root/work/spacevim_data/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'markdown-preview.nvim'
  project_rooter_automatically = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.8.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
[[layers]]
  name="tools"
[[layers]]
  name="leaderf"
[[layers]]
  name="lang#markdown"
  enabled_formater=['prettier']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/workspace/volume/johnsonkee-data/tools/squashfs-root/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:29:11] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [11:29:11] [ Info ] Startup with no argv, current dir is used: /workspace/volume/johnsonkee-data/iva_detection
[ SpaceVim ] [11:29:11] [ Info ] find local conf: /workspace/volume/johnsonkee-data/iva_detection/.SpaceVim.d/init.toml
[ SpaceVim ] [11:29:11] [ Info ] loading cached local conf: /root/work/spacevim_data/SpaceVim/conf/_workspace_volume_johnsonkee-data_iva_detection__SpaceVim_d_init_toml.json
[ SpaceVim ] [11:29:11] [ Info ] start to apply config [local]
[ SpaceVim ] [11:29:11] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [11:29:11] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:29:12] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:29:12] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [11:29:12] [ Info ] Load projects cache from: /root/work/spacevim_data/SpaceVim/projects.json
[   rooter ] [11:29:12] [ Info ] Start to find root for: /workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:12] [ Info ]         (.git/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:12] [ Info ]         (.SpaceVim.d/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:12] [ Info ] buffer name: No Name
[   rooter ] [11:29:12] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:12] [ Info ] buffer name: No Name
[   rooter ] [11:29:12] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:29:12] [ Info ] try to open SpaceVim welcome page
[   rooter ] [11:29:12] [ Info ] buffer name: No Name
[   rooter ] [11:29:12] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:21] [ Info ] Start to find root for: /workspace/volume/johnsonkee-data/iva_detection/vimfiler:default
[   rooter ] [11:29:21] [ Info ]         (.git/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:21] [ Info ]         (.SpaceVim.d/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:21] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:29:21] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:24] [ Info ] buffer name: No Name
[   rooter ] [11:29:24] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:24] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:29:24] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:24] [ Info ] buffer name: No Name
[   rooter ] [11:29:24] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:25] [ Info ] Start to find root for: /workspace/volume/johnsonkee-data/iva_detection/README.md
[   rooter ] [11:29:25] [ Info ]         (.git/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:25] [ Info ]         (.SpaceVim.d/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:25] [ Info ] buffer name: README.md
[   rooter ] [11:29:25] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:28] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:29:28] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:30] [ Info ] buffer name: README.md
[   rooter ] [11:29:30] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:30] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:29:30] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:30] [ Info ] buffer name: README.md
[   rooter ] [11:29:30] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:30] [ Info ] Start to find root for: /workspace/volume/johnsonkee-data/iva_detection/run_train.sh
[   rooter ] [11:29:30] [ Info ]         (.git/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:30] [ Info ]         (.SpaceVim.d/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:29:30] [ Info ] buffer name: run_train.sh
[   rooter ] [11:29:30] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:41] [ Info ] buffer name: README.md
[   rooter ] [11:29:41] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:42] [ Info ] buffer name: run_train.sh
[   rooter ] [11:29:42] [ Info ] same as current directory, no need to change.
[   rooter ] [11:29:56] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:29:56] [ Info ] same as current directory, no need to change.
[   rooter ] [11:31:32] [ Info ] buffer name: run_train.sh
[   rooter ] [11:31:32] [ Info ] same as current directory, no need to change.
[   rooter ] [11:33:50] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:33:50] [ Info ] same as current directory, no need to change.
[   rooter ] [11:34:03] [ Info ] buffer name: run_train.sh
[   rooter ] [11:34:03] [ Info ] same as current directory, no need to change.
[   rooter ] [11:42:10] [ Info ] Start to find root for: /workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:42:10] [ Info ]         (.git/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:42:10] [ Info ]         (.SpaceVim.d/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:42:10] [ Info ] buffer name: No Name
[   rooter ] [11:42:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:42:10] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [11:42:10] [ Info ] buffer name: run_train.sh
[   rooter ] [11:42:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:42:10] [ Info ] close float statusline winid:1004
[   rooter ] [11:42:10] [ Info ] Start to find root for: /workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:42:10] [ Info ]         (.git/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:42:10] [ Info ]         (.SpaceVim.d/):/workspace/volume/johnsonkee-data/iva_detection/
[   rooter ] [11:42:10] [ Info ] buffer name: No Name
[   rooter ] [11:42:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:42:10] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [11:42:10] [ Info ] buffer name: run_train.sh
[   rooter ] [11:42:10] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:42:10] [ Info ] close float statusline winid:1006
[   rooter ] [11:42:11] [ Info ] Start to find root for: /tmp/nvimFJHNaB/13/issue_report.md
[   rooter ] [11:42:11] [ Info ] buffer name: /tmp/nvimFJHNaB/13/issue_report.md
[   rooter ] [11:42:11] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

https://asciinema.org/a/V7EVTn9jAmlNg04gj241XQIg5
