### ISSUE TITLE
Ctrl+] (go to definition) fails with PHP language

### ISSUE THREAD

**Issue by edomato** [wsdjeg/SpaceVim#4519]
## Expected behavior, english is required
Jump to definition

## The reproduce ways from Vim starting (Required!)
Open any PHP project with nvim, try to go to definition

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>                                                                                
                                                                                                                                        
### SpaceVim options :                                                                                                                  
                                                                                                                                        
```toml                                                                                                                                 
  auto_disable_touchpad = 1                                                                                                             
  autocomplete_method = 'deoplete'                                                                                                      
  autocomplete_parens = 1                                                                                                               
  buffer_index_type = 4                                                                                                                 
  checkinstall = 1                                                                                                                      
  code_runner_focus = 0                                                                                                                 
  colorscheme = 'gruvbox'                                                                                                               
  colorscheme_bg = 'dark'                                                                                                               
  colorscheme_default = 'desert'                                                                                                        
  commandline_prompt = '➭'                                                                                                              
  custom_color_palette = []                                                                                                             
  custom_plugins = []                                                                                                                   
  data_dir = '/home/edomato/.cache/'                                                                                                    
  debug_level = 1                                                                                                                       
  default_custom_leader = '<Space>'                                                                                                     
  default_indent = 2                                                                                                                    
  disabled_plugins = []                                                                                                                 
  enable_bepo_layout = 0                                                                                                                
  enable_cursorcolumn = 0                                                                                                               
  enable_cursorline = 1                                                                                                                 
  enable_debug = 0                                                                                                                      
  enable_googlesuggest = 0                                                                                                              
  enable_guicolors = 1                                                                                                                  
  enable_javacomplete2_py = 0                                                                                                           
  enable_key_frequency = 0                                                                                                              
  enable_language_specific_leader = 1
  enable_neocomplcache = 0                                                                                                              
  enable_os_fileformat_icon = 0                                                                                                         
  enable_powerline_fonts = 1                                                                                                            
  enable_projects_cache = 1                                                                                                             
  enable_statusline_bfpath = 0                                                                                                          
  enable_statusline_mode = 0                                                                                                            
  enable_statusline_tag = 1                                                                                                             
  enable_tabline_filetype_icon = 1                                                                                                      
  enable_tabline_ft_icon = 0                                                                                                            
  enable_vimfiler_welcome = 1                                                                                                           
  enable_ycm = 0                                                                                                                        
  error_symbol = '✖'                                                                                                                    
  escape_key_binding = 'jk'                                                                                                             
  expand_tab = 1                                                                                                                        
  file_searching_tools = []                                                                                                             
  filemanager = 'nerdtree'                                                                                                              
  filetree_direction = 'right'                                                                                                          
  filetype_icons = {}                                                                                                                   
  force_global_config = 0                                                                                                               
  gitcommit_issue_icon = ''                                                                                                            
  gitcommit_pr_icon = ''                                                                                                               
  github_username = ''                                                                                                                  
  guifont = ''                                                                                                                          
  hiddenfileinfo = 1                                                                                                                    
  home_files_number = 6                                                                                                                 
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'                                                            
  info_symbol = 'ⓘ'                                                                                                                     
  keep_server_alive = 1                                                                                                                 
  language = ''                                                                                                                         
  leader_guide_default_group_name = ''                                                                                                  
  leader_guide_flatten = 1  
  leader_guide_hspace = 5                                                                                                               
  leader_guide_max_size = 0                                                                                                             
  leader_guide_position = 'botright'                                                                                                    
  leader_guide_run_map_on_popup = 1                                                                                                     
  leader_guide_sort_horizontal = 0                                                                                                      
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}                                                                                
  leader_guide_vertical = 0                                                                                                             
  lint_engine = 'neomake'                                                                                                               
  lint_on_save = 1                                                                                                                      
  lint_on_the_fly = 0                                                                                                                   
  max_column = 120                                                                                                                      
  plugin_bundle_dir = '/home/edomato/.cache/vimfiles/'                                                                                  
  plugin_manager = 'dein'                                                                                                               
  plugin_manager_processes = 16                                                                                                         
  plugin_name = 'PHP-Indenting-for-VIm'                                                                                                 
  project_auto_root = 1                                                                                                                 
  project_rooter_outermost = 1                                                                                                          
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']                                              
  projects_cache_num = 20                                                                                                               
  realtime_leader_guide = 1                                                                                                             
  relativenumber = 1                                                                                                                    
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']                                                                    
  sidebar_direction = ''                                                                                                                
  sidebar_width = 30                                                                                                                    
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']                                                                                         
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']                                                                              
  snippet_engine = 'neosnippet'                                                                                                         
  src_root = 'E:\sources\'                                                                                                              
  statusline_iseparator = 'arrow'                                                                                                       
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']              
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']                                                                 
  statusline_separator = 'arrow'                                                                                                        
  statusline_unicode = 1                                                                                                                
  terminal_cursor_shape = 2                                                                                                             
  todo_labels = ['@fixme', '@question', '@todo', '@idea']                                                                               
  update_retry_cnt = 3                                                                                                                  
  version = '1.9.0-dev'                                                                                                                 
  vim_help_language = 'en'                                                                                                              
  vimcompatible = 0                                                                                                                     
  warning_symbol = '⚠'                                                                                                                  
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'                 
  windows_index_type = 3                                                                                                                
  windows_leader = 's'                                                                                                                  
  windows_smartclose = 'q'                                                                                                              
  wrap_line = 0                                                                                                                         
```                                                                                                                                     
                                                                                                                                        
                                                                                                                                        
### SpaceVim layers :                                                                                                                   
                                                                                                                                        
```toml                                                                                                                                 
[[layers]]                                                                                                                              
  name="autocomplete"                                                                                                                   
  auto_completion_return_key_behavior='complete'                                                                                        
  auto_completion_tab_key_behavior='smart'                                                                                              
[[layers]]                                                                                                                              
  name="checkers"                                                                                                                       
[[layers]]                                                                                                                              
  name="format"                                                                                                                         
[[layers]]                                                                                                                              
  name="edit"
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']                                                                 
  statusline_separator = 'arrow'                                                                                                        
  statusline_unicode = 1                                                                                                                
  terminal_cursor_shape = 2                                                                                                             
  todo_labels = ['@fixme', '@question', '@todo', '@idea']                                                                               
  update_retry_cnt = 3                                                                                                                  
  version = '1.9.0-dev'                                                                                                                 
  vim_help_language = 'en'                                                                                                              
  vimcompatible = 0                                                                                                                     
  warning_symbol = '⚠'                                                                                                                  
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'                 
  windows_index_type = 3                                                                                                                
  windows_leader = 's'                                                                                                                  
  windows_smartclose = 'q'                                                                                                              
  wrap_line = 0                                                                                                                         
```                                                                                                                                     
                                                                                                                                        
                                                                                                                                        
### SpaceVim layers :                                                                                                                   
                                                                                                                                        
```toml                                                                                                                                 
[[layers]]                                                                                                                              
  name="autocomplete"                                                                                                                   
  auto_completion_return_key_behavior='complete'                                                                                        
  auto_completion_tab_key_behavior='smart'                                                                                              
[[layers]]                                                                                                                              
  name="checkers"                                                                                                                       
[[layers]]                                                                                                                              
  name="format"                                                                                                                         
[[layers]]                                                                                                                              
  name="edit"          
[[layers]]                                                                                                                              
  name="ui"                                                                                                                             
[[layers]]                                                                                                                              
  name="core"                                                                                                                           
[[layers]]                                                                                                                              
  name="core#banner"                                                                                                                    
[[layers]]                                                                                                                              
  name="core#statusline"                                                                                                                
[[layers]]                                                                                                                              
  name="core#tabline"                                                                                                                   
[[layers]]                                                                                                                              
  name="shell"                                                                                                                          
  default_position='bottom'                                                                                                             
  default_height=35                                                                                                                     
[[layers]]                                                                                                                              
  name="denite"                                                                                                                         
[[layers]]                                                                                                                              
  name="gtags"                                                                                                                          
  gtagslabel='ctags'                                                                                                                    
[[layers]]                                                                                                                              
  name="git"                                                                                                                            
[[layers]]                                                                                                                              
  name="lang#php"                                                                                                                       
```                                                                                                                                     
                                                                                                                                        
                                                                                                                                        
### SpaceVim Health checking :                                                                                                          
                                                                                                                                        
SpaceVim clipboard support check report:                                                                                                
Checking +clipboard:                                                                                                                    
      SUCCEED!
Checking +python:                                                                                                                       
      Failed : to support +python, you need run `pip2 install neovim`                                                                   
                                                                                                                                        
### SpaceVim runtime log :                                                                                                              
                                                                                                                                        
```log                                                                                                                                  
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!                                                
[ SpaceVim ] [00:32:50] [ Error] Can not set language to en_US.utf8                                                                     
[ SpaceVim ] [00:32:50] [ Info ] Startup with no argv, current dir is used: ~/devel/GeekBunker/Dora/git/dorashop                        
[ SpaceVim ] [00:32:50] [ Info ] Can not find project local config, start loading global config                                         
[ SpaceVim ] [00:32:50] [ Info ] global_dir is: /home/edomato/.SpaceVim.d/                                                              
[ SpaceVim ] [00:32:50] [ Info ] start to apply config [glob]                                                                           
[ SpaceVim ] [00:32:50] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server                                                   
[ SpaceVim ] [00:32:50] [ Info ] the func has been added to mode:syntax-checking                                                        
[ SpaceVim ] [00:32:50] [ Info ] the func has been added to mode:spell-checking                                                         
[ SpaceVim ] [00:32:50] [ Info ] the func has been added to mode:paste-mode                                                             
[ SpaceVim ] [00:32:50] [ Info ] try to call func of mode:whitespace                                                                    
[ SpaceVim ] [00:32:50] [ Info ] no func found for mode:whitespace                                                                      
[   rooter ] [00:32:50] [ Info ] Load projects cache from: /home/edomato/.cache/SpaceVim/projects.json                                  
[   rooter ] [00:32:50] [ Info ] Start to find root for: /home/edomato/devel/GeekBunker/Dora/git/dorashop/                              
[   rooter ] [00:32:50] [ Info ]         (.git/):/home/edomato/devel/GeekBunker/Dora/git/dorashop/                                      
[   rooter ] [00:32:50] [ Info ] buffer name: No Name                                                                                   
[   rooter ] [00:32:50] [ Info ] same as current directory, no need to change.                                                          
[ SpaceVim ] [00:32:50] [ Info ] try to open SpaceVim welcome page                                                                      
[   rooter ] [00:32:50] [ Info ] buffer name: No Name                                                                                   
[   rooter ] [00:32:50] [ Info ] same as current directory, no need to change.                                                          
[   rooter ] [00:32:56] [ Info ] Start to find root for: /home/edomato/devel/GeekBunker/Dora/git/dorashop/src/Controller/CarritoControll
er.php                                                                                                                                  
[   rooter ] [00:32:56] [ Info ]         (.git/):/home/edomato/devel/GeekBunker/Dora/git/dorashop/                                      
[   rooter ] [00:32:56] [ Info ] buffer name: /home/edomato/devel/GeekBunker/Dora/git/dorashop/src/Controller/CarritoController.php     
[   rooter ] [00:32:56] [ Info ] same as current directory, no need to change.
[   rooter ] [00:32:56] [ Info ] same as current directory, no need to change.                                                          
```                                                                                                                                     
</details> 

## Screenshots
![imagen](https://user-images.githubusercontent.com/1550373/141404534-35624f0e-2c3a-4ebb-9498-99fb66041486.png)
