### ISSUE TITLE
Can't switch syntax checker

### ISSUE THREAD

**Issue by UltraBlackLinux** [wsdjeg/SpaceVim#4520]
## Expected behavior, english is required
It should check the syntax and switch the syntax checker (C++), but it doesn't.
Even after setting the lint engine to syntastic it still seems to use the broken Neomake.

## The reproduce ways from Vim starting (Required!)
Use my config and edit any C++ file

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'one'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/maus/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/maus/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'tagbar-markdown'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
  lint_engine='syntastic'
  lint_on_the_fly=1
[[layers]]
  name="format"
  format_on_save=1
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=1
  enable_indentline=1
  enable_scrollbar=0
  concealcursor=''
  enable_cursorword=0
  cursorword_exclude_filetype=[]
  indentline_char='|'
  cursorword_delay=50
  indentline_exclude_filetyps=[]
  conceallevel=0
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=0
[[layers]]
  name="lang#markdown"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:17:31] [ Info ] Startup with argv: ['/sbin/nvim', '/home/maus/Cxx/WordSearch/src/WordSearch.cpp']
[ SpaceVim ] [11:17:31] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:17:31] [ Info ] global_dir is: /home/maus/.SpaceVim.d/
[ SpaceVim ] [11:17:31] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:17:31] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [11:17:31] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:17:31] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:17:31] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [11:17:31] [ Info ] Load projects cache from: /home/maus/.cache/SpaceVim/projects.json
[   rooter ] [11:17:31] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [11:17:31] [ Info ] Start to find root for: /home/maus/Cxx/WordSearch/src/WordSearch.cpp
[   rooter ] [11:17:31] [ Info ]         (.git/):/home/maus/Cxx/WordSearch/
[   rooter ] [11:17:31] [ Info ] buffer name: /home/maus/Cxx/WordSearch/src/WordSearch.cpp
[   rooter ] [11:17:31] [ Info ] change to root: /home/maus/Cxx/WordSearch/
[   rooter ] [11:17:31] [ Info ] buffer name: src/WordSearch.cpp
[   rooter ] [11:17:31] [ Info ] same as current directory, no need to change.
```
</details>

### SpaceVim options :
[init.toml.txt](https://github.com/SpaceVim/SpaceVim/files/7533532/init.toml.txt)

Is there something I missed about the syntax checking?
Thanks!
