### ISSUE TITLE
Several Errors when starting spacevim

### ISSUE THREAD

**Issue by MagicRedDeer** [wsdjeg/SpaceVim#4522]
## Expected behavior, english is required

Spacevim starts as expected and shows startup screen

## The reproduce ways from Vim starting (Required!)

1. Just install spacevim commit `283939971496825f122bf27a13432ddf1e78c16e`

2. start vim or neovim

3. The following error shows up:

[ SpaceVim ] [15:40:42] [ Warn ] Failed to generate helptags for SpaceVim
Error detected while processing function SpaceVim#end[101]..SpaceVim#plugins#load[2]..SpaceVim#plugins#begin:
line    9:
E117: Unknown function: dein#begin
Error detected while processing function SpaceVim#layers#core#statusline#get[209]..<SNR>39_active:
line   15:
E121: Undefined variable: s:lsep
E116: Invalid arguments for function 125
E15: Invalid expression: s:STATUSLINE.build(lsec, rsec, s:lsep, s:rsep, fname, tag, 'SpaceVim_statusline_a', 'SpaceVim_statusline_b', 'SpaceVim_statusline_c', 'SpaceVim_statusline_z', winwidth(winnr()))

I am using windows 10

The error goes away when I step one commit back.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 0
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['tmhedberg/SimpylFold', {'repo': 'tmhedberg/SimpylFold', 'merged': 0}], ['Coacher/vim-virtualenv', {'repo': 'Coacher/vim-virtualenv', 'merged': 0}], ['vim-scripts/Tail-Bundle', {'repo': 'vim-scripts/Tail-Bundle', 'merged': 0}], ['https://gitlab.com/LazyLeopard/vimya', {'depends': 'vim-scripts/Tail-Bundle', 'repo': 'https://gitlab.com/LazyLeopard/vimya', 'merged': 0}], ['Coacher/vim-virtualenv', {'repo': 'Coacher/vim-virtualenv', 'merged': 0}], ['bkad/CamelCaseMotion', {'repo': 'bkad/CamelCaseMotion', 'merged': 0}], ['xolox/vim-misc', {'repo': 'xolox/vim-misc', 'merged': 0}], ['xolox/vim-session', {'repo': 'xolox/vim-session', 'merged': 0}]]
  data_dir = 'C:\Users\talha.ahmed\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_filetree_gitstatus = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'BitstreamVeraSansMono Nerd Font:h9'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\talha.ahmed\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'curve'
  statusline_unicode = 1
  statusline_unicode_symbols = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  filetree_show_hidden=1
  enable_smooth_scrolling=1
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
[[layers]]
  name="lang#python"
  enabled_linters=['flake8']
[[layers]]
  name="gtags"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#sh"
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lsp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\tools\neovim\Neovim\bin\nvim.exe)
version: 800
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:43:57] [ Info ] start to loading SpaceVim!
[ SpaceVim ] [15:43:57] [ Info ] init spacevim root dir:C:/Users/talha.ahmed/AppData/Local/nvim
[ SpaceVim ] [15:43:58] [ Info ] Startup with no argv, current dir is used: ~\.SpaceVim
[ SpaceVim ] [15:43:58] [ Info ] find local conf: C:/Users/talha.ahmed/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [15:43:58] [ Info ] force loading global config >>>
[ SpaceVim ] [15:43:58] [ Info ] global_dir is: C:/Users/talha.ahmed/.SpaceVim.d/
[ SpaceVim ] [15:43:58] [ Info ] start to apply config [glob]
[ SpaceVim ] [15:43:58] [ Warn ] Failed to generate helptags for SpaceVim
[ SpaceVim ] [15:43:58] [ Info ] finished loading SpaceVim!
[ SpaceVim ] [15:43:58] [ Info ] try to open SpaceVim welcome page
```
</details>

## Screenshots

![nvim](https://user-images.githubusercontent.com/3265849/141769287-1946a808-2c6b-4988-a5ac-f44d1360372a.PNG)
