### ISSUE TITLE
[g d] goto-definition not working in python

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4526]
## Expected behavior, english is required

`g d` is supposed to go to variable definition

## The reproduce ways from Vim starting (Required!)

With this python code in a file opened in SpaceVim

```python
a = 'hi'
print(a)
```

1. Place cursor on the second line, character `a`
2. Use [g d] shortcut

I have this error message :

```
Error detected while processing function SpaceVim#mapping#gd[2]..<SNR>55_go_to_def[5]..SpaceVim#lsp#go_to_def:
line    1:
E117: Unknown function: LanguageClient_textDocument_definition
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/mgedmin/python-imports.vim.git', {'repo': 'https://github.com/mgedmin/python-imports.vim.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/puremourning/vimspector.git', {'repo': 'https://github.com/puremourning/vimspector.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/ludovicchabant/vim-gutentags.git', {'repo': 'https://github.com/ludovicchabant/vim-gutentags.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/vim-scripts/argtextobj.vim', {'repo': 'https://github.com/vim-scripts/argtextobj.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/KabbAmine/zeavim.vim', {'repo': 'https://github.com/KabbAmine/zeavim.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'JetBrainsMono Nerd Font Mono:h10.5:l'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Denite-sources'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left_sections = ['major mode', 'filename', 'version control info', 'vcs', 'hunks']
  statusline_right_sections = ['cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:28:15] [0.000] [ Info ] start to loading SpaceVim!
[ SpaceVim ] [16:28:15] [0.000] [ Info ] init spacevim root dir:/home/jacky/.SpaceVim/
[ SpaceVim ] [16:28:15] [0.071] [ Info ] Startup with argv: ['failed to get v:argv']
[ SpaceVim ] [16:28:15] [0.075] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [16:28:15] [0.075] [ Info ] global_dir is: /home/jacky/.SpaceVim.d/
[ SpaceVim ] [16:28:15] [0.075] [ Info ] start to apply config [glob]
[ SpaceVim ] [16:28:15] [0.097] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:28:15] [0.135] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:28:15] [0.135] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [16:28:15] [0.154] [ Info ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[ SpaceVim ] [16:28:15] [0.184] [ Info ] finished loading SpaceVim!
[   rooter ] [16:28:15] [0.287] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [16:28:15] [0.288] [ Info ] Start to find root for: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:28:15] [0.288] [ Info ] buffer name: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:28:15] [0.288] [ Info ] same as current directory, no need to change.
[   rooter ] [16:28:15] [0.291] [ Info ] buffer name: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:28:15] [0.291] [ Info ] same as current directory, no need to change.
[   rooter ] [16:31:35] [199.715] [ Info ] Start to find root for: /home/jacky/Documents/Client-projects/2010_09_inrae_assainissement/
[   rooter ] [16:31:35] [199.715] [ Info ]         (.git/):/home/jacky/Documents/Client-projects/2010_09_inrae_assainissement/
[   rooter ] [16:31:35] [199.716] [ Info ] buffer name: No Name
[   rooter ] [16:31:35] [199.716] [ Info ] same as current directory, no need to change.
[   rooter ] [16:31:35] [199.736] [ Info ] Start to find root for: /usr/share/nvim/runtime/doc/various.txt
[   rooter ] [16:31:35] [199.737] [ Info ] buffer name: /usr/share/nvim/runtime/doc/various.txt
[   rooter ] [16:31:35] [199.737] [ Info ] same as current directory, no need to change.
[   rooter ] [16:31:52] [216.917] [ Info ] buffer name: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:31:52] [216.917] [ Info ] same as current directory, no need to change.
[   rooter ] [16:32:14] [239.202] [ Info ] Start to find root for: /home/jacky/Documents/Client-projects/2010_09_inrae_assainissement/
[   rooter ] [16:32:14] [239.202] [ Info ]         (.git/):/home/jacky/Documents/Client-projects/2010_09_inrae_assainissement/
[   rooter ] [16:32:14] [239.204] [ Info ] buffer name: No Name
[   rooter ] [16:32:14] [239.204] [ Info ] same as current directory, no need to change.
[   rooter ] [16:32:14] [239.213] [ Info ] buffer name: /usr/share/nvim/runtime/doc/various.txt
[   rooter ] [16:32:14] [239.213] [ Info ] same as current directory, no need to change.
[   rooter ] [16:32:36] [261.010] [ Info ] buffer name: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:32:36] [261.010] [ Info ] same as current directory, no need to change.
[   rooter ] [16:33:50] [334.699] [ Info ] Start to find root for: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:33:50] [334.700] [ Info ] buffer name: /home/jacky/Bureau/asuppr.py
[   rooter ] [16:33:50] [334.701] [ Info ] same as current directory, no need to change.
```
</details>
