### ISSUE TITLE
use coc.nvim with python, got E117: Unknown function: jedi#goto error while press gd

### ISSUE THREAD

**Issue by sydnash** [wsdjeg/SpaceVim#4531]
## Expected behavior, english is required
i want jump to declaration while press the gd command.

## The reproduce ways from Vim starting (Required!)
vim main.py which has the follow content:
```python
a = 1
print(a)
```
move cursor to print and press gd command in normal mode.
## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/sydnash/.cache/'
  debug_level = 1
  default_custom_leader = ';'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  mapleader = '\'
  max_column = 120
  plugin_bundle_dir = '/Users/sydnash/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'helpful.vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
  statusline_right_sections = ['cursorpos', 'percentage', 'input method', 'date', 'time']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'qq'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  enable_smooth_scrolling=0
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="incsearch"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#c"
  clang_executable='/usr/bin/clang'
[[layers]]
  name="gtags"
[[layers]]
  name="lsp"
  filetypes=['c', 'cpp', 'go', 'python']
[[layers]]
  name="git"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#json"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(vim)
version: 802
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:42:11] [0.000] [ Info ] start to loading SpaceVim!
[ SpaceVim ] [12:42:11] [0.000] [ Info ] init spacevim root dir:/Users/sydnash/.SpaceVim/
[ SpaceVim ] [12:42:11] [0.014] [ Info ] Startup with argv: ['vim', 'main.py']
[ SpaceVim ] [12:42:11] [0.020] [ Info ] find local conf: /Users/sydnash/.SpaceVim.d/init.toml
[ SpaceVim ] [12:42:11] [0.021] [ Info ] loading cached local conf: /Users/sydnash/.cache/SpaceVim/conf/_Users_sydnash__SpaceVim_d_init_toml.json
[ SpaceVim ] [12:42:11] [0.021] [ Info ] start to apply config [local]
[ SpaceVim ] [12:42:11] [0.048] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:42:11] [0.066] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:42:11] [0.066] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [12:42:11] [0.086] [ Info ] Load projects cache from: /Users/sydnash/.cache/SpaceVim/projects.json
[ SpaceVim ] [12:42:11] [0.120] [ Info ] finished loading SpaceVim!
[   rooter ] [12:42:12] [0.568] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [12:42:12] [0.568] [ Info ] Start to find root for: /Users/sydnash/main.py
[   rooter ] [12:42:12] [0.569] [ Info ] buffer name: main.py
[   rooter ] [12:42:12] [0.569] [ Info ] same as current directory, no need to change.
[   rooter ] [12:42:12] [0.595] [ Info ] buffer name: main.py
[   rooter ] [12:42:12] [0.595] [ Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/5484932/143810573-4e3cf0b4-83b5-43cb-822b-7bb88b5ab043.png)
