### ISSUE TITLE
Termux python autocomplete not working as expected

### ISSUE THREAD

**Issue by Nebdir** [wsdjeg/SpaceVim#4538]
## Environment
Android11
Termux 0.117(fdroid)

## Expected behavior, english is required
Ive done a fresh install in termux.
Ive read the documents for installing and configurating spacevim.
Ive also read the documents about autocomplete and SP as python ide.
Ive tried my best to follow all suggestion to not to miss anything, but i cannot get python autocomplete working. Or its working as you would expect it and ive missread any point.

Edit: after reviewing before posting ive rechecked that neovim for python is installed. But SP doesnt seems to recognize it correctly.

## The reproduce ways from Vim starting
1. Open python file
2. Enter insert mode
3. Start typing

Expected autocomplete starting at any point, suggesting any python function.

Actually only completion from buffer are shown

## Output of the `:SPDebugInfo!`
(Sry, ive copy pasted that as im doing all via android)

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/data/data/com.termux/files/home/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk
/hosts/master/hosts'
info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}

  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/data/data/com.termux/files/home/
.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-pythonsense'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/',
 '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'find
str', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'S
paceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'Hel
pDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceV
imTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default
']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left_sections = ['winnr', 'filename', 'majo
r mode', 'search count', 'syntax checking', 'minor mode
lighters']
  statusline_right_sections = ['fileformat', 'cursorpos'
, 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea'
]
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store
,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  python_interpreter='/data/data/com.termux/files/usr/bi
n/python3'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one o
f following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/
pocke/lemonade
               5. doitclient (for SSH) http://www.chiark
.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/data/data/com.termux/files/usr/b
in/nvim)
version: 800
[shell, shellcmdflag, shellslash]: ['/data/data/com.term
ux/files/usr/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua no
w.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 i
nstall neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 in
      Failed : to support +python, you need run `pip2 in
stall neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log fo
r current process will be shown!
[ SpaceVim ] [22:25:11] [0.003] [ Info ] start to loadin
g SpaceVim!
[ SpaceVim ] [22:25:11] [0.004] [ Info ] init spacevim r
oot dir:/data/data/com.termux/files/home/.SpaceVim/
[ SpaceVim ] [22:25:11] [0.497] [ Info ] Startup with ar
gv: ['nvim', 'py/main.py']
[ SpaceVim ] [22:25:11] [0.542] [ Info ] find local conf
: /data/data/com.termux/files/home/.SpaceVim.d/init.toml
[ SpaceVim ] [22:25:11] [0.542] [ Info ] loading cached
local conf: /data/data/com.termux/files/home/.cache/Spac
eVim/conf/_data_data_com_termux_files_home__SpaceVim_d_i
nit_toml.json
[ SpaceVim ] [22:25:11] [0.543] [ Info ] start to apply
config [local]
[ SpaceVim ] [22:25:12] [0.695] [ Info ] the func has be
en added to mode:syntax-checking
[ SpaceVim ] [22:25:12] [0.777] [ Info ] the func has be
en added to mode:spell-checking
[ SpaceVim ] [22:25:12] [0.777] [ Info ] the func has be
en added to mode:paste-mode
[ SpaceVim ] [22:25:12] [0.969] [ Info ] finished loadin
g SpaceVim!
[   rooter ] [22:25:12] [1.293] [ Info ] Load projects c
ache from: /data/data/com.termux/files/home/.cache/Space
Vim/projects.json
[   rooter ] [22:25:17] [6.610] [ Info ] Start to find r
oot for: /data/data/com.termux/files/home/
[   rooter ] [22:25:18] [6.618] [ Info ] buffer name: No
 Name
[   rooter ] [22:25:18] [6.618] [ Info ] same as current
 directory, no need to change.
[ SpaceVim ] [22:25:18] [6.654] [ Info ] key binding gui
de float statusline winid:1003
[   rooter ] [22:25:20] [9.248] [ Info ] Start to find r
oot for: /data/data/com.termux/files/home/py/main.py
[   rooter ] [22:25:20] [9.252] [ Info ] buffer name: py
/main.py
[   rooter ] [22:25:20] [9.252] [ Info ] same as current
 directory, no need to change.
[ SpaceVim ] [22:25:20] [9.253] [ Info ] close float sta
tusline winid:1003
[   rooter ] [22:25:20] [9.276] [ Info ] Start to find r
oot for: /data/data/com.termux/files/home/
[   rooter ] [22:25:20] [9.280] [ Info ] buffer name: No
 Name
[   rooter ] [22:25:20] [9.280] [ Info ] same as current
 directory, no need to change.
[ SpaceVim ] [22:25:20] [9.313] [ Info ] key binding gui
de float statusline winid:1005
[   rooter ] [22:25:24] [12.703] [ Info ] buffer name: p
y/main.py
[   rooter ] [22:25:24] [12.703] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:25:24] [12.704] [ Info ] close float st
atusline winid:1005
[   rooter ] [22:25:28] [17.456] [ Info ] Start to find
root for: /data/data/com.termux/files/home/
[   rooter ] [22:25:28] [17.459] [ Info ] buffer name: N
o Name
[   rooter ] [22:25:28] [17.459] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:25:28] [17.493] [ Info ] key binding gu
ide float statusline winid:1007
[   rooter ] [22:25:28] [17.578] [ Info ] buffer name: p
y/main.py
[   rooter ] [22:25:28] [17.578] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:25:28] [17.579] [ Info ] close float st
atusline winid:1007
[   rooter ] [22:25:28] [17.602] [ Info ] Start to find
root for: /data/data/com.termux/files/home/
[   rooter ] [22:25:28] [17.606] [ Info ] buffer name: N
o Name
[   rooter ] [22:25:28] [17.606] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:25:29] [17.640] [ Info ] key binding gu
ide float statusline winid:1009
[   rooter ] [22:25:29] [18.283] [ Info ] buffer name: p
y/main.py
[   rooter ] [22:25:29] [18.283] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:25:29] [18.284] [ Info ] close float st
atusline winid:1009
[   rooter ] [22:25:29] [18.322] [ Info ] Start to find
root for: /data/data/com.termux/files/home/__runner__
[   rooter ] [22:25:29] [18.326] [ Info ] buffer name: _
_runner__
[   rooter ] [22:25:29] [18.326] [ Info ] same as curren
t directory, no need to change.
[   rooter ] [22:25:29] [18.379] [ Info ] buffer name: p
y/main.py
[   rooter ] [22:25:29] [18.379] [ Info ] same as curren
t directory, no need to change.
[   runner ] [22:25:29] [18.380] [ Info ]    cmd:['/data
/data/com.termux/files/usr/bin/python3', '-']
[   rooter ] [22:26:02] [51.466] [ Info ] Start to find
root for: /data/data/com.termux/files/home/
[   rooter ] [22:26:02] [51.469] [ Info ] buffer name: N
o Name
[   rooter ] [22:26:02] [51.470] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:26:02] [51.502] [ Info ] key binding gu
ide float statusline winid:1012
[   rooter ] [22:26:06] [55.090] [ Info ] buffer name: p
y/main.py
[   rooter ] [22:26:06] [55.090] [ Info ] same as curren
t directory, no need to change.
[ SpaceVim ] [22:26:06] [55.092] [ Info ] close float st
atusline winid:1012
[   rooter ] [22:28:09] [178.439] [ Info ] Start to find
 root for: /data/data/com.termux/files/home/SpaceVimLaye
rs
[   rooter ] [22:28:09] [178.442] [ Info ] buffer name:
SpaceVimLayers
[   rooter ] [22:28:09] [178.442] [ Info ] same as curre
nt directory, no need to change.
[   rooter ] [22:29:18] [246.742] [ Info ] buffer name:
py/main.py
[   rooter ] [22:29:18] [246.743] [ Info ] same as curre
nt directory, no need to change.
[   rooter ] [22:34:22] [550.824] [ Info ] Start to find
 root for: /data/data/com.termux/files/home/.SpaceVim.d/init.toml
[   rooter ] [22:34:22] [550.828] [ Info ] buffer name:
/data/data/com.termux/files/home/.SpaceVim.d/init.toml
[   rooter ] [22:34:22] [550.828] [ Info ] same as curre
nt directory, no need to change.
[   rooter ] [22:34:32] [561.365] [ Info ] buffer name:
py/main.py
[   rooter ] [22:34:32] [561.366] [ Info ] same as curre
nt directory, no need to change.
```
</details>

## Screenshots
![Screenshot_20211204-223725.png](https://user-images.githubusercontent.com/6737610/144725322-990e22b7-beec-4ff2-9f83-b28835683fda.png)

![Screenshot_20211204-224006.png](https://user-images.githubusercontent.com/6737610/144725404-bdb713aa-7491-4fad-b5c1-6efc8de35866.png)
