### ISSUE TITLE
SpaceVim#mapping#gd() not working with multiple results

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4544]
## Expected behavior, english is required

When using the `gd` mapping, which callls `SpaceVim#mapping#gd()` on a function that is found at multiple places in tags, I should be able to select one result by typing the number I want to go to.

![image](https://user-images.githubusercontent.com/34267385/145985015-2abaedce-0329-4c20-9e9b-5fdfe545cbff.png)

# Problem

But typing a number causes the pop up to close instantly. 

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/mgedmin/python-imports.vim.git', {'repo': 'https://github.com/mgedmin/python-imports.vim.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/puremourning/vimspector.git', {'repo': 'https://github.com/puremourning/vimspector.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/ludovicchabant/vim-gutentags.git', {'repo': 'https://github.com/ludovicchabant/vim-gutentags.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/vim-scripts/argtextobj.vim', {'repo': 'https://github.com/vim-scripts/argtextobj.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/KabbAmine/zeavim.vim', {'repo': 'https://github.com/KabbAmine/zeavim.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'JetBrainsMono Nerd Font Mono:h10.5:l'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Denite-sources'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left_sections = ['major mode', 'filename', 'version control info', 'vcs', 'hunks']
  statusline_right_sections = ['cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:46:10] [0.000] [ Info ] start to loading SpaceVim!
[ SpaceVim ] [11:46:10] [0.000] [ Info ] init spacevim root dir:/home/jacky/.SpaceVim/
[ SpaceVim ] [11:46:10] [0.072] [ Info ] Startup with no argv, current dir is used: ~/sandbox/QGIS
[ SpaceVim ] [11:46:10] [0.077] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:46:10] [0.077] [ Info ] global_dir is: /home/jacky/.SpaceVim.d/
[ SpaceVim ] [11:46:10] [0.077] [ Info ] start to apply config [glob]
[ SpaceVim ] [11:46:10] [0.080] [ Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [11:46:10] [0.100] [ Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:46:10] [0.138] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:46:10] [0.138] [ Info ] the func has been added to mode:paste-mode
[   rooter ] [11:46:10] [0.160] [ Info ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[ SpaceVim ] [11:46:10] [0.194] [ Info ] finished loading SpaceVim!
[   rooter ] [11:46:10] [0.244] [ Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [11:46:10] [0.244] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:10] [0.245] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:10] [0.245] [ Info ] buffer name: No Name
[   rooter ] [11:46:10] [0.245] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:10] [0.250] [ Info ] try to open SpaceVim welcome page
[   rooter ] [11:46:10] [0.322] [ Info ] buffer name: No Name
[   rooter ] [11:46:10] [0.323] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:11] [1.261] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:11] [1.261] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:11] [1.262] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:11] [1.262] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:19] [8.632] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:19] [8.632] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:19] [8.632] [ Info ] buffer name: No Name
[   rooter ] [11:46:19] [8.632] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:19] [8.646] [ Info ] key binding guide float statusline winid:1004
[   rooter ] [11:46:19] [8.791] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:19] [8.791] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:19] [8.795] [ Info ] close float statusline winid:1004
[   rooter ] [11:46:19] [8.801] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:19] [8.801] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:19] [8.802] [ Info ] buffer name: No Name
[   rooter ] [11:46:19] [8.802] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:19] [8.814] [ Info ] key binding guide float statusline winid:1006
[   rooter ] [11:46:21] [10.991] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:21] [10.991] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:21] [10.995] [ Info ] close float statusline winid:1006
[   rooter ] [11:46:23] [12.772] [ Info ] Start to find root for: git://diff
[   rooter ] [11:46:23] [12.772] [ Info ] buffer name: git://diff
[   rooter ] [11:46:23] [12.773] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:24] [13.671] [ Info ] buffer name: git://diff
[   rooter ] [11:46:24] [13.671] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:29] [19.360] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:29] [19.360] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:35] [24.845] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:35] [24.846] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:35] [24.846] [ Info ] buffer name: No Name
[   rooter ] [11:46:35] [24.846] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:35] [24.859] [ Info ] key binding guide float statusline winid:1010
[   rooter ] [11:46:35] [24.872] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:35] [24.872] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:35] [24.876] [ Info ] close float statusline winid:1010
[   rooter ] [11:46:35] [24.882] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:35] [24.882] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:35] [24.883] [ Info ] buffer name: No Name
[   rooter ] [11:46:35] [24.883] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:35] [24.896] [ Info ] key binding guide float statusline winid:1012
[   rooter ] [11:46:36] [26.127] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:36] [26.127] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:36] [26.131] [ Info ] close float statusline winid:1012
[   rooter ] [11:46:37] [27.354] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:37] [27.355] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:37] [27.356] [ Info ] buffer name: No Name
[   rooter ] [11:46:37] [27.356] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:37] [27.377] [ Info ] key binding guide float statusline winid:1014
[   rooter ] [11:46:40] [29.857] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:40] [29.857] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:40] [29.862] [ Info ] close float statusline winid:1014
[   rooter ] [11:46:40] [29.873] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:40] [29.873] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:40] [29.874] [ Info ] buffer name: No Name
[   rooter ] [11:46:40] [29.875] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:40] [29.897] [ Info ] key binding guide float statusline winid:1016
[   rooter ] [11:46:42] [31.765] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:42] [31.765] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:42] [31.769] [ Info ] close float statusline winid:1016
[   rooter ] [11:46:42] [31.774] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:46:42] [31.775] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:42] [31.775] [ Info ] buffer name: No Name
[   rooter ] [11:46:42] [31.775] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:42] [31.787] [ Info ] key binding guide float statusline winid:1018
[   rooter ] [11:46:44] [34.181] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:44] [34.181] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:46:44] [34.186] [ Info ] close float statusline winid:1018
[     repl ] [11:46:44] [34.194] [ Info ] start repl for filetype:c
[     repl ] [11:46:44] [34.194] [ Info ] get the command:c
[   rooter ] [11:46:44] [34.207] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/__REPL__
[   rooter ] [11:46:44] [34.207] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:44] [34.208] [ Info ] buffer name: __REPL__
[   rooter ] [11:46:44] [34.208] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:44] [34.224] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:44] [34.224] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:47] [37.431] [ Info ] buffer name: __REPL__
[   rooter ] [11:46:47] [37.431] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:47] [37.441] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/vimfiler:default
[   rooter ] [11:46:47] [37.441] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:46:47] [37.442] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:46:47] [37.442] [ Info ] same as current directory, no need to change.
[   rooter ] [11:46:47] [37.452] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:46:47] [37.452] [ Info ] same as current directory, no need to change.
[   rooter ] [11:47:19] [68.760] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/src/core/vector/qgsvectorlayereditbuffer.h
[   rooter ] [11:47:19] [68.760] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:47:19] [68.761] [ Info ] buffer name: src/core/vector/qgsvectorlayereditbuffer.h
[   rooter ] [11:47:19] [68.761] [ Info ] same as current directory, no need to change.
[   rooter ] [11:47:21] [71.528] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:47:21] [71.528] [ Info ] same as current directory, no need to change.
[   rooter ] [11:47:24] [74.070] [ Info ] buffer name: src/core/vector/qgsvectorlayereditbuffer.h
[   rooter ] [11:47:24] [74.070] [ Info ] same as current directory, no need to change.
[   rooter ] [11:47:25] [75.336] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:47:25] [75.336] [ Info ] same as current directory, no need to change.
[   rooter ] [11:50:28] [258.175] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:50:28] [258.176] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:50:28] [258.178] [ Info ] buffer name: No Name
[   rooter ] [11:50:28] [258.178] [ Info ] same as current directory, no need to change.
[   rooter ] [11:50:30] [259.658] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/
[   rooter ] [11:50:30] [259.659] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:50:30] [259.659] [ Info ] buffer name: No Name
[   rooter ] [11:50:30] [259.659] [ Info ] same as current directory, no need to change.
[ SpaceVim ] [11:50:30] [259.685] [ Info ] key binding guide float statusline winid:1022
[ SpaceVim ] [11:50:31] [260.628] [ Info ] close float statusline winid:1022
[   rooter ] [11:50:31] [261.207] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:50:31] [261.207] [ Info ] same as current directory, no need to change.
[   rooter ] [11:50:33] [263.470] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:50:33] [263.470] [ Info ] same as current directory, no need to change.
[   rooter ] [11:50:36] [265.739] [ Info ] buffer name: [Command Line]
[   rooter ] [11:50:36] [265.739] [ Info ] same as current directory, no need to change.
[   rooter ] [11:50:36] [266.418] [ Info ] buffer name: vimfiler:default
[   rooter ] [11:50:36] [266.418] [ Info ] same as current directory, no need to change.
[   rooter ] [11:50:55] [284.647] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:50:55] [284.647] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:06] [416.012] [ Info ] buffer name: src/core/vector/qgsvectorlayereditbuffer.h
[   rooter ] [11:53:06] [416.012] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:09] [418.919] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:53:09] [418.919] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:11] [420.741] [ Info ] buffer name: src/core/vector/qgsvectorlayereditbuffer.h
[   rooter ] [11:53:11] [420.741] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:11] [421.500] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:53:11] [421.500] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:14] [424.448] [ Info ] Start to find root for: /home/jacky/sandbox/QGIS/src/core/qgsproperty.cpp
[   rooter ] [11:53:14] [424.448] [ Info ]         (.git/):/home/jacky/sandbox/QGIS/
[   rooter ] [11:53:14] [424.449] [ Info ] buffer name: src/core/qgsproperty.cpp
[   rooter ] [11:53:14] [424.449] [ Info ] same as current directory, no need to change.
[   rooter ] [11:53:18] [427.950] [ Info ] buffer name: src/gui/attributetable/qgsfeaturelistmodel.cpp
[   rooter ] [11:53:18] [427.951] [ Info ] same as current directory, no need to change.
```
</details>
