### ISSUE TITLE
init.toml does not take effect immediately

### ISSUE THREAD

**Issue by Tokubara** [wsdjeg/SpaceVim#4549]
## Expected behavior

I changed init.toml, commentd custom_plugins.
```
[[custom_plugins]]
  name = 'Tokubara/neoterm'
```
Then I restarted spacevim, the plugin is still in effect.
After 20 minutes(while I keeped restarting spacevim), the plugin was not loaded anymore.
Then I uncommented and reopened spacevim, the plugin was still not loaded. What can I do to make the plugin work?
```
[[custom_plugins]]
  name = 'Tokubara/neoterm'
```

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['neoclide/coc.nvim', {'name': 'neoclide/coc.nvim', 'merge': 0, 'overwrite': 1}], ['junegunn/fzf.vim', {'name': 'junegunn/fzf.vim', 'overwrite': 1}], ['skywind3000/vim-cppman', {'name': 'skywind3000/vim-cppman', 'overwrite': 1}], ['rhysd/git-messenger.vim', {'lazy': 1, 'name': 'rhysd/git-messenger.vim', 'on_cmd': 'GitMessenger', 'overwrite': 1}], ['Tokubara/rg.vim', {'name': 'Tokubara/rg.vim', 'overwrite': 1}], ['vim-scripts/applescript.vim', {'name': 'vim-scripts/applescript.vim', 'overwrite': 1}], ['gcmt/taboo.vim', {'name': 'gcmt/taboo.vim', 'on_cmd': 'Taboo', 'merged': 0, 'overwrite': 1}], ['epii1/tagbar-markdown', {'name': 'epii1/tagbar-markdown', 'merged': 0, 'on_ft': ['markdown'], 'overwrite': 1}], ['tpope/vim-scriptease', {'name': 'tpope/vim-scriptease', 'overwrite': 1}], ['Tokubara/neoterm', {'name': 'Tokubara/neoterm', 'overwrite': 1}], ['Tokubara/nvim-send-to-term', {'name': 'Tokubara/nvim-send-to-term', 'overwrite': 1}], ['Tokubara/vim-textobj-hydrogen', {'name': 'Tokubara/vim-textobj-hydrogen', 'overwrite': 1}], ['paretje/nvim-man', {'name': 'paretje/nvim-man', 'overwrite': 1}]]
  data_dir = '/Users/quebec/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['Tokubara/neoterm']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SourceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/quebec/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-toml'
  project_auto_root = 0
  project_rooter_automatically = 0
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="tools"
[[layers]]
  name="fzf"
[[layers]]
  name="VersionControl"
  enable-gtm-status=1
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="lang#toml"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.5.0/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:22:11] [0.001] [ Info ] Startup with argv: ['nvim', '-u', '/Users/quebec/.SpaceVim/init.vim']
[ SpaceVim ] [18:22:11] [0.012] [ Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:22:11] [0.013] [ Info ] global_dir is: /Users/quebec/.SpaceVim.d/
[ SpaceVim ] [18:22:11] [0.013] [ Info ] start to apply config [glob]
[ SpaceVim ] [18:22:11] [0.219] [ Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:22:11] [0.220] [ Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [18:22:11] [0.312] [ Info ] finished loading SpaceVim!
[   rooter ] [18:22:11] [0.479] [ Info ] Load projects cache from: /Users/quebec/.cache/SpaceVim/projects.json
```
