### ISSUE TITLE
Bundled version of Indent Blank Line has horizontal scroll bug

### ISSUE THREAD

**Issue by kayleg** [wsdjeg/SpaceVim#4551]
## Expected behavior, english is required

When scrolling horizontally on a long line the indentation stays and overwrites the characters. This is fixed in the upstream and just needs the bundled version to be updated.

## The reproduce ways from Vim starting (Required!)

Open a new document
Create a few blocks of random text with indentation.
Make one of the lines really long to trigger horizontal scrolling
Scroll to end of long line and notice indentation overwrites text

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['challenger-deep-theme/vim', {'repo': 'challenger-deep-theme/vim', 'merged': 0, 'overwrite': 1}], ['peterhoeg/vim-qml', {'repo': 'peterhoeg/vim-qml', 'merged': 0, 'overwrite': 1}], ['tpope/vim-dotenv', {'repo': 'tpope/vim-dotenv', 'merged': 0, 'overwrite': 1}], ['tpope/vim-abolish', {'repo': 'tpope/vim-abolish', 'merged': 0, 'overwrite': 1}], ['kristijanhusak/vim-dadbod-ui', {'repo': 'kristijanhusak/vim-dadbod-ui', 'merged': 0, 'overwrite': 1}], ['wfxr/minimap.vim', {'build': 'cargo install --locked code-minimap', 'repo': 'wfxr/minimap.vim', 'merged': 0, 'overwrite': 1}], ['inkarkat/vim-SyntaxRange', {'repo': 'inkarkat/vim-SyntaxRange', 'merged': 0, 'overwrite': 1}], ['wakatime/vim-wakatime', {'repo': 'wakatime/vim-wakatime', 'merged': 0, 'overwrite': 1}], ['AndrewRadev/tagalong.vim', {'repo': 'AndrewRadev/tagalong.vim', 'merged': 0, 'overwrite': 1}], ['vimwiki/vimwiki', {'rev': 'dev', 'repo': 'vimwiki/vimwiki', 'merged': 0, 'overwrite': 1}], ['chrisbra/csv.vim', {'repo': 'chrisbra/csv.vim', 'merged': 0, 'overwrite': 1}], ['ellisonleao/glow.nvim', {'repo': 'ellisonleao/glow.nvim', 'merged': 0, 'overwrite': 1}], ['jbyuki/instant.nvim', {'repo': 'jbyuki/instant.nvim', 'merged': 0, 'overwrite': 1}], ['pantharshit00/vim-prisma', {'repo': 'pantharshit00/vim-prisma', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/Users/me/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'defx'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 80
  plugin_bundle_dir = '/Users/me/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'nvim-lspconfig'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pubspec.yaml', 'package.json', 'Cargo.toml', 'tsconfig.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['TODO', 'FIXME', 'XXX', 'QUESTION']
  todo_labels_pattern = '\v\cTODO:?|FIXME:?|XXX:?|QUESTION:?'
  update_retry_cnt = 3
  version = '1.9.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
  format_on_save=1
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="denite"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="test"
[[layers]]
  name="tools"
[[layers]]
  name="tools#dash"
[[layers]]
  name="treesitter"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#dart"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
  auto_fix=1
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#python"
  format_on_save=1
[[layers]]
  name="lang#rust"
  recommended_style=1
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.5.1_1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      SUCCEED!

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [21:40:33] [0.000] [  Info ] start to loading SpaceVim!
[ SpaceVim ] [21:40:33] [0.001] [  Info ] init spacevim root dir:/Users/me/.SpaceVim/
[ SpaceVim ] [21:40:33] [0.155] [  Info ] Startup with no argv, current dir is used: ~/code/neon/funnels
[ SpaceVim ] [21:40:33] [0.174] [  Info ] Can not find project local config, start loading global config
[ SpaceVim ] [21:40:33] [0.174] [  Info ] global_dir is: /Users/me/.SpaceVim.d/
[ SpaceVim ] [21:40:33] [0.174] [  Info ] start to apply config [glob]
[ SpaceVim ] [21:40:33] [0.203] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [21:40:33] [0.265] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [21:40:33] [0.369] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [21:40:33] [0.369] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [21:40:33] [0.400] [  Info ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [21:40:33] [0.400] [  Info ] no func found for mode:fill-column-indicator
[ SpaceVim ] [21:40:33] [0.403] [  Info ] try to call func of mode:whitespace
[ SpaceVim ] [21:40:33] [0.403] [  Info ] no func found for mode:whitespace
[   rooter ] [21:40:34] [0.640] [  Info ] Load projects cache from: /Users/me/.cache/SpaceVim/projects.json
[ SpaceVim ] [21:40:34] [0.784] [  Info ] finished loading SpaceVim!
[   rooter ] [21:40:34] [1.097] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [21:40:34] [1.104] [  Info ] buffer name: No Name
[   rooter ] [21:40:34] [1.104] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [21:40:34] [1.113] [  Info ] try to open SpaceVim welcome page
[   rooter ] [21:40:34] [1.157] [  Info ] buffer name: No Name
[   rooter ] [21:40:34] [1.157] [  Info ] same as current directory, no need to change.
[   rooter ] [21:40:36] [2.815] [  Info ] same as current directory, no need to change.
[   rooter ] [21:48:26] [472.991] [  Info ] buffer name: No Name
[   rooter ] [21:48:26] [472.991] [  Info ] same as current directory, no need to change.
[   rooter ] [21:48:33] [479.859] [  Info ] buffer name: No Name
[   rooter ] [21:48:33] [479.860] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [21:48:33] [479.901] [  Info ] key binding guide float statusline winid:1004
[   rooter ] [21:48:33] [479.921] [  Info ] buffer name: No Name
[   rooter ] [21:48:33] [479.921] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [21:48:33] [479.926] [  Info ] close float statusline winid:1004
[   rooter ] [21:48:50] [496.925] [  Info ] buffer name: No Name
[   rooter ] [21:48:50] [496.925] [  Info ] same as current directory, no need to change.
[   rooter ] [21:48:52] [498.658] [  Info ] buffer name: No Name
[   rooter ] [21:48:52] [498.659] [  Info ] same as current directory, no need to change.
[   rooter ] [21:48:52] [499.092] [  Info ] buffer name: No Name
[   rooter ] [21:48:52] [499.092] [  Info ] same as current directory, no need to change.
```

</details>
