### ISSUE TITLE
emmet not work using ``<c-e>,``

### ISSUE THREAD

**Issue by thawk** [wsdjeg/SpaceVim#4552]
## Expected behavior, english is required

``<c-e>,`` should be used as emmet trigger key, but actually the default ``<c-y>`` is used.

It seems that `lang/html.vim` sets `g:emmet_leader_key`, but `mattn/emmet-vim` only recognize `g:user_emmet_leader_key`.

## The reproduce ways from Vim starting (Required!)

* ``init.toml``
  ```toml
  [[layers]]
  name = "lang#html"
  emmet_leader_key = "<c-e>" 
  emmet_filetyps = ['html']
  ```
* ``vim index.html``
* type ``ul>li``
* type ``<c-e>,``, nothing happens
* type ``<c-y>,``, the code snippet get expanded

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
