### ISSUE TITLE
spacevim use deprecated vim.lsp.diagnostic.show_line_diagnostics for nvim 0.6.0

### ISSUE THREAD

**Issue by rachmadaniHaryono** [wsdjeg/SpaceVim#4556]
## Expected behavior, english is recommend
with nvim 0.6.0 on python file, and pressing `[spc] l h`, it will show line diagnostic
it will show following message

`vim.lsp.diagnostic.show_line_diagnostics is deprecated. See :h deprecated`

which refer to this

https://github.com/neovim/neovim/blob/e65b724451ba5f65dfcaf8f8c16afdd508db7359/runtime/doc/deprecated.txt#L89

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.6.1
- SpaceVim version: 2.0.0-dev
- SpaceVim status: 039d5187

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)
- create file `test.py` with content `print('hello world')`
- press `[spc] l h`

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['dhruvasagar/vim-table-mode', {'repo': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], ['masukomi/vim-markdown-folding', {'repo': 'masukomi/vim-markdown-folding', 'on_ft': ['markdown'], 'overwrite': 1}], ['Konfekt/FastFold', {'repo': 'Konfekt/FastFold', 'on_ft': ['python'], 'overwrite': 1}], ['tmhedberg/SimpylFold', {'repo': 'tmhedberg/SimpylFold', 'on_ft': ['python'], 'overwrite': 1}], ['neovim/nvim-lspconfig', {'loadconf': 1, 'repo': 'neovim/nvim-lspconfig', 'merged': 0, 'hook_source': 'call SpaceVim#util#loadConfig(''plugins/nvim-lspconfig.vim'')', 'overwrite': 1}]]
  data_dir = '/home/r3r/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['fcitx.vim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = 'rachmadaniHaryono'
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/r3r/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'zeavim.vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="foldsearch"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="github"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#rst"
[[layers]]
  name="lsp"
  enabled_clients=['pyright']
  filetypes=['python']
[[layers]]
  name="shell"
  default_shell='terminal'
[[layers]]
  name="gtags"
  gtagslabel='pygments'
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#mpv"
  musics_directory='/home/r3r/Music/Music_Unsorted'
  mpv_interpreter='/usr/bin/mpv'
[[layers]]
  name="tools#zeal"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:21:29] [0.000] [  Info ] start to loading SpaceVim!
[ SpaceVim ] [11:21:29] [0.000] [  Info ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/home/r3r/.pyenv/versions/py3nvim/bin/python3
[ SpaceVim ] [11:21:29] [0.001] [  Info ] init spacevim root dir:/home/r3r/.SpaceVim/
[ SpaceVim ] [11:21:29] [0.782] [  Info ] Startup with argv: ['nvim', 'test.py']
[ SpaceVim ] [11:21:30] [0.808] [  Info ] Can not find project local config, start loading global config
[ SpaceVim ] [11:21:30] [0.808] [  Info ] global_dir is: /home/r3r/.SpaceVim.d/
[ SpaceVim ] [11:21:30] [0.847] [  Info ] start to apply config [glob]
[ SpaceVim ] [11:21:30] [0.891] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [11:21:30] [0.985] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:21:30] [1.034] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:21:30] [1.034] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [11:21:30] [1.405] [  Info ] Load projects cache from: /home/r3r/.cache/SpaceVim/projects.json
[ SpaceVim ] [11:21:30] [1.731] [  Info ] finished loading SpaceVim!
[   rooter ] [11:21:31] [2.709] [  Info ] Start to find root for: /tmp/temp1/test.py
[   rooter ] [11:21:31] [2.710] [  Info ] buffer name: test.py
[   rooter ] [11:21:31] [2.710] [  Info ] same as current directory, no need to change.
[   rooter ] [11:21:31] [2.718] [  Info ] buffer name: test.py
[   rooter ] [11:21:31] [2.718] [  Info ] same as current directory, no need to change.
[   rooter ] [11:21:39] [10.730] [  Info ] Start to find root for: /tmp/temp1/test.py
[   rooter ] [11:21:39] [10.731] [  Info ] buffer name: test.py
[   rooter ] [11:21:39] [10.731] [  Info ] same as current directory, no need to change.
[   rooter ] [11:21:39] [10.796] [  Info ] buffer name: test.py
[   rooter ] [11:21:39] [10.796] [  Info ] same as current directory, no need to change.
[    ctags ] [11:21:40] [10.816] [  Info ] update ctags database for /tmp/temp1
[    ctags ] [11:21:40] [10.944] [  Info ] ctags database updated successfully
[   rooter ] [11:21:41] [12.788] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:21:41] [12.790] [  Info ] buffer name: No Name
[   rooter ] [11:21:41] [12.791] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:21:42] [12.843] [  Info ] key binding guide float statusline winid:1003
[   rooter ] [11:21:42] [13.261] [  Info ] buffer name: test.py
[   rooter ] [11:21:42] [13.261] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:21:42] [13.313] [  Info ] close float statusline winid:1003
[   rooter ] [11:21:42] [13.319] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:21:42] [13.320] [  Info ] buffer name: No Name
[   rooter ] [11:21:42] [13.320] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:21:42] [13.346] [  Info ] key binding guide float statusline winid:1005
[   rooter ] [11:21:43] [14.674] [  Info ] buffer name: test.py
[   rooter ] [11:21:43] [14.675] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:21:43] [14.690] [  Info ] close float statusline winid:1005
[   rooter ] [11:24:48] [199.260] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:24:48] [199.261] [  Info ] buffer name: No Name
[   rooter ] [11:24:48] [199.261] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:24:48] [199.292] [  Info ] key binding guide float statusline winid:1007
[   rooter ] [11:24:49] [200.041] [  Info ] buffer name: test.py
[   rooter ] [11:24:49] [200.041] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:24:49] [200.051] [  Info ] close float statusline winid:1007
[   rooter ] [11:24:49] [200.057] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:24:49] [200.058] [  Info ] buffer name: No Name
[   rooter ] [11:24:49] [200.058] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:24:49] [200.081] [  Info ] key binding guide float statusline winid:1009
[   rooter ] [11:24:51] [201.835] [  Info ] buffer name: test.py
[   rooter ] [11:24:51] [201.836] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:24:51] [201.852] [  Info ] close float statusline winid:1009
[   rooter ] [11:26:55] [326.331] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:26:55] [326.331] [  Info ] buffer name: No Name
[   rooter ] [11:26:55] [326.331] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:55] [326.354] [  Info ] key binding guide float statusline winid:1011
[   rooter ] [11:26:55] [326.369] [  Info ] buffer name: test.py
[   rooter ] [11:26:55] [326.369] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:55] [326.376] [  Info ] close float statusline winid:1011
[   rooter ] [11:26:55] [326.382] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:26:55] [326.383] [  Info ] buffer name: No Name
[   rooter ] [11:26:55] [326.383] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:55] [326.405] [  Info ] key binding guide float statusline winid:1013
[   rooter ] [11:26:58] [328.875] [  Info ] buffer name: test.py
[   rooter ] [11:26:58] [328.875] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:58] [328.883] [  Info ] close float statusline winid:1013
[   rooter ] [11:26:58] [328.889] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:26:58] [328.890] [  Info ] buffer name: No Name
[   rooter ] [11:26:58] [328.890] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:26:58] [328.912] [  Info ] key binding guide float statusline winid:1015
[   rooter ] [11:27:00] [330.866] [  Info ] buffer name: test.py
[   rooter ] [11:27:00] [330.866] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:00] [330.873] [  Info ] close float statusline winid:1015
[   rooter ] [11:27:02] [332.902] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:02] [332.903] [  Info ] buffer name: No Name
[   rooter ] [11:27:02] [332.903] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:02] [332.935] [  Info ] key binding guide float statusline winid:1017
[   rooter ] [11:27:02] [332.954] [  Info ] buffer name: test.py
[   rooter ] [11:27:02] [332.954] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:02] [332.961] [  Info ] close float statusline winid:1017
[   rooter ] [11:27:02] [332.967] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:02] [332.968] [  Info ] buffer name: No Name
[   rooter ] [11:27:02] [332.968] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:02] [332.990] [  Info ] key binding guide float statusline winid:1019
[   rooter ] [11:27:02] [333.001] [  Info ] buffer name: test.py
[   rooter ] [11:27:02] [333.001] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:02] [333.008] [  Info ] close float statusline winid:1019
[   rooter ] [11:27:02] [333.014] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:02] [333.015] [  Info ] buffer name: No Name
[   rooter ] [11:27:02] [333.015] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:02] [333.037] [  Info ] key binding guide float statusline winid:1021
[   rooter ] [11:27:03] [334.727] [  Info ] buffer name: test.py
[   rooter ] [11:27:03] [334.727] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:03] [334.742] [  Info ] close float statusline winid:1021
[   rooter ] [11:27:11] [341.883] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:11] [341.884] [  Info ] buffer name: No Name
[   rooter ] [11:27:11] [341.884] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:11] [341.928] [  Info ] key binding guide float statusline winid:1023
[   rooter ] [11:27:18] [349.756] [  Info ] buffer name: test.py
[   rooter ] [11:27:18] [349.757] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:18] [349.772] [  Info ] close float statusline winid:1023
[   rooter ] [11:27:20] [350.999] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:20] [351.000] [  Info ] buffer name: No Name
[   rooter ] [11:27:20] [351.000] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:20] [351.030] [  Info ] key binding guide float statusline winid:1025
[   rooter ] [11:27:20] [351.680] [  Info ] buffer name: test.py
[   rooter ] [11:27:20] [351.680] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:20] [351.690] [  Info ] close float statusline winid:1025
[   rooter ] [11:27:20] [351.704] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:20] [351.706] [  Info ] buffer name: No Name
[   rooter ] [11:27:20] [351.706] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:20] [351.741] [  Info ] key binding guide float statusline winid:1027
[   rooter ] [11:27:25] [355.907] [  Info ] buffer name: test.py
[   rooter ] [11:27:25] [355.907] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:25] [355.918] [  Info ] close float statusline winid:1027
[   rooter ] [11:27:25] [355.926] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:25] [355.928] [  Info ] buffer name: No Name
[   rooter ] [11:27:25] [355.928] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:25] [355.959] [  Info ] key binding guide float statusline winid:1029
[   rooter ] [11:27:26] [357.349] [  Info ] buffer name: test.py
[   rooter ] [11:27:26] [357.349] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:26] [357.357] [  Info ] close float statusline winid:1029
[   rooter ] [11:27:28] [359.456] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:28] [359.458] [  Info ] buffer name: No Name
[   rooter ] [11:27:28] [359.458] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:28] [359.495] [  Info ] key binding guide float statusline winid:1031
[   rooter ] [11:27:28] [359.508] [  Info ] buffer name: test.py
[   rooter ] [11:27:28] [359.508] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:28] [359.514] [  Info ] close float statusline winid:1031
[   rooter ] [11:27:28] [359.520] [  Info ] Start to find root for: /tmp/temp1/
[   rooter ] [11:27:28] [359.521] [  Info ] buffer name: No Name
[   rooter ] [11:27:28] [359.521] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:28] [359.540] [  Info ] key binding guide float statusline winid:1033
[   rooter ] [11:27:33] [364.499] [  Info ] buffer name: test.py
[   rooter ] [11:27:33] [364.499] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [11:27:33] [364.509] [  Info ] close float statusline winid:1033
[   rooter ] [11:27:34] [365.042] [  Info ] Start to find root for: /tmp/nvimGm8jY8/7/issue_report.md
[   rooter ] [11:27:34] [365.043] [  Info ] buffer name: /tmp/nvimGm8jY8/7/issue_report.md
[   rooter ] [11:27:34] [365.043] [  Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
