### ISSUE TITLE
git layer

### ISSUE THREAD

**Issue by rachmadaniHaryono** [wsdjeg/SpaceVim#4560]
## Expected behavior, english is recommend

- `spc g h a` have different function when github and git layer installed but this is not documented on [git layer page](https://spacevim.org/layers/git/)
- when using fugitive, Glog and Gdiff is used. it should be Gclog and Gdiffsplit

https://github.com/tpope/vim-fugitive/blob/0615cd2baf15ed0aebacd3546015a89d491553ef/doc/fugitive.txt#L674

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.6.1
- SpaceVim version: 2.0.0-dev
- SpaceVim status: 0f2a73df

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['dhruvasagar/vim-table-mode', {'repo': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], ['masukomi/vim-markdown-folding', {'repo': 'masukomi/vim-markdown-folding', 'on_ft': ['markdown'], 'overwrite': 1}], ['Konfekt/FastFold', {'repo': 'Konfekt/FastFold', 'on_ft': ['python'], 'overwrite': 1}], ['tmhedberg/SimpylFold', {'repo': 'tmhedberg/SimpylFold', 'on_ft': ['python'], 'overwrite': 1}], ['neovim/nvim-lspconfig', {'loadconf': 1, 'repo': 'neovim/nvim-lspconfig', 'merged': 0, 'hook_source': 'call SpaceVim#util#loadConfig(''plugins/nvim-lspconfig.vim'')', 'overwrite': 1}]]
  data_dir = '/home/r3r/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['fcitx.vim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/r3r/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'zeavim.vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="foldsearch"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#rst"
[[layers]]
  name="lsp"
  enabled_clients=['pyright']
  filetypes=['python']
[[layers]]
  name="shell"
  default_shell='terminal'
[[layers]]
  name="gtags"
  gtagslabel='pygments'
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#mpv"
  musics_directory='/home/r3r/Music/Music_Unsorted'
  mpv_interpreter='/usr/bin/mpv'
[[layers]]
  name="tools#zeal"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:34:03] [0.000] [  Info ] Loading SpaceVim from: /home/r3r/.SpaceVim/
[ SpaceVim ] [18:34:03] [0.000] [  Info ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/home/r3r/.pyenv/versions/py3nvim/bin/python3
[ SpaceVim ] [18:34:03] [0.090] [  Info ] Startup with argv: ['nvim', 'tmp.py']
[ SpaceVim ] [18:34:03] [0.107] [  Info ] Can not find project local config, start loading global config
[ SpaceVim ] [18:34:03] [0.107] [  Info ] global_dir is: /home/r3r/.SpaceVim.d/
[ SpaceVim ] [18:34:03] [0.108] [  Info ] start to apply config [glob]
[ SpaceVim ] [18:34:03] [0.138] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [18:34:04] [0.197] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:34:04] [0.233] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:34:04] [0.233] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [18:34:04] [0.304] [  Info ] Load projects cache from: /home/r3r/.cache/SpaceVim/projects.json
[ SpaceVim ] [18:34:04] [0.358] [  Info ] finished loading SpaceVim!
[   rooter ] [18:34:04] [0.538] [  Info ] Start to find root for: /tmp/tmp/tmp.py
[   rooter ] [18:34:04] [0.539] [  Info ] buffer name: tmp.py
[   rooter ] [18:34:04] [0.539] [  Info ] same as current directory, no need to change.
[   rooter ] [18:34:04] [0.546] [  Info ] buffer name: tmp.py
[   rooter ] [18:34:04] [0.546] [  Info ] same as current directory, no need to change.
[   rooter ] [18:34:06] [3.073] [  Info ] Start to find root for: /tmp/tmp/
[   rooter ] [18:34:06] [3.075] [  Info ] buffer name: No Name
[   rooter ] [18:34:06] [3.075] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:34:06] [3.127] [  Info ] key binding guide float statusline winid:1003
[   rooter ] [18:34:06] [3.148] [  Info ] buffer name: tmp.py
[   rooter ] [18:34:06] [3.148] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:34:06] [3.153] [  Info ] close float statusline winid:1003
[   rooter ] [18:34:06] [3.159] [  Info ] Start to find root for: /tmp/tmp/
[   rooter ] [18:34:06] [3.160] [  Info ] buffer name: No Name
[   rooter ] [18:34:06] [3.160] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:34:07] [3.183] [  Info ] key binding guide float statusline winid:1005
[   rooter ] [18:34:07] [3.193] [  Info ] buffer name: tmp.py
[   rooter ] [18:34:07] [3.193] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:34:07] [3.198] [  Info ] close float statusline winid:1005
[   rooter ] [18:34:07] [3.205] [  Info ] Start to find root for: /tmp/tmp/
[   rooter ] [18:34:07] [3.205] [  Info ] buffer name: No Name
[   rooter ] [18:34:07] [3.205] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:34:07] [3.228] [  Info ] key binding guide float statusline winid:1007
[   rooter ] [18:37:41] [218.017] [  Info ] buffer name: tmp.py
[   rooter ] [18:37:41] [218.017] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:37:41] [218.022] [  Info ] close float statusline winid:1007
[   rooter ] [18:38:05] [241.897] [  Info ] Start to find root for: /tmp/tmp/
[   rooter ] [18:38:05] [241.899] [  Info ] buffer name: No Name
[   rooter ] [18:38:05] [241.899] [  Info ] same as current directory, no need to change.
[   rooter ] [18:38:05] [242.029] [  Info ] Start to find root for: /home/r3r/.cache/vimfiles/.cache/init.vim/.dein/doc/fugitive.txt
[   rooter ] [18:38:05] [242.033] [  Info ] buffer name: /home/r3r/.cache/vimfiles/.cache/init.vim/.dein/doc/fugitive.txt
[   rooter ] [18:38:05] [242.033] [  Info ] same as current directory, no need to change.
[   rooter ] [18:38:35] [271.902] [  Info ] buffer name: tmp.py
[   rooter ] [18:38:35] [271.902] [  Info ] same as current directory, no need to change.
[   rooter ] [18:38:37] [273.200] [  Info ] Start to find root for: /tmp/tmp/
[   rooter ] [18:38:37] [273.202] [  Info ] buffer name: No Name
[   rooter ] [18:38:37] [273.202] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:38:37] [273.252] [  Info ] key binding guide float statusline winid:1010
[   rooter ] [18:38:37] [273.754] [  Info ] buffer name: tmp.py
[   rooter ] [18:38:37] [273.754] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:38:37] [273.760] [  Info ] close float statusline winid:1010
[   rooter ] [18:38:37] [273.766] [  Info ] Start to find root for: /tmp/tmp/
[   rooter ] [18:38:37] [273.767] [  Info ] buffer name: No Name
[   rooter ] [18:38:37] [273.767] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:38:37] [273.797] [  Info ] key binding guide float statusline winid:1012
[   rooter ] [18:38:40] [276.295] [  Info ] buffer name: tmp.py
[   rooter ] [18:38:40] [276.295] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:38:40] [276.307] [  Info ] close float statusline winid:1012
[   rooter ] [18:38:40] [276.699] [  Info ] Start to find root for: /tmp/nvimLxSCMG/4/issue_report.md
[   rooter ] [18:38:40] [276.700] [  Info ] buffer name: /tmp/nvimLxSCMG/4/issue_report.md
[   rooter ] [18:38:40] [276.700] [  Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
