### ISSUE TITLE
autoflake support accidentally removed

### ISSUE THREAD

**Issue by nekoknot** [wsdjeg/SpaceVim#4561]
## Expected behavior, english is required
Unused imports removed when hitting `[SPC]-l-i-r`

## The reproduce ways from Vim starting (Required!)
Open a python file with unused imports and hit `[SPC]-l-i-r` or run `:Neoformat autoflake`. The unused imports should be removed.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_before = 'customvim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/jess/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jess/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'markdown-preview.nvim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-return-key-behavior='complete'
  auto-completion-tab-key-behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  enable_typeinfo=1
[[layers]]
  name="sudo"
[[layers]]
  name="lang#rst"
[[layers]]
  name="lang#nim"
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#markdown"
  enabled_formater=['prettier']
[[layers]]
  name="lang#toml"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:34:56] [0.001] [  Info ] Loading SpaceVim from: /home/jess/.SpaceVim/
[ SpaceVim ] [14:34:56] [0.125] [  Info ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [14:34:56] [0.131] [  Info ] find local conf: /home/jess/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [14:34:56] [0.138] [  Info ] force loading global config >>>
[ SpaceVim ] [14:34:56] [0.139] [  Info ] global_dir is: /home/jess/.SpaceVim.d/
[ SpaceVim ] [14:34:56] [0.139] [  Info ] start to apply config [glob]
[ SpaceVim ] [14:34:56] [0.167] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [14:34:56] [0.190] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [14:34:56] [0.190] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [14:34:56] [0.236] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [14:34:56] [0.307] [  Info ] try to open SpaceVim welcome page
[   rooter ] [14:34:56] [0.369] [  Info ] Load projects cache from: /home/jess/.cache/SpaceVim/projects.json
```
</details>

## Screenshots

The result is simply a message saying:
`Neoformat: formatter definition for autoflake not found`

## Comments
SpaceVim did a fork of an old version of `neoformat` which ended up removing `autoflake` support: https://github.com/SpaceVim/SpaceVim/pull/4290

EDIT: Changed it cause it was clearing the buffer if it had nothing to change (only works if you save the file first)

A workaround is to define this:
```vimscript
let g:neoformat_python_autoflake = {
      \ 'exe': 'bash',
      \ 'args': ['-c', '"FN=\$(mktemp); cp \"%:p\" \$FN; autoflake --remove-all-unused-imports --remove-duplicate-keys --expand-star-imports --in-place \$FN; cat \$FN; rm \$FN"'],
      \ 'stdin': 0,
      \ }
```

The janky `bash -c` usage is because using the old version also removed the fix for a bug that was added to support `autoflake`, since its output is different than other formatters. See: https://github.com/SpaceVim/SpaceVim/issues/2293#issuecomment-448067278

It's unclear why the PR forked what seems to be an old (2018?) version of `neoformat`
