### ISSUE TITLE
spc i s error when autocomplete layer enabled

### ISSUE THREAD

**Issue by rachmadaniHaryono** [wsdjeg/SpaceVim#4571]
## Expected behavior, english is recommend

- when pressing `spc i s` there should be no error when autocomplete layer is enabled. but i got `E492: Not an editor command: Unite neosnippet`
- there should be option when pressing `spc i` but i only got lorem ipsum, password and uuid submenu

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.6.1
- SpaceVim version: 2.0.0-dev
- SpaceVim status: 1e95167f

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## The reproduce ways from Vim starting (Required!)

- open /tmp/tmp.txt
- press `spc i s`

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['dhruvasagar/vim-table-mode', {'repo': 'dhruvasagar/vim-table-mode', 'overwrite': 1}], ['masukomi/vim-markdown-folding', {'repo': 'masukomi/vim-markdown-folding', 'on_ft': ['markdown'], 'overwrite': 1}], ['Konfekt/FastFold', {'repo': 'Konfekt/FastFold', 'on_ft': ['python'], 'overwrite': 1}], ['tmhedberg/SimpylFold', {'repo': 'tmhedberg/SimpylFold', 'on_ft': ['python'], 'overwrite': 1}], ['neovim/nvim-lspconfig', {'loadconf': 1, 'repo': 'neovim/nvim-lspconfig', 'merged': 0, 'hook_source': 'call SpaceVim#util#loadConfig(''plugins/nvim-lspconfig.vim'')', 'overwrite': 1}]]
  data_dir = '/home/r3r/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['fcitx.vim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/r3r/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'zeavim.vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="debug"
[[layers]]
  name="default"
[[layers]]
  name="foldsearch"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#rst"
[[layers]]
  name="lsp"
  enabled_clients=['pyright']
  filetypes=['python']
[[layers]]
  name="shell"
  default_shell='terminal'
[[layers]]
  name="gtags"
  gtagslabel='pygments'
[[layers]]
  name="test"
[[layers]]
  name="tmux"
[[layers]]
  name="tools"
[[layers]]
  name="tools#mpv"
  musics_directory='/home/r3r/Music/Music_Unsorted'
  mpv_interpreter='/usr/bin/mpv'
[[layers]]
  name="tools#zeal"
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:27:11] [0.000] [  Info ] Loading SpaceVim from: /home/r3r/.SpaceVim/
[ SpaceVim ] [12:27:11] [0.001] [  Info ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/home/r3r/.pyenv/versions/py3nvim/bin/python3
[ SpaceVim ] [12:27:11] [0.090] [  Info ] Startup with argv: ['nvim', '/tmp/tmp.txt']
[ SpaceVim ] [12:27:11] [0.100] [  Info ] Can not find project local config, start loading global config
[ SpaceVim ] [12:27:11] [0.100] [  Info ] global_dir is: /home/r3r/.SpaceVim.d/
[ SpaceVim ] [12:27:11] [0.100] [  Info ] start to apply config [glob]
[ SpaceVim ] [12:27:11] [0.126] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [12:27:11] [0.162] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:27:11] [0.196] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:27:11] [0.197] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [12:27:11] [0.268] [  Info ] Load projects cache from: /home/r3r/.cache/SpaceVim/projects.json
[ SpaceVim ] [12:27:11] [0.322] [  Info ] finished loading SpaceVim!
[   rooter ] [12:27:11] [0.477] [  Info ] Start to find root for: /tmp/tmp.txt
[   rooter ] [12:27:11] [0.478] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:11] [0.478] [  Info ] same as current directory, no need to change.
[   rooter ] [12:27:11] [0.482] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:11] [0.482] [  Info ] same as current directory, no need to change.
[   rooter ] [12:27:18] [7.104] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:18] [7.105] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:18] [7.107] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:18] [7.107] [  Info ] buffer name: No Name
[   rooter ] [12:27:18] [7.107] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:18] [7.159] [  Info ] key binding guide float statusline winid:1003
[   rooter ] [12:27:18] [7.179] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:18] [7.179] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:18] [7.184] [  Info ] close float statusline winid:1003
[   rooter ] [12:27:18] [7.190] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:18] [7.190] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:18] [7.191] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:18] [7.192] [  Info ] buffer name: No Name
[   rooter ] [12:27:18] [7.192] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:18] [7.214] [  Info ] key binding guide float statusline winid:1005
[   rooter ] [12:27:20] [9.105] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:20] [9.105] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:20] [9.110] [  Info ] close float statusline winid:1005
[   rooter ] [12:27:20] [9.116] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:20] [9.116] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:20] [9.117] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:20] [9.117] [  Info ] buffer name: No Name
[   rooter ] [12:27:20] [9.117] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:20] [9.140] [  Info ] key binding guide float statusline winid:1007
[   rooter ] [12:27:22] [11.376] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:22] [11.376] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:22] [11.385] [  Info ] close float statusline winid:1007
[   rooter ] [12:27:25] [14.775] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:25] [14.776] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:25] [14.778] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:25] [14.778] [  Info ] buffer name: No Name
[   rooter ] [12:27:25] [14.778] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:25] [14.827] [  Info ] key binding guide float statusline winid:1009
[   rooter ] [12:27:25] [14.848] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:25] [14.849] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:25] [14.853] [  Info ] close float statusline winid:1009
[   rooter ] [12:27:25] [14.858] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:25] [14.858] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:25] [14.859] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:25] [14.859] [  Info ] buffer name: No Name
[   rooter ] [12:27:25] [14.859] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:26] [14.881] [  Info ] key binding guide float statusline winid:1011
[   rooter ] [12:27:29] [18.136] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:29] [18.136] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:29] [18.146] [  Info ] close float statusline winid:1011
[   rooter ] [12:27:29] [18.162] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:29] [18.163] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:29] [18.166] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:29] [18.166] [  Info ] buffer name: No Name
[   rooter ] [12:27:29] [18.166] [  Info ] same as current directory, no need to change.
[   rooter ] [12:27:35] [24.402] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:35] [24.402] [  Info ] same as current directory, no need to change.
[   rooter ] [12:27:37] [25.983] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:37] [25.984] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:37] [25.986] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:37] [25.987] [  Info ] buffer name: No Name
[   rooter ] [12:27:37] [25.987] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:37] [26.035] [  Info ] key binding guide float statusline winid:1014
[   rooter ] [12:27:38] [26.895] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:38] [26.895] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:38] [26.905] [  Info ] close float statusline winid:1014
[   rooter ] [12:27:38] [26.917] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:38] [26.918] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:38] [26.920] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:38] [26.921] [  Info ] buffer name: No Name
[   rooter ] [12:27:38] [26.921] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:38] [26.968] [  Info ] key binding guide float statusline winid:1016
[   rooter ] [12:27:42] [31.255] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:42] [31.255] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:42] [31.266] [  Info ] close float statusline winid:1016
[   rooter ] [12:27:42] [31.308] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:42] [31.309] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:42] [31.312] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:42] [31.312] [  Info ] buffer name: No Name
[   rooter ] [12:27:42] [31.312] [  Info ] same as current directory, no need to change.
[   rooter ] [12:27:44] [33.120] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:44] [33.120] [  Info ] same as current directory, no need to change.
[   rooter ] [12:27:45] [34.658] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:45] [34.659] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:45] [34.661] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:45] [34.662] [  Info ] buffer name: No Name
[   rooter ] [12:27:45] [34.662] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:45] [34.711] [  Info ] key binding guide float statusline winid:1019
[   rooter ] [12:27:45] [34.732] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:45] [34.732] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:45] [34.737] [  Info ] close float statusline winid:1019
[   rooter ] [12:27:45] [34.743] [  Info ] Start to find root for: /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:45] [34.743] [  Info ]         (.git/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:45] [34.744] [  Info ]         (.SpaceVim.d/):/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/gallery-dl/
[   rooter ] [12:27:45] [34.745] [  Info ] buffer name: No Name
[   rooter ] [12:27:45] [34.745] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:45] [34.767] [  Info ] key binding guide float statusline winid:1021
[   rooter ] [12:27:51] [40.159] [  Info ] buffer name: /tmp/tmp.txt
[   rooter ] [12:27:51] [40.160] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [12:27:51] [40.169] [  Info ] close float statusline winid:1021
[   rooter ] [12:27:51] [40.637] [  Info ] Start to find root for: /tmp/nvimKjmYiN/6/issue_report.md
[   rooter ] [12:27:51] [40.637] [  Info ] buffer name: /tmp/nvimKjmYiN/6/issue_report.md
[   rooter ] [12:27:51] [40.637] [  Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
