### ISSUE TITLE
plantuml_previewer#start: require java command | Defining java path

### ISSUE THREAD

**Issue by anoduck** [wsdjeg/SpaceVim#4586]
## The Nut Shell

I just need the proper syntax for defining the path for java within `init.toml`, so plantuml_previewer can use it to run the `plantuml.jar`.

## Expected behavior, english is required

Expected plantuml previewer to generate preview of the loaded file.

## The reproduce ways from Vim starting (Required!)

Certain this is an issue specific to non-linux systems, such as OpenBSD...

1. Open nvim/vim.
2. Either open file with `:hide edit file.puml` or simply `:PlantumlOpen`
3. And then error output.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['folke/tokyonight.nvim', {'tokyonight_style': 'night', 'repo': 'folke/tokyonight.nvim', 'merged': 0, 'overwrite': 1}], ['wakatime/vim-wakatime', {'repo': 'wakatime/vim-wakatime', 'merged': 0, 'overwrite': 1}], ['friedenberg/vim-fancy-comment', {'repo': 'friedenberg/vim-fancy-comment', 'merged': 0, 'overwrite': 1}], ['edluffy/hologram.nvim', {'repo': 'edluffy/hologram.nvim', 'merged': 0, 'overwrite': 1}], ['is0n/fm-nvim', {'repo': 'is0n/fm-nvim', 'merged': 0, 'overwrite': 1}], ['justinmk/vim-syntax-extra', {'repo': 'justinmk/vim-syntax-extra', 'merged': 0, 'overwrite': 1}], ['tridactyl/vim-tridactyl', {'repo': 'tridactyl/vim-tridactyl', 'merged': 0, 'overwrite': 1}], ['chrisbra/vim-zsh', {'repo': 'chrisbra/vim-zsh', 'merged': 0, 'on_ft': 'zsh', 'overwrite': 1}], ['folke/tokyonight.nvim', {'tokyonight_style': 'night', 'repo': 'folke/tokyonight.nvim', 'merged': 0, 'overwrite': 1}], ['wakatime/vim-wakatime', {'repo': 'wakatime/vim-wakatime', 'merged': 0, 'overwrite': 1}], ['friedenberg/vim-fancy-comment', {'repo': 'friedenberg/vim-fancy-comment', 'merged': 0, 'overwrite': 1}], ['edluffy/hologram.nvim', {'repo': 'edluffy/hologram.nvim', 'merged': 0, 'overwrite': 1}], ['is0n/fm-nvim', {'repo': 'is0n/fm-nvim', 'merged': 0, 'overwrite': 1}], ['justinmk/vim-syntax-extra', {'repo': 'justinmk/vim-syntax-extra', 'merged': 0, 'overwrite': 1}], ['tridactyl/vim-tridactyl', {'repo': 'tridactyl/vim-tridactyl', 'merged': 0, 'overwrite': 1}], ['chrisbra/vim-zsh', {'repo': 'chrisbra/vim-zsh', 'merged': 0, 'on_ft': 'zsh', 'overwrite': 1}]]
  data_dir = '/home/user/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Sauce Code Pro Nerd Font Complete Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  java = '/usr/local/jdk-11/bin/java'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/user/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-lsp'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  python3_host_prog = '/usr/local/bin/python3.9'
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#python"
  python_interpretor='/usr/local/bin/python3.9'
  python_file_head=['#!/usr/bin/env python', '# -*- coding: utf-8 -*-', '', '']
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#ipynb"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="git"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#plantuml"
  plantuml_jar_path='/home/user/bin/plantuml.jar'
  java='/usr/local/jdk-11/bin/java'
[[layers]]
  name="VersionControl"
[[layers]]
  name="tools"
[[layers]]
  name="tmux"
[[layers]]
  name="sudo"
[[layers]]
  name="fzf"
[[layers]]
  name="ctrlspace"
[[layers]]
  name="denite"
[[layers]]
  name="lang#sh"
  sh_file_head='#!/usr/bin/env bash'
[[layers]]
  name="lang#json"
[[layers]]
  name="colorscheme"
[[layers]]
  name="lsp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:57:43] [0.001] [  Info ] Loading SpaceVim from: /home/user/.SpaceVim/
[ SpaceVim ] [17:57:44] [0.393] [  Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [17:57:44] [0.419] [  Info ] start loading global config >>>
[ SpaceVim ] [17:57:44] [0.419] [  Info ] global_dir is: /home/user/.SpaceVim.d/
[ SpaceVim ] [17:57:44] [0.420] [  Info ] start to apply config [glob]
[ SpaceVim ] [17:57:44] [0.448] [  Info ] find local conf: /home/user/.SpaceVim.d/init.toml
[ SpaceVim ] [17:57:44] [0.448] [  Info ] loading cached local conf: /home/user/.cache/SpaceVim/conf/_home_vassilios__SpaceVim_d_init_toml.json
[ SpaceVim ] [17:57:44] [0.449] [  Info ] start to apply config [local]
[ SpaceVim ] [17:57:44] [0.474] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [17:57:44] [0.560] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:57:44] [0.893] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [17:57:44] [0.894] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [17:57:44] [0.943] [  Info ] try to call func of mode:whitespace
[ SpaceVim ] [17:57:44] [0.943] [  Info ] no func found for mode:whitespace
[ SpaceVim ] [17:57:44] [1.292] [  Info ] finished loading SpaceVim!
[   rooter ] [17:57:45] [1.525] [  Info ] Load projects cache from: /home/user/.cache/SpaceVim/projects.json
[   rooter ] [17:57:45] [1.669] [  Info ] Start to find root for: /home/user/
[   rooter ] [17:57:45] [1.672] [  Info ] buffer name: No Name
[   rooter ] [17:57:45] [1.673] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [17:57:45] [1.680] [  Info ] try to open SpaceVim welcome page
[   rooter ] [17:57:51] [7.609] [  Info ] buffer name: No Name
[   rooter ] [17:57:51] [7.609] [  Info ] same as current directory, no need to change.
[   rooter ] [22:25:16] [16053.039] [  Info ] Start to find root for: /home/user/NERD_tree_1
[   rooter ] [22:25:16] [16053.042] [  Info ] buffer name: NERD_tree_1
[   rooter ] [22:25:16] [16053.043] [  Info ] same as current directory, no need to change.
[   rooter ] [22:25:18] [16054.944] [  Info ] buffer name: No Name
[   rooter ] [22:25:18] [16054.944] [  Info ] change to root: /home/user/
[   rooter ] [22:25:18] [16054.994] [  Info ] Start to find root for: /home/user/
[   rooter ] [22:25:18] [16055.000] [  Info ] buffer name: No Name
[   rooter ] [22:25:18] [16055.000] [  Info ] same as current directory, no need to change.
[   rooter ] [22:25:18] [16055.094] [  Info ] Start to find root for: /home/user/NERD_tree_2
[   rooter ] [22:25:18] [16055.099] [  Info ] buffer name: NERD_tree_2
[   rooter ] [22:25:18] [16055.099] [  Info ] same as current directory, no need to change.
[   rooter ] [22:25:32] [16068.798] [  Info ] buffer name: No Name
[   rooter ] [22:25:32] [16068.798] [  Info ] change to root: /home/user/
[   rooter ] [22:25:32] [16068.839] [  Info ] Start to find root for: /home/user/
[   rooter ] [22:25:32] [16068.843] [  Info ] buffer name: No Name
[   rooter ] [22:25:32] [16068.843] [  Info ] same as current directory, no need to change.
[   rooter ] [22:25:32] [16068.895] [  Info ] Start to find root for: /home/user/NERD_tree_3
[   rooter ] [22:25:32] [16068.900] [  Info ] buffer name: NERD_tree_3
[   rooter ] [22:25:32] [16068.900] [  Info ] same as current directory, no need to change.
```
</details>

## Screenshots

![2022-02-09_23-37](https://user-images.githubusercontent.com/9925396/153338159-7bdbe1f2-f66b-4d65-ab58-6bca5968330d.png)
