### ISSUE TITLE
Lua support checking fails and indent line can not be enabled by default

### ISSUE THREAD

**Issue by PeterDing** [wsdjeg/SpaceVim#4600]
## Expected behavior, english is required
The output of `:SPDebugInfo!` shows `Failed : Known issue, neovim do not support lua now.` always.
I use both `neovim` (0.6.1) installed from `brew` and [neovim/releases](https://github.com/neovim/neovim/releases).

But, `nvim --version` shows that lua is supported, as following:

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

Because this issue, indent line can not be enable by default. I must enable it manually when opening a file.

------

The weird thing is that Indent line is supported when I checkout to the SpaceVim commit `ee07874`.

## The reproduce ways from Vim starting (Required!)
1. Cleaning Env

```
rrm -rf ~/.SpaceVim* ~/.cache/vimfiles ~/.cache/SpaceVim ~/.config/nvim ~/.local/share/nvim
```

2. Reinstall SpaceVim

```
curl -sLf https://spacevim.org/install.sh | bash
```

3. Start `nvim` and run `:SPDebugInfo!`

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/peter/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/peter/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_indentline=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.6.1/bin/nvim)
version: 800
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:45:13] [0.001] [  Info ] Loading SpaceVim from: /Users/peter/.SpaceVim/
[ SpaceVim ] [16:45:13] [0.332] [  Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [16:45:13] [0.366] [  Info ] start loading global config >>>
[ SpaceVim ] [16:45:13] [0.367] [  Info ] global_dir is: /Users/peter/.SpaceVim.d/
[ SpaceVim ] [16:45:13] [0.367] [  Info ] start to apply config [glob]
[ SpaceVim ] [16:45:13] [0.370] [  Info ] find local conf: /Users/peter/.SpaceVim.d/init.toml
[ SpaceVim ] [16:45:13] [0.371] [  Info ] loading cached local conf: /Users/peter/.cache/SpaceVim/conf/_Users_peter__SpaceVim_d_init_toml.json
[ SpaceVim ] [16:45:13] [0.371] [  Info ] start to apply config [local]
[ SpaceVim ] [16:45:13] [0.376] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [16:45:13] [0.435] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:45:14] [0.888] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:45:14] [0.888] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [16:45:14] [0.955] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [16:45:14] [1.151] [  Info ] try to open SpaceVim welcome page
[   rooter ] [16:45:14] [1.352] [  Info ] Load projects cache from: /Users/peter/.cache/SpaceVim/projects.json
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
