### ISSUE TITLE
Wrong function syntax_checking is used when lint_engine option is changed

### ISSUE THREAD

**Issue by rcasta74** [wsdjeg/SpaceVim#4606]
## Expected behavior, english is required
Function syntax_checking should be the one defined for the option lint_engine, while it look like that the option is read after the definition of the function.

## The reproduce ways from Vim starting (Required!)
1) Apply the following patch for test:
```
--- a/autoload/SpaceVim/layers/core/statusline.vim
+++ b/autoload/SpaceVim/layers/core/statusline.vim
@@ -235,6 +235,7 @@ endfunction
 
 if g:spacevim_lint_engine ==# 'neomake'
   function! s:syntax_checking() abort
+    return 'NAN'
     if !exists('g:loaded_neomake')
       return ''
     endif
```

2) Change lint_engine in init.toml
```
[options]
  lint_engine = 'ale'
```
3) Open _init.toml_ with  _vim_/_nvim_
`nvim .SpaceVim.d/init.toml`
The string _NAN_ is displayed into statusline, so the function _syntax_checking_ defined for _neomake_ is used.

4) Check the value of _g:spacevim_lint_engine_
`:echo g:spacevim_lint_engine`
The value _ale_ is displayed

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/roberto/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'ale'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/roberto/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: 800
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [23:13:29] [0.001] [  Info ] Loading SpaceVim from: /home/roberto/.SpaceVim/
[ SpaceVim ] [23:13:30] [0.471] [  Info ] Startup with argv: ['nvim', '.SpaceVim.d/init.toml']
[ SpaceVim ] [23:13:30] [0.509] [  Info ] start loading global config >>>
[ SpaceVim ] [23:13:30] [0.509] [  Info ] global_dir is: /home/roberto/.SpaceVim.d/
[ SpaceVim ] [23:13:30] [0.510] [  Info ] start to apply config [glob]
[ SpaceVim ] [23:13:30] [0.515] [  Info ] find local conf: /home/roberto/.SpaceVim.d/init.toml
[ SpaceVim ] [23:13:30] [0.516] [  Info ] loading cached local conf: /home/roberto/.cache/SpaceVim/conf/_home_roberto__SpaceVim_d_init_toml.json
[ SpaceVim ] [23:13:30] [0.516] [  Info ] start to apply config [local]
[ SpaceVim ] [23:13:30] [0.527] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [23:13:30] [0.663] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [23:13:30] [1.008] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [23:13:30] [1.009] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [23:13:30] [1.173] [  Info ] finished loading SpaceVim!
[   rooter ] [23:13:31] [1.597] [  Info ] Load projects cache from: /home/roberto/.cache/SpaceVim/projects.json
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
