### ISSUE TITLE
"K" doesn't show documentation with float window

### ISSUE THREAD

**Issue by im6chen** [wsdjeg/SpaceVim#4621]
## Expected behavior, english is required
"K" doesn't show documentation with float window, but show a buffer window. 
":map K" return "*@:GoDoc<CR>"
I tried ":lua vim.lsp.buf.hover()" on method text but no response.

Before using SpaceVim, ”K“ works well with the traditional .vim setting.
I can't fix it, so looking for help.
Thanks!

## The reproduce ways from Vim starting (Required!)
1. Start neovim by $nvim
2. Choose a golang file by index.
3. press "K" or "SPC l d" on a golang method text.(after "vim-go: Finished loading packages.")

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 0
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/liuchen/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/liuchen/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'srcery-vim'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lang#go"
[[layers]]
  name="shell"
  default_position='float'
  default_height=30
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/local/Cellar/neovim/0.6.1/bin/nvim)
version: NVIM v0.6.1
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:47:49] [0.001] [  Info ] Loading SpaceVim from: /Users/liuchen/.SpaceVim/
[ SpaceVim ] [12:47:49] [0.375] [  Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [12:47:50] [0.392] [  Info ] start loading global config >>>
[ SpaceVim ] [12:47:50] [0.392] [  Info ] global_dir is: /Users/liuchen/.SpaceVim.d/
[ SpaceVim ] [12:47:50] [0.392] [  Info ] start to apply config [glob]
[ SpaceVim ] [12:47:50] [0.395] [  Info ] find local conf: /Users/liuchen/.SpaceVim.d/init.toml
[ SpaceVim ] [12:47:50] [0.396] [  Info ] loading cached local conf: /Users/liuchen/.cache/SpaceVim/conf/_Users_liuchen__SpaceVim_d_init_toml.json
[ SpaceVim ] [12:47:50] [0.396] [  Info ] start to apply config [local]
[ SpaceVim ] [12:47:50] [0.458] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:47:50] [0.503] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:47:50] [0.503] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [12:47:50] [0.594] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [12:47:50] [0.751] [  Info ] try to open SpaceVim welcome page
[   rooter ] [12:47:50] [0.920] [  Info ] Load projects cache from: /Users/liuchen/.cache/SpaceVim/projects.json
[   rooter ] [12:48:01] [11.937] [  Info ] Start to find root for: /Users/liuchen/go/src/gin-demo/main.go
[   rooter ] [12:48:01] [11.938] [  Info ]         (.git/):/Users/liuchen/go/src/gin-demo/
[   rooter ] [12:48:01] [11.941] [  Info ] buffer name: go/src/gin-demo/main.go
[   rooter ] [12:48:01] [11.941] [  Info ] change to root: /Users/liuchen/go/src/gin-demo/
[   rooter ] [12:48:05] [16.149] [  Info ] Start to find root for: /Users/liuchen/go/src/gin-demo/
[   rooter ] [12:48:05] [16.150] [  Info ]         (.git/):/Users/liuchen/go/src/gin-demo/
[   rooter ] [12:48:05] [16.153] [  Info ] buffer name: No Name
[   rooter ] [12:48:05] [16.154] [  Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

https://asciinema.org/a/opwGxKMS4A4AX201xJt5Ito65

Now it looks like this:
<img width="1432" alt="截屏2022-04-05 12 53 27" src="https://user-images.githubusercontent.com/48371247/161737882-a881f0f0-2a4c-454b-b0dd-61c8e1f752b6.png">

But what I want is :
<img width="1358" alt="截屏2022-04-03 23 30 23" src="https://user-images.githubusercontent.com/48371247/161737676-afb5c0b0-f3e9-41d5-931b-fe9464c5f952.png">
