### ISSUE TITLE
formatting `.tsx` (typescriptreact) does not work

### ISSUE THREAD

**Issue by alk-mandrianarijaona** [wsdjeg/SpaceVim#4624]
## Expected behavior, english is required
When working on file with extension `.tsx`, user should be able to format the buffer. Currently, the formatting is not working for this file type `Typescript react`. 

## The reproduce ways from Vim starting (Required!)
Clone an example project https://github.com/bahmutov/prettier-config-example.
Create a file with extension `.tsx` (in folder ProjectA on the sample project) and add some content that need formatting : 

```
const o =      {
    name: "Gleb",
    age: 39,
    hacker: true,
    twitter: "@bahmutov",
    site: "https://gleb.dev"
};
```
Call `SPC b f` to format the buffer. A message is displayed: `Neoformat: no change necessary`. If neoformat verbose mode is enabled,, and additional information is given `Neoformat: executable: prettier is not an executable`. On other files with extension `js` or `ts`, the formatter works just fine.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '➭'
  custom_color_palette = []
  custom_plugins = [['justinmk/vim-sneak', {'repo': 'justinmk/vim-sneak', 'overwrite': 1}], ['TimUntersberger/neogit', {'repo': 'TimUntersberger/neogit', 'overwrite': 1}], ['nvim-lua/plenary.nvim', {'repo': 'nvim-lua/plenary.nvim', 'overwrite': 1}], ['github/copilot.vim', {'repo': 'github/copilot.vim', 'overwrite': 1}]]
  data_dir = '/Users/mika/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 1
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'defx'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/mika/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-lsp'
  project_auto_root = 1
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '.SpaceVim.d/', 'tsconfig.json', 'package.json', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left_sections = ['winnr', 'filename', 'major mode', 'search count', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['@fixme', '@question', '@todo', '@idea']
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/node_modules/*,*/coverage/*'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
  lint_on_save=1
  lint_on_the_fly=1
[[layers]]
  name="format"
  format_on_save=1
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  filetree_show_hidden=1
  enable_smooth_scrolling=1
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#typescript"
[[layers]]
  name="git"
  git_plugin='gina'
[[layers]]
  name="denite"
[[layers]]
  name="VersionControl"
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
[[layers]]
  name="github"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#python"
  enabled_linters=['flake8']
[[layers]]
  name="colorscheme"
[[layers]]
  name="test"
  use_ultest=1
  override_config={'python_runner': 'pytest'}
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#rust"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
[[layers]]
  name="lsp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.6.1/bin/nvim)
version: NVIM v0.6.1
OS: mac
[shell, shellcmdflag, shellslash]: ['fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:19:09] [0.001] [  Info ] Loading SpaceVim from: /Users/mika/.SpaceVim/
[ SpaceVim ] [16:19:09] [0.123] [  Info ] Startup with directory: ~/Workspace/prettier-config-example
[ SpaceVim ] [16:19:09] [0.133] [  Info ] start loading global config >>>
[ SpaceVim ] [16:19:09] [0.133] [  Info ] global_dir is: /Users/mika/.SpaceVim.d/
[ SpaceVim ] [16:19:09] [0.134] [  Info ] start to apply config [glob]
[   rooter ] [16:19:09] [0.134] [  Info ] Load projects cache from: /Users/mika/.cache/SpaceVim/projects.json
[   rooter ] [16:19:09] [0.135] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:09] [0.136] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:09] [0.136] [  Info ] buffer name: .
[   rooter ] [16:19:09] [0.136] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:19:09] [0.491] [  Info ] Could not find project local config
[ SpaceVim ] [16:19:10] [0.529] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:19:10] [0.564] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:19:10] [0.564] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [16:19:10] [0.587] [  Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [16:19:10] [0.598] [  Info ] try to call func of mode:hi-characters-for-long-lines
[ SpaceVim ] [16:19:10] [0.598] [  Info ] no func found for mode:hi-characters-for-long-lines
[ SpaceVim ] [16:19:10] [0.707] [  Info ] finished loading SpaceVim!
[   rooter ] [16:19:10] [0.812] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [16:19:10] [0.812] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:10] [0.812] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:10] [0.813] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:10] [0.814] [  Info ] buffer name: .
[   rooter ] [16:19:10] [0.814] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:19:10] [0.896] [  Info ] try to open SpaceVim welcome page
[   rooter ] [16:19:10] [1.067] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:10] [1.068] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:10] [1.069] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:10] [1.070] [  Info ] buffer name: No Name
[   rooter ] [16:19:10] [1.070] [  Info ] same as current directory, no need to change.
[   rooter ] [16:19:13] [4.111] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/[defx] -0
[   rooter ] [16:19:13] [4.111] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:13] [4.113] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:13] [4.114] [  Info ] buffer name: [defx] -0
[   rooter ] [16:19:13] [4.114] [  Info ] same as current directory, no need to change.
[   rooter ] [16:19:18] [8.885] [  Info ] buffer name: No Name
[   rooter ] [16:19:18] [8.885] [  Info ] same as current directory, no need to change.
[   rooter ] [16:19:18] [9.095] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/project-with-typescript/index.ts
[   rooter ] [16:19:18] [9.096] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:18] [9.097] [  Info ]         (tsconfig.json):/Users/mika/Workspace/prettier-config-example/project-with-typescript/
[   rooter ] [16:19:18] [9.098] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:18] [9.098] [  Info ] buffer name: /Users/mika/Workspace/prettier-config-example/project-with-typescript/index.ts
[   rooter ] [16:19:18] [9.098] [  Info ] same as current directory, no need to change.
[   rooter ] [16:19:26] [16.915] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:26] [16.915] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:26] [16.917] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:26] [16.918] [  Info ] buffer name: No Name
[   rooter ] [16:19:26] [16.918] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:19:26] [16.950] [  Info ] key binding guide float statusline winid:1004
[   rooter ] [16:19:27] [18.009] [  Info ] buffer name: /Users/mika/Workspace/prettier-config-example/project-with-typescript/index.ts
[   rooter ] [16:19:27] [18.010] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:19:27] [18.023] [  Info ] close float statusline winid:1004
[   rooter ] [16:19:27] [18.030] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:27] [18.030] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:27] [18.032] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:27] [18.033] [  Info ] buffer name: No Name
[   rooter ] [16:19:27] [18.033] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:19:27] [18.054] [  Info ] key binding guide float statusline winid:1006
[   rooter ] [16:19:27] [18.359] [  Info ] buffer name: /Users/mika/Workspace/prettier-config-example/project-with-typescript/index.ts
[   rooter ] [16:19:27] [18.360] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:19:27] [18.369] [  Info ] close float statusline winid:1006
[   rooter ] [16:19:30] [20.786] [  Info ] buffer name: [defx] -0
[   rooter ] [16:19:30] [20.786] [  Info ] same as current directory, no need to change.
[   rooter ] [16:19:32] [22.945] [  Info ] buffer name: /Users/mika/Workspace/prettier-config-example/project-with-typescript/index.ts
[   rooter ] [16:19:32] [22.945] [  Info ] same as current directory, no need to change.
[   rooter ] [16:19:32] [23.138] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/projectA/index.tsx
[   rooter ] [16:19:32] [23.139] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:32] [23.140] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:19:32] [23.141] [  Info ] buffer name: projectA/index.tsx
[   rooter ] [16:19:32] [23.141] [  Info ] same as current directory, no need to change.
[   rooter ] [16:21:33] [143.560] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:21:33] [143.561] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:21:33] [143.562] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:21:33] [143.563] [  Info ] buffer name: No Name
[   rooter ] [16:21:33] [143.563] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:21:33] [143.583] [  Info ] key binding guide float statusline winid:1008
[   rooter ] [16:21:33] [144.179] [  Info ] buffer name: projectA/index.tsx
[   rooter ] [16:21:33] [144.180] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:21:33] [144.194] [  Info ] close float statusline winid:1008
[   rooter ] [16:21:33] [144.199] [  Info ] Start to find root for: /Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:21:33] [144.200] [  Info ]         (.git/):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:21:33] [144.202] [  Info ]         (package.json):/Users/mika/Workspace/prettier-config-example/
[   rooter ] [16:21:33] [144.202] [  Info ] buffer name: No Name
[   rooter ] [16:21:33] [144.202] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:21:33] [144.223] [  Info ] key binding guide float statusline winid:1010
[   rooter ] [16:21:35] [145.842] [  Info ] buffer name: projectA/index.tsx
[   rooter ] [16:21:35] [145.842] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [16:21:35] [145.852] [  Info ] close float statusline winid:1010
[   rooter ] [16:22:47] [217.513] [  Info ] Start to find root for: /Users/mika/.SpaceVim.d/init.toml
[   rooter ] [16:22:47] [217.515] [  Info ] buffer name: /Users/mika/.SpaceVim.d/init.toml
[   rooter ] [16:22:47] [217.515] [  Info ] same as current directory, no need to change.
[   rooter ] [16:22:54] [224.734] [  Info ] Start to find root for: /Users/mika/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [16:22:54] [224.736] [  Info ] buffer name: /Users/mika/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [16:22:54] [224.736] [  Info ] same as current directory, no need to change.
[   rooter ] [16:24:55] [345.806] [  Info ] buffer name: /Users/mika/.SpaceVim.d/init.toml
[   rooter ] [16:24:55] [345.806] [  Info ] same as current directory, no need to change.
[   rooter ] [16:24:57] [348.064] [  Info ] buffer name: projectA/index.tsx
[   rooter ] [16:24:57] [348.064] [  Info ] same as current directory, no need to change.
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

https://user-images.githubusercontent.com/72619409/161778323-5e2853ac-701b-4ca7-92f2-ece891eb2fff.mov
