### ISSUE TITLE
Error open shell with ['] (open-shell)

### ISSUE THREAD

**Issue by mrmodolo** [wsdjeg/SpaceVim#4644]
## Simply run vim and open a new shell with **ESC '**

```
Error detected while processing function <SNR>48_open_default_shell:                                                                                   
line  111:                                                                                                                                             
E475: Invalid value for argument cwd  
## Output of the `:SPDebugInfo!`
```
Note 1: If you open the shell with ESC " (open-shell-in-buffer-dir) the error does not happen

Note 2: With neovim the error does not happen. With vim 8.1 and 8.2 the error happens

## SPDebugInfo

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['https://github.com/hashivim/vim-terraform', {'repo': 'https://github.com/hashivim/vim-terraform', 'merged': 0, 'overwrite': 1}], ['https://github.com/hashivim/vim-terraform', {'repo': 'https://github.com/hashivim/vim-terraform', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/modolo/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/modolo/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_shell='terminal'
  default_position='bottom'
  default_height=25
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/home/modolo/opt/vim/bin/vim)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:34:48] [0.000] [  Info ] Loading SpaceVim from: /home/modolo/.SpaceVim/
[ SpaceVim ] [09:34:48] [0.075] [  Info ] Startup with argv: ['vim', 'spdebug.info']
[ SpaceVim ] [09:34:48] [0.088] [  Info ] start loading global config >>>
[ SpaceVim ] [09:34:48] [0.088] [  Info ] global_dir is: /home/modolo/.SpaceVim.d/
[ SpaceVim ] [09:34:48] [0.089] [  Info ] start to apply config [glob]
[ SpaceVim ] [09:34:48] [0.090] [  Info ] find local conf: /home/modolo/.SpaceVim.d/init.toml
[ SpaceVim ] [09:34:48] [0.091] [  Info ] loading cached local conf: /home/modolo/.cache/SpaceVim/conf/_home_modolo__SpaceVim_d_init_toml.json
[ SpaceVim ] [09:34:48] [0.091] [  Info ] start to apply config [local]
[ SpaceVim ] [09:34:48] [0.097] [  Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [09:34:48] [0.152] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:34:48] [0.197] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:34:48] [0.197] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [09:34:48] [0.291] [  Info ] finished loading SpaceVim!
[   rooter ] [09:34:48] [0.402] [  Info ] Load projects cache from: /home/modolo/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:35:03] [15.230] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:35:03] [15.247] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:35:03] [15.247] [  Info ] the func has been added to mode:paste-mode
```
</details>

## Screenshots

Opening the shell with ESC ' (open-shell)
![2022-04-21_09-49](https://user-images.githubusercontent.com/1923174/164461569-74633540-f93e-4811-ae70-5b2f8e1fc199.png)

Opening the shell with ESC " (open-shell-in-buffer-dir)
![2022-04-21_09-51](https://user-images.githubusercontent.com/1923174/164462001-79626ab8-e654-441a-8116-e25b79dd1895.png)
