### ISSUE TITLE
[neovim] Indent Blankline breaks jump to line

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4649]
## Expected behavior, english is required

When using jump-to-line with `[SPC] j l` I expect to see the jump targets on the left of the lines.

It does not work when Indent Blankline is enabled (which is the default behavior) because it appears that the jump targets are hidden by the indent marker (I can jump to a line where there is no target displayed when I randomly choose a key).  

It works when Indent Blankline is disabled with `[SPC] t h i` before jumping, or on not indented lines.

## The reproduce ways from Vim starting (Required!)

Open a file (python file for instance).

Hit `[SPC] j l`.

Targets are shown only on lines without indentation.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/vim-scripts/argtextobj.vim', {'repo': 'https://github.com/vim-scripts/argtextobj.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/KabbAmine/zeavim.vim', {'repo': 'https://github.com/KabbAmine/zeavim.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_gitstatus = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'vimfiler'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'JetBrainsMono Nerd Font Mono:h10.5:l'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'Denite-sources'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 40
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="cscope"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
[[layers]]
  name="denite"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.6.1
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

colorscheme layer health:

ok

cscope layer health:

ok

shell layer health:

ok

lang#c layer health:

ok

lang#python layer health:

ok

git layer health:

ok

VersionControl layer health:

ok

debug layer health:

ok

denite layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [10:43:25] [0.000] [  Info ] Loading SpaceVim from: /home/jacky/.SpaceVim/
[ SpaceVim ] [10:43:26] [0.084] [  Info ] Startup with no argv, current dir is used: ~/dev/QGIS
[ SpaceVim ] [10:43:26] [0.089] [  Info ] start loading global config >>>
[ SpaceVim ] [10:43:26] [0.089] [  Info ] global_dir is: /home/jacky/.SpaceVim.d/
[ SpaceVim ] [10:43:26] [0.090] [  Info ] find global config: /home/jacky/.SpaceVim.d/init.toml
[ SpaceVim ] [10:43:26] [0.090] [  Info ] start to apply config [glob]
[ SpaceVim ] [10:43:26] [0.093] [  Info ] start loading local config >>>
[ SpaceVim ] [10:43:26] [0.093] [  Info ] Could not find project local config
[ SpaceVim ] [10:43:26] [0.095] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [10:43:26] [0.122] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [10:43:26] [0.168] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [10:43:26] [0.168] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [10:43:26] [0.185] [  Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [10:43:26] [0.194] [  Info ] try to call func of mode:whitespace
[ SpaceVim ] [10:43:26] [0.194] [  Info ] no func found for mode:whitespace
[   rooter ] [10:43:26] [0.207] [  Info ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[ SpaceVim ] [10:43:26] [0.241] [  Info ] finished loading SpaceVim!
[   rooter ] [10:43:26] [0.303] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [10:43:26] [0.303] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:43:26] [0.303] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:43:26] [0.304] [  Info ] buffer name: No Name
[   rooter ] [10:43:26] [0.304] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:43:26] [0.309] [  Info ] try to open SpaceVim welcome page
[   rooter ] [10:43:26] [0.401] [  Info ] buffer name: No Name
[   rooter ] [10:43:26] [0.401] [  Info ] same as current directory, no need to change.
[   rooter ] [10:43:27] [1.530] [  Info ] Start to find root for: /home/jacky/dev/QGIS/tests/src/python/test_provider_oracle.py
[   rooter ] [10:43:27] [1.530] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:43:27] [1.531] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:43:27] [1.531] [  Info ] same as current directory, no need to change.
[   rooter ] [10:45:05] [100.032] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:45:05] [100.032] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:45:05] [100.033] [  Info ] buffer name: No Name
[   rooter ] [10:45:05] [100.033] [  Info ] same as current directory, no need to change.
[   rooter ] [10:45:06] [100.055] [  Info ] Start to find root for: /usr/share/nvim/runtime/doc/pattern.txt
[   rooter ] [10:45:12] [106.994] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:45:12] [106.994] [  Info ] same as current directory, no need to change.
[   rooter ] [10:45:19] [113.333] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:45:19] [113.333] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:45:19] [113.334] [  Info ] buffer name: No Name
[   rooter ] [10:45:19] [113.334] [  Info ] same as current directory, no need to change.
[   rooter ] [10:45:19] [113.358] [  Info ] Start to find root for: /home/jacky/.SpaceVim/doc/SpaceVim.txt
[   rooter ] [10:45:19] [113.358] [  Info ]         (.git/):/home/jacky/.SpaceVim/
[   rooter ] [10:45:19] [113.359] [  Info ] buffer name: /home/jacky/.SpaceVim/doc/SpaceVim.txt
[   rooter ] [10:45:19] [113.359] [  Info ] change to root: /home/jacky/.SpaceVim/
[   rooter ] [10:45:52] [146.980] [  Info ] Start to find root for: /usr/share/nvim/runtime/doc/options.txt
[   rooter ] [10:47:37] [251.507] [  Info ] Start to find root for: /home/jacky/.cache/vimfiles/.cache/init.vim/.dein/doc/indent_blankline.txt
[   rooter ] [10:47:50] [264.986] [  Info ] buffer name: /home/jacky/dev/QGIS/tests/src/python/test_provider_oracle.py
[   rooter ] [10:47:50] [264.986] [  Info ] change to root: /home/jacky/dev/QGIS/
[   rooter ] [10:48:10] [284.259] [  Info ] Start to find root for: /home/jacky/.cache/vimfiles/.cache/init.vim/.dein/doc/indent_blankline.txt
[   rooter ] [10:49:09] [343.722] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:49:09] [343.722] [  Info ] same as current directory, no need to change.
[   rooter ] [10:50:58] [452.192] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:50:58] [452.192] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:50:58] [452.193] [  Info ] buffer name: No Name
[   rooter ] [10:50:58] [452.193] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:50:58] [452.207] [  Info ] key binding guide float statusline winid:1006
[   rooter ] [10:50:58] [452.224] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:50:58] [452.224] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:50:58] [452.238] [  Info ] close float statusline winid:1006
[   rooter ] [10:50:58] [452.244] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:50:58] [452.244] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:50:58] [452.245] [  Info ] buffer name: No Name
[   rooter ] [10:50:58] [452.245] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:50:58] [452.258] [  Info ] key binding guide float statusline winid:1008
[   rooter ] [10:50:59] [453.955] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:50:59] [453.955] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:50:59] [453.959] [  Info ] close float statusline winid:1008
[   rooter ] [10:51:01] [455.279] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:51:01] [455.280] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:51:01] [455.280] [  Info ] buffer name: No Name
[   rooter ] [10:51:01] [455.280] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:01] [455.295] [  Info ] key binding guide float statusline winid:1010
[   rooter ] [10:51:01] [455.312] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:51:01] [455.312] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:01] [455.317] [  Info ] close float statusline winid:1010
[   rooter ] [10:51:01] [455.323] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:51:01] [455.323] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:51:01] [455.324] [  Info ] buffer name: No Name
[   rooter ] [10:51:01] [455.324] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:01] [455.338] [  Info ] key binding guide float statusline winid:1012
[   rooter ] [10:51:01] [455.354] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:51:01] [455.354] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:01] [455.359] [  Info ] close float statusline winid:1012
[   rooter ] [10:51:02] [456.513] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:51:02] [456.513] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:51:02] [456.514] [  Info ] buffer name: No Name
[   rooter ] [10:51:02] [456.514] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:02] [456.527] [  Info ] key binding guide float statusline winid:1014
[   rooter ] [10:51:05] [459.068] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:51:05] [459.068] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:05] [459.075] [  Info ] close float statusline winid:1014
[   rooter ] [10:51:05] [459.085] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:51:05] [459.085] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:51:05] [459.086] [  Info ] buffer name: No Name
[   rooter ] [10:51:05] [459.086] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:51:05] [459.102] [  Info ] key binding guide float statusline winid:1016
[   rooter ] [10:53:14] [588.229] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:14] [588.229] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:14] [588.235] [  Info ] close float statusline winid:1016
[   rooter ] [10:53:15] [589.844] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:15] [589.844] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:15] [589.845] [  Info ] buffer name: No Name
[   rooter ] [10:53:15] [589.846] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:15] [589.867] [  Info ] key binding guide float statusline winid:1018
[   rooter ] [10:53:15] [589.896] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:15] [589.896] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:15] [589.902] [  Info ] close float statusline winid:1018
[   rooter ] [10:53:15] [589.912] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:15] [589.913] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:15] [589.914] [  Info ] buffer name: No Name
[   rooter ] [10:53:15] [589.914] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:15] [589.935] [  Info ] key binding guide float statusline winid:1020
[   rooter ] [10:53:15] [589.964] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:15] [589.964] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:15] [589.970] [  Info ] close float statusline winid:1020
[   rooter ] [10:53:19] [593.520] [  Info ] Start to find root for: /home/jacky/dev/QGIS/vimfiler:default
[   rooter ] [10:53:19] [593.521] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:19] [593.522] [  Info ] buffer name: vimfiler:default
[   rooter ] [10:53:19] [593.522] [  Info ] same as current directory, no need to change.
[   rooter ] [10:53:19] [593.540] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:19] [593.540] [  Info ] same as current directory, no need to change.
[   rooter ] [10:53:21] [595.605] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:21] [595.606] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:21] [595.607] [  Info ] buffer name: No Name
[   rooter ] [10:53:21] [595.607] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:21] [595.636] [  Info ] key binding guide float statusline winid:1024
[   rooter ] [10:53:21] [595.669] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:21] [595.669] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:21] [595.675] [  Info ] close float statusline winid:1024
[   rooter ] [10:53:21] [595.686] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:21] [595.686] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:21] [595.687] [  Info ] buffer name: No Name
[   rooter ] [10:53:21] [595.687] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:21] [595.709] [  Info ] key binding guide float statusline winid:1026
[   rooter ] [10:53:25] [599.820] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:25] [599.821] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:25] [599.827] [  Info ] close float statusline winid:1026
[   rooter ] [10:53:27] [601.479] [  Info ] buffer name: vimfiler:default
[   rooter ] [10:53:27] [601.479] [  Info ] same as current directory, no need to change.
[   rooter ] [10:53:27] [601.491] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:27] [601.491] [  Info ] same as current directory, no need to change.
[   rooter ] [10:53:32] [606.493] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:32] [606.493] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:32] [606.494] [  Info ] buffer name: No Name
[   rooter ] [10:53:32] [606.494] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:32] [606.514] [  Info ] key binding guide float statusline winid:1030
[   rooter ] [10:53:32] [606.815] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:32] [606.815] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:32] [606.824] [  Info ] close float statusline winid:1030
[   rooter ] [10:53:32] [606.842] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:32] [606.842] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:32] [606.843] [  Info ] buffer name: No Name
[   rooter ] [10:53:32] [606.843] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:32] [606.863] [  Info ] key binding guide float statusline winid:1032
[   rooter ] [10:53:33] [607.311] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:33] [607.311] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:33] [607.320] [  Info ] close float statusline winid:1032
[   rooter ] [10:53:33] [607.338] [  Info ] Start to find root for: /home/jacky/dev/QGIS/
[   rooter ] [10:53:33] [607.339] [  Info ]         (.git/):/home/jacky/dev/QGIS/
[   rooter ] [10:53:33] [607.340] [  Info ] buffer name: No Name
[   rooter ] [10:53:33] [607.341] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:33] [607.372] [  Info ] key binding guide float statusline winid:1034
[   rooter ] [10:53:35] [609.231] [  Info ] buffer name: tests/src/python/test_provider_oracle.py
[   rooter ] [10:53:35] [609.231] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [10:53:35] [609.240] [  Info ] close float statusline winid:1034
[ SpaceVim ] [10:54:25] [659.126] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [10:54:25] [659.133] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [10:54:25] [659.133] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [10:54:25] [659.140] [  Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [10:54:25] [659.145] [  Info ] try to call func of mode:whitespace
[ SpaceVim ] [10:54:25] [659.145] [  Info ] no func found for mode:whitespace
[ SpaceVim ] [10:54:25] [659.151] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [10:54:25] [659.151] [  Info ] statusline build-in section hunks has been changed!
```
</details>

## Screenshots

The targets for indented lines seems hidden by the indentation level marker.

![image](https://user-images.githubusercontent.com/34267385/165262422-bcaf408d-f71c-4b0a-a380-a10704ef037e.png)

After hiding the indentation level markers

![image](https://user-images.githubusercontent.com/34267385/165263169-69273bfd-527d-4a62-afeb-d2130d027acc.png)
