### ISSUE TITLE
Can not select a theme via fuzzy finder binding SPC T s - does not exist

### ISSUE THREAD

**Issue by dixonge** [wsdjeg/SpaceVim#4659]
## Expected behavior, english is required

Expected this binding to be present, as it is in the official Docs:

https://spacevim.org/documentation/#colorschemes

Mappings | Descriptions
-- | --
SPC T n | switch to a random colorscheme listed in colorscheme layer.
SPC T s | select a theme using a fuzzy finder.

## The reproduce ways from Vim starting (Required!)

I don't understand this instruction...? I mean, you hit SPC-T and there is no 's' option available...

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['renerocksai/calendar-vim', {'repo': 'renerocksai/calendar-vim', 'overwrite': 1}], ['nvim-telescope/telescope.nvim', {'repo': 'nvim-telescope/telescope.nvim', 'overwrite': 1}], ['nvim-telescope/telescope-symbols.nvim', {'repo': 'nvim-telescope/telescope-symbols.nvim', 'overwrite': 1}], ['iamcco/markdown-preview.nvim', {'repo': 'iamcco/markdown-preview.nvim', 'overwrite': 1}], ['mzlogin/vim-markdown-toc', {'repo': 'mzlogin/vim-markdown-toc', 'overwrite': 1}]]
  data_dir = '/Users/donblanco/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/donblanco/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimshell.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/opt/homebrew/Cellar/neovim/0.7.0/bin/nvim)
version: NVIM v0.7.0
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

colorscheme layer health:

ok

shell layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:47:42] [0.001] [  Info ] Loading SpaceVim from: /Users/donblanco/.SpaceVim/
[ SpaceVim ] [08:47:42] [0.137] [  Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [08:47:42] [0.142] [  Info ] start loading global config >>>
[ SpaceVim ] [08:47:42] [0.142] [  Info ] global_dir is: /Users/donblanco/.SpaceVim.d/
[ SpaceVim ] [08:47:42] [0.142] [  Info ] find global config: /Users/donblanco/.SpaceVim.d/init.toml
[ SpaceVim ] [08:47:42] [0.145] [  Info ] start to apply config [glob]
[ SpaceVim ] [08:47:42] [0.146] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [08:47:42] [0.147] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [08:47:42] [0.165] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [08:47:42] [0.180] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [08:47:42] [0.180] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [08:47:42] [0.215] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [08:47:42] [0.260] [  Info ] try to open SpaceVim welcome page
[   rooter ] [08:47:42] [0.350] [  Info ] Load projects cache from: /Users/donblanco/.cache/SpaceVim/projects.json
[   rooter ] [08:57:20] [578.530] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:20] [578.549] [  Info ] key binding guide float statusline winid:1004
[   rooter ] [08:57:21] [579.161] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:21] [579.164] [  Info ] close float statusline winid:1004
[   rooter ] [08:57:21] [579.173] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:21] [579.191] [  Info ] key binding guide float statusline winid:1006
[   rooter ] [08:57:25] [582.980] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:25] [582.983] [  Info ] close float statusline winid:1006
[   rooter ] [08:57:44] [601.757] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:44] [601.775] [  Info ] key binding guide float statusline winid:1008
[   rooter ] [08:57:44] [602.050] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:44] [602.053] [  Info ] close float statusline winid:1008
[   rooter ] [08:57:50] [608.538] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:50] [608.556] [  Info ] key binding guide float statusline winid:1010
[   rooter ] [08:57:58] [615.935] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:57:58] [615.938] [  Info ] close float statusline winid:1010
[   rooter ] [08:58:02] [619.998] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:58:02] [620.016] [  Info ] key binding guide float statusline winid:1012
[   rooter ] [08:58:19] [637.564] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:58:19] [637.567] [  Info ] close float statusline winid:1012
[   rooter ] [08:58:19] [637.576] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:58:19] [637.595] [  Info ] key binding guide float statusline winid:1014
[   rooter ] [08:58:22] [640.470] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:58:22] [640.473] [  Info ] close float statusline winid:1014
[   rooter ] [08:58:24] [642.159] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:58:24] [642.176] [  Info ] key binding guide float statusline winid:1016
[   rooter ] [08:58:33] [651.296] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [08:58:33] [651.299] [  Info ] close float statusline winid:1016
[   rooter ] [09:41:44] [3242.688] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:45] [3242.714] [  Info ] key binding guide float statusline winid:1018
[   rooter ] [09:41:47] [3244.789] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:47] [3244.791] [  Info ] close float statusline winid:1018
[   rooter ] [09:41:47] [3244.800] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:47] [3244.817] [  Info ] key binding guide float statusline winid:1020
[   rooter ] [09:41:49] [3247.105] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:49] [3247.108] [  Info ] close float statusline winid:1020
[   rooter ] [09:41:51] [3249.510] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:51] [3249.528] [  Info ] key binding guide float statusline winid:1022
[   rooter ] [09:41:52] [3250.061] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:52] [3250.064] [  Info ] close float statusline winid:1022
[   rooter ] [09:41:52] [3250.073] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:41:52] [3250.090] [  Info ] key binding guide float statusline winid:1024
[   rooter ] [09:42:26] [3283.938] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:26] [3283.940] [  Info ] close float statusline winid:1024
[   rooter ] [09:42:28] [3286.201] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:28] [3286.218] [  Info ] key binding guide float statusline winid:1026
[   rooter ] [09:42:28] [3286.545] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:28] [3286.548] [  Info ] close float statusline winid:1026
[   rooter ] [09:42:28] [3286.556] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:28] [3286.574] [  Info ] key binding guide float statusline winid:1028
[   rooter ] [09:42:30] [3288.696] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:30] [3288.699] [  Info ] close float statusline winid:1028
[   rooter ] [09:42:32] [3290.314] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:32] [3290.333] [  Info ] key binding guide float statusline winid:1030
[   rooter ] [09:42:35] [3293.563] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:35] [3293.565] [  Info ] close float statusline winid:1030
[   rooter ] [09:42:35] [3293.574] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:42:35] [3293.592] [  Info ] key binding guide float statusline winid:1032
[   rooter ] [09:55:05] [4043.261] [  Info ] Start to find root for: /Users/donblanco/
[ SpaceVim ] [09:55:05] [4043.264] [  Info ] close float statusline winid:1032
[ SpaceVim ] [09:55:18] [4055.856] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:55:18] [4055.869] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:55:18] [4055.869] [  Info ] the func has been added to mode:paste-mode
```
</details>

## Screenshots

<img width="1001" alt="SPC-T-spacevim" src="https://user-images.githubusercontent.com/1578506/166479877-bbee29df-a8fe-44f7-9f25-5de2358dec71.png">
