### ISSUE TITLE
docker version of SpaceVim has no write permission to volume

### ISSUE THREAD

**Issue by CyrusYip** [wsdjeg/SpaceVim#4673]
## Expected behavior, english is required

SpaceVim can modify files in host.

## The reproduce ways from Vim starting (Required!)

Run SpaceVim by:

```
docker run -i -t --rm -v $(pwd):/home/spacevim/src spacevim/spacevim:latest
```

Edit the file and save by `:w`, and it shows `E505: "src/hello.md" is read-only (add ! to override)`. Save by `:w!`, and it shows `E212: Can't open file for writing: permission denied`.

I tried other docker images such as Arch Linux and Ubuntu. They can write files.

```
docker run -i -t --rm -v $(pwd):/home/spacevim/src archlinux:base-devel
docker run -i -t --rm -v $(pwd):/home/spacevim/src ubuntu:latest
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 0
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/spacevim/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/spacevim/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'open-browser.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.0.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/local/bin/nvim)
version: NVIM v0.8.0-dev+90-gcc2754056
OS: linux
[shell, shellcmdflag, shellslash]: ['sh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [01:31:22] [0.000] [  Info ] Loading SpaceVim from: /home/spacevim/.SpaceVim/
[ SpaceVim ] [01:31:22] [0.177] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [01:31:22] [0.177] [  Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [01:31:22] [0.202] [  Info ] start loading global config >>>
[ SpaceVim ] [01:31:22] [0.203] [  Info ] global_dir is: /home/spacevim/.SpaceVim.d/
[ SpaceVim ] [01:31:22] [0.203] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [01:31:22] [0.208] [  Info ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [01:31:22] [0.283] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [01:31:22] [0.322] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [01:31:22] [0.322] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [01:31:22] [0.378] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [01:31:22] [0.461] [  Info ] try to open SpaceVim welcome page
[   rooter ] [01:31:22] [0.504] [  Info ] projects cache file does not exists!
[   rooter ] [01:31:24] [2.475] [  Info ] Start to find root for: /home/spacevim/NERD_tree_1
[   rooter ] [01:31:28] [6.872] [  Info ] Start to find root for: /home/spacevim/src/hello.md
[   rooter ] [01:31:34] [12.877] [  Info ] Start to find root for: /home/spacevim/src/hello.md
[ SpaceVim ] [01:32:58] [96.330] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [01:32:58] [96.355] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [01:32:58] [96.356] [  Info ] the func has been added to mode:paste-mode
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<img width="945" alt="spacevim" src="https://user-images.githubusercontent.com/60951091/168940081-35e246cd-4685-438e-9ed6-ec5142f51705.png">

<img width="945" alt="arch" src="https://user-images.githubusercontent.com/60951091/168939703-5acbe57f-3b40-4e73-b169-e39fb695ef4d.png">

<img width="951" alt="ubuntu" src="https://user-images.githubusercontent.com/60951091/168939716-20c894cf-874e-4b35-a37e-9da73dc5885f.png">
