### ISSUE TITLE
Changing the default_custom_leader setting results in E756

### ISSUE THREAD

**Issue by dcbaok** [wsdjeg/SpaceVim#4710]
Changing the default_custom_leader option to anything but \<Space\> produces an error: 

E756: Spell checking is not possible

## Expected behavior, english is required
Expected the new leader key would replace SPC and function as the new leader key.

## The reproduce ways from Vim starting (Required!)
Update default_custom_leader by adding a line in the options section in ~/.SpaceVim.d/init.toml
    default_custom_leader = "Q"

Then start a new spacevim session and input the new leader key.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'molokai'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/user/.cache/'
  debug_level = 1
  default_custom_leader = 'Q'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/user/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'palenight.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 802
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok

colorscheme layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:04:28] [   0.000] [  Info ] Loading SpaceVim from: /home/user/.SpaceVim/
[ SpaceVim ] [11:04:28] [   0.065] [  Info ] Startup with argv: ['vim', '-u', '/home/user/.SpaceVim/vimrc']
[ SpaceVim ] [11:04:28] [   0.070] [  Info ] start loading global config >>>
[ SpaceVim ] [11:04:28] [   0.070] [  Info ] global_dir is: /home/user/.SpaceVim.d/
[ SpaceVim ] [11:04:28] [   0.070] [  Info ] find global config: /home/user/.SpaceVim.d/init.toml
[ SpaceVim ] [11:04:28] [   0.070] [  Info ] start to apply config [glob]
[ SpaceVim ] [11:04:28] [   0.071] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [11:04:28] [   0.098] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:04:28] [   0.118] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:04:28] [   0.118] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [11:04:28] [   0.157] [  Info ] finished loading SpaceVim!
[   rooter ] [11:04:28] [   0.208] [  Info ] Load projects cache from: /home/user/.cache/SpaceVim/projects.json
[ SpaceVim ] [11:04:38] [  10.246] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:04:38] [  10.256] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:04:38] [  10.257] [  Info ] the func has been added to mode:paste-mode
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
