### ISSUE TITLE
Format typescript code report `E482: Can't open file with an empty name`

### ISSUE THREAD

**Issue by gilboom** [wsdjeg/SpaceVim#4713]
## Expected behavior, english is required

format typescript code

## The reproduce ways from Vim starting (Required!)

press `SPC b f`

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.7.2
- SpaceVim version: 2.1.0-dev
- SpaceVim status: 2adcaae6

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/gilboom/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/gilboom/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-jsdoc'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'tsconfig.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#typescript"
  format_on_save=1
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok

lang#typescript layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:54:42] [0.000] [ Info  ] Loading SpaceVim from: /home/gilboom/.SpaceVim/
[ SpaceVim ] [14:54:42] [0.109] [ Info  ] Startup with directory: ~/code/multisite-service
[ SpaceVim ] [14:54:42] [0.111] [ Info  ] init default vim options
[ SpaceVim ] [14:54:42] [0.111] [ Info  ] options init done
[ SpaceVim ] [14:54:42] [0.117] [ Info  ] start loading global config >>>
[ SpaceVim ] [14:54:42] [0.117] [ Info  ] global_dir is: /home/gilboom/.SpaceVim.d/
[ SpaceVim ] [14:54:42] [0.117] [ Info  ] find global config: /home/gilboom/.SpaceVim.d/init.toml
[ SpaceVim ] [14:54:42] [0.117] [ Info  ] start to apply config [glob]
[ SpaceVim ] [14:54:42] [0.118] [ Info  ] start loading local config >>>
[ SpaceVim ] [14:54:42] [0.118] [ Info  ] Could not find project local config
[ SpaceVim ] [14:54:42] [0.166] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [14:54:42] [0.195] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [14:54:42] [0.195] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [14:54:42] [0.317] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [14:54:42] [0.491] [ Info  ] try to open SpaceVim welcome page
[  project ] [14:54:42] [0.547] [ Info  ] Load projects cache from: /home/gilboom/.cache/SpaceVim/projects.json
[  project ] [14:54:46] [4.417] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [14:54:46] [4.417] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:54:46] [4.418] [ Info  ]         (tsconfig.json):/home/gilboom/code/multisite-service/packages/server/
[  project ] [14:56:59] [137.679] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:58:07] [204.838] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:58:15] [213.396] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:58:31] [229.309] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:59:28] [286.098] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:59:44] [301.989] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:59:46] [304.052] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [14:59:50] [307.870] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[  project ] [15:01:01] [379.074] [ Info  ]         (.git/):/home/gilboom/code/multisite-service/
[ SpaceVim ] [15:02:52] [490.042] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:02:52] [490.050] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:02:52] [490.050] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [15:04:04] [562.220] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:04:04] [562.228] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:04:04] [562.229] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [15:05:48] [666.159] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:05:48] [666.167] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:05:48] [666.167] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/23697209/192456442-c0fbc7c1-7294-4cba-991c-bb23ecf316f9.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
