### ISSUE TITLE
undefined s:lsep variable

### ISSUE THREAD

**Issue by tjni** [wsdjeg/SpaceVim#4723]
**This bug only impacts a non-standard usage of SpaceVim.**

In order to install SpaceVim using [nix package manager](https://nixos.org/), I need to disable SpaceVim's plugin management system and [install plugins declaratively](https://git.sr.ht/~tni/dotfiles/tree/main/item/packages/neovim/default.nix) in my system configuration. Toward that end, I patch SpaceVim locally using the patch below, and then I run into the error in the screenshot at the bottom of this issue.

## The reproduce ways from Vim starting (Required!)

Please apply this patch:

https://git.sr.ht/~tni/dotfiles/tree/main/item/overlays/SpaceVim/patches/disable_plugin_manager.patch

and then start SpaceVim.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'bootstrap#after'
  bootstrap_before = 'bootstrap#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/tni/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['neco-syntax', 'neoinclude.vim', 'neosnippet-snippets', 'vim-snippets']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Hack Nerd Font Mono:h16'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/tni/.cache/vimfiles/'
  plugin_manager = ''
  plugin_manager_processes = 16
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = ''
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'percentage', 'cursorpos']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="fzf"
[[layers]]
  name="tmux"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/nix/store/zdw58fr4dd6isfdzzqlj2bc5d407zwm4-neovim-unwrapped-0.8.0/bin/nvim)
version: NVIM v0.8.0
OS: mac
[shell, shellcmdflag, shellslash]: ['/run/current-system/sw/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

fzf layer health:

ok

tmux layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:03:13] [0.000] [ Info  ] Loading SpaceVim from: /nix/store/135qvamiqc0pxphg4q0py0b2yvn5rffr-vimplugin-SpaceVim-2022-10-10/
[ SpaceVim ] [16:03:13] [0.051] [ Info  ] Startup with argv: ['/etc/profiles/per-user/tni/bin/nvim', '--cmd', 'let g:loaded_node_provider=0 | let g:loaded_python_provider=0 | let g:python3_host_prog=''/nix/store/anq2lqkpsn8ikr9gxlfxj6ypa8xc0az9-neovim-0.8.0/bin/nvim-python3'' | let g:loaded_ruby_provider=0', '--cmd', 'set packpath^=/nix/store/b2hfzx8spfsxpriz8b7dh25d3fi8r0x3-vim-pack-dir', '--cmd', 'set rtp^=/nix/store/b2hfzx8spfsxpriz8b7dh25d3fi8r0x3-vim-pack-dir', 'borne_ui/src/components/App.tsx']
[ SpaceVim ] [16:03:13] [0.051] [ Info  ] init default vim options
[ SpaceVim ] [16:03:13] [0.051] [ Info  ] options init done
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] start loading global config >>>
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] global_dir is: /Users/tni/.SpaceVim.d/
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] find global config: /Users/tni/.SpaceVim.d/init.toml
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] start to apply config [glob]
[ SpaceVim ] [16:03:13] [0.091] [ Info  ] start loading local config >>>
[ SpaceVim ] [16:03:13] [0.091] [ Info  ] Could not find project local config
[ SpaceVim ] [16:03:13] [0.105] [ Info  ] finished loading SpaceVim!
[  project ] [16:03:13] [0.121] [ Info  ] Load projects cache from: /Users/tni/.cache/SpaceVim/projects.json
[ SpaceVim ] [16:05:06] [113.633] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:05:06] [113.633] [ Info  ] the func has been added to mode:paste-mode

```
</details>

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/nix/store/zdw58fr4dd6isfdzzqlj2bc5d407zwm4-neovim-unwrapped-0.8.0/bin/nvim)
version: NVIM v0.8.0
OS: mac
[shell, shellcmdflag, shellslash]: ['/run/current-system/sw/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

fzf layer health:

ok

tmux layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:03:13] [0.000] [ Info  ] Loading SpaceVim from: /nix/store/135qvamiqc0pxphg4q0py0b2yvn5rffr-vimplugin-SpaceVim-2022-10-10/
[ SpaceVim ] [16:03:13] [0.051] [ Info  ] Startup with argv: ['/etc/profiles/per-user/tni/bin/nvim', '--cmd', 'let g:loaded_node_provider=0 | let g:loaded_python_provider=0 | let g:python3_host_prog=''/nix/store/anq2lqkpsn8ikr9gxlfxj6ypa8xc0az9-neovim-0.8.0/bin/nvim-python3'' | let g:loaded_ruby_provider=0', '--cmd', 'set packpath^=/nix/store/b2hfzx8spfsxpriz8b7dh25d3fi8r0x3-vim-pack-dir', '--cmd', 'set rtp^=/nix/store/b2hfzx8spfsxpriz8b7dh25d3fi8r0x3-vim-pack-dir', 'borne_ui/src/components/App.tsx']
[ SpaceVim ] [16:03:13] [0.051] [ Info  ] init default vim options
[ SpaceVim ] [16:03:13] [0.051] [ Info  ] options init done
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] start loading global config >>>
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] global_dir is: /Users/tni/.SpaceVim.d/
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] find global config: /Users/tni/.SpaceVim.d/init.toml
[ SpaceVim ] [16:03:13] [0.057] [ Info  ] start to apply config [glob]
[ SpaceVim ] [16:03:13] [0.091] [ Info  ] start loading local config >>>
[ SpaceVim ] [16:03:13] [0.091] [ Info  ] Could not find project local config
[ SpaceVim ] [16:03:13] [0.105] [ Info  ] finished loading SpaceVim!
[  project ] [16:03:13] [0.121] [ Info  ] Load projects cache from: /Users/tni/.cache/SpaceVim/projects.json
[ SpaceVim ] [16:05:06] [113.633] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:05:06] [113.633] [ Info  ] the func has been added to mode:paste-mode

```
</details>
```

## Screenshots

<img width="1728" alt="Screen Shot 2022-10-12 at 4 03 25 PM" src="https://user-images.githubusercontent.com/3806110/195463717-4401d8c8-b2a7-404a-9834-ad7b5d9986d6.png">

<!-- please remove the issue template when request for a feature -->
