### ISSUE TITLE
Toggles are not saved

### ISSUE THREAD

**Issue by perrotuerto** [wsdjeg/SpaceVim#4733]
## Expected behavior, english is required

Toggles like highlight-long-lines and toggle conceallevel should be saved.

## The reproduce ways from Vim starting (Required!)

I always have to enable them with: 'SPC t c' and 'SPC t 8'. When I close SpaceVim and opened again, I have to do the same and so on.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'palenight'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['https://github.com/peterhurford/send.vim.git', {'repo': 'https://github.com/peterhurford/send.vim.git', 'merged': 1, 'overwrite': 1}], ['https://github.com/ellisonleao/glow.nvim.git', {'repo': 'https://github.com/ellisonleao/glow.nvim.git', 'merged': 1, 'overwrite': 1}]]
  data_dir = '/home/perro/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/perro/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-virtualenv'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#python"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 900
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok

colorscheme layer health:

ok

fzf layer health:

ok

git layer health:

ok

VersionControl layer health:

ok

lang#ruby layer health:

ok

lang#python layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [18:29:13] [   0.000] [  Info ] Loading SpaceVim from: /home/perro/.SpaceVim/
[ SpaceVim ] [18:29:13] [   0.031] [  Info ] Startup with no argv, current dir is used: ~/Documentos/Django/tutorial-django
[ SpaceVim ] [18:29:13] [   0.049] [  Info ] start loading global config >>>
[ SpaceVim ] [18:29:13] [   0.049] [  Info ] global_dir is: /home/perro/.SpaceVim.d/
[ SpaceVim ] [18:29:13] [   0.049] [  Info ] find global config: /home/perro/.SpaceVim.d/init.toml
[ SpaceVim ] [18:29:13] [   0.050] [  Info ] start to apply config [glob]
[ SpaceVim ] [18:29:13] [   0.054] [  Info ] start loading local config >>>
[ SpaceVim ] [18:29:13] [   0.055] [  Info ] Could not find project local config
[ SpaceVim ] [18:29:13] [   0.137] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:29:13] [   0.211] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:29:13] [   0.211] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [18:29:14] [   0.454] [  Info ] finished loading SpaceVim!
[   rooter ] [18:29:14] [   0.512] [  Info ] Load projects cache from: /home/perro/.cache/SpaceVim/projects.json
[   rooter ] [18:29:14] [   0.581] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:14] [   0.581] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:14] [   0.583] [  Info ] buffer name: No Name
[   rooter ] [18:29:14] [   0.583] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:29:14] [   0.592] [  Info ] try to open SpaceVim welcome page
[   rooter ] [18:29:14] [   0.682] [  Info ] buffer name: No Name
[   rooter ] [18:29:14] [   0.682] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:29:21] [   8.053] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:29:21] [   8.071] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:29:21] [   8.071] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [18:29:21] [   8.097] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [18:29:21] [   8.097] [  Info ] statusline build-in section hunks has been changed!
[   rooter ] [18:29:21] [   8.109] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:21] [   8.109] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:21] [   8.111] [  Info ] buffer name: No Name
[   rooter ] [18:29:21] [   8.111] [  Info ] same as current directory, no need to change.
[   rooter ] [18:29:41] [  28.072] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:41] [  28.073] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:41] [  28.077] [  Info ] buffer name: No Name
[   rooter ] [18:29:41] [  28.077] [  Info ] same as current directory, no need to change.
[   rooter ] [18:29:43] [  29.936] [  Info ] buffer name: No Name
[   rooter ] [18:29:43] [  29.936] [  Info ] same as current directory, no need to change.
[   rooter ] [18:29:45] [  31.955] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/polls/tests.py
[   rooter ] [18:29:45] [  31.956] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:45] [  31.958] [  Info ] buffer name: /home/perro/Documentos/Django/tutorial-django/polls/tests.py
[   rooter ] [18:29:45] [  31.958] [  Info ] same as current directory, no need to change.
[   rooter ] [18:29:50] [  36.944] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:50] [  36.944] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:50] [  36.946] [  Info ] buffer name: No Name
[   rooter ] [18:29:50] [  36.946] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:29:50] [  36.991] [  Info ] key binding guide float statusline winid:1005
[ SpaceVim ] [18:29:50] [  37.018] [  Info ] close float statusline winid:1005
[   rooter ] [18:29:50] [  37.025] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:50] [  37.026] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:50] [  37.027] [  Info ] buffer name: No Name
[   rooter ] [18:29:50] [  37.027] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:29:50] [  37.059] [  Info ] key binding guide float statusline winid:1007
[ SpaceVim ] [18:29:53] [  39.478] [  Info ] close float statusline winid:1007
[   rooter ] [18:29:55] [  42.177] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:55] [  42.178] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:55] [  42.180] [  Info ] buffer name: No Name
[   rooter ] [18:29:55] [  42.180] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:29:55] [  42.208] [  Info ] key binding guide float statusline winid:1009
[ SpaceVim ] [18:29:55] [  42.231] [  Info ] close float statusline winid:1009
[   rooter ] [18:29:55] [  42.237] [  Info ] Start to find root for: /home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:55] [  42.238] [  Info ]         (.git/):/home/perro/Documentos/Django/tutorial-django/
[   rooter ] [18:29:55] [  42.239] [  Info ] buffer name: No Name
[   rooter ] [18:29:55] [  42.239] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [18:29:55] [  42.272] [  Info ] key binding guide float statusline winid:1011
[ SpaceVim ] [18:29:56] [  42.550] [  Info ] close float statusline winid:1011
[ SpaceVim ] [18:29:56] [  42.556] [  Info ] try to call func of mode:hi-characters-for-long-lines
[ SpaceVim ] [18:29:56] [  42.556] [  Info ] no func found for mode:hi-characters-for-long-lines
[ SpaceVim ] [18:30:05] [  51.694] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [18:30:05] [  51.711] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [18:30:05] [  51.711] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [18:30:05] [  51.727] [  Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [18:30:05] [  51.739] [  Info ] try to call func of mode:hi-characters-for-long-lines
[ SpaceVim ] [18:30:05] [  51.739] [  Info ] no func found for mode:hi-characters-for-long-lines
[ SpaceVim ] [18:30:05] [  51.753] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [18:30:05] [  51.753] [  Info ] statusline build-in section hunks has been changed!
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
