### ISSUE TITLE
E5108: Error executing lua ...r/start/filetype.nvim/lua/filetype/mappings/function.lua:319: Vim(call):E117: Unknown function: dist#ft#FThtml

### ISSUE THREAD

**Issue by TomYule** [wsdjeg/SpaceVim#4734]
when I open html  error

## Expected behavior, english is required
```
Error detected while processing function startify#open_buffers[6]..<SNR>217_open_buffer[12]..BufReadPost Autocommands for "*":
E5108: Error executing lua ...r/start/filetype.nvim/lua/filetype/mappings/function.lua:319: Vim(call):E117: Unknown function: dist#ft#FThtml
stack traceback:
        [C]: in function 'cmd'
        ...r/start/filetype.nvim/lua/filetype/mappings/function.lua:319: in function 'name'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:17: in function 'set_filetype'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:65: in function 'try_lookup'
        ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:168: in function 'resolve'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```
## The reproduce ways from Vim starting (Required!)
open html file
## Output of the `:SPDebugInfo!`
```
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'OceanicNext'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['mhartington/oceanic-next', {'repo': 'mhartington/oceanic-next', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/root/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
 expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/root/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-lsp'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'package.json', 'tsconfig.json', 'pom.xml', 'package.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
 snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#html"
  emmet_filetyps=['html']
  emmet_leader_key='<C-e>'
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="git"
[[layers]]
  name="JavaUnite"
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.le
vel=NONE', '-noverify', '-Xmx1G', '-jar', '/dev/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher.jar', '-configuration', '/dev/jdt-language-server-latest/config_linux', '-data', '~/.cache/javals
p']}
  filetypes=['java']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/nvim/bin/nvim)
version: NVIM v0.9.0-dev-143+ga288b4f21
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
 Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok
ok

lang#java layer health:

ok

lang#html layer health:

ok

lang#python layer health:

ok

lang#csharp layer health:

ok

lang#javascript layer health:

ok

lang#typescript layer health:

ok

git layer health:

ok

JavaUnite layer health:

    There is no function: SpaceVim#layers#JavaUnite#health()

lsp layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:39:52] [0.000] [ Info  ] Loading SpaceVim from: /root/.SpaceVim/
[ SpaceVim ] [11:39:52] [0.087] [ Info  ] Startup with no argv, current dir is used: /mnt/d/IdeaProjects/CostManagement
[ SpaceVim ] [11:39:52] [0.087] [ Info  ] init default vim options
[ SpaceVim ] [11:39:52] [0.087] [ Info  ] options init done
[ SpaceVim ] [11:39:52] [0.094] [ Info  ] start loading global config >>>
[ SpaceVim ] [11:39:52] [0.094] [ Info  ] global_dir is: /root/.SpaceVim.d/
[ SpaceVim ] [11:39:52] [0.094] [ Info  ] find global config: /root/.SpaceVim.d/init.toml
[ SpaceVim ] [11:39:52] [0.095] [ Info  ] start to apply config [glob]
[ SpaceVim ] [11:39:52] [0.098] [ Info  ] start loading local config >>>
[ SpaceVim ] [11:39:52] [0.098] [ Info  ] Could not find project local config
[ SpaceVim ] [11:39:52] [0.175] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:39:52] [0.247] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:39:52] [0.247] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [11:39:52] [0.462] [ Info  ] finished loading SpaceVim!
[  project ] [11:39:52] [0.581] [ Info  ] Load projects cache from: /root/.cache/SpaceVim/projects.json
[  project ] [11:39:53] [1.024] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [11:39:53] [1.029] [ Info  ]         (.git/):/mnt/d/IdeaProjects/CostManagement/
[ SpaceVim ] [11:39:53] [1.045] [ Info  ] try to open SpaceVim welcome page
[  project ] [11:39:56] [4.046] [ Info  ]         (.git/):/mnt/d/IdeaProjects/CostManagement/
[ SpaceVim ] [11:40:00] [8.506] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:40:00] [8.566] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:40:00] [8.566] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [11:40:29] [37.150] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [11:40:29] [37.208] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:40:29] [37.208] [ Info  ] the func has been added to mode:paste-mode

```
</details>
```
## Screenshots
![图片](https://user-images.githubusercontent.com/13266764/198186386-bacd8da8-7975-4442-9949-3f8b1e65d10b.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<!-- please remove the issue template when request for a feature -->
