### ISSUE TITLE
Error detected while processing function <SNR>94_nerdtree_l[10]..304[18]..303[3]..<SNR>166_activateFileNode[1]..333[1]..349[3]..405[6]..406[17]..241[3]..BufEnter Autocommands for "*.ts": E117: Unknown function: TSOnBufEnte

### ISSUE THREAD

**Issue by TomYule** [wsdjeg/SpaceVim#4735]
Error detected while processing function <SNR>94_nerdtree_l[10]..304[18]..303[3]..<SNR>166_activateFileNode[1]..333[1]..349[3]..405[6]..406[17]..241[3]..BufEnter Autocommands for "*.ts":
E117: Unknown function: TSOnBufEnter
Press ENTER or type command to continue
## Expected behavior, english is required
when I open *.ts file error
## The reproduce ways from Vim starting (Required!)
when I open *.ts file error
## Output of the `:SPDebugInfo!`
```
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'OceanicNext'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['mhartington/oceanic-next', {'repo': 'mhartington/oceanic-next', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/root/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
 file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/root/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'markdown-preview.nvim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'tsconfig.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'

 src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
  java_formatter_jar='~/.SpaceVim.d/lib/google-java-format-1.15.0-all-deps.jar'
[[layers]]
  name="lang#html"
  emmet_filetyps=['html']
  emmet_leader_key='<C-e>'
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#vue"
[[layers]]
  name="git"
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.le
vel=NONE', '-noverify', '-Xmx1G', '-jar', '~/.SpaceVim.d/lib/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar', '-configuration', '~/.SpaceVim.d/config/config_linux', '-data', '~/.SpaceVim.d/javalsp/.ca
che/javalsp']}
  filetypes=['java']
[[layers]]
  name="lang#markdown"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/nvim/bin/nvim)
version: NVIM v0.9.0-dev-143+ga288b4f21
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok

lang#java layer health:

ok

lang#html layer health:

ok

lang#python layer health:

ok

lang#csharp layer health:

ok

lang#typescript layer health:

ok

lang#vue layer health:

ok

git layer health:

ok

lsp layer health:

ok

lang#markdown layer health:

ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:41:47] [0.000] [ Info  ] Loading SpaceVim from: /root/.SpaceVim/
[ SpaceVim ] [17:41:47] [0.000] [ Info  ] Loading SpaceVim from: /root/.SpaceVim/
[ SpaceVim ] [17:41:47] [0.093] [ Info  ] Startup with no argv, current dir is used: /mnt/d/IdeaProjects/secret-evaluation-cloud/secret-evaluation-cloud-client
[ SpaceVim ] [17:41:47] [0.093] [ Info  ] init default vim options
[ SpaceVim ] [17:41:47] [0.093] [ Info  ] options init done
[ SpaceVim ] [17:41:47] [0.100] [ Info  ] start loading global config >>>
[ SpaceVim ] [17:41:47] [0.100] [ Info  ] global_dir is: /root/.SpaceVim.d/
[ SpaceVim ] [17:41:47] [0.100] [ Info  ] find global config: /root/.SpaceVim.d/init.toml
[ SpaceVim ] [17:41:47] [0.112] [ Info  ] start to apply config [glob]
[ SpaceVim ] [17:41:47] [0.114] [ Info  ] start loading local config >>>
[ SpaceVim ] [17:41:47] [0.115] [ Info  ] Could not find project local config
[ SpaceVim ] [17:41:47] [0.194] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:41:47] [0.269] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [17:41:47] [0.269] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [17:41:47] [0.522] [ Info  ] finished loading SpaceVim!
[  project ] [17:41:47] [0.643] [ Info  ] Load projects cache from: /root/.cache/SpaceVim/projects.json
[  project ] [17:41:48] [1.115] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [17:41:48] [1.123] [ Info  ]         (.git/):/mnt/d/IdeaProjects/secret-evaluation-cloud/secret-evaluation-cloud-client/
[  project ] [17:41:48] [1.144] [ Info  ]         (tsconfig.json):/mnt/d/IdeaProjects/secret-evaluation-cloud/secret-evaluation-cloud-client/
[ SpaceVim ] [17:41:48] [1.147] [ Info  ] try to open SpaceVim welcome page
[  project ] [17:41:51] [4.144] [ Info  ]         (.git/):/mnt/d/IdeaProjects/secret-evaluation-cloud/secret-evaluation-cloud-client/
[  project ] [17:41:51] [4.157] [ Info  ]         (tsconfig.json):/mnt/d/IdeaProjects/secret-evaluation-cloud/secret-evaluation-cloud-client/
[ SpaceVim ] [17:44:33] [166.594] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [17:44:33] [166.645] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [17:44:33] [166.645] [ Info  ] the func has been added to mode:paste-mode

```
</details>
```
## Screenshots  
![图片](https://user-images.githubusercontent.com/13266764/198558442-f63f3c81-845d-41bd-a793-52059a649a8e.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<!-- please remove the issue template when request for a feature -->
