### ISSUE TITLE
Language - Java: javacomplete error: {} 

### ISSUE THREAD

**Issue by szczad** [wsdjeg/SpaceVim#4736]
<!-- bug reporting without issue template will be closed automatically -->

## Expected behavior, english is required

Code completion does not work with Java.
NeoVIM version: v0.7.2
Python version: v3.10.6
PyNVIM version: 0.4.3
Java version: OpenJDK - Temurin-17.0.4.1+1 (build 17.0.4.1+1)
Gradle: 7.5.1

## The reproduce ways from Vim starting (Required!)

* Create Spring Boot project
* Start vim: `nvim`
* Open any Java class file
* type:
```
import org.springframework.
```
* Get the message:
```
javacomplete error: {}
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/szczad/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  default_indentation = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_filetree_gitstatus = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/szczad/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'java_getset.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 0
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'pom.xml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  filetree_show_hidden=1
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#java"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.level=NONE', '-noverify', '-Xmx1G', '-jar', '/home/szczad/Workspace/java/eclipse-jdt/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar', '-configuration', '/home/szczad/Workspace/java/eclipse-jdt/config_linux', '-data', '/home/szczad/.cache/javalsp']}
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
autocomplete layer health:

ok

checkers layer health:

ok

format layer health:

ok

edit layer health:

ok

ui layer health:

ok

core layer health:

ok

core#banner layer health:

ok

core#statusline layer health:

ok

core#tabline layer health:

ok

shell layer health:

ok

colorscheme layer health:

ok

git layer health:

ok

VersionControl layer health:

ok

lang#dockerfile layer health:

ok

lang#go layer health:

ok

lang#java layer health:

ok


### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [16:53:27] [0.000] [ Info  ] Loading SpaceVim from: /home/szczad/.SpaceVim/
[ SpaceVim ] [16:53:27] [0.095] [ Info  ] Startup with no argv, current dir is used: ~/Workspace/Java/my_project
[ SpaceVim ] [16:53:27] [0.095] [ Info  ] init default vim options
[ SpaceVim ] [16:53:27] [0.096] [ Info  ] options init done
[ SpaceVim ] [16:53:27] [0.100] [ Info  ] start loading global config >>>
[ SpaceVim ] [16:53:27] [0.100] [ Info  ] global_dir is: /home/szczad/.SpaceVim.d/
[ SpaceVim ] [16:53:27] [0.100] [ Info  ] find global config: /home/szczad/.SpaceVim.d/init.toml
[ SpaceVim ] [16:53:27] [0.100] [ Info  ] start to apply config [glob]
[  project ] [16:53:27] [0.101] [ Info  ] Load projects cache from: /home/szczad/.cache/SpaceVim/projects.json
[  project ] [16:53:27] [0.101] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [16:53:27] [0.101] [ Info  ]         (.git/):/home/szczad/Workspace/Java/my_project/
[ SpaceVim ] [16:53:27] [0.103] [ Info  ] start loading local config >>>
[ SpaceVim ] [16:53:27] [0.103] [ Info  ] Could not find project local config
[ SpaceVim ] [16:53:27] [0.104] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [16:53:27] [0.122] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:53:27] [0.138] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:53:27] [0.138] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [16:53:27] [0.177] [ Info  ] finished loading SpaceVim!
[  project ] [16:53:27] [0.217] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [16:53:27] [0.218] [ Info  ]         (.git/):/home/szczad/Workspace/Java/my_project/
[ SpaceVim ] [16:53:27] [0.221] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [16:53:27] [0.260] [ Info  ] run root changed callback on VimEnter!
[  project ] [16:53:29] [2.816] [ Info  ]         (.git/):/home/szczad/Workspace/Java/my_project/
[ autosave ] [16:56:06] [159.868] [ Info  ] backup path is:/home/szczad/.cache/SpaceVim/backup/_home_szczad_Workspace_Java_my_project-service_app_src_main_java_com_szczad_myproject_HelloWorldController_java.backup
[ SpaceVim ] [16:56:09] [162.624] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:56:09] [162.630] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:56:09] [162.630] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [16:56:09] [162.638] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [16:56:09] [162.638] [ Info  ] statusline build-in section hunks has been changed!
[ SpaceVim ] [16:56:15] [168.142] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [16:56:15] [168.157] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [16:56:15] [168.157] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [16:56:15] [168.165] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [16:56:15] [168.165] [ Info  ] statusline build-in section hunks has been changed!

```
</details>

<details><summary>Messages</summary>

```
NERDTree: CWD is now: /home/szczad/Workspace/Java/my_project                                                                                                                                                                                                                                                                                                                                                               
[ SpaceVim ] [17:12:11] [4.844] [ Warn  ]  [ plug manager ] All of the plugins are already installed.                                                                                                                                                                                                                                                                                                                                    
Unknown tag kind encountered: "<f6>". Your ctags and Tagbar configurations are out of sync! Please read ':help tagbar-extend'.                                                                                                                                                                                                                                                                                                           
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
1 change; before #30  50 seconds ago                                                                                                                                                                                                                                                                                                                                                                                                     
1 change; after #30  52 seconds ago                                                                                                                                                                                                                                                                                                                                                                                                      
Already at newest change                                                                                                                                                                                                                                                                                                                                                                                                                 
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
message: packages still empty, try later. indexing...                                                                                                                                                                                                                                                                                                                                                                                    
javacomplete error: []                                                                                                                                                                                                                                                                                                                                                                                                                   
message: packages still empty, try later. indexing...                                                                                                                                                                                                                                                                                                                                                                                    
javacomplete error: []                                                                                                                                                                                                                                                                                                                                                                                                                   
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
javacomplete error: {}                                                                                                                                                                                                                                                                                                                                                                                                                   
1 change; before #33  33 seconds ago                                                                                                                                                                                                                                                                                                                                                                                                     
javacomplete error: {}  
```

</details>

## Sample repository location

Sample [Java SpringBoot Bare Repository](https://github.com/szczad/java-springboot-bare-repository.git)

## Screenshots

![Zrzut ekranu z 2022-10-31 15-35-36](https://user-images.githubusercontent.com/2914011/199034010-efa1d44e-2ea3-4c14-9639-28bc8f97e0ae.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

<!-- please remove the issue template when request for a feature -->
