### ISSUE TITLE
Neosnippet snippet expansion is not working

### ISSUE THREAD

**Issue by RegreTTO** [wsdjeg/SpaceVim#4753]
## Expected behavior, english is required
When I press `Enter` on deoplete suggestion I get a snippet expanded

## The reproduce ways from Vim starting (Required!)
1. Type smth that have snippet ("main" in my case)
2. Print `Enter`
3. Get `main<Plug>(neosnippet_expand) `

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 0
  automatic_update = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['Shougo/deoppet.nvim', {'do': ':UpdateRemotePlugins', 'repo': 'Shougo/deoppet.nvim', 'overwrite': 1}], ['davidhalter/jedi-vim', {'repo': 'davidhalter/jedi-vim', 'overwrite': 1}], ['yaegassy/coc-ansible', {'do': 'yarn install --frozen-lockfile', 'repo': 'yaegassy/coc-ansible', 'overwrite': 1}], ['stephpy/vim-yaml', {'repo': 'stephpy/vim-yaml', 'overwrite': 1}], ['pearofducks/ansible-vim', {'repo': 'pearofducks/ansible-vim', 'overwrite': 1}], ['sheerun/vim-polyglot', {'repo': 'sheerun/vim-polyglot', 'overwrite': 1}], ['ryanoasis/vim-devicons', {'repo': 'ryanoasis/vim-devicons', 'overwrite': 1}], ['mgedmin/python-imports.vim', {'repo': 'mgedmin/python-imports.vim', 'overwrite': 1}], ['machakann/vim-highlightedyank', {'repo': 'machakann/vim-highlightedyank', 'overwrite': 1}], ['vim-scripts/Auto-Pairs', {'repo': 'vim-scripts/Auto-Pairs', 'overwrite': 1}], ['Valloric/YouCompleteMe', {'name': 'Valloric/YouCompleteMe', 'merge': 0, 'overwrite': 1}]]
  data_dir = '/home/regretto/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 0
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/regretto/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-zsh'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='smart'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
  lint_on_the_fly=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="gtags"
  gtagslabel='ctags'
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#python"
  python_file_head=['#!/usr/bin/env python', '', '']
  format_on_save=1
  enabled_linters=['pylint']
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="debug"
[[layers]]
  name="lsp"
  enabled_clients=['vimls', 'pylsp', 'clangd']
[[layers]]
  name="lang#c"
[[layers]]
  name="c-lsp"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#sh"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.8.1
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `gtags`:ok
  - `lang#go`:ok
  - `lang#python`:ok
  - `shell`:ok
  - `debug`:ok
  - `lsp`:ok
  - `lang#c`:ok
  - `c-lsp`: can not find function: SpaceVim#layers#c-lsp#health()
  - `git`:ok
  - `VersionControl`:ok
  - `lang#sh`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/regretto/.SpaceVim/
[ SpaceVim ] [00:00:00:080] [ Info  ] Startup with argv: ['nvim', '-c', ':SPDebugInfo!']
[ SpaceVim ] [00:00:00:080] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:081] [ Info  ] options init done
[ SpaceVim ] [00:00:00:086] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:086] [ Info  ] global_dir is: /home/regretto/.SpaceVim.d/
[ SpaceVim ] [00:00:00:086] [ Info  ] find global config: /home/regretto/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:086] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:089] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:112] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:133] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:133] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:157] [ Info  ] Load projects cache from: /home/regretto/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:209] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:289] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:00:296] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:304] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:304] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:00:317] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:00:00:317] [ Info  ] statusline build-in section hunks has been changed!

```
</details>

## Screenshots
![изображение](https://user-images.githubusercontent.com/39791198/202232155-b074a95e-8532-4451-8d94-c5fbd33e25e0.png)
