### ISSUE TITLE
rust layer still wants to use racer even if lsp is enabled and configured

### ISSUE THREAD

**Issue by rck** [wsdjeg/SpaceVim#4762]
this is spacevim as of today (GIT: 3ac0fe27ccc0bebbcdc419de7654e06a41b7c803)

this is basically a followup of https://github.com/SpaceVim/SpaceVim/issues/4303

## Expected behavior, english is required

it should use the configured lsp program and not `racer`

## The reproduce ways from Vim starting (Required!)

open a rust file and run a completion. If I remove the razer binary from `PATH` nvim complains about not finding the `razer` binary. also taken from the other thread, when I run `map <Plug>(rust-doc)` this shows `n <Plug>(rust-doc) *@:call racer#ShowDocumentation(0)<CR>` as reported by others in the closed issue.

FWIW there is no difference when I set `rust = ["rls"]`

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 0
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['rck/lucius-vim', {'repo': 'rck/lucius-vim', 'merged': 0, 'overwrite': 1}], ['vim-scripts/spec.vim', {'repo':
 'vim-scripts/spec.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/rkammerer/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 0
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/rkammerer/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dockerfile'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'Cargo.toml', '.clang', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescr
ibe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks',
'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 1
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
  lint_on_the_fly=0
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="denite"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="VersionControl"
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#c"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rust-analyzer']}
  filetypes=['rust']
[[layers]]
  name="lang#rust"
  rustfmt_cmd='rustfmt'
  format_on_save=1
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#dockerfile"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `denite`:ok
  - `shell`:ok
  - `VersionControl`:ok
  - `git`:ok
  - `lang#sh`:ok
  - `lang#c`:ok
  - `lsp`:ok
  - `lang#rust`:ok
  - `lang#go`:ok
  - `lang#dockerfile`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/rkammerer/.SpaceVim/
[ SpaceVim ] [00:00:00:059] [ Info  ] Startup with argv: ['nvim', 'src/bin/drbd-reactorctl.rs']
[ SpaceVim ] [00:00:00:061] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:062] [ Info  ] options init done
[ SpaceVim ] [00:00:00:089] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:089] [ Info  ] global_dir is: /home/rkammerer/.SpaceVim.d/
[ SpaceVim ] [00:00:00:089] [ Info  ] find global config: /home/rkammerer/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:105] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:113] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:113] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:115] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:151] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:172] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:172] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:207] [ Info  ] Load projects cache from: /home/rkammerer/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:261] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:438] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [00:00:00:439] [ Info  ]         (.git/):/home/rkammerer/src/linbit/public/drbd-reactor/
[  project ] [00:00:00:439] [ Info  ]         (Cargo.toml):/home/rkammerer/src/linbit/public/drbd-reactor/
[ SpaceVim ] [00:00:00:446] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:446] [ Info  ] switch to project:[drbd-reactor]
[  project ] [00:00:00:446] [ Info  ]        rootdir is:/home/rkammerer/src/linbit/public/drbd-reactor/
[ SpaceVim ] [00:04:55:060] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:04:55:077] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:04:55:077] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:04:55:093] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:04:55:093] [ Info  ] statusline build-in section hunks has been changed!
[ SpaceVim ] [00:14:01:088] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:14:01:104] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:14:01:105] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:14:01:122] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:14:01:122] [ Info  ] statusline build-in section hunks has been changed!
```
## Screenshots
none
