### ISSUE TITLE
Zooming using Transient Mode immediately causes a crash on Windows 10/11.

### ISSUE THREAD

**Issue by AlOwain** [wsdjeg/SpaceVim#4764]
## Expected behavior

After entering Transient Mode (by using "SPC" + "z" + ".") then zooming in (using "+") you would be able to zoom in or out.

## The reproduce ways from Vim starting (Required!)

1) Enter Transient Mode ("SPC" + "z" + ".")

2) Zoom in ("+")

**Note**: The crash is less likely to happen when zooming out; and when zooming in using the numpad.

**Note**: The crash was reproducible on a new download of SpaceVim on a Windows 11 system (this system is a Windows 10 system), unfortunately I do not have its SPDebugInfo with me.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\AlOwain\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\AlOwain\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(D:\BrowserDownloads\Nvim\bin\nvim.exe)
version: NVIM v0.8.1
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: C:/Users/AlOwain/.SpaceVim/
[ SpaceVim ] [00:00:00:016] [ Info  ] Startup with no argv, current dir is used: D:\BrowserDownloads\Nvim\bin
[ SpaceVim ] [00:00:00:016] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:017] [ Info  ] options init done
[ SpaceVim ] [00:00:00:030] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:030] [ Info  ] global_dir is: C:/Users/AlOwain/.SpaceVim.d/
[ SpaceVim ] [00:00:00:031] [ Info  ] find global config: C:/Users/AlOwain/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:031] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:033] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:033] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:035] [ Info  ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [00:00:00:093] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:139] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:139] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:00:203] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:00:311] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:00:377] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:378] [ Info  ] Load projects cache from: C:/Users/AlOwain/.cache/SpaceVim/projects.json
[  project ] [00:00:00:379] [ Info  ] switch to project:[bin]
[  project ] [00:00:00:379] [ Info  ]        rootdir is:D:/BrowserDownloads/Nvim/bin/
[ SpaceVim ] [00:00:06:721] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:06:745] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:06:745] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

Enter Transient State:
![image](https://user-images.githubusercontent.com/79036261/207679437-a18906fe-bceb-4237-bcc6-96fb4bd683fa.png)

Stuck after attempting to zoom in:
![image](https://user-images.githubusercontent.com/79036261/207679869-66fa3745-c410-4103-bb1d-65b2a365681a.png)

Process fails:
![image](https://user-images.githubusercontent.com/79036261/207652687-7073c494-8549-4821-898b-ac82e787be20.png)
