### ISSUE TITLE
Deoplete / Nvim Issue

### ISSUE THREAD

**Issue by C4E5G3** [wsdjeg/SpaceVim#4768]
```
[deoplete] jedi module is not found.  You need to install it.  Use :messages / see above fo
r error details
```

## Expected behavior
Not to have an error

## The reproduce ways from Vim starting (Required!)

- $ nvim
- `0` to open file
- `j` to line in file
- `b` to word
- `c` to change a word

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/marcus/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/marcus/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#python"
  python_interpreter='D:\scoop\shims\python.exe'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.8.1
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#python`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/marcus/.SpaceVim/
[ SpaceVim ] [00:00:00:144] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:145] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:145] [ Info  ] options init done
[ SpaceVim ] [00:00:00:166] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:167] [ Info  ] global_dir is: /home/marcus/.SpaceVim.d/
[ SpaceVim ] [00:00:00:167] [ Info  ] find global config: /home/marcus/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:167] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:171] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:174] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:249] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:315] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:316] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:00:430] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:00:618] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:00:800] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:809] [ Info  ] Load projects cache from: /home/marcus/.cache/SpaceVim/projects.json
[  project ] [00:00:00:810] [ Info  ] switch to project:[marcus]
[  project ] [00:00:00:810] [ Info  ]        rootdir is:/home/marcus/
[  project ] [00:00:03:523] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [00:00:03:523] [ Info  ] ignore $HOME directory:/home/marcus/
[ autosave ] [00:05:00:317] [ Info  ] backup path is:/home/marcus/.cache/SpaceVim/backup/_home_marcus_Dev_Projects_ZeroHero_Blackjack_Main_Package_chip_class_py.backup
[ autosave ] [00:05:41:528] [ Info  ] backup path is:/home/marcus/.cache/SpaceVim/backup/_home_marcus_Dev_Projects_ZeroHero_Blackjack_Main_Package_chip_class_py.backup
[ SpaceVim ] [00:05:47:080] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:05:47:101] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:05:47:101] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

[log_py3_script.txt](https://github.com/SpaceVim/SpaceVim/files/10295514/log_py3_script.txt)
[log_py3_rplugin.txt](https://github.com/SpaceVim/SpaceVim/files/10295515/log_py3_rplugin.txt)
