### ISSUE TITLE
Key binding behavior varies depending on whether mappings guide is activated or not.

### ISSUE THREAD

**Issue by StaySharp0** [wsdjeg/SpaceVim#4769]
## Expected behavior, english is required
The same key binding behavior must be ensured whether or not the mappings guide is activated .
When the mappings guide is inactivated, it works as expected, but when activated, part of the keybinding text is entered.

## The reproduce ways from Vim starting (Required!)
```
$ vim  ~/.SpaceVim.d/init.toml
...
[options]
    bootstrap_before = "StaySharp0#before" # add Bootstrap Functions
...
$ cat <<EOT > ~/.SpaceVim.d/autoload/StaySharp0.vim
" ~/.SpaceVim.d/autoload/StaySharp0.vim
function! StaySharp0#before() abort
  call SpaceVim#custom#SPCGroupName(['S'], '+StaySharp0 Custom')
  call SpaceVim#custom#SPC('noremap', ['S','a'], 'ggvG$', 'all selection', 0)
  call SpaceVim#custom#SPC('nmap', ['S','y'], '<Space>Sa<leader>y', 'all copy', 0)
  call SpaceVim#custom#SPC('nmap', ['S','d'], '<Space>Sy<Space>Sad', 'all cut', 0)
endfunction
EOT
```

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'StaySharp0#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/staysharp0/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/staysharp0/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'coveragepy.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="lang#python"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.basic)
version: 801
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `fzf`:ok
  - `lang#python`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [15:39:23] [   0.000] [  Info ] Loading SpaceVim from: /home/staysharp0/.SpaceVim/
[ SpaceVim ] [15:39:23] [   0.050] [  Info ] Startup with no argv, current dir is used: ~/.SpaceVim.d/autoload
[ SpaceVim ] [15:39:23] [   0.056] [  Info ] start loading global config >>>
[ SpaceVim ] [15:39:23] [   0.056] [  Info ] global_dir is: /home/staysharp0/.SpaceVim.d/
[ SpaceVim ] [15:39:23] [   0.056] [  Info ] find global config: /home/staysharp0/.SpaceVim.d/init.toml
[ SpaceVim ] [15:39:23] [   0.056] [  Info ] start to apply config [glob]
[ SpaceVim ] [15:39:23] [   0.057] [  Info ] start loading local config >>>
[ SpaceVim ] [15:39:23] [   0.058] [  Info ] Could not find project local config
[ SpaceVim ] [15:39:23] [   0.119] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:39:23] [   0.177] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:39:23] [   0.178] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [15:39:23] [   0.362] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [15:39:23] [   0.717] [  Info ] try to open SpaceVim welcome page
[ SpaceVim ] [15:39:23] [   0.749] [  Info ] run root changed callback on VimEnter!
[   rooter ] [15:39:23] [   0.749] [  Info ] Load projects cache from: /home/staysharp0/.cache/SpaceVim/projects.json
[   rooter ] [15:39:24] [   1.538] [  Info ] Start to find root for: /home/staysharp0/.SpaceVim.d/autoload/StaySharp0.vim
[ SpaceVim ] [15:39:26] [   3.480] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [15:39:26] [   3.528] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [15:39:26] [   3.528] [  Info ] the func has been added to mode:paste-mode
```
</details>

## Screenshots
![image](https://user-images.githubusercontent.com/7071372/209424796-a014da25-c935-4da6-b136-2936c851fc2f.png)
![image](https://user-images.githubusercontent.com/7071372/209424830-62ff57db-5618-42db-be40-597ae277e3b9.png)
![image](https://user-images.githubusercontent.com/7071372/209424805-c6b3468e-9594-4cea-b966-c27b998b742a.png)
