### ISSUE TITLE
Setting colorscheme in init.toml but didn't change

### ISSUE THREAD

**Issue by JackyPro** [wsdjeg/SpaceVim#4774]
## Setting colorscheme in init.toml but didn't change
i'm new in both vim and SpaceVim.
the colorscheme is work when i use the command mode in vim
```
:colorscheme "blue"
```
but the colorscheme didn't work in SpaceVim when i setted the init.toml.
It seemed that it is always in the default mode.
what's the problem?
## The reproduce ways from Vim starting
Here's my ini.toml file.
```
This is a basic configuration example for SpaceVim

# All SpaceVim options are below [options] snippet
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "molokai" #"one" #"gruvbox"
    colorscheme_bg = "light"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow" #"nil"
    statusline_iseparato = "arrow" #"bar"
    buffer_index_type = 4
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart" #"cycle"

[[layers]]
    name = "shell"
    default_position = "bottom" #top"
    default_height = 30

[[layers]]
    name = "colorscheme"
    random_theme = true
    frequency = "daily"

# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
    repo = "liuchengxu/space-vim-dark" #"https://github.com/liuchengxu/space-vim-dark.git"  #"liuchengxu/space-vim-dark" #"lilydjwg/colorizer"
    merged = 01

[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = 0

[[custom_plugins]]
    repo = "junegunn/vader.vim"
    merged = 0

[[custom_plugins]]
    repo = "mhartington/oceanic-next"
    merged = 0

```
## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  able_os_fileformat_icon = 0
  ader_guide_position = 'botright'
  rsion = '2.1.0-dev'
  rce_global_config = 0
  artcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  fault_indent = 2
  able_key_frequency = 0
  able_javacomplete2_py = 0
  cape_key_binding = 'jk'
  able_powerline_fonts = 1
  oject_non_root = ''
  date_retry_cnt = 3
  able_language_specific_leader = 1
  oject_auto_root = 1
  rning_symbol = '⚠'
  able_statusline_bfpath = 0
  lorscheme = 'gruvbox'
  pand_tab = 1
  atusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  able_guicolors = 0
  stom_plugins = []
  ader_guide_submode_mappings = {'<C-C>': 'win_close'}
  ffer_index_type = 4
  ddenfileinfo = 1
  ojects_cache_num = 20
  tcommit_pr_icon = ''
  ugin_manager = 'neobundle'
  ror_symbol = '✖'
  do_labels = ['fixme', 'question', 'todo', 'idea']
  ndows_smartclose = 'q'
  ndows_leader = 's'
  ldignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  able_cursorcolumn = 0
  lorscheme_bg = 'dark'
  able_statusline_tag = 1
  able_neocomplcache = 0
  ader_guide_sort_horizontal = 0
  able_vimfiler_welcome = 1
  x_column = 120
  able_debug = 0
  mmandline_prompt = '>'
  le_searching_tools = []
  oject_rooter_outermost = 1
  to_disable_touchpad = 1
  m_help_language = 'en'
  nt_on_save = 1
  debar_direction = ''
  tocomplete_method = 'neocomplcache'
  ep_server_alive = 1
  tcommit_issue_icon = ''
  ugin_manager_processes = 16
  able_ycm = 0
  de_runner_focus = 0
  altime_leader_guide = 1
  lorscheme_default = 'desert'
  atusline_separator = 'nil'
  letree_direction = 'right'
  able_tabline_ft_icon = 0
  fault_custom_leader = '<Space>'
  ap_line = 0
  sabled_plugins = []
  ifont = ''
  ader_guide_max_size = 0
  atusline_iseparator = 'nil'
  nt_on_the_fly = 0
  fo_symbol = 'ⓘ'
  ader_guide_flatten = 1
  debar_width = 30
  able_googlesuggest = 0
  nguage = ''
  tocomplete_parens = 1
  ugin_bundle_dir = '/home/users1/jacky616/.cache/vimfiles/'
  atusline_right = ['fileformat', 'cursorpos', 'percentage']
  ader_guide_run_map_on_popup = 1
  do_prefix = '@'
  lativenumber = 1
  atusline_unicode = 1
  ader_guide_default_group_name = ''
  mcompatible = 0
  artcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  me_files_number = 6
  rminal_cursor_shape = 2
  ippet_engine = 'neosnippet'
  oject_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  arch_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  able_projects_cache = 1
  nt_engine = 'neomake'
  thub_username = ''
  ader_guide_hspace = 5
  eckinstall = 1
  ndows_index_type = 3
  letype_icons = {}
  ugin_name = 'vim-grepper'
  able_cursorline = 1
  stom_color_palette = []
  sts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  bug_level = 1
  able_bepo_layout = 0
  able_statusline_mode = 0
  lemanager = 'nerdtree'
  c_root = 'E:\sources\'
  ader_guide_vertical = 0
  ta_dir = '/home/users1/jacky616/.cache/'
  ndisk_encoding = 'cp936'
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vim(vim)
version: 704
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, Please install vim-gtk, or build from sources.
Checking +python:
      SUCCEED!
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [11:11:25] [   0.000] [  Info ] Loading SpaceVim from: /home/users1/jacky616/.SpaceVim/
[ SpaceVim ] [11:11:25] [   0.021] [  Info ] Startup with no argv, current dir is used: ~/
[ SpaceVim ] [11:11:25] [   0.043] [  Info ] start loading global config >>>
[ SpaceVim ] [11:11:25] [   0.043] [  Info ] global_dir is: /home/users1/jacky616/.SpaceVim.d/
[ SpaceVim ] [11:11:25] [   0.043] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [11:11:25] [   0.091] [  Info ] smart tab in autocomplete layer need patch 7.4.774
[ SpaceVim ] [11:11:25] [   0.092] [  Info ] the func has been added to mode:syntax-checking
[ autosave ] [11:11:25] [   0.107] [  Warn ] failed to setup timer, needs `+timers` feature!
[ autosave ] [11:11:25] [   0.107] [  Warn ] failed to setup timer, needs `+timers` feature!
[ SpaceVim ] [11:11:25] [   0.119] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:11:25] [   0.120] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [11:11:25] [   0.184] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [11:11:25] [   0.333] [  Info ] try to open SpaceVim welcome page
[ SpaceVim ] [11:11:26] [   0.559] [  Info ] run root changed callback on VimEnter!
[   rooter ] [11:11:26] [   0.561] [  Info ] Load projects cache from: /home/users1/jacky616/.cache/SpaceVim/projects.json
[   rooter ] [11:11:29] [   3.580] [  Info ] Start to find root for: /home/users1/jacky616/.SpaceVim/.SpaceVim.d/init.toml
[   rooter ] [11:11:29] [   3.582] [  Info ]         (.git/):/home/users1/jacky616/.SpaceVim/
[   rooter ] [11:11:29] [   3.588] [  Info ]         (.SpaceVim.d/):/home/users1/jacky616/.SpaceVim/
[   rooter ] [11:11:29] [   3.588] [  Info ] buffer name: /home/users1/jacky616/.SpaceVim/.SpaceVim.d/init.toml
[   rooter ] [11:11:29] [   3.588] [  Info ] change to root: /home/users1/jacky616/.SpaceVim/
[ SpaceVim ] [11:11:51] [  26.021] [  Info ] smart tab in autocomplete layer need patch 7.4.774
[ SpaceVim ] [11:11:51] [  26.021] [  Warn ] show_cursor_error in checkers layer needs timers feature
[ SpaceVim ] [11:11:51] [  26.022] [  Info ] the func has been added to mode:syntax-checking
[ autosave ] [11:11:51] [  26.024] [  Warn ] failed to setup timer, needs `+timers` feature!
[ SpaceVim ] [11:11:51] [  26.031] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:11:51] [  26.031] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [11:12:47] [  82.082] [  Info ] smart tab in autocomplete layer need patch 7.4.774
[ SpaceVim ] [11:12:47] [  82.082] [  Warn ] show_cursor_error in checkers layer needs timers feature
[ SpaceVim ] [11:12:47] [  82.083] [  Info ] the func has been added to mode:syntax-checking
[ autosave ] [11:12:47] [  82.085] [  Warn ] failed to setup timer, needs `+timers` feature!
[ SpaceVim ] [11:12:47] [  82.092] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [11:12:47] [  82.093] [  Info ] the func has been added to mode:paste-mode
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
