### ISSUE TITLE
Error while loading markdown files in SpaceVim

### ISSUE THREAD

**Issue by linusjf** [wsdjeg/SpaceVim#4777]
## Expected behavior, english is required
Loading of markdown files must work as expected.

## The reproduce ways from Vim starting (Required!)
vim <markdownfile>

Instead we see the following:
```



Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:22: Error executing lua: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:23: Vim(if):E121: Undefined variable: g:markdown_default_mappings
stack traceback:
	[C]: in function 'nvim_cmd'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:23: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:22>
	[C]: in function 'nvim_buf_call'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:22: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:22: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:11>
Error detected while processing BufNewFile Autocommands for "*.{md,mdown,mkd,mkdn,markdown,mdwn,mdx}"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[17]..script /data/data/com.termux/files/home/.SpaceVim/bundle/vim-markdown/ftplugin/markdown.vim:
line    3:
E121: Undefined variable: g:markdown_default_mappings
Error detected while processing BufNewFile Autocommands for "*.{md,mdown,mkd,mkdn,markdown,mdwn,mdx}"..FileType Autocommands for "*"..function <SNR>2_LoadIndent[14]..script /data/data/com.termux/files/home/.SpaceVim/bundle/vim-markdown/indent/markdown.vim:
line   11:
E121: Undefined variable: g:vim_markdown_auto_insert_bullets

```

## Output of the `:SPDebugInfo!`

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builder@24238d0703f7

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builder@24238d0703f7

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['MaxMEllon/vim-jsx-pretty', {'name': 'MaxMEllon/vim-jsx-pretty', 'merged': 0, 'overwrite': 1}], ['vim-scripts/dbext.vim', {'repo': 'vim-scripts/dbext.vim', 'merged': 0, 'overwrite': 1}], ['lilydjwg/colorizer', {'repo': 'lilydjwg/colorizer', 'merged': 0, 'overwrite': 1}], ['junegunn/vim-github-dashboard', {'if': 0, 'repo': 'junegunn/vim-github-dashboard', 'merged': 0, 'overwrite': 1}], ['github/copilot.vim', {'repo': 'github/copilot.vim', 'merged': 0, 'overwrite': 1}], ['nono/jquery.vim', {'repo': 'nono/jquery.vim', 'merged': 0, 'overwrite': 1}], ['tibabit/vim-templates', {'repo': 'tibabit/vim-templates', 'merged': 0, 'overwrite': 1}], ['editorconfig/editorconfig-vim', {'if': 1, 'repo': 'editorconfig/editorconfig-vim', 'merged': 0, 'overwrite': 1}], ['tpope/vim-surround', {'repo': 'tpope/vim-surround', 'merged': 0, 'overwrite': 1}], ['scrooloose/nerdtree', {'loadconf': 1, 'repo': 'scrooloose/nerdtree', 'merged': 0, 'hook_source': 'call SpaceVim#util#loadConfig(''plugins/nerdtree.vim'')', 'overwrite': 1}], ['scrooloose/syntastic', {'repo': 'scrooloose/syntastic', 'merged': 0, 'overwrite': 1}], ['pangloss/vim-javascript', {'repo': 'pangloss/vim-javascript', 'merged': 0, 'overwrite': 1}], ['shougo/neocomplete.vim', {'repo': 'shougo/neocomplete.vim', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/data/data/com.termux/files/home/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_ale = 1
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_neomake = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 1
  max_column = 120
  plugin_bundle_dir = '/data/data/com.termux/files/home/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-graphql'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'build.gradle', 'package.json', '.clang', '.Rprofile', 'Cargo.toml', 'pom.xml', 'build.gradle', 'package.json', '.clang', '.Rprofile', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'bar'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_delay=200
  auto-completion-return-key-behavior='complete'
  auto_completion_tab_key_behavior='smart'
  auto_completion_complete_with_key_sequence='nil'
  auto_completion_complete_with_key_sequence_delay=0.1
[[layers]]
  name="checkers"
  enable_ale=1
  lint_on_the_fly=1
  enable_neomake=0
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_sidebar=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#jsonnet"
[[layers]]
  name="lang#python"
  python_file_head=[]
  format_on_save=1
  enable_typeinfo=1
  enabled_linters=['python']
[[layers]]
  name="lang#javascript"
  auto_fix=1
  enable_flow_syntax=1
[[layers]]
  name="lang#perl"
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#c"
  clang_executable='/data/data/com.termux/files/usr/bin/clang'
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#r"
  repl_command='R --no-save'
[[layers]]
  name="git"
[[layers]]
  name="github"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="sudo"
[[layers]]
  name="VersionControl"
[[layers]]
  name="ssh"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#csharp"
  highlight_types=0
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#rust"
  format_on_save=1
  recommended_style=1
[[layers]]
  name="lang#julia"
[[layers]]
  name="lang#sql"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lang#xquery"
[[layers]]
  name="lang#groovy"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#d"
[[layers]]
  name="lang#graphql"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/data/data/com.termux/files/usr/bin/nvim)
version: NVIM v0.8.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/data/data/com.termux/files/usr/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#java`:ok
  - `lang#php`:ok
  - `lang#html`:ok
  - `lang#sh`:ok
  - `lang#jsonnet`:ok
  - `lang#python`:ok
  - `lang#javascript`:ok
  - `lang#perl`:ok
  - `lang#ruby`:ok
  - `lang#c`:ok
  - `lang#r`:ok
  - `git`:ok
  - `github`:ok
  - `lang#latex`:ok
  - `lang#markdown`:ok
  - `sudo`:ok
  - `VersionControl`:ok
  - `ssh`:ok
  - `lang#assembly`:ok
  - `lang#csharp`:ok
  - `lang#toml`:ok
  - `lang#vim`:ok
  - `lang#rust`:ok
  - `lang#julia`:ok
  - `lang#sql`:ok
  - `lang#xml`:ok
  - `lang#xquery`:ok
  - `lang#groovy`:ok
  - `lang#json`:ok
  - `lang#d`:ok
  - `lang#graphql`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /data/data/com.termux/files/home/.SpaceVim/
[ SpaceVim ] [00:00:00:000] [ Info  ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/data/data/com.termux/files/usr/bin/python
[ SpaceVim ] [00:00:00:164] [ Info  ] Startup with argv: ['nvim', 'test']
[ SpaceVim ] [00:00:00:164] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:165] [ Info  ] options init done
[ SpaceVim ] [00:00:00:177] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:177] [ Info  ] global_dir is: /data/data/com.termux/files/home/.SpaceVim.d/
[ SpaceVim ] [00:00:00:178] [ Info  ] find global config: /data/data/com.termux/files/home/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:178] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:194] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:194] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:238] [ Warn  ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [00:00:00:238] [ Warn  ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [00:00:00:241] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:280] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:280] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:328] [ Info  ] Load projects cache from: /data/data/com.termux/files/home/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:466] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:656] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [00:00:00:657] [ Info  ] ignore $HOME directory:/data/data/com.termux/files/home/
[ SpaceVim ] [00:00:00:694] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:694] [ Info  ] switch to project:[CIAY]
[  project ] [00:00:00:694] [ Info  ]        rootdir is:/data/data/com.termux/files/home/CIAY/
[ SpaceVim ] [00:00:11:013] [ Warn  ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [00:00:11:013] [ Warn  ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [00:00:11:019] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:11:068] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:11:069] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:11:107] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:00:11:107] [ Info  ] statusline build-in section hunks has been changed!
[ SpaceVim ] [00:01:03:863] [ Warn  ] enable_neomake and enable_ale is duplecated
[ SpaceVim ] [00:01:03:863] [ Warn  ] please read :h spacevim-options-lint_engine for more info!
[ SpaceVim ] [00:01:03:871] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:01:03:922] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:01:03:922] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:01:03:977] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:01:03:977] [ Info  ] statusline build-in section hunks has been changed!

```
</details>

----
Contents of myspacevim.vim:
```
function! myspacevim#before() abort
  au BufRead,BufNewFile *.R setlocal textwidth=80
  au BufRead,BufNewFile *.r setlocal textwidth=80
  au BufRead,BufNewFile *.jl setlocal textwidth=80
  au BufRead,BufNewFile jquery.*.js set ft=javascript syntax=jquery
let g:neomake_enabled_c_makers = ['clang']
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['prettier', 'eslint'],
\   'r': ['styler']
\}
" Set this variable to 1 to fix files when you save them.
let g:ale_fix_on_save = 0
" Enable completion where available.
" This setting must be set before ALE is loaded.
" You should not turn this setting on if you wish to use ALE as a completion
" source for other completion plugins, like Deoplete.
let g:ale_completion_enabled = 1
nnoremap jk <Esc>
" normal mode mapping
nnoremap <localleader>jf :JuliaFormatterFormat<CR>
" visual mode mapping
vnoremap <localleader>jf :JuliaFormatterFormat<CR>
let g:JuliaFormatter_options = {
      \ 'indent'                    : 2,
      \ 'margin'                    : 80,
      \ 'always_for_in'             : v:true,
      \ 'whitespace_typedefs'       : v:false,
      \ 'whitespace_ops_in_indices' : v:true,
      \ 'remove_extra_newlines'     : v:true,
      \ 'always_use_return'         : v:true,
      \ 'whitespace_in_kwargs'      : v:true,
      \ 'annotate_untyped_fields_with_any' : v:true,
      \ 'format_docstrings'         : v:true
      \ }
"other configs
let g:github_dashboard = { 'username': 'fernal73', 'password': $GITHUB_TOKEN }
let g:gista#client#default_username = 'monkeyxite'
let g:tmpl_auto_initialize = 1 
let g:tmpl_search_paths = ['~/templates']
let g:tmpl_author_email = 'linusfernandes at gmail dot com'
let g:tmpl_author_name = 'Linus Fernandes'
let g:tmpl_project = 'Github Learning Repos'
let g:tmpl_company = 'Linus Fernandes'
let g:tmpl_copyright = 'Copyright (c) g:tmpl_company'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_auto_jump = 1
endfunction

function! myspacevim#after() abort
iunmap jk
let g:neomake_javascript_eslint_maker =  {
        \ 'exe': 'npx',
        \ 'args': ['--quiet', 'eslint', '--format=compact'],
        \ 'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
        \   '%W%f: line %l\, col %c\, Warning - %m,%-G,%-G%*\d problems%#',
        \ 'cwd': '%:p:h',
        \ 'output_stream': 'stdout',
        \ }

  let g:neomake_javascript_jsx_enabled_makers = ['eslint']

  let g:neoformat_enabled_javascript = ['npxprettier']
endfunction



```

## Screenshots

None
