### ISSUE TITLE
No error detected by linters in layer `lang#python`

### ISSUE THREAD

**Issue by fpom** [wsdjeg/SpaceVim#4785]
## Expected behavior, english is required

I have installed `lang#python` but see no errors from the code linters, either when saving the file or typing `SPC e l`.

## The reproduce ways from Vim starting (Required!)

Edit `test.py` with a `=` instead of a `==` on line 1:

```python
if __name__ = "__main__" :
    print("Hello world!")
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'one'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/franck/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 80
  plugin_bundle_dir = '/home/franck/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-virtualenv'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="unite"
[[layers]]
  name="lang#python"
  python_file_head=[]
  enable_linters=['python', 'pylint']
[[layers]]
  name="lang#latex"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(/usr/bin/nvim)
version: NVIM v0.6.1
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `shell`:ok
  - `unite`:ok
  - `lang#python`:ok
  - `lang#latex`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/franck/.SpaceVim/
[ SpaceVim ] [00:00:00:000] [ Info  ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/usr/bin/python3
[ SpaceVim ] [00:00:00:048] [ Info  ] Startup with argv: ['vi', 'test.py']
[ SpaceVim ] [00:00:00:053] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:053] [ Info  ] global_dir is: /home/franck/.SpaceVim.d/
[ SpaceVim ] [00:00:00:053] [ Info  ] find global config: /home/franck/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:054] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:055] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:055] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:056] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:075] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:01:843] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:01:843] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:01:855] [ Info  ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [00:00:01:855] [ Info  ] no func found for mode:fill-column-indicator
[ SpaceVim ] [00:00:01:860] [ Info  ] try to call func of mode:wrapline
[ SpaceVim ] [00:00:01:860] [ Info  ] no func found for mode:wrapline
[ SpaceVim ] [00:00:01:861] [ Info  ] try to call func of mode:whitespace
[ SpaceVim ] [00:00:01:861] [ Info  ] no func found for mode:whitespace
[ SpaceVim ] [00:00:01:895] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:01:985] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:986] [ Info  ] Load projects cache from: /home/franck/.cache/SpaceVim/projects.json
[  project ] [00:00:01:986] [ Info  ] switch to project:[Desktop]
[  project ] [00:00:01:986] [ Info  ]        rootdir is:/home/franck/Desktop/
[  project ] [00:00:03:732] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:03:740] [ Info  ] key binding guide float statusline winid:1003
[ SpaceVim ] [00:00:04:226] [ Info  ] close float statusline winid:1003
[ SpaceVim ] [00:00:04:237] [ Info  ] key binding guide float statusline winid:1005
[ SpaceVim ] [00:00:04:487] [ Info  ] close float statusline winid:1005
[ SpaceVim ] [00:00:04:491] [ Info  ] lsp client: nvim built-in lsp
[ SpaceVim ] [00:00:10:425] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:10:431] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:10:431] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:10:436] [ Info  ] try to call func of mode:syntax-checking
[ SpaceVim ] [00:00:10:439] [ Info  ] try to call func of mode:fill-column-indicator
[ SpaceVim ] [00:00:10:439] [ Info  ] no func found for mode:fill-column-indicator
[ SpaceVim ] [00:00:10:439] [ Info  ] try to call func of mode:wrapline
[ SpaceVim ] [00:00:10:439] [ Info  ] no func found for mode:wrapline
[ SpaceVim ] [00:00:10:440] [ Info  ] try to call func of mode:whitespace
[ SpaceVim ] [00:00:10:440] [ Info  ] no func found for mode:whitespace

```
</details>

## Screenshots

nvim showing `no errors` after hitting `SPC e l`:

![nvim showing 'no errors' after 'SPC e l'](https://user-images.githubusercontent.com/4525552/213439645-0f3adf2b-bf04-46b9-8917-6d9ebde9760b.png)

error found by pylint called from the shell:

![pylint in the shell showin the error](https://user-images.githubusercontent.com/4525552/213439739-14149aba-9a9a-49a1-967f-1561f1c03b7d.png)

**Comment by fpom** [comment]
It works now, I did not do anything to obtain this, except some reboots. I've also changed config to include a `bootstrap_before` that sets `clipboard=unnamedplus`. For information, I give below the new output of `:SPDebugInfo!`. I'm closing the issue since it vanished magically. However, if someone has an idea, I'd be happy to know what the problem was.

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'one'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/franck/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 80
  plugin_bundle_dir = '/home/franck/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-virtualenv'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="unite"
[[layers]]
  name="lang#python"
  python_file_head=[]
  enable_linters=['python', 'pylint']
[[layers]]
  name="lang#latex"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(/usr/bin/nvim)
version: NVIM v0.6.1
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `shell`:ok
  - `unite`:ok
  - `lang#python`:ok
  - `lang#latex`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/franck/.SpaceVim/
[ SpaceVim ] [00:00:00:000] [ Info  ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/usr/bin/python3
[ SpaceVim ] [00:00:00:050] [ Info  ] Startup with argv: ['vi', 'test.py']
[ SpaceVim ] [00:00:00:054] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:054] [ Info  ] global_dir is: /home/franck/.SpaceVim.d/
[ SpaceVim ] [00:00:00:054] [ Info  ] find global config: /home/franck/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:054] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:056] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:056] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:076] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:01:031] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:01:031] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:01:077] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:01:192] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:193] [ Info  ] Load projects cache from: /home/franck/.cache/SpaceVim/projects.json
[  project ] [00:00:01:194] [ Info  ] switch to project:[Desktop]
[  project ] [00:00:01:194] [ Info  ]        rootdir is:/home/franck/Desktop/
[ SpaceVim ] [00:00:09:000] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:10:010] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:10:010] [ Info  ] the func has been added to mode:paste-mode

```
</details>
