### ISSUE TITLE
Plugins don't automatically install

### ISSUE THREAD

**Issue by johngilbert2000** [wsdjeg/SpaceVim#4792]
## Expected behavior, english is required
Plugins should install when I open SpaceVim for the first time

## The reproduce ways from Vim starting (Required!)
SpaceVim plugins do not install automatically when I open SpaceVim, and I can't figure out how to get the plugins to install. I've tried uninstalling deleting .SpaceVim and .SpaceVim.d, and reinstalling. I am using Manjaro GNOME, and I believe something important got deleted when trying to clean up space on my computer (running `sudo pacman -Rns $(pacman -Qtdq)`)

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/j2000/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/j2000/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 900
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [04:54:12] [   0.001] [  Info ] Loading SpaceVim from: /home/j2000/.SpaceVim/
[ SpaceVim ] [04:54:12] [   0.056] [  Info ] Startup with argv: ['vim', 'clean.sh']
[ SpaceVim ] [04:54:12] [   0.073] [  Info ] start loading global config >>>
[ SpaceVim ] [04:54:12] [   0.073] [  Info ] global_dir is: /home/j2000/.SpaceVim.d/
[ SpaceVim ] [04:54:12] [   0.073] [  Info ] find global config: /home/j2000/.SpaceVim.d/init.toml
[ SpaceVim ] [04:54:12] [   0.073] [  Info ] start to apply config [glob]
[ SpaceVim ] [04:54:12] [   0.076] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [04:54:12] [   0.082] [  Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [04:54:12] [   0.162] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [04:54:12] [   0.234] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [04:54:12] [   0.235] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [04:54:12] [   0.289] [  Info ] try to call func of mode:syntax-checking
[ SpaceVim ] [04:54:12] [   0.339] [  Info ] try to call func of mode:wrapline
[ SpaceVim ] [04:54:12] [   0.339] [  Info ] no func found for mode:wrapline
[ SpaceVim ] [04:54:12] [   0.422] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [04:54:12] [   0.576] [  Info ] run root changed callback on VimEnter!
[   rooter ] [04:54:12] [   0.577] [  Info ] Load projects cache from: /home/j2000/.cache/SpaceVim/projects.json
[ SpaceVim ] [04:54:23] [  11.586] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [04:54:23] [  11.613] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [04:54:23] [  11.614] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [04:54:23] [  11.639] [  Info ] try to call func of mode:wrapline
[ SpaceVim ] [04:54:23] [  11.639] [  Info ] no func found for mode:wrapline
```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
