### ISSUE TITLE
Fuzzy finder (all alternative layers) not working

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4794]
nvim 0.7.2
Ubuntu 22.04

## Expected behavior, english is required

I would like to have the fuzzy finder features described in the documentation.

## The reproduce ways from Vim starting (Required!)

Enabling the layer "ctrlp" or "denite" or "fzf" in my `init.toml` does not give access to `[spc] f` features like `[spc] f e` for Fuzzy find register for example.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/vim-scripts/argtextobj.vim', {'repo': 'https://github.com/vim-scripts/argtextobj.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/KabbAmine/zeavim.vim', {'repo': 'https://github.com/KabbAmine/zeavim.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/Xuyuanp/nerdtree-git-plugin', {'repo': 'https://github.com/Xuyuanp/nerdtree-git-plugin', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'JetBrainsMono Nerd Font Mono:h10.5:l'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-ctrlp-message'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 40
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_indentline=0
  cursorword_delay=1500
  enable_cursorword=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
[[layers]]
  name="ctrlp"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `shell`:ok
  - `lang#c`:ok
  - `lang#python`:ok
  - `git`:ok
  - `VersionControl`:ok
  - `debug`:ok
  - `ctrlp`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/jacky/.SpaceVim/
[ SpaceVim ] [00:00:00:107] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:107] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:107] [ Info  ] options init done
[ SpaceVim ] [00:00:00:114] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:114] [ Info  ] global_dir is: /home/jacky/.SpaceVim.d/
[ SpaceVim ] [00:00:00:114] [ Info  ] find global config: /home/jacky/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:114] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:117] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:118] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:149] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:176] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:176] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:212] [ Info  ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:256] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:353] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:00:360] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:00:505] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:505] [ Info  ] switch to project:[jacky]
[  project ] [00:00:00:505] [ Info  ]        rootdir is:/home/jacky/
[  project ] [00:00:02:288] [ Info  ]         (.git/):/home/jacky/Documents/proj/CtrlCraft/
[  project ] [00:00:02:288] [ Info  ] switch to project:[CtrlCraft]
[  project ] [00:00:02:288] [ Info  ]        rootdir is:/home/jacky/Documents/proj/CtrlCraft/
[ SpaceVim ] [00:00:04:941] [ Info  ] key binding guide float statusline winid:1004
[ SpaceVim ] [00:00:04:964] [ Info  ] close float statusline winid:1004
[ SpaceVim ] [00:00:04:984] [ Info  ] key binding guide float statusline winid:1006
[ SpaceVim ] [00:00:07:353] [ Info  ] close float statusline winid:1006
[ SpaceVim ] [00:00:12:977] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:12:986] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:12:986] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:13:001] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:00:13:001] [ Info  ] statusline build-in section hunks has been changed!

```
</details>
