### ISSUE TITLE
a language check window pop up.

### ISSUE THREAD

**Issue by JaydenFish** [wsdjeg/SpaceVim#4796]
In C++ program mode, I disabled all language checker. When I quickly click `<SPC> <l> <c>`, there is a language check window pop up below the screen. When I slowly click <SPC> <l> <c>, It doesn't show. I don't want language checker. It seems like a bug.

enviroment:
latest spacevim

**Comment by wsdjeg** [comment]
I can not reproduce it.

**Comment by JaydenFish** [comment]
I record this bug in a video. https://www.youtube.com/watch?v=RZJ3GCqWos0

**Comment by wsdjeg** [comment]
you can use:

```toml
[[layers]]
  name = "checkers"
  show_cursor_error = false
  open_error_list = 0
```
