### ISSUE TITLE
Bootstrap_before (and after) not being called at all

### ISSUE THREAD

**Issue by Spodeian** [wsdjeg/SpaceVim#4797]
## Expected behavior, english is required
Bootstrap_before function is called and doesn't abort.

## The reproduce ways from Vim starting (Required!)
Open NeoVim from powershell 7 via 'nvim' command

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\MyUserName\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\MyUserName\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'nvim-lspconfig'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'package.json', 'Cargo.toml', '.clang', 'package.json', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
  format_on_save=1
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="denite"
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="treesitter"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#ipynb"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#python"
  python_interpreter='C:\Python311\python.exe'
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#WebAssembly"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lsp"
  enabled_clients=['clangd', 'rust', 'vimls', 'pyls']
  override_cmd={'rust': ['rust-analyzer'], 'vimls': ['vim-language-server', '--stdio']}
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim.exe(C:\Program Files\Neovim\bin\nvim.exe)
version: NVIM v0.8.3
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `denite`:ok
  - `git`:ok
  - `VersionControl`:ok
  - `treesitter`:ok
  - `lang#c`:ok
  - `lang#html`:ok
  - `lang#ipynb`:ok
  - `lang#javascript`:ok
  - `lang#json`:ok
  - `lang#latex`:ok
  - `lang#lua`:ok
  - `lang#powershell`:ok
  - `lang#python`:ok
  - `lang#rust`:ok
  - `lang#sh`:ok
  - `lang#toml`:ok
  - `lang#WebAssembly`:ok
  - `lang#xml`:ok
  - `lsp`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: C:/Users/MyUserName/.SpaceVim/
[ SpaceVim ] [00:00:00:000] [ Info  ] $PYTHON_HOST_PROG is not empty, setting g:python_host_prog:C:\Python311\python.exe
[ SpaceVim ] [00:00:00:492] [ Info  ] Startup with no argv, current dir is used: ~\AppData\Local\nvim
[ SpaceVim ] [00:00:00:493] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:494] [ Info  ] options init done
[ SpaceVim ] [00:00:00:535] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:535] [ Info  ] global_dir is: C:/Users/MyUserName/.SpaceVim.d/
[ SpaceVim ] [00:00:00:535] [ Info  ] find global config: C:/Users/MyUserName/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:537] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:578] [ Error ] bootstrap_before function failed: myspacevim#before
[ SpaceVim ] [00:00:00:578] [ Error ]        exception: Vim(call):E117: Unknown function: myspacevim#before
[ SpaceVim ] [00:00:00:578] [ Error ]        throwpoint: C:\Users\MyUserName\AppData\Local\nvim\init.vim[60]..function SpaceVim#custom#load[1]..<SNR>51_load_glob_conf[14]..<SNR>51_apply, line 110
[ SpaceVim ] [00:00:00:579] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:648] [ Info  ] find local conf: C:/Users/MyUserName/AppData/Local/nvim/.SpaceVim.d/init.vim
[ SpaceVim ] [00:00:00:655] [ Info  ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [00:00:00:799] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:916] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:917] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:01:075] [ Info  ] Load projects cache from: C:/Users/MyUserName/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:01:496] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:01:998] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:02:008] [ Info  ] try to open SpaceVim welcome page
[  project ] [00:00:02:242] [ Info  ] switch to project:[nvim]
[  project ] [00:00:02:242] [ Info  ]        rootdir is:C:/Users/MyUserName/AppData/Local/nvim/
[ SpaceVim ] [00:00:02:258] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:02:259] [ Info  ] switch to project:[nvim]
[  project ] [00:00:02:259] [ Info  ]        rootdir is:C:/Users/MyUserName/AppData/Local/nvim/
[ SpaceVim ] [00:00:02:280] [ Info  ] loading local conf: .SpaceVim.d/init.vim
[ SpaceVim ] [00:00:02:296] [ Info  ] finished loading local conf
[ SpaceVim ] [00:00:07:141] [ Info  ] key binding guide float statusline winid:1004
[ SpaceVim ] [00:00:07:310] [ Info  ] close float statusline winid:1004
[ SpaceVim ] [00:00:07:383] [ Info  ] key binding guide float statusline winid:1006
[ SpaceVim ] [00:00:07:921] [ Info  ] close float statusline winid:1006
[ SpaceVim ] [00:21:53:711] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:21:53:757] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:21:53:758] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:21:53:809] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:21:53:809] [ Info  ] statusline build-in section hunks has been changed!
[  project ] [00:21:53:931] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:22:10:672] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:22:10:717] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:22:10:718] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:22:10:768] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:22:10:768] [ Info  ] statusline build-in section hunks has been changed!

```
</details>
