### ISSUE TITLE
plantuml filetype not set even though lang#plantuml layer is enabled

### ISSUE THREAD

**Issue by pplatek** [wsdjeg/SpaceVim#4804]
## Expected behavior
filetype is set to `plantuml` and syntax highlighting works

## The reproduce ways from Vim starting (Required!)
Fresh installation of SpaceVim

init.toml
```
[options]     
    # set spacevim theme. by default colorscheme layer is not loaded,                                                                                                                                                                                                                                                                                                                                                                                                                         
    # if you want to use more colorscheme, please load the colorscheme                                                                                                                                                                                                                                                                                                                                                                                                                        
    # layer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    colorscheme = "gruvbox"                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    colorscheme_bg = "dark"                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    # Disable guicolors in basic mode, many terminal do not support 24bit                                                                                                                                                                                                                                                                                                                                                                                                                     
    # true colors                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    enable_guicolors = false                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    # Disable statusline separator, if you want to use other value, please                                                                                                                                                                                                                                                                                                                                                                                                                    
    # install nerd fonts                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    statusline_separator = "nil"                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    statusline_iseparator = "bar"                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    buffer_index_type = 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    windows_index_type = 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    enable_tabline_filetype_icon = false                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    enable_statusline_mode = false                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    statusline_unicode = false                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    # Enable vim compatible mode, avoid changing origin vim key bindings                                                                                                                                                                                                                                                                                                                                                                                                                      
    vimcompatible = true                                                                            
                                                                                                                                                                                                                                                                                                                                                                                        
# Enable autocomplete layer     
[[layers]]     
name = 'autocomplete'     
auto_completion_return_key_behavior = "complete"     
auto_completion_tab_key_behavior = "cycle"     
     
[[layers]]     
name = 'shell'     
default_position = 'top'     
default_height = 30     
     
[[layers]]     
name = "lang#plantuml"
```

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/peterp/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/peterp/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-slumlord'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#plantuml"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/home/peterp/brew/Cellar/neovim/0.8.3/bin/nvim)
version: NVIM v0.8.3
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#plantuml`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/peterp/.SpaceVim/
[ SpaceVim ] [00:00:00:270] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:271] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:273] [ Info  ] options init done
[ SpaceVim ] [00:00:00:292] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:293] [ Info  ] global_dir is: /home/peterp/.SpaceVim.d/
[ SpaceVim ] [00:00:00:293] [ Info  ] find global config: /home/peterp/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:293] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:296] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:299] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:389] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:450] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:450] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:00:507] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:00:593] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:00:660] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:662] [ Info  ] Load projects cache from: /home/peterp/.cache/SpaceVim/projects.json
[  project ] [00:00:00:662] [ Info  ] switch to project:[peterp]
[  project ] [00:00:00:662] [ Info  ]        rootdir is:/home/peterp/
[  project ] [00:00:02:849] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:02:879] [ Info  ] key binding guide float statusline winid:1004
[ SpaceVim ] [00:00:03:559] [ Info  ] close float statusline winid:1004
[ SpaceVim ] [00:00:03:599] [ Info  ] key binding guide float statusline winid:1006
[ SpaceVim ] [00:01:32:627] [ Info  ] close float statusline winid:1006
[ SpaceVim ] [00:01:34:713] [ Info  ] key binding guide float statusline winid:1008
[ SpaceVim ] [00:01:35:206] [ Info  ] close float statusline winid:1008
[ SpaceVim ] [00:01:35:240] [ Info  ] key binding guide float statusline winid:1010
[ SpaceVim ] [00:01:35:430] [ Info  ] close float statusline winid:1010
[ SpaceVim ] [00:01:35:464] [ Info  ] key binding guide float statusline winid:1012
[ SpaceVim ] [00:01:35:679] [ Info  ] close float statusline winid:1012
[ SpaceVim ] [00:06:50:659] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:06:50:682] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:06:50:683] [ Info  ] the func has been added to mode:paste-mode

```
</details>


If I force the `set filetype=plantuml`, then everything works fine.
