### ISSUE TITLE
[LSP] Rename, no matching language servers with rename capability

### ISSUE THREAD

**Issue by BAF3C9BDC8CB** [wsdjeg/SpaceVim#4809]
## The reproduce ways from Vim starting (Required!)
Install the java environment according to the tutorial on the official website. After installation, other functions can be used, except for the lsp language server.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\Luis\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\Luis\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'neomru.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'build.gradle', 'pom.xml', 'build.gradle', 'pom.xml', 'build.gradle']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
 relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix',
'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'cn'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
name="colorscheme"
  random_theme=1
[[layers]]
  name="chinese"
[[layers]]
  name="lang#java"
[[layers]]
  name="lsp"
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.level=ALL', '-noverify', '-Xmx1G', '--add-modules=ALL-SYSTEM', '--add-opens java.base/java.util=ALL-UNNAMED', '--add-opens java.base/java.lang=ALL-UNNAMED', '-jar', 'C:\Users\Luis\.SpaceVim.d\
vim_dev\jdt-language-server-latest\plugins\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar', '-configuration', 'C:\Users\Luis\.SpaceVim.d\
vim_dev\jdt-language-server-latest\config_win', '-data', 'C:\Users\Luis\.SpaceVim.d\
vim_dev\jdt-language-server-latest\workspace']}
  filetypes=['java']
[[layers]]
  name="tagbar"
[[layers]]
  name="denite"
```
### SpaceVim Health checking :
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(D:\Program Files (x86)\nvim-win64\bin\nvim.exe)
version: NVIM v0.8.2
OS: windows
[shell, shellcmdflag, shellslash]: ['cmd.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `chinese`:ok
  - `lang#java`:ok
  - `lsp`:ok
  - `tagbar`: can not find function: SpaceVim#layers#tagbar#health()
  - `denite`:ok

### SpaceVim runtime log :
```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: C:/Users/Luis/.SpaceVim/
[ SpaceVim ] [00:00:00:211] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:211] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:211] [ Info  ] options init done
[ SpaceVim ] [00:00:00:234] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:234] [ Info  ] global_dir is: C:/Users/Luis/.SpaceVim.d/
[ SpaceVim ] [00:00:00:235] [ Info  ] find global config: C:/Users/Luis/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:235] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:248] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:251] [ Info  ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [00:00:00:333] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:401] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:402] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:482] [ Info  ] Load projects cache from: C:/Users/Luis/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:581] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:994] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:00:998] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:01:202] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:202] [ Info  ] switch to project:[Luis]
[  project ] [00:00:01:202] [ Info  ]        rootdir is:C:/Users/Luis/
[  project ] [00:00:06:241] [ Info  ]         (.git/):D:/projects/yytProject/yytCloud/
[  project ] [00:00:06:248] [ Info  ]         (pom.xml):D:/projects/yytProject/yytCloud/
[  project ] [00:00:06:250] [ Info  ] switch to project:[yytCloud]
[  project ] [00:00:06:250] [ Info  ]        rootdir is:D:/projects/yytProject/yytCloud/
[ SpaceVim ] [00:01:47:725] [ Info  ] lsp client: nvim built-in lsp
[ SpaceVim ] [00:08:39:816] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:08:39:843] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:08:39:844] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:09:25:235] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:09:25:263] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:09:25:263] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:09:43:020] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:09:43:048] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:09:43:048] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots 
![image](https://user-images.githubusercontent.com/30283646/228119174-ddb7d44c-8e9c-4a84-99d9-ebb71d350442.png)
![image](https://user-images.githubusercontent.com/30283646/228119232-923af564-0296-4215-a636-87a662b01a35.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
