### ISSUE TITLE
Autocomplete questions

### ISSUE THREAD

**Issue by DDGRCF** [wsdjeg/SpaceVim#4821]
**Is your feature request related to a problem? Please describe.**

When I installed youcomplete plugin in spacevim, I find that a file will code checker by two engine. One is youcomplete and another is spacevim itself.  like 

![截图 2023-04-01 10-33-14](https://user-images.githubusercontent.com/63622528/229261779-86dae3ce-982b-4b0a-aa3f-9af201f3e717.png)
How I disable the yellow code checker.

Here is my config
```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts

    enable_filetree_gitstatus = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    enable_ycm = true
    bootstrap_after="config#after"


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "ycm"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#python'
python_interpreter = '/home/r/anaconda3/bin/python'

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c11"

[[layers]]
name = 'lang#go'

[[layers]]
name = 'format'
enable = true
format_on_save = true
[Layers.override_cmd]
  go = ["gofmt -s -w --google"]
  c = ["clang-format -style=google -i"]
  cpp = ["clang-format -style=google -i"]
  javascript = ["prettier --single-quote --trailing-comma es5 --print-width 120 --no-semi --jsx-single-quote --arrow-parens always --write"]
  json = ["prettier --single-quote --trailing-comma es5 --print-width 120 --write"]
  python = ["autopep8 --in-place --aggressive --aggressive --max-line-length=120"]
  rust = ["rustfmt --config-path=~/.config/rustfmt.toml"]


[[custom_plugins]]
name = "Valloric/YouCompleteMe"
merge = 0

[[layers]]
name = 'debug'

[[custom_plugins]]
name = "rdnetto/YCM-Generator"
merged = 0

[[custom_plugins]]
name = "dyng/ctrlsf.vim"
merged = 0
```
**Additional context**
