### ISSUE TITLE
Spacevim of coc can't find header file

### ISSUE THREAD

**Issue by DDGRCF** [wsdjeg/SpaceVim#4822]
## Expected behavior, english is required
I have enabled the coc module in spacevim but it has been showing that the header file cannot be found. However, the jump of the code is indeed normal.

## The reproduce ways from Vim starting (Required!)
Here is my project workdir
```shell
...
├── CMakeLists.txt
├── compile_commands.json -> build/compile_commands.json
...
├── LICENSE
├── README.md
```
Here is my spacevim config
```toml
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts

    enable_filetree_gitstatus = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_after="config#after"
    autocomplete_method = "coc" 
    enable_neomake = true


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "coc"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'lsp'
filetypes = [
  'c',
  'cpp',
  'go',
  'css',
  'javascript',
  'python'
]

[[layers]]
name = 'lang#python'
python_interpreter = '/home/r/anaconda3/bin/python'

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c11"

[[layers]]
name = 'lang#go'

[[layers]]
name = 'format'
enable = true
format_on_save = true
[Layers.override_cmd]
  go = ["gofmt -s -w --google"]
  c = ["clang-format -style=google -i"]
  cpp = ["clang-format -style=google -i"]
  javascript = ["prettier --single-quote --trailing-comma es5 --print-width 120 --no-semi --jsx-single-quote --arrow-parens always --write"]
  json = ["prettier --single-quote --trailing-comma es5 --print-width 120 --write"]
  python = ["autopep8 --in-place --aggressive --aggressive --max-line-length=120"]
  rust = ["rustfmt --config-path=~/.config/rustfmt.toml"]

# [[custom_plugins]]
# name = "Valloric/YouCompleteMe"
# merge = 0
#
# [[custom_plugins]]
# name = "rdnetto/YCM-Generator"
# merged = 0


[[layers]]
name = 'debug'

[[custom_plugins]]
name = "dyng/ctrlsf.vim"
merged = 0

[[custom_plugins]]
name = "roxma/vim-tmux-clipboard"
merged = 0

[[custom_plugins]]
name = "tmux-plugins/vim-tmux-focus-events"
merged = 0

```
## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
