### ISSUE TITLE
Can't run anything with spacevim in Windows. (both vim and nvim)

### ISSUE THREAD

**Issue by unta1337** [wsdjeg/SpaceVim#4824]
Using spacevim in windows, I found some bugs with tasks.
Maybe it responsible to runner.

BTW, problem below not shown in WSL; maybe Windows is the problem.

## Expected behavior, english is required
Some of my tasks are work, but some of them aren't.

I configured my tasks.json as follow:
``` toml
[echo-test]
command = 'echo'
args = [
    'Hello'
]

[echo-with-pwsh-test]
command = 'powershell'
args = [
    '-c',
    'echo',
    'Hello from powershell!'
]

[clang-test]
command = 'clang'
```

All of tasks above are not working in nvim.
echo-with-pwsh-test and clang-test are working in vim.

## The reproduce ways from Vim starting (Required!)
It is simple to reproduce this problem.
Config your tasks.json and run it.

## Output of the `:SPDebugInfo!`
And unfortunately, I couldn't gather some useful information about this problem.

<details><summary> SpaceVim debug information (vim) </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\first\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Sarasa_Fixed_K:h12:b'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\first\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'java_getset.vim'
  project_auto_root = 0
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'build.gradle']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\Program Files\Neovim\bin\nvim.exe)
version: NVIM v0.8.2
OS: windows
[shell, shellcmdflag, shellslash]: ['C:/Windows/SysWOW64/WindowsPowerShell/v1.0/powershell.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `colorscheme`:ok
  - `lang#c`:ok
  - `lang#python`:ok
  - `lang#java`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: C:/Users/first/.SpaceVim/
[ SpaceVim ] [00:00:00:792] [ Info  ] Startup with no argv, current dir is used: C:\Program Files\goneovim-v0.6.4-windows\goneovim-v0.6.4-windows
[ SpaceVim ] [00:00:00:793] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:793] [ Info  ] options init done
[ SpaceVim ] [00:00:00:808] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:808] [ Info  ] global_dir is: C:/Users/first/.SpaceVim.d/
[ SpaceVim ] [00:00:00:808] [ Info  ] find global config: C:/Users/first/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:809] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:815] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:815] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:817] [ Info  ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [00:00:00:874] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:921] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:921] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:978] [ Info  ] Load projects cache from: C:/Users/first/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:01:046] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:01:184] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:01:230] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:230] [ Info  ] switch to project:[goneovim-v0.6.4-windows]
[  project ] [00:00:01:230] [ Info  ]        rootdir is:C:/Program Files/goneovim-v0.6.4-windows/goneovim-v0.6.4-windows/
[  project ] [00:01:15:711] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[   runner ] [00:01:18:094] [ Info  ]    cmd:'echo Hello'
[   runner ] [00:01:22:493] [ Info  ]    cmd:'clang'
[ SpaceVim ] [00:01:39:961] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:01:40:093] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:01:40:093] [ Info  ] the func has been added to mode:paste-mode

```
</details>

<details><summary> SpaceVim debug information (nvim) </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'onedark'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\first\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Sarasa_Fixed_K:h12:b'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\first\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'java_getset.vim'
  project_auto_root = 0
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'build.gradle']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#java"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(C:\Program Files\Neovim\bin\nvim.exe)
version: NVIM v0.8.2
OS: windows
[shell, shellcmdflag, shellslash]: ['C:/Windows/SysWOW64/WindowsPowerShell/v1.0/powershell.exe', '/s /c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `colorscheme`:ok
  - `lang#c`:ok
  - `lang#python`:ok
  - `lang#java`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: C:/Users/first/.SpaceVim/
[ SpaceVim ] [00:00:00:792] [ Info  ] Startup with no argv, current dir is used: C:\Program Files\goneovim-v0.6.4-windows\goneovim-v0.6.4-windows
[ SpaceVim ] [00:00:00:793] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:793] [ Info  ] options init done
[ SpaceVim ] [00:00:00:808] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:808] [ Info  ] global_dir is: C:/Users/first/.SpaceVim.d/
[ SpaceVim ] [00:00:00:808] [ Info  ] find global config: C:/Users/first/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:809] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:815] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:815] [ Info  ] Could not find project local config
[ SpaceVim ] [00:00:00:817] [ Info  ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [00:00:00:874] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:921] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:921] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:978] [ Info  ] Load projects cache from: C:/Users/first/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:01:046] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:01:184] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:01:230] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:230] [ Info  ] switch to project:[goneovim-v0.6.4-windows]
[  project ] [00:00:01:230] [ Info  ]        rootdir is:C:/Program Files/goneovim-v0.6.4-windows/goneovim-v0.6.4-windows/
[  project ] [00:01:15:711] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[   runner ] [00:01:18:094] [ Info  ]    cmd:'echo Hello'
[   runner ] [00:01:22:493] [ Info  ]    cmd:'clang'
[ SpaceVim ] [00:01:39:961] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:01:40:093] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:01:40:093] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots
![vim echo-test not working](https://user-images.githubusercontent.com/51486948/229333735-70986d4c-f5e0-40d0-839f-08ec4729f67a.png)

![vim echo-with-pwsh-test working](https://user-images.githubusercontent.com/51486948/229333740-49fa6f95-d1d8-4ed6-88a7-b79d472c2860.png)

![vim clang-test working](https://user-images.githubusercontent.com/51486948/229333781-dca09173-0bb4-4ac3-baa9-a6a8d88ced9b.png)

![nvim clang-test not working](https://user-images.githubusercontent.com/51486948/229333789-0741e588-33f0-4119-bd29-59c60fab4618.png)

Runner screens stay the same as shown above. They never change, run nor exit with whatever the code is.
