### ISSUE TITLE
lang#python not loaded in [SPC] h l

### ISSUE THREAD

**Issue by Djedouas** [wsdjeg/SpaceVim#4825]
## Expected behavior, english is recommend

In list-all-layers view, `lang#python` should be loaded because it's in my layers list, and health checking says that it's ok.

I don't know if the layer is not loaded of if it's a false information in this view.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.7.2
- SpaceVim version: 2.2.0-dev
- SpaceVim status: de6efc65

```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	after/syntax/python.vim

nothing added to commit but untracked files present (use "git add" to track)
```

<details><summary>after/syntax/python.vim</summary>

```
hi link pythonFunctionCall SrceryBlue
hi link pythonClassVar SrceryWhite
hi link pythonDot SrceryOrangeBold
hi link pythonImport SrceryRed
hi link pythonClass SrceryCyanBold
hi link pythonFString SrceryGreen
```

</details>

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'srcery'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['https://github.com/vim-python/python-syntax.git', {'repo': 'https://github.com/vim-python/python-syntax.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/bkad/CamelCaseMotion.git', {'repo': 'https://github.com/bkad/CamelCaseMotion.git', 'merged': 0, 'overwrite': 1}], ['https://github.com/vim-scripts/argtextobj.vim', {'repo': 'https://github.com/vim-scripts/argtextobj.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/KabbAmine/zeavim.vim', {'repo': 'https://github.com/KabbAmine/zeavim.vim', 'merged': 0, 'overwrite': 1}], ['https://github.com/Xuyuanp/nerdtree-git-plugin', {'repo': 'https://github.com/Xuyuanp/nerdtree-git-plugin', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/jacky/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'left'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'JetBrainsMono Nerd Font Mono:h10.5:l'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/jacky/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'fzf-neoyank'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 40
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'slant'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'slant'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_indentline=0
  cursorword_delay=1500
  enable_cursorword=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="gtags"
  gtagslabel='exuberant ctag'
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lsp"
  enabled_client=['pylsp']
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="git"
[[layers]]
  name="VersionControl"
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
[[layers]]
  name="fzf"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `gtags`:ok
  - `shell`:ok
  - `lang#c`:ok
  - `lsp`:ok
  - `lang#python`:ok
  - `git`:ok
  - `VersionControl`:ok
  - `debug`:ok
  - `fzf`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/jacky/.SpaceVim/
[ SpaceVim ] [00:00:00:000] [ Info  ] $PYTHON_HOST_PROG is not empty, setting g:python_host_prog:python2
[ SpaceVim ] [00:00:00:000] [ Info  ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:python
[ SpaceVim ] [00:00:00:184] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:185] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:186] [ Info  ] options init done
[ SpaceVim ] [00:00:00:213] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:213] [ Info  ] global_dir is: /home/jacky/.SpaceVim.d/
[ SpaceVim ] [00:00:00:213] [ Info  ] find global config: /home/jacky/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:213] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:226] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:316] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:402] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:403] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:501] [ Info  ] Load projects cache from: /home/jacky/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:660] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:898] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:00:907] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:01:273] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:273] [ Info  ] switch to project:[jacky]
[  project ] [00:00:01:273] [ Info  ]        rootdir is:/home/jacky/
[ SpaceVim ] [00:00:23:003] [ Info  ] key binding guide float statusline winid:1005
[ SpaceVim ] [00:00:27:520] [ Info  ] close float statusline winid:1005
[ SpaceVim ] [00:00:27:548] [ Info  ] key binding guide float statusline winid:1007
[ SpaceVim ] [00:00:31:272] [ Info  ] close float statusline winid:1007
[ SpaceVim ] [00:01:03:046] [ Info  ] key binding guide float statusline winid:1010
[ SpaceVim ] [00:01:03:069] [ Info  ] close float statusline winid:1010
[ SpaceVim ] [00:01:03:104] [ Info  ] key binding guide float statusline winid:1012
[ SpaceVim ] [00:01:05:197] [ Info  ] close float statusline winid:1012
[ SpaceVim ] [00:01:05:249] [ Info  ] key binding guide float statusline winid:1014
[ SpaceVim ] [00:01:12:151] [ Info  ] close float statusline winid:1014
[ SpaceVim ] [00:01:12:182] [ Info  ] key binding guide float statusline winid:1016
[ SpaceVim ] [00:01:14:727] [ Info  ] close float statusline winid:1016
[ SpaceVim ] [00:01:16:228] [ Info  ] key binding guide float statusline winid:1018
[ SpaceVim ] [00:01:16:248] [ Info  ] close float statusline winid:1018
[ SpaceVim ] [00:01:16:278] [ Info  ] key binding guide float statusline winid:1020
[ SpaceVim ] [00:01:16:298] [ Info  ] close float statusline winid:1020
[ SpaceVim ] [00:01:17:735] [ Info  ] key binding guide float statusline winid:1022
[ SpaceVim ] [00:01:17:754] [ Info  ] close float statusline winid:1022
[ SpaceVim ] [00:01:17:781] [ Info  ] key binding guide float statusline winid:1024
[ SpaceVim ] [00:01:23:367] [ Info  ] close float statusline winid:1024
[ SpaceVim ] [00:01:23:983] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:01:24:002] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:01:24:002] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:01:24:033] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [00:01:24:034] [ Info  ] statusline build-in section hunks has been changed!

```
</details>

## Screenshots

![image](https://user-images.githubusercontent.com/34267385/229521538-8572b02b-6172-480e-bb8b-10a3a16a6644.png)
