### ISSUE TITLE
window transient state

### ISSUE THREAD

**Issue by DDGRCF** [wsdjeg/SpaceVim#4829]
## Expected behavior, english is required
when use to window  transient state to resize the window(SPC w .), it can done well without the shell popup. But when I bring up the shell, the window always bisects the shell and other windows in this mode.

## The reproduce ways from Vim starting (Required!)
SPC ' to bring the shell and SPC w. to move the window.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'coc'
  autocomplete_parens = 1
  bootstrap_after = 'config#after'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['dyng/ctrlsf.vim', {'name': 'dyng/ctrlsf.vim', 'merged': 0, 'overwrite': 1}], ['roxma/vim-tmux-clipboard', {'name': 'roxma/vim-tmux-clipboard', 'merged': 0, 'overwrite': 1}], ['tmux-plugins/vim-tmux-focus-events', {'name': 'tmux-plugins/vim-tmux-focus-events', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/r/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_filetree_gitstatus = 1
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_neomake = 1
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/r/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vimproc.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
  autocomplete_method='coc'
[[layers]]
  name="format"
  enable=1
  format_on_save=1
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="lsp"
  filetypes=['c', 'cpp', 'go', 'css', 'javascript', 'python', 'shell']
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.8.3
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lsp`:ok
  - `debug`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/r/.SpaceVim/
[ SpaceVim ] [00:00:00:086] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:087] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:087] [ Info  ] options init done
[ SpaceVim ] [00:00:00:092] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:092] [ Info  ] global_dir is: /home/r/.SpaceVim.d/
[ SpaceVim ] [00:00:00:092] [ Info  ] find global config: /home/r/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:092] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:093] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:132] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:132] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:00:166] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:00:216] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:00:306] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:307] [ Info  ] Load projects cache from: /home/r/.cache/SpaceVim/projects.json
[  project ] [00:00:00:308] [ Info  ] switch to project:[r]
[  project ] [00:00:00:308] [ Info  ]        rootdir is:/home/r/
[  project ] [00:00:03:703] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:35:922] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:35:922] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
