### ISSUE TITLE
Deoplete don't work with python on macos

### ISSUE THREAD

**Issue by VCGRC** [wsdjeg/SpaceVim#4833]
## Expected behavior, english is required

I want deoplete working with python.
I have 
```
python3 --version
Python 3.11.2
```

```
nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

Layer `lang#python` is enabled.
MacOS : `13.3 (22E252)`

## The reproduce ways from Vim starting (Required!)

I have test script (you can see in screenshot, just write something to test autocomplete). I am opening it and trying to enter insert mode, but i see red error message (on first screenshot). Autocomplete is not working when i'm trying to import something or use variable, which i used before.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/Users/viktorblinov/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/viktorblinov/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'python-imports.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/opt/homebrew/Cellar/neovim/0.8.3/bin/nvim)
version: NVIM v0.8.3
OS: mac
[shell, shellcmdflag, shellslash]: ['/opt/homebrew/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#python`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /Users/viktorblinov/.SpaceVim/
[ SpaceVim ] [00:00:00:078] [ Info  ] Startup with argv: 2
[ SpaceVim ] [00:00:00:079] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:079] [ Info  ] options init done
[ SpaceVim ] [00:00:00:084] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:084] [ Info  ] global_dir is: /Users/viktorblinov/.SpaceVim.d/
[ SpaceVim ] [00:00:00:084] [ Info  ] find global config: /Users/viktorblinov/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:084] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:085] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:086] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:103] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:118] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:118] [ Info  ] the func has been added to mode:paste-mode
[ SpaceVim ] [00:00:00:146] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [00:00:00:263] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:265] [ Info  ] Load projects cache from: /Users/viktorblinov/.cache/SpaceVim/projects.json
[  project ] [00:00:00:265] [ Info  ] switch to project:[viktorblinov]
[  project ] [00:00:00:265] [ Info  ]        rootdir is:/Users/viktorblinov/
[ autosave ] [00:00:04:534] [ Info  ] backup path is:/Users/viktorblinov/.cache/SpaceVim/backup/_Users_viktorblinov_test_py.backup
[ SpaceVim ] [00:00:08:573] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:08:584] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:08:584] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:08:602] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:03:48:080] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:03:48:092] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:03:48:092] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots
<img width="896" alt="image" src="https://user-images.githubusercontent.com/93795198/230627483-b1a58f96-20a9-4baa-968a-8fb523222798.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/93795198/230627558-6c96d371-3452-4340-9987-20c38f3c164d.png">

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
