### ISSUE TITLE
Cannot create new file with neovim

### ISSUE THREAD

**Issue by dqnk** [wsdjeg/SpaceVim#4836]
## Expected behavior, english is required
On command `$ nvim test.c` I would expect nvim to open with Spacevim configuration and create a new file buffer (test.c does not exist currently). Instead Spacevim opens as if no file name was specified (startify menu).

## The reproduce ways from Vim starting (Required!)
Open Spacevim using `$ nvim test.c`.

When using nvim to create a new file, this line appears in :SPDebugInfo: `[ SpaceVim ] [00:00:00:449] [ Info  ] Startup with no argv, current dir is used: ~`
But with just Vim, this line appears instead: `[ SpaceVim ] [12:07:14] [   0.434] [  Info ] Startup with argv: 2`

If I just delete all Spacevim config, then both (barebone) nvim and vim create the file as expected.

This only happens with nvim version >= 0.9, with version 0.8.3 it works fine.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'molokai'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['tbodt/deoplete-tabnine', {'build': './install.sh'}]]
  data_dir = '/home/dqnk/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 8
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_filetypeicon = 1
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/dqnk/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-lsp'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'build.gradle', 'Cargo.toml', 'tsconfig.json', 'package.json']
  projects_cache_num = 100
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
  autocomplete_method='deoplete'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
  format_on_save=1
  format_method='neoformat'
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
[[layers]]
  name="git"
  git_plugin='fugitive'
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#assembly"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#jsonet"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#html"
[[layers]]
  name="telescope"
[[layers]]
  name="colorscheme"
[[layers]]
  name="tools"
[[layers]]
  name="lsp"
  enabled_clients=['rust_analyzer', 'pylsp', 'clangd']
  override_client_cmds={'rust_analyzer': ['rust-analyzer']}
  override_cmd={'rust': ['rust-analyzer']}
  filetypes=['rust', 'python', 'javascript', 'typescript', 'typescriptreact']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.9.0
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/fish', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `git`:ok
  - `lang#c`:ok
  - `lang#python`:ok
  - `lang#latex`:ok
  - `lang#assembly`:ok
  - `lang#java`:ok
  - `lang#jsonet`: can not find function: SpaceVim#layers#lang#jsonet#health()
  - `lang#rust`:ok
  - `lang#typescript`:ok
  - `lang#javascript`:ok
  - `lang#html`:ok
  - `telescope`:ok
  - `colorscheme`:ok
  - `tools`:ok
  - `lsp`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/dqnk/.SpaceVim/
[ SpaceVim ] [00:00:00:449] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:449] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:450] [ Info  ] options init done
[ SpaceVim ] [00:00:00:456] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:456] [ Info  ] global_dir is: /home/dqnk/.SpaceVim.d/
[ SpaceVim ] [00:00:00:456] [ Info  ] find global config: /home/dqnk/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:456] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:460] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:489] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:00:516] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:00:516] [ Info  ] the func has been added to mode:paste-mode
[  project ] [00:00:00:546] [ Info  ] Load projects cache from: /home/dqnk/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:626] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:01:104] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:01:107] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:01:254] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:01:254] [ Info  ] switch to project:[dqnk]
[  project ] [00:00:01:254] [ Info  ]        rootdir is:/home/dqnk/
[ SpaceVim ] [00:00:04:649] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [00:00:04:657] [ Info  ] the func has been added to mode:spell-checking
[ SpaceVim ] [00:00:04:657] [ Info  ] the func has been added to mode:paste-mode

```
</details>

## Screenshots

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
