### ISSUE TITLE
SPUpdate: Updating Failed

### ISSUE THREAD

**Issue by sarvex** [wsdjeg/SpaceVim#4841]
## Expected behavior, English is required
SPUpdate should update / install the missing plugins

## The reproduce ways from Vim starting (Required!)
1. Launch gVim on windows
2. Update plugins using `:SPUpdate`

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = 'C:\Users\Yoga\.cache\'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro NF'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = 'C:\Users\Yoga\.cache\vimfiles\'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-lsp'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 0
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang', 'pom.xml', 'build.gradle', 'package.json', 'Cargo.toml', 'tsconfig.json', '.clang', 'pom.xml', 'build.gradle', 'package.json', 'Cargo.toml', '.clang', 'pom.xml', 'build.gradle', 'package.json', 'Cargo.toml', '.clang', 'pom.xml', 'build.gradle', 'package.json', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="git"
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#lua"
[[layers]]
  name="lang#nim"
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#typescript"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['c', 'cpp', 'go', 'java', 'javascript', 'javascriptreact', 'lua', 'nim', 'python', 'rust', 'typescript']
[[layers]]
  name="VersionControl"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: gvim.exe(C:\Program Files\Vim\vim90\gvim.exe)
version: 900
OS: windows
[shell, shellcmdflag, shellslash]: ['C:\Windows\system32\cmd.exe', '/c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : to support +lua, you need recompile your vim with +lua support.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python3, install vim from https://github.com/vim/vim-win32-installer/releases
                                    install python3, make sure you have `python` in your path.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `git`:ok
  - `lang#c`:ok
  - `lang#go`:ok
  - `lang#java`:ok
  - `lang#javascript`:ok
  - `lang#lua`:ok
  - `lang#nim`:ok
  - `lang#python`:ok
  - `lang#rust`:ok
  - `lang#typescript`:ok
  - `lsp`:ok
  - `VersionControl`:ok
  - `shell`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:08:47] [   0.001] [  Info ] Loading SpaceVim from: C:/Users/Yoga/.SpaceVim/
[ SpaceVim ] [12:08:47] [   0.160] [  Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [12:08:47] [   0.234] [  Info ] start loading global config >>>
[ SpaceVim ] [12:08:47] [   0.234] [  Info ] global_dir is: C:/Users/Yoga/.SpaceVim.d/
[ SpaceVim ] [12:08:47] [   0.234] [  Info ] find global config: C:/Users/Yoga/.SpaceVim.d/init.toml
[ SpaceVim ] [12:08:47] [   0.258] [  Info ] start to apply config [glob]
[   rooter ] [12:08:47] [   0.261] [  Info ] Load projects cache from: C:/Users/Yoga/.cache/SpaceVim/projects.json
[   rooter ] [12:08:47] [   0.263] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:08:47] [   0.274] [  Warn ] Failed to load telescope layer, read :h SpaceVim-layer-telescope for more info!
[ SpaceVim ] [12:08:47] [   0.312] [  Warn ] Failed to enable lsp for c, clangd is not executable!
[ SpaceVim ] [12:08:47] [   0.321] [  Warn ] Failed to enable lsp for cpp, clangd is not executable!
[ SpaceVim ] [12:08:47] [   0.328] [  Warn ] Failed to find the lsp server command for java
[ SpaceVim ] [12:08:47] [   0.336] [  Warn ] Failed to enable lsp for javascript, typescript-language-server is not executable!
[ SpaceVim ] [12:08:47] [   0.346] [  Warn ] Failed to enable lsp for javascriptreact, typescript-language-server is not executable!
[ SpaceVim ] [12:08:47] [   0.346] [  Warn ] Failed to find the lsp server command for lua
[ SpaceVim ] [12:08:47] [   0.346] [  Warn ] Failed to find the lsp server command for nim
[ SpaceVim ] [12:08:47] [   0.354] [  Warn ] Failed to enable lsp for python, pyls is not executable!
[ SpaceVim ] [12:08:47] [   0.367] [  Warn ] Failed to enable lsp for typescript, typescript-language-server is not executable!
[ SpaceVim ] [12:08:47] [   0.374] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [12:08:47] [   0.476] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:08:47] [   0.543] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:08:47] [   0.543] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [12:08:47] [   0.742] [  Info ] lsp client: vim-lsp
[ SpaceVim ] [12:08:48] [   1.046] [  Info ] finished loading SpaceVim!
[   rooter ] [12:08:49] [   1.867] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [12:08:49] [   1.868] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:08:49] [   1.889] [  Info ] try to open SpaceVim welcome page
[   rooter ] [12:08:49] [   2.317] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:08:49] [   2.335] [  Info ] run root changed callback on VimEnter!
[   rooter ] [12:09:05] [  18.555] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:09:05] [  18.651] [  Info ] key binding guide float statusline winid:1004
[ SpaceVim ] [12:09:08] [  21.128] [  Info ] close float statusline winid:1004
[   rooter ] [12:09:08] [  21.140] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:09:08] [  21.229] [  Info ] key binding guide float statusline winid:1006
[ SpaceVim ] [12:09:08] [  21.309] [  Info ] close float statusline winid:1006
[   rooter ] [12:09:27] [  40.446] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:09:27] [  40.547] [  Info ] key binding guide float statusline winid:1008
[ SpaceVim ] [12:09:27] [  40.615] [  Info ] close float statusline winid:1008
[   rooter ] [12:09:27] [  40.618] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:09:27] [  40.713] [  Info ] key binding guide float statusline winid:1010
[ SpaceVim ] [12:09:44] [  56.947] [  Info ] close float statusline winid:1010
[   rooter ] [12:09:47] [  60.215] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:09:47] [  60.303] [  Info ] key binding guide float statusline winid:1012
[ SpaceVim ] [12:09:47] [  60.370] [  Info ] close float statusline winid:1012
[   rooter ] [12:09:47] [  60.374] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:09:47] [  60.463] [  Info ] key binding guide float statusline winid:1014
[ SpaceVim ] [12:09:47] [  60.523] [  Info ] close float statusline winid:1014
[ SpaceVim ] [12:09:58] [  71.385] [  Warn ]  [ plug manager ] All of the plugins are already installed.
[   rooter ] [12:10:03] [  76.031] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:10:05] [  78.504] [  Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 3
[ SpaceVim ] [12:10:06] [  78.931] [  Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 2
[ SpaceVim ] [12:10:06] [  79.353] [  Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 1
[   rooter ] [12:10:22] [  94.883] [  Info ] Start to find root for: C:/Users/Yoga/
[   rooter ] [12:10:24] [  97.548] [  Info ] Start to find root for: C:/Users/Yoga/
[   rooter ] [12:13:15] [ 267.795] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:13:17] [ 269.926] [  Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 3
[ SpaceVim ] [12:13:17] [ 270.366] [  Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 2
[ SpaceVim ] [12:13:18] [ 270.841] [  Warn ]  [ plug manager ] Reinstalling Failed Plugins. Remaining Retries: 1
[ SpaceVim ] [12:14:41] [ 354.632] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:14:41] [ 354.651] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:14:41] [ 354.651] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [12:14:41] [ 354.734] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [12:14:41] [ 354.734] [  Info ] statusline build-in section hunks has been changed!
[   rooter ] [12:14:59] [ 372.015] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [12:14:59] [ 372.016] [  Info ] Start to find root for: C:/Users/Yoga/
[   rooter ] [12:14:59] [ 372.603] [  Info ] Start to find root for: C:/Users/Yoga/
[ SpaceVim ] [12:18:49] [ 602.653] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:18:49] [ 602.677] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:18:49] [ 602.677] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [12:18:50] [ 602.769] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [12:18:50] [ 602.769] [  Info ] statusline build-in section hunks has been changed!
[ SpaceVim ] [12:19:28] [ 641.093] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:19:28] [ 641.115] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:19:28] [ 641.115] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [12:19:28] [ 641.210] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [12:19:28] [ 641.210] [  Info ] statusline build-in section hunks has been changed!
[ SpaceVim ] [12:21:45] [ 777.996] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [12:21:45] [ 778.019] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [12:21:45] [ 778.019] [  Info ] the func has been added to mode:paste-mode
[ SpaceVim ] [12:21:45] [ 778.111] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [12:21:45] [ 778.111] [  Info ] statusline build-in section hunks has been changed!
```
</details>

303 lines yanked into "+

## Screenshots
![Screenshot 2023-04-17 121123](https://user-images.githubusercontent.com/1885938/232405080-4f1cbc08-0a25-41c5-8b33-da7504108001.png)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.
