### ISSUE TITLE
filemanager set to nvim-tree. The cursor is on the the nvim-tree side instead of the start page when opening.

### ISSUE THREAD

**Issue by ChasingZenith** [wsdjeg/SpaceVim#4848]
## Expected behavior, english is required
When using `nvim-tree` and starting nvim, the cursor appears on the nvim-tree side but not the start page side
## The reproduce ways from Vim starting (Required!)
set option `filemanager="nvim-tree"`. Open neovim.

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'latexconfig#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'newpaper'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = [['#fafafa', '#50a14f', 71, 255], ['#494b53', '#d3d3d3', 251, 23], ['#494b53', '#d3d3d3', 251, 23], ['#f0f0f0', 254], ['#fafafa', '#0184bc', 255, 31], ['#fafafa', '#a626a4', 255, 127], ['#fafafa', '#a626a4', 255, 127], ['#fafafa', '#4078f2', 255, 33], ['#fafafa', '#e45649', 255, 166]]
  custom_plugins = [['williamboman/mason.nvim', {'name': 'williamboman/mason.nvim', 'merge': 0, 'overwrite': 1}], ['williamboman/mason-lspconfig.nvim', {'name': 'williamboman/mason-lspconfig.nvim', 'merge': 0, 'overwrite': 1}], ['neovim/nvim-lspconfig', {'name': 'neovim/nvim-lspconfig', 'merge': 0, 'overwrite': 1}], ['brymer-meneses/grammar-guard.nvim', {'name': 'brymer-meneses/grammar-guard.nvim', 'merge': 0, 'overwrite': 1}], ['nvimdev/lspsaga.nvim', {'on_lua': 'lspsaga', 'name': 'nvimdev/lspsaga.nvim', 'on_event': 'LspAttach', 'merge': 0, 'overwrite': 1}], ['nvim-treesitter/nvim-treesitter', {'name': 'nvim-treesitter/nvim-treesitter', 'overwrite': 1}], ['nvim-treesitter/playground', {'name': 'nvim-treesitter/playground', 'overwrite': 1}], ['nvim-treesitter/nvim-treesitter-context', {'name': 'nvim-treesitter/nvim-treesitter-context', 'overwrite': 1}], ['p00f/nvim-ts-rainbow', {'name': 'p00f/nvim-ts-rainbow', 'overwrite': 1}], ['ferrine/md-img-paste.vim', {'name': 'ferrine/md-img-paste.vim', 'merged': 0, 'on_ft': ['markdown'], 'overwrite': 1}], ['frabjous/knap', {'on_lua': ['knaphelper'], 'name': 'frabjous/knap', 'merged': 0, 'on_ft': ['tex'], 'overwrite': 1}], ['ChasingZenith/zyt-snippet', {'name': 'ChasingZenith/zyt-snippet', 'overwrite': 1}], ['jbyuki/nabla.nvim', {'on_lua': 'nabla', 'name': 'jbyuki/nabla.nvim', 'on_ft': ['markdown'], 'overwrite': 1}], ['rcarriga/nvim-notify', {'on_lua': 'notify', 'repo': 'rcarriga/nvim-notify', 'overwrite': 1}], ['yorik1984/newpaper.nvim', {'repo': 'yorik1984/newpaper.nvim', 'overwrite': 1}], ['Shougo/echodoc.vim', {'on_event': 'CompleteDone', 'repo': 'Shougo/echodoc.vim', 'loadconf_before': 1, 'on_cmd': ['EchoDocEnable', 'EchoDocDisable'], 'merged': 0, 'overwrite': 1}], ['deathlyfrantic/deoplete-spell', {'repo': 'deathlyfrantic/deoplete-spell', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/user/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['nvim-cmp', 'cmp-buffer', 'cmp-cmdline', 'cmp-nvim-lsp', 'cmp-path', 'cmp-neosnippet', 'vnote', 'dracula', 'rainbow']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nvim-tree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/user/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'telescope-ultisnips.nvim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='nil'
  auto_completion_tab_key_behavior='smart'
  autocomplete_parens=0
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="colorscheme"
[[layers]]
  name="tmux"
[[layers]]
  name="sudo"
[[layers]]
  name="git"
[[layers]]
  name="tools"
[[layers]]
  name="lsp"
[[layers]]
  name="chinese"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#latex"
[[layers]]
  name="telescope"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.9.0
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `colorscheme`:ok
  - `tmux`:ok
  - `sudo`:ok
  - `git`:ok
  - `tools`:ok
  - `lsp`:ok
  - `chinese`:ok
  - `lang#markdown`:ok
  - `lang#latex`:ok
  - `telescope`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/user/.SpaceVim/
[ SpaceVim ] [00:00:00:139] [ Info  ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [00:00:00:139] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:140] [ Info  ] options init done
[ SpaceVim ] [00:00:00:150] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:150] [ Info  ] global_dir is: /home/user/.SpaceVim.d/
[ SpaceVim ] [00:00:00:150] [ Info  ] find global config: /home/user/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:151] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:161] [ Info  ] current directory is $HOME, skip local config
[ SpaceVim ] [00:00:00:162] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [00:00:00:444] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:477] [ Info  ] Load projects cache from: /home/user/.cache/SpaceVim/projects.json
[  project ] [00:00:00:529] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:00:530] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [00:00:00:591] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:591] [ Info  ] switch to project:[user]
[  project ] [00:00:00:591] [ Info  ]        rootdir is:/home/user/

```
</details>
