### ISSUE TITLE
Update LSP doc page with full exact list of all supported LSP clients in `enabled_clients` section

### ISSUE THREAD

**Issue by lucomsky** [wsdjeg/SpaceVim#4854]
**Is your feature request related to a problem? Please describe.**
We have a nice page about LSP here: https://spacevim.org/layers/language-server-protocol/ but have lack of corresponding list of possible values in `enabled_clients` see below example:
```toml
[[layers]]
    name = 'lsp'
    enabled_clients = [
        'tsserver',
        'clangd'
    ]
```
How should I know that for `python-language-server` it is `pylsp` and for `typescript-language-server` it is `tsserver`?

**Describe the solution you'd like**
Add info for possible values in `enabled_clients` and there real exe name and link to the plugin/project.

**Describe alternatives you've considered**
Add helper command like `:LspSupportedClients` with full info on supported names and plugins.
