### ISSUE TITLE
Opening a file in a split with telescope and autochdir opens a non existent file

### ISSUE THREAD

**Issue by autra** [wsdjeg/SpaceVim#4858]
## Expected behavior

When `autochdir` is activated, and trying to open a file in a split in telescope with ctrl+x or v, the selected file is opened correctly

## Actual behavior

The opened file doesn't exist (the path is wrong)

## The reproduce ways from Vim starting (Required!)

This example can be reproduced in the root of this repository (`SpaceVim`):

- open a file in a subfolder: `vim wiki/async.sh` for instance
- use `ctrl+p` to open telescope
- select a file to open, ex `README.md`
- type `ctrl+x` to open it in a split

The opened file is empty. The `:file` command returns `README.md`, and the `:pwd` command returns `wiki/`. It wrongly prepends the old current dir to the path apparently...

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'autumnleaf'
  colorscheme_bg = 'light'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['MaxMEllon/vim-jsx-pretty', {'name': 'MaxMEllon/vim-jsx-pretty', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/augustin/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/augustin/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-racer'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', '.clang', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'arrow'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="sudo"
[[layers]]
  name="treesitter"
[[layers]]
  name="telescope"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rls']}
  filetypes=['rust']
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#python"
  python_file_head=[]
[[layers]]
  name="lang#c"
  enable_clang_syntax_highlight=1
[[layers]]
  name="git"
  git-plugin='fugitive'
[[layers]]
  name="colorscheme"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#rst"
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
[[layers]]
  name="lang#rust"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(/usr/bin/nvim)
version: NVIM v0.8.3
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `sudo`:ok
  - `treesitter`:ok
  - `telescope`:ok
  - `lsp`:ok
  - `lang#javascript`:ok
  - `lang#python`:ok
  - `lang#c`:ok
  - `git`:ok
  - `colorscheme`:ok
  - `lang#markdown`:ok
  - `lang#rst`:ok
  - `debug`:ok
  - `lang#rust`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/augustin/.SpaceVim/
[ SpaceVim ] [00:00:00:153] [ Info  ] Startup with argv: 2
[ SpaceVim ] [00:00:00:153] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:154] [ Info  ] options init done
[ SpaceVim ] [00:00:00:166] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:167] [ Info  ] global_dir is: /home/augustin/.SpaceVim.d/
[ SpaceVim ] [00:00:00:167] [ Info  ] find global config: /home/augustin/.SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:167] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:173] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:174] [ Info  ] find local conf: /home/augustin/.SpaceVim/.SpaceVim.d/init.vim
[  project ] [00:00:00:315] [ Info  ] Load projects cache from: /home/augustin/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:398] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:640] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [00:00:00:641] [ Info  ]         (.git/):/home/augustin/.SpaceVim/
[ SpaceVim ] [00:00:00:649] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:649] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:00:649] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:01:899] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:01:899] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:06:027] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:06:027] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:06:163] [ Info  ]         (.git/):/home/augustin/.SpaceVim/
[  project ] [00:00:06:163] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:06:163] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:47:271] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:47:271] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:47:900] [ Info  ]         (.git/):/home/augustin/.SpaceVim/
[  project ] [00:00:47:901] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:47:901] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:58:800] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:58:800] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:00:58:802] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:00:58:802] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:01:02:857] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:01:02:857] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:01:06:240] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:01:06:240] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:01:06:678] [ Info  ]         (.git/):/home/augustin/.SpaceVim/
[  project ] [00:01:06:679] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:01:06:679] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/
[  project ] [00:02:31:672] [ Info  ] switch to project:[.SpaceVim]
[  project ] [00:02:31:672] [ Info  ]        rootdir is:/home/augustin/.SpaceVim/

```
</details>
