### ISSUE TITLE
Selected formatting of code (at least for C file types) formats the full buffer instead of just the selection

### ISSUE THREAD

**Issue by m-fonseca** [wsdjeg/SpaceVim#4864]
## Expected behavior, english is required

When I have selected c code, I expect only the formatting of the selected code to format, but instead the whole file is formatted.  The docs indicate selected formatting should work.  I suspect this has nothing to do with c, but probably all filetypes have the same problem?

## The reproduce ways from Vim starting (Required!)

Open a c file that needs formatting.  Select only a portion of it, and do the `SPC b f`, to format the selection.  Instead, it formats the whole file.  If you instead select your text and do :'<,'>Neoformat, it correctly formats.

Workaround for me is to just add
```
   vmap [SPC]bf :Neoformat<CR> 
```
to my custom vimscript file.

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/test/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/test/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dispatch'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="tmux"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#c"
[[layers]]
  name="git"
  git_plugin='fugitive'
[[layers]]
  name="treesitter"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvimaYV9Oj/usr/bin/nvim)
version: NVIM v0.9.0
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `fzf`:ok
  - `tmux`:ok
  - `lang#markdown`:ok
  - `lang#sh`:ok
  - `lang#c`:ok
  - `git`:ok
  - `treesitter`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/test/.config/SpaceVim/
[ SpaceVim ] [00:00:00:054] [ Info  ] Startup with argv: 2
[ SpaceVim ] [00:00:00:054] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:054] [ Info  ] options init done
[ SpaceVim ] [00:00:00:057] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:057] [ Info  ] global_dir is: /home/test/.config/SpaceVim.d/
[ SpaceVim ] [00:00:00:057] [ Info  ] find global config: /home/test/.config/SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:057] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:059] [ Info  ] current directory is $HOME, skip local config
[  project ] [00:00:00:111] [ Info  ] Load projects cache from: /home/test/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:124] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:800] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[ SpaceVim ] [00:00:00:802] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:802] [ Info  ] switch to project:[test]
[  project ] [00:00:00:802] [ Info  ]        rootdir is:/home/test/
[ neoformat ] [00:01:42:228] [ Info  ] executable: uncrustify is not an executable
[ neoformat ] [00:01:42:229] [ Info  ] table: 0x7fdb21b239b0
[ neoformat ] [00:01:42:229] [ Info  ] clang-format -assume-filename=test.c 2> /dev/null
[ neoformat ] [00:01:42:229] [ Info  ] using stdin
[ neoformat ] [00:01:42:242] [ Info  ] table: 0x7fdb21d75a08
[ neoformat ] [00:01:42:242] [ Info  ] table: 0x7fdb21b0e578
[ neoformat ] [00:01:42:242] [ Info  ] 0

```
</details>
