### ISSUE TITLE
Todo manager is not working properly

### ISSUE THREAD

**Issue by jscolaire** [wsdjeg/SpaceVim#4867]
## Expected behavior, english is required

As I read in the documentation Todo manager I can write tags in my code for list task pending or questions or fixme procedures managed by todo manager.

## The reproduce ways from Vim starting (Required!)

The simple below code fails in todo manager according to documentation and only shows `@tag` and an unique word.

~~~
#!/usr/bin/env python
# -*- coding: utf-8 -*-

def main():
    print("this is a test for SpaceVim todo manager")
    #@todo this is a test for SpaceVim todo manager
    #@todo|this is a test for SpaceVim todo manager
    # @todo this is a test for SpaceVim todo manager
    # @todor| this is a test for SpaceVim todo manager
    #@fixme this is a test for SpaceVim todo manager
    #@fixme|this is a test for SpaceVim todo manager

if __name__ == '__main__':
    main()
~~~

## Output of the `:SPDebugInfo!`
~~~
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['Glench/Vim-Jinja2-Syntax', {'repo': 'Glench/Vim-Jinja2-Syntax', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/ac/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/ac/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dockerfile'
  project_auto_root = 0
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="colorscheme"
[[layers]]
  name="gtags"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
  emmet_filetyps=['html']
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#python"
[[layers]]
  name="git"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lepture/vim-jinja"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vi(/usr/bin/vim.nox)
version: 900
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `fzf`:ok
  - `colorscheme`:ok
  - `gtags`:ok
  - `lang#sh`:ok
  - `lang#extra`:ok
  - `lang#html`:ok
  - `lang#ruby`:ok
  - `lang#python`:ok
  - `git`:ok
  - `lang#dockerfile`:ok
  - `lepture/vim-jinja`: can not find function: SpaceVim#layers#lepture/vim-jinja#health()

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [08:56:49] [   0.000] [  Info ] Loading SpaceVim from: /home/ac/.SpaceVim/
[ SpaceVim ] [08:56:49] [   0.026] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [08:56:49] [   0.027] [  Info ] Startup with argv: ['vi', 'main.py']
[ SpaceVim ] [08:56:49] [   0.039] [  Info ] start loading global config >>>
[ SpaceVim ] [08:56:49] [   0.039] [  Info ] global_dir is: /home/ac/.SpaceVim.d/
[ SpaceVim ] [08:56:49] [   0.039] [  Info ] find global config: /home/ac/.SpaceVim.d/init.toml
[ SpaceVim ] [08:56:49] [   0.040] [  Info ] start to apply config [glob]
[ SpaceVim ] [08:56:49] [   0.046] [  Info ] start loading local config >>>
[ SpaceVim ] [08:56:49] [   0.046] [  Info ] Could not find project local config
[ SpaceVim ] [08:56:49] [   0.109] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [08:56:49] [   0.166] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [08:56:49] [   0.166] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [08:56:49] [   0.237] [  Info ] Load projects cache from: /home/ac/.cache/SpaceVim/projects.json
[ SpaceVim ] [08:56:49] [   0.354] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [08:56:50] [   0.723] [  Info ] run root changed callback on VimEnter!
[ SpaceVim ] [08:57:27] [  38.240] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [08:57:27] [  38.261] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [08:57:27] [  38.261] [  Info ] the func has been added to mode:paste-mode
```
</details>

~~~
## Screenshots
![imagen](https://github.com/SpaceVim/SpaceVim/assets/1184251/ee096c77-389e-4953-a44a-29e6f8ccb12f)

**vs**

![imagen](https://github.com/SpaceVim/SpaceVim/assets/1184251/e00cbc88-fd8e-47f7-b713-3533960fc0d3)

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

**Comment by wsdjeg** [comment]
you need to run `:SPDebugInfo!` after open todomanager, I can not see any info about todo manager.

**Comment by jscolaire** [comment]
Here SPDebuginfo with Todo manager open

~~~
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['Glench/Vim-Jinja2-Syntax', {'repo': 'Glench/Vim-Jinja2-Syntax', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/ac/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = ''
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/ac/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dockerfile'
  project_auto_root = 0
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerSh
ell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.1.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```


### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="colorscheme"
[[layers]]
  name="gtags"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
  emmet_filetyps=['html']
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#python"
[[layers]]
  name="git"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lepture/vim-jinja"
```


### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need recompile your vim with +clipboard support.
SpaceVim environment check report:
Current progpath: vi(/usr/bin/vim.nox)
version: 900
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `fzf`:ok
  - `colorscheme`:ok
  - `gtags`:ok
  - `lang#sh`:ok
  - `lang#extra`:ok
  - `lang#html`:ok
  - `lang#ruby`:ok
  - `lang#python`:ok
  - `git`:ok
  - `lang#dockerfile`:ok
  - `lepture/vim-jinja`: can not find function: SpaceVim#layers#lepture/vim-jinja#health()

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [09:29:05] [   0.000] [  Info ] Loading SpaceVim from: /home/ac/.SpaceVim/
[ SpaceVim ] [09:29:05] [   0.034] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [09:29:05] [   0.034] [  Info ] Startup with argv: ['vi', 'main.py']
[ SpaceVim ] [09:29:05] [   0.051] [  Info ] start loading global config >>>
[ SpaceVim ] [09:29:05] [   0.051] [  Info ] global_dir is: /home/ac/.SpaceVim.d/
[ SpaceVim ] [09:29:05] [   0.051] [  Info ] find global config: /home/ac/.SpaceVim.d/init.toml
[ SpaceVim ] [09:29:05] [   0.052] [  Info ] start to apply config [glob]
[ SpaceVim ] [09:29:05] [   0.060] [  Info ] start loading local config >>>
[ SpaceVim ] [09:29:05] [   0.060] [  Info ] Could not find project local config
[ SpaceVim ] [09:29:05] [   0.150] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:29:05] [   0.231] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:29:05] [   0.231] [  Info ] the func has been added to mode:paste-mode
[   rooter ] [09:29:05] [   0.323] [  Info ] Load projects cache from: /home/ac/.cache/SpaceVim/projects.json
[ SpaceVim ] [09:29:05] [   0.470] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [09:29:06] [   0.915] [  Info ] run root changed callback on VimEnter!
[   rooter ] [09:31:01] [ 116.437] [  Info ] Start to find root for: /home/ac/projects/flask/main.py
[    ctags ] [09:31:01] [ 116.442] [  Info ] start to check ctags version
[    ctags ] [09:31:01] [ 116.508] [  Info ] ctags version checking done:
[    ctags ] [09:31:01] [ 116.508] [  Info ]       ctags bin:ctags
[    ctags ] [09:31:01] [ 116.508] [  Info ] update ctags database for /home/ac/projects/flask
[    ctags ] [09:31:01] [ 116.516] [  Info ] ctags database updated successfully
[   rooter ] [09:31:13] [ 127.687] [  Info ] Start to find root for: /home/ac/projects/flask/main.py
[    ctags ] [09:31:13] [ 127.693] [  Info ] update ctags database for /home/ac/projects/flask
[    ctags ] [09:31:13] [ 127.709] [  Info ] ctags database updated successfully
[   rooter ] [09:31:19] [ 134.530] [  Info ] Start to find root for: /home/ac/projects/flask/main.py
[    ctags ] [09:31:20] [ 134.538] [  Info ] update ctags database for /home/ac/projects/flask
[    ctags ] [09:31:20] [ 134.564] [  Info ] ctags database updated successfully
[     todo ] [09:31:23] [ 137.951] [  Info ] cmd: ['grep', '-inHr', '-e', '@fixme\b\|@question\b\|@todo\b\|@idea\b', '.']
[     todo ] [09:31:23] [ 137.952] [  Info ]    labels_partten: \v\@fixme>\|\@question>\|\@todo>\|\@idea>
[     todo ] [09:31:23] [ 137.953] [  Info ] jobid: 1
[     todo ] [09:31:23] [ 137.960] [  Info ] stdout: ./spdebuginfo.txt:5:    #@todo this is a test
[     todo ] [09:31:23] [ 137.960] [  Info ] stdout: ./spdebuginfo.txt:6:    # @todo this is a test
[     todo ] [09:31:23] [ 137.961] [  Info ] stdout: ./spdebuginfo.txt:7:    #@todo|this is a test
[     todo ] [09:31:23] [ 137.961] [  Info ] stdout: ./main.py:6:    #@todo this is a test
[     todo ] [09:31:23] [ 137.961] [  Info ] stdout: ./main.py:7:    # @todo this is a test
[     todo ] [09:31:23] [ 137.962] [  Info ] stdout: ./main.py:8:    #@todo|this is a test
[     todo ] [09:31:23] [ 137.962] [  Info ] todomanager exit: 0
[     todo ] [09:31:50] [ 165.162] [  Info ] cmd: ['grep', '-inHr', '-e', '@fixme\b\|@question\b\|@todo\b\|@idea\b', '.']
[     todo ] [09:31:50] [ 165.162] [  Info ]    labels_partten: \v\@fixme>\|\@question>\|\@todo>\|\@idea>
[    ctags ] [09:31:20] [ 134.538] [  Info ] update ctags database for /home/ac/projects/flask
[    ctags ] [09:31:20] [ 134.564] [  Info ] ctags database updated successfully
[     todo ] [09:31:23] [ 137.951] [  Info ] cmd: ['grep', '-inHr', '-e', '@fixme\b\|@question\b\|@todo\b\|@idea\b', '.']
[     todo ] [09:31:23] [ 137.952] [  Info ]    labels_partten: \v\@fixme>\|\@question>\|\@todo>\|\@idea>
[     todo ] [09:31:23] [ 137.953] [  Info ] jobid: 1
[     todo ] [09:31:23] [ 137.960] [  Info ] stdout: ./spdebuginfo.txt:5:    #@todo this is a test
[     todo ] [09:31:23] [ 137.960] [  Info ] stdout: ./spdebuginfo.txt:6:    # @todo this is a test
[     todo ] [09:31:23] [ 137.961] [  Info ] stdout: ./spdebuginfo.txt:7:    #@todo|this is a test
[     todo ] [09:31:23] [ 137.961] [  Info ] stdout: ./main.py:6:    #@todo this is a test
[     todo ] [09:31:23] [ 137.961] [  Info ] stdout: ./main.py:7:    # @todo this is a test
[     todo ] [09:31:23] [ 137.962] [  Info ] stdout: ./main.py:8:    #@todo|this is a test
[     todo ] [09:31:23] [ 137.962] [  Info ] todomanager exit: 0
[     todo ] [09:31:50] [ 165.162] [  Info ] cmd: ['grep', '-inHr', '-e', '@fixme\b\|@question\b\|@todo\b\|@idea\b', '.']
[     todo ] [09:31:50] [ 165.162] [  Info ]    labels_partten: \v\@fixme>\|\@question>\|\@todo>\|\@idea>
[     todo ] [09:31:50] [ 165.164] [  Info ] jobid: 2
[     todo ] [09:31:50] [ 165.169] [  Info ] stdout: ./main.py:6:    #@todo this is a test
[     todo ] [09:31:50] [ 165.169] [  Info ] stdout: ./main.py:7:    # @todo this is a test
[     todo ] [09:31:50] [ 165.169] [  Info ] stdout: ./main.py:8:    #@todo|this is a test
[     todo ] [09:31:50] [ 165.169] [  Info ] todomanager exit: 0
[ SpaceVim ] [09:31:59] [ 174.157] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:31:59] [ 174.183] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:31:59] [ 174.184] [  Info ] the func has been added to mode:paste-mode
[     todo ] [09:32:45] [ 219.936] [  Info ] cmd: ['grep', '-inHr', '-e', '@fixme\b\|@question\b\|@todo\b\|@idea\b', '.']
[     todo ] [09:32:45] [ 219.936] [  Info ]    labels_partten: \v\@fixme>\|\@question>\|\@todo>\|\@idea>
[     todo ] [09:32:45] [ 219.938] [  Info ] jobid: 3
[     todo ] [09:32:45] [ 219.943] [  Info ] stdout: ./main.py:6:    #@todo this is a test
[     todo ] [09:32:45] [ 219.943] [  Info ] stdout: ./main.py:7:    # @todo this is a test
[     todo ] [09:32:45] [ 219.944] [  Info ] stdout: ./main.py:8:    #@todo|this is a test
[     todo ] [09:32:45] [ 219.944] [  Info ] todomanager exit: 0
[ SpaceVim ] [09:32:49] [ 224.204] [  Info ] the func has been added to mode:syntax-checking
[ SpaceVim ] [09:32:49] [ 224.231] [  Info ] the func has been added to mode:spell-checking
[ SpaceVim ] [09:32:49] [ 224.232] [  Info ] the func has been added to mode:paste-mode
```
</details>
~~~
