### ISSUE TITLE
An additional window is showing when terminal window receives focus

### ISSUE THREAD

**Issue by necrosis** [wsdjeg/SpaceVim#4871]
Arch's package gvim==9.0.1572-1
When I'm moving my mouse of the window and then move it in, vim opens an additional window below, with some text. I don't know what it showing, but with a huge project vim hangs for about 10 seconds every time. Can't reproduce with nvim though.
How can I disable this behavior 

## Screenshots

![20230605_12h49m44s_grim](https://github.com/SpaceVim/SpaceVim/assets/1309252/43b94f40-46cc-4085-a943-87e00c7134a2)

![20230605_12h44m11s_grim](https://github.com/SpaceVim/SpaceVim/assets/1309252/4c58d73f-9d71-43a5-88e9-37d7ef920614)

## Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'gitbindings#after'
  bootstrap_before = 'gitbindings#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/necrosis/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/necrosis/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-tmux'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'curve'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
  show_cursor_error=0
  lint_on_save=0
[[layers]]
  name="format"
[[layers]]
  name="edit"
  autosave_timeout=300000
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="debug"
  debugger_plugin='vimspector'
[[layers]]
  name="lang#c"
  enable=1
  enable_clang_syntax_highlight=1
[[layers]]
  name="lang#python"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#kotlin"
[[layers]]
  name="lang#lsp"
[[layers]]
  name="fzf"
[[layers]]
  name="tools"
[[layers]]
  name="git"
  git_plugin='fugitive'
[[layers]]
  name="gtags"
  gtagslabel='pygments'
  auto_update=0
[[layers]]
  name="colorscheme"
[[layers]]
  name="tmux"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim)
version: 900
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `default`: can not find function: SpaceVim#layers#default#health()
  - `shell`:ok
  - `debug`:ok
  - `lang#c`:ok
  - `lang#python`:ok
  - `lang#sh`:ok
  - `lang#kotlin`:ok
  - `lang#lsp`: can not find function: SpaceVim#layers#lang#lsp#health()
  - `fzf`:ok
  - `tools`:ok
  - `git`:ok
  - `gtags`:ok
  - `colorscheme`:ok
  - `tmux`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:49:25] [   0.000] [  Info ] Loading SpaceVim from: /home/necrosis/.SpaceVim/
[ SpaceVim ] [12:49:25] [   0.051] [  Info ] Startup with argv: 2
[ SpaceVim ] [12:49:25] [   0.057] [  Info ] start loading global config >>>
[ SpaceVim ] [12:49:25] [   0.057] [  Info ] global_dir is: /home/necrosis/.SpaceVim.d/
[ SpaceVim ] [12:49:25] [   0.057] [  Info ] find global config: /home/necrosis/.SpaceVim.d/init.toml
[ SpaceVim ] [12:49:25] [   0.057] [  Info ] start to apply config [glob]
[ SpaceVim ] [12:49:25] [   0.061] [  Info ] start loading local config >>>
[ SpaceVim ] [12:49:25] [   0.061] [  Info ] Could not find project local config
[   rooter ] [12:49:25] [   0.144] [  Info ] Load projects cache from: /home/necrosis/.cache/SpaceVim/projects.json
[ SpaceVim ] [12:49:25] [   0.199] [  Info ] finished loading SpaceVim!
[   rooter ] [12:49:25] [   0.300] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [12:49:25] [   0.301] [  Info ] Start to find root for: /home/necrosis/.SpaceVim.d/init.toml
[   rooter ] [12:49:25] [   0.304] [  Info ] Start to find root for: /home/necrosis/.SpaceVim.d/init.toml
[ SpaceVim ] [12:49:25] [   0.307] [  Info ] run root changed callback on VimEnter!
```
</details>
