### ISSUE TITLE
Tagbar is not working

### ISSUE THREAD

**Issue by m-fonseca** [wsdjeg/SpaceVim#4872]
## Expected behavior, english is recommend

Expect tagbar to show up, but it gives the error:

    :TagbarToggle

    E117: Unknown function: tagbar#ToggleWindow

I'm trying this on a c file.

## Environment Information

- OS: linux
- vim version: -
- neovim version: 0.9.0
- SpaceVim version: 2.2.0-dev
- SpaceVim status: 1061082e

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

## Output of the `:SPDebugInfo!`

Neomake is enabled.
failed to enable spell check
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['ibhagwan/fzf-lua', {'repo': 'ibhagwan/fzf-lua', 'merged': 0, 'overwrite': 1}], ['ojroques/vim-oscyank', {'repo': 'ojroques/vim-oscyank', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/test/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/test/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'nvim-treesitter'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="lsp"
  enabled_clients=['bashls', 'ccls']
  filetypes=['c', 'sh', 'python']
[[layers]]
  name="tmux"
[[layers]]
  name="lang#markdown"
  enabled_formater=['prettier']
  listItemChar='*'
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#c"
[[layers]]
  name="git"
  git_plugin='fugitive'
[[layers]]
  name="treesitter"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvimQpiYu3/usr/bin/nvim)
version: NVIM v0.9.0
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      Failed : to support +python3, you need run `pip3 install neovim`
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `fzf`:ok
  - `lsp`:ok
  - `tmux`:ok
  - `lang#markdown`:ok
  - `lang#sh`:ok
  - `lang#c`:ok
  - `git`:ok
  - `treesitter`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [00:00:00:000] [ Info  ] Loading SpaceVim from: /home/test/.config/SpaceVim/
[ SpaceVim ] [00:00:00:016] [ Info  ] Startup with argv: 2
[ SpaceVim ] [00:00:00:016] [ Info  ] init default vim options
[ SpaceVim ] [00:00:00:016] [ Info  ] options init done
[ SpaceVim ] [00:00:00:020] [ Info  ] start loading global config >>>
[ SpaceVim ] [00:00:00:020] [ Info  ] global_dir is: /home/test/.config/SpaceVim.d/
[ SpaceVim ] [00:00:00:020] [ Info  ] find global config: /home/test/.config/SpaceVim.d/init.toml
[ SpaceVim ] [00:00:00:020] [ Info  ] start to apply config [glob]
[ SpaceVim ] [00:00:00:025] [ Info  ] start loading local config >>>
[ SpaceVim ] [00:00:00:025] [ Info  ] Could not find project local config
[  project ] [00:00:00:093] [ Info  ] Load projects cache from: /home/test/.cache/SpaceVim/projects.json
[ SpaceVim ] [00:00:00:111] [ Info  ] finished loading SpaceVim!
[  project ] [00:00:00:172] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [00:00:00:172] [ Info  ]         (.git/):/home/test/work/
[ SpaceVim ] [00:00:00:176] [ Info  ] run root changed callback on VimEnter!
[  project ] [00:00:00:176] [ Info  ] switch to project:[lp]
[  project ] [00:00:00:176] [ Info  ]        rootdir is:/home/test/work/
[  FlyGrep ] [00:13:28:362] [ Info  ] FlyGrep startting ===========================
[  FlyGrep ] [00:13:28:362] [ Info  ]    executable    : rg
[  FlyGrep ] [00:13:28:362] [ Info  ]    option        : ['--hidden', '--no-heading', '--color=never', '--with-filename', '--line-number', '--column', '-g', '!.git']
[  FlyGrep ] [00:13:28:362] [ Info  ]    r_option      : []
[  FlyGrep ] [00:13:28:362] [ Info  ]    files         : ['/home/test/.config/SpaceVim/doc/SpaceVim.txt', '/home/test/.config/SpaceVim/bundle/tagbar/doc/tagbar.txt', '/home/test/.config/SpaceVim/bundle/neomake/doc/neomake.txt', '/home/test/.cache/vimfiles/repos/github.com/junegunn/fzf/doc/fzf.txt', '/home/test/.config/SpaceVim/bundle/vim-grammarous/doc/grammarous.txt', '/home/test/.config/SpaceVim/bundle/neomru.vim/doc/neomru.txt', '/home/test/.config/SpaceVim/bundle/vim-textobj-line/doc/textobj-line.txt', '/home/test/.cache/vimfiles/repos/github.com/prabirshrestha/asyncomplete.vim/doc/asyncomplete.txt', '/home/test/.config/SpaceVim/bundle/vim-cursorword/doc/cursorword.txt', '/home/test/.config/SpaceVim/bundle/nvim-lspconfig-0.1.4/doc/lspconfig.txt', '/home/test/.config/SpaceVim/bundle/nvim-lspconfig-0.1.4/doc/server_configurations.txt', '/home/test/.cache/vimfiles/repos/github.com/ibhagwan/fzf-lua/doc/fzf-lua.txt', '/home/test/.config/SpaceVim/bundle/hop.nvim/doc/hop.txt', '/home/test/.cache/vimfiles/repos/github.com/airblade/vim-gitgutter/doc/gitgutter.txt', '/home/test/.config/SpaceVim/bundle/vim-textobj-indent/doc/textobj-indent.txt', '/home/test/.config/SpaceVim/bundle/nvim-treesitter/doc/nvim-treesitter.txt', '/home/test/.cache/vimfiles/repos/github.com/SpaceVim/fzf-neoyank/doc/fzf_neoyank.txt', '/home/test/.config/SpaceVim/bundle/vim-matchup/doc/matchup.txt', '/home/test/.config/SpaceVim/bundle/vim-dispatch/doc/dispatch.txt', '/home/test/.config/SpaceVim/bundle/CompleteParameter.vim/doc/complete_parameter.txt', '/home/test/.cache/vimfiles/repos/github.com/edkolev/tmuxline.vim/doc/tmuxline.txt', '/home/test/.config/SpaceVim/bundle/delimitMate/doc/delimitMate.txt', '/home/test/.config/SpaceVim/bundle/vim-expand-region/doc/expand_region.txt', '/home/test/.config/SpaceVim/bundle/vim-textobj-user/doc/textobj-user.txt', '/home/test/.cache/vimfiles/repos/github.com/ojroques/vim-oscyank/doc/oscyank.txt', '/home/test/.config/SpaceVim/bundle/indent-blankline.nvim/doc/indent_blankline.txt', '/home/test/.config/SpaceVim/bundle/nerdtree/doc/NERDTree.txt', '/home/test/.config/SpaceVim/bundle/open-browser.vim/doc/openbrowser.txt', '/home/test/.config/SpaceVim/bundle/tabular/doc/Tabular.txt', '/home/test/.config/SpaceVim/bundle/vim-startify/doc/startify.txt', '/home/test/.config/SpaceVim/bundle/neoyank.vim/doc/neoyank.txt', '/home/test/.config/SpaceVim/bundle/vim-fugitive/doc/fugitive.txt', '/home/test/.config/SpaceVim/bundle/dein.vim/doc/dein.txt', '/home/test/.config/SpaceVim/bundle/vim-table-mode/doc/table-mode.txt', '/home/test/.config/SpaceVim/bundle/neoformat/doc/neoformat.txt', '/home/test/.config/SpaceVim/bundle/vim-textobj-entire/doc/textobj-entire.txt', '/home/test/.config/SpaceVim/bundle/vim-surround/doc/surround.txt', '/home/test/.config/SpaceVim/bundle/clever-f.vim/doc/clever_f.txt', '/home/test/.config/SpaceVim/bundle/nerdcommenter/doc/NERD_commenter.txt', '/home/test/.config/SpaceVim/bundle/vim-better-whitespace/doc/better-whitespace.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/asyncomplete.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/deol.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/echodoc.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/fzf-lua.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/fzf.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/fzf_neoyank.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/gitgutter.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/oscyank.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/splitjoin.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/tmux.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/tmuxline.txt', '/home/test/.cache/vimfiles/.cache/init.vim/.dein/doc/vimshell.txt', '/home/test/.config/SpaceVim/bundle/dein.vim/doc/dein.txt']
...
[  FlyGrep ] [00:13:38:899] [ Info  ] flygrep job id is: 12
[  project ] [00:13:40:757] [ Info  ]         (.git/):/home/test/.config/SpaceVim/
[  project ] [00:13:40:758] [ Info  ] switch to project:[SpaceVim]
[  project ] [00:13:40:758] [ Info  ]        rootdir is:/home/test/.config/SpaceVim/
[  FlyGrep ] [00:13:40:806] [ Info  ] FlyGrep ending    ===========================

```
</details>

## Screenshots

If you have any screenshots for this issue please upload here. BTW you can use https://asciinema.org/ for recording video  in terminal.
