### ISSUE TITLE
[^OA and [^OB showing while scrolling with the mousewheel when the battery status bar indicator is set to autoload

### ISSUE THREAD

**Issue by tshazar** [wsdjeg/SpaceVim#4876]
## Expected behavior, english is required

You should be able to use the mouse scroll without escape characters displaying on screen (vim v9.0) or having the interface freeze (nvim v0.9.1)

## The reproduce ways from Vim starting (Required!)

OS: mac osx 13.4
terminal: alacrity 0.12.1
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 03 2023 16:11:47)
macOS version - arm64
Included patches: 1-1600
Compiled by Homebrew

create a config file ~/.SpaceVim.d/init.toml 
add options as noted 

[options]
  statusline_right = [
    'battery status' # Causes ^[OA and ^[OB while scrolling with mouse
  ]

restart vim and load a file scroll using the mouse wheel

FYI ... nvim was also tested it does not show the same display error but freezes when the top and bottom of the pages are hit while scrolling with the mouse 

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

## Output of the `:SPDebugInfo!`
<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  automatic_update = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 0
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'dracula'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['ryanoasis/vim-devicons', {'repo': 'ryanoasis/vim-devicons', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/Users/dlovejoy/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '☒'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = ''
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/dlovejoy/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'helpful.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/', 'package.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'nil'
  statusline_left = ['winnr', 'input method', 'filename', 'major mode', 'minor mode lighters', 'version control info', 'vcs', 'hunks']
  statusline_right = ['syntax checking', 'whitespace', 'search status', 'search count', 'cursorpos', 'percentage', 'totallines', 'fileformat', 'date', 'time', 'battery status']
  statusline_separator = 'curve'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠️'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  enable_filetree_filetypeicon=1
  enable_filetree_gitstatus=1
  enable_smooth_scrolling=1
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="incsearch"
[[layers]]
  name="colorscheme"
[[layers]]
  name="git"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height='33%'
[[layers]]
  name="VersionControl"
  enable-gtm-status=1
[[layers]]
  name="gtags"
[[layers]]
  name="leaderf"
[[layers]]
  name="lang#batch"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#vim"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vi(vi)
version: 900
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `incsearch`:ok
  - `colorscheme`:ok
  - `git`:ok
  - `shell`:ok
  - `VersionControl`:ok
  - `gtags`:ok
  - `leaderf`:ok
  - `lang#batch`:ok
  - `lang#php`:ok
  - `lang#html`:ok
  - `lang#javascript`:ok
  - `lang#json`:ok
  - `lang#vim`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [17:04:15] [   0.000] [  Info ] Loading SpaceVim from: /Users/dlovejoy/.SpaceVim/
[ SpaceVim ] [17:04:15] [   0.015] [  Info ] Startup with argv: 2
[ SpaceVim ] [17:04:15] [   0.022] [  Info ] start loading global config >>>
[ SpaceVim ] [17:04:15] [   0.022] [  Info ] global_dir is: /Users/dlovejoy/.SpaceVim.d/
[ SpaceVim ] [17:04:15] [   0.022] [  Info ] find global config: /Users/dlovejoy/.SpaceVim.d/init.toml
[ SpaceVim ] [17:04:15] [   0.022] [  Info ] start to apply config [glob]
[ SpaceVim ] [17:04:15] [   0.026] [  Info ] start loading local config >>>
[ SpaceVim ] [17:04:15] [   0.026] [  Info ] Could not find project local config
[   rooter ] [17:04:15] [   0.107] [  Info ] Load projects cache from: /Users/dlovejoy/.cache/SpaceVim/projects.json
[   rooter ] [17:04:15] [   0.111] [  Info ] Start to find root for: /Users/dlovejoy/.SpaceVim.d/autoload/myspacevim.vim
[ SpaceVim ] [17:04:15] [   0.158] [  Info ] finished loading SpaceVim!
[   rooter ] [17:04:16] [   0.337] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [17:04:16] [   0.337] [  Info ] Start to find root for: /Users/dlovejoy/.SpaceVim.d/autoload/myspacevim.vim
[   rooter ] [17:04:16] [   0.344] [  Info ] Start to find root for: /Users/dlovejoy/.SpaceVim.d/autoload/myspacevim.vim
[ SpaceVim ] [17:04:16] [   0.347] [  Info ] run root changed callback on VimEnter!
[ SpaceVim ] [17:04:16] [   0.437] [ Error ] failed to call bootstrap_after function: myspacevim#after
[ SpaceVim ] [17:04:16] [   0.437] [ Error ]        exception: Vim(#):E488: Trailing characters: call SpaceVim#layers#core#statusline#toggle_section(:   # call SpaceVim#layers#core#statusline#toggle_section(
[ SpaceVim ] [17:04:16] [   0.437] [ Error ]        throwpoint: VimEnter Autocommands for "*"..function SpaceVim#autocmds#VimEnter[17]..myspacevim#after, line 9
[ SpaceVim ] [17:04:25] [   9.944] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [17:04:25] [   9.944] [  Info ] statusline build-in section hunks has been changed!
[   rooter ] [17:04:25] [   9.947] [  Info ] Start to find root for: /Users/dlovejoy/.SpaceVim.d/autoload/myspacevim.vim
```
</details>

## Screenshots

<img width="1518" alt="image" src="https://github.com/SpaceVim/SpaceVim/assets/5994486/35579d26-b442-44bc-8b27-02039a9b9422">

If you have any screenshots for this issue, please upload here. BTW you can use https://asciinema.org/ for recording video in terminal.

NOTE workaround is to create a myspacevim#after() function as in the documentation and toggle the battery icon off and on 
(or not have it display automatically and just use the command keys to toggle it on after load)

function! myspacevim#after() abort
  call SpaceVim#layers#core#statusline#toggle_section("battery status")
  call SpaceVim#layers#core#statusline#toggle_section("battery status")
endfunction
