### ISSUE TITLE
Fail to open bookmark in NERDTree

### ISSUE THREAD

**Issue by jonahfang** [wsdjeg/SpaceVim#4918]
### Expected behavior.

1.switch to NERDTree window.
2.exec ::Bookmark command to add a bookmark to a file.
3.select the bookmark will open the file.

### The reproduce ways from Vim starting.

1.switch to NERDTree window.
2.exec ::Bookmark command to add a bookmark to a file.
3.select the bookmark will show error like this:

```
Error detected while processing function <SNR>97_nerdtree_enter:
line    1:
E716: Key not present in Dictionary: "path.str()"
```

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'init#after'
  bootstrap_before = 'init#before'
  buffer_index_type = 1
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['chrisbra/NrrwRgn'], ['moll/vim-bbye'], ['dsummersl/gundo.vim'], ['mklabs/split-term.vim'], ['jiangmiao/auto-pairs'], ['MattesGroeger/vim-bookmarks'], ['Shougo/vimproc', {'build': 'make', 'overwrite': 1}], ['mileszs/ack.vim', {'on_cmd': 'Ack', 'overwrite': 1}], ['albfan/ag.vim', {'loadconf': 1, 'on_cmd': 'Ag', 'overwrite': 1}], ['jonahfang/ctrlsf.vim', {'loadconf': 1, 'on_map': '<Plug>CtrlSF', 'loadconf_before': 1, 'on_cmd': 'CtrlSF', 'overwrite': 1}], ['natebosch/vim-lsc'], ['rizzatti/dash.vim'], ['nvie/vim-flake8'], ['Yggdroot/indentLine']]
  data_dir = '/Users/fzx/nvim3-spacevim2/data'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/fzx/nvim3-spacevim2/cache/vimfiles'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'deoplete-lsp'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'package.json', 'Cargo.toml', 'package.json', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_left_sections = ['major mode', 'version control info']
  statusline_right = ['cursorpos']
  statusline_separator = 'nil'
  statusline_unicode = 1
  statusline_unicode_symbols = 1
  terminal_cursor_shape = 2
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.2.0'
  vim_help_language = 'en'
  vimcompatible = 1
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
  open_error_list=1
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="default"
[[layers]]
  name="VersionControl"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#javascript"
  auto_fix=1
[[layers]]
  name="lang#python"
  python_interpreter='/usr/bin/python'
  python_file_head=['#coding=utf-8', 'from __future__ import unicode_literals', '', '', '#EOP']
[[layers]]
  name="unite"
[[layers]]
  name="ctrlp"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lsp"
  override_cmd={'rust': ['rust-analyzer']}
  filetypes=['rust']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/Users/fzx/nvim3-spacevim2/nvim/bin/nvim)
version: NVIM v0.9.1
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `default`: can not find function: SpaceVim#layers#default#health()
  - `VersionControl`:ok
  - `shell`:ok
  - `lang#javascript`:ok
  - `lang#python`:ok
  - `unite`:ok
  - `ctrlp`:ok
  - `lang#rust`:ok
  - `lsp`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [14:43:05:650] [ Info  ] Loading SpaceVim from: /Users/fzx/nvim3-spacevim2/spacevim/
[ SpaceVim ] [14:43:05:864] [ Info  ] Startup with argv: 2
[ SpaceVim ] [14:43:05:865] [ Info  ] init default vim options
[ SpaceVim ] [14:43:05:865] [ Info  ] options init done
[ SpaceVim ] [14:43:05:894] [ Info  ] start loading global config >>>
[ SpaceVim ] [14:43:05:894] [ Info  ] global_dir is: /Users/fzx/nvim3-spacevim2/.SpaceVim.d/
[ SpaceVim ] [14:43:05:894] [ Info  ] find global config: /Users/fzx/nvim3-spacevim2/.SpaceVim.d/init.toml
[ SpaceVim ] [14:43:05:895] [ Info  ] start to apply config [glob]
[ SpaceVim ] [14:43:05:909] [ Error ] bootstrap_before function failed: init#before
[ SpaceVim ] [14:43:05:909] [ Error ]        exception: Vim(let):E15: Invalid expression: /Library/Developer/CommandLineTools/usr/bin/ctags
[ SpaceVim ] [14:43:05:909] [ Error ]        throwpoint: /Users/fzx/nvim3-spacevim2/spacevim/init.vim[60]..function SpaceVim#custom#load[1]..<SNR>51_load_glob_conf[14]..<SNR>51_apply[128]..init#before[1]..script /Users/fzx/nvim3-spacevim2/.SpaceVim.d/autoload/before.vim, line 72
[ SpaceVim ] [14:43:05:909] [ Info  ] start loading local config >>>
[ SpaceVim ] [14:43:05:909] [ Info  ] Could not find project local config
[ SpaceVim ] [14:43:06:221] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [14:43:06:571] [ Info  ] run root changed callback on VimEnter!
[  project ] [14:43:06:576] [ Info  ] projects cache file does not exists!
[  project ] [14:43:06:576] [ Info  ] switch to project:[api3]
[  project ] [14:43:06:576] [ Info  ]        rootdir is:/Users/fzx/adev/yz/api3/
[ SpaceVim ] [14:43:12:168] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [14:43:12:168] [ Info  ] statusline build-in section hunks has been changed!
[ SpaceVim ] [14:43:18:760] [ Info  ] statusline build-in section vcs has been changed!
[ SpaceVim ] [14:43:18:760] [ Info  ] statusline build-in section hunks has been changed!

```
</details>
