### ISSUE TITLE
New line in insert mode not mapped to <cr>, <return>, or <c-m> in recent commits

### ISSUE THREAD

**Issue by mpm896** [wsdjeg/SpaceVim#4929]
### Expected behavior.

Hitting Enter or Return on the keyboard should go to a new line in insert mode. However, nothing happens. Instead, a new line can be created with <c-j> which is not ideal. I've confirmed this while using neovim 0.10.0 and 0.9.5

When SpaceVim is first installed and you select either Basic mode or Dark Powered mode, you can start a new buffer with no problems. Once SpaceVim is closed and reopened, then the issue occurs.

Switching to a less recent commit, such as 721e31186, solves the issue so somehow this keymapping got disrupted in recent commits.

### The reproduce ways from Vim starting.

Install a recent version of SpaceVim (i.e. commit 3ed7c00 or 057c0d5), select basic or dark powered mode, close and reopen spacevim, open a new buffer, go into insert mode, hit return/enter/c-m

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'nvim-cmp'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/root/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 1
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/root/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-grepper'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/opt/nvim-linux64/bin/nvim)
version: NVIM v0.10.0
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
SpaceVim clipboard support check report:
Checking +clipboard:
      Failed : to support +clipboard, you need has one of following clipboard tools in your $PATH:
               1. xclip
               2. xsel
               3. pbcopy/pbpaste (Mac OS X)
               4. lemonade (for SSH) https://github.com/pocke/lemonade
               5. doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/
SpaceVim environment check report:
Current progpath: nvim(/opt/nvim-linux64/bin/nvim)
version: NVIM v0.10.0
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] [13:51:30:282] [ Info  ] Loading SpaceVim from: /root/.SpaceVim/
[ SpaceVim ] [13:51:30:282] [ Info  ] default rtp is:
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /root/.SpaceVim/
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /root/.config/nvim
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /etc/xdg/nvim
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /root/.local/share/nvim/site
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /usr/local/share/nvim/site
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /usr/share/nvim/site
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /opt/nvim-linux64/share/nvim/runtime
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /opt/nvim-linux64/lib/nvim
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /usr/share/nvim/site/after
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /usr/local/share/nvim/site/after
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /root/.local/share/nvim/site/after
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /etc/xdg/nvim/after
[ SpaceVim ] [13:51:30:282] [ Info  ]   > /root/.config/nvim/after
[ SpaceVim ] [13:51:30:347] [ Info  ] v:argv is:['nvim', '--embed']
[ SpaceVim ] [13:51:30:347] [ Info  ] startup status:[0]
[ SpaceVim ] [13:51:30:347] [ Info  ] Startup with no argv, current dir is used: ~/.SpaceVim
[ SpaceVim ] [13:51:30:348] [ Info  ] init default vim options
[ SpaceVim ] [13:51:30:348] [ Info  ] options init done
[ SpaceVim ] [13:51:30:348] [ Info  ] init default layer list.
[ SpaceVim ] [13:51:30:348] [ Info  ] load layer:autocomplete
[ SpaceVim ] [13:51:30:349] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:349] [ Info  ] load layer:checkers
[ SpaceVim ] [13:51:30:349] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:349] [ Info  ] load layer:format
[ SpaceVim ] [13:51:30:349] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:349] [ Info  ] load layer:edit
[ SpaceVim ] [13:51:30:350] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:350] [ Info  ] load layer:ui
[ SpaceVim ] [13:51:30:351] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:351] [ Info  ] load layer:core
[ SpaceVim ] [13:51:30:352] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:352] [ Info  ] load layer:core#banner
[ SpaceVim ] [13:51:30:352] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:352] [ Info  ] load layer:core#statusline
[ SpaceVim ] [13:51:30:352] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:352] [ Info  ] load layer:core#tabline
[ SpaceVim ] [13:51:30:352] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:352] [ Info  ] layer list init done
[ SpaceVim ] [13:51:30:353] [ Info  ] start loading global config >>>
[ SpaceVim ] [13:51:30:353] [ Info  ] global_dir is: /root/.SpaceVim.d/
[ SpaceVim ] [13:51:30:353] [ Info  ] find global config: /root/.SpaceVim.d/init.toml
[ SpaceVim ] [13:51:30:353] [ Info  ] start to apply config [glob]
[ SpaceVim ] [13:51:30:354] [ Info  ] load layer:autocomplete
[ SpaceVim ] [13:51:30:354] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:354] [ Info  ] load layer:shell
[ SpaceVim ] [13:51:30:354] [ Info  ] layer loaded.
[ SpaceVim ] [13:51:30:354] [ Info  ] start loading local config >>>
[ SpaceVim ] [13:51:30:354] [ Info  ] find local conf: /root/.SpaceVim/.SpaceVim.d/init.vim
[ SpaceVim ] [13:51:30:565] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [13:51:30:582] [ Info  ] lsp client: nvim built-in lsp
[ SpaceVim ] [13:51:30:652] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [13:51:30:664] [ Info  ] run root changed callback on VimEnter!
[  project ] [13:51:30:665] [ Info  ] Load projects cache from: /root/.cache/SpaceVim/projects.json
[  project ] [13:51:30:665] [ Info  ] switch to project:[.SpaceVim]
[  project ] [13:51:30:665] [ Info  ]        rootdir is:/root/.SpaceVim/
[ SpaceVim ] [13:51:30:665] [ Info  ] loading local conf: .SpaceVim.d/init.vim
[ SpaceVim ] [13:51:30:666] [ Info  ] finished loading local conf
[ SpaceVim ] [13:51:30:672] [ Info  ] init default key bindings.
[ SpaceVim ] [13:51:30:673] [ Info  ] default key binding init done
[ SpaceVim ] [13:51:30:673] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[  project ] [13:51:31:170] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [13:51:31:171] [ Info  ]         (.git/):/root/.SpaceVim/

</details>
```
