### ISSUE TITLE
Ruby code runner window shows empty output

### ISSUE THREAD

**Issue by ledinhhuy88** [wsdjeg/SpaceVim#4933]
### Expected behavior.

![Screenshot 2024-08-14 at 10 00 08 PM](https://github.com/user-attachments/assets/887dd41f-6e4e-4c45-be79-c87824f85a99)
the runner window should include

> asdf

### The reproduce ways from Vim starting.

execute the current file with `SPC l r`, then the runner window doesn't show the expected output

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'nvim-cmp'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'everforest'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['sainnhe/everforest', {'repo': 'sainnhe/everforest', 'merged': 0, 'overwrite': 1}], ['roman/golden-ratio', {'repo': 'roman/golden-ratio', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/Users/huyle/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 0
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/huyle/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-ruby'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 0
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 0
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_indentline=0
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="telescope"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="lang#ruby"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.10.1/bin/nvim)
version: NVIM v0.10.1
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/local/Cellar/neovim/0.10.1/bin/nvim)
version: NVIM v0.10.1
OS: mac
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `telescope`:ok
  - `shell`:ok
  - `lang#ruby`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] [21:59:24:362] [ Info  ] Loading SpaceVim from: /Users/huyle/.SpaceVim/
[ SpaceVim ] [21:59:24:362] [ Info  ] default rtp is:
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /Users/huyle/.SpaceVim/
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /Users/huyle/.config/nvim
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/local/etc/xdg/nvim
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /etc/xdg/nvim
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /Users/huyle/.local/share/nvim/site
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/local/share/nvim/site
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/share/nvim/site
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/local/Cellar/neovim/0.10.1/share/nvim/runtime
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/local/Cellar/neovim/0.10.1/lib/nvim
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/share/nvim/site/after
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/local/share/nvim/site/after
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /Users/huyle/.local/share/nvim/site/after
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /etc/xdg/nvim/after
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /usr/local/etc/xdg/nvim/after
[ SpaceVim ] [21:59:24:362] [ Info  ]   > /Users/huyle/.config/nvim/after
[ SpaceVim ] [21:59:24:363] [ Info  ] $PYTHON3_HOST_PROG is not empty, setting g:python3_host_prog:/usr/local/bin/python3
[ SpaceVim ] [21:59:24:366] [ Info  ] v:argv is:['nvim', '--embed']
[ SpaceVim ] [21:59:24:366] [ Info  ] startup status:[0]
[ SpaceVim ] [21:59:24:366] [ Info  ] Startup with no argv, current dir is used: ~/dev/lab/ruby/map-reduce-select/first
[ SpaceVim ] [21:59:24:367] [ Info  ] init default vim options
[ SpaceVim ] [21:59:24:367] [ Info  ] options init done
[ SpaceVim ] [21:59:24:368] [ Info  ] init default layer list.
[ SpaceVim ] [21:59:24:368] [ Info  ] load layer:autocomplete
[ SpaceVim ] [21:59:24:369] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:369] [ Info  ] load layer:checkers
[ SpaceVim ] [21:59:24:369] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:369] [ Info  ] load layer:format
[ SpaceVim ] [21:59:24:370] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:370] [ Info  ] load layer:edit
[ SpaceVim ] [21:59:24:372] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:372] [ Info  ] load layer:ui
[ SpaceVim ] [21:59:24:373] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:373] [ Info  ] load layer:core
[ SpaceVim ] [21:59:24:375] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:375] [ Info  ] load layer:core#banner
[ SpaceVim ] [21:59:24:375] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:375] [ Info  ] load layer:core#statusline
[ SpaceVim ] [21:59:24:375] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:375] [ Info  ] load layer:core#tabline
[ SpaceVim ] [21:59:24:376] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:376] [ Info  ] layer list init done
[ SpaceVim ] [21:59:24:377] [ Info  ] start loading global config >>>
[ SpaceVim ] [21:59:24:377] [ Info  ] global_dir is: /Users/huyle/.SpaceVim.d/
[ SpaceVim ] [21:59:24:377] [ Info  ] find global config: /Users/huyle/.SpaceVim.d/init.toml
[ SpaceVim ] [21:59:24:378] [ Info  ] start to apply config [glob]
[  project ] [21:59:24:380] [ Info  ] Load projects cache from: /Users/huyle/.cache/SpaceVim/projects.json
[ SpaceVim ] [21:59:24:381] [ Info  ] load layer:autocomplete
[ SpaceVim ] [21:59:24:381] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:381] [ Info  ] load layer:ui
[ SpaceVim ] [21:59:24:381] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:381] [ Info  ] load layer:telescope
[ SpaceVim ] [21:59:24:381] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:382] [ Info  ] load layer:shell
[ SpaceVim ] [21:59:24:382] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:382] [ Info  ] load layer:lang#ruby
[ SpaceVim ] [21:59:24:383] [ Info  ] lang#ruby layer do not implement loadable function
[ SpaceVim ] [21:59:24:383] [ Info  ] layer loaded.
[ SpaceVim ] [21:59:24:383] [ Info  ] start loading local config >>>
[ SpaceVim ] [21:59:24:383] [ Info  ] Could not find project local config
[ SpaceVim ] [21:59:24:568] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [21:59:24:596] [ Info  ] lsp client: nvim built-in lsp
[ SpaceVim ] [21:59:24:600] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [21:59:24:624] [ Info  ] run root changed callback on VimEnter!
[  project ] [21:59:24:624] [ Info  ] switch to project:[first]
[  project ] [21:59:24:624] [ Info  ]        rootdir is:/Users/huyle/dev/lab/ruby/map-reduce-select/first/
[ SpaceVim ] [21:59:24:631] [ Info  ] init default key bindings.
[ SpaceVim ] [21:59:24:632] [ Info  ] default key binding init done
[ SpaceVim ] [21:59:24:633] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[  project ] [21:59:25:653] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[   runner ] [21:59:39:714] [ Info  ]    cmd:{ "ruby", "-" }

```
</details>
