### ISSUE TITLE
php lsp not work

### ISSUE THREAD

**Issue by victor-vb** [wsdjeg/SpaceVim#4934]
### Expected behavior.

When configuring the lsp language layer, there should be automatic completion, input prompts, and reference search, but after installing the plug-in, there are no prompts.

### The reproduce ways from Vim starting.

### neovim version
```
NVIM v0.10.1
SpaceVim 2.2.0-998535a8                      
                                                                                                                                                                                                                                            
Optional features included (+) or not (-):                                                                                                                                                                                                  
    -tui                    -jemalloc               +acl                                                                                                                                                                                    
    +arabic                 +autocmd                -browse                                                                                                                                                                                 
    +byte_offset            +cindent                -clientserver                                                                                                                                                                           
    +clipboard              +cmdline_compl          +cmdline_hist                                                                                                                                                                           
    +cmdline_info           +comments               +conceal                                                                                                                                                                                
    -cscope                 +cursorbind             +cursorshape                                                                                                                                                                            
    -debug                  -dialog_gui             +dialog_con                                                                                                                                                                             
    -dialog_con_gui         +digraphs               +eval                                                                                                                                                                                   
    +ex_extra               +extra_search           -farsi                                                                                                                                                                                  
    +file_in_path           +find_in_path           +folding                                                                                                                                                                                
    +gettext                +iconv                  -iconv/dyn                                                                                                                                                                              
    +insert_expand          +jumplist               +keymap                                                                                                                                                                                 
    +langmap                +libcall                +linebreak                                                                                                                                                                              
    +lispindent             +listcmds               +localmap                                                                                                                                                                               
    +menu                   +mksession              +modify_fname                                                                                                                                                                           
    +mouse                  -mouseshape             +multi_byte                                                                                                                                                                             
    -multi_byte_ime         +multi_lang             +path_extra                                                                                                                                                                             
    +persistent_undo        -postscript             -printer                                                                                                                                                                                
    +profile                -python                 -python3                                                                                                                                                                                
    +quickfix               +reltime                +rightleft                                                                                                                                                                              
    +scrollbind             +shada                  +signs                                                                                                                                                                                  
    +smartindent            +startuptime            +statusline                                                                                                                                                                             
    +syntax                 +tablineat              +tag_binary                                                                                                                                                                             
    -tag_old_static         -tag_any_white          +termguicolors                                                                                                                                                                          
    -terminfo               +termresponse           +textobjects                                                                                                                                                                            
    -tgetent                +timers                 +title                                                                                                                                                                                  
    -toolbar                +user_commands          +vertsplit                                                                                                                                                                              
    +virtualedit            +visual                 +visualextra                                                                                                                                                                            
    +vreplace               +wildignore             +wildmenu                                                                                                                                                                               
    +windows                +writebackup            -xim                                                                                                                                                                                    
    -xfontset               -xpm                    -xpm_w32
```

### Try running php-language-server manually

```
mac@MAC ~ % php /opt/homebrew/bin/phpactor language-server
Starting language server, use -vvv for verbose output
^C%   
```
it's ok

### After installing `php-layer` and enabling `php-lsp`, open the php file to test
Open a php file and write some built-in syntax. Some drop-down prompts will appear, but some third-party libraries will not prompt, such as: `new Swoole`, `new Redis`。

### Search if php-language-server is running
```
mac@MAC ~ % ps aux |grep php
mac        73740   0.0  0.0 408102576   1104 s001  S+    1:03PM   0:00.00 grep php

```
Nothing is running

`phpactor` is a library that has built-in some third-party libraries commonly used in PHP. You can directly check relevant information, but I don’t know why there seems to be no syntax prompt. Did I miss something?


### When I execute an `LspInfo`: there is an error from the upstream `lsp-config`
```
Error executing Lua callback: ...undle/nvim-lspconfig-latest/lua/lspconfig/ui/lspinfo.lua:276: attempt to call field '_trim' (a nil value)
stack traceback:                                                                                                                                                                                                                            
        ...undle/nvim-lspconfig-latest/lua/lspconfig/ui/lspinfo.lua:276: in function <...undle/nvim-lspconfig-latest/lua/lspconfig/ui/lspinfo.lua:187>                                                                                      
        ...aceVim/bundle/nvim-lspconfig-latest/plugin/lspconfig.lua:64: in function <...aceVim/bundle/nvim-lspconfig-latest/plugin/lspconfig.lua:63>
```



### Output of the `:SPDebugInfo!`

  :SPDebugInfo                                                                                                                                                                                                                                
<details><summary> SpaceVim debug information </summary>                                                                                                                                                                                    
                                                                                                                                                                                                                                            
### SpaceVim options :                                                                                                                                                                                                                      
                                                                                                                                                                                                                                            
```toml                                                                                                                                                                                                                                     
  auto_disable_touchpad = 1                                                                                                                                                                                                                 
  autocomplete_method = 'asyncomplete'                                                                                                                                                                                                      
  autocomplete_parens = 1                                                                                                                                                                                                                   
  buffer_index_type = 4                                                                                                                                                                                                                     
  checkinstall = 1                                                                                                                                                                                                                          
  code_runner_focus = 0                                                                                                                                                                                                                     
  colorscheme = 'gruvbox'                                                                                                                                                                                                                   
  colorscheme_bg = 'dark'                                                                                                                                                                                                                   
  colorscheme_default = 'desert'                                                                                                                                                                                                            
  commandline_prompt = '>'                                                                                                                                                                                                                  
  custom_color_palette = []                                                                                                                                                                                                                 
  custom_plugins = []                                                                                                                                                                                                                       
  data_dir = '/Users/mac/.cache/'                                                                                                                                                                                                     
  debug_level = 0                                                                                                                                                                                                                           
  default_custom_leader = '<Space>'                                                                                                                                                                                                         
  default_indent = 2                                                                                                                                                                                                                        
  disabled_plugins = []                                                                                                                                                                                                                     
  enable_bepo_layout = 0                                                                                                                                                                                                                    
  enable_cursorcolumn = 0                                                                                                                                                                                                                   
  enable_cursorline = 1                                                                                                                                                                                                                     
  enable_debug = 1                                                                                                                                                                                                                          
  enable_googlesuggest = 0                                                                                                                                                                                                                  
  enable_guicolors = 0                                                                                                                                                                                                                      
  enable_javacomplete2_py = 0                                                                                                                                                                                                               
  enable_key_frequency = 0                                                                                                                                                                                                                  
  enable_language_specific_leader = 1                                                                                                                                                                                                       
  enable_list_mode = 0                                                                                                                                                                                                                      
  enable_neocomplcache = 0                                                                                                                                                                                                                  
  enable_os_fileformat_icon = 0                                                                                                                                                                                                             
  enable_powerline_fonts = 1                                                                                                                                                                                                                
  enable_projects_cache = 1                                                                                                                                                                                                                 
  enable_statusline_bfpath = 0                                                                                                                                                                                                              
  enable_statusline_mode = 0                                                                                                                                                                                                                
  enable_statusline_tag = 1                                                                                                                                                                                                                 
  enable_tabline_filetype_icon = 0                                                                                                                                                                                                          
  enable_tabline_ft_icon = 0                                                                                                                                                                                                                
  enable_vimfiler_welcome = 1                                                                                                                                                                                                               
  enable_ycm = 0 
  error_symbol = '✖'                                                                                                                                                                                                                        
  escape_key_binding = 'jk'                                                                                                                                                                                                                 
  expand_tab = 1                                                                                                                                                                                                                            
  file_searching_tools = []                                                                                                                                                                                                                 
  filemanager = 'nerdtree'                                                                                                                                                                                                                  
  filetree_direction = 'right'                                                                                                                                                                                                              
  filetype_icons = {}                                                                                                                                                                                                                       
  force_global_config = 0                                                                                                                                                                                                                   
  gitcommit_issue_icon = ''                                                                                                                                                                                                                
  gitcommit_pr_icon = ''                                                                                                                                                                                                                   
  github_username = ''                                                                                                                                                                                                                      
  guifont = 'SauceCodePro Nerd Font Mono:h11'                                                                                                                                                                                               
  hiddenfileinfo = 1                                                                                                                                                                                                                        
  home_files_number = 6                                                                                                                                                                                                                     
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'                                                                                                                                                                
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/Users/mac/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'phpcomplete.vim-vim7'                                                                                                                                                                                                      
  project_auto_root = 1                                                                                                                                                                                                                     
  project_non_root = ''                                                                                                                                                                                                                     
  project_rooter_outermost = 1                                                                                                                                                                                                              
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']                                                                                                                                                                  
  projects_cache_num = 20                                                                                                                                                                                                                   
  realtime_leader_guide = 1                                                                                                                                                                                                                 
  relativenumber = 1                                                                                                                                                                                                                        
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']                                                                                                                                                                        
  sidebar_direction = ''                                                                                                                                                                                                                    
  sidebar_width = 30                                                                                                                                                                                                                        
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 
 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager']                             
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']                                                                                                                                                                                  
  snippet_engine = 'neosnippet'                                                                                                                                                                                                             
  src_root = 'E:\sources\'                                                                                                                                                                                                                  
  statusline_iseparator = 'bar'                                                                                                                                                                                                             
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']                                                                                                                           
  statusline_right = ['fileformat', 'cursorpos', 'percentage']                                                                                                                                                                              
  statusline_separator = 'nil'                                                                                                                                                                                                              
  statusline_unicode = 0                                                                                                                                                                                                                    
  terminal_cursor_shape = 2                                                                                                                                                                                                                 
  todo_labels = ['fixme', 'question', 'todo', 'idea']                                                                                                                                                                                       
  todo_prefix = '@'                                                                                                                                                                                                                         
  update_retry_cnt = 3                                                                                                                                                                                                                      
  version = '2.2.0'                                                                                                                                                                                                                         
  vim_help_language = 'en'                                                                                                                                                                                                                  
  vimcompatible = 1                                                                                                                                                                                                                         
  warning_symbol = '⚠'                                                                                                                                                                                                                      
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'                                                                                                                     
  windisk_encoding = 'cp936'                                                                                                                                                                                                                
  windows_index_type = 3                                                                                                                                                                                                                    
  windows_leader = ''                                                                                                                                                                                                                       
  windows_smartclose = ''                                                                                                                                                                                                                   
  wrap_line = 0                                                                                                                                                                                                                             
```  


### SpaceVim layers :
          
```toml   
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='cycle'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"                                                                                                                                                                                                                       
[[layers]]                                                                                                                                                                                                                                  
  name="shell"                                                                                                                                                                                                                              
  default_position='top'                                                                                                                                                                                                                    
  default_height=30                                                                                                                                                                                                                         
[[layers]]                                                                                                                                                                                                                                  
  name="lang#php"                                                                                                                                                                                                                           
[[layers]]                                                                                                                                                                                                                                  
  name="lsp"                                                                                                                                                                                                                                
  override_cmd={'enabled_clients': ['php'], 'php': ['/opt/homebrew/bin/phpactor', 'language-server']}                                                                                                                                       
  filetypes=['php']                                                                                                                                                                                                                         
```                                  
### SpaceVim Health checking :                                                                                                                                                                                                              
                                                                                                                                                                                                                                            
SpaceVim clipboard support check report:                                                                                                                                                                                                    
Checking +clipboard:                                                                                                                                                                                                                        
      SUCCEED!                                                                                                                                                                                                                              
SpaceVim environment check report:                                                                                                                                                                                                          
Current progpath: nvim(/opt/homebrew/Cellar/neovim/0.10.1/bin/nvim)                                                                                                                                                                         
version: NVIM v0.10.1                                                                                                                                                                                                                       
OS: mac                                                                                                                                                                                                                                     
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]                                                                                                                                                                                    
SpaceVim lua support check report:                                                                                                                                                                                                          
Checking +lua:                                                                                                                                                                                                                              
      Failed : Known issue, neovim do not support lua now.                                                                                                                                                                                  
SpaceVim python support check report:                                                                                                                                                                                                       
Checking +python3:                                                                                                                                                                                                                          
      Failed : to support +python3, you need run `pip3 install neovim`                                                                                                                                                                      
Checking +python:                                                                                                                                                                                                                           
      Failed : to support +python, you need run `pip2 install neovim`                                                                                                                                                                       
Checking SpaceVim layer health:                                                                                                                                                                                                             
  - `autocomplete`:ok                                                                                                                                                                                                                       
  - `checkers`:ok                                                                                                                                                                                                                           
  - `format`:ok                                                                                                                                                                                                                             
  - `edit`:ok                                                                                                                                                                                                                               
  - `ui`:ok                                                                                                                                                                                                                                 
  - `core`:ok                                                                                                                                                                                                                               
  - `core#banner`:ok                                                                                                                                                                                                                        
  - `core#statusline`:ok                                                                                                                                                                                                                    
  - `core#tabline`:ok                                                                                                                                                                                                                       
  - `shell`:ok                                                                                                                                                                                                                              
  - `lang#php`:ok                                                                                                                                                                                                                           
  - `lsp`:ok     


### SpaceVim runtime log :                                                                                                                                                                                                                  
                                                                                                                                                                                                                                            
```log                                                                                                                                                                                                                                      
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!                                                                                                                                                    
[ SpaceVim ] [12:47:07:812] [ Info  ] Loading SpaceVim from: /Users/mac/.SpaceVim/                                                                                                                                                    
[ SpaceVim ] [12:47:07:909] [ Info  ] Startup with no argv, current dir is used: ~/project/php/mas                                                                                                                                          
[ SpaceVim ] [12:47:07:909] [ Info  ] init default vim options                                                                                                                                                                              
[ SpaceVim ] [12:47:07:910] [ Info  ] options init done                                                                                                                                                                                     
[ SpaceVim ] [12:47:07:918] [ Info  ] start loading global config >>>                                                                                                                                                                       
[ SpaceVim ] [12:47:07:918] [ Info  ] global_dir is: /Users/mac/.SpaceVim.d/                                                                                                                                                          
[ SpaceVim ] [12:47:07:918] [ Info  ] find global config: /Users/mac/.SpaceVim.d/init.toml                                                                                                                                            
[ SpaceVim ] [12:47:07:925] [ Info  ] start to apply config [glob]                                                                                                                                                                          
[ SpaceVim ] [12:47:07:926] [ Info  ] start loading local config >>>                                                                                                                                                                        
[ SpaceVim ] [12:47:07:926] [ Info  ] Could not find project local config                                                                                                                                                                   
[ SpaceVim ] [12:47:07:926] [ Debug ] init default key bindings.                                                                                                                                                                            
[ SpaceVim ] [12:47:07:927] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server                                                                                                                                                  
[ SpaceVim ] [12:47:07:927] [ Debug ] init g key bindings                                                                                                                                                                                   
[ SpaceVim ] [12:47:07:928] [ Debug ] init z key bindings                                                                                                                                                                                   
[ SpaceVim ] [12:47:07:928] [ Debug ] defind SPC h k prefixs                                                                                                                                                                                
[ SpaceVim ] [12:47:07:928] [ Debug ] init SPC key bindings                                                                                                                                                                                 
[ SpaceVim ] [12:47:07:939] [ Debug ] init autocomplete layer plugins list.                                                                                                                                                                 
[ SpaceVim ] [12:47:07:944] [ Debug ] load autocomplete layer config.                                                                                                                                                                       
[ SpaceVim ] [12:47:07:944] [ Debug ] init checkers layer plugins list.                                                                                                                                                                     
[ SpaceVim ] [12:47:07:945] [ Debug ] load checkers layer config.                                                                                                                                                                           
[ SpaceVim ] [12:47:07:945] [ Debug ] register major mode function:syntax-checking                                                                                                                                                          
[ SpaceVim ] [12:47:07:945] [ Debug ] init format layer plugins list.                                                                                                                                                                       
[ SpaceVim ] [12:47:07:946] [ Debug ] load format layer config.                                                                                                                                                                             
[ SpaceVim ] [12:47:07:946] [ Debug ] init edit layer plugins list.                                                                                                                                                                         
[ SpaceVim ] [12:47:07:951] [ Debug ] load edit layer config.                                                                                                                                                                               
[ autosave ] [12:47:07:952] [ Debug ] setup new autosave timer, timeoutlen:300000                                                                                                                                                           
[ SpaceVim ] [12:47:07:954] [ Debug ] init ui layer plugins list.                                                                                                                                                                           
[ SpaceVim ] [12:47:07:957] [ Debug ] load ui layer config.                                                                                                                                                                                 
[ SpaceVim ] [12:47:07:958] [ Debug ] register major mode function:spell-checking                                                                                                                                                           
[ SpaceVim ] [12:47:07:958] [ Debug ] register major mode function:hi-characters-for-long-lines                                                                                                                                             
[ SpaceVim ] [12:47:07:958] [ Debug ] register major mode function:fill-column-indicator                                                                                                                                                    
[ SpaceVim ] [12:47:07:958] [ Debug ] register major mode function:whitespace                                                                                                                                                               
[ SpaceVim ] [12:47:07:958] [ Debug ] register major mode function:paste-mode                                                                                                                                                               
[ SpaceVim ] [12:47:07:958] [ Debug ] register major mode function:wrapline
[ SpaceVim ] [12:47:07:958] [ Debug ] init core layer plugins list.
[ SpaceVim ] [12:47:07:962] [ Debug ] load core layer config.
[ SpaceVim ] [12:47:07:966] [ Debug ] init core#banner layer plugins list.
[ SpaceVim ] [12:47:07:966] [ Debug ] load core#banner layer config.
[ SpaceVim ] [12:47:07:966] [ Debug ] init core#statusline layer plugins list.
[ SpaceVim ] [12:47:07:966] [ Debug ] load core#statusline layer config.
[ SpaceVim ] [12:47:07:966] [ Debug ] init core#tabline layer plugins list.
[ SpaceVim ] [12:47:07:967] [ Debug ] load core#tabline layer config.
[ SpaceVim ] [12:47:07:967] [ Debug ] init shell layer plugins list.
[ SpaceVim ] [12:47:07:968] [ Debug ] load shell layer config.
[ SpaceVim ] [12:47:07:968] [ Debug ] init lang#php layer plugins list.
[ SpaceVim ] [12:47:07:969] [ Debug ] load lang#php layer config.
[ SpaceVim ] [12:47:07:971] [ Debug ] init lsp layer plugins list.
[ SpaceVim ] [12:47:07:972] [ Debug ] load lsp layer config.
[ SpaceVim ] [12:47:07:985] [ Debug ] init SpaceVim_core autocmd group
[ SpaceVim ] [12:47:07:991] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [12:47:08:029] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [12:47:08:053] [ Info  ] run root changed callback on VimEnter!
[  project ] [12:47:08:055] [ Debug ] project rooter patterns:{ ".git/", "_darcs/", ".hg/", ".bzr/", ".svn/" }
[  project ] [12:47:08:055] [ Info  ] Load projects cache from: /Users/mac/.cache/SpaceVim/projects.json
[  project ] [12:47:08:056] [ Info  ] switch to project:[mas]
[  project ] [12:47:08:056] [ Info  ]        rootdir is:/Users/mac/project/php/mas/
[  project ] [12:47:11:059] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [12:47:11:059] [ Debug ] project rooter patterns:{ ".git/", "_darcs/", ".hg/", ".bzr/", ".svn/" }
[  project ] [12:47:11:059] [ Debug ] start to find root for: /Users/mac/project/php/mas/NERD_tree_1
[  project ] [12:47:12:469] [ Debug ] start to find root for: /Users/mac/project/php/mas/index.php
[ SpaceVim ] [12:47:20:864] [ Debug ] register major mode function:syntax-checking
[ SpaceVim ] [12:47:20:872] [ Debug ] register major mode function:spell-checking
[ SpaceVim ] [12:47:20:872] [ Debug ] register major mode function:hi-characters-for-long-lines
[ SpaceVim ] [12:47:20:872] [ Debug ] register major mode function:fill-column-indicator
[ SpaceVim ] [12:47:20:872] [ Debug ] register major mode function:whitespace
[ SpaceVim ] [12:47:20:872] [ Debug ] register major mode function:paste-mode
[ SpaceVim ] [12:47:20:873] [ Debug ] register major mode function:wrapline
[ SpaceVim ] [12:51:46:995] [ Debug ] register major mode function:syntax-checking
[ SpaceVim ] [12:51:47:005] [ Debug ] register major mode function:spell-checking
[ SpaceVim ] [12:51:47:005] [ Debug ] register major mode function:hi-characters-for-long-lines
[ SpaceVim ] [12:51:47:006] [ Debug ] register major mode function:fill-column-indicator
[ SpaceVim ] [12:51:47:006] [ Debug ] register major mode function:whitespace
[ SpaceVim ] [12:51:47:006] [ Debug ] register major mode function:paste-mode
[ SpaceVim ] [12:51:47:006] [ Debug ] register major mode function:wrapline
[ autosave ] [12:54:42:796] [ Info  ] backup path is:/Users/mac/.cache/SpaceVim/backup/_Users_mac_project_php_mas_index_php.backup
[ autosave ] [12:54:47:714] [ Info  ] backup path is:/Users/mac/.cache/SpaceVim/backup/_Users_mac_project_php_mas_index_php.backup
[ autosave ] [12:54:47:911] [ Info  ] backup path is:/Users/mac/.cache/SpaceVim/backup/_Users_mac_project_php_mas_index_php.backup
[ autosave ] [12:54:48:085] [ Info  ] backup path is:/Users/mac/.cache/SpaceVim/backup/_Users_mac_project_php_mas_index_php.backup
[ autosave ] [12:54:48:888] [ Info  ] backup path is:/Users/mac/.cache/SpaceVim/backup/_Users_mac_project_php_mas_index_php.backup
[ autosave ] [12:55:11:691] [ Info  ] backup path is:/Users/mac/.cache/SpaceVim/backup/_Users_mac_project_php_mas_index_php.backup
[ SpaceVim ] [12:55:23:978] [ Debug ] register major mode function:syntax-checking
[ SpaceVim ] [12:55:23:988] [ Debug ] register major mode function:spell-checking
[ SpaceVim ] [12:55:23:988] [ Debug ] register major mode function:hi-characters-for-long-lines
[ SpaceVim ] [12:55:23:988] [ Debug ] register major mode function:fill-column-indicator
[ SpaceVim ] [12:55:23:988] [ Debug ] register major mode function:whitespace
[ SpaceVim ] [12:55:23:988] [ Debug ] register major mode function:paste-mode
[ SpaceVim ] [12:55:23:988] [ Debug ] register major mode function:wrapline
          
```       
</details>
