### ISSUE TITLE
运行python程序时，本地文件库无法加载，报错找不到 module

### ISSUE THREAD

**Issue by YanMing-lxb** [wsdjeg/SpaceVim#4937]
### Expected behavior.

![image](https://github.com/user-attachments/assets/e398d722-d542-449c-9ef5-5404b1fbf697)

logger_config.py 是我自己定义的一个库，但是无法加载，哪怕是 `from .logger_config import setup_logger `也是无效的

在 vscode 和 终端中是可以运行的。

## 系统环境：
ubuntu 24.04
miniconda3

### The reproduce ways from Vim starting.

A bug happened!

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'ycm'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'molokai'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/yanming/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 4
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 1
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/yanming/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'async.vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'ultisnips'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
  statusline_right = ['cursorpos', 'percentage', 'input method', 'date', 'time']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="colorscheme"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="chinese"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#python"
  format_on_save=1
  enable_typeinfo=1
[[layers]]
  name="lang#cmake"
[[layers]]
  name="lang#sh"
[[layers]]
  name="git"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lsp"
  enabled_clients=['pylsp']
[[layers]]
  name="VersionControl"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 901
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `colorscheme`:ok
  - `shell`:ok
  - `chinese`:ok
  - `lang#latex`:ok
  - `lang#python`:ok
  - `lang#cmake`:ok
  - `lang#sh`:ok
  - `git`:ok
  - `lang#toml`:ok
  - `lsp`:ok
  - `VersionControl`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [22:07:34] [   0.000] [  Info ] Loading SpaceVim from: /home/yanming/.SpaceVim/
[ SpaceVim ] [22:07:34] [   0.000] [  Info ] default rtp is:
[ SpaceVim ] [22:07:34] [   0.001] [  Info ]   > /home/yanming/.SpaceVim/
[ SpaceVim ] [22:07:34] [   0.001] [  Info ]   > /usr/share/vim/vim91
[ SpaceVim ] [22:07:34] [   0.024] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [22:07:34] [   0.024] [  Info ] v:argv is:['vim', './src/__main__.py']
[ SpaceVim ] [22:07:34] [   0.024] [  Info ] startup status:[2, ['vim', './src/__main__.py']]
[ SpaceVim ] [22:07:34] [   0.025] [  Info ] Startup with argv: 2
[ SpaceVim ] [22:07:34] [   0.026] [  Info ] init default layer list.
[ SpaceVim ] [22:07:34] [   0.026] [  Info ] load layer:autocomplete
[ SpaceVim ] [22:07:34] [   0.026] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.026] [  Info ] load layer:checkers
[ SpaceVim ] [22:07:34] [   0.027] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.027] [  Info ] load layer:format
[ SpaceVim ] [22:07:34] [   0.027] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.027] [  Info ] load layer:edit
[ SpaceVim ] [22:07:34] [   0.030] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.030] [  Info ] load layer:ui
[ SpaceVim ] [22:07:34] [   0.031] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.031] [  Info ] load layer:core
[ SpaceVim ] [22:07:34] [   0.032] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.032] [  Info ] load layer:core#banner
[ SpaceVim ] [22:07:34] [   0.032] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.032] [  Info ] load layer:core#statusline
[ SpaceVim ] [22:07:34] [   0.035] [  Info ] core#statusline layer do not implement loadable function
[ SpaceVim ] [22:07:34] [   0.035] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.035] [  Info ] load layer:core#tabline
[ SpaceVim ] [22:07:34] [   0.036] [  Info ] layer loaded.
[ SpaceVim ] [22:07:34] [   0.036] [  Info ] layer list init done
[ SpaceVim ] [22:07:34] [   0.037] [  Info ] start loading global config >>>
[ SpaceVim ] [22:07:34] [   0.037] [  Info ] global_dir is: /home/yanming/.SpaceVim.d/
[ SpaceVim ] [22:07:34] [   0.037] [  Info ] find global config: /home/yanming/.SpaceVim.d/init.toml
[ SpaceVim ] [22:07:35] [   0.100] [  Info ] start to apply config [glob]
[ SpaceVim ] [22:07:35] [   0.101] [  Info ] load layer:colorscheme
[ SpaceVim ] [22:07:35] [   0.101] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.101] [  Info ] load layer:autocomplete
[ SpaceVim ] [22:07:35] [   0.101] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.101] [  Info ] load layer:shell
[ SpaceVim ] [22:07:35] [   0.102] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.102] [  Info ] load layer:chinese
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] chinese layer do not implement loadable function
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] chinese layer do not implement set_variable function
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] load layer:lang#latex
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] lang#latex layer do not implement loadable function
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] lang#latex layer do not implement set_variable function
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.103] [  Info ] load layer:lang#python
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] load layer:lang#cmake
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] lang#cmake layer do not implement loadable function
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] lang#cmake layer do not implement set_variable function
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] load layer:lang#sh
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.104] [  Info ] load layer:git
[ SpaceVim ] [22:07:35] [   0.105] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.105] [  Info ] load layer:lang#toml
[ SpaceVim ] [22:07:35] [   0.105] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.105] [  Info ] load layer:lsp
[ SpaceVim ] [22:07:35] [   0.106] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.106] [  Info ] load layer:VersionControl
[ SpaceVim ] [22:07:35] [   0.106] [  Info ] layer loaded.
[ SpaceVim ] [22:07:35] [   0.107] [  Info ] start loading local config >>>
[ SpaceVim ] [22:07:35] [   0.107] [  Info ] Could not find project local config
[ SpaceVim ] [22:07:35] [   0.107] [  Info ] YCM only support ultisnips
[ SpaceVim ] [22:07:35] [   0.161] [  Info ] core#statusline layer do not implement plugins function
[ SpaceVim ] [22:07:35] [   0.214] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [22:07:35] [   0.310] [  Info ] lsp client: vim-lsp
[ SpaceVim ] [22:07:35] [   0.490] [  Info ] run root changed callback on VimEnter!
[   rooter ] [22:07:35] [   0.493] [  Info ] Load projects cache from: /home/yanming/.cache/SpaceVim/projects.json
[ SpaceVim ] [22:07:35] [   0.729] [  Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [22:07:35] [   0.757] [  Info ] init default key bindings.
[ SpaceVim ] [22:07:35] [   0.759] [  Info ] default key binding init done
[   rooter ] [22:07:36] [   1.914] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:36] [   1.914] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:36] [   1.916] [  Info ] buffer name: No Name
[   rooter ] [22:07:36] [   1.917] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:37] [   2.435] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:37] [   2.436] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:37] [   2.438] [  Info ] buffer name: No Name
[   rooter ] [22:07:37] [   2.438] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:39] [   4.515] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:39] [   4.516] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:39] [   4.520] [  Info ] buffer name: No Name
[   rooter ] [22:07:39] [   4.521] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:40] [   5.572] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:40] [   5.573] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:40] [   5.577] [  Info ] buffer name: No Name
[   rooter ] [22:07:40] [   5.577] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:41] [   6.538] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/__runner__
[   rooter ] [22:07:41] [   6.539] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:41] [   6.543] [  Info ] buffer name: __runner__
[   rooter ] [22:07:41] [   6.543] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:41] [   6.627] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/src/__main__.py
[   rooter ] [22:07:41] [   6.628] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:41] [   6.631] [  Info ] buffer name: ./src/__main__.py
[   rooter ] [22:07:41] [   6.631] [  Info ] same as current directory, no need to change.
[   runner ] [22:07:41] [   6.652] [  Info ]    cmd:['python3', '-']
[   rooter ] [22:07:43] [   8.916] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:43] [   8.916] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:43] [   8.918] [  Info ] buffer name: No Name
[   rooter ] [22:07:43] [   8.918] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:44] [   9.275] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:44] [   9.275] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:44] [   9.277] [  Info ] buffer name: No Name
[   rooter ] [22:07:44] [   9.278] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:47] [  12.139] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:47] [  12.140] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:47] [  12.142] [  Info ] buffer name: No Name
[   rooter ] [22:07:47] [  12.143] [  Info ] same as current directory, no need to change.
[   rooter ] [22:07:47] [  12.309] [  Info ] Start to find root for: /home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/NERD_tree_1
[   rooter ] [22:07:47] [  12.310] [  Info ]         (.git/):/home/yanming/文档/GitHub-Project/Heat-Exchanger-Calibration-Calculator/
[   rooter ] [22:07:47] [  12.312] [  Info ] buffer name: NERD_tree_1
[   rooter ] [22:07:47] [  12.312] [  Info ] same as current directory, no need to change.
[   rooter ] [22:08:00] [  25.201] [  Info ] buffer name: src/__main__.py
[   rooter ] [22:08:00] [  25.201] [  Info ] same as current directory, no need to change.
[   rooter ] [22:09:57] [ 142.064] [  Info ] buffer name: __runner__
[   rooter ] [22:09:57] [ 142.064] [  Info ] same as current directory, no need to change.
[   rooter ] [22:11:21] [ 226.552] [  Info ] buffer name: src/__main__.py
[   rooter ] [22:11:21] [ 226.552] [  Info ] same as current directory, no need to change.
[   rooter ] [22:11:24] [ 229.579] [  Info ] buffer name: NERD_tree_1
[   rooter ] [22:11:24] [ 229.579] [  Info ] same as current directory, no need to change.
[   rooter ] [22:14:08] [ 393.518] [  Info ] buffer name: __runner__
[   rooter ] [22:14:08] [ 393.518] [  Info ] same as current directory, no need to change.
[   rooter ] [22:14:14] [ 399.205] [  Info ] buffer name: src/__main__.py
[   rooter ] [22:14:14] [ 399.205] [  Info ] same as current directory, no need to change.
[ SpaceVim ] [22:14:20] [ 405.058] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [22:14:20] [ 405.059] [  Info ] statusline build-in section hunks has been changed!
[ SpaceVim ] [22:14:56] [ 442.039] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [22:14:56] [ 442.040] [  Info ] statusline build-in section hunks has been changed!
[ SpaceVim ] [22:16:28] [ 533.825] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [22:16:28] [ 533.825] [  Info ] statusline build-in section hunks has been changed!
[ SpaceVim ] [22:18:55] [ 680.598] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [22:18:55] [ 680.598] [  Info ] statusline build-in section hunks has been changed!
```
</details>
