### ISSUE TITLE
When using lang#java, javavi fails to compile

### ISSUE THREAD

**Issue by inuitviking** [wsdjeg/SpaceVim#4938]
### Expected behavior.

Java language support should work as expected.

### The reproduce ways from Vim starting.

Simply install java layer on a fresh install. I have personally installed it with these settings:

```toml
[[layers]]
  name = "lang#java"

[[layers]]
  name = 'lsp'
  enabled_clients = ['intelephense', 'clangd']
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
      "java",
      "-Declipse.application=org.eclipse.jdt.ls.core.id1",
	    "-Dosgi.bundles.defaultStartLevel=4",
	    "-Declipse.product=org.eclipse.jdt.ls.core.product",
      "Dlog.protocol=true",
	    "-Dlog.level=NONE",
      "-noverify",
    	"-Xmx1G",
	    "-jar /home/crt@hamag-2011.local/eclipse/java-2023-12/eclipse/plugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar",
	    "-configuration ./config_linux",
	    "-data /home/crt@hamag-2011.local"
    ]
```

To ***solve*** it as a user, you go into `~/.SpaceVim/bundle/vim-javacomplete2/libs` and download the jar files available here (`javavi_log4j-api.jar` and `javavi_log4j-core.jar` is sufficient): https://github.com/artur-shaik/vim-javacomplete2/tree/master/libs

Those files must be in `~/.SpaceVim/bundle/vim-javacomplete2/libs` for it to work.

Is it possible to have these jar files included when SpaceVim installs Java language support?

On another notice, vim-javacomplete2 is also deprecated in favor of [jc.nvim](https://github.com/artur-shaik/jc.nvim); I have not personally tried jv.nvim yet, but it is the same maintainer, and would be excited to see an updated layer that uses this, if it's possible. :smile: 

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/crt@hamag-2011.local/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/crt@hamag-2011.local/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'xmledit'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.clang', 'pom.xml', 'build.gradle', 'package.json', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="cscope"
  auto_update='enable'
[[layers]]
  name="ctrlspace"
  autoload-workspaces=1
[[layers]]
  name="debug"
[[layers]]
  name="fzf"
[[layers]]
  name="git"
[[layers]]
  name="gtags"
  gtagslabel='ctags'
[[layers]]
  name="lang#asciidoc"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#cmake"
[[layers]]
  name="lang#csharp"
  highlight_types=1
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lang#erlang"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#kotlin"
[[layers]]
  name="lang#markdown"
[[layers]]
  name="lang#php"
[[layers]]
  name="lsp"
  enabled_clients=['intelephense', 'clangd']
  override_cmd={'java': ['java', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', 'Dlog.protocol=true', '-Dlog.level=NONE', '-noverify', '-Xmx1G', '-jar /home/c
rt@hamag-2011.local/eclipse/java-2023-12/eclipse/plugins/org.eclipse.equinox.launcher_1.6.600.v20231106-1826.jar', '-configuration ./config_linux', '-data /home/crt@hamag-2011.local']}
  filetypes=['java']
[[layers]]
  name="lang#plantuml"
  plantuml_jar_path='/usr/share/plantuml/plantuml.jar'
[[layers]]
  name="lang#powershell"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#xml"
[[layers]]
  name="ssh"
[[layers]]
  name="treesitter"
```

### SpaceVim Health checking :

```
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/usr/bin/nvim)
version: NVIM v0.7.2
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
```

Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `cscope`:ok
  - `ctrlspace`:ok
  - `debug`:ok
  - `fzf`:ok
  - `git`:ok
  - `gtags`:ok
  - `lang#asciidoc`:ok
  - `lang#c`:ok
  - `lang#cmake`:ok
  - `lang#csharp`:ok
  - `lang#dockerfile`:ok
  - `lang#erlang`:ok
  - `lang#html`:ok
  - `lang#java`:ok
  - `lang#javascript`:ok
  - `lang#json`:ok
  - `lang#kotlin`:ok
  - `lang#markdown`:ok
  - `lang#php`:ok
  - `lsp`:ok
  - `lang#plantuml`:ok
  - `lang#powershell`:ok
  - `lang#rust`:ok
  - `lang#toml`:ok
  - `lang#vim`:ok
  - `lang#vue`:ok
  - `lang#xml`:ok
  - `ssh`:ok
  - `treesitter`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] [11:20:27:529] [ Info  ] Loading SpaceVim from: /home/crt@hamag-2011.local/.SpaceVim/
[ SpaceVim ] [11:20:27:529] [ Info  ] default rtp is:
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.SpaceVim/
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.config/nvim
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /etc/xdg/xdg-pop/nvim
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /etc/xdg/nvim
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.local/share/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/pop/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/gnome/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.local/share/flatpak/exports/share/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /var/lib/flatpak/exports/share/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/local/share/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/nvim/site
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/nvim/runtime
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/lib/nvim
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/local/share/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /var/lib/flatpak/exports/share/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.local/share/flatpak/exports/share/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/gnome/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /usr/share/pop/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.local/share/nvim/site/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /etc/xdg/nvim/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /etc/xdg/xdg-pop/nvim/after
[ SpaceVim ] [11:20:27:529] [ Info  ]   > /home/crt@hamag-2011.local/.config/nvim/after
[ SpaceVim ] [11:20:27:594] [ Info  ] v:argv is:['nvim']
[ SpaceVim ] [11:20:27:594] [ Info  ] startup status:[0]
[ SpaceVim ] [11:20:27:594] [ Info  ] Startup with no argv, current dir is used: ~/.SpaceVim/bundle/vim-javacomplete2/libs
[ SpaceVim ] [11:20:27:594] [ Info  ] init default vim options
[ SpaceVim ] [11:20:27:595] [ Info  ] options init done
[ SpaceVim ] [11:20:27:595] [ Info  ] init default layer list.
[ SpaceVim ] [11:20:27:595] [ Info  ] load layer:autocomplete
[ SpaceVim ] [11:20:27:595] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:596] [ Info  ] load layer:checkers
[ SpaceVim ] [11:20:27:596] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:596] [ Info  ] load layer:format
[ SpaceVim ] [11:20:27:596] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:596] [ Info  ] load layer:edit
[ SpaceVim ] [11:20:27:597] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:597] [ Info  ] load layer:ui
[ SpaceVim ] [11:20:27:597] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:597] [ Info  ] load layer:core
[ SpaceVim ] [11:20:27:598] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:598] [ Info  ] load layer:core#banner
[ SpaceVim ] [11:20:27:598] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:598] [ Info  ] load layer:core#statusline
[ SpaceVim ] [11:20:27:599] [ Info  ] core#statusline layer do not implement loadable function
[ SpaceVim ] [11:20:27:599] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:599] [ Info  ] load layer:core#tabline
[ SpaceVim ] [11:20:27:600] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:600] [ Info  ] layer list init done
[ SpaceVim ] [11:20:27:600] [ Info  ] start loading global config >>>
[ SpaceVim ] [11:20:27:600] [ Info  ] global_dir is: /home/crt@hamag-2011.local/.SpaceVim.d/
[ SpaceVim ] [11:20:27:600] [ Info  ] find global config: /home/crt@hamag-2011.local/.SpaceVim.d/init.toml
[ SpaceVim ] [11:20:27:600] [ Info  ] start to apply config [glob]
[ SpaceVim ] [11:20:27:601] [ Info  ] load layer:autocomplete
[ SpaceVim ] [11:20:27:601] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:601] [ Info  ] load layer:shell
[ SpaceVim ] [11:20:27:601] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:601] [ Info  ] load layer:cscope
[ SpaceVim ] [11:20:27:601] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:601] [ Info  ] load layer:ctrlspace
[ SpaceVim ] [11:20:27:601] [ Info  ] ctrlspace layer do not implement loadable function
[ SpaceVim ] [11:20:27:601] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:601] [ Info  ] load layer:debug
[ SpaceVim ] [11:20:27:602] [ Info  ] debug layer do not implement loadable function
[ SpaceVim ] [11:20:27:602] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:602] [ Info  ] load layer:fzf
[ SpaceVim ] [11:20:27:602] [ Info  ] fzf layer do not implement loadable function
[ SpaceVim ] [11:20:27:602] [ Info  ] fzf layer do not implement set_variable function
[ SpaceVim ] [11:20:27:602] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:602] [ Info  ] load layer:git
[ SpaceVim ] [11:20:27:602] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:602] [ Info  ] load layer:gtags
[ SpaceVim ] [11:20:27:602] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:602] [ Info  ] load layer:lang#asciidoc
[ SpaceVim ] [11:20:27:603] [ Info  ] lang#asciidoc layer do not implement loadable function
[ SpaceVim ] [11:20:27:603] [ Info  ] lang#asciidoc layer do not implement set_variable function
[ SpaceVim ] [11:20:27:603] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:603] [ Info  ] load layer:lang#c
[ SpaceVim ] [11:20:27:603] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:603] [ Info  ] load layer:lang#cmake
[ SpaceVim ] [11:20:27:603] [ Info  ] lang#cmake layer do not implement loadable function
[ SpaceVim ] [11:20:27:603] [ Info  ] lang#cmake layer do not implement set_variable function
[ SpaceVim ] [11:20:27:603] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:603] [ Info  ] load layer:lang#csharp
[ SpaceVim ] [11:20:27:603] [ Info  ] lang#csharp layer do not implement loadable function
[ SpaceVim ] [11:20:27:603] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:603] [ Info  ] load layer:lang#dockerfile
[ SpaceVim ] [11:20:27:603] [ Info  ] lang#dockerfile layer do not implement loadable function
[ SpaceVim ] [11:20:27:604] [ Info  ] lang#dockerfile layer do not implement set_variable function
[ SpaceVim ] [11:20:27:604] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:604] [ Info  ] load layer:lang#erlang
[ SpaceVim ] [11:20:27:604] [ Info  ] lang#erlang layer do not implement loadable function
[ SpaceVim ] [11:20:27:604] [ Info  ] lang#erlang layer do not implement set_variable function
[ SpaceVim ] [11:20:27:604] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:604] [ Info  ] load layer:lang#html
[ SpaceVim ] [11:20:27:604] [ Info  ] lang#html layer do not implement loadable function
[ SpaceVim ] [11:20:27:604] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:604] [ Info  ] load layer:lang#java
[ SpaceVim ] [11:20:27:604] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:604] [ Info  ] load layer:lang#javascript
[ SpaceVim ] [11:20:27:605] [ Info  ] lang#javascript layer do not implement loadable function
[ SpaceVim ] [11:20:27:605] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:605] [ Info  ] load layer:lang#json
[ SpaceVim ] [11:20:27:605] [ Info  ] lang#json layer do not implement loadable function
[ SpaceVim ] [11:20:27:605] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:605] [ Info  ] load layer:lang#kotlin
[ SpaceVim ] [11:20:27:605] [ Info  ] lang#kotlin layer do not implement loadable function
[ SpaceVim ] [11:20:27:605] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:605] [ Info  ] load layer:lang#markdown
[ SpaceVim ] [11:20:27:605] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:605] [ Info  ] load layer:lang#php
[ SpaceVim ] [11:20:27:605] [ Info  ] lang#php layer do not implement loadable function
[ SpaceVim ] [11:20:27:605] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:605] [ Info  ] load layer:lsp
[ SpaceVim ] [11:20:27:605] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:605] [ Info  ] load layer:lang#plantuml
 SpaceVim ] [11:20:27:606] [ Info  ] lang#plantuml layer do not implement loadable function
[ SpaceVim ] [11:20:27:606] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:606] [ Info  ] load layer:lang#powershell
[ SpaceVim ] [11:20:27:606] [ Info  ] lang#powershell layer do not implement loadable function
[ SpaceVim ] [11:20:27:606] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:606] [ Info  ] load layer:lang#rust
[ SpaceVim ] [11:20:27:606] [ Info  ] lang#rust layer do not implement loadable function
[ SpaceVim ] [11:20:27:606] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:606] [ Info  ] load layer:lang#toml
[ SpaceVim ] [11:20:27:606] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:606] [ Info  ] load layer:lang#vim
[ SpaceVim ] [11:20:27:607] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:607] [ Info  ] load layer:lang#vue
[ SpaceVim ] [11:20:27:607] [ Info  ] lang#vue layer do not implement loadable function
[ SpaceVim ] [11:20:27:607] [ Info  ] lang#vue layer do not implement set_variable function
[ SpaceVim ] [11:20:27:607] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:607] [ Info  ] load layer:lang#xml
[ SpaceVim ] [11:20:27:607] [ Info  ] lang#xml layer do not implement loadable function
[ SpaceVim ] [11:20:27:607] [ Info  ] lang#xml layer do not implement set_variable function
[ SpaceVim ] [11:20:27:607] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:607] [ Info  ] load layer:ssh
[ SpaceVim ] [11:20:27:607] [ Info  ] ssh layer do not implement loadable function
[ SpaceVim ] [11:20:27:607] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:607] [ Info  ] load layer:treesitter
[ SpaceVim ] [11:20:27:607] [ Info  ] treesitter layer do not implement set_variable function
[ SpaceVim ] [11:20:27:607] [ Info  ] layer loaded.
[ SpaceVim ] [11:20:27:608] [ Info  ] start loading local config >>>
[ SpaceVim ] [11:20:27:608] [ Info  ] Could not find project local config
[ SpaceVim ] [11:20:27:633] [ Info  ] core#statusline layer do not implement plugins function
[ SpaceVim ] [11:20:27:660] [ Info  ] ssh layer do not implement plugins function
[ SpaceVim ] [11:20:27:682] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [11:20:27:725] [ Info  ] lsp client: nvim built-in lsp
[ SpaceVim ] [11:20:27:731] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [11:20:27:743] [ Info  ] run root changed callback on VimEnter!
[  project ] [11:20:27:744] [ Info  ] Load projects cache from: /home/crt@hamag-2011.local/.cache/SpaceVim/projects.json
[  project ] [11:20:27:745] [ Info  ] switch to project:[libs]
[  project ] [11:20:27:745] [ Info  ]        rootdir is:/home/crt@hamag-2011.local/.SpaceVim/bundle/vim-javacomplete2/libs/
[ SpaceVim ] [11:20:27:808] [ Info  ] init default key bindings.
[ SpaceVim ] [11:20:27:809] [ Info  ] default key binding init done
[ SpaceVim ] [11:20:27:881] [ Info  ] CtrlSpace: no suitable grepping tool found
[ SpaceVim ] [11:20:27:881] [ Info  ] CtrlSpace: using Vim's globpath() to collect files
[ SpaceVim ] [11:20:27:881] [ Info  ] CtrlSpace: install rg or ag for faster file collection and .gitignore respect
[ SpaceVim ] [11:20:27:895] [ Info  ] lang#vue layer do not implement config function
[ SpaceVim ] [11:20:27:896] [ Info  ] treesitter layer do not implement config function
[  project ] [11:20:28:275] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [11:20:28:275] [ Info  ]         (.git/):/home/crt@hamag-2011.local/.SpaceVim/
[  project ] [11:20:28:277] [ Info  ] switch to project:[.SpaceVim]
[  project ] [11:20:28:277] [ Info  ]        rootdir is:/home/crt@hamag-2011.local/.SpaceVim/
[ SpaceVim ] [11:20:32:625] [ Info  ] CtrlSpace: no suitable grepping tool found
[ SpaceVim ] [11:20:32:625] [ Info  ] CtrlSpace: using Vim's globpath() to collect files
[ SpaceVim ] [11:20:32:625] [ Info  ] CtrlSpace: install rg or ag for faster file collection and .gitignore respect

```
</details>
