### ISSUE TITLE
Which-Key only work for the first time when I press <space>l

### ISSUE THREAD

**Issue by sdsaati** [wsdjeg/SpaceVim#4942]
### Expected behavior.

by pressing `<space>l` I expect to list all of the keys for the current python file. (but it's empty after canceling it for the first time)

### The reproduce ways from Vim starting.

If I press <space>l for the first time on a python file opened in a python project, it works correctly but if I cancel it (using esc key) and then try again (pressing <space>l) it doesn't work.
so in short: pressing <space>l only works for the first time, **unless I change the window and come back here again**

Images:
for the first time:
![image](https://github.com/user-attachments/assets/af638172-9d0a-4c58-b070-d3bd5cbb0307)
for the second time:
![image](https://github.com/user-attachments/assets/f0cb84b9-d4df-43b0-a10e-fd7f1723f64b)

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'nvim-cmp'
  autocomplete_parens = 1
  bootstrap_after = 'file#after'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = []
  data_dir = '/home/sdsaati/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'MonaSpiceNe Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/sdsaati/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'nvim-lspconfig-latest'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', 'pom.xml', 'build.gradle', 'package.json', 'pubspec.yaml', '.clang', 'Cargo.toml']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto-completion-delay=10
  auto_completion_tab_key_behavior='smart'
  auto_completion_return_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
  enable_scrollbar=1
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="fzf"
[[layers]]
  name="colorscheme"
[[layers]]
  name="tools#cpicker"
[[layers]]
  name="shell"
  default_position='top'
  default_height=30
[[layers]]
  name="git"
[[layers]]
  name="lang#python"
  format_on_save=1
  enable_typeinfo=1
  enabled_linters=['python', 'pylint']
[[layers]]
  name="lang#java"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#html"
[[layers]]
  name="lang#go"
[[layers]]
  name="lang#dart"
[[layers]]
  name="lang#csharp"
[[layers]]
  name="lang#cmake"
[[layers]]
  name="lang#c"
[[layers]]
  name="lang#kotlin"
[[layers]]
  name="lang#rust"
[[layers]]
  name="lang#toml"
[[layers]]
  name="lang#vim"
[[layers]]
  name="lang#vue"
[[layers]]
  name="lang#xml"
[[layers]]
  name="lang#php"
[[layers]]
  name="lang#plantuml"
[[layers]]
  name="framework#django"
[[layers]]
  name="lsp"
  enabled_clients=['pylsp']
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvim.arP1Hko/usr/bin/nvim)
version: NVIM v0.11.0-dev-1321+gfe1e2eff06
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 1]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: nvim(/tmp/.mount_nvim.arP1Hko/usr/bin/nvim)
version: NVIM v0.11.0-dev-1321+gfe1e2eff06
OS: linux
[shell, shellcmdflag, shellslash]: ['/usr/bin/fish', '-c', 1]
SpaceVim lua support check report:
Checking +lua:
      Failed : Known issue, neovim do not support lua now.
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, you need run `pip2 install neovim`
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `fzf`:ok
  - `colorscheme`:ok
  - `tools#cpicker`:ok
  - `shell`:ok
  - `git`:ok
  - `lang#python`:ok
  - `lang#java`:ok
  - `lang#javascript`:ok
  - `lang#latex`:ok
  - `lang#json`:ok
  - `lang#html`:ok
  - `lang#go`:ok
  - `lang#dart`:ok
  - `lang#csharp`:ok
  - `lang#cmake`:ok
  - `lang#c`:ok
  - `lang#kotlin`:ok
  - `lang#rust`:ok
  - `lang#toml`:ok
  - `lang#vim`:ok
  - `lang#vue`:ok
  - `lang#xml`:ok
  - `lang#php`:ok
  - `lang#plantuml`:ok
  - `framework#django`:ok
  - `lsp`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] [08:35:24:869] [ Info  ] Loading SpaceVim from: /home/sdsaati/.SpaceVim/
[ SpaceVim ] [08:35:24:869] [ Info  ] default rtp is:
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /home/sdsaati/.SpaceVim/
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /home/sdsaati/.config/nvim
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /home/sdsaati/.config/kdedefaults/nvim
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /etc/xdg/xdg-plasmax11/nvim
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /etc/xdg/nvim
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /home/sdsaati/.local/share/nvim/site
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /usr/share/plasmax11/nvim/site
[ SpaceVim ] [08:35:24:869] [ Info  ]   > /home/sdsaati/.local/share/flatpak/exports/share/nvim/site
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /var/lib/flatpak/exports/share/nvim/site
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /usr/local/share/nvim/site
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /usr/share/nvim/site
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /var/lib/snapd/desktop/nvim/site
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /tmp/.mount_nvim.arP1Hko/usr/share/nvim/runtime
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /tmp/.mount_nvim.arP1Hko/usr/lib/nvim
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /var/lib/snapd/desktop/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /usr/share/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /usr/local/share/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /var/lib/flatpak/exports/share/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /home/sdsaati/.local/share/flatpak/exports/share/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /usr/share/plasmax11/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /home/sdsaati/.local/share/nvim/site/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /etc/xdg/nvim/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /etc/xdg/xdg-plasmax11/nvim/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /home/sdsaati/.config/kdedefaults/nvim/after
[ SpaceVim ] [08:35:24:870] [ Info  ]   > /home/sdsaati/.config/nvim/after
[ SpaceVim ] [08:35:24:919] [ Info  ] v:argv is:['/tmp/.mount_nvim.arP1Hko/usr/bin/nvim', '--embed']
[ SpaceVim ] [08:35:24:919] [ Info  ] startup status:[0]
[ SpaceVim ] [08:35:24:919] [ Info  ] Startup with no argv, current dir is used: ~/Projects/main_projects/RiskManager/risk-manager
[ SpaceVim ] [08:35:24:919] [ Info  ] init default vim options
[ SpaceVim ] [08:35:24:919] [ Info  ] options init done
[ SpaceVim ] [08:35:24:920] [ Info  ] init default layer list.
[ SpaceVim ] [08:35:24:920] [ Info  ] load layer:autocomplete
[ SpaceVim ] [08:35:24:921] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:921] [ Info  ] load layer:checkers
[ SpaceVim ] [08:35:24:921] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:921] [ Info  ] load layer:format
[ SpaceVim ] [08:35:24:921] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:921] [ Info  ] load layer:edit
[ SpaceVim ] [08:35:24:923] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:923] [ Info  ] load layer:ui
[ SpaceVim ] [08:35:24:923] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:923] [ Info  ] load layer:core
[ SpaceVim ] [08:35:24:925] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:925] [ Info  ] load layer:core#banner
[ SpaceVim ] [08:35:24:925] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:925] [ Info  ] load layer:core#statusline
[ SpaceVim ] [08:35:24:925] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:925] [ Info  ] load layer:core#tabline
[ SpaceVim ] [08:35:24:925] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:925] [ Info  ] layer list init done
[ SpaceVim ] [08:35:24:926] [ Info  ] start loading global config >>>
[ SpaceVim ] [08:35:24:926] [ Info  ] global_dir is: /home/sdsaati/.SpaceVim.d/
[ SpaceVim ] [08:35:24:927] [ Info  ] find global config: /home/sdsaati/.SpaceVim.d/init.toml
[ SpaceVim ] [08:35:24:927] [ Info  ] start to apply config [glob]
[ SpaceVim ] [08:35:24:927] [ Info  ] load layer:fzf
[ SpaceVim ] [08:35:24:929] [ Info  ] fzf layer do not implement loadable function
[ SpaceVim ] [08:35:24:929] [ Info  ] fzf layer do not implement set_variable function
[ SpaceVim ] [08:35:24:929] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:929] [ Info  ] load layer:colorscheme
[ SpaceVim ] [08:35:24:929] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:930] [ Info  ] load layer:ui
[ SpaceVim ] [08:35:24:930] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:930] [ Info  ] load layer:tools#cpicker
[ SpaceVim ] [08:35:24:930] [ Info  ] tools#cpicker layer do not implement loadable function
[ SpaceVim ] [08:35:24:930] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:930] [ Info  ] load layer:autocomplete
[ SpaceVim ] [08:35:24:930] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:930] [ Info  ] load layer:shell
[ SpaceVim ] [08:35:24:930] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:930] [ Info  ] load layer:git
[ SpaceVim ] [08:35:24:931] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:931] [ Info  ] load layer:lang#python
[ SpaceVim ] [08:35:24:931] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:931] [ Info  ] load layer:lang#java
[ SpaceVim ] [08:35:24:931] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:931] [ Info  ] load layer:lang#javascript
[ SpaceVim ] [08:35:24:931] [ Info  ] lang#javascript layer do not implement loadable function
[ SpaceVim ] [08:35:24:931] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:931] [ Info  ] load layer:lang#latex
[ SpaceVim ] [08:35:24:932] [ Info  ] lang#latex layer do not implement loadable function
[ SpaceVim ] [08:35:24:932] [ Info  ] lang#latex layer do not implement set_variable function
[ SpaceVim ] [08:35:24:932] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:932] [ Info  ] load layer:lang#json
[ SpaceVim ] [08:35:24:932] [ Info  ] lang#json layer do not implement loadable function
[ SpaceVim ] [08:35:24:932] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:932] [ Info  ] load layer:lang#html
[ SpaceVim ] [08:35:24:932] [ Info  ] lang#html layer do not implement loadable function
[ SpaceVim ] [08:35:24:932] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:932] [ Info  ] load layer:lang#go
[ SpaceVim ] [08:35:24:932] [ Info  ] lang#go layer do not implement loadable function
[ SpaceVim ] [08:35:24:932] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:932] [ Info  ] load layer:lang#dart
[ SpaceVim ] [08:35:24:933] [ Info  ] lang#dart layer do not implement loadable function
[ SpaceVim ] [08:35:24:933] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:933] [ Info  ] load layer:lang#csharp
[ SpaceVim ] [08:35:24:933] [ Info  ] lang#csharp layer do not implement loadable function
[ SpaceVim ] [08:35:24:933] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:933] [ Info  ] load layer:lang#cmake
[ SpaceVim ] [08:35:24:933] [ Info  ] lang#cmake layer do not implement loadable function
[ SpaceVim ] [08:35:24:933] [ Info  ] lang#cmake layer do not implement set_variable function
[ SpaceVim ] [08:35:24:933] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:933] [ Info  ] load layer:lang#c
[ SpaceVim ] [08:35:24:934] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:934] [ Info  ] load layer:lang#kotlin
[ SpaceVim ] [08:35:24:934] [ Info  ] lang#kotlin layer do not implement loadable function
[ SpaceVim ] [08:35:24:934] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:934] [ Info  ] load layer:lang#rust
[ SpaceVim ] [08:35:24:934] [ Info  ] lang#rust layer do not implement loadable function
[ SpaceVim ] [08:35:24:934] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:934] [ Info  ] load layer:lang#toml
[ SpaceVim ] [08:35:24:934] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:935] [ Info  ] load layer:lang#vim
[ SpaceVim ] [08:35:24:935] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:935] [ Info  ] load layer:lang#vue
[ SpaceVim ] [08:35:24:935] [ Info  ] lang#vue layer do not implement loadable function
[ SpaceVim ] [08:35:24:935] [ Info  ] lang#vue layer do not implement set_variable function
[ SpaceVim ] [08:35:24:935] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:935] [ Info  ] load layer:lang#xml
[ SpaceVim ] [08:35:24:935] [ Info  ] lang#xml layer do not implement loadable function
[ SpaceVim ] [08:35:24:935] [ Info  ] lang#xml layer do not implement set_variable function
[ SpaceVim ] [08:35:24:935] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:935] [ Info  ] load layer:lang#php
[ SpaceVim ] [08:35:24:936] [ Info  ] lang#php layer do not implement loadable function
[ SpaceVim ] [08:35:24:936] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:936] [ Info  ] load layer:lang#plantuml
[ SpaceVim ] [08:35:24:936] [ Info  ] lang#plantuml layer do not implement loadable function
[ SpaceVim ] [08:35:24:936] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:936] [ Info  ] load layer:framework#django
[ SpaceVim ] [08:35:24:936] [ Info  ] framework#django layer do not implement loadable function
[ SpaceVim ] [08:35:24:936] [ Info  ] framework#django layer do not implement set_variable function
[ SpaceVim ] [08:35:24:936] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:936] [ Info  ] load layer:lsp
[ SpaceVim ] [08:35:24:936] [ Info  ] layer loaded.
[ SpaceVim ] [08:35:24:937] [ Info  ] start loading local config >>>
[ SpaceVim ] [08:35:24:937] [ Info  ] Could not find project local config
[ SpaceVim ] [08:35:25:190] [ Info  ] finished loading SpaceVim!
[ SpaceVim ] [08:35:25:278] [ Info  ] lsp client: nvim built-in lsp
[ SpaceVim ] [08:35:25:325] [ Info  ] try to open SpaceVim welcome page
[ SpaceVim ] [08:35:25:354] [ Info  ] run root changed callback on VimEnter!
[  project ] [08:35:25:356] [ Info  ] Load projects cache from: /home/sdsaati/.cache/SpaceVim/projects.json
[  project ] [08:35:25:356] [ Info  ] switch to project:[risk-manager]
[  project ] [08:35:25:356] [ Info  ]        rootdir is:/home/sdsaati/Projects/main_projects/RiskManager/risk-manager/
[ SpaceVim ] [08:35:25:371] [ Info  ] init default key bindings.
[ SpaceVim ] [08:35:25:372] [ Info  ] default key binding init done
[ SpaceVim ] [08:35:25:373] [ Info  ] SpaceVim server startup at:/tmp/spacevim_nvim_server
[ SpaceVim ] [08:35:25:438] [ Info  ] lang#vue layer do not implement config function
[ SpaceVim ] [08:35:25:439] [ Info  ] framework#django layer do not implement config function
[  project ] [08:35:25:872] [ Info  ] project_rooter_patterns option has been change, clear b:rootDir
[  project ] [08:35:25:872] [ Info  ]         (.git/):/home/sdsaati/Projects/main_projects/RiskManager/risk-manager/

```
</details>
