### ISSUE TITLE
Emmet plugin fails

### ISSUE THREAD

**Issue by jscolaire** [wsdjeg/SpaceVim#4944]
### Expected behavior.

HI, I Use emmet plugin enabled with html lang and it works only any times and another no. I test on vim 9.1 and nvim v0.9.5 both . I've found a pattern, in root directory or subdirectory emmet works but if subdirectory starts with _ (underscore) emmet doesn't work. The name of subdirectory is not optional because I'm developing with jekyll

### The reproduce ways from Vim starting.

<!DOCTYPE html>
<html lang="es">
  {% include head.html %}
  <body>
    <div class="container">
      <nav class="navbar has-text-centered">
        <div class="navbar-start"><a class="navbar-item" href="">Home</a></div>
      </nav>
      <div class="content">
        {{ content }}
      </div>
      .ui.container, #after <C-e>, to use emmet plugin
    </div>
  </body>
</html>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'deoplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'nord'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  custom_color_palette = []
  custom_plugins = [['Glench/Vim-Jinja2-Syntax', {'repo': 'Glench/Vim-Jinja2-Syntax', 'merged': 0, 'overwrite': 1}]]
  data_dir = '/home/ac/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = []
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 1
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 1
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 0
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 0
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = 'nerdtree'
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'SauceCodePro Nerd Font Mono:h11'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/ac/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'vim-dockerfile'
  project_auto_root = 0
  project_non_root = ''
  project_rooter_outermost = 1
  project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '.SpaceVim.d/']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 1
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQ
uickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_iseparator = 'arrow'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters']
  statusline_right = ['fileformat', 'cursorpos', 'percentage']
  statusline_separator = 'arrow'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0-dev'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = 's'
  windows_smartclose = 'q'
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="autocomplete"
  auto_completion_return_key_behavior='complete'
  auto_completion_tab_key_behavior='smart'
[[layers]]
  name="checkers"
[[layers]]
  name="format"
[[layers]]
  name="edit"
[[layers]]
  name="ui"
[[layers]]
  name="core"
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="lsp"
[[layers]]
  name="shell"
  default_position='bottom'
  default_height=30
[[layers]]
  name="fzf"
[[layers]]
  name="colorscheme"
[[layers]]
  name="gtags"
[[layers]]
  name="lang#sh"
[[layers]]
  name="lang#extra"
[[layers]]
  name="lang#html"
  emmet_filetyps=['html']
  emmet_leader_key='<C-e>'
[[layers]]
  name="lang#ruby"
[[layers]]
  name="lang#python"
[[layers]]
  name="git"
[[layers]]
  name="lang#dockerfile"
[[layers]]
  name="lepture/vim-jinja"
```
### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 901
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `autocomplete`:ok
  - `checkers`:ok
  - `format`:ok
  - `edit`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `lsp`:ok
  - `shell`:ok
  - `fzf`:ok
  - `colorscheme`:ok
  - `gtags`:ok
  - `lang#sh`:ok
  - `lang#extra`:ok
  - `lang#html`:ok
  - `lang#ruby`:ok
  - `lang#python`:ok
  - `git`:ok
  - `lang#dockerfile`:ok
  - `lepture/vim-jinja`: can not find function: SpaceVim#layers#lepture/vim-jinja#health()

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [12:00:25] [   0.001] [  Info ] Loading SpaceVim from: /home/ac/.SpaceVim/
[ SpaceVim ] [12:00:25] [   0.001] [  Info ] default rtp is:
[ SpaceVim ] [12:00:25] [   0.001] [  Info ]   > /home/ac/.SpaceVim/
[ SpaceVim ] [12:00:25] [   0.001] [  Info ]   > /usr/share/vim/vim91
[ SpaceVim ] [12:00:25] [   0.111] [ Error ] Can not set language to en_US.utf8
[ SpaceVim ] [12:00:25] [   0.111] [  Info ] v:argv is:['vim', '_layouts/default.html']
[ SpaceVim ] [12:00:25] [   0.111] [  Info ] startup status:[2, ['vim', '_layouts/default.html']]
[ SpaceVim ] [12:00:25] [   0.111] [  Info ] Startup with argv: 2
[ SpaceVim ] [12:00:25] [   0.112] [  Info ] init default layer list.
[ SpaceVim ] [12:00:25] [   0.112] [  Info ] load layer:autocomplete
[ SpaceVim ] [12:00:25] [   0.113] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.113] [  Info ] load layer:checkers
[ SpaceVim ] [12:00:25] [   0.113] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.113] [  Info ] load layer:format
[ SpaceVim ] [12:00:25] [   0.113] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.113] [  Info ] load layer:edit
[ SpaceVim ] [12:00:25] [   0.115] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.116] [  Info ] load layer:ui
[ SpaceVim ] [12:00:25] [   0.116] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.116] [  Info ] load layer:core
[ SpaceVim ] [12:00:25] [   0.117] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.117] [  Info ] load layer:core#banner
[ SpaceVim ] [12:00:25] [   0.117] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.117] [  Info ] load layer:core#statusline
[ SpaceVim ] [12:00:25] [   0.119] [  Info ] core#statusline layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.119] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.119] [  Info ] load layer:core#tabline
[ SpaceVim ] [12:00:25] [   0.120] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.120] [  Info ] layer list init done
[ SpaceVim ] [12:00:25] [   0.121] [  Info ] start loading global config >>>
[ SpaceVim ] [12:00:25] [   0.121] [  Info ] global_dir is: /home/ac/.SpaceVim.d/
[ SpaceVim ] [12:00:25] [   0.121] [  Info ] find global config: /home/ac/.SpaceVim.d/init.toml
[ SpaceVim ] [12:00:25] [   0.122] [  Info ] start to apply config [glob]
[ SpaceVim ] [12:00:25] [   0.122] [  Info ] load layer:autocomplete
[ SpaceVim ] [12:00:25] [   0.123] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.123] [  Info ] load layer:lsp
[ SpaceVim ] [12:00:25] [   0.123] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.123] [  Info ] load layer:shell
[ SpaceVim ] [12:00:25] [   0.124] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.124] [  Info ] load layer:fzf
[ SpaceVim ] [12:00:25] [   0.124] [  Info ] fzf layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.124] [  Info ] fzf layer do not implement set_variable function
[ SpaceVim ] [12:00:25] [   0.124] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.124] [  Info ] load layer:colorscheme
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] load layer:gtags
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] load layer:lang#sh
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] load layer:lang#extra
[ SpaceVim ] [12:00:25] [   0.125] [  Info ] lang#extra layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] lang#extra layer do not implement set_variable function
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] load layer:lang#html
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] lang#html layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] load layer:lang#ruby
[ SpaceVim ] [12:00:25] [   0.126] [  Info ] lang#ruby layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.127] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.127] [  Info ] load layer:lang#python
[ SpaceVim ] [12:00:25] [   0.127] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.127] [  Info ] load layer:git
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] load layer:ui
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] load layer:gtags
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] load layer:lang#dockerfile
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] load layer:lang#dockerfile
[ SpaceVim ] [12:00:25] [   0.128] [  Info ] lang#dockerfile layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.129] [  Info ] lang#dockerfile layer do not implement set_variable function
[ SpaceVim ] [12:00:25] [   0.129] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.129] [  Info ] load layer:lepture/vim-jinja
[ SpaceVim ] [12:00:25] [   0.129] [  Info ] lepture/vim-jinja layer do not implement loadable function
[ SpaceVim ] [12:00:25] [   0.129] [  Info ] lepture/vim-jinja layer do not implement set_variable function
[ SpaceVim ] [12:00:25] [   0.129] [  Info ] layer loaded.
[ SpaceVim ] [12:00:25] [   0.130] [  Info ] start loading local config >>>
[ SpaceVim ] [12:00:25] [   0.130] [  Info ] Could not find project local config
[ SpaceVim ] [12:00:25] [   0.176] [  Info ] core#statusline layer do not implement plugins function
[ SpaceVim ] [12:00:25] [   0.202] [  Info ] lepture/vim-jinja layer do not implement plugins function
[ SpaceVim ] [12:00:25] [   0.242] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [12:00:25] [   0.311] [  Info ] lsp client: vim-lsp
[ SpaceVim ] [12:00:25] [   0.464] [  Info ] run root changed callback on VimEnter!
[   rooter ] [12:00:25] [   0.465] [  Info ] Load projects cache from: /home/ac/.cache/SpaceVim/projects.json
[ SpaceVim ] [12:00:25] [   0.544] [  Warn ] gtags is not executable, the gtags database will not be updated automatically

[ SpaceVim ] [12:00:25] [   0.544] [  Info ] lang#extra layer do not implement config function
[ SpaceVim ] [12:00:25] [   0.550] [  Info ] lepture/vim-jinja layer do not implement config function
[ SpaceVim ] [12:00:25] [   0.552] [  Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [12:00:25] [   0.575] [  Info ] init default key bindings.
[ SpaceVim ] [12:00:25] [   0.577] [  Info ] default key binding init done
[ SpaceVim ] [12:01:04] [  39.105] [  Warn ] gtags is not executable, the gtags database will not be updated automatically

```
</details>

**Comment by jscolaire** [comment]
I'm sorry. I see what is error. Emmet fails in jinja templates no underscore directories named, how do I enable this kind of files? Fails with vim 9.1 and works with neovim 0.95

**Comment by wsdjeg** [comment]
- `emmet_filetyps`: Set the filetypes for enabling emmet

  ```toml
  [[layers]]
    name = "lang#html"
    emmet_leader_key = "<C-e>"
    emmet_filetyps = ['html']
  ```

add your filetype to filetype list.
