### ISSUE TITLE
E121: Undefined variable: g:_spacevim_statusline_fileformat

### ISSUE THREAD

**Issue by OnkV** [wsdjeg/SpaceVim#4945]
### Expected behavior.

No error message

### The reproduce ways from Vim starting.

I'm using Vim 9.0 from Debian stable (patches: 1-1378, 1499).
SpaceVim 2.3.0 works fine.

To reproduce open an empty buffer or file, split the window (`:split`).

### Output of the `:SPDebugInfo!`

<details><summary> SpaceVim debug information </summary>

### SpaceVim options :

```toml
  auto_disable_touchpad = 1
  autocomplete_method = 'asyncomplete'
  autocomplete_parens = 1
  bootstrap_after = 'myspacevim#after'
  bootstrap_before = 'myspacevim#before'
  buffer_index_type = 4
  checkinstall = 1
  code_runner_focus = 0
  colorscheme = 'simpleblack'
  colorscheme_bg = 'dark'
  colorscheme_default = 'desert'
  commandline_prompt = '>'
  conceallevel = 0
  custom_color_palette = []
  custom_plugins = [['jpalardy/vim-slime', {'repo': 'jpalardy/vim-slime', 'overwrite': 1}], ['vimoutliner/vimoutliner', {'repo': 'vimoutliner/vimoutliner', 'overwrite': 1}], ['jamessan/vim-gnupg', {'repo': 'jamessan/vim-gnupg', 'overwrite': 1}], ['vifm/vifm.vim', {'repo': 'vifm/vifm.vim', 'overwrite': 1}], ['nvie/vim-flake8', {'repo': 'nvie/vim-flake8', 'overwrite': 1}], ['itspriddle/vim-shellcheck', {'repo': 'itspriddle/vim-shellcheck', 'overwrite': 1}], ['vim-scripts/tracwiki', {'repo': 'vim-scripts/tracwiki', 'overwrite': 1}], ['sheerun/vim-polyglot', {'repo': 'sheerun/vim-polyglot', 'overwrite': 1}], ['ocaml/vim-ocaml', {'repo': 'ocaml/vim-ocaml', 'overwrite': 1}], ['zaid/vim-rec', {'repo': 'zaid/vim-rec', 'overwrite': 1}], ['lucasprag/simpleblack', {'repo': 'lucasprag/simpleblack', 'overwrite': 1}]]
  data_dir = '/home/andi/.cache/'
  debug_level = 1
  default_custom_leader = '<Space>'
  default_indent = 2
  disabled_plugins = ['jplus.vim']
  enable_bepo_layout = 0
  enable_cursorcolumn = 0
  enable_cursorline = 1
  enable_debug = 0
  enable_googlesuggest = 0
  enable_guicolors = 0
  enable_javacomplete2_py = 0
  enable_key_frequency = 0
  enable_language_specific_leader = 0
  enable_list_mode = 0
  enable_neocomplcache = 0
  enable_os_fileformat_icon = 0
  enable_powerline_fonts = 1
  enable_projects_cache = 1
  enable_statusline_bfpath = 0
  enable_statusline_mode = 1
  enable_statusline_tag = 1
  enable_tabline_filetype_icon = 1
  enable_tabline_ft_icon = 0
  enable_vimfiler_welcome = 1
  enable_ycm = 0
  error_symbol = '✖'
  escape_key_binding = 'jk'
  expand_tab = 1
  file_searching_tools = []
  filemanager = ''
  filetree_direction = 'right'
  filetype_icons = {}
  force_global_config = 0
  gitcommit_issue_icon = ''
  gitcommit_pr_icon = ''
  github_username = ''
  guifont = 'Courier Code 13'
  hiddenfileinfo = 1
  home_files_number = 6
  hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
  if_ruby = 1
  info_symbol = 'ⓘ'
  keep_server_alive = 1
  language = ''
  lazy_conf_timeout = 200
  leader_guide_default_group_name = ''
  leader_guide_flatten = 1
  leader_guide_hspace = 5
  leader_guide_max_size = 0
  leader_guide_position = 'botright'
  leader_guide_run_map_on_popup = 1
  leader_guide_sort_horizontal = 0
  leader_guide_submode_mappings = {'<C-C>': 'win_close'}
  leader_guide_theme = 'leaderguide'
  leader_guide_vertical = 0
  lint_engine = 'neomake'
  lint_on_save = 1
  lint_on_the_fly = 0
  max_column = 120
  plugin_bundle_dir = '/home/andi/.cache/vimfiles/'
  plugin_manager = 'dein'
  plugin_manager_processes = 16
  plugin_name = 'emmet-vim'
  project_auto_root = 1
  project_non_root = ''
  project_rooter_outermost = 0
  project_rooter_patterns = ['.svn/', '.git/', '.hg/', '_darcs/', '.bzr/', 'package.json', 'package.json']
  projects_cache_num = 20
  realtime_leader_guide = 1
  relativenumber = 0
  search_tools = ['rg', 'ag', 'pt', 'ack', 'grep', 'findstr', 'git']
  sidebar_direction = ''
  sidebar_width = 30
  smartcloseignoreft = ['tagbar', 'neo-tree', 'vimfiler', 'defx', 'NvimTree', 'SpaceVimRunner', 'SpaceVimREPL', 'SpaceVimQuickFix', 'HelpDescribe', 'VebuggerShell', 'VebuggerTerminal', 'SpaceVimTabsManager', 'SpaceVimGitRemoteManager']
  smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
  snippet_engine = 'neosnippet'
  src_root = 'E:\sources\'
  statusline_inactive_separator = 'bar'
  statusline_iseparator = 'bar'
  statusline_left = ['winnr', 'filename', 'major mode', 'search count', 'syntax checking', 'minor mode lighters', 'vcs', 'hunks', 'vcs', 'hunks']
  statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters']
  statusline_right = ['cursorpos', 'percentage']
  statusline_separator = 'nil'
  statusline_unicode = 1
  terminal_cursor_shape = 2
  todo_close_list = 0
  todo_labels = ['fixme', 'question', 'todo', 'idea']
  todo_prefix = '@'
  update_retry_cnt = 3
  version = '2.4.0'
  vim_help_language = 'en'
  vimcompatible = 0
  warning_symbol = '⚠'
  wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store,*.svg'
  windisk_encoding = 'cp936'
  windows_index_type = 3
  windows_leader = ''
  windows_smartclose = ''
  wrap_line = 0
```

### SpaceVim layers :

```toml
[[layers]]
  name="checkers"
  show_cursor_error=0
  lint_on_save=1
  lint_on_the_fly=0
[[layers]]
  name="format"
[[layers]]
  name="ui"
[[layers]]
  name="core"
  filetree_show_hidden=0
  enable_smooth_scrolling=0
[[layers]]
  name="core#banner"
[[layers]]
  name="core#statusline"
[[layers]]
  name="core#tabline"
[[layers]]
  name="shell"
  default_shell='terminal'
  default_position='top'
  default_height=30
[[layers]]
  name="lang#python"
  python_interpreter='/usr/bin/python3'
  python_file_head=['#!/usr/bin/env python3', '# -*- coding: utf-8 -*-', '', '']
  enabled_linters=['python', 'pylint']
[[layers]]
  name="VersionControl"
[[layers]]
  name="lang#sql"
[[layers]]
  name="ctrlp"
[[layers]]
  name="git"
[[layers]]
  name="sh"
[[layers]]
  name="framework#django"
[[layers]]
  name="lang#graphql"
[[layers]]
  name="lang#haskell"
[[layers]]
  name="lang#json"
[[layers]]
  name="lang#latex"
[[layers]]
  name="lang#javascript"
[[layers]]
  name="lang#html"
```

### SpaceVim Health checking :

SpaceVim clipboard support check report:
Checking +clipboard:
      SUCCEED!
SpaceVim environment check report:
Current progpath: vim(/usr/bin/vim.gtk3)
version: 900
OS: linux
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
SpaceVim lua support check report:
Checking +lua:
      SUCCEED!
SpaceVim python support check report:
Checking +python3:
      SUCCEED!
Checking +python:
      Failed : to support +python, Please install vim-gtk, or build from sources.
Checking SpaceVim layer health:
  - `checkers`:ok
  - `format`:ok
  - `ui`:ok
  - `core`:ok
  - `core#banner`:ok
  - `core#statusline`:ok
  - `core#tabline`:ok
  - `shell`:ok
  - `lang#python`:ok
  - `VersionControl`:ok
  - `lang#sql`:ok
  - `ctrlp`:ok
  - `git`:ok
  - `sh`: can not find function: SpaceVim#layers#sh#health()
  - `framework#django`:ok
  - `lang#graphql`:ok
  - `lang#haskell`:ok
  - `lang#json`:ok
  - `lang#latex`:ok
  - `lang#javascript`:ok
  - `lang#html`:ok

### SpaceVim runtime log :

```log
[ SpaceVim ] : logger file  does not exists, only log for current process will be shown!
[ SpaceVim ] [13:36:20] [   0.000] [  Info ] Loading SpaceVim from: /home/andi/.SpaceVim/
[ SpaceVim ] [13:36:20] [   0.000] [  Info ] default rtp is:
[ SpaceVim ] [13:36:20] [   0.000] [  Info ]   > /home/andi/.SpaceVim/
[ SpaceVim ] [13:36:20] [   0.000] [  Info ]   > /usr/share/vim/vim90
[ SpaceVim ] [13:36:20] [   0.014] [  Info ] v:argv is:['vim']
[ SpaceVim ] [13:36:20] [   0.014] [  Info ] startup status:[0]
[ SpaceVim ] [13:36:20] [   0.014] [  Info ] Startup with no argv, current dir is used: ~
[ SpaceVim ] [13:36:20] [   0.015] [  Info ] init default layer list.
[ SpaceVim ] [13:36:20] [   0.015] [  Info ] load layer:autocomplete
[ SpaceVim ] [13:36:20] [   0.015] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.015] [  Info ] load layer:checkers
[ SpaceVim ] [13:36:20] [   0.015] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.015] [  Info ] load layer:format
[ SpaceVim ] [13:36:20] [   0.016] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.016] [  Info ] load layer:edit
[ SpaceVim ] [13:36:20] [   0.017] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.017] [  Info ] load layer:ui
[ SpaceVim ] [13:36:20] [   0.017] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.017] [  Info ] load layer:core
[ SpaceVim ] [13:36:20] [   0.018] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.018] [  Info ] load layer:core#banner
[ SpaceVim ] [13:36:20] [   0.018] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.018] [  Info ] load layer:core#statusline
[ SpaceVim ] [13:36:20] [   0.019] [  Info ] core#statusline layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.019] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.019] [  Info ] load layer:core#tabline
[ SpaceVim ] [13:36:20] [   0.019] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.019] [  Info ] layer list init done
[ SpaceVim ] [13:36:20] [   0.020] [  Info ] start loading global config >>>
[ SpaceVim ] [13:36:20] [   0.020] [  Info ] global_dir is: /home/andi/.SpaceVim.d/
[ SpaceVim ] [13:36:20] [   0.020] [  Info ] find global config: /home/andi/.SpaceVim.d/init.toml
[ SpaceVim ] [13:36:20] [   0.020] [  Info ] start to apply config [glob]
[   rooter ] [13:36:20] [   0.021] [  Info ] Load projects cache from: /home/andi/.cache/SpaceVim/projects.json
[   rooter ] [13:36:20] [   0.021] [  Info ] Start to find root for: /home/andi/
[   rooter ] [13:36:20] [   0.022] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [13:36:20] [   0.022] [  Info ] Start to find root for: /home/andi/
[ SpaceVim ] [13:36:20] [   0.022] [  Info ] load layer:core
[ SpaceVim ] [13:36:20] [   0.022] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.022] [  Info ] load layer:shell
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] load layer:lang#python
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] load layer:VersionControl
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] load layer:lang#sql
[ SpaceVim ] [13:36:20] [   0.023] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] load layer:ctrlp
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] ctrlp layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] ctrlp layer do not implement set_variable function
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] load layer:git
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] load layer:sh
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] sh layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] sh layer do not implement set_variable function
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] load layer:checkers
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] load layer:ui
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] load layer:framework#django
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] framework#django layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] framework#django layer do not implement set_variable function
[ SpaceVim ] [13:36:20] [   0.024] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:lang#graphql
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#graphql layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#graphql layer do not implement set_variable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:core#statusline
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] core#statusline layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:lang#haskell
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#haskell layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#haskell layer do not implement set_variable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:lang#json
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#json layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:lang#latex
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#latex layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#latex layer do not implement set_variable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:lang#javascript
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] lang#javascript layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.025] [  Info ] load layer:lang#html
[ SpaceVim ] [13:36:20] [   0.026] [  Info ] lang#html layer do not implement loadable function
[ SpaceVim ] [13:36:20] [   0.026] [  Info ] layer loaded.
[ SpaceVim ] [13:36:20] [   0.049] [  Info ] current directory is $HOME, skip local config
[ SpaceVim ] [13:36:20] [   0.065] [  Info ] core#statusline layer do not implement plugins function
[ SpaceVim ] [13:36:20] [   0.074] [  Info ] sh layer do not implement plugins function
[ SpaceVim ] [13:36:20] [   0.114] [  Info ] finished loading SpaceVim!
[ SpaceVim ] [13:36:20] [   0.122] [  Info ] lsp client: vim-lsp
[   rooter ] [13:36:20] [   0.123] [  Info ] Start to find root for: /home/andi/
[ SpaceVim ] [13:36:20] [   0.125] [  Info ] try to open SpaceVim welcome page
[   rooter ] [13:36:20] [   0.134] [  Info ] Start to find root for: /home/andi/
[ SpaceVim ] [13:36:20] [   0.137] [  Info ] run root changed callback on VimEnter!
[ SpaceVim ] [13:36:20] [   0.267] [  Info ] SpaceVim server startup at:/tmp/spacevim_vim_server
[ SpaceVim ] [13:36:20] [   0.281] [  Info ] init default key bindings.
[ SpaceVim ] [13:36:20] [   0.281] [  Info ] default key binding init done
[ SpaceVim ] [13:36:20] [   0.331] [  Info ] sh layer do not implement config function
[ SpaceVim ] [13:36:20] [   0.331] [  Info ] framework#django layer do not implement config function
[ SpaceVim ] [13:36:20] [   0.331] [  Info ] lang#graphql layer do not implement config function
[   rooter ] [13:36:22] [   1.983] [  Info ] project_rooter_patterns option has been change, clear b:rootDir
[   rooter ] [13:36:22] [   1.984] [  Info ] Start to find root for: /home/andi/
[ SpaceVim ] [13:39:01] [ 160.978] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [13:39:01] [ 160.978] [  Info ] statusline build-in section hunks has been changed!
[ SpaceVim ] [13:40:03] [ 223.212] [  Info ] statusline build-in section vcs has been changed!
[ SpaceVim ] [13:40:03] [ 223.212] [  Info ] statusline build-in section hunks has been changed!
```
</details>
